### ISSUE TITLE
How to open desktop sharing

### ISSUE THREAD

**Issue by x157123** [jitsi/docker-jitsi-meet#1]
How to open desktop sharing, modify docker-jitsi-meet/web/rootfs/defaults/config.js is invalid

**Comment by saghul** [comment]
What do you want to change in config.js ? What is invalid? What browser / device are you testing?

**Comment by x157123** [comment]
Browser：google Chrome
// The ID of the jidesha extension for Chrome.
desktopSharingChromeExtId: null,
// Whether desktop sharing should be disabled on Chrome.
desktopSharingChromeDisabled: false
 
Change desktopSharingChromeDisabled is false.
The google Chrome does not display the share button.

**Comment by x157123** [comment]
Browser：google Chrome
// The ID of the jidesha extension for Chrome.
desktopSharingChromeExtId: 'hdhdjxhesusjjjsjjdjs',
// Whether desktop sharing should be disabled on Chrome.
desktopSharingChromeDisabled: false

Change desktopSharingChromeDisabled is false.
The google Chrome does not display the share button.

**Comment by saghul** [comment]
Gotcha. You need to edit the generated config.js file. It will be in CONFIG/meet/config.js, so if you configured CONFIG to be /opt/jitsi-meet, it will be in /opt/jitsi-meet/meet/config.js.

Then restart the container and it should work.

**Comment by jmereaux** [comment]
Hi,

Desktop sharing on chrome does not work for me.

This is what I put in the config.js file:
```
desktopSharingChromeExtId: 'kglhbbefdnlheedjiejgomgmfplipfeb',
desktopSharingChromeDisabled: false,
```

When in a conf, the share button shows up.
But when I click on it, regardless whether the extension has been installed or not, the browser asks to install the Jitsi extension (and properly redirects to the Jitsi extension page on the chrome web store)

**Comment by x157123** [comment]
1、'kglhbbefdnlheedjiejgomgmfplipfeb' is chrome plugin ID.
2、Chrome plugin manifest.json file matches attributes is you domain name.
      [https://github.com/jitsi/jidesha/tree/master/chrome](url)
Ｍy Setting
`
desktopSharingChromeExtId: 'lekeplmbddljllhjmcojcmmoikfnibdg',
desktopSharingChromeDisabled: false,
`
 'lekeplmbddljllhjmcojcmmoikfnibdg' is My Chrome Plugin ID.

My chrome plugin manifest.json setting
`"matches": [
          "*://www.x157123.xyz/*","*://x157123.xyz/*"
      ]`


Ｍy Demo[www.x157123.xyz](url)

**Comment by jmereaux** [comment]
The chrome extension ID you provided targets your own extension and not the standard Jitsi meet one.
Are you saying that I have to write my custom Chrome plugin?

**Comment by saghul** [comment]
@jmereaux yes, you do. Just fork jidesha and update the config with the extension ID you are given. This is a Chrome limitation, which they will be lifting sometime soon.

**Comment by jmereaux** [comment]
Got it! thanks to you both
