### ISSUE TITLE
Commit 953a4d2 has broken jitsi

### ISSUE THREAD

**Issue by a1lu** [jitsi/docker-jitsi-meet#1002]
Hi,
I am up to date with origin/master but if I remove JICOFO_COMPONENT_SECRET from my .env file (as happened in 953a4d2) the prosody and jicofo container are in a restart loop with
```
FATAL ERROR: Jicofo component secret and auth password must be set
```

docker image ls:
```
jitsi/jicofo        latest              d3ba0fe4aee5        8 weeks ago         288MB
jitsi/web           latest              4bedc7454b5d        8 weeks ago         244MB
jitsi/prosody       latest              708c00202a84        8 weeks ago         119MB
jitsi/jvb           latest              7016d33ab417        2 months ago        291MB
```

I already cleared my configs directory and restarted docker-compose.
Any hints how to fix this?
thanks

**Comment by prayagsingh** [comment]
You have to build your own docker images to use the main(master) repository. Go to `docker-jitsi-meet` directory and execute **`FORCE_REBUILD=1 JITSI_RELEASE=unstable JITSI_REPO=a1lu make`** command. Then use `a1lu/web:latest` image in `docker-compose.yaml` file. You can control which image to build from [here](https://github.com/jitsi/docker-jitsi-meet/blob/1fa5048510059323678a25c5e52f4c7bad3b5099/Makefile#L5)

**Comment by a1lu** [comment]
Ah, ok thanks.
