### ISSUE TITLE
Jicofo docker image out of sync with current config files

### ISSUE THREAD

**Issue by mmgutsche** [jitsi/docker-jitsi-meet#1006]
Hi, 

I just noticed that the current   [jicofo docker image is 2 months old](https://hub.docker.com/r/jitsi/jicofo) and there have been modifications to the authentication env files. This leads to authentication issues when starting via docker-compose up.

**Comment by xsxavier** [comment]
Ahh, that's why. I've been having issues with this. Like 'Jicofo component secret and auth password must be set' even when I added them manually in the .env. 
Do you have a temporary manual solution perhaps? Which variables need to be added?

**Comment by saghul** [comment]
You shouldn't be using the compose file from master with a release. Use the compose file in a release, which ties the images together.

master works with unstable images which you need to build yourself.

**Comment by mmgutsche** [comment]
Since a lot of stuff started breaking, I reverted to the following tag: stable-5142. Probably not needed to go back to last October, but it worked for me.

**Comment by saghul** [comment]
stable-5930-3 should work just fine.

**Comment by xsxavier** [comment]
My bad, I've been blindly cloning https://github.com/jitsi/docker-jitsi-meet not realising these weren't the stable releases....

**Comment by mmgutsche** [comment]
Maybe it would help a lot of people to just mention that the master branch should not be cloned and used.

**Comment by saghul** [comment]
I have updated the handbook: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker
