### ISSUE TITLE
[question] did I need a reverse proxy for the videobridge?

### ISSUE THREAD

**Issue by Lukas1818** [jitsi/docker-jitsi-meet#1015]
Because I already run a web server on my machine I can not give Jitsi access to port 443 and 80.
Instead I using caddy as a reverse proxy to the http port of the Nginx container.
But according to the [Network description](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-manual#network-description) the videobridge has two port expose too.

**Did I need an second  reverse proxy for this ports?**

How are these encrypted?

**Comment by saghul** [comment]
We need to update that, yikes.

The JVB also listens for WebSocket traffic, but it's proxied from the web container.

So all you need to do in your reverse proxy (other than the usual) is WS proxy the /xmpp-websocket and /colibri-ws routes.

**Comment by Lukas1818** [comment]
Thanks for the info.

Does that mean that is not needed to expose the port to the host, like the docker-compose does do it?:
https://github.com/jitsi/docker-jitsi-meet/blob/0cbe0d9801942dd693a94eac7fb7ca6468ce371b/docker-compose.yml#L228-L230

**Comment by saghul** [comment]
Those are the media ports that need to be exposed too, yes. I thought you were asking specifically from an HTTP reverse proxy perspective.

**Comment by Lukas1818** [comment]
tkanks

**Comment by Lukas1818** [comment]
> Those are the media ports that need to be exposed too, yes. I thought you were asking specifically from an HTTP reverse proxy perspective.

I only would like to know if the tunneling the Nginx container through ssl is the only think I have to do, to make the communication with jitsi encrypted.
Did I need to pass the ssl certificate to some container?

**Comment by saghul** [comment]
> Did I need to pass the ssl certificate to some container?

No.
