### ISSUE TITLE
p2p get enable automatic after disable

### ISSUE THREAD

**Issue by Lukas1818** [jitsi/docker-jitsi-meet#1016]
I have try to disable the p2p feature in the `/web/config.js` file, but it will be set to true if I restart the container.

I have try the folowing thinks
* set  `p2p: { enabled: true,`  to false in  `/web/config.js`
* add `ENABLE_P2P=0` to the `.env` file
* change `ENABLE_P2P` in the docker-compose to `ENABLE_P2P=0`
* remove `ENABLE_P2P` from `.env` and docker-compose

None of this does work.

Edit:
Other settings in `config.d/web/config.js`, which doe not even have an env-varaible does change back too.

**Comment by saghul** [comment]
What version of the images  are you using?

**Comment by Lukas1818** [comment]
jitsi/web:stable-5390-3
It is the verison of the latest release

**Comment by saghul** [comment]
Note that the first part of the file is the defaults, check further down to see if it's overridden.

**Comment by Lukas1818** [comment]
I did not notify that the first part of the file are only the default values.
I check the file again and found this:
```
// Peer-to-Peer options.
//

if (!config.hasOwnProperty('p2p')) config.p2p = {};

config.p2p.enabled = false;
```
So it seems the setting in the `.env`  does work.


But how can I change setting, which does not exist in the `.env` or the docker-compose, as example `startWithVideoMuted`?
The `config.d/web/config.js` seems to be overwrite at the container start.
So the `config.startWithVideoMuted =  true;` which I did add to the bottom of the file will be overwrite.
I found for this special value a workaround https://github.com/jitsi/jitsi-meet/issues/8144#issuecomment-812789147 but it looks like very inelegant.

**Comment by saghul** [comment]
We don't have env variables for all config options yet. Feel free to open a PR with the ones you need. #8144 is orthogonal.

**Comment by Lukas1818** [comment]
> We don't have env variables for all config options yet. Feel free to open a PR with the ones you need. #8144 is orthogonal.

I have done the PR:
https://github.com/jitsi/docker-jitsi-meet/pull/1021/files

**Comment by saghul** [comment]
Landed, cheers!
