### ISSUE TITLE
Can't log in  when  LDAP authentication is enabled

### ISSUE THREAD

**Issue by nigangkaka** [jitsi/docker-jitsi-meet#102]
Hi :

I am new to the JITSI.  I have been following the instructions  here https://github.com/jitsi/docker-jitsi-meet/blob/dev/README.md#authentication-using-ldap

and configured with my owner LDAP server.  But I can't log in .

 It shows "
![image](https://user-images.githubusercontent.com/13623477/59247828-37ed8d00-8c53-11e9-9e49-d7a20e4d2704.png)

The below is my workable LDAP settings for Gitlab 

> gitlab_rails['ldap_servers'] = {
'main' => {
  'label' => 'demo LDAP',
  'host' =>  '192.168.1.1',
  'port' => 389,
  'uid' => 'sAMAccountName',
  'encryption' => 'plain',
  'verify_certificates' => true,
  'bind_dn' => 'CN=demo_albd,CN=users,DC=demo,DC=com',
  'password' => 'fakepassword',
  'active_directory' => false,
  'base' => 'DC=demo,DC=com',
  'group_base' => 'OU=demo,DC=demo,DC=com',
  'admin_group' => 'Global Admins'
  }
}

Here is the settings for jitsi:

> LDAP_URL=ldap://192.168.1.1
LDAP_BASE=DC=demo,DC=com
LDAP_BINDDN=CN=demo_albd,CN=users,DC=demo,DC=com
LDAP_BINDPW=fakepassword
LDAP_FILTER=(sAMAccountName=%u)
LDAP_AUTH_METHOD=bind

Could anybody give some advice on how to fix this? 

BTW:
Where can I get the error logs for the LDAP authentication fails?

**Comment by saghul** [comment]
@netaskd any idea?

**Comment by netaskd** [comment]
Hi there,
1. Try to make auth test inside the prosody container:
```
testsaslauthd -u username -p password
```
2. if it works, try to enable prosody debug and try to auth.

**Comment by nigangkaka** [comment]
@netaskd 

Thans for your reply.

There is no `testsaslauthd`  inside prosody container.

After installing  sasl2-bin by `apt-get update && apt-get install sasl2-bin`  , run the test command `testsaslauthd -u username -p password`

The result:

> connect() : No such file or directory
0:

**Comment by netaskd** [comment]
@nigangkaka, it means that you use containers builded not from dev branch.

**Comment by nigangkaka** [comment]
@netaskd 

After checked out the `dev` branch and run `sudo make` to build the latest docker images. 

I can login to the LDAP successfully .  

Thanks for your help
