### ISSUE TITLE
wrong default value?

### ISSUE THREAD

**Issue by Lukas1818** [jitsi/docker-jitsi-meet#1020]
If it right that the default value is `false`?
It is not casting to `true`, because it is unequal to `0`?

https://github.com/jitsi/docker-jitsi-meet/blob/0cbe0d9801942dd693a94eac7fb7ca6468ce371b/web/rootfs/defaults/settings-config.js#L37

**Comment by saghul** [comment]
The `toBool` operator is smart and can parse that: https://github.com/subchen/frep/blob/0547af438b6e18049c16459e6d4b02ca4197370c/func.go#L120-L134
