### ISSUE TITLE
Up to date jitsi version

### ISSUE THREAD

**Issue by kim366** [jitsi/docker-jitsi-meet#103]
We are using a local Jitsi instance in Docker with this repo and the version does not seem to match the one at meet.jit.si. The external_api.js is quite different and this repo version misses functions like `isDeviceChangeAvailable`.

Is it possible to get the version which is used in the public Jitsi instance? What has to be done to get it?

Thanks for the help!

**Comment by saghul** [comment]
We plan to release it sometime this week. Note that you can build the container images yourself with the included `Makefile`.

**Comment by kim366** [comment]
I see, thank you for the quick response!
