### ISSUE TITLE
Important config files are always overwritten

### ISSUE THREAD

**Issue by suuchan** [jitsi/docker-jitsi-meet#1034]
Some config files such as _web/config.js_ or _prosody/config/conf.d/jitsi-meet.cfg.lua_ are always overwritten by  default templates built into the containers when the containers start. 

I for instance need to change these two files to make use of our TURN server. The only way to work around this is to start the containers once, make changes to the files and do a 'chattr +i'. 

It would be more helpful if these defaults would also be written once to $CONFIG, only if not present yet. Then the containers should use these for templating and it would be possible to make manual changes more easily.

**Comment by saghul** [comment]
We started there, and we are not going back sorry. It didn't work well. Everyone was confused because that's not the usual / native way to do configs in containers.

If we are lacking configurability, we can add more env vars. TURN evn vars have come up on occasion, but nobody has sent us  PR yet.

**Comment by suuchan** [comment]
Jitsi is very configurable and if you have env vars for every tiny knob it will be a lot of work. I just hat to turn off the experimental features because E2E encryption does not work right yet. I could only do this via manual change _web/config.js_.

How about this then. Most config files are actually code that sets variables, at least the ones that I had to touch. Variables can be overwritten later. If for instance you could add something like _WEB_CONFIG_CUSTOM_ to the environment that would expand to a one line java script code at the end of  _web/config.js_, then all the changes can at least be packed into a javascript one-liner. Same goes for lua code. 

I can make you a PR for that if you tell me it would have a chance.

**Comment by saghul** [comment]
>  I just hat to turn off the experimental features because E2E encryption does not work right yet.

What doesn't work right yet? What version of the images did you test?

> How about this then. Most config files are actually code that sets variables, at least the ones that I had to touch. Variables can be overwritten later. If for instance you could add something like WEB_CONFIG_CUSTOM to the environment that would expand to a one line java script code at the end of web/config.js, then all the changes can at least be packed into a javascript one-liner. 

That already exists: https://github.com/jitsi/docker-jitsi-meet/blob/6f52f71b0d3ab4f7aa8c22427a6d4f2b513e554e/web/rootfs/etc/cont-init.d/10-config#L81

For TURN in Prosody I'd like to see env vars.

**Comment by suuchan** [comment]
> > I just hat to turn off the experimental features because E2E encryption does not work right yet.
> 
> What doesn't work right yet? What version of the images did you test?

stable-5765-1. We subjectively found that the stream stability was less reliable. Once on you cannot turn it off anymore for a room when people are still in. It gets turned on automatically if another participant has it on.
 
> > How about this then. Most config files are actually code that sets variables, at least the ones that I had to touch. Variables can be overwritten later. If for instance you could add something like WEB_CONFIG_CUSTOM to the environment that would expand to a one line java script code at the end of web/config.js, then all the changes can at least be packed into a javascript one-liner.
> 
> That already exists:
> 
> https://github.com/jitsi/docker-jitsi-meet/blob/6f52f71b0d3ab4f7aa8c22427a6d4f2b513e554e/web/rootfs/etc/cont-init.d/10-config#L81

Cool, didn't notice this was there. Thanks for pointing this out. For prosody I now see that I can create any new file in _prosody/config/conf.d/_.

**Comment by saghul** [comment]
> We subjectively found that the stream stability was less reliable.

Can you elaborate? There is nothing inherent to E2EE (other than a bit of overhead) that would yield quality problems.



> Once on you cannot turn it off anymore for a room when people are still in. It gets turned on automatically if another participant has it on.

I cannot reproduce this. When a participant turns it off it's turned off for them. What we did add in the last release is that if a participant turns it on, it automatically turns it on for everyone. But turning it off is still possible, though every participant needs to do it by themselves.

**Comment by suuchan** [comment]
> > We subjectively found that the stream stability was less reliable.
> 
> Can you elaborate? There is nothing inherent to E2EE (other than a bit of overhead) that would yield quality problems.

As I said, it was subjective. 

As soon as the comment about this being experimental vanishes from the config we will enable it.

> > Once on you cannot turn it off anymore for a room when people are still in. It gets turned on automatically if another participant has it on.
> 
> I cannot reproduce this. When a participant turns it off it's turned off for them. What we did add in the last release is that if a participant turns it on, it automatically turns it on for everyone. But turning it off is still possible, though every participant needs to do it by themselves.

That did not work for a five people meeting we held, even if we turned it of and closed the dialog all at the same time. We had to switch to a new room 

We will try again with the next update.
