### ISSUE TITLE
TOKEN_AUTH_UR no longer working (no redirect)

### ISSUE THREAD

**Issue by d3473r** [jitsi/docker-jitsi-meet#1044]
Hi,

i just pulled the changes and the latest images, deleted the config folder and started the containers.
Now the `TOKEN_AUTH_UR` is no longer working. Instead of redirecting jitsi now shows:
<img width="333" alt="2021-05-12 09_54_41-Test _ Jitsi Meet" src="https://user-images.githubusercontent.com/10356892/117939171-1b0ed800-b308-11eb-8d8b-42d140de7172.png">

**Comment by saghul** [comment]
Can you try the unstable images?

**Comment by d3473r** [comment]
With the `unstable` images the redirect is working again :)
Thank you!

**Comment by saghul** [comment]
Thanks for checking!
