### ISSUE TITLE
Jibri build not working - Chrome version 78 not available anymore

### ISSUE THREAD

**Issue by pandel** [jitsi/docker-jitsi-meet#1045]
Hello!

Currently building the Jibri container does not work, because Chrom version 78.0.3904.97 is not available anymore at Google DL site. I tried everything but am always getting a 404. Perhaps you should use a newer version.

Regards
Holger

**Comment by pandel** [comment]
For now I use this repo: http://mirror.cs.uchicago.edu/google-chrome/pool/main/g/google-chrome-stable/

**Comment by saghul** [comment]
We have a plan: a `base-url` config option will be added to jibri (per xmpp environment), so we'll configure that and jibri will open PUBLIC_URL instead of "meet.jitsi". This will allow us to use the latest Chrome because certificates will no longer be an issue.

**Comment by pandel** [comment]
Ah, I see! Seeing forward to this :-)! Many thanks for the info.

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/docker-jitsi-meet/pull/1046 - Unstable builds are working now. I am planning to make a stable release later today.
