### ISSUE TITLE
Prosody security advisory 2021-05-12

### ISSUE THREAD

**Issue by lorenzbausch** [jitsi/docker-jitsi-meet#1047]
Prosody recently published a [security advisory](https://prosody.im/security/advisory_20210512/) and also a new version 0.11.9 addressing those security vulnerabilities.
Is  Jitsi Meet on Docker affected by this security advisory?

**Comment by saghul** [comment]
The release that went out ~20 minutes ago (https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-5870) has 0.11.9.

**Comment by lorenzbausch** [comment]
that was fast, thanks @saghul!

**Comment by L3o-pold** [comment]
@saghul should we add mitigation as recommended in the document https://prosody.im/security/advisory_20210512/ in the default prosody configuration?

**Comment by prayagsingh** [comment]
@L3o-pold In the advice section, they are saying that either upgrade to 0.11.9 or apply the  above config. I think they have added all these in 0.11.9 by default. 

**Snippet** 

```
Advice

All public deployments should upgrade to 0.11.9 or apply the above configuration changes.

```

**Comment by L3o-pold** [comment]
@prayagsingh yeah but they also said:

> By default Prosody does not enable any rate limits. However we recommend enabling them for all production and public deployments to ensure fair consumption of resources across all connections.

**Comment by prayagsingh** [comment]
@saghul WDYT?

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/docker-jitsi-meet/pull/1072
