### ISSUE TITLE
Jitsi stable-5870 forces screen sharing to an unreadable low resolution of 414x232

### ISSUE THREAD

**Issue by cedricroijakkers** [jitsi/docker-jitsi-meet#1048]
I've just upgraded Jitsi to the latest release of stable-5870. Eveything is working fine, except that screen sharing sessions have an extremely low resolution.

Video is clear, but screen sharing uses a resolution of 414x232 with a bitrate of 82Kbits, making it totally unreadable.

Rolling back to stable-5765-1 instantly fixes this issue, no configuration changes were made.

**Comment by jallamsetty1** [comment]
Can you please share your config.js settings related to screensharing -  `desktopSharingFrameRate` and `testing.capScreenshareBitrate`

**Comment by cedricroijakkers** [comment]
Here is what is currently present in the web container:

```
config.desktopSharingFrameRate = { min: 5, max: 30 };
```

and

```
config.testing.capScreenshareBitrate = 1;
```

I did not change any environment variables with respect to this, so these must be the default values in the containers.

**Comment by jallamsetty1** [comment]
Can you also provide information about your codec preference settings on the client ?

**Comment by cedricroijakkers** [comment]
As for codecs, I've only enabled H264, since I'm getting really bad image quality with screen sharing, and therefore set multicast to off.
