### ISSUE TITLE
blurring background / background picture is slower since stable-5765-1

### ISSUE THREAD

**Issue by JacBra** [jitsi/docker-jitsi-meet#1056]
Hi,

In stable-5765-1 I was surprised by the nice working of blurring of the background / using a background picture.
However, in stable-5870 this has been 'enhanced' but now it isn't working smooth anymore. What was changed?
Is there something I can do about this?

Best regards,

Jacco

**Comment by saghul** [comment]
You may need to enable WASM SIMD: https://v8.dev/features/simd you can do so in chrome://flags or apply for the origin trial for your domain.

**Comment by JacBra** [comment]
thanks!
