### ISSUE TITLE
Prosody throwing  "warn Component not connected, bouncing error for: ... "

### ISSUE THREAD

**Issue by zarator99** [jitsi/docker-jitsi-meet#1060]
Hi all,

I have a Jitsi meet implementation with the Docker solution installed on Red Hat 8 and when I start a meeting, the Docker Prosody container is throwing the following error

`warn Component not connected, bounce error for: <iq type = 'set' from='740dc073-0d76-422b-990a-8d6d48fbebd6@jitsi.example.com/KbIiDJRG 'to =' focus.jitsi.example.org 'id = '63d53b39-1a05-411e-975e-ebcec940f515: sendIQ'>
`
Another problem that I am facing is that Prosody rewrite the configuration file to default when i change some of configuration parameters.

Can anyone help me understand what is the problem ?
Note: I am using the tag "stable-5390-3" of Docker Repository

**Comment by HeBuDuMkA-83** [comment]
solution can be found here https://community.jitsi.org/t/cant-create-meeting-room-keep-reconnecting-and-showing-focus-error/91827
