### ISSUE TITLE
Jitsi Meet no audio/video external users

### ISSUE THREAD

**Issue by furky1905** [jitsi/docker-jitsi-meet#1061]
Hi, I deployed Jitsi Meet with HashiCorp Nomad (+ Traefik). I'm having some trouble when connecting from an external network. You can see audio/video when connected to the internal network but not when you connect from an external network.

What you see internal:
![afbeelding](https://user-images.githubusercontent.com/24234531/119509363-e0c62180-bd70-11eb-8ec3-fde93a48694e.png)
What you see external:
![afbeelding](https://user-images.githubusercontent.com/24234531/119509566-0b17df00-bd71-11eb-9afc-25119c433f3c.png)

external client console logs: [consoleLogs.txt](https://github.com/jitsi/docker-jitsi-meet/files/6539799/consoleLogs.txt)

Any help is appreciated.

**Comment by damencho** [comment]
This is a network issue. either jvb is not advertising its public address https://github.com/jitsi/docker-jitsi-meet/blob/db3d790e52a741f9ce4316a058fbafc7e30e98b2/jvb/rootfs/defaults/sip-communicator.properties#L3
Or you haven't forward port udp 10000 to jvb checkout https://jitsi.org/qi advanced section for more details for ports used.

**Comment by furky1905** [comment]
> 
> 
> This is a network issue. either jvb is not advertising its public address
> 
> https://github.com/jitsi/docker-jitsi-meet/blob/db3d790e52a741f9ce4316a058fbafc7e30e98b2/jvb/rootfs/defaults/sip-communicator.properties#L3
> 
> Or you haven't forward port udp 10000 to jvb checkout https://jitsi.org/qi advanced section for more details for ports used.

sip-communicator
``` 
org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=172.17.0.24
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=192.168.xx.xx  <-- is this supposed to be 95.xx.xx.xx ?
```
jvb logs
```
May 26, 2021 9:20:23 AM org.ice4j.ice.harvest.StunMappingCandidateHarvester discover
INFO: Discovered public address 95.xx.xx.xx:49957/udp from STUN server 193.122.56.141:443/udp using local address 172.17.0.24:0/udp
```

**Comment by damencho** [comment]
> NAT_HARVESTER_PUBLIC_ADDRESS=192.168.xx.xx

Yes, that needs to be the public address, as this is definitely not reachable from the clients.

**Comment by furky1905** [comment]
> 
> 
> > NAT_HARVESTER_PUBLIC_ADDRESS=192.168.xx.xx
> 
> Yes, that needs to be the public address, as this is definitely not reachable from the clients.

After changing it, meetings with more than 2 people no longer work.
sip-communicator:
```
org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=172.17.0.25
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=95.xx.xx.xx
```
I'm getting errors in the browser console.
![errors](https://user-images.githubusercontent.com/24234531/119668813-c905a080-be37-11eb-9a15-4a80b2227038.png)

I was reading about STUN and TURN servers here: https://community.jitsi.org/t/using-stun-turn-server-and-why/95623/2
I'm using the STUN server `JVB_STUN_SERVERS=meet-jit-si-turnrelay.jitsi.net:443`
Is it also necessary to have a TURN server?

**Comment by damencho** [comment]
> ```
> org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=95.xx.xx.xx
> ```

Have you handled the firewall and port forwarding ?

And you have errors with the websockets which is a different issue.

**Comment by bgrozev** [comment]
Note that with jitsi-videobridge master you can specify multiple static mappings in jvb.conf like this:
```
ice4j.harvest.mapping.static-mappings = [
{
  localAddress = 172.17.0.25
  publicAddress = 95.xx.xx.xx
},
{
  localAddress = 172.17.0.25
  publicAddress = 192.168.xx.xx
}
]
```
