### ISSUE TITLE
get/generate secret key, iss

### ISSUE THREAD

**Issue by Lukas1818** [jitsi/docker-jitsi-meet#1073]
I have set up a workadventure instance and would like to use my own already running jitsi instance instead of the official.
Because my jitsi instance need a login before it can be used, I must give workadventure access to jitsi, by giving it a key.
Sadly I do not know how I can generate/get the key.

from the workadenture [`.env` template](https://github.com/thecodingmachine/workadventure/blob/bcc86d6041a136e832ff82e56c6bbc80df779b5c/contrib/docker/.env.prod.template#L5):
```yml
JITSI_URL=meet.jit.si
# If your Jitsi environment has authentication set up, you MUST set JITSI_PRIVATE_MODE to "true" and you MUST pass a SECRET_JITSI_KEY to generate the JWT secret
JITSI_PRIVATE_MODE=false
JITSI_ISS=  
SECRET_JITSI_KEY=
```
I also do not know what a `JITSI_ISS` is.

**Comment by saghul** [comment]
You’ll need to ask workadventure, they are using those variables, not us.
