### ISSUE TITLE
Make jitsi to use only ports 80/443 

### ISSUE THREAD

**Issue by mghadam** [jitsi/docker-jitsi-meet#1076]
I am trying to make jitsi to use tcp ports 80/443 only. 

I have a nginx web server running on my server and I am using proxy-pass to send traffic to jit.si `HTTP_PORT`/`HTTPS_PORT` ports running on the same server. 

However, it is not possible to proxy-pass the traffic for the JVB_TCP port as jitsi-docker directly uses the this port specified in the .env file in meetings.

It would be great if we can rewrite the JVB_TCP URL to use a custom URL, such as a specific hostname e.g. `https://jvb.dom.com`  or even the same domain name with a path e.g. `https://dom.com/jvb/` . This way, it will be possible to manually proxy-pass the traffic coming to this custom URL to `JVB_TCP_PORT` running on the server, and run jitsi with ports 80/443 only which would be compatible with strict firewalls.

**Comment by saghul** [comment]
The JVB traffic is not HTTP traffic, you can’t proxy-pass it.
