### ISSUE TITLE
ports, letsencrypt and a script error

### ISSUE THREAD

**Issue by mricim** [jitsi/docker-jitsi-meet#1077]
[I have followed this manual](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#running-behind-nat-or-on-a-lan-environment)

As it does not work, I decide to look at the logs of the dockers:
`root@test:/home/tester/docker-jitsi-meet# docker logs --tail 50 3aa72adc59eb`

```
[cont-init.d] 10-config: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-set-timezone: executing...
[cont-init.d] 01-set-timezone: exited 0.
[cont-init.d] 10-config: executing...
/opt /
[Fri Jun 18 09:35:09 CEST 2021] Installing to /config/acme.sh
[Fri Jun 18 09:35:09 CEST 2021] Installed to /config/acme.sh/acme.sh
[Fri Jun 18 09:35:09 CEST 2021] Installing alias to '/root/.profile'
[Fri Jun 18 09:35:09 CEST 2021] OK, Close and reopen your terminal to start using acme.sh
[Fri Jun 18 09:35:09 CEST 2021] Installing cron job
13 0 * * * "/config/acme.sh"/acme.sh --cron --home "/config/acme.sh" > /dev/null
[Fri Jun 18 09:35:09 CEST 2021] Good, bash is found, so change the shebang to use bash as preferred.
[Fri Jun 18 09:35:09 CEST 2021] OK
/
[Fri Jun 18 09:35:09 CEST 2021] Using ACME_DIRECTORY: https://acme-staging-v02.api.letsencrypt.org/directory
[Fri Jun 18 09:35:10 CEST 2021] Using CA: https://acme-staging-v02.api.letsencrypt.org/directory
[Fri Jun 18 09:35:10 CEST 2021] Run pre hook:'if [[ -f /var/run/s6/services/nginx ]]; then s6-svc -d /var/run/s6/services/nginx; fi'
[Fri Jun 18 09:35:10 CEST 2021] Standalone mode.
[Fri Jun 18 09:35:10 CEST 2021] Single domain='domain.example'
[Fri Jun 18 09:35:10 CEST 2021] Getting domain auth token for each domain
[Fri Jun 18 09:35:13 CEST 2021] Getting webroot for domain='domain.example'
[Fri Jun 18 09:35:13 CEST 2021] Verifying: domain.example
[Fri Jun 18 09:35:13 CEST 2021] Standalone mode server
[Fri Jun 18 09:35:18 CEST 2021] domain.example:Verify error:Fetching http://domain.example/.well-known/acme-challenge/XXKEYXX: Connection refused
[Fri Jun 18 09:35:18 CEST 2021] Please add '--debug' or '--log' to check more details.
[Fri Jun 18 09:35:18 CEST 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Fri Jun 18 09:35:18 CEST 2021] Run post hook:'if [[ -f /var/run/s6/services/nginx ]]; then s6-svc -u /var/run/s6/services/nginx; fi'
Failed to obtain a certificate from the Let's Encrypt CA.
```
You can see that letsencrypt failed. 
`domain.example:Verify error:Fetching http://domain.example/.well-known/acme-challenge/XXKEYXX: Connection refused`
The url is missing the port (:8000)
`http://domain.example:8000/.well-known/acme-challenge/XXKEYXX`
By doing it manual it works. But when I connect through the browser, it returns the message that the certificate is not valid

My solution was to change in the ".env" port 8000 for 80 and 8443 for 443. When I connect using "http://" (it also happens with localhost) it does not resolve, but when I connect with "https:// "works, but giving the certificate error

I wanted to use a proxy, but I am having a hard time making it work by itself, without a proxy.

**Comment by mricim** [comment]
Yesterday I was testing this on another server and when I connected (now) it turns out that the certificate works

**Comment by saghul** [comment]
The builtin let’s encrypt integration works o ku on the standard ports (80, 443). If are going to run this setup behind a proxy that proxy should take care of the TLS certificates.

**Comment by mricim** [comment]
> The builtin let’s encrypt integration works o ku on the standard ports (80, 443). If are going to run this setup behind a proxy that proxy should take care of the TLS certificates.

Thanks for the prompt response. But it does not solve the problem I describe.
(Let's forget for a moment what I said about the proxy and focus on the rest of the topics)

I will try to put it another way:

- Both in the documentation and in the zip there is a configuration that does not work or does not work as expected
  - Having to wait 24 hours for the certificate to work is strange
  - In the configuration comes "https://domain.example" but for it to work I must leave it in "domain.example"
  - In the configuration comes port 8000 and 8443, but if I don't use localhost I have to change them and that is not mentioned anywhere

If it should work like this, it would be good if the documentation indicates it

**Comment by saghul** [comment]
The port requirements are documented in the handbook: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#lets-encrypt-configuration

Not sure what you mean with the 24h, I don’t know where that comes from.

What setting is incorrectly quoted? Also, what docker-compose version are you using? They have changed the quoting behavior.

**Comment by mricim** [comment]
I do not think it is necessary to mention the issues one by one so that you realize that this list of points is repetitive on many occasions and that this occurs due to lack of information in the documentation.  I give you a simple example: In the quick guide it tells you to add the jibri to the docker-compose file and configure the return, but that alone does not work.  So either the documentation is missing information or something is wrong.
And do not tell me now that you do not have several issues where the same thing that I explained here arises

Don't take this as a bad thing, it's just constructive criticism.

I have set up several jitsi servers, with plugins, without, with doker, virtualized, etc.  I think that adding these annotations in the documentation would improve it and I also think that when someone creates an issue it is to detail the problem, and investigate what the causes were and explain what the solutions were applied and even and if necessary modify the code and / or the documentation to try to prevent that from happening again.
Example: in my first text I explained what the problem was, how I identified it and what solution applies (I made sure by doing this process several times that this solution always fixes it).
You answered this saying that it was correct and closed the issue, without stopping to think that what I was exposing was the reason why there are more than 10 issues that indicate the same thing that I summarized to all those who want to use jitsi docker in a future and find the same problems that I encountered


About the 24 o'clock, the documentation indicates that it may take a few minutes for the certificate to work, but it is not noticed anywhere that if a wrong certificate was loaded for any of the reasons described above, it may happen that the caches are left with the first certificate and that you have to clean them, in case you don't it will be several hours before you see the real results of your changes.  Surely they do not explain this in the documentation since you assume that we are all aware of this, when this is not the case
