### ISSUE TITLE
Self-hosted Jitsi-docker server with authentication

### ISSUE THREAD

**Issue by CaosFR** [jitsi/docker-jitsi-meet#1081]
Hi

I have jitsi-docker and I need to active the authentification for my foundry-docker serveur.
According to this two url (https://dev.to/noandrea/self-hosted-jitsi-server-with-authentication-ie7 / https://vtta.io/articles/installing-a-self-hosted-jitsi-server) I have to modify my jitsi configuration like that :  

1 - Enable Cross-Origin Resource Sharing (CORS).
Ok done, I have find and modify the nginx config in ./web/rootfs/defaults/meet.conf
$ nano ./web/rootfs/defaults/meet.conf
```
# BOSH
location = /http-bind {
    proxy_pass {{ .Env.XMPP_BOSH_URL_BASE }}/http-bind;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header Host {{ .Env.XMPP_DOMAIN }};
    add_header 'Access-Control-Allow-Origin' '_';
    add_header 'Access-Control-Allow-Credentials' 'true';
    add_header 'Access-Control-Allow-Methods' 'GET,HEAD,OPTIONS,POST,PUT';
    add_header 'Access-Control-Allow-Headers' 'Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers';
}
```

2- Enable authentication for Jitsi.
Enabling the authentication requires only to edit three files:
- /etc/jitsi/meet/apeunit.test-config.js
- /etc/prosody/conf.avail/apeunit.test.cfg.lua
- /etc/jitsi/jicofo/sip-communicator.properties

Big fail :) I dont find this repertory or files in the host or inside running containers.
Can someone help me ?
Thanks !

**Comment by saghul** [comment]
You don’t seem to be using Docker, right? In that case the best to ask would be our community.

**Comment by CaosFR** [comment]
I'm using Docker and this "docker-jitsi-meet". I dont understand what you mean.
