### ISSUE TITLE
Custom web build crashes

### ISSUE THREAD

**Issue by juanludlf** [jitsi/docker-jitsi-meet#1086]
Hi,

I'd like to use docker-jitsi-meet with a customized web service. I've cloned https://github.com/jitsi/docker-jitsi-meet. It works fine using the cloud image (jitsi/web:latest) but building a custom image (`JITSI_RELEASE=unstable FORCE_REBUILD=1 JITSI_SERVICES=web make`) results in a broken container. No error traces appear in the make command output. I run `docker-compose up` as normally, but the container crashes with the following information:

```
web_1      | exited 0.
web_1      | [fix-attrs.d] applying ownership & permissions fixes...
web_1      | [fix-attrs.d] done.
web_1      | [cont-init.d] executing container initialization scripts...
web_1      | [cont-init.d] 01-set-timezone: executing...
web_1      | [cont-init.d] 01-set-timezone: exited 0.
web_1      | [cont-init.d] 10-config: executing...
: No such file or directorynable to exec bash
web_1      | [cont-init.d] 10-config: exited 127.
web_1      | [cont-finish.d] executing container finish scripts...
web_1      | [cont-finish.d] done.
web_1      | [s6-finish] waiting for services.
web_1      | [s6-finish] sending all processes the TERM signal.
jvb_1      | Jul 07, 2021 12:54:09 PM org.jitsi.utils.logging2.LoggerImpl log
jvb_1      | INFO: Performed a successful health check in PT0S. Sticky failure: false
web_1      | [s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by prayagsingh** [comment]
> web_1      | [cont-init.d] 10-config: executing...
> : No such file or directorynable to exec bash

This is the issue with your custom build. Re-check the changes again.
