### ISSUE TITLE
Failed to create prosody users

### ISSUE THREAD

**Issue by arnuschky** [jitsi/docker-jitsi-meet#109]
I'd like to use auth. However, I fail to create prosody users:

```
$ prosodyctl --config /config/prosody.cfg.lua register user myuser meet.jitsi mypassword
The given hostname does not exist in the config
```

Any ideas?

PS: the docs are wrong, I needed `docker exec -it jitsi_prosody_1 /bin/bash` to get into the container

**Comment by arnuschky** [comment]
FYI, `http_default_host` in `/config/conf.d/jitsi-meet.cfg.lua` is set to `"meet.jitsi"`. Didn't change anything.

**Comment by sapkra** [comment]
I think you have to use the xmpp **auth** hostname:
```bash
prosodyctl --config /config/prosody.cfg.lua register user myuser auth.meet.jitsi mypassword
```

FYI: I've added `http_default_host` because my server is communicating with a prosody plugin without any hostname just with the IP and port. I don't wanted to proxy the connection so I've just added this fallback. I think it's not important for your problem.

**Comment by arnuschky** [comment]
Doesn't work for me, gives me the same error.

I didn't set anything special in the configfiles; certainly no hostname. The host setting above is the default.

**Comment by arnuschky** [comment]
Figured it out after following prosody docs here https://prosody.im/doc/creating_accounts. Command is:

`prosodyctl --config /config/prosody.cfg.lua adduser myuser@meet.jitsi`

Command then asks for password.

**Comment by saghul** [comment]
PR landed in `dev`, closing.

**Comment by hugokoopmans** [comment]
still not fixed in the docs ...
and suggested fix seems not the soluton
root@2752fd24aae8:/# prosodyctl --config /config/prosody.cfg.lua adduser hugo@meet.jitsi         
Enter new password: 
Retype new password: 
creating-user-failed

**Comment by hugokoopmans** [comment]
hmmm this still gives issues : 

prosodyctl --config /config/prosody.cfg.lua adduser hugo@meet.xxx.yy
The host 'meet.xxx.yy' is not listed in the configuration file (or is not enabled).
The user will not be able to log in until this is changed.

**Comment by hugokoopmans** [comment]
with default XMPP host:

prosodyctl --config /config/prosody.cfg.lua adduser hugo@meet.jitsi  
Enter new password: 
Retype new password: 
creating-user-failed

**Comment by h-109** [comment]
@hugokoopmans just restart the containers.
`docker-compose down` then
`docker-compose up -d`

Now check the prosody container id:
`docker exec -it <ID> /bin/bash`
`prosodyctl --config /config/prosody.cfg.lua register user DesiredUserName meet.jitsi DesiredPassword`
`exit`

That is it.

**Comment by oDinZu** [comment]
I received the same error today.

`sudo prosodyctl register odinzu meet.domin.example`

Error Creating user failed

**Comment by saghul** [comment]
Are you running that on docker?

**Comment by lakevetch** [comment]
> I received the same error today.
> 
> `sudo prosodyctl register odinzu meet.domin.example`
> 
> Error Creating user failed

I am receiving a similar error when attempting to create a user in the Prosody container 

`docker compose exec prosody /bin/bash
prosodyctl --config /config/prosody.cfg.lua register TheDesiredUsername meet.jitsi TheDesiredPassword
Error: Creating user failed`

**Comment by lakevetch** [comment]
I am taking the above action in accordance with the Docker self-hosting guide section regarding internal authentication

**Comment by saghul** [comment]
Weird, do you see any errors in the container logs?

Did you change the XMPP domain in your config?

**Comment by lakevetch** [comment]
Thanks for the reply. Have not checked container logs. I'm unfamiliar with where to find them. How can I best do that?

**Comment by lakevetch** [comment]
> Did you change the XMPP domain in your config?

I have not changed the domain.

**Comment by saghul** [comment]
> Thanks for the reply. Have not checked container logs. I'm unfamiliar with where to find them. How can I best do that?

You can do `docker compose logs prosody`

**Comment by lakevetch** [comment]
Thank you! Nothing shows up in the log when I attempt the user creation. The last entries are all from my most recent test conference a few days ago.

**Comment by lakevetch** [comment]
Still confirming that all did indeed work, but it would appear that modifying the above command to the following avoids the error.
`prosodyctl --config /config/prosody.cfg.lua register TheDesired Username **auth**.meet.jitsi TheDesiredPassword`

**Comment by saghul** [comment]
Hum, that's odd. Can you share the generated prosody config files?

**Comment by lakevetch** [comment]
Yes I can. I have just been testing to see if after the updated 'auth.meet.jitsi' version of the command works, however it doesn't seem to recognize the user/password combo. Will share the current logs below.

**Comment by lakevetch** [comment]
`prosody-1  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
prosody-1  | [s6-init] ensuring user provided files have correct perms...exited 0.
prosody-1  | [fix-attrs.d] applying ownership & permissions fixes...
prosody-1  | [fix-attrs.d] done.
prosody-1  | [cont-init.d] executing container initialization scripts...
prosody-1  | [cont-init.d] 01-set-timezone: executing... 
prosody-1  | [cont-init.d] 01-set-timezone: exited 0.
prosody-1  | [cont-init.d] 10-config: executing... 
prosody-1  | Adding user `prosody' to group `sasl' ...
prosody-1  | Adding user prosody to group sasl
prosody-1  | Done.
prosody-1  | mkdir: cannot create directory '/config/certs': File exists
prosody-1  | Prosody normal mode, using default config
prosody-1  | [cont-init.d] 10-config: exited 0.
prosody-1  | [cont-init.d] done.
prosody-1  | [services.d] starting services
prosody-1  | mv: cannot stat '/config/data/*.crt': No such file or directory
prosody-1  | mv: cannot stat '/config/data/*.key': No such file or directory
prosody-1  | saslauthd[249] :num_procs  : 5
prosody-1  | saslauthd[249] :mech_option: /etc/saslauthd.conf
prosody-1  | saslauthd[249] :run_path   : /var/run/saslauthd
prosody-1  | saslauthd[249] :auth_mech  : ldap
prosody-1  | saslauthd[249] :mmaped shared memory segment on file: /var/run/saslauthd/cache.mmap
prosody-1  | saslauthd[249] :bucket size: 96 bytes
prosody-1  | saslauthd[249] :stats size : 36 bytes
prosody-1  | saslauthd[249] :timeout    : 28800 seconds
prosody-1  | saslauthd[249] :cache table: 985828 total bytes
prosody-1  | saslauthd[249] :cache table: 1711 slots
prosody-1  | saslauthd[249] :cache table: 10266 buckets
prosody-1  | saslauthd[249] :flock file opened at /var/run/saslauthd/cache.flock
prosody-1  | saslauthd[249] :using accept lock file: /var/run/saslauthd/mux.accept
prosody-1  | saslauthd[249] :master pid is: 0
prosody-1  | saslauthd[249] :listening on socket: /var/run/saslauthd/mux
prosody-1  | saslauthd[249] :using process model
prosody-1  | saslauthd[249] :forked child: 259
prosody-1  | saslauthd[249] :forked child: 260
prosody-1  | saslauthd[249] :forked child: 261
prosody-1  | saslauthd[249] :forked child: 262
prosody-1  | saslauthd[249] :acquired accept lock
prosody-1  | 2024-04-24 20:57:54 startup             info       Hello and welcome to Prosody version 0.12.4
prosody-1  | [services.d] done.
prosody-1  | 2024-04-24 20:57:54 startup             info       Prosody is using the epoll backend for connection handling
prosody-1  | 2024-04-24 20:57:54 conferenceduration.meet.jitsi:conference_duration_component  info	Starting conference duration timer for muc.meet.jitsi
prosody-1  | 2024-04-24 20:57:54 conferenceduration.meet.jitsi:conference_duration_component  info	No host/component found, will wait for it: muc.meet.jitsi
prosody-1  | 2024-04-24 20:57:54 conferenceduration.meet.jitsi:tls                            info	Certificates loaded
prosody-1  | 2024-04-24 20:57:54 focus.meet.jitsi:tls                                         info	Certificates loaded
prosody-1  | 2024-04-24 20:57:54 metadata.meet.jitsi:room_metadata_component                  info	Starting room metadata for muc.meet.jitsi
prosody-1  | 2024-04-24 20:57:54 metadata.meet.jitsi:room_metadata_component                  info	No host/component found, will wait for it: muc.meet.jitsi
prosody-1  | 2024-04-24 20:57:54 metadata.meet.jitsi:room_metadata_component                  info	No host/component found, will wait for it: breakout.meet.jitsi
prosody-1  | 2024-04-24 20:57:54 metadata.meet.jitsi:tls                                      info	Certificates loaded
prosody-1  | 2024-04-24 20:57:54 metadata.meet.jitsi:room_metadata_component                  info	Hook to muc events on breakout.meet.jitsi
prosody-1  | 2024-04-24 20:57:54 breakout.meet.jitsi:tls                                      info	Certificates loaded
prosody-1  | 2024-04-24 20:57:54 internal-muc.meet.jitsi:tls                                  info	Certificates loaded
prosody-1  | 2024-04-24 20:57:54 portmanager                                                  info	Activated service 'http' on [*]:5280, [::]:5280
prosody-1  | 2024-04-24 20:57:54 portmanager                                                  info	Activated service 'https' on no ports
prosody-1  | 2024-04-24 20:57:54 meet.jitsi:http                                              info	Serving 'bosh' at http://meet.jitsi:5280/http-bind
prosody-1  | 2024-04-24 20:57:54 meet.jitsi:muc_lobby_rooms                                   info	No host/component found, will wait for it: lobby.meet.jitsi
prosody-1  | 2024-04-24 20:57:54 meet.jitsi:muc_lobby_rooms                                   info	No host/component found, will wait for it: muc.meet.jitsi
prosody-1  | 2024-04-24 20:57:54 meet.jitsi:conference_duration                               info	No host/component found, will wait for it: muc.meet.jitsi
prosody-1  | 2024-04-24 20:57:54 portmanager                                                  info	Activated service 'c2s' on [*]:5222, [::]:5222
prosody-1  | 2024-04-24 20:57:54 portmanager                                                  info	Activated service 'c2s_direct_tls' on no ports
prosody-1  | 2024-04-24 20:57:54 portmanager                                                  info	Activated service 'legacy_ssl' on no ports
prosody-1  | 2024-04-24 20:57:54 meet.jitsi:http                                              info	Serving 'websocket' at http://meet.jitsi:5280/xmpp-websocket
prosody-1  | 2024-04-24 20:57:54 meet.jitsi:room_destroy                                      info	loaded
prosody-1  | 2024-04-24 20:57:54 meet.jitsi:muc_breakout_rooms                                info	Breakout rooms component created breakout.meet.jitsi
prosody-1  | 2024-04-24 20:57:54 meet.jitsi:muc_breakout_rooms                                info	Hook to muc events on breakout.meet.jitsi
prosody-1  | 2024-04-24 20:57:54 meet.jitsi:muc_breakout_rooms                                info	No host/component found, will wait for it: muc.meet.jitsi
prosody-1  | 2024-04-24 20:57:54 meet.jitsi:tls                                               info	Certificates loaded
prosody-1  | 2024-04-24 20:57:54 meet.jitsi:muc_lobby_rooms                                   info	Lobby component loaded lobby.meet.jitsi
prosody-1  | 2024-04-24 20:57:54 lobby.meet.jitsi:tls                                         info	Certificates loaded
prosody-1  | 2024-04-24 20:57:54 speakerstats.meet.jitsi:speakerstats_component               info	Starting speakerstats for muc.meet.jitsi
prosody-1  | 2024-04-24 20:57:54 speakerstats.meet.jitsi:speakerstats_component               info	No host/component found, will wait for it: muc.meet.jitsi
prosody-1  | 2024-04-24 20:57:54 speakerstats.meet.jitsi:speakerstats_component               info	Breakout component loaded breakout.meet.jitsi
prosody-1  | 2024-04-24 20:57:54 speakerstats.meet.jitsi:speakerstats_component               info	Hook to muc events on table: 0x55a5d3930890
prosody-1  | 2024-04-24 20:57:54 speakerstats.meet.jitsi:tls                                  info	Certificates loaded
prosody-1  | 2024-04-24 20:57:54 guest.meet.jitsi:tls                                         info	Certificates loaded
prosody-1  | 2024-04-24 20:57:54 avmoderation.meet.jitsi:av_moderation_component              info	Starting av_moderation for muc.meet.jitsi
prosody-1  | 2024-04-24 20:57:54 avmoderation.meet.jitsi:av_moderation_component              info	No host/component found, will wait for it: muc.meet.jitsi
prosody-1  | 2024-04-24 20:57:54 avmoderation.meet.jitsi:tls                                  info	Certificates loaded
prosody-1  | 2024-04-24 20:57:54 avmoderation.meet.jitsi:av_moderation_component              info	Hook to muc events on muc.meet.jitsi
prosody-1  | 2024-04-24 20:57:54 speakerstats.meet.jitsi:speakerstats_component               info	Conference component loaded muc.meet.jitsi
prosody-1  | 2024-04-24 20:57:54 speakerstats.meet.jitsi:speakerstats_component               info	Hook to muc events on table: 0x55a5d378cc90
prosody-1  | 2024-04-24 20:57:54 speakerstats.meet.jitsi:speakerstats_component               info	Main muc service table: 0x55a5d37971a0
prosody-1  | 2024-04-24 20:57:54 metadata.meet.jitsi:room_metadata_component                  info	Hook to muc events on muc.meet.jitsi
prosody-1  | 2024-04-24 20:57:54 muc.meet.jitsi:muc_domain_mapper                             info	Loading mod_muc_domain_mapper for host conferenceduration.meet.jitsi!
prosody-1  | 2024-04-24 20:57:54 muc.meet.jitsi:muc_domain_mapper                             info	Loading mod_muc_domain_mapper for host focus.meet.jitsi!
prosody-1  | 2024-04-24 20:57:54 muc.meet.jitsi:muc_domain_mapper                             info	Loading mod_muc_domain_mapper for host metadata.meet.jitsi!
prosody-1  | 2024-04-24 20:57:54 muc.meet.jitsi:muc_domain_mapper                             info	Loading mod_muc_domain_mapper for host breakout.meet.jitsi!
prosody-1  | 2024-04-24 20:57:55 muc.meet.jitsi:muc_domain_mapper                             info	Loading mod_muc_domain_mapper for host internal-muc.meet.jitsi!
prosody-1  | 2024-04-24 20:57:55 muc.meet.jitsi:muc_domain_mapper                             info	Loading mod_muc_domain_mapper for host meet.jitsi!
prosody-1  | 2024-04-24 20:57:55 muc.meet.jitsi:muc_domain_mapper                             info	Loading mod_muc_domain_mapper for host speakerstats.meet.jitsi!
prosody-1  | 2024-04-24 20:57:55 muc.meet.jitsi:muc_domain_mapper                             info	Loading mod_muc_domain_mapper for host guest.meet.jitsi!
prosody-1  | 2024-04-24 20:57:55 muc.meet.jitsi:muc_domain_mapper                             info	Loading mod_muc_domain_mapper for host muc.meet.jitsi!
prosody-1  | 2024-04-24 20:57:55 muc.meet.jitsi:muc_domain_mapper                             info	Loading mod_muc_domain_mapper for host lobby.meet.jitsi!
prosody-1  | 2024-04-24 20:57:55 muc.meet.jitsi:muc_domain_mapper                             info	Loading mod_muc_domain_mapper for host avmoderation.meet.jitsi!
prosody-1  | 2024-04-24 20:57:55 muc.meet.jitsi:tls                                           info	Certificates loaded
prosody-1  | 2024-04-24 20:57:55 meet.jitsi:muc_breakout_rooms                                info	Hook to muc events on muc.meet.jitsi
prosody-1  | 2024-04-24 20:57:55 muc.meet.jitsi:muc_domain_mapper                             info	Loading mod_muc_domain_mapper for host endconference.meet.jitsi!
prosody-1  | 2024-04-24 20:57:55 endconference.meet.jitsi:end_conference                      info	Starting end_conference for muc.meet.jitsi
prosody-1  | 2024-04-24 20:57:55 endconference.meet.jitsi:tls                                 info	Certificates loaded
prosody-1  | 2024-04-24 20:57:55 muc.meet.jitsi:muc_domain_mapper                             info	Loading mod_muc_domain_mapper for host recorder.meet.jitsi!
prosody-1  | 2024-04-24 20:57:55 recorder.meet.jitsi:tls                                      info	Certificates loaded
prosody-1  | 2024-04-24 20:57:55 muc.meet.jitsi:muc_domain_mapper                             info	Loading mod_muc_domain_mapper for host auth.meet.jitsi!
prosody-1  | 2024-04-24 20:57:55 auth.meet.jitsi:tls                                          info	Certificates loaded
prosody-1  | 2024-04-24 20:57:58 c2s55a5d3abb1b0                                              info	Client connected
prosody-1  | 2024-04-24 20:57:59 c2s55a5d3abb1b0                                              info	Stream encrypted (TLSv1.3 with TLS_AES_256_GCM_SHA384)
prosody-1  | 2024-04-24 20:57:59 c2s55a5d39c7d50                                              info	Client connected
prosody-1  | 2024-04-24 20:57:59 c2s55a5d3abb1b0                                              info	Authenticated as focus@auth.meet.jitsi
prosody-1  | 2024-04-24 20:57:59 auth.meet.jitsi:limits_exception                             info	Setting stanza size limits for focus@auth.meet.jitsi to 10485760
prosody-1  | 2024-04-24 20:58:00 c2s55a5d39c7d50                                              info	Stream encrypted (TLSv1.3 with TLS_AES_256_GCM_SHA384)
prosody-1  | 2024-04-24 20:58:00 c2s55a5d39c7d50                                              info	Authenticated as jvb@auth.meet.jitsi
prosody-1  | 2024-04-24 20:58:00 auth.meet.jitsi:limits_exception                             info	Setting stanza size limits for jvb@auth.meet.jitsi to 10485760
prosody-1  | 2024-04-24 20:58:03 c2s55a5d3b71200                                              info	Client connected
prosody-1  | 2024-04-24 20:58:03 c2s55a5d3b71200                                              info	Stream encrypted (TLSv1.2 with ECDHE-RSA-AES256-GCM-SHA384)
prosody-1  | 2024-04-24 20:58:03 c2s55a5d3b71200                                              info	Authenticated as jigasi@auth.meet.jitsi
prosody-1  | 2024-04-24 20:58:31 c2s55a5d3d85420                                              info	Client connected
prosody-1  | 2024-04-24 20:58:31 c2s55a5d3d85420                                              info	Authenticated as 7efa1ee3-9471-4332-85f9-a9fcd27ffaae@guest.meet.jitsi
prosody-1  | 2024-04-24 20:58:45 c2s55a5d3b93580                                              info	Client connected
prosody-1  | 2024-04-24 20:59:09 c2s55a5d3d2a8a0                                              info	Client connected
prosody-1  | 2024-04-24 20:59:18 c2s55a5d3caa2e0                                              info	Client connected
prosody-1  | 2024-04-24 20:59:45 c2s55a5d3b93580                                              info	Client disconnected: connection closed
prosody-1  | 2024-04-24 21:00:09 c2s55a5d3d2a8a0                                              info	Client disconnected: connection closed
prosody-1  | 2024-04-24 21:00:18 c2s55a5d3caa2e0                                              info	Client disconnected: connection closed
prosody-1  | 2024-04-24 21:08:26 c2s55a5d3d85420                                              info	Client disconnected: connection closed
prosody-1  | 2024-04-24 21:08:32 c2s55a5d3b964f0                                              info	Client connected
prosody-1  | 2024-04-24 21:08:33 c2s55a5d3b964f0                                              info	Authenticated as fa22dfb3-38f2-404c-912e-5ed1380da079@guest.meet.jitsi
prosody-1  | 2024-04-24 21:08:38 c2s55a5d3938a40                                              info	Client connected
prosody-1  | 2024-04-24 21:08:41 c2s55a5d3b964f0                                              info	Client disconnected: connection closed
prosody-1  | 2024-04-24 21:08:41 c2s55a5d3938a40                                              info	Client disconnected: connection closed
prosody-1  | 2024-04-24 21:09:08 c2s55a5d3363080                                              info	Client connected
prosody-1  | 2024-04-24 21:09:08 c2s55a5d3363080                                              info	Authenticated as 503503b3-668a-445f-aadc-9f62995fe272@guest.meet.jitsi
prosody-1  | 2024-04-24 21:09:31 c2s55a5d3b548b0                                              info	Client connected
prosody-1  | 2024-04-24 21:09:47 c2s55a5d396e560                                              info	Client connected
prosody-1  | 2024-04-24 21:09:52 c2s55a5d3b548b0                                              info	Client disconnected: connection closed
prosody-1  | 2024-04-24 21:09:52 c2s55a5d396e560                                              info	Client disconnected: connection closed
prosody-1  | 2024-04-24 21:09:52 c2s55a5d3363080                                              info	Client disconnected: connection closed
`

**Comment by lakevetch** [comment]
oh god, sorry about the formatting, will attempt to improve

**Comment by saghul** [comment]
That doesn't help much. What env vars did you set? Can you get the jitsi-meet.cf.lua file off the container?

**Comment by lakevetch** [comment]
the env vars for authentication that I have configured are:
ENABLE_AUTH=1
ENABLE_GUESTS=1
AUTH_TYPE=internal

fetching that file now

**Comment by lakevetch** [comment]
admins = {
    
    "jigasi@auth.meet.jitsi",
    

    
    "jibri@auth.meet.jitsi",
    

    "focus@auth.meet.jitsi",
    "jvb@auth.meet.jitsi"
}

unlimited_jids = {
    "focus@auth.meet.jitsi",
    "jvb@auth.meet.jitsi"
}

plugin_paths = { "/prosody-plugins/", "/prosody-plugins-custom" }

muc_mapper_domain_base = "meet.jitsi";
muc_mapper_domain_prefix = "muc";

http_default_host = "meet.jitsi"









consider_bosh_secure = true;
consider_websocket_secure = true;


smacks_max_unacked_stanzas = 5;
smacks_hibernation_time = 60;
smacks_max_hibernated_sessions = 1;
smacks_max_old_sessions = 1;




VirtualHost "meet.jitsi"

  
    authentication = "internal_hashed"
  

    ssl = {
        key = "/config/certs/meet.jitsi.key";
        certificate = "/config/certs/meet.jitsi.crt";
    }
    modules_enabled = {
        "bosh";
        
        "websocket";
        "smacks"; -- XEP-0198: Stream Management
        
        "speakerstats";
        "conference_duration";
        "room_metadata";
        
        "end_conference";
        
        
        
        "muc_lobby_rooms";
        
        
        "muc_breakout_rooms";
        
        
        "av_moderation";
        
        
        
        
        
    }

    main_muc = "muc.meet.jitsi"
    room_metadata_component = "metadata.meet.jitsi"
    
    lobby_muc = "lobby.meet.jitsi"
    
    muc_lobby_whitelist = { "recorder.meet.jitsi" }
    
    

    

    
    breakout_rooms_muc = "breakout.meet.jitsi"
    

    speakerstats_component = "speakerstats.meet.jitsi"
    conference_duration_component = "conferenceduration.meet.jitsi"

    
    end_conference_component = "endconference.meet.jitsi"
    

    
    av_moderation_component = "avmoderation.meet.jitsi"
    

    c2s_require_encryption = true

    

    
VirtualHost "guest.meet.jitsi"
    authentication = "jitsi-anonymous"
    modules_enabled = {
        
        "smacks"; -- XEP-0198: Stream Management
        
    }

    c2s_require_encryption = true
    



VirtualHost "auth.meet.jitsi"
    ssl = {
        key = "/config/certs/auth.meet.jitsi.key";
        certificate = "/config/certs/auth.meet.jitsi.crt";
    }
    modules_enabled = {
        "limits_exception";
    }
    authentication = "internal_hashed"


VirtualHost "recorder.meet.jitsi"
    modules_enabled = {
      "smacks";
    }
    authentication = "internal_hashed"


Component "internal-muc.meet.jitsi" "muc"
    storage = "memory"
    modules_enabled = {
        }
    restrict_room_creation = true
    muc_filter_whitelist="auth.meet.jitsi"
    muc_room_locking = false
    muc_room_default_public_jids = true
    muc_room_cache_size = 1000
    muc_tombstones = false
    muc_room_allow_persistent = false

Component "muc.meet.jitsi" "muc"
    restrict_room_creation = true
    storage = "memory"
    modules_enabled = {
        "muc_meeting_id";
        
        "polls";
        "muc_domain_mapper";
        
        "muc_password_whitelist";
    }

    -- The size of the cache that saves state for IP addresses
    rate_limit_cache_size = 10000;

    muc_room_cache_size = 10000
    muc_room_locking = false
    muc_room_default_public_jids = true
    
    muc_password_whitelist = {
        "focus@auth.meet.jitsi";
        "recorder@recorder.meet.jitsi";
    }
    muc_tombstones = false
    muc_room_allow_persistent = false

Component "focus.meet.jitsi" "client_proxy"
    target_address = "focus@auth.meet.jitsi"

Component "speakerstats.meet.jitsi" "speakerstats_component"
    muc_component = "muc.meet.jitsi"

Component "conferenceduration.meet.jitsi" "conference_duration_component"
    muc_component = "muc.meet.jitsi"


Component "endconference.meet.jitsi" "end_conference"
    muc_component = "muc.meet.jitsi"



Component "avmoderation.meet.jitsi" "av_moderation_component"
    muc_component = "muc.meet.jitsi"



Component "lobby.meet.jitsi" "muc"
    storage = "memory"
    restrict_room_creation = true
    muc_tombstones = false
    muc_room_allow_persistent = false
    muc_room_cache_size = 10000
    muc_room_locking = false
    muc_room_default_public_jids = true
    modules_enabled = {
        }

    


Component "breakout.meet.jitsi" "muc"
    storage = "memory"
    restrict_room_creation = true
    muc_room_cache_size = 10000
    muc_room_locking = false
    muc_room_default_public_jids = true
    muc_tombstones = false
    muc_room_allow_persistent = false
    modules_enabled = {
        "muc_meeting_id";
        "polls";
        }


Component "metadata.meet.jitsi" "room_metadata_component"
    muc_component = "muc.meet.jitsi"
    breakout_rooms_component = "breakout.meet.jitsi"

**Comment by saghul** [comment]
Very odd, your main domain does have auth on!

**Comment by lakevetch** [comment]
Just took a look into /config/data/auth%2emeet%2ejitsi/accounts in the container, and it would appear that both the transcriber and the admin account I created have .dat files there, alongside jibri.dat, focus.dat, etc.

**Comment by lakevetch** [comment]
> prosodyctl --config /config/prosody.cfg.lua register TheDesired Username auth.meet.jitsi TheDesiredPassword

So this command did successfully create accounts, but when I try to log in:

![image](https://github.com/jitsi/docker-jitsi-meet/assets/108903240/11dfab0c-b1e1-449a-a5f4-e68221b5bb6f)

**Comment by saghul** [comment]
That's correct yes, they don't match the domain.

**Comment by filwu8** [comment]
Note that when copying, except for the spaces in the text
The difference between &nbsp and spaces in HTML code: Each time you enter an escape character &nbsp in the HTML code, it represents a space. If you enter ten &nbsp, 10 space positions will be displayed on the page. When entering spaces in the html code, no matter how many spaces are entered, only one space will be displayed on the page. The escaped Character&amp in html means &Character, and a space means a space.

**Comment by lakevetch** [comment]
Following up on this issue. If the auth issue is due to users not being registered on the meet.jitsi domain, and attempting to register users to the meet.jitsi domain always throws the "Error: Creating user failed" error, then we are stuck. I'm in conversation with Prosody support about why the error could be occurring. Any further insight here would also be welcome. Thanks all

**Comment by lakevetch** [comment]
User creation has just worked for me. I followed suggestions in this [thread](https://github.com/jitsi/docker-jitsi-meet/issues/443) to remove and cleanly reinstall all containers and the config directory
