### ISSUE TITLE
use own tls certificate instead of letsencrypt

### ISSUE THREAD

**Issue by solick** [jitsi/docker-jitsi-meet#1096]
I have an own wildcard certificate for my domain which I would like to use instead of lets encrypt. How can I configure own certificate instead of lets encrypt? didn't find anything in the documentation.

**Comment by saghul** [comment]
You can mount the files here: https://github.com/jitsi/docker-jitsi-meet/blob/master/web/rootfs/defaults/ssl.conf#L11-L12

**Comment by solick** [comment]
No that does not work. If I do so and disable lets encrypt support in .env, own certs will be created and used. I removed all containers, deleted the config and still after deploying the containers again the same behavior observed.

Version stable-5963

**Comment by saghul** [comment]
Did you mount your certs?

**Comment by solick** [comment]
I created a symlink into the config file and added the link to the ssl.conf but this seems not to work. So I have to moint the host dir where the ssl files are located into the container to make it working?

**Comment by prayagsingh** [comment]
> So I have to moint the host dir where the ssl files are located into the container to make it working?

Yes. mount it like `/host_directory/ssl.crt:/config/keys/cert.crt` and same for key.

**Comment by solick** [comment]
ok tried this but still every time I make a clean deployment, own certificate is generated:

    :~/docker-data/docker-jitsi-meet$ docker logs docker-jitsi-meet_web_1 -n 100
    [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
    [s6-init] ensuring user provided files have correct perms...exited 0.
    [fix-attrs.d] applying ownership & permissions fixes...
    [fix-attrs.d] done.
    [cont-init.d] executing container initialization scripts...
    [cont-init.d] 01-set-timezone: executing... 
    [cont-init.d] 01-set-timezone: exited 0.
    [cont-init.d] 10-config: executing... 
    generating self-signed keys in /config/keys, you can replace these with your own keys if required
    Generating a RSA private key
    ..................................................................+++++
    ......+++++
    writing new private key to '/config/keys/cert.key'
    -----
    [cont-init.d] 10-config: exited 0.
    [cont-init.d] done.
    [services.d] starting services
    [services.d] done.

according to docker inspect the files are mounted and I can see them in de .jitsi-meet-cfg/keys directory

**Comment by prayagsingh** [comment]
@solick Please share the `service: web` part from docker-compose.yml file

**Comment by solick** [comment]
@prayagsingh 

    web:
        image: jitsi/web:stable-5963
        restart: ${RESTART_POLICY}
        ports:
            - '${HTTP_PORT}:80'
            - '${HTTPS_PORT}:443'
        volumes:
            - ${CONFIG}/web:/config:Z
            - ${CONFIG}/transcripts:/usr/share/jitsi-meet/transcripts:Z
            - /etc/ssl/wildcard.XXX.com.crt:/config/keys/wildcard.XXX.com.crt:Z
            - /etc/ssl/wildcard.XXX.com.key:/config/keys/wildcard.XXX.com.key:Z
        environment:
            - ENABLE_COLIBRI_WEBSOCKET
            - ENABLE_FLOC
            - ENABLE_LETSENCRYPT
            - ENABLE_HTTP_REDIRECT
            - ENABLE_HSTS
            - ENABLE_XMPP_WEBSOCKET
            - DISABLE_HTTPS
            - DISABLE_DEEP_LINKING
            - LETSENCRYPT_DOMAIN
            - LETSENCRYPT_EMAIL
            - LETSENCRYPT_USE_STAGING
            - PUBLIC_URL
            - TZ
            - AMPLITUDE_ID
            - ANALYTICS_SCRIPT_URLS
            - ANALYTICS_WHITELISTED_EVENTS
            - CALLSTATS_CUSTOM_SCRIPT_URL
            - CALLSTATS_ID
            - CALLSTATS_SECRET
            - CHROME_EXTENSION_BANNER_JSON
            - CONFCODE_URL
            - CONFIG_EXTERNAL_CONNECT
            - DEFAULT_LANGUAGE
            - DEPLOYMENTINFO_ENVIRONMENT
            - DEPLOYMENTINFO_ENVIRONMENT_TYPE
            - DEPLOYMENTINFO_REGION
            - DEPLOYMENTINFO_SHARD
            - DEPLOYMENTINFO_USERREGION
            - DIALIN_NUMBERS_URL
            - DIALOUT_AUTH_URL
            - DIALOUT_CODES_URL
            - DROPBOX_APPKEY
            - DROPBOX_REDIRECT_URI
            - DYNAMIC_BRANDING_URL
            - ENABLE_AUDIO_PROCESSING
            - ENABLE_AUTH
            - ENABLE_CALENDAR
            - ENABLE_FILE_RECORDING_SERVICE
            - ENABLE_FILE_RECORDING_SERVICE_SHARING
            - ENABLE_GUESTS
            - ENABLE_IPV6
            - ENABLE_LIPSYNC
            - ENABLE_NO_AUDIO_DETECTION
            - ENABLE_P2P
            - ENABLE_PREJOIN_PAGE
            - ENABLE_WELCOME_PAGE
            - ENABLE_CLOSE_PAGE
            - ENABLE_RECORDING
            - ENABLE_REMB
            - ENABLE_REQUIRE_DISPLAY_NAME
            - ENABLE_SIMULCAST
            - ENABLE_STATS_ID
            - ENABLE_STEREO
            - ENABLE_SUBDOMAINS
            - ENABLE_TALK_WHILE_MUTED
            - ENABLE_TCC
            - ENABLE_TRANSCRIPTIONS
            - ETHERPAD_PUBLIC_URL
            - ETHERPAD_URL_BASE
            - GOOGLE_ANALYTICS_ID
            - GOOGLE_API_APP_CLIENT_ID
            - INVITE_SERVICE_URL
            - JICOFO_AUTH_USER
            - MATOMO_ENDPOINT
            - MATOMO_SITE_ID
            - MICROSOFT_API_APP_CLIENT_ID
            - NGINX_RESOLVER
            - NGINX_WORKER_PROCESSES
            - NGINX_WORKER_CONNECTIONS
            - PEOPLE_SEARCH_URL
            - RESOLUTION
            - RESOLUTION_MIN
            - RESOLUTION_WIDTH
            - RESOLUTION_WIDTH_MIN
            - START_AUDIO_ONLY
            - START_AUDIO_MUTED
            - START_WITH_AUDIO_MUTED
            - START_SILENT
            - DISABLE_AUDIO_LEVELS
            - ENABLE_NOISY_MIC_DETECTION
            - START_BITRATE
            - DESKTOP_SHARING_FRAMERATE_MIN
            - DESKTOP_SHARING_FRAMERATE_MAX
            - START_VIDEO_MUTED
            - START_WITH_VIDEO_MUTED
            - TESTING_CAP_SCREENSHARE_BITRATE
            - TESTING_OCTO_PROBABILITY
            - XMPP_AUTH_DOMAIN
            - XMPP_BOSH_URL_BASE
            - XMPP_DOMAIN
            - XMPP_GUEST_DOMAIN
            - XMPP_MUC_DOMAIN
            - XMPP_RECORDER_DOMAIN
            - TOKEN_AUTH_URL
        networks:
            meet.jitsi:

The cert files are available in the config directory but somehow are not seen during initialization...

**Comment by prayagsingh** [comment]
@solick you are mounting like this 
`/etc/ssl/wildcard.XXX.com.crt:/config/keys/wildcard.XXX.com.crt:Z`

Instead, try 

`/etc/ssl/wildcard.XXX.com.crt:/config/keys/cert.crt:Z`

Then `exec` into the container and verify that It is the same cert that you are mapping. 

If they are different then the only way to fix it is to create your own docker image. 
1. edit `ssl.conf` file and change
 ```
 ssl_certificate /config/keys/wildcard.XXX.com.crt;
 ssl_certificate_key /config/keys/wildcard.XXX.com.key;
 ```
 2. create a docker-image using the command `docker image build -t solick/web:latest .` execute this inside the `web` directory on your machine.

**Comment by saghul** [comment]
Mounting them with the right name should be enough, as they won't be overwritten.

**Comment by solick** [comment]
ok thanks at least I got it working. I needed the bundle certificate to get it working and as @prayagsingh wrote need to point the files into the container with exact the original names from the docker config.

Thanks for your support!
