### ISSUE TITLE
Jitsi meet crashes in Docker

### ISSUE THREAD

**Issue by Algoritm211** [jitsi/docker-jitsi-meet#1099]
Now I`m trying to launch jitsi in Docker on my Macbook and check the functionality before deploying jitsi to Google cloud run.

I`m using this guide: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker

And however, I cannot access jitsi at `https://localhost:8443`
I decided to look at the logs and got an error in one of the containers: `failed to initialize Lua VM in /config/nginx/nginx.conf:65`

Initially nginx.conf looks like this:
```nginx
user www-data;
worker_processes {{ .Env.NGINX_WORKER_PROCESSES | default "4" }};
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
	worker_connections {{ .Env.NGINX_WORKER_CONNECTIONS | default "768" }};
	# multi_accept on;
}

http {

	##
	# Basic Settings
	##

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	server_tokens off;

	# server_names_hash_bucket_size 64;
	# server_name_in_redirect off;

	client_max_body_size 0;

	resolver {{ .Env.NGINX_RESOLVER | default "127.0.0.11" }};

 	include /etc/nginx/mime.types;
	types {
		# add support for wasm MIME type, that is required by specification and it is not part of default mime.types file
		application/wasm wasm;
	}
	default_type application/octet-stream;

	##
	# Logging Settings
	##

	access_log /dev/stdout;
	error_log /dev/stderr;

	##
	# Gzip Settings
	##

	gzip on;
	gzip_types text/plain text/css application/javascript application/json;
	gzip_vary on;
	gzip_min_length 860;

	# gzip_vary on;
	# gzip_proxied any;
	# gzip_comp_level 6;
	# gzip_buffers 16 8k;
	# gzip_http_version 1.1;
	# gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;

	##
	# Virtual Host Configs
	##
        include /config/nginx/site-confs/*;  /////// Here is something wrong, but I dont know what`s wrong with it. I have looked a lot of guides and in none of this file is changed.
}


daemon off;

```
Can you please tell me why there might be an error and how to solve it. Tried running on many devices but got the same result (`failed to initialize Lua VM in /config/nginx/nginx.conf:65`)

Thank you very much in advance)

**Comment by saghul** [comment]
Do you have more logs? What is in line 65?

**Comment by Algoritm211** [comment]
> Do you have more logs? What is in line 65?

 include /config/nginx/site-confs/*; - is 65`s line of code in nginx.conf. Unfortunately, I don`t know what`s wrong with it. I have looked a lot of guides and in none of this file is changed.

**Comment by saghul** [comment]
what files do you have there? please paste them here

**Comment by Algoritm211** [comment]
> what files do you have there? please paste them here

There is no files. Perhaps I have nginx configured incorrectly, I do not have this folder and files. But in theory I just need running nginx and it is there. However, nowhere did I find the correct nginx config to run jitsi and where to put it. Do you have any idea how I can run jitsi on my machine?

**Comment by Algoritm211** [comment]
> what files do you have there? please paste them here

nginx.conf is in a stable release in https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-5963. 
In theory, I should not change it at all, everything is assembled there to launch the container and images

**Comment by saghul** [comment]
Can you paste the full container log?

**Comment by Algoritm211** [comment]
> Can you paste the full container log?

Yes, of course. I hope for your help

```nginx
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] 01-set-timezone: executing...

[cont-init.d] 01-set-timezone: exited 0.

[cont-init.d] 10-config: executing...

using keys found in /config/keys

[cont-init.d] 10-config: exited 0.

[cont-init.d] done.

[services.d] starting services


[services.d] done.


nginx: [error] failed to initialize Lua VM in /config/nginx/nginx.conf:65


nginx: [error] failed to initialize Lua VM in /config/nginx/nginx.conf:65


nginx: [error] failed to initialize Lua VM in /config/nginx/nginx.conf:65


nginx: [error] failed to initialize Lua VM in /config/nginx/nginx.conf:65


nginx: [error] failed to initialize Lua VM in /config/nginx/nginx.conf:65


nginx: [error] failed to initialize Lua VM in /config/nginx/nginx.conf:65


nginx: [error] failed to initialize Lua VM in /config/nginx/nginx.conf:65


nginx: [error] failed to initialize Lua VM in /config/nginx/nginx.conf:65


nginx: [error] failed to initialize Lua VM in /config/nginx/nginx.conf:65


nginx: [error] failed to initialize Lua VM in /config/nginx/nginx.conf:65


nginx: [error] failed to initialize Lua VM in /config/nginx/nginx.conf:65


nginx: [error] failed to initialize Lua VM in /config/nginx/nginx.conf:65


nginx: [error] failed to initialize Lua VM in /config/nginx/nginx.conf:65


nginx: [error] failed to initialize Lua VM in /config/nginx/nginx.conf:65
```

**Comment by Algoritm211** [comment]
> Can you paste the full container log?

Have you any idea to fix it?

**Comment by saghul** [comment]
I have never seen this, sorry!

**Comment by arunkleargroup** [comment]
Even I am facing same issue in MacBook m1 processor

**Comment by mickyarun** [comment]
Even I am facing the same issue MacBook m1

**Comment by segullshairbutt** [comment]
Is there any solution to it. I am also facing it on Macbook m1.

**Comment by kaloster** [comment]
Facing the same error with MBP M1 - not sure it's entirely related.

**Comment by saghul** [comment]
We don't provide arm64 images yet, so M1 is not currently supported sorry.

**Comment by kaloster** [comment]
I can confirm that it does work on MBP with Intel chip (though keeps disconnecting, but that's a different issue).

**Comment by solarkraft** [comment]
I have the same issue. Tried [setting the platform as seen here](https://erica.works/docker-on-mac-m1/), but it doesn't seem to change anything.

**Comment by solarkraft** [comment]
Vaguely related: docker/for-mac/issues/5337

**Comment by solarkraft** [comment]
@adam-at-mobomo Thanks for the hints in the Kong issue! Sadly it didn't work for me. Could you have a look?

Here are my steps:

- `docker buildx build --platform linux/arm64 base --no-cache -t jitsi/base:arm`
- `BASE_TAG=arm docker buildx build --platform linux/arm64 --no-cache web -t jitsi/web:arm`
- ` image: jitsi/web:arm` for `web`  in  'docker-compose.yml`
- `docker compose down && docker compose up`

The container in use for `web` has the `arm` tag (`docker compose up -d && docker compose images`) and both show `"Architecture": "arm64"` on inspection (`docker image inspect jitsi/web:arm`, `docker image inspect jitsi/base:arm`).

**Comment by RicardoDolNL** [comment]
Any update on this problem yet?

**Comment by saghul** [comment]
No updates yet, sorry.

**Comment by saghul** [comment]
Please follow https://github.com/jitsi/docker-jitsi-meet/issues/1214
