### ISSUE TITLE
Behind reverse proxy?

### ISSUE THREAD

**Issue by gerroon** [jitsi/docker-jitsi-meet#110]
Hi

Is it possible to run this behind a reverse proxy like Apache reverse proxy? Or do I really need a dedicated :443 port for it to be usable?

**Comment by saghul** [comment]
Sure you can. By default this setup listens on port 8000 and port 8443 with a self-signed certificate. You can just proxy to port 8000 and it will work just fine.

**Comment by gerroon** [comment]
@saghul thanks for the reply. I know this is anot a forum, but one last question so that I do not end up wasting my time on this.

So basically proxying 8000 takes care of everything, no need to proxy internal XMPP ports or other stuff?

**Comment by saghul** [comment]
Correct! All the XMPP stuff happens in the internal Docker network, you don't need to worry about that.

**Comment by gerroon** [comment]
Woww sounds easier than I thought. Thanks and have a good day.
