### ISSUE TITLE
RFC: enable lobby, prejoin, av moderation by default

### ISSUE THREAD

**Issue by saghul** [jitsi/docker-jitsi-meet#1104]
In general I feel like those features are better off enabled by default, and they can be disabled at deploy time. Having them enabled makes for a safer  out-of-the-box experience IMHO.

So, I'm opening this issue to try and get some feedback from those who deploy the Docker setup. Disabling those features will still be possible of course, but they would now default to being enabled.

Since this could be a breaking change, I'd mention that clearly in the release notes.

Thoughts?

**Comment by prayagsingh** [comment]
TBH it's very confusing for me to decide.

**This is what I thought earlier**
```
I think it's better to keep them off by default. 
Let's keep minimal config to spin up the setup and let the user decide if they want to enable any of the new features. 
```

But at the same time, everyone is switching to updated versions for new features and fixes only hence it is better to set them true by default.  

> Since this could be a breaking change, I'd mention that clearly in the release notes.

100% agree. 

Lets set these features to true by default.

**Comment by khakulov** [comment]
don't forget to get `mod_polls` to that list

**Comment by Vertganti** [comment]
Having lobbies enabled by default was a requirement for our setup. Until now we have used custom modifications of the `mod_muc_lobby_rooms.lua` file [suggested on the forums](https://community.jitsi.org/t/start-a-room-with-lobby-enabled/79279/4) to achieve this. However, those might not work anymore when we update (newer posts in that thread suggest so). Having lobbies enabled by default OOTB would be a great improvement for us. I also think that for most videocalls and conferences it is safe to assume that people want to decide who is able to join.

We have not used prejoin and AV moderation yet, but I'd say that safer by default is a good thing anyway.

**Comment by saghul** [comment]
> Having lobbies enabled by default was a requirement for our setup. Until now we have used custom modifications of the `mod_muc_lobby_rooms.lua` file [suggested on the forums](https://community.jitsi.org/t/start-a-room-with-lobby-enabled/79279/4) to achieve this. However, those might not work anymore when we update (newer posts in that thread suggest so). Having lobbies enabled by default OOTB would be a great improvement for us. I also think that for most videocalls and conferences it is safe to assume that people want to decide who is able to join.
> 
> 
> 
> We have not used prejoin and AV moderation yet, but I'd say that safer by default is a good thing anyway.

The proposal here is a bit different.

The idea is to have the features enabled by default, that is, available in the UI, not turned on by default.

**Comment by Vertganti** [comment]
> The proposal here is a bit different.
> 
> The idea is to have the features enabled by default, that is, available in the UI, not turned on by default.

Ok, thanks for the clarification.  I forgot lobbies are disabled by default... Anyway, in that case I fully agree that they should be enabled by default since they are probably useful for most deployments. Same for AV moderation.
