### ISSUE TITLE
Remove quotation marks from TURN configuration

### ISSUE THREAD

**Issue by Vertganti** [jitsi/docker-jitsi-meet#1110]
The environment variables for TURN configuration in the `env.example` file define the default for `TURN_CREDENTIALS` as [`"secret"` (with quotation marks)](https://github.com/jitsi/docker-jitsi-meet/blob/master/env.example#L361).

    # Configure an external TURN server
    # TURN_CREDENTIALS="secret"

For me this seemed to suggest that I should put the secret between quotation marks. However, when starting the containers the prosody container would claim that a problem occurred reading the config file:

    Error: /config/conf.d/jitsi-meet.cfg.lua:33: malformed number near 'SECRET'

Inspecting the configuration file I could see that the `external_service_secret` had been set with too many quotation marks.

    external_service_secret = ""SECRET"";

Removing the quotation marks from the configuration file fixed the issue as expected. I assume the same might happen to others and therefore think it would be clearer if the quotation marks were removed from the example configuration. I could create a PR for this, but that might not be needed for such a small fix.

**Comment by saghul** [comment]
Makes sense. Care to send a PR?

**Comment by Vertganti** [comment]
Sure, created PR #1111
