### ISSUE TITLE
Cert renewal cron job does not persist when recreating container

### ISSUE THREAD

**Issue by jkowens** [jitsi/docker-jitsi-meet#1116]
When doing a `docker-compose down` and `docker-compose up` the cron job to renew the cert is lost. A work around is to delete the `.jitsi-meet-cfg` directory before running `docker-compose up`. 

If the crontab could be stored to a persistent location that would be a nice improvement.

**Comment by jkowens** [comment]
I didn't confirm, but it is possible the crontab does not persist container restart either.

See: https://github.com/jitsi/docker-jitsi-meet/pull/1079

**Comment by driehuis** [comment]
This will probably be fixed by #1121.

**Comment by saghul** [comment]
Fixed in #1121
