### ISSUE TITLE
dev branch constantly crashes

### ISSUE THREAD

**Issue by gerroon** [jitsi/docker-jitsi-meet#112]
Hi

I downloaded the zip file and did make and docker-compose-up but it seems like it contantly crashes see the log files please

https://bin.privacytools.io/?25a6edc94dce1927#QFTDqJfaeBawNDcGoZ7aFV/v8J/RcCIt4W0CcvGvzGY=

**Comment by saghul** [comment]
What's in your nginx config file?

```
invalid number of arguments in "proxy_pass" directive in /config/nginx/meet.conf:31
```

**Comment by saghul** [comment]
I just tested a fresh checkout and have no issues. Check your .env file, you migh have mistyped something there.

**Comment by gerroon** [comment]
Ok I will take a look at it. The .env file is the same file I use for the release which is interesting because that one works.
