### ISSUE TITLE
Background image/blur option missing?

### ISSUE THREAD

**Issue by emacsen** [jitsi/docker-jitsi-meet#1125]
I recently upgraded my Docker instance of Jitsi and now the background image/blur options are missing.

Looking through the new env.example, I don't see mention of it.

Looking at the interface_config.js I see this:

```
    /**
     * Whether or not the blurred video background for large video should be
     * displayed on browsers that can support it.
     */
    DISABLE_VIDEO_BACKGROUND: false,
```

I'm unsure if this is the correct value or not. The web interface has kept my previous image/blur settings so this appears to just be a web interface setting.

Any help on finding this setting?

**Comment by saghul** [comment]
Try to delete interface_config.js from your Jitsi config directory so it's regenerated. 

This is fixed in master, it will always be generated.

**Comment by emacsen** [comment]
That fixed it. I forgot about this. If it's not in the README, it may be a good thing to add!

**Comment by saghul** [comment]
No need, the next release contains a fix!
