### ISSUE TITLE
docker stable-6173: release  Invalid certificate

### ISSUE THREAD

**Issue by godpit** [jitsi/docker-jitsi-meet#1126]
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] 01-set-timezone: executing... 

[cont-init.d] 01-set-timezone: exited 0.

[cont-init.d] 10-config: executing... 

/opt /

[Sat Sep 25 19:40:26 CST 2021] Installing to /config/acme.sh

[Sat Sep 25 19:40:26 CST 2021] Installed to /config/acme.sh/acme.sh

[Sat Sep 25 19:40:26 CST 2021] Installing alias to '/root/.profile'

[Sat Sep 25 19:40:26 CST 2021] OK, Close and reopen your terminal to start using acme.sh

[Sat Sep 25 19:40:26 CST 2021] Installing cron job

no crontab for root

no crontab for root

[Sat Sep 25 19:40:26 CST 2021] Good, bash is found, so change the shebang to use bash as preferred.

[Sat Sep 25 19:40:26 CST 2021] OK

/

[Sat Sep 25 19:40:26 CST 2021] Using ACME_DIRECTORY: https://acme-staging-v02.api.letsencrypt.org/directory

[Sat Sep 25 19:40:26 CST 2021] Using CA: https://acme-staging-v02.api.letsencrypt.org/directory

[Sat Sep 25 19:40:26 CST 2021] Run pre hook:'if [[ -d /var/run/s6/services/nginx ]]; then s6-svc -d /var/run/s6/services/nginx; fi'

[Sat Sep 25 19:40:26 CST 2021] Standalone mode.

[Sat Sep 25 19:40:27 CST 2021] Create account key ok.

[Sat Sep 25 19:40:27 CST 2021] Registering account: https://acme-staging-v02.api.letsencrypt.org/directory

[Sat Sep 25 19:40:28 CST 2021] Registered

[Sat Sep 25 19:40:28 CST 2021] ACCOUNT_THUMBPRINT='Ijx6TwmJDzj2GBEE3nQoHuW15aM0jUEzBSB-D4Ax8PE'

[Sat Sep 25 19:40:28 CST 2021] Creating domain key

[Sat Sep 25 19:40:28 CST 2021] The domain key is here: /config/acme.sh/******/******key

[Sat Sep 25 19:40:28 CST 2021] Single domain='******'

[Sat Sep 25 19:40:28 CST 2021] Getting domain auth token for each domain

[Sat Sep 25 19:40:31 CST 2021] Getting webroot for domain='******'

[Sat Sep 25 19:40:31 CST 2021] Verifying: ******

[Sat Sep 25 19:40:31 CST 2021] Standalone mode server

[Sat Sep 25 19:40:37 CST 2021] Success

[Sat Sep 25 19:40:37 CST 2021] Verify finished, start to sign.

[Sat Sep 25 19:40:37 CST 2021] Lets finalize the order.

[Sat Sep 25 19:40:37 CST 2021] Le_OrderFinalize='https://acme-staging-v02.api.letsencrypt.org/acme/finalize/27789818/613699218'

[Sat Sep 25 19:40:38 CST 2021] Downloading cert.

[Sat Sep 25 19:40:38 CST 2021] Le_LinkCert='https://acme-staging-v02.api.letsencrypt.org/acme/cert/fa7c00393d1b6bc9a73013595439bda82cf6'

[Sat Sep 25 19:40:39 CST 2021] Cert success.

-----BEGIN CERTIFICATE-----

MIIFVzCCBD+gAwIBAgITAPp8ADk9G2vJpzATWVQ5vags9jANBgkqhkiG9w0BAQsF

ADBZMQswCQYDVQQGEwJVUzEgMB4GA1UEChMXKFNUQUdJTkcpIExldCdzIEVuY3J5

cHQxKDAmBgNVBAMTHyhTVEFHSU5HKSBBcnRpZmljaWFsIEFwcmljb3QgUjMwHhcN

MjEwOTI1MTA0MDM4WhcNMjExMjI0MTA0MDM3WjAbMRkwFwYDVQQDExBwYWxtcHJp

bnQub25saW5lMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt1MJV3Xm

p2mk6tAu88PT72veg0FNrRrteItoSVMsOCK4Ks8/bIoHA0RFWgvc8u+4KixIEFgM

pW/R7hZwZwccnTNNtQs/I5iODU6fxnglU0Io7bnH3rP7YZUdhcO9O1dDLQ6PUAY8

PPPmFMMxrsGnG0I3IFXrpy/gEdzl82UBCqaL+TjJj8f6ge3GTmGByjMuywwIdqOX

cmkN7qqoFrz5mXv8HbNsMfd+ZVeX4RV6MiA5n5DgSs+/8/XPMWVd7gzPe6+TFmtZ

zYfwbi+6bOduFND+mh9wR5dKbAzzdEl2UOyPWW1UeyaViSVPOhIqCxcBhS8WJK2q

rAUY77bk90F/wQIDAQABo4ICVDCCAlAwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQW

MBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBST

c3uWp1RJEjQQ5tMtiGD9EH4+FjAfBgNVHSMEGDAWgBTecnpI3zHDplDfn4Uj31c3

S10uZTBdBggrBgEFBQcBAQRRME8wJQYIKwYBBQUHMAGGGWh0dHA6Ly9zdGctcjMu

by5sZW5jci5vcmcwJgYIKwYBBQUHMAKGGmh0dHA6Ly9zdGctcjMuaS5sZW5jci5v

cmcvMBsGA1UdEQQUMBKCEHBhbG1wcmludC5vbmxpbmUwTAYDVR0gBEUwQzAIBgZn

gQwBAgEwNwYLKwYBBAGC3xMBAQEwKDAmBggrBgEFBQcCARYaaHR0cDovL2Nwcy5s

ZXRzZW5jcnlwdC5vcmcwggEFBgorBgEEAdZ5AgQCBIH2BIHzAPEAdgAW6GnB0ZXq

18P4lxrj8HYB94zhtp0xqFIYtoN/MagVCAAAAXwcwdgVAAAEAwBHMEUCIFerk6Nk

v38OQ2y9eC9Kp1mJqRGFDFNLJZHBJMVJGIMdAiEAoPt30ecVu6ElFimvlu3Q8z4k

eMMiLoAYaNQuwK0uW0AAdwDdmTT8peckgMlWaH2BNJkISbJJ97Vp2Me8qz9cwfNu

ZAAAAXwcwdoNAAAEAwBIMEYCIQD0dJouHhNj1FIIXE/bMJQ6MV/IJDd4jt4x791R

bniB0QIhAPazUZyh4Y/30LwIDdYCL94Ldeln2gXkyUUWAyhgUVLEMA0GCSqGSIb3

DQEBCwUAA4IBAQCjIS9fys3gtvCjKqNYn4gDe483Tn5LRFhE8cSiqHbQRsvsPmPA

kFdkxpFfVJeddyHJulqbOKJIMgV7Q2tOoXq8NQ/BRvvgF8kIs09e7GKzrNFk+BEb

UVZnIRVGU1L1gwh971iDo61yNrVGe8kjuLWN6B9+iWBA1F748wIj1jrgjZBzREXB

zOmXk8JO1L5jfX+1rh5aUdPvZwlCh9A0LUSWHC2RghZMUY4k45xEF2CVWDA3kdEO

W4skCpi8af40ht/90wdXv2fUpf7yZwBIJY20me36XvzbDGQlnuBUPktJ696KNnj8

BJXQW9DFNEIrJvkjB9vCgc4EsJYlwk4XbVv7

-----END CERTIFICATE-----

[Sat Sep 25 19:40:39 CST 2021] Your cert is in  /config/acme.sh/******/******cer 

[Sat Sep 25 19:40:39 CST 2021] Your cert key is in  /config/acme.sh/******/******.key 

[Sat Sep 25 19:40:39 CST 2021] The intermediate CA cert is in  /config/acme.sh/******ca.cer 

[Sat Sep 25 19:40:39 CST 2021] And the full chain certs is there:  /config/acme.sh/******/fullchain.cer 

[Sat Sep 25 19:40:39 CST 2021] Run post hook:'if [[ -d /var/run/s6/services/nginx ]]; then s6-svc -u /var/run/s6/services/nginx; fi'

[Sat Sep 25 19:40:39 CST 2021] Installing key to:/config/acme-certs/******/key.pem

[Sat Sep 25 19:40:39 CST 2021] Installing full chain to:/config/acme-certs/******/fullchain.pem

[cont-init.d] 10-config: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

**Comment by godpit** [comment]
<img width="419" alt="QQ20210925-195119@2x" src="https://user-images.githubusercontent.com/34534331/134770765-154ba8cb-43b7-422d-97dd-3e031c0190b6.png">

**Comment by godpit** [comment]
And then， this will cause Android SDK to request config.js file failed.

**Comment by saghul** [comment]
You have enabled the staging mode of Let's Encrypt. That yields invalid certificates, only useful for testing on desktop browsers and the mobile apps need a valid cert.
