### ISSUE TITLE
Colibri WebSocket doesn't work with default Jitsi Docker setup

### ISSUE THREAD

**Issue by preetmishra** [jitsi/docker-jitsi-meet#1129]
I have a standard Jitsi Meet Docker setup on AWS EC2. Everything seems to be working well but when the meeting participants are more than 2, the video quality drops down to the lowest. I read somewhere in Jitsi Forum that this is potentially due to Colibri. I keep getting the following set of errors as Colibri WebSocket does not work.

I'd greatly appreciate any pointers to help fix the issue. 

Please let me know if any additional information is required.

**Jitsi Web Logs**
```
2021/09/27 12:48:48 [error] 259#259: *100 upstream timed out (110: Connection timed out) while connecting to upstream, client: 172.31.67.133, server: _, request: "GET /colibri-ws/172.21.0.5/477c6fda2f5f712e/93ecfab9?pwd=5ukh8fj956sbsfcvvrf7gsvdld HTTP/1.1", upstream: "http://172.21.0.5:9090/colibri-ws/172.21.0.5/477c6fda2f5f712e/93ecfab9?pwd=5ukh8fj956sbsfcvvrf7gsvdld", host: "meet.nbl.one"
172.31.67.133 - - [27/Sep/2021:12:48:48 +0000] "GET /colibri-ws/172.21.0.5/477c6fda2f5f712e/93ecfab9?pwd=5ukh8fj956sbsfcvvrf7gsvdld HTTP/1.1" 504 590 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36"
```

**Chrome Screenshot**

![image](https://user-images.githubusercontent.com/43616959/134910005-0fb4b0a8-7a95-4611-9498-426e30f81c8d.png)

**Comment by saghul** [comment]
Can the web container reach 172.21.0.5 on port 9090 ?

**Comment by preetmishra** [comment]
There was an with IP configuration issue. This has been resolved. See https://community.jitsi.org/t/colibri-websocket-doesnt-work-with-default-jitsi-docker-setup/105859/14.
