### ISSUE TITLE
Modify Welcome Page of Jitsi 

### ISSUE THREAD

**Issue by bstaylor12** [jitsi/docker-jitsi-meet#1133]
Hi,

I have jitsi running with docker. How would I modify the jitsi welcome page to reflect banners? I am looking at the .jitsi-meet-cfg/web directory and I see a config.js file. Would this be where I would make a change? Would it reflect in the container after the container is restarted?

Thanks,
Brittany

**Comment by saghul** [comment]
You would need to rebuild the image.

Please post in our community for such questions.
