### ISSUE TITLE
Ldapauth not working in stable-6173

### ISSUE THREAD

**Issue by denis-robel** [jitsi/docker-jitsi-meet#1136]
I configured the .env in the right way, other containers binding well with the same credentials to my ldap server.

Then I made some investigations:
in prosody container:
1. /etc/default/saslauthd
start=no
 and 
MECHANISMS="pam"

is that correct? I would expect start=yes and MECHANISMS="ldap"

**Comment by Zarawee** [comment]
Hi, can you post your LDAP config in your .env, and the structure of LDAP DB where the user are looked.

**Comment by denis-robel** [comment]
Am Dienstag, 23. November 2021, 23:45:42 CET schrieb Zarawee:
> Hi, can you post your LDAP config in your .env, and the structure of LDAP DB
> where the user are looked.
Hi you can close this problem because I had a problem in my docker network.

The jitsi container was not able to connect with ldap container. I modified the
networks of prosody and of openldap container. Now all is working well.

--
-

Best regards Denis
