### ISSUE TITLE
Your device may be offline or our servers may be experiencing problems.

### ISSUE THREAD

**Issue by godpit** [jitsi/docker-jitsi-meet#1138]
Suddenly, the domain name cannot be accessed, and IP access is possible.

<img width="437" alt="QQ20211012-001912@2x" src="https://user-images.githubusercontent.com/34534331/136823216-5e8f3025-288c-4690-82d4-9a8cefdfef24.png">

**Comment by godpit** [comment]
The web service container has no access logs

**Comment by godpit** [comment]
It is possible to access services with IP

**Comment by godpit** [comment]
You can't access 80 with the domain name. I can access it through IP

**Comment by tuanmeo01** [comment]
I'm encountering the same issue; could you suggest a solution?

**Comment by Xjifn** [comment]
same problem with jitsi meet if anyone got a way to fix it?

**Comment by tuanmeo01** [comment]
@Xjifn the problem I had was SSL expired, I renewed the SSL to fix it

**Comment by alexander-potemkin** [comment]
My user got the same error. Reloaded a few times and it started to work.
