### ISSUE TITLE
Lets Encrypt autorenew

### ISSUE THREAD

**Issue by roeycohen** [jitsi/docker-jitsi-meet#114]
it seems like the master branch will not auto renew the letsencrypt certificate automatically.

i had to run "/defaults/letsencrypt-renew" manually from within the container...

am i missing something? :)

**Comment by saghul** [comment]
Do you have anything in `/etc/cron.monthly/` ?

Also, does the log in `/config/` say anything useful?

**Comment by roeycohen** [comment]
hi @saghul sorry for my (very) late reply :)

- there's "letsencrypt-renew" script inside this directory and it has the X attribute.
- "/config/le-renew.log" seems updated. (not sure if it was my last manual update or by cron).
- cron service is running.

still i got notification by mail from letsencrypt about the certificate that is about to expire...

just for common knowledge, are scripts inside /etc/cron.{hourly,daily,weekly,monthly} runs automatically by root user? because running:
`for user in $(cut -f1 -d: /etc/passwd); do crontab -l $user 2>/dev/null; done`
says no user has a jobs defined.

**Comment by saghul** [comment]
>     * "/config/le-renew.log" seems updated. (not sure if it was my last manual update or by cron).

Does it have any content?



> just for common knowledge, are scripts inside /etc/cron.{hourly,daily,weekly,monthly} runs automatically by root user?

Yep, AFAIK.



> because running:
> `for user in $(cut -f1 -d: /etc/passwd); do crontab -l $user 2>/dev/null; done`
> says no user has a jobs defined.

This is not a crontab so that's somewhat expected.

I'm trying to debug this now, I moved the renew script to the hourly cron, let's see.

**Comment by saghul** [comment]
This is what I'm getting in the logs:

```
root@5358cdba36c4:/# cat /config/le-renew.log

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/meet.saghul.net.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

The following certs are not due for renewal yet:
  /etc/letsencrypt/live/meet.saghul.net/fullchain.pem expires on 2019-10-22 (skipped)
No renewals were attempted.
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
```

So it looks like it's working.

**Comment by roeycohen** [comment]
i can see that the file was updated on july 5th:

![image](https://user-images.githubusercontent.com/2613845/61878525-d8dd9200-aef9-11e9-9ab5-d00ac75fabad.png)

it's content is (domain was changed):

```
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Processing /etc/letsencrypt/renewal/example.com.conf
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
new certificate deployed without reload, fullchain is
/etc/letsencrypt/live/example.com/fullchain.pem
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Congratulations, all renewals succeeded. The following certs have been renewed:
  /etc/letsencrypt/live/example.com/fullchain.pem (success)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

```

i guess we should wait to the next month to see what happens...

**Comment by saghul** [comment]
🤞

**Comment by roeycohen** [comment]
hi @saghul, hope you're doing well :)

From what i see the monthly job did NOT run.
That's weird, because according to this: https://unix.stackexchange.com/a/509873/307495 the job should have run at august 1st. 

Running the job command manually did update the /config/le-renew.log file
`test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.monthly )`

The cron daemon is also running:
![putty_1D9hRPmCiY](https://user-images.githubusercontent.com/2613845/62684633-c0757900-b9c9-11e9-94f8-c2564aa94473.png)

😱😱😱

**Comment by klehmann** [comment]
Do I see this right that the Let's Encrypt renewal is not enabled by default, but has to be run manually or configured as a cronjob?
Just tried ```crontab -e``` from within the container:
```
root@fd9296092f2c:/etc/cron.monthly# crontab -e
no crontab for root - using an empty one
/usr/bin/sensible-editor: 25: /usr/bin/sensible-editor: editor: not found
/usr/bin/sensible-editor: 28: /usr/bin/sensible-editor: nano: not found
/usr/bin/sensible-editor: 31: /usr/bin/sensible-editor: nano-tiny: not found
/usr/bin/sensible-editor: 34: /usr/bin/sensible-editor: vi: not found
Couldn't find an editor!
Set the $EDITOR environment variable to your desired editor.
crontab: "/usr/bin/sensible-editor" exited with status 1
```
So there does not seem to be any editor installed in the container. What's the recommended way to do this in an easy way?
I would have loved to find a section about the LE cert renewal in the Docker documentation at:
https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#lets-encrypt-configuration

Fortunately I found this Github issue that describes I have to run ```/defaults/letsencrypt-renew``` to do this.

**Comment by saghul** [comment]
Based on the lack of updates I thought we had fixed this already.

**Comment by jkowens** [comment]
@saghul the letsencrypt cert is not getting renewed for us. It seems like others are having this issue too:

https://github.com/jitsi/docker-jitsi-meet/pull/1079

Should the cert get renewed without having to restart the container?
