### ISSUE TITLE
Jitsi Meet Screensharing Not Working: Receiving a Grey Screen

### ISSUE THREAD

**Issue by bstaylor12** [jitsi/docker-jitsi-meet#1149]
Hi,

I have almost completed my jitsi install (installed with kubernetes). I have a few questions:

How do I disable the “failed to access your microphone/failed to access your camera” messages from showing when a conference starts (there are no camera or mic capabilities for my setup )?

I have the JVB_PORT set to 10000 udp, and enabled the port on a security group. However, when I try to share my screen with another user, they continue to get a grey screen instead of what I am sharing. Why is this?

Thanks

**Comment by bstaylor12** [comment]
Oh, right now I have the ENABLE_COLIBRI_WEBSOCKET set to 0. Should I change it to 1 to enable it?

**Comment by bstaylor12** [comment]
Setting ENABLE_COLIBRI_WEBSOCKET=1 made the bridge channel errors go away. I have ENABLE_SCTP=1 and ENABLE_XMPP_WEBSOCKET=0. I am still not able to screenshare. Are these settings affecting screensharing?

I am also getting these errors: 

![image](https://user-images.githubusercontent.com/82893038/138103854-61453bca-5dff-485f-983b-40d340c51d26.png)

![image](https://user-images.githubusercontent.com/82893038/138104215-851b870b-f65c-4af7-bca7-3e3e71d5e67a.png)

Logger.js:154 2021-04-21T15:29:15.542Z [modules/xmpp/strophe.jingle.js] getting turn credentials with extdisco:2 failed, trying extdisco:1 <iq xmlns=​"jabber:​client" type=​"error" to=​"mikey@meet.civicrm.community/​pS4G1fzo" id=​"d17b8885-9eb0-47d7-a735-724ecb91ace1:​sendIQ" from=​"meet.civicrm.community">​…​</iq>​
o @ Logger.js:154

**Comment by bstaylor12** [comment]
Hi, 

I was able to get rid of the red error messages in the network console. However, screensharing is still not working after getting the ports enabled on the security group. 

I am seeing errors similar to the logs below in the jicofo container in my kubernetes service: 


Jicofo 2018-01-15 20:51:58.472 SEVERE: [26] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.log() Failed to connect/login: The followi
ng addresses failed: 'localhost:5222' failed because: localhost/127.0.0.1 exception: java.net.ConnectException: Connection refused (Conn
ection refused)
org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'localhost:5222' failed because: localhost/12
7.0.0.1 exception: java.net.ConnectException: Connection refused (Connection refused)
        at org.jivesoftware.smack.SmackException$ConnectionException.from(SmackException.java:278)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:618)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:890)
        at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:379)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.doConnect(XmppProtocolProvider.java:248)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.access$000(XmppProtocolProvider.java:57)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider$1.call(XmppProtocolProvider.java:229)
        at org.jitsi.impl.protocol.xmpp.XmppProtocolProvider$1.call(XmppProtocolProvider.java:224)
        at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

![image](https://user-images.githubusercontent.com/82893038/138352554-c4790967-070b-4281-a9f8-fdc420d3ad3e.png)
 

Please help. Thank you.

**Comment by bstaylor12** [comment]
@saghul Hi, 

We decided to deploy Jitsi with Docker. However, with more than two users, we are not able to screenshare. We receive a grey screen still. We have port 10000 UDP enabled and all the other ports enabled. When we open the web console, we receive the message Bridge Channel send: no opened channel. 
Is there something in the configurations I am missing? Please help.

**Comment by saghul** [comment]
How does your .env file look like?

**Comment by bstaylor12** [comment]
Good Morning @saghul 

Here is a example of my .env file. I did not include the actual Public URL and docker_host address for security purposes. 
[sample env .txt](https://github.com/jitsi/docker-jitsi-meet/files/7588204/sample.env.txt)

**Comment by bstaylor12** [comment]
Good Morning @saghul 

When you have a chance, can you please provide feedback. Please let me know if I have configured something wrong. The po￼rts are open but still experiencing the bridge channel send: no open channel error.

Our port forwarding looks like this:

TCP 443 >>>> 443
UDP 10000 >>>> 10000

We are using a network load balancer within AWS as well.

Please help.

**Comment by ozgur0** [comment]
Greetings @bstaylor12 
I have the same problem, did you happen to find any kinda solution?

**Comment by bstaylor12** [comment]
Hi @ozgur0, 

 I had a tough time figuring this out. I ended up changing my docker ip address to the public address of my load balancer. I took 443 off the end of my public URL: old: https://my.jitsi.url.com: 443 >>> new https://my.jitsi.url.com. I changed the following environment variables: 
ENABLE_XMPP_WEBSOCKET=1
ENABLE_COLIBRI_WEBSOCKET=1
ENABLE_SCTP=0
JVB_PORT=10000

Be sure to enable UDP 10000 and TCP 443 on your firewall and add to your security group. 
 
This is the bulk of what I did. If I think of anything else, I will add it here tomorrow.

**Comment by ozgur0** [comment]
Hi @bstaylor12 thank you very much for the answer, I'll give it a shot

**Comment by tranhoangnguyen193** [comment]
hi @bstaylor12, how did you do with docker IP addresses, do you use the env:
DOCKER_HOST_ADDRESS

**Comment by bstaylor12** [comment]
Hi @tranhoangnguyen193 

I changed my docker_address to be the public IP address of my network load balancer. If you're using AWS, you can find this under EC2>>>Network & Security>>>> Network Interfaces.
