### ISSUE TITLE
jibri build with dockerfile stucked at xserver-xorg-video-dummy

### ISSUE THREAD

**Issue by tifcty1** [jitsi/docker-jitsi-meet#1152]
Hi,
I built docker-jitsi-meet in release 6433, the meeting works fun.
But when I wanted to record the video, it said the driver only suppor chromedriver 95, so I changed the jibri's Dockerfile, and built it from source. 

The problem is, when I built the command in Dockerfile "RUN apt-dpkg-wrap apt-get update ", It always stucked at the "xserver-xorg-video-dummy" Even I changed the apt source

This is the output.
```
...
Get:200 http://mirrors.163.com/debian buster/main amd64 libfontenc1 amd64 1:1.1.3-1+b2 [24.4 kB]
Get:201 http://mirrors.163.com/debian buster/main amd64 libxfont2 amd64 1:2.0.3-1 [135 kB]
Get:202 http://mirrors.163.com/debian buster/main amd64 xserver-xorg-core amd64 2:1.20.4-1+deb10u3 [3542 kB]
Get:203 http://mirrors.163.com/debian buster/main amd64 xserver-xorg-video-dummy amd64 1:0.3.8-1+b1 [19.1 kB]
```

Anyone who can help me please.

**Comment by saghul** [comment]
Looks like a network issue contacting the Debian servers.

Have you tried our Jibri builds? Why do you need to build your own?

**Comment by tifcty1** [comment]
Thanks for reply. 
I built my image because I wanted to change jibri.conf directly and change chromium driver version.
And now I run the official image, then record to mp4, 
but I can't play it. It only shows a taskbar below and no sounds. 

![jitsi](https://user-images.githubusercontent.com/22765439/140267073-b6e8253c-024c-4030-903b-c1ad7c14093d.png)

**Comment by tifcty1** [comment]
I fixed it by change chromium flags,  just remove the --headness flag.

**Comment by saghul** [comment]
Is that a flag you set yourself? I don't think we do.

**Comment by tifcty1** [comment]
Yes, my bad. I didn't know what flags shoud be set when I wanted to ignore the ssl error, so I copyed them from the jitsi community and didn't know what exactly these flgas mean.
And after compared the chromium flag in  jibri's repository with mine, I found that it was the --headness flag raised the question.
