### ISSUE TITLE
Web iOS devices - Problem with camera and mic in version stable-6433

### ISSUE THREAD

**Issue by protoshub** [jitsi/docker-jitsi-meet#1153]
Camera and microphone cannot be detected in iOS web. Same symptoms in self-host of version stable-6433 and in https://meet.jit.si

The weird thing is I can see myself from the camera but in the device setting, none can be detected. The others also cannot see or hear anything from iOS device.

**Comment by saghul** [comment]
Can you reliably reproduce this on meet.jit.si? What iOS version do you have? What exact steps do you follow to run into problems?

**Comment by protoshub** [comment]
Yes, it happens every time. No special steps, just start a meeting and go to the setting. When I posted the issue, both camera and mic can be found. But today, only mic cannot be found.

![0940741A-78DA-4F61-BFEF-AB9B72AEAD39](https://user-images.githubusercontent.com/42835662/143509914-01330dee-d174-4398-995d-0130ef95a960.jpg)

I'm using iOS 14.8.1

**Comment by saghul** [comment]
Ah that is actually how it's currently implemented.

iOS does not allow to use multiple devices at once, which the settings dialogs uses for preview, so we temporarily disabled it while we work on a better UI for that dialog.

**Comment by protoshub** [comment]
I see. But the other end of the conference room also cannot hear or see the iOS user. Is it your intention too?

**Comment by saghul** [comment]
Obviously not :-) Please give the unstable / nightly images a try, this has been fixed recently and is not part of the current stable images.

**Comment by protoshub** [comment]
I did try but the problem still remains T-T

**Comment by saghul** [comment]
Ok, let's take a step back then. What audio devices are you using and what is happening when you join a meeting with Safari? How many participants are there? What device are they using?

**Comment by protoshub** [comment]
2 participants
Participant 1 => Safari on iOS, build-in audio
Participant 2 => Chrome on android, build-in audio

Participant 2 cannot see or hear participant 1
Participant 1 can see and hear participant 2

**Comment by saghul** [comment]
I don't have iOS 14 at hand, but I could not reproduce this with iOS 15.
