### ISSUE TITLE
When updating to stable-6433 jitsi-meet-electron crashes when joining a room

### ISSUE THREAD

**Issue by cedricroijakkers** [jitsi/docker-jitsi-meet#1156]
I'm running Jitsi in Kubernetes for quite some time now, and all is working well. However, when updating to stable-6433 and then trying to join a room with the jitsi-meet-electron app on Linux (but also heard complains from people working on MacOS, not sure about Windows) the desktop client fully crashes. Joining by browser works fine, but joining by desktop app is impossible. The crash is also so severe, that the F5 key to refresh the electron app does absolutely nothing anymore. The only solution is to stop the electron app, and re-start it. Re-joining the room on the stable-6433 server then instantly crashes it again.

Rolling back to stable-6173 instantly solves the issue (after restarting the desktop app of course).

So far I've been able to reproduce this with the desktop app versions 2.9.1, 2021.11.1, 2021.11.2, and 2021.12.1. So I think it must be something server-side.

**Comment by saghul** [comment]
Please follow-up here: https://github.com/jitsi/jitsi-meet-electron/issues/649

It cannot be server side, since it's the client that crashes when loading the content.
