### ISSUE TITLE
/etc/ldap and /etc/ldap/ldap.conf missing in prosody container

### ISSUE THREAD

**Issue by psych0d0g** [jitsi/docker-jitsi-meet#1158]
just updated to the latest commits using bullseye as base image today, said file and folder are nonexistant and therefor break ldap authentication via ldaps.
no idea as of yet where those files came from in the former images so i cant fix it properly right now, as a workaround i added the file in my local builds statically

**Comment by ajippes** [comment]
Same here stable-6726 :(

**Comment by saghul** [comment]
I don't have a LDAP setup to test this on, if a file is missing, can you please send a PR? Thanks!

**Comment by PeerD** [comment]
I fixed it by copying the file from my host system aswell as a short term fix (Thank you psych0d0g for the hint to solve this!). As I see it, there are two ways to solve this problem. Copy the file in manually or add the [libldap-common](https://packages.debian.org/bullseye/libldap-common) package. I'm note sure which way you would prefer.

This is the default content of the debian /etc/ldap/ldap.conf file which works if I just mount it in. Only the last 3 lines are really relevant.
```
#
# LDAP Defaults
#

# See ldap.conf(5) for details
# This file should be world readable but not world writable.

#BASE   dc=example,dc=com
#URI    ldap://ldap.example.com ldap://ldap-master.example.com:666

#SIZELIMIT      12
#TIMELIMIT      15
#DEREF          never

# TLS certificates (needed for GnuTLS)
TLS_CACERT      /etc/ssl/certs/ca-certificates.crt

TLS_REQCERT allow
TLS_REQCERT allow
```

**Comment by xoxys** [comment]
`libldap-common` is not installed anymore (is installed in stable-6433 but not in the latest release), that's why `/etc/ldap` directory is missing. I'll prepare a PR.

**Comment by psych0d0g** [comment]
good find xoxys, i wasnt able to pin the file down to a specific package, that makes a permanent fix easy :)

**Comment by xoxys** [comment]
As an alternative workaround, you can also bind mount a custom s6 init step into the container:

```Shell
[~] # cat /etc/jitsi/prosody-00-custom 
#!/usr/bin/with-contenv bash
apt update -qq && apt-get upgrade -yqq libldap-common
---

docker run [...] --mount 'type=bind,src=/etc/jitsi/prosody-00-custom,target=/etc/cont-init.d/00-custom'
```
