### ISSUE TITLE
Use latest jitsi web version 2.0.6689 (2021-12-06)

### ISSUE THREAD

**Issue by tanandy** [jitsi/docker-jitsi-meet#1160]
Hi,

A new version is available so i create an issue for it to prepare a future tag release.

Thank you

**Comment by saghul** [comment]
The fact that a new stable Debian package release is out doesn't mean the Docker one is ready. Please just wait.

**Comment by tanandy** [comment]
sure but why cant we create an issue about this ?

**Comment by damencho** [comment]
As, this is not an issue, and creating one does not help speed up the process.

**Comment by saghul** [comment]
All it does is stress people out.

**Comment by tanandy** [comment]
ok sorry was not my intention, just adding reminder in the backlog :)
