### ISSUE TITLE
Strophe: Server did not yet offer a supported authentication mechanism.

### ISSUE THREAD

**Issue by mehmetgulek81** [jitsi/docker-jitsi-meet#1161]
Hi all.

I am new to Jitsi. I recently installed jitsi on my domain, say mydomain.com, on an ubuntu. I also enabled secure domain. It was working well, asking passwords.

After I tried to enable JWT authentication, whenever I call https://mydomain.com/room1?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ.... or even https://mydomain.com/room1 without any token, I get the following error:

Strophe: Server did not yet offer a supported authentication mechanism.

In https://github.com/jitsi/docker-jitsi-meet/issues/87, it says "add following jitsi-meet.cfg.lua file...", but I don't have that file; instead I have /etc/prosody/conf.d/mydomain.com.cfg.lua file. I changed it. And secondly it says "in the client side, change "JitsiMeetJS.JitsiConnection" configuration to:...". What is it meant here? /usr/share/jitsi-meet-web-config/config.js file? Changing it doesn't solve the problem too. Is the problem with the token I send?

Thanks in advance.

**Comment by prayagsingh** [comment]
@mehmetgulek81 Are you using docker for your deployment?

**Comment by mehmetgulek81** [comment]
I didn't install Jitsi myself actually. I don't know. But the admins followed the instructions on https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart https://jitsi.github.io/handbook/docs/devops-guide/secure-domain and https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md#installing-the-token-plugin

**Comment by saghul** [comment]
> I didn't install Jitsi myself actually. I don't know. But the admins followed the instructions on https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart https://jitsi.github.io/handbook/docs/devops-guide/secure-domain and https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md#installing-the-token-plugin

That means you are not using the Docker setup. Please post in our community instead: https://community.jitsi.org/
