### ISSUE TITLE
Prosody configuration missing STUN parameter

### ISSUE THREAD

**Issue by fwagner-smf** [jitsi/docker-jitsi-meet#1177]
The prosody docker image should have an option to provide a STUN Server, similar to TURN(S) servers.

https://github.com/jitsi/docker-jitsi-meet/blob/81dc3849b18b734ea20c8ed9281df14353615603/prosody/rootfs/defaults/conf.d/jitsi-meet.cfg.lua#L39-L51 

Should I provide a PR? Or is there a deeper reaseon, why this is not exposed in the docker images configuration?

**Comment by damencho** [comment]
The stun servers are coming from config.js.

**Comment by fwagner-smf** [comment]
In many STUN/TURN setup guides, there is an additional stun entry for `external_services`. I thought, the web/lib-jitsi-meet might do a service (discovery) lookup with at the xmpp server for the stun/turn entries?

So you say, it is sufficient, to configure 
```    config.p2p = {
        enabled: true,
        useStunTurn: true,
        stunServers: [
            { urls: 'stun:stun.server:443' }
        ]
    };```
? This is also not explicitly exposed.

Thanks.

**Comment by damencho** [comment]
Yep. The thing is that stun is needed only for p2p. To be able to communicate with jvb you don't need it, you may only need as fallback turns in some network conditions.

**Comment by fwagner-smf** [comment]
OK, thank you,
