### ISSUE TITLE
How to upgrade?

### ISSUE THREAD

**Issue by gerroon** [jitsi/docker-jitsi-meet#118]
Hi

I realize this is not directly a Jitsi-Meet issue but how do I update/upgrade the docker-compose here? It is easy with docker with pull but not sure how I cna upgrade Jitsi-Meet with docker-compose.

thanks

**Comment by sapkra** [comment]
You can pull the new images with `docker-compose pull` if there are new published.
https://docs.docker.com/compose/reference/pull/

**Comment by gerroon** [comment]
That easy! Thnask for the reply
