### ISSUE TITLE
DOMException: Failed to construct 'RTCPeerConnection'

### ISSUE THREAD

**Issue by alsan1997** [jitsi/docker-jitsi-meet#1182]
**ISSUE**

Hi, i'm not able to see other's video and voice. It has been working perfectly previously and for some reason got this new error.

This is my browser's console log
```
UnhandledError: null Script: null Line: null Column: null StackTrace:  DOMException: Failed to construct
'RTCPeerConnection': Plan B SDP semantics is a legacy version of the Session Description Protocol that has severe 
compatibility issues on modern browsers and is no longer supported. See 
https://www.chromestatus.com/feature/5823036655665152 for more details, including the possibility of registering for a Deprecation Trial in order to extend the Plan B deprecation deadline for a limited amount of time.
```

**Docker jitsi meet version**

jitsi/web:stable-5142

**[UPDATE]**

The error only happens when i'm using Chrome

The video call is successful using Safari / Firefox

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

Update your deployment. Latest few stable releases use Unified plan. Chrome has dropped support for PlanB since Chrome 96.
