### ISSUE TITLE
Settings from custom-config.js are not applied

### ISSUE THREAD

**Issue by Antonditto** [jitsi/docker-jitsi-meet#1183]
Good afternoon, the latest version of Jitsi stable-6726-1: release is being used. There is a task to turn off the notification about the beginning and end of the recording. Judging by config.js, you need to add the line to custom-config.js
`config.disabledSounds = ['RECORDING_ON_SOUND', 'RECORDING_OFF_SOUND'];`
But this does not work, please tell me, am I filling out the custom-config.js correctly, or do I need to do it somehow differently?

**Comment by saghul** [comment]
Do you see that line in the generated config.js file?

**Comment by Antonditto** [comment]
Yes, the line appears when the container is created.

**Comment by saghul** [comment]
Try setting the deprecated property: "disableRecordAudioNotification" to true. Maybe we have a bug in there...

**Comment by Antonditto** [comment]
I tried this too, it still doesn't work.

**Comment by saghul** [comment]
There might be a bug in the latest release then, oops!

**Comment by Antonditto** [comment]
Found a problem, some config lines were not correct. They were higher than config.disabledSounds = ['RECORDING_ON_SOUND', 'RECORDING_OFF_SOUND'] ;. Therefore, it seems that the parser did not even reach these settings. As soon as I removed these incorrect lines, everything started.

**Comment by saghul** [comment]
Excellent!
