### ISSUE TITLE
Enabling Octo - why is port 4096 missing from jvb in docker-compose?

### ISSUE THREAD

**Issue by pandel** [jitsi/docker-jitsi-meet#1188]
Hi!

If I enable Octo via ENABLE_OCTO everything is setup as it should be, BUT the docker-compose.yml is missing exposed port 4096 for the JVB to actually accept traffic from additional JVBs. As noted in the official documentation, for Octo to work correctly you need that port to be open so that the JVBs can communicate with each other.

I could not get Octo to work correctly between two Docker nodes unless I modified docker-compose accordingly. Is this somehow missing or am I missing something here?

Regards,
Holger

**Comment by saghul** [comment]
It's missing yes. The reason why it's probably missing is that you need more than one JVB for octo to work but the default setup only has a single JVB so I guess it was forgotten since those using octo are using a (slightly) modified setup already.

**Comment by pandel** [comment]
Ah thanks! What do you mean by "slightly modified setup"? Is there something one can additionally download somewhere? I am using multiple JVBs and a "slightly" modified setup myself, but have written a script framework around docker-jitsi-meet to apply all of my changes and configuration details after a fresh git clone. If there is something already I could use, I'd be thankful!

**Comment by saghul** [comment]
By slightly modified I mean for instance creating some jvb2, jvb3 etc xml files to launch more JVBs in different ports. Everything should be possible with the current env vars though. Plus exposing the port of course.
