### ISSUE TITLE
[FR] Please make MUC_NICKNAME configurable via .env

### ISSUE THREAD

**Issue by pandel** [jitsi/docker-jitsi-meet#1189]
Hi!

It would be very comfortable if MUC_NICKNAME could be configured via .env. The reason for that is, if you add i.e. Grafana to monitor your Jitsi environment, everytime you rebuild your JVB containers they get a new random hostname, which is currently being used as MUC_NICKNAME. If you then look into your Grafana history you get a bunch of random, unidentifiable JVB entries.

If we could provide our own MUC_NICKNAME, then the data could be held consistent over all container rebuild. You could simply give them different numbers or even set the real hostname as a reference in your monitoring data.

I.e. I have two JVBs, one in the normal docker-jitsi-meet setup and an additional one. I changed MUC_NICKNAME after firing up the container and restarting JVB inside. That works great, my data is consistent, but it is a real mess always having to fire up a container, reaching into the running container, change MUC_NICKNAME and restart the JVB container without rebuilding.

Perhaps you could change the rule that sets up MUC_NICKNAME to either use .Env.HOSTNAME or use a custom value defined via .env. That would be great!

Regards,
Holger

**Comment by saghul** [comment]
Sounds reasonable. Care to make a PR?

**Comment by pandel** [comment]
I'll try to 👍

**Comment by pandel** [comment]
Here you are: https://github.com/jitsi/docker-jitsi-meet/pull/1191

**Comment by saghul** [comment]
Landed!
