### ISSUE TITLE
urgent:Two people joined the meeting,Reconnecting

### ISSUE THREAD

**Issue by YaYaGuan** [jitsi/docker-jitsi-meet#119]
No extranet，
Use docker jitsi meeting
When two people joined the meeting
<img width="1169" alt="WechatIMG343" src="https://user-images.githubusercontent.com/34049601/60941541-1c3cdb80-a312-11e9-96d3-5d06080143af.png">

**Comment by saghul** [comment]
First, there are no urgen issues here, sorry.

Now, onto your problem. I see you are running in a LAN environment. Did you follow https://github.com/jitsi/docker-jitsi-meet#running-on-a-lan-environment ? What do the JS console logs say?

**Comment by imakshath** [comment]
I encounter the same issue. When 2 peoples try to connect to a room its show below screen 

![Screenshot 2019-08-07 at 5 36 08 PM](https://user-images.githubusercontent.com/9428527/62621593-e5221000-b939-11e9-9362-d8a887267e80.png)

**Comment by saghul** [comment]
And have you followed the instructions on the link I shared above?

**Comment by saghul** [comment]
No follow-up, closing.

**Comment by EliterScripts** [comment]
I'm having the same issue. I am using an Apache2 proxy, that redirects HTTP traffic to HTTPS traffic, then proxies on the SSL server:
```
<IfModule mod_ssl.c>
<VirtualHost *:443>
	ServerName example.com
	ServerAdmin webmaster@localhost
	ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined
        SSLEngine on
	Protocols h2 http/1.1
	Header always set Strict-Transport-Security "max-age=63072000"
	Include /etc/letsencrypt/options-ssl-apache.conf
	SSLProtocol             all -SSLv3 -TLSv1 -TLSv1.1
	SSLCipherSuite          ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
	SSLHonorCipherOrder     off
	SSLSessionTickets       off
	SSLUseStapling On
	SSLCertificateFile /etc/letsencrypt/live/example.com/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/example.com/privkey.pem

	ProxyPass "/"  "http://172.17.0.1:8000/"
	ProxyPassReverse "/"  "http://172.17.0.1:8000/"

</VirtualHost>
</IfModule>
```

I have even tried using `ProxyPreserveHost On`, and it gives me the same issue. It gives the web, but when I enter a meeting, it gives me the issue. I have even tried putting `PUBLIC_URL=https://example.com` in `docker-jitsi-meet/.env` before starting up the servers with `docker-compose up -d`.

Is this a problem on my end? It was working, then I tried using it with multiple domains, and it stopped working. Maybe I screwed something up in the Apache2 proxy, was connecting it with more than one domain, the Github clone is now unstable?
