### ISSUE TITLE
[Docker] Failling to rendering template `<.Env.XMPP_MUC_DOMAIN>: invalid value`

### ISSUE THREAD

**Issue by bioinfornatics** [jitsi/docker-jitsi-meet#1195]
### Description:

While running compose, I got multiple various message that seems due the same original cause.
``` 
# podman-compose logs web
using podman version: podman version 3.3.1
podman logs jitsifoo_web_1
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-set-timezone: executing... 
[cont-init.d] 01-set-timezone: exited 0.
[cont-init.d] 10-config: executing... 
using keys found in /config/keys
fatal: render template error, caused:

   template: /defaults/system-config.js:11:45: executing "/defaults/system-config.js" at <.Env.XMPP_MUC_DOMAIN>: invalid value; expected string

[cont-init.d] 10-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
nginx: [emerg] invalid number of arguments in "proxy_pass" directive in /config/nginx/meet.conf:59
nginx: [emerg] invalid number of arguments in "proxy_pass" directive in /config/nginx/meet.conf:59
nginx: [emerg] invalid number of arguments in "proxy_pass" directive in /config/nginx/meet.conf:59
nginx: [emerg] invalid number of arguments in "proxy_pass" directive in /config/nginx/meet.conf:59

```

To my understanding `XMPP_MUC_DOMAIN` env var is not defined or not a string.
Thus:

1. this error is raised `template: /defaults/system-config.js:11:45: executing "/defaults/system-config.js" at <.Env.XMPP_MUC_DOMAIN>: invalid value; expected string` 
2. as the variable is not filled the file `/nginx/meet.conf` is incomplete
3. this error is raised `nginx: [emerg] invalid number of arguments in "proxy_pass" directive in /config/nginx/meet.conf:59`

### Steps to reproduce:

1. `curl -Lo/tmp/docker_jitsi.tar.gz https://github.com/jitsi/docker-jitsi-meet/archive/refs/tags/stable-6726-1.tar.gz`
2. `tar xf /tmp/docker_jitsi.tar.gz -C /var/www/jitsi.microbiomestudio.fr/ --strip-components=1`

### Actual behavior:
We can see from file `system-config.js` that `XMPP_MUC_DOMAIN` is filled from its corresponding env var

```bash
# grep XMPP_MUC_DOMAIN ./web/rootfs/defaults/system-config.js
{{ $XMPP_MUC_DOMAIN := .Env.XMPP_MUC_DOMAIN -}}
{{ $XMPP_MUC_DOMAIN_PREFIX := (split "." .Env.XMPP_MUC_DOMAIN)._0  -}}
config.hosts.muc = '{{ $XMPP_MUC_DOMAIN_PREFIX }}.'+subdomain+'{{ $XMPP_DOMAIN }}';
config.hosts.muc = '{{ $XMPP_MUC_DOMAIN }}';
```
The env file declare the expected variable
```bash
# grep XMPP_MUC_DOMAIN .env
XMPP_MUC_DOMAIN="muc.meet.jitsi"
```
I even defined the variable into the current bash session to ensure its presence.

Thanks for your helps

Best regards

**Comment by saghul** [comment]
We don't currently test with podman. Can you try docker-compose instead?

**Comment by bioinfornatics** [comment]
@saghul After a try, i can confirm it works with docker.
Netherless they are several problem in near future, as

1.  jitsi-meet do not support RHEL like OS it is not possible to install from source
2. RHEL like OS stop the support of docker

Thanks for your awesome works

Have a nice day

**Comment by saghul** [comment]
I'd welcome a PR fixing whatever is necessary to make it work in Podman. However, if podman claims to have full compatibility with vanilla Docker, it should all work unmodified.

**Comment by bioinfornatics** [comment]
@saghul Thanks for your answer.
I agree, that seems more a `podman-compose` problem
I tried to install from source jitsi-meet on a rocky linux but after some works  I chose an easier path using container so I tried first podman which fail.
Now I try with docker that works better but it is not the ideal case

**Comment by saghul** [comment]
Closing this this is a podman issue. Podman support is tracked at https://github.com/jitsi/docker-jitsi-meet/issues/201
