### ISSUE TITLE
DOCKER_HOST_ADDRESS is restricted to a single networking stack

### ISSUE THREAD

**Issue by almereyda** [jitsi/docker-jitsi-meet#1199]
Currently the `DOCKER_HOST_ADDRESS` only accepts one value, which most often will be an IPv6 address. In our dual stack configuration, we also would like to announce the public IPv6 address to peers, in case STUN/TURN does not work as expected.

Is it possible or advised to extend

https://github.com/jitsi/docker-jitsi-meet/blob/ae3e7e765126c8c46b3aeb229b9ce1bcfd2a048e/jvb/rootfs/defaults/jvb.conf#L92

and `jvb` in so both addresses can be announced?

Related:

#293 
#657 
#745

**Comment by saghul** [comment]
Yes, it's actually possible to support multiple addresses. This is also useful when you want the service to be accessible both in and out of a LAN.

At this point we need to rename the ill-named env var to something like `JVB_PUBLIC_ADDRESSES`

**Comment by alex-regelt** [comment]
This would  be really helpful for our current setup.

> This is also useful when you want the service to be accessible both in and out of a LAN.

This is exactly our use-case. It kind of works by setting `DOCKER_HOST_ADDRESS` to one IP address and have the other address discovered via STUN, but we'd like to disable outgoing connections completely. So if we could define both addresses statically that would be great.

My Java skills are very limited, but let me know if I can do anything else to help.

**Comment by saghul** [comment]
Multiple advertised support was just added: https://github.com/jitsi/docker-jitsi-meet/commit/c53de728cedf54edcbb94e104b3a45fd029f8b9d
