### ISSUE TITLE
No connection and 'prosody.cfg.lua' errors

### ISSUE THREAD

**Issue by tvld** [jitsi/docker-jitsi-meet#12]
First time user today.  Cloned this repo and and ``docker-compose up``. The containers build ok, but I can not connect on http://localhost:8000  I tried different ports also no luck. With ``docker stats`` seeing ``jitsi_jicofo_1`` using full CPU of one processor, when doing nothing.

 I decided to run ``docker-compose up`` as non-detached, I am getting many error messages:
```
**************************
prosody_1  | A problem occured while reading the config file /config/prosody.cfg.lua
prosody_1  | 
prosody_1  | Error: Component "<no value>" clashes with previously defined Host "<no value>", for services use a sub-domain like conference.<no value>
prosody_1  | 
prosody_1  | More help on configuring Prosody can be found at http://prosody.im/doc/configure
prosody_1  | Good luck!
prosody_1  | **************************
```

**Comment by coding46** [comment]
@tvld Did you copy env.example to .env?

**Comment by saghul** [comment]
@tvld Hi Tom! Can you paste the full log? Looks like you didn't copy the environment file as I see those `<no value>` strings in there.

**Comment by tvld** [comment]
Very well, thank you. I thought that my ``.env`` was pushed to the server. But now I realize ``.gitignore`` prevented that (for good reason, but still...)...  Anyway, made a duplicate ``.env`` on the server and now it's fine )
