### ISSUE TITLE
ETHERPAD_PUBLIC_URL needs to contain /p/ path fragment

### ISSUE THREAD

**Issue by almereyda** [jitsi/docker-jitsi-meet#1200]
The `env.example` contains a key for an external Etherpad instance, that can be served through its `ETHERPAD_PUBLIC_URL`. Since the generated address will only append a current room's name to that base URL, it is necessary here to also add the `/p/` pad path fragment from Etherpad.

This way pads can be embedded and displayed.

Example:

```shell
ETHERPAD_PUBLIC_URL=https://pad.example.com/p/
```

The information about the necessity of the presence of the `/p/` fragment could be included in the `#` comment above the key in `env.example`.

**Comment by saghul** [comment]
Sounds good, care to send a PR?

**Comment by almereyda** [comment]
Very well: #1202
