### ISSUE TITLE
No video with NAT or portfowarding

### ISSUE THREAD

**Issue by dejageek** [jitsi/docker-jitsi-meet#121]
I have the dev branch up and running.  All client that are on the local lan can do video sharing/desktop sharing.  Any client coming in from the outside network can not see any video sharing and when attempting to video share a black screen shows for the other clients.

I have ports 8443, 4443 and 10000 forwarded to my jitsi instance.

**Comment by saghul** [comment]
Have you done this? https://github.com/jitsi/docker-jitsi-meet#running-on-a-lan-environment

**Comment by dejageek** [comment]
> Have you done this? https://github.com/jitsi/docker-jitsi-meet#running-on-a-lan-environment

DOCKER_HOST_ADDRESS is set to the LAN ip address (ex a 192.168.1.x) ip address

**Comment by dejageek** [comment]
I resolved this by enabled TCP HARVESTING
