### ISSUE TITLE
nginx:[error] failed to initialize Lua VM in /config/nginx/nginx.conf:65

### ISSUE THREAD

**Issue by woogeunshin** [jitsi/docker-jitsi-meet#1210]
Download the latest docker image(stable 6826) and run it in the M1 MacBook.

There is nginx error.
------------------------
docker-jitsi-meet-stable-6826-jicofo-1   | Jan 27, 2022 2:17:55 AM org.jitsi.utils.logging2.LoggerImpl log
docker-jitsi-meet-stable-6826-jicofo-1   | INFO: Added brewery instance: jvbbrewery@internal-muc.meet.jitsi/78e8d130b21f
docker-jitsi-meet-stable-6826-jicofo-1   | Jan 27, 2022 2:17:55 AM org.jitsi.utils.logging2.LoggerImpl log
docker-jitsi-meet-stable-6826-jicofo-1   | INFO: Added new videobridge: Bridge[jid=jvbbrewery@internal-muc.meet.jitsi/78e8d130b21f, relayId=null, region=null, stress=0.00]
docker-jitsi-meet-stable-6826-jicofo-1   | Jan 27, 2022 2:17:55 AM org.jitsi.utils.logging2.LoggerImpl log
docker-jitsi-meet-stable-6826-jicofo-1   | INFO: Scheduled health-check task for: Bridge[jid=jvbbrewery@internal-muc.meet.jitsi/78e8d130b21f, relayId=null, region=null, stress=0.00]
docker-jitsi-meet-stable-6826-web-1      | nginx: [error] failed to initialize Lua VM in /config/nginx/nginx.conf:65
docker-jitsi-meet-stable-6826-web-1      | nginx: [error] failed to initialize Lua VM in /config/nginx/nginx.conf:65
-----------------------

I'm googling for this issue and find an article about Jitsi docker image not support Apple M1 machine yet. 
I'm novice about docker image and M1. 
Could you help me about this issue?

**Comment by saghul** [comment]
We don't provide ARM64 images yet, so it won't work on an M1.

Hopefully we can fix that soon.

**Comment by woogeunshin** [comment]
Thank you for your effort and I hope this issue can be fixed ASAP.

**Comment by RicardoDolNL** [comment]
Any indication as to when this hopefully soon fix will be?

**Comment by saghul** [comment]
Please follow https://github.com/jitsi/docker-jitsi-meet/issues/1214
