### ISSUE TITLE
Authentication does not work from website - but works from mobile phone

### ISSUE THREAD

**Issue by nikkonikko** [jitsi/docker-jitsi-meet#1212]
Hi Jitsi.

This is a very nice and interesting project. Well done!

I tried the newest release. 

The authentication works fine, when creating meetings from the mobile phone.

But the authentication doesn't work, when creating meetings from the browser (Chrome). It just allow anyone to create/join meetings.

I cleared the config folder, followed the installation steps and tried a simple .env, where Let's Encrypt is disabled and authentication is enabled:

HTTP_PORT=80
HTTPS_PORT=443
etc..

ENABLE_AUTH=1
ENABLE_GUESTS=1
AUTH_TYPE=internal

ENABLE_HTTP_REDIRECT=1
ENABLE_HSTS=1

At last, I created two internal users in prosody (as mentioned in the manual).

Regarding how bad the settings are, this should never never happend :-) but what am I doing wrong?

**Comment by saghul** [comment]
Were you already in the meeting from mobile when you tried to join from the browser?

**Comment by nikkonikko** [comment]
No no, I was not...
