### ISSUE TITLE
arm64 image support

### ISSUE THREAD

**Issue by saghul** [jitsi/docker-jitsi-meet#1214]
I'll pin this issue so people can find it easily and track it.

**Comment by luongdnt** [comment]
any news on this issue? @saghul

**Comment by saghul** [comment]
No.

**Comment by luongdnt** [comment]
do we have any solution for by pass this issue on M1 devices? @saghul

**Comment by saghul** [comment]
Please stop asking. You are not going make it happen faster, on the contrary, you'll make developers stressed and not keen on working on what you really want.

**Comment by wfleischer** [comment]
Thank you @saghul for working on this feature! If there is any specific task I could help with, please let me know.

**Comment by saghul** [comment]
> Thank you @saghul for working on this feature! If there is any specific task I could help with, please let me know.

I have a mostly ready branch, the only thing that I'm not a fan of is that buildx doesn't allow building multi arch images and then loading them locally instead of directly pushing them, but I think that's unavoidable at the moment without complicating things too much...

**Comment by wfleischer** [comment]
> > Thank you @saghul for working on this feature! If there is any specific task I could help with, please let me know.
> 
> I have a mostly ready branch, the only thing that I'm not a fan of is that buildx doesn't allow building multi arch images and then loading them locally instead of directly pushing them, but I think that's unavoidable at the moment without complicating things too much...

Just got the Jitsi backend running on my dev M1 mac. I only had to make few adjustments. You have already done a tremendous work. Thank you so much Saúl!

For anyone interested: use the latest release which already includes several patches to support arm64.

**Comment by saghul** [comment]
Yep I was thinking about skipping those for the first release indeed.

**Comment by nikwise29** [comment]
> > > Thank you @saghul for working on this feature! If there is any specific task I could help with, please let me know.
> > 
> > 
> > I have a mostly ready branch, the only thing that I'm not a fan of is that buildx doesn't allow building multi arch images and then loading them locally instead of directly pushing them, but I think that's unavoidable at the moment without complicating things too much...
> 
> Just got the Jitsi backend running on my dev M1 mac. I only had to make few adjustments. You have already done a tremendous work. Thank you so much Saúl!
> 
> For anyone interested: use the latest release which already includes several patches to support arm64.

@wfleischer would you mind highlighting those few adjustments so that one can reproduce it on their M1s.  Thanks!

**Comment by wfleischer** [comment]
@nikwise29: There is meanwhile a PR for the [patches at the base Dockerfile](https://github.com/jitsi/docker-jitsi-meet/pull/1269/files#diff-b093d34eec92adf6e0cc6e445edb7147ea45d25fb0c98f2f84a60f5aae6f34f7).

**Comment by nikwise29** [comment]
thanks @wfleischer. I will try this out!

**Comment by saghul** [comment]
Support for arm64 is now available in master.

**Comment by zibozeng** [comment]
docker-jitsi-meet-master-prosody-1

throw an error "No enabled VirtualHost entries found in the config file." 

master.

**Comment by saghul** [comment]
Why do you think that is arm64 related?
