### ISSUE TITLE
Lobby disabled by default

### ISSUE THREAD

**Issue by domibarton** [jitsi/docker-jitsi-meet#1215]
Hello

We're using a fresh Docker install of `stable-6826`. Everything works as expected (KUDOS to that!!!), but unfortunately the lobbies are not activated by default.

I checked out the existing issues and found this:

> This has landed in the new stable, everything is now ON by default.
_Originally posted by @saghul in https://github.com/jitsi/docker-jitsi-meet/issues/1104#issuecomment-948663636_

Unfortunately, this isn't the case in my installation. 

What I did / tried so far:

- Fetched the `stable-6826` release
- Created a complete new dockerised installation
- Removed all volumes / configs
- Copied the `example.env` to `.env`
- Changed the following variables:

```
# System time zone
TZ=Europe/Zurich

# Public URL for the web service (required)
PUBLIC_URL=https://…

# Control whether the lobby feature should be enabled or not
ENABLE_LOBBY=1

# Show a prejoin page before entering a conference
ENABLE_PREJOIN_PAGE=1

# Enable authentication
ENABLE_AUTH=1

# Enable guest access
ENABLE_GUESTS=1

# Select authentication type: internal, jwt or ldap
AUTH_TYPE=jwt
```

_Please note the passwords & JWT app ID / secrets are configured via CI/CD pipeline vars, thus they're not included in the config above._

When I then run a `docker-compose up -d`, everything works fine. JWT authentication works, guest access works and even the lobby feature is available. However, right now the lobby's are not activated by default. I've to activate it manually everytime I create a room.

This leads me to the following questions?

- Is that a PEBKAC error? :)
- If it is my fault, can you point me in the right direction?
- If this isn't my fault, what can I do to further pin point the error?
- Is this probably related to having guests or (JWT) authentication enabled?

**Comment by saghul** [comment]
We don't have that functionality yet, alas.

It's complex...

**Comment by saghul** [comment]
Closing since there is already an open issue in jitsi-meet and this is not Docker specific.
