### ISSUE TITLE
Add labels to docker Dockerfiles

### ISSUE THREAD

**Issue by xoxys** [jitsi/docker-jitsi-meet#1216]
Hi, I would like to add (a subset) of [opencontainers](https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys) labels to the Dockerfiles. A good starter would be: 

```
LABEL org.opencontainers.image.title=
LABEL org.opencontainers.image.url=
LABEL org.opencontainers.image.source=
LABEL org.opencontainers.image.documentation=
```

We use [renovate bot](https://docs.renovatebot.com/) to auto-create PRs for our infrastructure deployments, we would like to see the changelog in PRs created by renovate bot. This can be achieved by using the `org.opencontainers.image.source` label to point to the GitHub source directory, https://github.com/renovatebot/renovate/pull/2907.

**Comment by saghul** [comment]
Sounds reasonable, let's have them!

**Comment by xoxys** [comment]
Cool! I can provide a PR if you like.

**Comment by saghul** [comment]
Please do!

**Comment by rcarmo** [comment]
Hi again! 

In case my comment on the pull request is missed, the current labels are broken because they lack quotation marks for strings with spaces, and I had to remove them with 

```
sed -i "/^LABEL/d" $(find . -print |grep Dockerfile)
```

**Comment by xoxys** [comment]
Thanks for the info! See https://github.com/jitsi/docker-jitsi-meet/pull/1220

**Comment by prayagsingh** [comment]
Is anyone tried building an image on WSL2 using docker-desktop? I'm facing some issues. Below is the snippet.

```
docker image build -t prayagsingh/web:latest .
[+] Building 0.1s (2/2) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                       0.0s
 => => transferring dockerfile: 1.24kB                                                                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                                                                          0.0s
 => => transferring context: 2B                                                                                                                                                                            0.0s
failed to solve with frontend dockerfile.v0: failed to create LLB definition: no build stage in current context
``` 
There are a few suggestions available on StackOverflow about disabling the buildkit by setting `DOCKER_BUILDKIT=0` just before the `docker image build` command and it didn't work either.  Since I'm not familiar with the OCI standards hence asking this question. Is it mandatory to put the `LABEL` before the `FROM ${JITSI_REPO}/base:${BASE_TAG}` command?

**Comment by xoxys** [comment]
Ouch... How much can go wrong -.- Of course labels need to go after the `FROM` section, fixed in https://github.com/jitsi/docker-jitsi-meet/pull/1221 I did a (successful) local test build this time. Would be good to have a CI in place to test PRs.

**Comment by prayagsingh** [comment]
> Ouch... How much can go wrong -.- Of course labels need to go after the `FROM` section, fixed in #1221 I did a (successful) local test build this time. Would be good to have a CI in place to test PRs.

The last four builds for unstable images failed because of the same reason.
https://github.com/jitsi/docker-jitsi-meet/actions/runs/1816470437

**Comment by saghul** [comment]
Maybe we could run the CI for PRs too, just without pushing to the hub.

**Comment by xoxys** [comment]
I think that would make sense.

**Comment by saghul** [comment]
I'll add it to the pile, but if anyone would like to take a stab at it, a PR would be welcome.

**Comment by xoxys** [comment]
> PR would be welcome.

Here you go https://github.com/jitsi/docker-jitsi-meet/pull/1222
