### ISSUE TITLE
Disable jvb TCP

### ISSUE THREAD

**Issue by damencho** [jitsi/docker-jitsi-meet#1218]
I think we should drop the config for this
https://github.com/jitsi/docker-jitsi-meet/blob/3b8ed7ed2b6982cd6f68fb2ea4864eb312c03df2/env.example#L261

I think that is not working at all and we never test it and just bring a bad initial experience to users.

**Comment by saghul** [comment]
You mean to have it disabled by default without the possibility to enable it?

Fine by me, if we don't test we shouldn't support it.

What's the status in the Debian setup?

Last, do you want to make a PR or do you want me to?

**Comment by damencho** [comment]
> You mean to have it disabled by default without the possibility to enable it?

Yep.

We had dropped enabling it when we dropped serving web with jetty.





> Last, do you want to make a PR or do you want me to?

yep, please :)

**Comment by saghul** [comment]
This was done.
