### ISSUE TITLE
Unable to load module

### ISSUE THREAD

**Issue by DanielnetoDotCom** [jitsi/docker-jitsi-meet#1224]
Hi, 

I am running the docker stable-6865

I was using the mod_token_moderation for a while and now it is refusing to work.

I am keeping getting the error `modulemanager       error  Unable to load module 'token_moderation': /prosody-plugins-custom/mod_token_moderation.lua`, nothing else

here is a partial log 

```
prosody_1  | startup             info   Hello and welcome to Prosody version 0.11.13
prosody_1  | startup             info   Prosody is using the epoll backend for connection handling
prosody_1  | modulemanager       error  Unable to load module 'token_moderation': /prosody-plugins-custom/mod_token_moderation.lua
prosody_1  | muc.meet.jitsi:tls  info   Certificates loaded
prosody_1  | internal-muc.meet.jitsi:tls  info  Certificates loaded
prosody_1  | portmanager                  info  Activated service 'c2s' on [::]:5222, [*]:5222
prosody_1  | portmanager                  info  Activated service 'legacy_ssl' on no ports
prosody_1  | auth.meet.jitsi:tls          info  Certificates loaded
prosody_1  | recorder.meet.jitsi:tls      info  Certificates loaded
prosody_1  | general                      info  Starting speakerstats for muc.meet.jitsi
```

there is a way I can see more about this error?

any way to fix or debug it?

**Comment by saghul** [comment]
Is the module in that location?

**Comment by DanielnetoDotCom** [comment]
Hi, thanks for the response.

I just find out that on the `prosody/10-config` file the command

```
tpl /defaults/mod_token_moderation.lua > /prosody-plugins-custom/mod_token_moderation.lua
```
or 
```
cp  /defaults/mod_token_moderation.lua > /prosody-plugins-custom/mod_token_moderation.lua
```
either of them was creating a directory instead of a file, I am not sure why

so I added this ...


```
tpl /defaults/mod_token_moderation.lua > /prosody-plugins-custom/mod_token_moderation.lua
chmod -R 777 /prosody-plugins-custom/
if [[ ! -f /prosody-plugins-custom/mod_token_moderation.lua ]]; then
    mv /prosody-plugins-custom/mod_token_moderation.lua /prosody-plugins-custom/mod_token_moderation.lua.dir
    mv /prosody-plugins-custom/mod_token_moderation.lua.dir/mod_token_moderation.lua /prosody-plugins-custom/mod_token_moderation.lua   
fi 
```

I know this is not the correct way, but I have no idea why it does create a directory


![image](https://user-images.githubusercontent.com/18009293/154472712-6f74ef48-1c74-416f-b411-639b280fd0a6.png)

**Comment by prayagsingh** [comment]
@DanielnetoDotCom Below are the steps you can follow.

1. use `token_affiliation` instead of `token_moderation`. 
2. Add a `RUN` command in the `Dockerfile` to download `token_affiliations` to the prosody-plugins. Below is the snippet.
```
RUN wget -O /prosody-plugins/mod_token_affiliation.lua https://raw.githubusercontent.com/jitsi-contrib/prosody-plugins/main/token_affiliation/mod_token_affiliation.lua

COPY rootfs/ /
```

3. Create a docker image for prosody. cd `prosody` && run `docker image build -t your_docker_hub_username/prosody:latest .` command.

4. Set `- JWT_TOKEN_AUTH_MODULE=token_verification,token_affiliation` under `prosody` service in the `docker-compose.yml`

5. For how to use it with JWT, please refer [here](https://github.com/jitsi-contrib/prosody-plugins/tree/main/token_affiliation)

**Comment by prayagsingh** [comment]
@DanielnetoDotCom `Grant Moderator` is available + moderation creates some sought of exception logs in the jicofo.
