### ISSUE TITLE
How to change toolbar icons?

### ISSUE THREAD

**Issue by m-dastagir** [jitsi/docker-jitsi-meet#1228]
I am trying to get all toolbar icon svg’s that are present here [jitsi-meet/react/features/base/icons/svg at master · jitsi/jitsi-meet · GitHub](https://github.com/jitsi/jitsi-meet/tree/master/react/features/base/icons/svg) using docker.

I am able to get all images this way - `$ docker cp docker-jitsi-meet-web-1:/usr/share/jitsi-meet/images web/customfiles/`

But I am not able to get all icons - `$ docker cp docker-jitsi-meet-web-1:/usr/share/jitsi-meet/react/features/base/icons/svg web/customfiles/svg`

What am I doing wrong?

It says `Error: No such container:path: docker-jitsi-meet-web-1:/usr/share/jitsi-meet/react/features/base/icons/svg`

**Comment by saghul** [comment]
Icons are embedded and part of the app bundle. You cannot change them without making your own build.

**Comment by m-dastagir** [comment]
Thank you for your reply. How do I make my own build with docker?

**Comment by prayagsingh** [comment]
> Thank you for your reply. How do I make my own build with docker? 

You can checkout the jitsi community page for the same.
