### ISSUE TITLE
nginx issue in the dockerjitsimeet

### ISSUE THREAD

**Issue by whiranpat** [jitsi/docker-jitsi-meet#123]
I am getting this issue when running the `docker-compose up -d` in the stable version 3547:
`nginx: [emerg] PEM_read_bio_DHparams("/config/nginx/dhparams.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: DH PARAMETERS)`

I was wondering if anyone was able to fix this issue.

**Comment by whiranpat** [comment]
I went into the container and then do `openssl dhparam -out dhparam.pem 1024` and it start working but will probably will do the host and mount the directory

**Comment by saghul** [comment]
Did you wait long enough on the first container boot? It may take up to a minute to generate the DH parameters (IIRC we use 4096, which may take a while).

**Comment by whiranpat** [comment]
I waited like 4 minutes and it didn't generate it.

**Comment by saghul** [comment]
Can you paste the logs of the web container?

**Comment by whiranpat** [comment]
It was looping `nginx: [emerg] PEM_read_bio_DHparams("/config/nginx/dhparams.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: DH PARAMETERS)` but after I did that command it works.

**Comment by whiranpat** [comment]
thanks

**Comment by m-yosefpor** [comment]
I have the same issue here (same behaviour, same log) .. running the command in the container didn't work either.

`git clone https://github.com/jitsi/docker-jitsi-meet && cd docker-jitsi-meet`
`cp env.example .env`
`docker-compose up`

**Comment by saghul** [comment]
@m-yosefpor Please paste the logs of your web container from the start.

**Comment by m-yosefpor** [comment]
@saghul 
web_1      | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
web_1      | [s6-init] ensuring user provided files have correct perms...exited 0.
web_1      | [fix-attrs.d] applying ownership & permissions fixes...
web_1      | [fix-attrs.d] done.
web_1      | [cont-init.d] executing container initialization scripts...
web_1      | [cont-init.d] 01-set-timezone: executing...
web_1      | [cont-init.d] 01-set-timezone: exited 0.
web_1      | [cont-init.d] 10-config: executing...
web_1      | using keys found in /config/keys
web_1      | [cont-init.d] 10-config: exited 0.
web_1      | [cont-init.d] done.
web_1      | [services.d] starting services
web_1      | [services.d] done.
web_1      | nginx: [emerg] PEM_read_bio_DHparams("/config/nginx/dhparams.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: DH PARAMETERS)
web_1      | nginx: [emerg] PEM_read_bio_DHparams("/config/nginx/dhparams.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: DH PARAMETERS)
web_1      | nginx: [emerg] PEM_read_bio_DHparams("/config/nginx/dhparams.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: DH PARAMETERS)
web_1      | nginx: [emerg] PEM_read_bio_DHparams("/config/nginx/dhparams.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: DH PARAMETERS)
web_1      | nginx: [emerg] PEM_read_bio_DHparams("/config/nginx/dhparams.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: DH PARAMETERS)
web_1      | nginx: [emerg] PEM_read_bio_DHparams("/config/nginx/dhparams.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: DH PARAMETERS)
web_1      | nginx: [emerg] PEM_read_bio_DHparams("/config/nginx/dhparams.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: DH PARAMETERS)
web_1      | nginx: [emerg] PEM_read_bio_DHparams("/config/nginx/dhparams.pem") failed (SSL: error:0906D06C:PEM routines:PEM_read_bio:no start line:Expecting: DH PARAMETERS)

**Comment by saghul** [comment]
Can you delete the $CONFIG dir and start the containers again?

**Comment by m-yosefpor** [comment]
@saghul 
wow thanks! It fixes the issue. So it seems that if the container fails to start for the first time (for me unavailability for the port to bind), then it will fail to start forever (even after docker-compose down), unless the $CONFIG dir is removed completely before starting it.

**Comment by saghul** [comment]
Yes, that is somewhat by design: config files are generated on first container boot. If you want to re-create them, then wiping the config is necessary.

I understand this is not ideal, we may make improvements in the future, but for now, that's the best we can do.

**Comment by nebi-tessemuh** [comment]
What is the $CONFIG dir here? I'm new to docker and experiencing the same issue, but I don't even understand where /config/nginx/dhparams.pem is rooted. is $CONFIG's value the path /config/nginx/dhparams.pem?

**Comment by nebi-tessemuh** [comment]
I have looked in ~/.docker/compose/.env but there is no environment variable configured there called CONFIG

**Comment by m-yosefpor** [comment]
> I have looked in ~/.docker/compose/.env but there is no environment variable configured there called CONFIG

Have you cloned the repository and copied the "env.example" to  ".env" ?
`git clone https://github.com/jitsi/docker-jitsi-meet && cd docker-jitsi-meet`
`cp env.example .env`

if so, then the variable should be sth like:
CONFIG=~/.jitsi-meet-cfg
