### ISSUE TITLE
Docker resets prosody files

### ISSUE THREAD

**Issue by m-dastagir** [jitsi/docker-jitsi-meet#1231]
Docker contains two prosody directory - "config" & "prosody-plugins-custom". I am trying to add a new variable inside "jitsi-meet.cfg.lua" file present under `.jitsi-meet-cfg\prosody\config\conf.d` but whenever I restart docker, the files get reset. How do I avoid it from getting reset?

**Comment by saghul** [comment]
That's by design. It's re-created so all variable changes are applied. What are you trying to add?

**Comment by rbsongcan** [comment]
Hello, I have the same issue. I'm trying to change from 'turn' to 'turns'. I'm not sure if the changes can take effect on the fly or not. So I restart the matrix-jitsi-prosody service then the change has gone after that and system still use 'turn'. I'm looking for help on this

**Comment by saghul** [comment]
Did you set the TURNS_XXX variables?

**Comment by rbsongcan** [comment]
@saghul sorry it's working now. I did not know that the system was a playbook, make changes on playbook rather than on docker container directly. Thanks you for the reply.
