### ISSUE TITLE
Why doesn't jibri work?

### ISSUE THREAD

**Issue by drno88** [jitsi/docker-jitsi-meet#1233]
Good day. I have jitsi installed in docker. I'm trying to set up a recording, run jitsi.. but it throws an error...
sudo docker-compose -f docker-compose.yml -f jibri.yml up
ERROR: Binding /dev/snd is not found. Please check that you run docker-compose with -f jibri.yml.

Alsa installed and working...
Server - debian 11
I run everything as root

Can you help me with this?

**Comment by saghul** [comment]
Correct, they run on the container.

**Comment by drno88** [comment]
sudo docker-compose -f docker-compose.yml -f jibri.yml up
conteiners start... but 
in console - ERROR: Binding /dev/snd is not found. Please check that you run docker-compose with -f jibri.yml.

And record does not work

**Comment by saghul** [comment]
Don't run docker-compose with sudo.

**Comment by drno88** [comment]
Do you think this is the problem? I work on the server under the root user, which I wrote about at the very beginning. So with or without sudo - run as root

**Comment by saghul** [comment]
I missed that in the original message. That is problematic, I don't recommend it.

**Comment by drno88** [comment]
I tried as a non-root user. same problem

**Comment by saghul** [comment]
Do you have selinux or something of the sort enabled? Does /dev/snd exist on the host machine?

**Comment by drno88** [comment]
selinux - no. Only iptables. 
KVM is still running on the server... but I don't think it should affect
I also checked the installation on a clean ubuntu 18 - everything works. apparently this is some kind of specific debian problem, but I just can’t figure out what’s wrong (((

![image](https://user-images.githubusercontent.com/54410580/156557536-2353a1eb-223a-4555-b765-267532cb1cef.png)

**Comment by saghul** [comment]
Try to run it as a user instead of root and make sure you are in the audio group.

**Comment by drno88** [comment]
already run as a user without root. both root and another user are in the audio group
to be honest, there are no ideas yet what else needs to be checked (

**Comment by saghul** [comment]
I'm out of ideas myself :-/

Can you show me the output of `ls -lah /dev/snd`

**Comment by drno88** [comment]
I updated the kernel from the standard debian repository, maybe the hoster used a custom kernel... I did not have the opportunity to install the system from an iso file, when buying a server, it was only possible to auto-install debian

**Comment by saghul** [comment]
Happy to hear you got it working!
