### ISSUE TITLE
how can i add js-utils modules?

### ISSUE THREAD

**Issue by uberschaft** [jitsi/docker-jitsi-meet#1236]
I am trying to modify the random room name generator but I actually can't find the source file for room names. I guess there is a way by recompiling app.bundle.min.js but I don't know how to do it. Can anyone help me, please?
Thanks in advance.

**Comment by saghul** [comment]
You'd need to build the entire frontend and then build the Docker image. Please post in our community, we use this to track issues. https://community.jitsi.org
