### ISSUE TITLE
Iframe api script for self hosted producing error ‘net::ERR_CERT_COMMON_NAME_INVALID’ 

### ISSUE THREAD

**Issue by abhijeet-arya** [jitsi/docker-jitsi-meet#1237]
my self hosted Jitsi Meet works fine , I have also enabled lets_encrypt. But when I am adding the IFrame API script in html file it produces error in console ‘net::ERR_CERT_COMMON_NAME_INVALID’.

I am adding <script src='https://<your-domain>/external_api.js'></script> to use api = new JitsiMeetExternalAPI(domain, options) as mentioned in document.

**Comment by saghul** [comment]
That URL is missing the domain.

**Comment by abhijeet-arya** [comment]
sorry, in this post it's missing but I'm using my domain instead of meet.jit.si

**Comment by saghul** [comment]
Are you using the same domain name as you requested the certificate with?

**Comment by abhijeet-arya** [comment]
I was using LETSENCRYPT_DOMAIN=www.my-domain.in and now I change it to LETSENCRYPT_DOMAIN=my-domain.in
but there's new error or warning it says:-
DevTools failed to load source map: Could not parse content for https://my-domain.in/external_api.min.js.map: Unexpected token < in JSON at position 0

**Comment by saghul** [comment]
Please let's not mix things. Are you able to load the iframe now?

**Comment by abhijeet-arya** [comment]
no, currently my console shows 
DevTools failed to load source map: Could not parse content for https://my-domain.in/external_api.min.js.map: Unexpected token < in JSON at position 0

**Comment by saghul** [comment]
That error is irrelevant. Anything else in the console?

**Comment by abhijeet-arya** [comment]
<img width="1440" alt="Screenshot 2022-03-11 at 5 58 04 PM" src="https://user-images.githubusercontent.com/65891095/157867465-b56c91bc-4916-4f8a-8ed4-ea004bfa8876.png">

**Comment by saghul** [comment]
Make sure you enable logs for all levels.

**Comment by saghul** [comment]
Also, what code are you using using the iframe API?

**Comment by abhijeet-arya** [comment]
how can I enable logs for all levels?

I am using the example from the document

const domain = 'my domain';
const options = {
    roomName: 'JitsiMeetAPIExample8888888888888888888',
    width: 700,
    height: 700,
    parentNode: document.querySelector('#meet'),
    lang: 'de'
};
const api = new JitsiMeetExternalAPI(domain, options);

**Comment by abhijeet-arya** [comment]
@saghul thanks for assisting. I found the problem. I did a silly mistake in my code.
