### ISSUE TITLE
Colibri REST port 8080 gone after update to v7001

### ISSUE THREAD

**Issue by chris-est** [jitsi/docker-jitsi-meet#1239]
Hello,
i enabled "COLIBRI_REST_ENABLED=true" to expose port 8080 for statistics about Jitsi.
Since v7001 the port does not seem to be exported anymore, i suspect it has something to do with the removal of:
- '${JVB_TCP_PORT}:${JVB_TCP_PORT}'

Is there a new way to enable this?

**Comment by saghul** [comment]
That port mapping was for TCP media, not for the stats endpoints. I think you need to be using port 9090.

**Comment by chris-est** [comment]
Thanks for your reply, i am trying to switch to port 9090 but did not get the same results as before when using 8080.

I want to gain access again to /colibri/stats as described here: https://github.com/jitsi/jitsi-videobridge/blob/master/doc/rest-colibri.md

Forwarding port 9090 to my docker host worked, but when trying to access the url i get:
URI: /colibri/stats
Status: 404
Message: Not Found
Servlet: org.eclipse.jetty.servlet.ServletHandler$Default404Servlet-2237bada

Is there any documentation about this? I could not find anything on how to use the api on port 9090.

**Comment by bgrozev** [comment]
Port 8080 is correct for stats. I don't know why it's not working, seems unrelated to the TCP_PORT removal.

**Comment by chris-est** [comment]
Ok i got it working again, adding a port forwarding in the docker-compose file under jvb: ports: - '127.0.0.1:8080:8080'.
Maybe i missed something when migrating the .env file to the new version. Thank you for your help

**Comment by saghul** [comment]
Oh you're right, we seem to be missing that port forward in compose. Care to send a PR?

Also @bgrozev where is the port configured? Now we seem to use the default, but I'd like to be explicit.

**Comment by bgrozev** [comment]
It would go here as `port` https://github.com/jitsi/jitsi-videobridge/blob/master/jvb/src/main/resources/reference.conf#L129
