### ISSUE TITLE
Etherpad not usable since upgrade to 7001 (curious effect)

### ISSUE THREAD

**Issue by PhilippeAccorsi** [jitsi/docker-jitsi-meet#1242]
Hi,

We have updated to version 7001 and now is it impossible to use etherpad. When we click on "open shared document" we just see a new page of our Jitsi instance.

It seems something wrong with url `src="https://********/etherpad/p/edededed?showControls=true&showChat=false&showLineNumbers=true&useMonospaceFont=false&userName=philippe+-+algoo"`

https://user-images.githubusercontent.com/25848257/158389437-356853ba-7b53-4685-ab17-dc91c0f0477e.mp4

We did not change anything in configuration. To upgrade we just download new release in a new folder, copy `.env` file in this new folder, stop old image, and start with the new docker-compose file.

We use the same config folder. Is there something wrong with this process?

This is the Etherpad configuration we use (with etherpad 1.8.16)
~~~
#
# Etherpad integration (for document sharing)
#

# Set etherpad-lite URL in docker local network (uncomment to enable)
ETHERPAD_URL_BASE=http://etherpad.meet.jitsi:9001

# Set etherpad-lite public URL (uncomment to enable)
#ETHERPAD_PUBLIC_URL=https://etherpad.my.domain

# Name your etherpad instance!
ETHERPAD_TITLE=Video Chat

# The default text of a pad
ETHERPAD_DEFAULT_PAD_TEXT="Welcome to Algoo Web chat!\n\n"

# Name of the skin for etherpad
ETHERPAD_SKIN_NAME=colibris

# Skin variants for etherpad
ETHERPAD_SKIN_VARIANTS="super-light-toolbar super-light-editor light-background full-width-editor"
~~~

**Comment by saghul** [comment]
Do you have any errors in the console logs?

**Comment by saghul** [comment]
Are you using the iframe API?

**Comment by saghul** [comment]
I'll try to reproduce this.

**Comment by bergalath** [comment]
Hello, we have the exact same problem here, using Firefox Dev Edition (99.0b2) or the [Jitsi Desktop App](https://aur.archlinux.org/packages/jitsi-meet-desktop-bin)

We have the same Etherpad config in `.env` than @PhilippeAccorsi, the same `docker-compose` command, and no iframe API.
One difference : we use an Apache proxy with Let’s Encrypt enabled

**Comment by PhilippeAccorsi** [comment]
Good news for me (not really a good news), it is not just on my server \o/
So I think it is a real bug.

**Comment by ares1977** [comment]
Same problem here. 
6865 is not affected.

**Comment by tom666-debug** [comment]
Confirmed - same here. 
All okay with version 6865, but broken with version 7001.

**Comment by saghul** [comment]
I found the problem. This is a regression introduced in 0b019ee. That commit enabled tenants / subdomains by default, and the default Etherpad installation proxies it on https://your-meet-domain.tld/etherpad/ which is treated as a tenant. Oops.

A workaround if to disable subdomains by adding this to your .env file: `ENABLE_SUBDOMAINS=0`

Ping @damencho

**Comment by bergalath** [comment]
Also confirmed here, thanks @saghul  !

**Comment by damencho** [comment]
> I found the problem. This is a regression introduced in [0b019ee](https://github.com/jitsi/docker-jitsi-meet/commit/0b019ee4ebc92b2c0223258a887c360e473a5aa9). That commit enabled tenants / subdomains by default, and the default Etherpad installation proxies it on https://your-meet-domain.tld/etherpad/ which is treated as a tenant. Oops.

But if the etherpad rule is before the rest it should work.

**Comment by damencho** [comment]
Does this change anything? https://github.com/jitsi/docker-jitsi-meet/pull/1252
