### ISSUE TITLE
Host authentication alternatives other than prosody

### ISSUE THREAD

**Issue by 0xspade** [jitsi/docker-jitsi-meet#1249]
Does prosody use the web sockets? I disabled the web sockets in my Jitsi instance because I'm getting too many errors, and it keeps disconnecting. Are there any ways to have an authentication for host besides prosody without using web sockets? I'm taking a look into JWT, but there are no helpful links or article to implement it. Can someone help me out?

Currently using the Jitsi docker 7001 stable

*PS: not a docker wizard, I'm just a noob IT guy.*

**Comment by saghul** [comment]
Authentication and transport are completely separate.

You could use JWT or LDAP based auth, but XMPP still needs to be transported somehow and you have 2 options BOSH (HTTP long polling) or WebSocket.

What keeps disconnecting exactly, in your installation? Share some logs please.

**Comment by 0xspade** [comment]
I already resolved the issue without using websockets, I can now use prosody without any issues (my mistakes is that I didn't read the documentation).
