### ISSUE TITLE
jvb - port 8080 exposed, but not part of .env?

### ISSUE THREAD

**Issue by Meffesino** [jitsi/docker-jitsi-meet#1250]
Hello, 
I have updated jitsi to the latest level. Since then, I got an JVB error that port 8080 is already in use (which is true, as it is used for another service). 

`user@h2876099:/opt/jitsi-dockerized# docker-compose up -d`

```
Creating network "jitsi-dockerized_meet.jitsi" with the default driver
Creating jitsi-dockerized_web_1     ... done
Creating jitsi-dockerized_prosody_1 ... done
Creating jitsi-dockerized_jicofo_1  ...
Creating jitsi-dockerized_jvb_1     ...
Creating jitsi-dockerized_jvb_1     ... error

ERROR: for jitsi-dockerized_jvb_1  Cannot start service jvb: driver failed programming external connectivity on end      Creating jitsi-dockerized_jicofo_1  ... done
:8080 failed: port is already allocated
```

The port forwarding in the docker-compose.yml file was added in this [commit](https://github.com/jitsi/docker-jitsi-meet/commit/c5b049ad5653a271485cb999d22cfef200075e1f)

I'm not sure, why the port is now exposed but wasn't before? Would be good to understand that. 

Nevertheless it would be awesome to be able to change the port via the .env file, as 8080 is a common port used in various applications.

In the meantime, does it work stable, when I comment out this specific line of the docker-compose.yml file?

Thank you!

**Comment by saghul** [comment]
A PR with an env var to change the port would be welcome.

**Comment by Meffesino** [comment]
can you let me know, why the port is even exposed? What benefit does it have?

**Comment by tom666-debug** [comment]
Would it be possible to use a different port (host side) than 8080?
e.g. 127.0.0.1:**8085**:8080?

8080 is already in use on my machine.

**Comment by bgrozev** [comment]
In jvb.conf it would go [here](https://github.com/jitsi/docker-jitsi-meet/blob/master/jvb/rootfs/defaults/jvb.conf#L50) as "port" (it defaults to 8080 in the backend). I makes sense that it should be configurable.

**Comment by bgrozev** [comment]
> Will there be any impact if I change the "external" port to lets say 8085?
> I'm asking because I really dont know what part of Jitsi (function/service) is using 127.0.0.1:8080 and on my host 8080 is already in use by ownCloud.

Hmm, I'm not 100% what we have running in docker, but there will probably be no impact at all. Make sure the port is *not* open publically as it exposes jvb internals.

**Comment by mammo0** [comment]
>Make sure the port is not open publically as it exposes jvb internals.

But why is it then needed at all to expose this port on the Docker host?

For example in my setup the majority of the connections come from the Internet. That means those clients will have no access to that port anyway. Even if I expose it to the Docker host.

**Comment by bgrozev** [comment]
> But why is it then needed at all to expose this port on the Docker host?

For health checks and expoosing metrics. @saghul wdyt?

**Comment by mammo0** [comment]
>For health checks and expoosing metrics.

But the docker-compose.yml file defines an own network for Jitsi. So all containers that are part of this network can communicate with each other.
Exposing ports to the host is not necessary in this case. Or do I get something wrong here?

**Comment by chris-est** [comment]
> But the docker-compose.yml file defines an own network for Jitsi. So all containers that are part of this network can communicate with each other. Exposing ports to the host is not necessary in this case. Or do I get something wrong here?

My use case was to access the REST API from my telegraf instance running on the docker host.

> I'm asking because I really dont know what part of Jitsi (function/service) is using 127.0.0.1:8080.

AFAIK you could change the port on the docker host to sth. else or remove the line from the docker-compose file and Jitsi will run just fine, as long as you do not need to access the REST API there should be no drawbacks, just try it out ;-)

**Comment by mammo0** [comment]
Ok, thank you for clarification.
Now I don't have to worry that something doesn't work, because I removed the line from the docker-compose file.

**Comment by waja** [comment]
I opened #1289
