### ISSUE TITLE
Version '0.11.13-1~bpo11+1' for 'prosody' was not found

### ISSUE THREAD

**Issue by JohannesPertl** [jitsi/docker-jitsi-meet#1260]
The specified prosody version in prosody/Dockerfile does not exist, is there a new version available?

**Comment by saghul** [comment]
https://github.com/jitsi/docker-jitsi-meet/issues/1259

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/docker-jitsi-meet/commit/3afc1e3c12492f7ff7991e1a657ca1c99f63ea85
