### ISSUE TITLE
Jitsi not working with Ubuntu 20.04.4 LTS

### ISSUE THREAD

**Issue by charon78** [jitsi/docker-jitsi-meet#1261]
Hello i installed jitsi from https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart/ on my localhost and i wants it to work within the LAN. But i have everytime errors, i search all of errors but nothing works. Have you any ideas? Jitsi reconnect everytime.
/var/log/jitsi/jvb.log
JVB 2022-04-15 10:33:35.653 INFO: [25] HealthChecker.run#171: Performed a successful health check in PT0.000003S. Sticky failure: false
JVB 2022-04-15 10:33:45.653 INFO: [25] HealthChecker.run#171: Performed a successful health check in PT0.000002S. Sticky failure: false
JVB 2022-04-15 10:33:55.653 INFO: [25] HealthChecker.run#171: Performed a successful health check in PT0.000003S. Sticky failure: false
JVB 2022-04-15 10:34:05.653 INFO: [25] HealthChecker.run#171: Performed a successful health check in PT0.000003S. Sticky failure: false
JVB 2022-04-15 10:34:15.654 INFO: [25] HealthChecker.run#171: Performed a successful health check in PT0.000003S. Sticky failure: false
JVB 2022-04-15 10:34:25.654 INFO: [25] HealthChecker.run#171: Performed a successful health check in PT0.000003S. Sticky failure: false
JVB 2022-04-15 10:34:35.619 INFO: [24] VideobridgeExpireThread.expire#140: Running expire()
JVB 2022-04-15 10:34:35.653 INFO: [25] HealthChecker.run#171: Performed a successful health check in PT0.000003S. Sticky failure: false
JVB 2022-04-15 10:34:45.653 INFO: [25] HealthChecker.run#171: Performed a successful health check in PT0.000003S. Sticky failure: false
JVB 2022-04-15 10:34:55.653 INFO: [25] HealthChecker.run#171: Performed a successful health check in PT0.000003S. Sticky failure: false
JVB 2022-04-15 10:35:05.653 INFO: [25] HealthChecker.run#171: Performed a successful health check in PT0.000003S. Sticky failure: false
JVB 2022-04-15 10:35:15.653 INFO: [25] HealthChecker.run#171: Performed a successful health check in PT0.000003S. Sticky failure: false
JVB 2022-04-15 10:35:25.653 INFO: [25] HealthChecker.run#171: Performed a successful health check in PT0.000003S. Sticky failure: false

/var/log/jitsi/jicofo.log
Jicofo 2022-04-15 10:03:19.677 INFO: [244] [xmpp_connection=client] XmppProviderImpl$XmppReConnectionListener.reconnectingIn#400: XMPP reconnecting in: 1
Jicofo 2022-04-15 10:03:20.677 INFO: [244] [xmpp_connection=client] XmppProviderImpl$XmppReConnectionListener.reconnectingIn#400: XMPP reconnecting in: 0
Jicofo 2022-04-15 10:03:20.678 INFO: [244] [xmpp_connection=client] XmppProviderImpl$XmppReConnectionListener.reconnectingIn#400: XMPP reconnecting in: 0
Jicofo 2022-04-15 10:03:20.743 INFO: [244] AvModerationHandler.registrationChanged#120: Discovered av_moderation component at avmoderation.jitsimeet.power.com.pl.
Jicofo 2022-04-15 10:03:20.746 INFO: [244] ConferenceIqHandler.registrationChanged#183: Using breakout room component address: breakout.jitsimeet.power.com.pl
Jicofo 2022-04-15 10:03:20.760 INFO: [244] [type=bridge brewery=jvbbrewery] BaseBrewery.start#171: Joined the room.
Jicofo 2022-04-15 10:03:20.760 INFO: [244] [xmpp_connection=client] XmppProviderImpl.fireRegistrationStateChanged#314: Set replyTimeout=PT15S
Jicofo 2022-04-15 10:03:26.482 INFO: [237] [type=bridge brewery=jvbbrewery] BaseBrewery.addInstance#341: Added brewery instance: jvbbrewery@internal.auth.jitsimeet.power.com.pl/37897621-32ac-4b2f-9fbd-d20d7656e3ac
Jicofo 2022-04-15 10:03:26.483 INFO: [237] BridgeSelector.addJvbAddress#95: Added new videobridge: Bridge[jid=jvbbrewery@internal.auth.jitsimeet.power.com.pl/37897621-32ac-4b2f-9fbd-d20d7656e3ac, relayId=null, region=null, stress=0.00]
Jicofo 2022-04-15 10:03:26.483 INFO: [32] JvbDoctor.bridgeAdded#127: Scheduled health-check task for: Bridge[jid=jvbbrewery@internal.auth.jitsimeet.power.com.pl/37897621-32ac-4b2f-9fbd-d20d7656e3ac, relayId=null, region=null, stress=0.00]

/var/log/prosody/prosody.log
**Apr 15 10:03:17 conference.jitsimeet.power.com.pl:muc_domain_mapper     info    Loading mod_muc_domain_mapper for host avmoderation.jitsimeet.power.com.pl!
Apr 15 10:03:17 breakout.jitsimeet.power.com.pl:muc_domain_mapper       info    Loading mod_muc_domain_mapper for host avmoderation.jitsimeet.power.com.pl!
Apr 15 10:03:17 conference.jitsimeet.power.com.pl:muc_domain_mapper     info    Loading mod_muc_domain_mapper for host internal.auth.jitsimeet.power.com.pl!
Apr 15 10:03:17 breakout.jitsimeet.power.com.pl:muc_domain_mapper       info    Loading mod_muc_domain_mapper for host internal.auth.jitsimeet.power.com.pl!
Apr 15 10:03:20 c2s558b7b94e070 info    Client connected
Apr 15 10:03:20 c2s558b7b94e070 info    Stream encrypted (TLSv1.3 with TLS_AES_256_GCM_SHA384)
Apr 15 10:03:20 c2s558b7b94e070 info    Authenticated as d_clp9c_kq2q8zxf@auth.jitsimeet.power.com.pl
Apr 15 10:03:21 c2s558b7b9b0770 info    Client connected
Apr 15 10:03:21 c2s558b7b9b0770 info    Stream encrypted (TLSv1.3 with TLS_AES_256_GCM_SHA384)
Apr 15 10:03:21 c2s558b7b9b0770 info    Authenticated as suvjy9k4-dl_cgki@auth.jitsimeet.power.com.pl

**
![Przechwytywanie](https://user-images.githubusercontent.com/75362505/163547700-49989c70-a999-43b8-949d-e44fd24eb017.PNG)

**Comment by saghul** [comment]
What prosody version did you install?

**Comment by charon78** [comment]
Prosody 0.11.4

**Comment by saghul** [comment]
You don't seem to be using a valid TLS certificate. That is likely why the connection is failing.

**Comment by charon78** [comment]
I don't think so, i have problem with websocket and it was generated certificate when i installed jitsi,

**Comment by saghul** [comment]
It's a self-signed certificate, which won't work unless you add an exception for it. Use a real cert with let's encrypt, it's free and you'll get an environment much closer to production.

**Comment by saghul** [comment]
I just realized this is the Docker setup repo. Please ask in our community instead, this is not the right place since this repo is for the Docekr setup.
