### ISSUE TITLE
etherpad URL is not matched by nginx config

### ISSUE THREAD

**Issue by yuchangyuan** [jitsi/docker-jitsi-meet#1262]
etherpad proxy_pass definition ``location /etherpad/ {`` in ``meet.conf``  is not work, due below regexp will match first
```
    location ~ ^/([^/?&:'"]+)/(.*)$ {
        set $subdomain "$1.";
        set $subdir "$1/";
        rewrite ^/([^/?&:'"]+)/(.*)$ /$2;
    }
```

change ``location /etherpad/ {`` to ``location ^~ /etherpad/ {`` should fix the issue.

**Comment by saghul** [comment]
Thanks! Care to send a PR?

**Comment by yuchangyuan** [comment]
see #1263
