### ISSUE TITLE
Prosody fails to load module `auth_cyrus`

### ISSUE THREAD

**Issue by timoschwarzer** [jitsi/docker-jitsi-meet#1264]
LDAP authentication stopped working with version 7210:

```
modulemanager                                    error	Unable to load module 'auth_cyrus': /usr/lib/prosody/modules/share/lua/5.4/mod_auth_cyrus/mod_auth_cyrus.lua: No such file or directory
```

Version 7001 worked and still works fine.

**Comment by TheRealBro** [comment]
I can confirm this issue. Same here.
```
modulemanager       error        Unable to load module 'auth_cyrus': /usr/lib/prosody/modules/share/lua/5.4/mod_auth_cyrus/mod_auth_cyrus.lua: No such file or directory
```

**Comment by saghul** [comment]
Ah looks like that module was mutated to the community repo: https://prosody.im/doc/release/0.12.0

I'll look into bringing it back or migrating to the better supported mod_auth_ldap.

**Comment by TheRealBro** [comment]
@saghul I digged a bit into it and opened https://github.com/jitsi/docker-jitsi-meet/pull/1265
maybe that helps as a quickfix, would be awesome to see the new version out and running with ldap support.

In the long run  - I agree - support should be moved to mod_auth_ldap for the project
