### ISSUE TITLE
Ldap Problem in 72

### ISSUE THREAD

**Issue by denis-robel** [jitsi/docker-jitsi-meet#1273]
Hallo,

Ldap auth seems to be broken and I cant authenticate. I got this logs:

warn No available SASL mechanisms, verify that the configured authentication module 'cyrus' is loaded and configured correctly.

warn No stream features to offer on secure session. Check authentication settings.

I double checked my configs... Are there any hints? 

The previous version 7001 is working well with ldap.

Best regards 
Denis

**Comment by saghul** [comment]
Please update to the stable release, 7210-2.
