### ISSUE TITLE
Use supplied SSL certs instead of Lets Encrypt and self-signed certs

### ISSUE THREAD

**Issue by dejageek** [jitsi/docker-jitsi-meet#128]
We have *.company.com certs.  In order to use them right now, we have to manually copy them over to the container files.  It would be nice to have an option in .env and a directory in web where we can place the certs and they get added in.

Also, use full chain certs for this too.

**Comment by saghul** [comment]
This is out of the scope of the project, you can just have a simple container with your own certs and then proxy requests to the jitsi web container via HTTP.
