### ISSUE TITLE
Configs not preserved, config.js and nginx.conf in volume gets overwritten on each reboot

### ISSUE THREAD

**Issue by BananaAcid** [jitsi/docker-jitsi-meet#1281]
There seems to be a bug, where the exported `/.jitsi-meet-cfg/web/nginx/nginx.conf` ... in the volume gets replaced on restart of the container, removing all manual changes.

Same is true for `/.jitsi-meet-cfg/config.js`

**Comment by saghul** [comment]
Not a bug, this is intentional behavior.

If you want to customize the config you have env variables, and the possibility to add more stuff in a config-custom.js file.
