### ISSUE TITLE
http-bind timeout error after mute/unmute participant

### ISSUE THREAD

**Issue by denis-ionov** [jitsi/docker-jitsi-meet#1290]
Question: chat running normally (http-bind's every 10sec) until some action (mute), after this next http-bind request timed out after 1 minute with 504.

web container nginx error:
`
2022/05/20 08:03:48 [error] 260#260: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: _, request: "POST /http-bind?room=[ROOM]&token=[TOKEN] HTTP/2.0", upstream: "http://172.18.0.4:5280/http-bind?room=[ROOM]&token=[TOKEN]", host: "meet.my.host:8443", referrer: "https://my.host/"
`

**Comment by saghul** [comment]
Do you see any errors in the prosody container logs?

**Comment by denis-ionov** [comment]
Seems that no errors in prosody container

**Comment by saghul** [comment]
What about the JS console logs?

**Comment by denis-ionov** [comment]
Firstly three times of:
`Logger.js:154 2022-05-20T09:21:06.343Z [esm/modules/xmpp/strophe.ping.js] Ping timeout null`

then:
`
Access to XMLHttpRequest at 'https://meet.my.host:8443/http-bind?room=ROOM&token=TOKEN' from origin 'https://my.host' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
`

then:
`
2022-05-20T09:21:32.323Z [esm/modules/xmpp/strophe.util.js] <Object.ut.Strophe.log>:  Strophe: request id 173.1 error 0 happened
`

and then 504 itself:
`
strophe.umd.js:5405          POST https://meet.my.host:8443/http-bind?room=ROOM&token=TOKEN net::ERR_FAILED 504
`

**Comment by saghul** [comment]
That's very odd. There is no correlation between the CORS error and muting. Are you sure the error doesn't happen even when you leave it alone?

Also, what image version are you running?

**Comment by denis-ionov** [comment]
@saghul All versions are last stable. I think i figure out what this problem about (but no ideas why) - this issue happens when i mute/unmute JitsiLocalTrack object when it wrapped into Vue reactivity. If i interact with JitsiLocalTrack itself its ok, but if this track is stored somewhere in Vue class it became Vue Proxy(JitsiLocalTrack) and actions on wrapped track cause this problems.

**Comment by kumarhardeep01** [comment]
I am facing the same problem, how did you solved @denis-ionov

**Comment by denis-ionov** [comment]
@kumarhardeep01 I wrote in the comment above what my problem was
