### ISSUE TITLE
Decrease JITSI resolution

### ISSUE THREAD

**Issue by kinseii** [jitsi/docker-jitsi-meet#1292]
When streaming video to Youtube, I observe frame skipping and buffering, as a consequence JIBRI drops. I want to reduce the quality of the transmitted video. I wrote in .env file option JIBRI_RECORDING_RESOLUTION=720, but with this option JIBRI gives error. How can I tell JIBRI to use needed resolution?

**Comment by prayagsingh** [comment]
If you are not setting the resolution then by default it's `1280x720` only.
check [here](https://github.com/jitsi/docker-jitsi-meet/blob/741ec4acdbea1f7ffb1aab29ee5b18540df7853b/jibri/rootfs/defaults/jibri.conf#L4)

IDK if we can lower the resolution below `1280x720`. @saghul Is it possible?

**Comment by kinseii** [comment]
Problem was solved by setting: JIBRI_RECORDING_RESOLUTION=854x480
