### ISSUE TITLE
Newest (05/22) .ENV and docker is wrong, not working

### ISSUE THREAD

**Issue by honestlai** [jitsi/docker-jitsi-meet#1294]
Hey guys, 

I've been using/deploying Jitsi meet for a few years now and have loved this project... but this latest release just isn't working. I've successfully deployed this many times, but this has been the one I've struggled most with.

If you follow this guide https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker/, it does not work

The ENV sample file is missing some critical items like 

```
# Internal XMPP domain
XMPP_DOMAIN=meet.jitsi

# Internal XMPP server
XMPP_SERVER=xmpp.meet.jitsi

# Internal XMPP server URL
XMPP_BOSH_URL_BASE=http://xmpp.meet.jitsi:5280

# Internal XMPP domain for authenticated services
XMPP_AUTH_DOMAIN=auth.meet.jitsi

# XMPP domain for the MUC
XMPP_MUC_DOMAIN=muc.meet.jitsi

# XMPP domain for the internal MUC used for jibri, jigasi and jvb pools
XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi

# XMPP domain for unauthenticated users
XMPP_GUEST_DOMAIN=guest.meet.jitsi
```

Without this, the web ui docker won't load because of configuration issues in the meet.conf file. 

I've been trying to use an old .ENV file from a previous installation to get my new installation working, but so far I can't get any audio/video functioning. I've turned off all firewall rules. At this point, I'm probably going to pull the working github copy I have on one of my other servers to get my new instance functioning.

But in case any of the devs is reading these posts, you should def try deploying on a vanilla Ubuntu 21.10 VM and see for yourself.

-Matt

**Comment by kinseii** [comment]
I think this is because you are using the latest unstable version. The documentation talks about the latest stable version for workloads

**Comment by honestlai** [comment]
That definitely helps, the env example file definitely has far more settings, including the crucial ones mentioned. I'm still unable to get video/audio between clients working, but that may be an issue with my server.

I'm seeing the below on the JVB logs. Not sure what this line is all about, or what the 10.x.x.x ip is that the system is trying to connect to

java.lang.IllegalArgumentException: No socket found for 172.0.0.4:10000/udp->10.147.0.100:64486/udp

```
JVB 2022-05-28 11:19:43.088 INFO: [53] [confId=ca0790b75dba7b30 conf_name=test@muc.meet.jitsi gid=-2 epId=083c8cae stats_id=Justine-EO6 local_ufrag=61o8s1g468k2b1] IceTransport.startConnectivityEstablishment#198: Starting the Agent without remote candidates.
JVB 2022-05-28 11:19:43.091 INFO: [53] [confId=ca0790b75dba7b30 conf_name=test@muc.meet.jitsi gid=-2 epId=083c8cae stats_id=Justine-EO6 local_ufrag=61o8s1g468k2b1 ufrag=61o8s1g468k2b1] Agent.startConnectivityEstablishment#736: Start ICE connectivity establishment.
JVB 2022-05-28 11:19:43.091 INFO: [53] [confId=ca0790b75dba7b30 conf_name=test@muc.meet.jitsi gid=-2 epId=083c8cae stats_id=Justine-EO6 local_ufrag=61o8s1g468k2b1 ufrag=61o8s1g468k2b1] Agent.initCheckLists#972: Init checklist for stream stream-083c8cae
JVB 2022-05-28 11:19:43.092 INFO: [53] [confId=ca0790b75dba7b30 conf_name=test@muc.meet.jitsi gid=-2 epId=083c8cae stats_id=Justine-EO6 local_ufrag=61o8s1g468k2b1 ufrag=61o8s1g468k2b1] Agent.setState#946: ICE state changed from Waiting to Running.
JVB 2022-05-28 11:19:43.092 INFO: [53] [confId=ca0790b75dba7b30 conf_name=test@muc.meet.jitsi gid=-2 epId=083c8cae stats_id=Justine-EO6 local_ufrag=61o8s1g468k2b1] IceTransport.iceStateChanged#341: ICE state changed old=Waiting new=Running
JVB 2022-05-28 11:19:43.092 INFO: [53] [confId=ca0790b75dba7b30 conf_name=test@muc.meet.jitsi gid=-2 epId=083c8cae stats_id=Justine-EO6 local_ufrag=61o8s1g468k2b1 ufrag=61o8s1g468k2b1] ConnectivityCheckClient.startChecks#147: Start connectivity checks.
JVB 2022-05-28 11:19:43.118 WARNING: [60] [confId=ca0790b75dba7b30 conf_name=test@muc.meet.jitsi gid=-2 epId=8ef0df41 stats_id=Linda-G2H local_ufrag=dv3bk1g468k0us ufrag=dv3bk1g468k0us] ConnectivityCheckClient.startCheckForPair#375: Failed to send BINDING-REQUEST(0x1)[attrib.count=6 len=92 tranID=0x0D0E8A0C810151B7DF4FED0C]
java.lang.IllegalArgumentException: No socket found for 172.0.0.4:10000/udp->10.147.0.100:64486/udp
	at org.ice4j.stack.NetAccessManager.sendMessage(NetAccessManager.java:631)
	at org.ice4j.stack.NetAccessManager.sendMessage(NetAccessManager.java:581)
	at org.ice4j.stack.StunClientTransaction.sendRequest0(StunClientTransaction.java:267)
	at org.ice4j.stack.StunClientTransaction.sendRequest(StunClientTransaction.java:245)
	at org.ice4j.stack.StunStack.sendRequest(StunStack.java:680)
	at org.ice4j.ice.ConnectivityCheckClient.startCheckForPair(ConnectivityCheckClient.java:333)
	at org.ice4j.ice.ConnectivityCheckClient.startCheckForPair(ConnectivityCheckClient.java:229)
	at org.ice4j.ice.ConnectivityCheckClient$PaceMaker.run(ConnectivityCheckClient.java:939)
	at org.ice4j.util.PeriodicRunnable.executeRun(PeriodicRunnable.java:206)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
JVB 2022-05-28 11:19:43.118 INFO: [60] [confId=ca0790b75dba7b30 conf_name=test@muc.meet.jitsi gid=-2 epId=8ef0df41 stats_id=Linda-G2H local_ufrag=dv3bk1g468k0us ufrag=dv3bk1g468k0us] ConnectivityCheckClient$PaceMaker.run#943: Pair failed: 172.0.0.4:10000/udp/host -> 10.147.0.100:64486/udp/host (stream-8ef0df41.RTP)
```

**Comment by saghul** [comment]
> Hey guys, 
> 
> 
> 
> I've been using/deploying Jitsi meet for a few years now and have loved this project... but this latest release just isn't working. I've successfully deployed this many times, but this has been the one I've struggled most with.
> 
> 
> 
> If you follow this guide https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker/, it does not work
> 
> 
> 
> The ENV sample file is missing some critical items like 
> 
> 
> 
> ```
> 
> # Internal XMPP domain
> 
> XMPP_DOMAIN=meet.jitsi
> 
> 
> 
> # Internal XMPP server
> 
> XMPP_SERVER=xmpp.meet.jitsi
> 
> 
> 
> # Internal XMPP server URL
> 
> XMPP_BOSH_URL_BASE=http://xmpp.meet.jitsi:5280
> 
> 
> 
> # Internal XMPP domain for authenticated services
> 
> XMPP_AUTH_DOMAIN=auth.meet.jitsi
> 
> 
> 
> # XMPP domain for the MUC
> 
> XMPP_MUC_DOMAIN=muc.meet.jitsi
> 
> 
> 
> # XMPP domain for the internal MUC used for jibri, jigasi and jvb pools
> 
> XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
> 
> 
> 
> # XMPP domain for unauthenticated users
> 
> XMPP_GUEST_DOMAIN=guest.meet.jitsi
> 
> ```
> 
> 
> 
> Without this, the web ui docker won't load because of configuration issues in the meet.conf file. 
> 
> 
> 
> I've been trying to use an old .ENV file from a previous installation to get my new installation working, but so far I can't get any audio/video functioning. I've turned off all firewall rules. At this point, I'm probably going to pull the working github copy I have on one of my other servers to get my new instance functioning.
> 
> 
> 
> But in case any of the devs is reading these posts, you should def try deploying on a vanilla Ubuntu 21.10 VM and see for yourself.
> 
> 
> 
> -Matt

The first item in the list mentions to NOT get the code from git but use a release directly.

master no longer needs so many settings, the setup is simpler, but you need to be using unstable images.

The socket errors are not critical nor indicative of an issue (I k ow they are misleading, they will be gone in the next stable).

Please re-test your setup using a fresh release and open a new issue if you still can't get it to work.
