### ISSUE TITLE
Can't chat with participants on Firefox v101.0 (64 bits)

### ISSUE THREAD

**Issue by the-lazy-fox** [jitsi/docker-jitsi-meet#1299]
Hi there,

I'm running a pretty simple self hosted setup with default docker compose stack.
The only things I have customized are:
- ENABLE_XMPP_WEBSOCKET=0 in .env file otherwise it was looping on the connection screen
- PUBLIC_URL in .env file to match my public reverse proxy subdomain

I've read a lot of issues and I don't know if I miss anything to make it works with Firefox. _Chrome is fine, chat and screen sharing are working._

In Firefox, No microphone can be selected, no audio device neither nor audio test. Screen sharing is missing as well.
My console is full of the following logs: https://pastebin.com/2df0JLnN

Thank you!
Let me know if you need more details

**Comment by saghul** [comment]
The paste in gives a 404.

**Comment by the-lazy-fox** [comment]
Hello @saghul 
Weird, edited!

**Comment by saghul** [comment]
How does a full URL look for you? (You can mask the domain if you want, but keep the rest intact please)

**Comment by the-lazy-fox** [comment]
Hello @saghul 
https://meet.domain.com

**Comment by the-lazy-fox** [comment]
Hello @saghul 
Any ideas?

**Comment by saghul** [comment]
Have you updated to the latest images?
