### ISSUE TITLE
error(TypeError){"message":"Network request failed", when I run android example ,i have this problem.

### ISSUE THREAD

**Issue by dualven** [jitsi/docker-jitsi-meet#1307]
(1) I clone https://github.com/jitsi/docker-jitsi-meet , to run the docker envirement . it is successful.
 I can communicate with others by web browse , so I want to test the android client.
 (2) I clone https://github.com/jitsi/jitsi-meet-sdk-samples.git . I want to run this project: 
 \jitsi-meet-sdk-samples\android\java\JitsiSDKTest 
 
 I change the serverURL 
      // When using JaaS, replace "https://meet.jit.si" with the proper serverURL
            serverURL = new URL("https://10.60.100.190:8443");
            
            
in android studio, I run it , but I can't enter the room . It has the  error below:
Failed to load config from https://10.60.100.190:8443/config.js?room=yyyy Error(TypeError){"message":"Network request failed","stack":"index.android.bundle:116:8201\nindex.android.bundle:603:498\nvalue@index.android.bundle:29:1293\nvalue@index.android.bundle:45:3557\nindex.android.bundle:45:674\nvalue@index.android.bundle:45:2504\nvalue@index.android.bundle:45:646\nvalue@[native code]"}

Please give me some help or some tips ?

**Comment by saghul** [comment]
You need a proper TLS certificate on mobile, the self-signed one won't work.

Use a real domain and let's encrypt if you don't already have one.
