### ISSUE TITLE
Dumb Question

### ISSUE THREAD

**Issue by WriteCodeEveryday** [jitsi/docker-jitsi-meet#1310]
I'm using the prosody docker container.

I added ["muc_max_occupants" to XMPP_MUC_MODULES... ](https://github.com/jitsi/docker-jitsi-meet/blob/7c29b57914125ba37ea0df90242d2344b5d8f7fa/prosody/rootfs/defaults/conf.d/jitsi-meet.cfg.lua#L227) ... [how can I add the configurations to the block below it through ENV variables](https://github.com/jitsi/docker-jitsi-meet/blob/7c29b57914125ba37ea0df90242d2344b5d8f7fa/prosody/rootfs/defaults/conf.d/jitsi-meet.cfg.lua#L243=) since it resets the config every time the docker container starts up.

I'm [using the following config set](https://community.jitsi.org/t/solved-where-to-add-the-muc-max-occupants-to-limit-participants-in-a-meeting/73968/2)

 muc_max_occupants = "2"
 muc_access_whitelist = { "recorder@auth.meet.example.com" }

**Comment by saghul** [comment]
It's currently not possible to do that.

**Comment by saghul** [comment]
Given it's a module we supply we should make in configurable with env variables. Would you like to send a PR?

**Comment by WriteCodeEveryday** [comment]
Yeah, it seems likely but I don't know if that would require a new release from jitsi? I'm currently on an old stable build.

**Comment by saghul** [comment]
In order to be incorporated into the images yeah it would.

**Comment by saghul** [comment]
A release of the images that is, not of the Jitsi Meet frontend or backend, that is.
