### ISSUE TITLE
docker-setup with stable-7287 in AWS ECS & Loadbalancer not working for morethan 2 participants

### ISSUE THREAD

**Issue by nikhilgoud** [jitsi/docker-jitsi-meet#1320]
I've configured the setup in AWS ECS following the steps mentioned here https://aws.amazon.com/blogs/opensource/getting-started-with-jitsi-an-open-source-web-conferencing-solution/

There are too many console errors and also errors related to **colibri-ws** websocket connection
the setup is only working for 2 participants, 
I've modified the following env variables only
**PUBLIC_URL** = 'added loadbalancer url'
**ENABLE_AUTH** = 0
**JIBRI_RECORDER_PASSWORD, JIBRI_XMPP_PASSWORDJICOFO_AUTH_PASSWORD, JIGASI_XMPP_PASSWORD, JVB_AUTH_PASSWORD** = generate a random passwd and added to these

![image](https://user-images.githubusercontent.com/21196948/173814102-82cd6574-4e64-483e-9cf9-8cca4bf8ce57.png)

Please let me know if I'm missing any additional configurations

**Comment by nikhilgoud** [comment]
> Please try the -2 release, I fixed a bug hat would have explained what you see.

Let me try,

**Comment by nikhilgoud** [comment]
> Please try the -2 release, I fixed a bug hat would have explained what you see.

Still the same error @saghul 
![image](https://user-images.githubusercontent.com/21196948/174790469-589ff447-f8d9-4ff6-b8a3-b524b2fd7339.png)

**Comment by saghul** [comment]
Are you sure you recreated the containers? I still see the IP missing in the URL.

**Comment by nikhilgoud** [comment]
Yes, used new setup
Do I need to set any additional env variables?

**Comment by saghul** [comment]
No, that's automatically set in -2. I cannot reproduce your issue.

**Comment by nikhilgoud** [comment]
As my setup includes AWS ECS and also a loadbalancer url
Am I missing anything like setting the DOCKER_HOST_ADDRESS

anyhow it is not mentioned in https://aws.amazon.com/blogs/opensource/getting-started-with-jitsi-an-open-source-web-conferencing-solution/

**Comment by nikhilgoud** [comment]
that line is there

please look at the generated jvb.conf in the docker container 

```  
videobridge {
    ice {
        udp {
            port = 10000
        }
    }
    apis {
        xmpp-client {
            configs {

                shard0 {
                    HOSTNAME = "xmpp.meet.jitsi"
                    PORT = "5222"
                    DOMAIN = "auth.meet.jitsi"
                    USERNAME = "jvb"
                    PASSWORD = "Q!A@z3w4"
                    MUC_JIDS = "jvbbrewery@internal-muc.meet.jitsi"
                    MUC_NICKNAME = "139b24c6aaa0"
                    DISABLE_CERTIFICATE_VERIFICATION = true
                }

            }
        }
        rest {
            enabled = false
        }
    }
    rest {
        shutdown {
            enabled = false
        }
    }
    stats {
        enabled = true
    }
    websockets {
        enabled = true
        domain = "#######.###" #public url is added here, I've masked it with #
        tls = true
        server-id = ""
    }
    http-servers {
        private {
          host = 0.0.0.0
        }
        public {
            host = 0.0.0.0
            port = 9090
        }
    }

    }

ice4j {
    harvest {
        mapping {
            stun {
addresses = [ "meet-jit-si-turnrelay.jitsi.net:443" ]
}
            static-mappings = [
]
        }
    }
}
```

**Comment by saghul** [comment]
It should be mapped to the private IP of the container. The web container will forward data channels to that IP port 9090.

**Comment by nikhilgoud** [comment]
Is there any way to map that manually?
I've tried setting the env variable XMPP_SERVER and deployed once again, still getting the same issue

Not sure of what am I missing here

**Comment by saghul** [comment]
Are you passing all variables that our compose file passes?

**Comment by nikhilgoud** [comment]
Not all the variables, I've copied the .env.example file and modied the below variables

PUBLIC_URL = 'added loadbalancer url'
ENABLE_AUTH = 0
JIBRI_RECORDER_PASSWORD, JIBRI_XMPP_PASSWORDJICOFO_AUTH_PASSWORD, JIGASI_XMPP_PASSWORD, JVB_AUTH_PASSWORD
XMPP_SERVER=xmpp.meet.jitsi

**Comment by saghul** [comment]
Can you try to get a shell and run this in the container:

```
XMPP_SERVER_IP=$(dig +short +search ${XMPP_SERVER})

echo $XMPP_SERVER_IP

ip route get ${XMPP_SERVER_IP} | grep -oP '(?<=src ).*' | awk '{ print $1 '}

```

**Comment by nikhilgoud** [comment]
not getting the IP

```

root@ddc57961cba1:/# dig $XMPP_SERVER

; <<>> DiG 9.16.27-Debian <<>> xmpp.meet.jitsi
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 52627
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;xmpp.meet.jitsi.               IN      A

;; Query time: 0 msec
;; SERVER: 172.16.0.2#53(172.16.0.2)
;; WHEN: Fri Jun 24 10:53:23 UTC 2022
;; MSG SIZE  rcvd: 44

```

![image](https://user-images.githubusercontent.com/21196948/175519994-f8154b99-2190-459c-86c7-a15342c4d5b8.png)

**Comment by saghul** [comment]
Interesting. That FQDN doesn't need to be real but it needs to be resolved to the IP address of the Prosody container.

What does the AWS guide you set that to?

**Comment by ShreyasBhaktharam** [comment]
Hi. I'm also facing the same issue after following the steps mentioned in this guide:
https://aws.amazon.com/blogs/opensource/getting-started-with-jitsi-an-open-source-web-conferencing-solution/

The version I'm using is [stable-7287-2](https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-7287-2)

I've followed all the steps listed in the issue and I'm stuck at the same step. The AWS guide does not tell us to resolve the IP address of the prosody container. How can we do that manually?

**Comment by BMA-Ronan** [comment]
Hi,

I'm working on this too. So when you use the following task in AWS guide :  
_Scroll down to the Network Settings and in the box called Links enter prosody:xmpp.meet.jitsi_.  
_Select the Prosody container, and scroll down to the Network settings, and this time enter xmpp.meet.jitsi in the Hostname and then click on Update._   
That's create host config in /etc/hosts, but can be resolve by tools like dig / nslookup ..
My solution, create cloudmap namespace meet.jitsi, add service xmpp and Service instance to the IP of EC2, but this manual task like container definitions update is not the best way for IaC deployment (docker compose with ecs handle cloudmap but doesn't support ECS with EC2 deploment, only FARGATE) ..  



Also I ran into a WS url problem, my websocket config is good now :  
`    websockets {
        enabled = true
        domain = "%PUBLIC_IP%:443"
        tls = true
        server-id = "%PRIVATE_IP%"
    }`. 
But when I try to create and join room the websocker url isn't good :  
_Firefox can’t establish a connection to the server at wss://localhost:8443/xmpp-websocket?room=test._


Sorry for my bad english,

Ronan

**Comment by BMA-Ronan** [comment]
I fixed my WS url problem.  
I use IP instead of Domain Name.

**Comment by gitbhavesh07** [comment]
@BMA-Ronan , Will you be able to share the latest task definition file to host the jitsi in ECS
