### ISSUE TITLE
jvb: Can't disable STUN in JVB because of default value

### ISSUE THREAD

**Issue by HansGeiz** [jitsi/docker-jitsi-meet#1321]
JVB_STUN_SERVERS can't be empty and it is not possible to disable STUN.

/jvb/rootfs/defaults/jvb.conf:
...
**{{ $JVB_STUN_SERVERS := .Env.JVB_STUN_SERVERS | default "meet-jit-si-turnrelay.jitsi.net:443" -}}**
...
ice4j {
    harvest {
        mapping {
            stun {
{{ if $JVB_STUN_SERVERS -}}
                addresses = [ "{{ join "\",\"" (splitList "," $JVB_STUN_SERVERS) }}" ]
{{ else -}}
                enabled = false
{{ end -}}

**Comment by saghul** [comment]
Good point.
