### ISSUE TITLE
How do i get "Or book a meeting URL in advance" option?

### ISSUE THREAD

**Issue by Issykul** [jitsi/docker-jitsi-meet#1322]
Hey i just hosted my own jitsi meet on my server and i need the function to create jitsi rooms in advance for our team meetings.

What do i need to edit to achieve this?

![Screenshot](https://i.imgur.com/tJDnujL.png)

**Comment by damencho** [comment]
You need to configure and deploy https://github.com/jitsi/moderated-meetings
And make sure your images configure this `moderatedRoomServiceUrl` in config.js with the link to the newly deployed service.

**Comment by Issykul** [comment]
> 

How would i deploy it as a docker container? Do i need to build my own image with the Dockerfile?
