### ISSUE TITLE
docker error Synology

### ISSUE THREAD

**Issue by gpopesc** [jitsi/docker-jitsi-meet#1325]
Hello,

I had used in the past the Synology package from @TosoBoso with  DSM 7.0. After upgrade to DSM 7.1 the package is no longer working for me. Even the source of it cphub.net is down.

I tried to install standard docker version by cloning github project of jitsi docker, I generated the passwords, created folders, put my own IP and domain in env file.
```

ENABLE_AUTH=1
ENABLE_GUESTS=1
AUTH_TYPE=internal
PUBLIC_URL=https://meet.mydomain.com
DOCKER_HOST_ADDRESS=my.public.ip
```

After I run docker containers (web, prosody, jvb, jicofo), I got following errors in containers:

web:
`nginx: [emerg] invalid number of arguments in "proxy_pass" directive in /config/nginx/meet.conf:63`

prosody:
```
startup error No enabled VirtualHost entries found in the config file.
startup error At least one active host is required for Prosody to function. Exiting...
```

I cannot access the container direct inside my network or by reverse proxy, although the containers are running.
Being error inside container, here it would be the first step to ask.

Any help is appreciated.

**Comment by gretzke** [comment]
was just working on the exact same error, so if you are still encounter the same problem even when following the documentation, don't uncomment the following line in your `.env` file
`#JITSI_IMAGE_VERSION=latest`
