### ISSUE TITLE
web configuration file content appended to `conf/web/config.js` each time `docker-compose up` is called

### ISSUE THREAD

**Issue by pawlakm** [jitsi/docker-jitsi-meet#1327]
### Version

stable-7287-2

### Issue

Each time `docker-compose stop` then `docker-compose up` is called, the configuration is appended again and again into the web configuration file `conf/web/config.js`

**Comment by saghul** [comment]
This was fixed in https://github.com/jitsi/docker-jitsi-meet/commit/576e5a9086a57f97f21e6f116eddd491b5cf588e and will be part of the next release.
