### ISSUE TITLE
Configure `docker-compose.yml`to expose all log files 

### ISSUE THREAD

**Issue by pawlakm** [jitsi/docker-jitsi-meet#1329]
Similarly to having a `<path_to>/conf` directory with subdirectories which contain configuration files, it wold be great to have all logs in a `<path_to>/log/` directory, 

In this `<path_to>/log` directory, logs could be split by service (i.e. jvb,web,meet,etc)

**Comment by saghul** [comment]
Containers either log to stdout, or when necessary to /config/<service>.log as in the case of Jibri.

**Comment by pawlakm** [comment]
It would be great to avoid mixing logs in the config directory

**Comment by pawlakm** [comment]
Is it possible to have a discussion prior to closing issues ?

**Comment by saghul** [comment]
> It would be great to avoid mixing logs in the config directory

Why?

> Is it possible to have a discussion prior to closing issues ?

Closing an issue doesn't prevent further discussion, I haven't locked it.

**Comment by pawlakm** [comment]
> > It would be great to avoid mixing logs in the config directory
> 
> Why?

For the same reason `/etc/` and `/var/log` are separated locations. 
By the way, being able to use logging to files for logs (instead of stdout only) would be useful as well.
Hope you'll consider this request.
