### ISSUE TITLE
SIP integration (jigasi) broken since version 7287

### ISSUE THREAD

**Issue by tom666-debug** [jitsi/docker-jitsi-meet#1334]
Hi,

Since version 7287 (including 7287-1, 7287 -2 and the latest version 7439) the SIP intgeration seems to be broken and is no longer working for me. On version stable-7210-2 everything still works as expected, means I am able to add participants via the SIP gateway.

This is what I have found out so far after a first quick check of the issue:
1. Entry in jicofo docker log saying:  WARNING: [38] JigasiIqHandler.inviteJigasi#102: **Request failed, no instances available:** 
2. sip-communicator.properties file was created but is completley empty

Docker containers were created with the latest versions of the compose and .env files.

Any hint how to solve or further troubleshoot this, would be much appreciated.

**Comment by saghul** [comment]
Can you share the output of the Jigasi container? I suspect the last 2 commits that landed this morning fix that.

**Comment by tom666-debug** [comment]
Sure, here you are: [_jitsi_jigasi_logs.txt](https://github.com/jitsi/docker-jitsi-meet/files/8975160/_jitsi_jigasi_logs.txt)

thx for having a look!

**Comment by saghul** [comment]
Yep, that was it, sorry about that, my mistake. I'll kick off a -1 release.

**Comment by tom666-debug** [comment]
That was quick :-) .... thx!

**Comment by saghul** [comment]
Should be fixed in stable-7439-2 cheers!

**Comment by tom666-debug** [comment]
I can confirm that the issue is fixed with version 7439-2. Thanks!
