### ISSUE TITLE
Users are alone in rooms when `ENABLE_AUTH=1` and `ENABLE_GUESTS=0`

### ISSUE THREAD

**Issue by pawlakm** [jitsi/docker-jitsi-meet#1336]
Hello,

Running version of `docker-jitsi-meet`: stable-7439-2

### The issue:

If I set `ENABLE_GUESTS` to `0`, `ENABLE_AUTH` to `1` ~~and `AUTH_TYPE` to `internal`~~ in the `.env` file, run `docker-compose up` then create internal users as described in the documentation, created users can login and create rooms, however when they enter the room they do not see each other, each one of them is alone in the room (same room name).

If I stop and rm the container, turn `ENABLE_AUTH` to `0`, `ENABLE_GUESTS` to `1`, and re-run `docker-compose up`, as expected there is no internal auth anymore, anyone can create rooms and eveybody can see each other in the rooms.

### Configuration files

Here is the content of the `.env` file.

```
CONFIG=<path/to/conf>                          
HTTP_PORT=8000
HTTPS_PORT=<https_port>
TZ=CET +0200
PUBLIC_URL=https://<server_public_fqdn>:<https_port>
DOCKER_HOST_ADDRESS=<server_public_static_ip>
RESTART_POLICY=always
ENABLE_IPV6=0
ENABLE_P2P=0
JVB_DISABLE_STUN=1
AUTH_TYPE=internal # or ldap


ENABLE_AUTH=1
ENABLE_GUESTS=0
```

**Comment by saghul** [comment]
Can you share the logs in the browser console of either user?

**Comment by pawlakm** [comment]
By the way: I'm not using private browsing tab. and the issue also occurs between a fresh firefox install and a Jitsi Meet android application.

**Comment by saghul** [comment]
I don't see anything suspicious in the logs. Are you using a nonstandard port? I cannot guarantee a bugfree experience in that case because that's not a scenario we test.

Also, if android is involved, you need a working cert chain, check here: https://whatsmychaincert.com/

**Comment by pawlakm** [comment]
Yes I use a non standard port for both `HTTPS_PORT` and `JVB_PORT` I will check with standard ports to make sure that it is not the cause of the issue. 

That being said, with the same non-standard ports, on a "non-docker" install of Jitsi-meet, everything works fine (I can check the version of Jitsi)

When I wrote that the same issue occurs when using an android client, I meant that the issue occurs on them but is not limited to them. On all devices (workstations, laptops, android devices) that I test tested:
- if internal auth is disabled: everything works perfectly 
- if internal auth is enabled: every logged user with credentials registered on the prosody node is in his own room, alone.

**Comment by pawlakm** [comment]
> Are you using a nonstandard port?

Changed back to standard ports and the issue remains.
 
One strange thing I observe in the server logs is that when connecting from an Android device, after having logged in, there are jitsi-jicofo-1 logs stating something like this:

```
jitsi-jicofo-1   | Jicofo 2022-06-29 15:02:09.581 INFO: [40] ConferenceIqHandler.handleConferenceIq#63: Focus request for room: testroom@muc.meet.jitsi
jitsi-jicofo-1   | Jicofo 2022-06-29 15:02:09.581 INFO: [40] AbstractAuthAuthority.authenticateJidWithSession#431: Authenticated jid: user1@meet.jitsi/90XrpouhDuSE with session: AuthSession[ID=user1@meet.jitsi, JID=user1@meet.jitsi/90XrpouhDuSE, SID=2597fc94-d7db-44be-b00e-06fa91befd3c, MUID=aa638b93824375b0a0fd6a15b704ea6c, LIFE_TM_SEC=475, R=test@muc.meet.jitsi]@946392942
jitsi-jicofo-1   | Jicofo 2022-06-29 15:02:09.581 INFO: [40] AbstractAuthAuthority.notifyUserAuthenticated#339: Jid user1@meet.jitsi/90XrpouhDuSE authenticated as: user1@meet.jitsi
jitsi-jicofo-1   | Jicofo 2022-06-29 15:02:09.582 INFO: [40] [room=testroom@muc.meet.jitsi] JitsiMeetConferenceImpl.<init>#258: Created new conference.
jitsi-jicofo-1   | Jicofo 2022-06-29 15:02:09.582 INFO: [40] [room=testroom@muc.meet.jitsi] JitsiMeetConferenceImpl.joinTheRoom#442: Joining testroom@muc.meet.jitsi
jitsi-web-1      | 213.55.221.91 - - [29/Jun/2022:15:02:09 +0000] "POST /http-bind?room=testroom HTTP/2.0" 200 1096 "-" "okhttp/4.9.2"
jitsi-web-1      | 213.55.221.91 - - [29/Jun/2022:15:02:09 +0000] "POST /http-bind?room=testroom HTTP/2.0" 200 2033 "-" "okhttp/4.9.2"
jitsi-jicofo-1   | Jicofo 2022-06-29 15:02:09.915 INFO: [31] [room=testroom@muc.meet.jitsi meeting_id=58472a2d-3bcc-4e63-a713-ccd27c3cfeb0] JitsiMeetConferenceImpl.onMemberJoined#589: Member joined:243f1b1e stats-id=Colt-yHP region=null audioMuted=true videoMuted=true isJibri=false isJigasi=false
```

These logs do not appear when I'm trying to log in using firefox.

So I tried to set `ENABLE_AUTH` to `0`, `ENABLE_GUESTS` to `1` and as a result,both from the android device and from firefox I see these jicofo logs stating that the user is joining the room!

I checked then if there is a difference with `ENABLE_AUTH` set to `1`, `ENABLE_GUESTS` to `1` (i.e. keeping guests enabled while enabling internal auth) and it works! The issue then is that only the first person joining the room has to login. This person becomes the moderator, and all other people joining the room can enter it as guests.

Is it the intended behavior ? Is there a way to force everybody to login to join a room ?

**Comment by pawlakm** [comment]
I just re-read the documentation page which states:

> If guest access is enabled, unauthenticated users will need to wait until a user authenticates before they can join a room. If guest access is not enabled, every user will need to authenticate before they can join.

My understanding is that to have all users authenticate in order to join the room one has to set `ENABLE_AUTH` to `1` and `ENABLE_GUESTS` to `0`. As such I really think that I am facing a bug. Can you please confirm ?

**Comment by bgrozev** [comment]
> My understanding is that to have all users authenticate in order to join the room one has to set `ENABLE_AUTH` to `1` and `ENABLE_GUESTS` to `0`.

That is correct. What do you observe instead? Is your firefox user allowed to join without logging in? Or does it fail to join the conference after logging in? Can you include jicofo logs from the case which is broken?

**Comment by pawlakm** [comment]
As I wrote above, when `ENABLE_AUTH` is set to `1` and `ENABLE_GUESTS` is set to `0`and joining a room (for instance "testroom"):
- to enter the room all users have to provide the credentials that have been set using `prosodyctl` 
- on server side, when joining a room, users using the android app trigger `jitsi-jicofo-1` logs showing that the user joined the room (see the logs in the above post)
- on server side, when joining a room, users using firefox DO NOT trigger `jitsi-jicofo-1` logs showing that the user joined the room (there is no jicofo logs stating it)
- all users are alone in the room 
- all users are marked as moderators of the room

When I write that there is no jicofo logs, here are the only logs which appear on the console at the time when the testuser enters the room (and is then alone):

```
jitsi-web-1      | 10.10.1.2 - - [29/Jun/2022:23:07:41 +0200] "GET /test HTTP/2.0" 200 9241 "https://<public_fqdn>:<https_port>" "Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0"
jitsi-prosody-1  | c2s55d1043a3d70                                              info	Client connected
jitsi-prosody-1  | c2s55d1043a3d70                                              info	Client disconnected: connection closed
jitsi-web-1      | 10.10.1.2 - - [29/Jun/2022:23:07:43 +0200] "GET /xmpp-websocket?room=testroom HTTP/1.1" 101 380 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0"
jitsi-prosody-1  | c2s55d10441f560                                              info	Client connected
jitsi-prosody-1  | c2s55d10441f560                                              info	Authenticated as testuser@meet.jitsi
```

When `ENABLE_AUTH` is set to `0` and `ENABLE_GUESTS` is set to `1`and joining a "testroom" room
- no credentials are required to enter the room
- on server side, when joining a room, users using the android app trigger `jitsi-jicofo-1` logs showing that the user joined the room
- on server side, when joining a room, users using firefox trigger `jitsi-jicofo-1` logs showing that the user joined the room 
- all users are together in the room 

When `ENABLE_AUTH` is set to `1` and `ENABLE_GUESTS` is set to `1`and joining a "testroom" room
- credentials are required for the first person which answers "I am the host" in the UI
- other people, once a host has joined, can enter the room without providing credentials
- on server side, when joining a room, users using the android app trigger `jitsi-jicofo-1` logs showing that the user joined the room
- on server side, when joining a room, users using firefox trigger `jitsi-jicofo-1` logs showing that the user joined the room 
- all users are together in the room

**Comment by pawlakm** [comment]
Note: I just installed chromium and get the same behavior as the one I get with firefox.

**Comment by bgrozev** [comment]
Can you post the XMPP logs from the browser (in the `ENABLE_AUTH=1`, `ENABLE_GUESTS=0` case)? You can grab them by executing `APP.conference.saveLogs()` in the javascript console.

**Comment by pawlakm** [comment]
Sure, when do you want me to execute this command ? And what do you want me to do then ?

When I execute `APP.conference.saveLogs()` in the JS console on my Jitsi Meet homepage (the one with the textbox where I can enter the room name) I get the following error:

```
Uncaught TypeError: APP.connection is undefined
    saveLogs conference.js:1333
    <anonymous> debugger eval code:1
```
If I enter a room name (testroom) a login window appears. If I enter the command at this time (prior to entering the credentials) I get the same `TypeError` as above.

If I enter my credentials then type the command I get the following result.

```
undefined 
```

Then nothing special happens, just keep alive messages : 

```
2022-06-30T07:43:03.144Z [modules/xmpp/XmppConnection.js] <_maybeStartWSKeepAlive>:  Scheduling next WebSocket keep-alive in 74743.49153429462ms [Logger.js:154:22](webpack://JitsiMeetJS/node_modules/@jitsi/logger/lib/Logger.js)
2022-06-30T07:44:17.903Z [modules/xmpp/XmppConnection.js] <_maybeStartWSKeepAlive>:  Scheduling next WebSocket keep-alive in 110975.27714878121ms [Logger.js:154:22](webpack://JitsiMeetJS/node_modules/@jitsi/logger/lib/Logger.js)
```

**Comment by pawlakm** [comment]
I checked the source code of jicofo.conf and see the following:

```
    {{ if $ENABLE_AUTH }}
    authentication {
      enabled = true
      // The type of authentication. Supported values are XMPP, JWT or SHIBBOLETH (default).
      {{ if eq $AUTH_TYPE "jwt" }}
      type = JWT
      {{ else if eq $AUTH_TYPE "shibboleth" }}
      type = SHIBBOLETH
      {{ else }}
      type = XMPP
      {{ end }}
      {{ if eq $AUTH_TYPE "shibboleth" }}
      login-url = "shibboleth:default"
      logout-url = "shibboleth:default"
      {{ else }}
      login-url = "{{ $XMPP_DOMAIN }}"
      {{ end }}
      enable-auto-login={{ $ENABLE_AUTO_LOGIN }}
    }
```
It seems that `internal` `AUTH_TYPE` is not handled. Could it be the root cause ?

**Comment by bgrozev** [comment]
> The content of the downloaded file is then the following:

So it authenticates successfully, but it never sends the `<conference` IQ to jicofo. I don't know why this could be.

**Comment by pawlakm** [comment]
What can I do on my side to help you help me ?
Could you reproduce this behavior ?

**Comment by saghul** [comment]
I will try to repro.

**Comment by pawlakm** [comment]
I did some tests and here is what I observe. Maybe it can help you.

If `ENABLE_AUTH` and `ENABLE_GUESTS` are both set to `1`, when I try to join a room, I have to manually click on the "Join meeting" blue button (left side menu where I have to input a nickname). After I click on this button, a div appears and asks me if I'm the host. Starting from this point in time I see in server logs the following line:

```
jitsi-jicofo-1   | Jicofo 2022-07-01 01:08:23.731 INFO: [39] ConferenceIqHandler.handleConferenceIq#63: Focus request for room: testroom@muc.meet.jitsi
```

This line continues to be logged every second until I click on `cancel` or until I login. If I login successfully, then I have the jicofo logs stating that I joined the room:

```
jitsi-jicofo-1   | Jicofo 2022-07-01 01:18:58.161 INFO: [37] AbstractAuthAuthority.authenticateJidWithSession#431: Authenticated jid: gdyhxnyn41lsqqauo8eghr7v@guest.meet.jitsi/95Stej_4_P9J with session: AuthSession[ID=testuser@meet.jitsi, JID=gdyhxnyn41lsqqauo8eghr7v@guest.meet.jitsi/95Stej_4_P9J, SID=b0043c9c-ea88-40f3-a7cf-ea66ea2ff3b6, MUID=55c36a1d0918aaf7c43bc0f0352d369c, LIFE_TM_SEC=0, R=testroom@muc.meet.jitsi]@2135559005
jitsi-jicofo-1   | Jicofo 2022-07-01 01:18:58.161 INFO: [37] AbstractAuthAuthority.notifyUserAuthenticated#339: Jid gdyhxnyn41lsqqauo8eghr7v@guest.meet.jitsi/95Stej_4_P9J authenticated as: testuser@meet.jitsi
jitsi-jicofo-1   | Jicofo 2022-07-01 01:18:58.230 INFO: [31] [room=testroom@muc.meet.jitsi meeting_id=91ddda91-13a2-4089-95c5-f7b7eb78e70f] JitsiMeetConferenceImpl.onMemberJoined#589: Member joined:fc59c34f stats-id=Fredrick-zKg region=null audioMuted=true videoMuted=true isJibri=false isJigasi=false
```

However, when I set `ENABLE_GUESTS` to `0` the main difference is that when I join a room, I don't have to click on the blue button (which triggers the "Focus request for room"). The form with the blue button is displayed then the login form is quickly displayed. At this time, and unlike when `ENABLE_GUESTS` is set to `1`, there is no logs stating that jicofo has a focus request for the conference room.

Maybe I'm wrong but when `ENABLE_GUESTS` is set to `0` the react event requesting the focus is not sent. 

Maybe you can check this ?

**Comment by pawlakm** [comment]
Update: I just checked with `ldap` instead of `internal` auth and the issue is exactly the same.
As a result I'm changing the title of the issue.

**Comment by saghul** [comment]
I could repro. I know what's going on.

To fix some other issue we made the prejoin page hide when the login dialogs are displayed. That works ok for guest connections (the XMPP connection is done in the background, while in the prejoin screen) but when guests are disabled the connection itself cannot be created and the auth dialog is shown, then we are dropped in the meeting view, but there is no meeting created, that's why it looks like you are always alone. You never even joined the meeting!

Ping @damencho. Not sure we can patch this before The Grand Auth Refactor.

**Comment by pawlakm** [comment]
Thank you for having confirmed that there is a problem. I hope that it will be fixable easily. Tell me if I can be of any help.
BTW, may I know what the "grand auth refactor" is about and for when it is planned ?

**Comment by saghul** [comment]
The "grand auth refactor" is a grandiose sounding name I'm giving to a refactor effort :-)

More details here: https://community.jitsi.org/t/intent-to-deprecate-and-remove-external-auth-mechanisms/115332?u=saghul

It will not happen immediately, but soon.

**Comment by saghul** [comment]
I fixed it in https://github.com/jitsi/jitsi-meet/pull/11787 you can test it in tomorrow's unstable images.

**Comment by pawlakm** [comment]
Oh great thanks a lots!

**Comment by pawlakm** [comment]
Ok I tested it and it works. Thanks again!
