### ISSUE TITLE
Prosody tries to open IPV6 ports even if `ENABLE_IPV6=0` is set

### ISSUE THREAD

**Issue by pawlakm** [jitsi/docker-jitsi-meet#1337]
In `.env` I have set `ENABLE_IPV6=0`. However I see in the logs the following info/errors.

```
jitsi-prosody-1  | portmanager                            error	Failed to open server port 5222 on ::, Address family not supported by protocol
jitsi-prosody-1  | portmanager                            info	Activated service 'c2s' on [*]:5222
jitsi-prosody-1  | portmanager                                                  error	Failed to open server port 5280 on ::, Address family not supported by protocol
```

**Comment by pawlakm** [comment]
I guess that the culprit line is [the following one](https://github.com/jitsi/docker-jitsi-meet/blob/be8c41f79eabcacf03047dfec2f2998077b701aa/prosody/rootfs/defaults/prosody.cfg.lua#L183). 

And the answer is in [prosody documentation](https://prosody.im/doc/ports).

So yes, I can write a PR.

**Comment by saghul** [comment]
Please go ahead!
