### ISSUE TITLE
Add configuration for persistent log files

### ISSUE THREAD

**Issue by atfrase** [jitsi/docker-jitsi-meet#1340]
As far as I can tell, Jibri is the only component whose logs can be placed on a persistent mounted volume via `JIBRI_LOGS_DIR`. Some containers may log to files inside the container but whose paths cannot be configured, while others (such as prosody) explicitly only log to console, so even adding a mounted host volume to i.e. `/var/log/prosody` doesn't work, no logs are written there.

`docker compose logs` is fine in some cases, but it would be really nice to have the option to configure `PROSODY_LOGS_DIR`, `JICOFO_LOGS_DIR`, etc so that the log files can be easily accessed from the host (for i.e. automatic archival, real-time analysis and monitoring, etc).

**Comment by atfrase** [comment]
Actually, on further inspection, I don't think `JIBRI_LOGS_DIR` even works; only `JIBRI_RECORDING_DIR` seems to be respected. But it seems like it should be easy enough to fix that in `jibri/rootfs/etc/cont-init.d/10-config`.

**Comment by saghul** [comment]
Generally speaking, the "container native" (I can't believe I'm typing this) seems to be to log to stdout.

That's what all our containers do, except when not possible because there are multiple moving parts, as is the case of Jibri.

You can configure Docker to divert logs to an external syslog server for example.

**Comment by pawlakm** [comment]
@atfrase I agree that it would be easier to have an easy way to access the log files (I also asked for this in another issue). That being said it (for now) not the case. 

However, you have multiple means to access logs as files when the container is detached:

1. run `docker-compose logs -t -f <service_name> > logs/<service_name>.log &`
- > You only need to know the service name
- > No specific rights are required
- > The output is readable 
- > You need to do it for each service and re-run it every time you start your container
- > It will create a new log file 
2. run `container_id=$(docker ps --no-trunc -aqf "name=^<container-name>") && sudo tail -f /var/lib/docker/containers/$container_id/$container_id-json.log
- > You need to know the container name
- > You need to have sudo rights
- > The output is in json format (you can change it per service or system-wide
- > There are timestamps
- > You need to do it for each container and re-run it every time you start your container
- > No log files are created, you read the content of the existing log file
3. If you have other means to read the logs change the logging driver to whatever else you need (local, json-file, splunk, syslog, etc...)
