### ISSUE TITLE
Question about how you want me to document custom SSL certificate/key usage

### ISSUE THREAD

**Issue by pawlakm** [jitsi/docker-jitsi-meet#1341]
Currently it is not expicit how to make Nginx use an existing SSL certificate/key. As far as I know it is not documented anywhere and people have to look in the code to find the mount point for custom SSL key and certificate chain or search in past issues. 

I plan to write a PR to document this, but prior to doing it, I would like to know if you want me to only modify the `README.md` file or if it's fine for you if I also provide an example configuration as a comment in `docker-compose.yml`.

What is your preference ?

**Comment by saghul** [comment]
Thanks for volunteering!

The handbook should be the si file source of truth.

I'd say adding an extra section in the same level as let's encrypt would make sense.

**Comment by pawlakm** [comment]
PR [created](https://github.com/jitsi/handbook/pull/338#issue-1291378453)

**Comment by saghul** [comment]
Landed!
