### ISSUE TITLE
add fail2ban to web image to auto-ban IPs scanning for known vulnerabilities

### ISSUE THREAD

**Issue by atfrase** [jitsi/docker-jitsi-meet#1347]
In my `jitsi-web` logs I see tons of requests for things like:

```
GET /wp-login.php HTTP/1.1
GET /wordpress/wp-login.php HTTP/1.1
GET /blog/wp-login.php HTTP/1.1
GET /wp/wp-login.php HTTP/1.1
GET ///remote/fgt_lang?lang=/../../../..//////////dev/ HTTP/1.1
GET /actuator/gateway/routes HTTP/1.1
GET /config/getuser?index=0 HTTP/1.1
```

which are clearly automated vulnerability scans and not legitimate user traffic. It would be great if the image included an option to enable something like fail2ban to detect and block these things.

**Comment by saghul** [comment]
I don't want to have that on our base image. Different users may want to integrate different applications and there just isn't a one size fits all here. You can just proxy the web traffic from another container / VM which has fail2ban.
