### ISSUE TITLE
relayId coming as 0.0.0.0 from after stable-7287-2 jvb images

### ISSUE THREAD

**Issue by shuhaib3** [jitsi/docker-jitsi-meet#1349]
Hi @saghul ,

After jvb release 7287-2 ie,  in stable-7439 and stable-7439-2. the relayid shown in jicofo logs is as 0.0.0.0.
![image](https://user-images.githubusercontent.com/57085593/180489451-b64d75df-a0d5-4fbf-be59-dbc85e580891.png)
I think the relay id is being picked up from here in the last two releases.
when I change the bind address the relay id in jicofo is changing.
Any way to change the relayid to JVB_OCTO_PUBLIC_ADDRESS?

**Comment by saghul** [comment]
I honestly have no idea :-/ @bgrozev can you enlighten us here?

**Comment by shuhaib3** [comment]
@bgrozev is this might be the issue 
https://github.com/jitsi/jitsi-videobridge/commit/26085c6fa0f16de558e2b66f3a82603dcde7b62b

**Comment by shuhaib3** [comment]
@bgrozev even if relayid is there it is getting a fallback to bind address

**Comment by bgrozev** [comment]
Sorry, I'm not sure what breaks, but it's best to simply update to the latest config scheme. Something like:
```
{{ if $ENABLE_OCTO -}}
relay {
  enabled = true
  relay-id="<RELAY-ID>"
  region = "{{ .Env.JVB_OCTO_REGION | default "europe" }}"
}
{{ end -}}
```

I'm not sure what the best way to set the ID in a docker setup is. It just needs to be unique in the set of jvb's connected to jicofo. Taking $JVB_MUC_NICKNAME might work, or whatever was used to set bind-address.

We can get rid of .Env.JVB_OCTO_BIND_ADDRESS, .Env.JVB_OCTO_PUBLIC_ADDRESS, and .Env.JVB_OCTO_BIND_PORT.

**Comment by shuhaib3** [comment]
![image](https://user-images.githubusercontent.com/57085593/180590937-b3b1c4d2-3be6-41cb-a4c5-83a0efc1ae57.png)
ok, but here what is happening is that in last two releases the bind address is taken as relayid. hence the default value is 0.0.0.0 it is not getting unique.  previously it used to take the relay id from public-address = "{{ .Env.JVB_OCTO_PUBLIC_ADDRESS }}"
@saghul do we need a change here
https://github.com/jitsi/docker-jitsi-meet/blob/master/jvb/rootfs/defaults/jvb.conf

**Comment by saghul** [comment]
> Sorry, I'm not sure what breaks, but it's best to simply update to the latest config scheme. Something like:
> 
> ```
> 
> {{ if $ENABLE_OCTO -}}
> 
> relay {
> 
>   enabled = true
> 
>   relay-id="<RELAY-ID>"
> 
>   region = "{{ .Env.JVB_OCTO_REGION | default "europe" }}"
> 
> }
> 
> {{ end -}}
> 
> ```
> 
> 
> 
> I'm not sure what the best way to set the ID in a docker setup is. It just needs to be unique in the set of jvb's connected to jicofo. Taking $JVB_MUC_NICKNAME might work, or whatever was used to set bind-address.
> 
> 
> 
> We can get rid of .Env.JVB_OCTO_BIND_ADDRESS, .Env.JVB_OCTO_PUBLIC_ADDRESS, and .Env.JVB_OCTO_BIND_PORT.
> 
>         

Thanks I'll update the config!

**Comment by saghul** [comment]
Continues on https://github.com/jitsi/docker-jitsi-meet/pull/1371

**Comment by shuhaib3** [comment]
@saghul relay id is still coming as 0.0.0.0 in latest jitsi/jvb:stable-7648-4 image
 version=2.2.22-g42bc1b99, relayId=0.0.0.0, region=europe, stress=0.01] with stress=0.01358 for participantRegion=ap-south-1

**Comment by saghul** [comment]
Did you set JVB_OCTO_RELAY_ID ?

**Comment by yoerayo** [comment]
@shuhaib3 @saghul I don't believe these changes are included in any releases yet, I had to manually apply them for my deployment.

**Comment by saghul** [comment]
Right, my bad! I just noticed the PR is not merged, I'll do that now.
