### ISSUE TITLE
Jitsi customization

### ISSUE THREAD

**Issue by talesam** [jitsi/docker-jitsi-meet#1354]
I'm wanting to make some customizations in the system interface, but I'm not finding where are the images that appear when the system is accessed, could someone help me?

I found persistent configuration files and inside the web directory a file called "interface_config.js" that presents paths to images that I couldn't find anywhere, like here:

```
    DEFAULT_BACKGROUND: '#040404',
    DEFAULT_LOGO_URL: 'images/watermark.svg',
    DEFAULT_WELCOME_PAGE_LOGO_URL: 'images/watermark.svg',
```

Where are the HTML and CSS files?

I want to mount to have access to this, which container is it in?

```
/var/lib/docker/overlay2/34c346a39c9df834da19dfbd9dbffb4b24cad765493b36739c625cccd8ab4131/merged/usr/share/jitsi-meet
````

**Comment by saghul** [comment]
They are in the web image's `/usr/share/jitsi-meet` directory.
