### ISSUE TITLE
SIP integration (jigasi) broken with version 7577

### ISSUE THREAD

**Issue by tom666-debug** [jitsi/docker-jitsi-meet#1357]
Hi,

Seems that the SIP intgeration with version stable-7577 is broken and is no longer working for me (again).
On version stable-7439-2 everything still works as expected, means I am able to add participants via the SIP gateway.

When I try to add participants now via the Jitsi Web-Frontend eveything looks and behave okay but in fact the dial out will not be initiated and the GUI stays with the message "Initiating Call".

The last time I had an issue with Jigasi the root cause was quite obvisous and it was fixed almost instantly (thx to [saghul](https://github.com/saghul)): https://github.com/jitsi/docker-jitsi-meet/issues/1334

Here's a log-file from a fresh installation including one attempt to add participants via the SIP gateway:
[_jitsi_jigasi_1_logs.txt](https://github.com/jitsi/docker-jitsi-meet/files/9274957/_jitsi_jigasi_1_logs.txt)

Docker containers were created with the latest versions of the compose and .env files.

Any hint how to solve or further troubleshoot this, would be much appreciated.

**Comment by damencho** [comment]
I think this is a jigasi issue with g722, I haven't had time yet to investigate it. If you change codecs it will work.

**Comment by tom666-debug** [comment]
Thx for having a look and your reply!
It seems that the codecs can not be set from outside the container (.env file), so therefore I'll rather wait for the fix.

**Comment by saghul** [comment]
You can use a custom-sip-communicator.properties file to add stuff to the default config.

**Comment by tom666-debug** [comment]
Sorry for my ignorance, but add what to a custom-sip-communicator.properties file? 
Is there any documentation/information avilable regarding to this topic?

**Comment by saghul** [comment]
It's a bit of an obscure feature 😅 

You can add a file with that name in .jitsi-meet-cfg/jigasi/ and it will be picked up by the container.

**Comment by saghul** [comment]
This -1 release was just for JWT auth.

I'm not sure what needs to be fixed TBH. @damencho would disabling G722 be a decent stopgap?

**Comment by damencho** [comment]
Yep, it will fallback to the other codecs if available...

**Comment by saghul** [comment]
Just setting a zero here? https://github.com/jitsi/docker-jitsi-meet/blob/e811d7b2e1e57ece586bdd4e939f2932be58322f/jigasi/rootfs/defaults/sip-communicator.properties#L53

**Comment by tom666-debug** [comment]
As adviced I have now created a custom-sip-communicator.properties file and added this line to it:
`net.java.sip.communicator.impl.protocol.sip.acc1.Encodings.G722/8000=0`

 I can confirm that this workaround is working (at least for me)

**Comment by saghul** [comment]
Excellent!
