### ISSUE TITLE
Please keep images on Docker Hub up to date

### ISSUE THREAD

**Issue by mingfang** [jitsi/docker-jitsi-meet#136]
The current images are very old.

**Comment by saghul** [comment]
We make releases synced with Jitsi Meet stable releases. We have released a new stable version today, so expect an update soon.

**Comment by sapkra** [comment]
@saghul Maybe the jitsi team should think about releasing Jitsi Meet more frequently. What do you think?

**Comment by saghul** [comment]
We are actively working on streamlining our release process, so expect faster updates!
