### ISSUE TITLE
Custom Configs are not considered

### ISSUE THREAD

**Issue by Kompromittiert93** [jitsi/docker-jitsi-meet#1363]
Example:

custom-interface_config.js:
RECENT_LIST_ENABLED=false
GENERATE_ROOMNAMES_ON_WELCOME_PAGE=false

interface_config.js;
**};**

/* eslint-enable no-unused-vars, no-var, max-len */
RECENT_LIST_ENABLED=false
GENERATE_ROOMNAMES_ON_WELCOME_PAGE=false
<EOF>

The problem is, that the paste from the custom conf will be placed EOF but outside the var "interfaceConfig"

**Comment by saghul** [comment]
you need to do `interfaceConfig.RECENT_LIST_ENABLED = false;` and so on. That is, set them on the object that was created.

**Comment by Kompromittiert93** [comment]
Done, but nothing changed. The Option will no longer paste to the end of the file, but the boolean won't be changed.

**Comment by saghul** [comment]
Can you please check the generated file and paste it here?

**Comment by Kompromittiert93** [comment]
Found the issue, I thought the custom config needs to be placed in the config root, not besides the orig config. Thanks!
