### ISSUE TITLE
possible Regression since stable-7439 when using jwt authentication

### ISSUE THREAD

**Issue by msfp-ggmbh** [jitsi/docker-jitsi-meet#1369]
We have been using a docker-based (using docker-compose as provided and described in the handbook tweaked to use traefik as reverse proxy) setup for about 2.5 years and used jwt-authentication with RocketChat and jitsi-admin. Worked like a charm till after the summer break we tried to upgrade to the latest stable release 7648.
No matter if we use RocketChat or Jitsi-Admin to lunch a call we are always presented with an authentication error ("e.g. you are not allowed to be here"). 
Since the setup had been in use for a while i decided to start from scratch however the problem persisted. I tried to narrow it down, and apparently the problem regarding jwt-auth was introduced in 7577. Anybody else facing similar problems?

**Comment by damencho** [comment]
Is this the case that you are mixing guest virtualhost and jwt.

**Comment by msfp-ggmbh** [comment]
> Is this the case that you are mixing guest virtualhost and jwt?

I did not touch anything beyond the .env and the docker-compose (adding labels for traefik to pick it up). I have attached the files
[env.txt](https://github.com/jitsi/docker-jitsi-meet/files/9351477/env.txt)
[docker-compose.yml.txt](https://github.com/jitsi/docker-jitsi-meet/files/9351484/docker-compose.yml.txt)
 Thus all the config files are generated from scratch when running docker-compose up afaik. I have no custom config files in use.

**Comment by damencho** [comment]
Yep,

```
# Enable guest access
ENABLE_GUESTS=1

# Select authentication type: internal, jwt, ldap or matrix
AUTH_TYPE=jwt
```

This combination has never been supported and tested, and the fact that it worked was luck. We will be refactoring authenticaton flow soon and will take in mind this usecase. More info at https://community.jitsi.org/t/intent-to-deprecate-and-remove-external-auth-mechanisms/115332

**Comment by msfp-ggmbh** [comment]
> Yep,
> 
> ```
> # Enable guest access
> ENABLE_GUESTS=1
> 
> # Select authentication type: internal, jwt, ldap or matrix
> AUTH_TYPE=jwt
> ```
> 
> This combination has never been supported and tested, and the fact that it worked was luck. We will be refactoring authenticaton flow soon and will take in mind this usecase. More info at https://community.jitsi.org/t/intent-to-deprecate-and-remove-external-auth-mechanisms/115332

I missed that! I understand your need to clean up the code. I'll stick to the last working release as long as there are no security related issued solved in the newer releases. 
As you mentioned the combination was not intentionally working. The right way to use jwt and have external users join meetings opened by someone authorized without a token woul be to disable guests and allow empty tokens?

Thank you for your efforts and quick response!
Alexander

**Comment by damencho** [comment]
> The right way to use jwt and have external users join meetings opened by someone authorized without a token woul be to disable guests and allow empty tokens?

Currently, there is no such thing as `meetings opened by someone authorized`, the first one to join guest or not is creating the meeting.

**Comment by chaosbiber** [comment]
Unsure about the jwt/guest issue, but @msfp-ggmbh regarding the "you are not allowed to be here" window or `not allowed to join` prosody error:
I had success with disabling `JWT_ENABLE_DOMAIN_VERIFICATION` (=false) in .env, while enabling that variable in docker-compose.yml (https://github.com/jitsi/docker-jitsi-meet/pull/1396). Restart with a current version and it should work again. In stable-7648 the configurable `enable_domain_verification` var was added but I couldn't disable the verification until adding it to the compose yml.

Still don't know what the actual verification problem is, the JWT's `sub` is set to my jitsi domain , but maybe we would have to set the "internal" domains that remain (auth/muc etc).meet.jitsi in the docker default configuration?

**Comment by msfp-ggmbh** [comment]
I tried your suggestion with the latest release and it worked. Thank you @chaosbiber!
> Unsure about the jwt/guest issue, but @msfp-ggmbh regarding the "you are not allowed to be here" window or `not allowed to join` prosody error: I had success with disabling `JWT_ENABLE_DOMAIN_VERIFICATION` (=false) in .env, while enabling that variable in docker-compose.yml (#1396). Restart with a current version and it should work again. In stable-7648 the configurable `enable_domain_verification` var was added but I couldn't disable the verification until adding it to the compose yml.
> 
> Still don't know what the actual verification problem is, the JWT's `sub` is set to my jitsi domain , but maybe we would have to set the "internal" domains that remain (auth/muc etc).meet.jitsi in the docker default configuration?
