### ISSUE TITLE
Rename DOCKER_HOST_ADDRESS to NAT_HARVESTER_PUBLIC_ADDRESS

### ISSUE THREAD

**Issue by mingfang** [jitsi/docker-jitsi-meet#137]
There's not need to have two different names for the same thing.
It's confusing at minimum and it's wrong when running behind NAT.

**Comment by saghul** [comment]
This is explained in the README. Care to elaborate what's confusing about it? 

Also, it's not wrong when running behind NAT if LAN-only communication is desired.

**Comment by mingfang** [comment]
https://github.com/jitsi/docker-jitsi-meet/blob/e1bd2447ae4f5e90e0acea9bf95e23b1960f70e9/jvb/rootfs/etc/services.d/jvb/run#L7
DOCKER_HOST_ADDRESS is used as NAT_HARVESTER_PUBLIC_ADDRESS and nothing else.
Then why not just call it NAT_HARVESTER_PUBLIC_ADDRESS?
Also it is wrong when behind NAT.

**Comment by saghul** [comment]
> DOCKER_HOST_ADDRESS is used as NAT_HARVESTER_PUBLIC_ADDRESS and nothing else.

I know, I wrote the code.

> All the documentation elsewhere talks about NAT_HARVESTER_PUBLIC_ADDRESS and only when people start using the project they learn about DOCKER_HOST_ADDRESS only to later find out they are the same. Confusing.

The Docker setup generates the config for all the projects, none of the variables used here exist really. The point was to abstract the user from needing to set ice4j options themselves.



> Also it is wrong when behind NAT.

Again, not it's not. If you have an internal installation which must work only in a private network you need this. Try to run this setup in Docker for Mac and you'll see why.

**Comment by mingfang** [comment]
Time to abandon ship and write my own Dockerfile.
This
