### ISSUE TITLE
After update to stable-7648 video broken

### ISSUE THREAD

**Issue by mungo312** [jitsi/docker-jitsi-meet#1370]
Hi,

after updating to stable-7648 we only get audio. Video is only working in P2P mode. 
Same problem occurs in unstable-2022-08-16. 
I do not know exactly what logs would be helpful as there a no obvious errors in the client or server logs.
What logs should I provide ?

**Comment by saghul** [comment]
`unstable-2022-08-17` is building now. Can you please give it a try?

**Comment by mungo312** [comment]
Same problem as before. 
For some time the video is black, then the speaker icon is displayed.

**Comment by dbrifox** [comment]
Having the same issue

**Comment by saghul** [comment]
Can you please share the browser console and JVB logs?

**Comment by DDG-MG** [comment]
I can confirm the behaviour,
I've swithced to stable-7577 and everything ran ok.

Unfortunately due to schedule constraints I cannot switch back to the latest to retrieve the logs.

**Comment by mbw83** [comment]
Seems to be similar to https://github.com/jitsi/jitsi-meet/issues/12026
For me enabling multistream solved the problem. See here: https://github.com/jitsi/jitsi-meet/issues/12026#issuecomment-1218838817

**Comment by mungo312** [comment]
That realy seams to fix the problem. After adding `ENABLE_MULTI_STREAM=1` to the `.env`, everything is working fine. Thanks for the hint @mbw83 .

**Comment by saghul** [comment]
Hum, latest stable has it enabled already... or did I make a mistake doing it?!

**Comment by saghul** [comment]
Shit I did. Multi stream defaults to on for the web container but off for the JVB. 🤦‍♀️ I'll do a fixup release.

**Comment by saghul** [comment]
I've pushed a fix to master, and re-triggered an unstable build, it's in progress.

**Comment by saghul** [comment]
Should be fixed in https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-7648-1
