### ISSUE TITLE
~/.jitsi-meet-cfg/web/nginx/meet.conf is empty on clean install 7648-2: release

### ISSUE THREAD

**Issue by kundulun** [jitsi/docker-jitsi-meet#1381]
~/.jitsi-meet-cfg/web/nginx/meet.conf is 0 bytes when on clean install 7648-2: release

**Comment by damencho** [comment]
That has been fixed in master and will come soon as -3 release.
https://github.com/jitsi/docker-jitsi-meet/commit/a2b86a0f9a7f9508c60ec5127e39c50943ea12ef
