### ISSUE TITLE
Free WebRTC TURN Server from metered.ca failed

### ISSUE THREAD

**Issue by ralfi** [jitsi/docker-jitsi-meet#1386]
Hi,

found this `https://www.metered.ca/tools/openrelay/` and try to use this service for the JVB. 

For TCP support (UDP is not allowed) DocJitMee not recognized the setting, e.g. `staticauth .... : 443?transport=tcp`
How do i setup the VARs to use this TURN server?

Thanks in advance

**Comment by saghul** [comment]
Set TURN_HOST to the hostname, it defaults to the TCP transport. Then TURN_PORT to 443 as I see there. And TURN_CREDENTIALS to the necessary credentials.

**Comment by ralfi** [comment]
Hi @saghul 

do not work with tcp, all logs tell me that udp is used ...

![ksnip_20220829-130809](https://user-images.githubusercontent.com/294423/187188090-cfec94b2-f07d-4848-b818-8133f436ce12.png)

**Comment by saghul** [comment]
How does your generated prosody config file look like?

**Comment by ralfi** [comment]
![ksnip_20220829-140809](https://user-images.githubusercontent.com/294423/187197654-d7eb54a6-1048-4cac-aca6-bb74930e63e0.png)

Seems to be okay.

Could be related to outgoing deep packet inspection firewall on port 443.
Few month's ago a set up a little vserver at hetzer with coturn and everything works as expected. The diff is that this vserver has a certbot https cert apache (not standalone cert mode) and i set the coturn listen ports to 443 for unencrypted and encrypted TURN traffic.

**Comment by ralfi** [comment]
But - independent from this - the JVB logs contains not tcp connection entries... Mmmmh

**Comment by saghul** [comment]
Any chance you used the wrong credential and thus failed to authenticate with those servers? Check `chrome://webrtc-internals` to see what ICE servers are in use.

**Comment by ralfi** [comment]
Yes, these ...

`ickkonf, { iceServers: [turn:staticauth.openrelay.metered.ca:80?transport=tcp, turns:staticauth.openrelay.metered.ca:443?transport=tcp], iceTransportPolicy: all, bundlePolicy: max-bundle, rtcpMuxPolicy: require, iceCandidatePoolSize: 0, sdpSemantics: "unified-plan", extmapAllowMixed: true }`

see also this

![ksnip_20220829-142702](https://user-images.githubusercontent.com/294423/187200854-e0f0bfe1-b62d-4518-a24a-a2055c6fe970.png)

and this

![ksnip_20220829-142716](https://user-images.githubusercontent.com/294423/187200931-f7ae4d0e-d27a-4ec9-a63f-2af4710615ea.png)

**Comment by damencho** [comment]
The certificates are expired, so it will not work. Make sure you have the full certificates chain and those are trusted certs.

**Comment by ralfi** [comment]
Hi @damencho sorry for stupid questions, which certs? For my own docker-jitsi-meet site? Or from metered.ca?

**Comment by damencho** [comment]
Those at the turnserver host staticauth.openrelay.metered.ca

**Comment by ralfi** [comment]
Thanks, but these are certs not from me...

**Comment by damencho** [comment]
🤷‍♂️ It will not work till those ceerts are fixed.

**Comment by ralfi** [comment]
Are there other TURN servers to compare?

**Comment by ralfi** [comment]
Now i send a mail and ask to fix it

**Comment by damencho** [comment]
I'm not aware of any free turnservers. If you install jitsi-meet from debian packages it comes with a turnserver listening on the standard ports for turns and stun and you need at least let's encrypt certs for it in order to work.

**Comment by ralfi** [comment]
Yes i know but i am behind of a restricted network which only allowed outgoing traffic on http or https. And as above i wrote i set up a little coturn vserver and this will work but i do not know if this knowledge or coincidence... And using this paid server only for some checks is a little bit overloaded.

**Comment by damencho** [comment]
There is a way to switch the standard ports of the turnserver to use port 443 is you want to run jitsi-meet on the same machine, you just need a second DNS. https://jitsi.github.io/handbook/docs/devops-guide/turn#use-turn-server-on-port-443



> And using this paid server only for some checks is a little bit overloaded.

What checks do you mean? 

A turnserver is used to relay traffic, it needs to be able to handle media and because media goes through it, it is expensive to host one. A turnserver is used for media to fall back to TCP when UDP is not available. And because it is expensive, that's why it is protected with short-lived credentials.

**Comment by ralfi** [comment]
of course your' right, i mean using webrtc apps behind firewalls for test environment

**Comment by bgrozev** [comment]
The turn server is used only by the jitsi-meet client, you shouldn't expect to see tcp connections on the bridge.

**Comment by ralfi** [comment]
Thanks @saghul and @damencho to explain this
