### ISSUE TITLE
Jitsi black screen on fresh install

### ISSUE THREAD

**Issue by Matt-CyberGuy** [jitsi/docker-jitsi-meet#1388]
Hey all,

It's been awhile since I setup a new jitsi server, I've been successful in the past, but for some reason I'm just striking out. I've recently spun up a new droplet on digital ocean running Ubuntu 22.04 and no matter how vanilla and to the T I do the install, I can't get Jitsi clients to talk to each other.

I even pulled the config and files from our previous server, spun everything up identical (same droplet FW rules as well) to our working setup and got the same result... black screen. So this tells me it's gotta be an OS thing. I thought maybe sound aloop? Nope. Our older server is running Ubuntu 21.10. Is this a known issue? 

I'm not even seeing standout errors in the logs that I've seen in the past when I was troubleshooting. What am I missing?

**Comment by saghul** [comment]
Are you using the docker setup?

**Comment by Matt-CyberGuy** [comment]
OK.. busy day w/ work.

So I tested this morning before work started and randomly it worked. But I soon discovered it would only work while my phone and laptop were on the same network. As soon as I disconnected from WiFi, the audio/video would no longer route.

**Comment by Matt-CyberGuy** [comment]
After studying the packets and logs in my firewall, it looks like both my firewall and the firewall at my office are blocking UDP 10000, which would explain why endpoints within the same network can connect to one another.

Hmmmm... anyone have any links/guides to changing the ports used by jitsi to be a little more firewall friendly?

We definitely ran into this issue with our old server and clients not being able to see/hear us on calls.

**Comment by saghul** [comment]
Depending on how the firewall is blocking things your only recourse might be to use a TURN server over TCP which is not great.

Do you know if all UDP is blocked or just certain ranges?

**Comment by Matt-CyberGuy** [comment]
I could see in my firewall logs udp 10000 was being blocked. How would I configure for UDP 443?

Also why is TURN over tcp not great?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Matt-CyberGuy** [comment]
Found it, going to try now

**Comment by saghul** [comment]
In general, media over TCP gives worse results due to things like congestion control. The real-time nature of it makes it a better fit for UDP.

**Comment by Matt-CyberGuy** [comment]
Makes sense....

Well, changing to UDP 443 worked... until I took my bypass rules off my firewall. Then all AV stopped between endpoints. Is this just a new server on the internet issue? Any ideas?

**Comment by saghul** [comment]
Sounds like a firewall issue still.

**Comment by Matt-CyberGuy** [comment]
Ya, I'm going to stand up an external turn server now to see if I can get around it. I can obviously fix this issue locally, but in production I wouldn't have any control over other people's firewalls

**Comment by Matt-CyberGuy** [comment]
Huh! So this is bizarre,

While trying to get this system running w/ an external turn server, I enabled the proxy'ing on cloudflare for the domain thinking the media streams would be handled externally by the turn server. While testing I got streaming on all of my devices, except for my phone in it's browser. 

Just to check and see how the turn server was handling things I checked logs and didn't see any traffic, so I decided to shut it down to see if was actually doing anything, and AMAZINGLY, the turn server isn't handling any of the streaming. 

From all of my previous attempts and research Jitsi shouldn't be able to function behind cloudflare's proxying. 

Also, anyone know any reason why my phone's browser can't stream when on cell signal, but the app can?

**Comment by Matt-CyberGuy** [comment]
Yes, followed the quick setup guide specifically.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by saghul** [comment]
Do you still have issues?

**Comment by Matt-CyberGuy** [comment]
Yes and no. If I expose the ip for our jitsi server directly, I get the black screen. No one can hear one another unless they're on the same network. I think I later figured out it was due to IPS/IDS.

For some reason, running Jitsi behind cloudflare seems to fix the issue. However, mobile devices seem to require the jitsi app to function.

If I trace traffic on firewalls, I can easily see traffic still going to port 8080 of the actual server IP, so I have no idea why using cloudflare makes a difference.

But at the end of the day, it's asking and I'm happy in general I'm able to put the server behind cloudflare's services.

**Comment by larafj** [comment]
I'm facing the same issue, but it must be due to my machine (QNAP nas) because I was able to successfully install jitsi on a VPS running Ubuntu without any issues. After checking the docker logs, I get this:

jitsi/web:stable

```
21 17:09:48 [error] 284#284: *9 open() "/config/config.js" failed (13: Permission denied), client: 192.168.1.22, server: _, request: "GET /favicon.ico HTTP/1.1", subrequest: "/config.js", host: "my.domain.com:8000", referrer: "http://my.domain.com:8000/"

2024/11/21 16:56:37 [error] 284#284: *2 open() "/config/interface_config.js" failed (13: Permission denied), client: 192.168.1.22, server: _, request: "GET / HTTP/2.0", subrequest: "/interface_config.js", host: "my.domain.com:8000"
```


jitsi/prosody:stable

```
Prosody was unable to find the configuration file.
We looked for: /etc/prosody//config/prosody.cfg.lua
```

jitsi/jvb:stable

```
JVB 2024-11-21 17:22:10.103 WARNING: [25] [hostname=xmpp.meet.jitsi id=shard0] MucClient.setPresenceExtensions#467: Cannot set presence extension: not connected.

JVB 2024-11-21 17:22:10.431 WARNING: [24] [hostname=xmpp.meet.jitsi id=shard0] MucClient.lambda$getConnectAndLoginCallable$9#640: Error connecting:

org.jivesoftware.smack.SmackException$EndpointConnectionException: The following addresses failed: 'RFC 6120 A/AAAA Endpoint + [xmpp.meet.jitsi:5222] (xmpp.meet.jitsi/172.29.4.2:5222)' failed because: java.net.ConnectException: Connection refused

	at org.jivesoftware.smack.SmackException$EndpointConnectionException.from(SmackException.java:334)
```

jitsi/jicofo:stable

```
Jicofo 2024-11-21 17:23:54.359 SEVERE: [18] [xmpp_connection=client] XmppProvider.doConnect#182: Failed to connect/login: The following addresses failed: 'RFC 6120 A/AAAA Endpoint + [xmpp.meet.jitsi:5222] (xmpp.meet.jitsi/172.29.4.2:5222)' failed because: java.net.ConnectException: Connection refused

org.jivesoftware.smack.SmackException$EndpointConnectionException: The following addresses failed: 'RFC 6120 A/AAAA Endpoint + [xmpp.meet.jitsi:5222] (xmpp.meet.jitsi/172.29.4.2:5222)' failed because: java.net.ConnectException: Connection refused

	at org.jivesoftware.smack.SmackException$EndpointConnectionException.from(SmackException.java:334)
```

If I check the source code of the black screen, it says: "JavaScript is disabled. For this site to work you have to enable JavaScript." But JS is not disabled on my web browser.

Any ideas? What could it be? Thanks!

**Comment by saghul** [comment]
Looks like the config volume has the wrong permissions.

**Comment by larafj** [comment]
Is that possible even if I copied the docker from the Ubuntu machine and then pasted it to the Qnap NAS?
`$ sudo tar -zvcf jitsi.tar.gz jitsi`
`$ sudo tar --same-owner -xzf jitsi.tar.gz`

**Comment by saghul** [comment]
Yes because the user IDs are likely different on both.

**Comment by larafj** [comment]
For a non-root user, they are different:
`uid=1000(usuario) gid=100(everyone) groups=0(administrators),100(everyone)`
`uid=1000(usuario) gid=1000(usuario) groups=1000(usuario),27(sudo),998(docker)`

But for a root user, they are very similiar if not identical:
`uid=0(admin) gid=0(administrators) groups=0(administrators),100(everyone)`
`uid=0(root) gid=0(root) groups=0(root)`

**Comment by larafj** [comment]
Well, it works if I use docker volumes instead of bind mounts. Not sure if this is inadvisable for any reason.

**Comment by saghul** [comment]
That should be fine!

**Comment by larafj** [comment]
Ok, thanks! It is working, although I get this warning, but as I said, it works.

`WARN[0000] mount of type `volume` should not define `bind` option`

**Comment by larafj** [comment]
I removed the "Z" flag from the volumes and no more warnings. It's working smoothly now.

**Comment by saghul** [comment]
Good to hear! TBH I don't remember what the Z flag does :-)

**Comment by larafj** [comment]
Apparently it only applies to bind mounts and it makes the content of the volume private. For Docker volumes, you must explicitly indicate whether you want to share them.
