### ISSUE TITLE
Endconference component not working.

### ISSUE THREAD

**Issue by debendraoli** [jitsi/docker-jitsi-meet#1389]
The last merged feature seems incomplete.

When I try to end the conference for all, there is no effect on room and following error is displayed on prosody logs.

`endconference.jitsi.meet:end_conference`                      `warn`    `No room found found for /roomName`

**Comment by saghul** [comment]
Are you using `unstable` ? Ping @wfleischer :-)

**Comment by debendraoli** [comment]
yes, Also I am getting same error with breakout room too. Perhaps something to do with subdomain enabled?

**Comment by saghul** [comment]
Maybe. Do you observe any problems if you don't use a subdomain?

**Comment by debendraoli** [comment]
I cannot join any meetings at all without any logs.

**Comment by debendraoli** [comment]
I cannot join any meetings at all. I guess it is not subdomain issue as it is there for months.

**Comment by wfleischer** [comment]
Hi @debendraoli. Thanks for reporting. End conference works well with the following plain setup:

```
git clone https://github.com/jitsi/docker-jitsi-meet
cd docker-jitsi-meet
cp env.example .env
./gen-passwords.sh  
docker-compose up -d
```

The log line you provided is from https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_end_conference.lua#L55. Obviously the `session.jitsi_web_query_room` and `session.jitsi_web_query_prefix` values are not populated accordingly. That also explains why breakout rooms are broken for you (compare https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_muc_breakout_rooms.lua#L259).

I tend to think that there is an issue with your configuration. Can you provide details that will allow us to duplicate?

**Comment by saghul** [comment]
We have no indication that it's broken. Please share your config and full logs.

**Comment by debendraoli** [comment]
Above logs is all I got, I manged to fix it by properly populating  `jitsi_web_query_prefix` with right subdomain.

**Comment by debendraoli** [comment]
`jitsi_web_query_prefix` value is empty so it cannot get room when subdomain is used.

It is expecting prefix from http request but its is not sent from jitsi web hence empty. 

https://github.com/jitsi/jitsi-meet/blob/6fe353cfa4774a7c52c14651b0bbefa7895d4bf5/resources/prosody-plugins/mod_jitsi_session.lua#L23

And in breakout or end conference module it is trying to get room using the prefix as subdomain but it is empty so the same error message I reported above.

https://github.com/jitsi/jitsi-meet/blob/6fe353cfa4774a7c52c14651b0bbefa7895d4bf5/resources/prosody-plugins/mod_muc_breakout_rooms.lua#L259

Maybe @damencho can put light on this.

**Comment by damencho** [comment]
The prefix url param that is used to populate that is coming from nginx config.
https://github.com/jitsi/jitsi-meet/blob/e8de9b4d66ea243273627c157eac97e4456b376e/doc/debian/jitsi-meet/jitsi-meet.example#L153
So probably your nginx config is missing that
