### ISSUE TITLE
Colibri throws error "ERR_CERT_COMMON_NAME_INVALID"

### ISSUE THREAD

**Issue by vskrish11** [jitsi/docker-jitsi-meet#1397]
We have set up Jitsi Meet on CentOS using docker container and it is listening to port 8414. 

Meet is working fine for video conference but we find this error frequently in the browser console log. Shouldn't the URL contain port 8445 as Meet is set up in docker-compose.yml to listen to that port ? Please let us know how to fix this issue.

WebSocket connection to 'wss://jitsi.Domainname.com/colibri-ws/172.26.0.5/ab8c9c61ad1a08c6/09a4c8d9?pwd=4j05cm7jhcv3p6nkt8us5u25cl' failed: Error in connection establishment: net::ERR_CERT_COMMON_NAME_INVALID

Screenshare is failing as of now with 3 or more participants, not sure if the above error has a relation.

**Comment by saghul** [comment]
What did you set for PUBLIC_URL ? Are you using a real certificate?

**Comment by vskrish11** [comment]
This is the public URL - 
PUBLIC_URL=https://jitsi.<Domainname>.com

Should I append the port number ?

**Comment by vskrish11** [comment]
I appended the port number to PUBLIC_URL in .env file and now that error is gone.
