### ISSUE TITLE
Jicofo needs more configuration options

### ISSUE THREAD

**Issue by gfriloux** [jitsi/docker-jitsi-meet#14]
Hello,

First : I am a total beginner with jitsi-meet.
I wanted to only allow room creation for authed users, and guest users to only be able to join existing rooms.

I found out that to achieve this, i had to add the following : `-Dorg.jitsi.jicofo.auth.URL=XMPP:$XMPP_DOMAIN`

otherwise it wouldn't work.
This means i had to patch the `run` script, rebuild the image, then run it, for this to work.

Is there a way to do this without having to rebuild the image ?
If not, could we have a patch for this ?

**Comment by saghul** [comment]
Hello! Yes, I have plans to add this. The way I think of it is with 2 flags: `ENABLE_AUTH` and `ALLOW_GUESTS`. With these 2, the Docker containers for web, jicofo and prosody would configure the needful.

I'm not sure when I'll get to it, so feel free to write a patch following the above guidelines and I'll be happy to review it.

**Comment by gfriloux** [comment]
This seems beyond my actual skills :/

**Comment by saghul** [comment]
@gfriloux I just updated the images with builtin authentication support. Please check the README for instructions.. Cheers!

**Comment by gfriloux** [comment]
Oh this is really nice!
Thx for the time and effort put into this!
