### ISSUE TITLE
There is no video or sound for meetings of more than two people

### ISSUE THREAD

**Issue by zhaoketong** [jitsi/docker-jitsi-meet#1407]
Please help me

![e64c5b9ad25a64559aedb0143c88cbc](https://user-images.githubusercontent.com/50908088/191883846-cb2a25a2-a34f-4c6c-a6dc-d2c885a445ea.jpg)

**Comment by saghul** [comment]
Did you configure the DOXKED_HOST_ADDRESS env var?

**Comment by zhaoketong** [comment]
yes, is 192.168.1.1

**Comment by saghul** [comment]
Is that the machine where the Docker setup is running? Please share your browser console logs.

**Comment by zhaoketong** [comment]
i think i got it   DOCKED_HOST_ADDRESS and PUBLIC_URL are same

**Comment by saghul** [comment]
For a test system in the local LAN yes.
