### ISSUE TITLE
Build failed on stable-7577-2

### ISSUE THREAD

**Issue by denis-ionov** [jitsi/docker-jitsi-meet#1410]
Docker build failed from stable-7577-2 since ~yesterday. Everything was fine about a week ago. Here are some details from the trace:
```
#0 137.7 Setting up jitsi-meet-prosody (1.0.6600-1) ...
#0 138.1 dpkg: error processing package jitsi-meet-prosody (--configure):
#0 138.1  installed jitsi-meet-prosody package post-installation script subprocess returned error exit status 10
#0 138.1 Processing triggers for libc-bin (2.31-13+deb11u3) ...
#0 138.1 Errors were encountered while processing:
#0 138.1  jitsi-meet-prosody
#0 138.2 E: Sub-process /usr/bin/dpkg returned an error code (1)
```
I noticed that [this](https://github.com/jitsi/docker-jitsi-meet/commit/dd95b3d29caef827c26923a4c5f102d19a038d14) commit fix the issue, but have no idea why prosody package installation was failed.

**Comment by saghul** [comment]
The commit explains it, we don't have a proper Debian package there. So we manually extract its contents. Yesterday's stable build is correct.
