### ISSUE TITLE
error: nettle random(yarrow) cannot initialize, getentropy failed: Function not implemented

### ISSUE THREAD

**Issue by dyfsd3** [jitsi/docker-jitsi-meet#1414]
error: nettle random(yarrow) cannot initialize, getentropy failed: Function not implemented

**Comment by dyfsd3** [comment]
docker logs prosody ：error: nettle random(yarrow) cannot initialize, getentropy failed: Function not implemented

**Comment by saghul** [comment]
Can you please paste the full log?

What image versions are you running?

**Comment by dyfsd3** [comment]
docker-jitsi-meet-stable-7439-2，prosody contains have so much core files  ，3q



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Saúl Ibarra ***@***.***> |
| Date | 10/08/2022 12:57 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [jitsi/docker-jitsi-meet] error: nettle random(yarrow) cannot initialize, getentropy failed: Function not implemented (Issue #1414) |

Can you please paste the full log?

What image versions are you running?

**Comment by saghul** [comment]
Please test the latest release and paste the full output, we can't help you otherwise.

**Comment by dyfsd3** [comment]
it is no problem to deploy in centos ，but i deploy it on red flag operating system and run on the intranet



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | Saúl Ibarra ***@***.***> |
| Date | 10/08/2022 15:16 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [jitsi/docker-jitsi-meet] error: nettle random(yarrow) cannot initialize, getentropy failed: Function not implemented (Issue #1414) |

Please test the latest release and paste the full output, we can't help you otherwise.

**Comment by dyfsd3** [comment]
it is no problem to deploy in centos ，but i deploy it on red flag operating system and run on the intranet



***@***.***
***@***.***



---- Replied Message ----
FromSaúl Ibarra ***@***.***>Date10/08/2022 ***@***.******@***.******@***.***>SubjectRe: [jitsi/docker-jitsi-meet] error: nettle random(yarrow) cannot initialize, getentropy failed: Function not implemented (Issue #1414)
Please test the latest release and paste the full output, we can't help you otherwise.

**Comment by saghul** [comment]
Looks like that día Teo might be running a too old kernel / glibc combo.

Nothing we can on our side to fix that, sorry.
