### ISSUE TITLE
Excaldraw-backend integration.

### ISSUE THREAD

**Issue by debendraoli** [jitsi/docker-jitsi-meet#1415]
Excalidraw is nice addition over Etherpad.

We tried etherpad but it has a lot of issues. Had to fork on our own, but still there are issue here and there.

We're looking forward to excalidraw which similar and nice alternative to google whiteboard.

I know it's still on testing, is there any chance of PR consideration so that it will expand the testing scope and speed up the later phase ?

Thanks.

**Comment by saghul** [comment]
Sure, a PR would help, and we can discuss specifics there.

**Comment by saghul** [comment]
https://github.com/jitsi/docker-jitsi-meet/commit/b4604f3078b0b7da5a9199e3974592d4d741bc35

**Comment by debendraoli** [comment]
nice to see the progress.
Handed over my jitsi integration ownership long ago.

Hope to get back in near future. :-)
