### ISSUE TITLE
Custom Config wont work: Uncaught ReferenceError: interfaceConfig is not defined

### ISSUE THREAD

**Issue by Kompromittiert93** [jitsi/docker-jitsi-meet#1416]
I placed in the config folder beside web/interface_config.js a new file with the name web/custom-interface_config.js inside the custom conf I put:
`interfaceConfig.DEFAULT_WELCOME_PAGE_LOGO_URL: 'images/watermark.png'`

But the Browserconsole says:
Uncaught ReferenceError: interfaceConfig is not defined

and the EOF of the interface_config.js looks like:

>...
>...
> };
> 
> /* eslint-enable no-unused-vars, no-var, max-len */
> interfaceConfig.DEFAULT_WELCOME_PAGE_LOGO_URL: 'images/watermark.png'

**Comment by saghul** [comment]
> interfaceConfig.DEFAULT_WELCOME_PAGE_LOGO_URL: 'images/watermark.png'

That's not correct JS. Do this:

`interfaceConfig.DEFAULT_WELCOME_PAGE_LOGO_URL = 'images/watermark.png';`

**Comment by filoucrackeur** [comment]
I have actually the same problem file is load but variable is not override :(

**Comment by filoucrackeur** [comment]
oh my god i understood my custom.js file override from my custom docker image sorry
