### ISSUE TITLE
i cant record video

### ISSUE THREAD

**Issue by mehrdadhaji** [jitsi/docker-jitsi-meet#1419]
i use version stable-7648-4
i setup docker on localhost and i dont have domain 
my .env value is default i only added this section
ENABLE_RECORDING=1

# XMPP domain for the jibri recorder
XMPP_RECORDER_DOMAIN=recorder.meet.jitsi

# XMPP recorder user for Jibri client connections
JIBRI_RECORDER_USER=recorder

# Directory for recordings inside Jibri container
JIBRI_RECORDING_DIR=/config/recordings

# XMPP user for Jibri client connections
JIBRI_XMPP_USER=jibri

# MUC name for the Jibri pool
JIBRI_BREWERY_MUC=jibribrewery

# MUC connection timeout
JIBRI_PENDING_TIMEOUT=90

JIBRI_STRIP_DOMAIN_JID=muc

JIBRI_LOGS_DIR=/config/logs

my jibri logs 
Jibri 2022-10-18 09:06:19.257 FINE: [20] WebhookClient$updateStatus$1.invokeSuspend#107: Updating 0 subscribers of status
Jibri 2022-10-18 09:06:25.349 FINE: [58] [hostname=xmpp.meet.jitsi id=xmpp.meet.jitsi] MucClient$3.handleIQRequest#503: Received an IQ with type set: IQ Stanza (jibri http://jitsi.org/protocol/jibri) [to=jibri@auth.meet.jitsi/XyYDwYnA76gx,from=jibribrewery@internal-muc.meet.jitsi/focus,id=amlicmlAYXV0aC5tZWV0LmppdHNpL1h5WUR3WW5BNzZneABaTVpESC01MQC2w/yTZmjGaQ==,type=set,]
Jibri 2022-10-18 09:06:25.350 INFO: [58] XmppApi.handleJibriIq#230: Received JibriIq <iq xmlns='jabber:client' to='jibri@auth.meet.jitsi/XyYDwYnA76gx' from='jibribrewery@internal-muc.meet.jitsi/focus' id='amlicmlAYXV0aC5tZWV0LmppdHNpL1h5WUR3WW5BNzZneABaTVpESC01MQC2w/yTZmjGaQ==' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' action='start' recording_mode='file' room='a@muc.meet.jitsi' session_id='ndinfjxlmvpurhul' app_data='{"file_recording_metadata":{"share":true}}'/></iq> from environment [MucClient id=xmpp.meet.jitsi hostname=xmpp.meet.jitsi]
Jibri 2022-10-18 09:06:25.350 INFO: [58] XmppApi.handleStartJibriIq#262: Received start request, starting service
Jibri 2022-10-18 09:06:25.366 INFO: [58] XmppApi.handleStartService#373: Parsed call url info: CallUrlInfo(baseUrl=https://meet.jitsi, callName=a, urlParams=[])
Jibri 2022-10-18 09:06:25.366 INFO: [58] JibriManager.startFileRecording#138: Starting a file recording with params: FileRecordingRequestParams(callParams=CallParams(callUrlInfo=CallUrlInfo(baseUrl=https://meet.jitsi, callName=a, urlParams=[]), email='', passcode=null, callStatsUsernameOverride=, displayName=), sessionId=ndinfjxlmvpurhul, callLoginParams=XmppCredentials(domain=recorder.meet.jitsi, port=null, username=recorder, password=*****))
Jibri 2022-10-18 09:06:25.367 FINE: [58] [session_id=ndinfjxlmvpurhul] FfmpegCapturer.<init>#88: Detected os as OS: LINUX
Jibri 2022-10-18 09:06:25.368 FINE: [58] MainKt$setupMetaconfigLogger$1.debug#232: ConfigSourceSupplier: Trying to retrieve key 'jibri.chrome.flags' from source 'config' as type kotlin.collections.List<kotlin.String>
Jibri 2022-10-18 09:06:25.370 FINE: [58] MainKt$setupMetaconfigLogger$1.debug#232: ConfigSourceSupplier: Successfully retrieved key 'jibri.chrome.flags' from source 'config' as type kotlin.collections.List<kotlin.String>
Starting ChromeDriver 104.0.5112.79 (3cf3e8c8a07d104b9e1260c910efb8f383285dc5-refs/branch-heads/5112@{#1307}) on port 14032
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
Jibri 2022-10-18 09:06:25.826 INFO: [58] org.openqa.selenium.remote.ProtocolHandshake.createSession: Detected dialect: OSS
Jibri 2022-10-18 09:06:25.833 FINE: [58] MainKt$setupMetaconfigLogger$1.debug#232: FallbackSupplier: checking for value via suppliers:
  LambdaSupplier: 'JibriConfig::recordingDirectory'
  ConfigSourceSupplier: key: 'jibri.recording.recordings-directory', type: 'kotlin.String', source: 'config'
Jibri 2022-10-18 09:06:25.833 FINE: [58] MainKt$setupMetaconfigLogger$1.debug#232: LambdaSupplier: Trying to retrieve value via JibriConfig::recordingDirectory
Jibri 2022-10-18 09:06:25.833 FINE: [58] MainKt$setupMetaconfigLogger$1.debug#232: FallbackSupplier: failed to find value via LambdaSupplier: 'JibriConfig::recordingDirectory': org.jitsi.metaconfig.ConfigException$UnableToRetrieve$Error: class java.lang.NullPointerException
Jibri 2022-10-18 09:06:25.833 FINE: [58] MainKt$setupMetaconfigLogger$1.debug#232: ConfigSourceSupplier: Trying to retrieve key 'jibri.recording.recordings-directory' from source 'config' as type kotlin.String
Jibri 2022-10-18 09:06:25.834 FINE: [58] MainKt$setupMetaconfigLogger$1.debug#232: ConfigSourceSupplier: Successfully retrieved key 'jibri.recording.recordings-directory' from source 'config' as type kotlin.String
Jibri 2022-10-18 09:06:25.834 FINE: [58] MainKt$setupMetaconfigLogger$1.debug#232: FallbackSupplier: value found via ConfigSourceSupplier: key: 'jibri.recording.recordings-directory', type: 'kotlin.String', source: 'config'
Jibri 2022-10-18 09:06:25.834 FINE: [58] MainKt$setupMetaconfigLogger$1.debug#232: FallbackSupplier: checking for value via suppliers:
  LambdaSupplier: 'JibriConfig::finalizeRecordingScriptPath'
  ConfigSourceSupplier: key: 'jibri.recording.finalize-script', type: 'kotlin.String', source: 'config'
Jibri 2022-10-18 09:06:25.834 FINE: [58] MainKt$setupMetaconfigLogger$1.debug#232: LambdaSupplier: Trying to retrieve value via JibriConfig::finalizeRecordingScriptPath
Jibri 2022-10-18 09:06:25.835 FINE: [58] MainKt$setupMetaconfigLogger$1.debug#232: FallbackSupplier: failed to find value via LambdaSupplier: 'JibriConfig::finalizeRecordingScriptPath': org.jitsi.metaconfig.ConfigException$UnableToRetrieve$Error: class java.lang.NullPointerException
Jibri 2022-10-18 09:06:25.835 FINE: [58] MainKt$setupMetaconfigLogger$1.debug#232: ConfigSourceSupplier: Trying to retrieve key 'jibri.recording.finalize-script' from source 'config' as type kotlin.String
Jibri 2022-10-18 09:06:25.835 FINE: [58] MainKt$setupMetaconfigLogger$1.debug#232: ConfigSourceSupplier: Successfully retrieved key 'jibri.recording.finalize-script' from source 'config' as type kotlin.String
Jibri 2022-10-18 09:06:25.835 FINE: [58] MainKt$setupMetaconfigLogger$1.debug#232: FallbackSupplier: value found via ConfigSourceSupplier: key: 'jibri.recording.finalize-script', type: 'kotlin.String', source: 'config'
Jibri 2022-10-18 09:06:25.836 INFO: [58] [session_id=ndinfjxlmvpurhul] FileRecordingJibriService.<init>#134: Writing recording to /config/recordings/ndinfjxlmvpurhul, finalize script path /config/finalize.sh
Jibri 2022-10-18 09:06:25.836 FINE: [58] JibriStatsDClient.incrementCounter#38: Incrementing statsd counter: start:recording
Jibri 2022-10-18 09:06:25.836 INFO: [58] JibriStatusManager$$special$$inlined$observable$1.afterChange#72: Busy status has changed: IDLE -> BUSY
Jibri 2022-10-18 09:06:25.836 FINE: [58] WebhookClient$updateStatus$1.invokeSuspend#107: Updating 0 subscribers of status
Jibri 2022-10-18 09:06:25.836 INFO: [58] XmppApi.updatePresence#203: Jibri reports its status is now JibriStatus(busyStatus=BUSY, health=OverallHealth(healthStatus=HEALTHY, details={})), publishing presence to connections
Jibri 2022-10-18 09:06:25.836 FINE: [58] MucClientManager.setPresenceExtension#160: Setting a presence extension: org.jitsi.xmpp.extensions.jibri.JibriStatusPacketExt@7f9287f7
Jibri 2022-10-18 09:06:25.837 FINE: [58] MucClientManager.saveExtension#185: Replacing presence extension: org.jitsi.xmpp.extensions.jibri.JibriStatusPacketExt@1ab6b825
Jibri 2022-10-18 09:06:25.837 INFO: [58] XmppApi.handleStartJibriIq#275: Sending 'pending' response to start IQ
Jibri 2022-10-18 09:06:25.845 INFO: [75] AbstractPageObject.visit#32: Visiting url https://meet.jitsi
Jibri 2022-10-18 09:06:25.866 FINE: [65] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse: Could not add a provider for element busy-status from namespace http://jitsi.org/protocol/jibri
Jibri 2022-10-18 09:06:25.868 FINE: [65] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse: Could not add a provider for element health-status from namespace http://jitsi.org/protocol/health
Jibri 2022-10-18 09:06:26.110 SEVERE: [75] [session_id=ndinfjxlmvpurhul] JibriSelenium$joinCall$1.run#325: An error occurred while joining the call
org.openqa.selenium.WebDriverException: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=104.0.5112.79)
  (Driver info: chromedriver=104.0.5112.79 (3cf3e8c8a07d104b9e1260c910efb8f383285dc5-refs/branch-heads/5112@{#1307}),platform=Linux 5.4.0-128-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: '56a3a431749f', ip: '172.23.0.6', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-128-generic', java.version: '11.0.16'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 104.0.5112.79 (3cf3e8c8a07d..., userDataDir: /tmp/.com.google.Chrome.M4T3jl}, cssSelectorsEnabled: true, databaseEnabled: false, goog:chromeOptions: {debuggerAddress: localhost:45791}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), rotatable: false, setWindowRect: true, strictFileInteractability: false, takesHeapSnapshot: true, takesScreenshot: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 104.0.5112.79, webStorageEnabled: true, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}
Session ID: 3a0c9b93af31b510448d8108bc4090e8
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
	at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
	at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
	at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:271)
	at org.jitsi.jibri.selenium.pageobjects.AbstractPageObject.visit(AbstractPageObject.kt:35)
	at org.jitsi.jibri.selenium.JibriSelenium$joinCall$1.run(JibriSelenium.kt:293)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Jibri 2022-10-18 09:06:26.111 INFO: [75] [session_id=ndinfjxlmvpurhul] JibriSelenium.onSeleniumStateChange#215: Transitioning from state Starting up to Error: FailedToJoinCall SESSION Failed to join the call
Jibri 2022-10-18 09:06:26.112 INFO: [75] [session_id=ndinfjxlmvpurhul] StatefulJibriService.onServiceStateChange#39: File recording service transitioning from state Starting up to Error: FailedToJoinCall SESSION Failed to join the call
Jibri 2022-10-18 09:06:26.112 INFO: [75] XmppApi$createServiceStatusHandler$1.invoke#311: Current service had an error Error: FailedToJoinCall SESSION Failed to join the call, sending error iq <iq xmlns='jabber:client' to='jibribrewery@internal-muc.meet.jitsi/focus' id='1K6NQ-55' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' status='off' failure_reason='error' should_retry='true'/></iq>
Jibri 2022-10-18 09:06:26.112 FINE: [75] JibriStatsDClient.incrementCounter#38: Incrementing statsd counter: stop:recording
Jibri 2022-10-18 09:06:26.115 INFO: [75] JibriManager.stopService#260: Stopping the current service
Jibri 2022-10-18 09:06:26.115 INFO: [75] [session_id=ndinfjxlmvpurhul] FileRecordingJibriService.stop#182: Stopping capturer
Jibri 2022-10-18 09:06:26.115 INFO: [75] [session_id=ndinfjxlmvpurhul] JibriSubprocess.stop#75: Stopping ffmpeg process
Jibri 2022-10-18 09:06:26.115 INFO: [75] [session_id=ndinfjxlmvpurhul] JibriSubprocess.stop#89: ffmpeg exited with value null
Jibri 2022-10-18 09:06:26.116 INFO: [75] [session_id=ndinfjxlmvpurhul] FileRecordingJibriService.stop#184: Quitting selenium
Jibri 2022-10-18 09:06:26.117 INFO: [75] [session_id=ndinfjxlmvpurhul] FileRecordingJibriService.stop#191: No media was recorded, deleting directory and skipping metadata file & finalize
Jibri 2022-10-18 09:06:26.118 INFO: [75] [session_id=ndinfjxlmvpurhul] JibriSelenium.leaveCallAndQuitBrowser#336: Leaving call and quitting browser
Jibri 2022-10-18 09:06:26.118 INFO: [75] [session_id=ndinfjxlmvpurhul] JibriSelenium.leaveCallAndQuitBrowser#339: Recurring call status checks cancelled
Jibri 2022-10-18 09:06:26.142 INFO: [75] [session_id=ndinfjxlmvpurhul] JibriSelenium.leaveCallAndQuitBrowser#345: Got 3 log entries for type browser
Jibri 2022-10-18 09:06:26.165 INFO: [75] [session_id=ndinfjxlmvpurhul] JibriSelenium.leaveCallAndQuitBrowser#345: Got 113 log entries for type driver
Jibri 2022-10-18 09:06:26.188 INFO: [75] [session_id=ndinfjxlmvpurhul] JibriSelenium.leaveCallAndQuitBrowser#345: Got 0 log entries for type client
Jibri 2022-10-18 09:06:26.188 INFO: [75] [session_id=ndinfjxlmvpurhul] JibriSelenium.leaveCallAndQuitBrowser#354: Leaving web call
Jibri 2022-10-18 09:06:26.220 INFO: [75] [session_id=ndinfjxlmvpurhul] JibriSelenium.leaveCallAndQuitBrowser#361: Quitting chrome driver
Jibri 2022-10-18 09:06:26.297 INFO: [75] [session_id=ndinfjxlmvpurhul] JibriSelenium.leaveCallAndQuitBrowser#363: Chrome driver quit
Jibri 2022-10-18 09:06:26.298 INFO: [75] JibriStatusManager$$special$$inlined$observable$1.afterChange#72: Busy status has changed: BUSY -> IDLE
Jibri 2022-10-18 09:06:26.298 FINE: [75] WebhookClient$updateStatus$1.invokeSuspend#107: Updating 0 subscribers of status
Jibri 2022-10-18 09:06:26.300 INFO: [75] XmppApi.updatePresence#203: Jibri reports its status is now JibriStatus(busyStatus=IDLE, health=OverallHealth(healthStatus=HEALTHY, details={})), publishing presence to connections
Jibri 2022-10-18 09:06:26.300 FINE: [75] MucClientManager.setPresenceExtension#160: Setting a presence extension: org.jitsi.xmpp.extensions.jibri.JibriStatusPacketExt@7a54d219
Jibri 2022-10-18 09:06:26.301 FINE: [75] MucClientManager.saveExtension#185: Replacing presence extension: org.jitsi.xmpp.extensions.jibri.JibriStatusPacketExt@7f9287f7
Jibri 2022-10-18 09:06:26.306 FINE: [65] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse: Could not add a provider for element busy-status from namespace http://jitsi.org/protocol/jibri
Jibri 2022-10-18 09:06:26.307 FINE: [65] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse: Could not add a provider for element health-status from namespace http://jitsi.org/protocol/health

what shoud i do?
thanks for your help

**Comment by saghul** [comment]
You need to set PUBLIC_URL to a valid value.

**Comment by saghul** [comment]
Please read the documentation. It's the public URL where your meetings are accessible.

**Comment by mehrdadhaji** [comment]
https://localhost:8443/
i cant use localhost? i dont want use it over internet just inside our office 
people can join to my meetings there is no problem only problem is recording

**Comment by saghul** [comment]
Then you'll need to override the chrome flags for the Jibri Chrome to ignore certificate checks.

**Comment by mehrdadhaji** [comment]
> 

now i have domain
this is my .env

CONFIG=~/.jitsi-meet-cfg

# Exposed HTTP port
HTTP_PORT=80

# Exposed HTTPS port
HTTPS_PORT=443

# System time zone
TZ=UTC


ENABLE_HTTP_REDIRECT=1

#JITSI_IMAGE_VERSION=latest
ENABLE_RECORDING=1
JIBRI_RECORDER_USER=recorder
JIBRI_RECORDING_DIR=/config/recordings
JIBRI_XMPP_USER=jibri
JIBRI_STRIP_DOMAIN_JID=muc
JIBRI_BREWERY_MUC=jibribrewery
JIBRI_PENDING_TIMEOUT=90



i set public domain and JVB_ADVERTISE_IPS

 when i start record i have this error:
the recording service currently unavailable


my logs

jicofo_1   | Jicofo 2022-10-25 11:24:33.615 INFO: [26] [room=m@muc.meet.jitsi meeting_id=8b7ddff8-093f-4908-abc0-d4c8fe8cbcf7] BaseJibri.handleJibriRequest#75: Accepted jibri request: <iq xmlns='jabber:client' to='focus@auth.meet.jitsi/focus' from='m@muc.meet.jitsi/d65155e0' id='Zm9jdXNAYXV0aC5tZWV0LmppdHNpL2ZvY3VzADhhNjY0ZjBkLWJhZWEtNDUzNC1hODA0LWZjYmI1NmRhNjY4NDpzZW5kSVEAY6EPDAaQlPo=' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' action='start' recording_mode='file' app_data='{"file_recording_metadata":{"share":true}}'/></iq>
jicofo_1   | Jicofo 2022-10-25 11:24:33.618 SEVERE: [44] [room=m@muc.meet.jitsi meeting_id=8b7ddff8-093f-4908-abc0-d4c8fe8cbcf7] JibriSession.startInternal#304: Unable to find an available Jibri, can't start
jicofo_1   | Jicofo 2022-10-25 11:24:33.618 INFO: [44] [room=m@muc.meet.jitsi meeting_id=8b7ddff8-093f-4908-abc0-d4c8fe8cbcf7] JibriRecorder.handleStartRequest#124: Failed to start a Jibri session, no Jibris available


what should i do now?

**Comment by mehrdadhaji** [comment]
> Then you'll need to override the chrome flags for the Jibri Chrome to ignore certificate checks.

this is my problem? where can i do this? which config file?

**Comment by saghul** [comment]
You need to set https://github.com/jitsi/docker-jitsi-meet/blob/c694a9e657627a2d31e0f10755caaa38d6d4f220/jibri.yml to the default: https://github.com/jitsi/jibri/blob/7ab9aa249fc1870c396d88400e895acf5a98d2a6/src/main/resources/reference.conf and add ` --ignore-certificate-errors`
