### ISSUE TITLE
Support single-use mode in jibri

### ISSUE THREAD

**Issue by Tobaroo** [jitsi/docker-jitsi-meet#1421]
Hi dear Jitsi crew,

Using Jitsi in version stable-7648-4, I would like to use the "single-use mode" capability for Jibri that is present in the regular (non- containerized) version.

The capability makes the health status of a Jibri go to "EXPIRED" after use so that it can be restarted and a fresh container spun up. Its usage was recommended by a fellow jitster in [this community comment](https://community.jitsi.org/t/how-to-create-multiple-jibri-instances/107823/5).

To my understanding, the source code is already there and no changes are required. However, the flag "jibri.single-use-mode" is missing from the [jibri.conf template](https://github.com/jitsi/docker-jitsi-meet/blob/master/jibri/rootfs/defaults/jibri.conf) for the Docker version.

Could this flag be added to an upcoming version, to be configured by an env variable and "false" by default?
Thank you for considering this.

**Comment by bgrozev** [comment]
Sounds reasonable. Are you interested in making a PR?

**Comment by Tobaroo** [comment]
Will do, thank you for the feedback. I will post it here when it's ready.

**Comment by Tobaroo** [comment]
[PR #1422](https://github.com/jitsi/docker-jitsi-meet/pull/1422) created

**Comment by Tobaroo** [comment]
That solved it: a Jibri instance can now be configured for single-use mode by setting the environment variable JIBRI_SINGLE_USE_MODE=true for the Jibri container.

Thank you @bgrozev for picking this up! Closing the issue.
