### ISSUE TITLE
Only in unstable: ENABLE_GUESTS=1 breaks login dialog with ENABLE_AUTH=1

### ISSUE THREAD

**Issue by JodliDev** [jitsi/docker-jitsi-meet#1425]
Hello. New Jitsi user here. So I hope I didnt overlook anything.
Thank you for this amazing project!

I think, there has been a small regression in the web frontent 9 days ago.

When using `ENABLE_AUTH=1` and `ENABLE_GUESTS=1` together, the login dialog never appears after pressing the button "I am the host". Instead, the "Waiting for host" - dialog just closes and after a few seconds it appears again.

Other things of notice:
- This problem does **not** occur when using `JITSI_IMAGE_VERSION=unstable-2022-10-17` and below. But starting with version `JITSI_IMAGE_VERSION=unstable-2022-10-18` until the most recent `JITSI_IMAGE_VERSION=unstable-2022-10-26`, the login dialog seems to be broken.
- The login dialog shows up as expected when using `ENABLE_AUTH=1` and `ENABLE_GUESTS=0` or when removing `config.hosts.anonymousdomain = 'guest.meet.jitsi';` from CONFIG/web/config.js (I assume both do the same internally).
- This only happens in the web frontend. Using the android app, everything works as expected.

I am using the stable version anyway. But I stumbled over that problem by accident and wanted to let you guys know. I hope that is alright :)

**Comment by saghul** [comment]
Thanks for the report! The image ranges are very useful to try and catch this one!

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/jitsi-meet/pull/12470 should be part of tomorrow's unstable.
