### ISSUE TITLE
 When I click on the JIGASI TRANSCRIBER ADVERTISE URL, I get 404 error

### ISSUE THREAD

**Issue by ChGunay** [jitsi/docker-jitsi-meet#1427]
When I try to access the txt files I recorded with jigasi and google speech to text services, I get the following error. Actually, I understood the cause of the error, but I couldn’t find how to solve it. Waiting for your valuable answers.
<img width="224" alt="Ekran Resmi 2022-10-29 15 14 14" src="https://user-images.githubusercontent.com/41910291/198833639-837599b9-4a46-4d4b-a25b-97107bccb479.png">

In the picture above, jitsi is sending the link where he recorded the meeting chat. But when I click on the link I get 404 error. also when I look at the logs of the web container
`{"log":"2022/10/26 20:07:12 [error] 260#260: *62 open() \"/usr/share/jitsi-meet/2022-10-26T20:07:00.591530Z_35c4790f- 7f4a-46cf-854d-b302f880d7f4/transcript_2022-10-26T20:07:00.592183Z_dc3d59c5-a967-4759-9dd0-5dad7e3181de.txt\" failed (2: No such file or directory)`

I see log. As far as I understand, the txt files are saved in the /usr/share/jitsi-meet/transcripts path, but it searches for the files directly in the /usr/share/jitsi-meet path. how can i solve this problem?

**Comment by saghul** [comment]
I think we need to add a handler to the web co Rainer so it can proxy / handle those requests.

**Comment by telam** [comment]
Any update on this issue?

**Comment by saghul** [comment]
No but a PR would be welcome.

**Comment by bmagistro** [comment]
PR incoming (hit this while testing out transcription), super trivial change and with the config volume mounted in you can edit and do a docker exec nginx -s reload to load the change without restarting the container and losing the config change for testing.
