### ISSUE TITLE
Websockets not working (solved)

### ISSUE THREAD

**Issue by audouts** [jitsi/docker-jitsi-meet#1433]
Reference: #1430 

I wrote about a problem in issue #1430 and then someone else came in and kind of took over the thread. It was closed before I responded.

The problem I had was simple to solve but the section on reverse proxy for Docker is kind of buried, in my opinion. The information could be organized better. For example, in the **Quick start** section, where there is mention of reverse proxy, it would be helpful to point the reader to the reverse proxy section. Even better, there could be a step "7." that talks about that part of the setup.

In my case the problem was solved by correctly setting up the two locations:
`/xmpp-websocket`
`/colibri-ws`

Thanks!

**Comment by saghul** [comment]
Thanks for sharing!
