### ISSUE TITLE
Disable hideAutoAssignButton via custom config not working

### ISSUE THREAD

**Issue by dg-otrs** [jitsi/docker-jitsi-meet#1434]
Hey,

I tried to disable the button hideAutoAssignButton on our jitsi meet (docker) instance. I tried via jitsi meet web custom config. Like:
`user@dockernode01 /var/lib/otrs-saas/home/docker/jitsi $ cat .jitsi-meet-cfg/web/custom-config.js
config.hideAutoAssignButton = true;
`

After restart of the web container, the button is still available. It seems to me that the docker version of Jitsi is not able to full fill this change.

Got this someone working? Did I something wrong?

Cheers

Dennis

**Comment by saghul** [comment]
Try this:

```
config.breakoutRooms = {
    hideAutoAssignButton: true;
};
```

**Comment by dg-otrs** [comment]
Perfect! Thank you man. Its working out like expected.
