### ISSUE TITLE
Limited features 

### ISSUE THREAD

**Issue by ncamacho97** [jitsi/docker-jitsi-meet#1435]
why is this docker setup limited with features the community server https://meet.jit.si/ has way more features like whitebored and live streaming any reason why this one is limited?

**Comment by saghul** [comment]
Is is not limited in any way.

meet.jit.si runs ahead of stable, so it may have features not yet on a released version.

For live streaming you just need to launch the Jibri container, and for whiteboards the Excalidraw backend.

The config necessary to wire the config for it is missing here, but will be coming with the next stable release.
