### ISSUE TITLE
Creating a prosody user fails

### ISSUE THREAD

**Issue by thomas-mc-work** [jitsi/docker-jitsi-meet#1448]
Following the instructions in #443 I've tried to create a user with this command:

    docker compose exec --user prosody prosody prosodyctl --config /config/prosody.cfg.lua register testuser meet.jitsi 123456

Then I get the following message:

    datamanager         error       Unable to write to accounts storage ('/config/data/meet%2ejitsi/accounts/testuser.dat~: Permission denied') for user: testuser@meet.jitsi
    Error: Error saving to storage

Then target folder has the following permissions:

    drwxr-xr-x 2 root root 4096 Oct 12 11:51 /config/data/meet%2ejitsi/accounts

So can that actually work at all? But also changing the permissions to make it writable for the user `prosody` didn't change the situation for me.

Any help is appreciated!

**Comment by saghul** [comment]
How are you starting Docker compose? As what user?what are the permissions of the config volume on the host system?

**Comment by thomas-mc-work** [comment]
:man_facepalming: I supposed it'd be something so simple … I changed it to the according user inside the prosody container – works.

Thank you!

**Comment by thomas-mc-work** [comment]
Final hint for following readers: Don't run docker as root. Seems to avoid this problem in the first place.
