### ISSUE TITLE
Error starting jitsi pod

### ISSUE THREAD

**Issue by rodrigo1254** [jitsi/docker-jitsi-meet#1451]
I had to reset my system images (after a year) as I was in someone else’s registry and then after that I stopped getting call logs, I start reporting these errors from the jitsi pod as soon as it starts

`speakerstats.meet.jitsi:speakerstats_component  error	No muc_component specified. No muc to operate on!
portmanager                                     info	Activated service 's2s' on [*]:5269, [::]:5269
speakerstats.meet.jitsi:tls                     info	Certificates loaded
portmanager                                     info	Activated service 'c2s' on [*]:5222, [::]:5222
portmanager                                     info	Activated service 'legacy_ssl' on no ports
meet.jitsi:tls                                  info	Certificates loaded
portmanager                                     info	Activated service 'http' on [*]:5280, [::]:5280
portmanager                                     info	Activated service 'https' on no ports
focus.meet.jitsi:tls                            info	Certificates loaded
<no value>:tls                                  error	Error creating context for c2s: No certificate present in SSL/TLS configuration for <no value>
<no value>:tls                                  error	Error creating contexts for s2sin: No certificate present in SSL/TLS configuration for <no value>
`

![Captura de tela de 2022-12-12 16-00-51](https://user-images.githubusercontent.com/56684626/207136931-547cdd7f-2687-409a-ba76-232f8b030fa5.png)

I already looked for something similar here but I didn’t find it

**Comment by rodrigo1254** [comment]
the prosody image has .lua scripts and so an image was generated separately from a former employee's repository, so now we move on to the company's repository

I updated the images and some errors disappeared and only this one was left in the print

could you help me with a detail please?

new calls, end of calls were generated logs inside our .lua script, example

`module:hook("muc-room-created", function(event)
    local room = event.room;
    local path = host .. "/api/v1/videoconferencia/criar/" .. room:get_name() .. "?status=inicio";

    https.request( path, { method = "GET", insecure = true }, function(res, test1, test2)
      module:log("info", "TEST OK");
    end)`

I remember these logs working including calling our apis and this stopped happening at runtime during calls

sorry the question seems simple but I'm new to jitsi and I didn't find details to guide me where it could be wrong

**Comment by damencho** [comment]
where do you load this custom module?

**Comment by saghul** [comment]
I'd start by looking at the Prosody logs. Are there any errors on startup or runtime?

**Comment by rodrigo1254** [comment]
@damencho 
in the prosody image there is a copy of the scriptsCOPY ./scripts/mod_muc_meeting_id.lua /usr/lib/prosody/modules/mod_muc_meeting_id.lua
COPY ./scripts/mod_muc_meeting_id.lua /prosody-plugins/mod_muc_meeting_id.lua

and in them are the sequence of custom modules

@saghul this print (which I forgot in the previous post) is the prosody log, there is an error
![Screenshot (25)](https://user-images.githubusercontent.com/56684626/207436200-cd0580eb-118e-44ef-a849-79fd0f3ffb8c.png)

**Comment by saghul** [comment]
That particular error is harmless. Does any error pop up when you join a meeting?

**Comment by rodrigo1254** [comment]
no, this is the main problem, it doesn't even generate any logs during the meetings, the only logs are generated only when I do a deployment and only

an observation to be made, is that when starting (startup info Hello and welcome to Prosody version 0.12.1..) I put a call outside the module:hook(.. right at the beginning calling one of our apis and it works, the problem is that these module:hook(... don't work at runtime

**Comment by damencho** [comment]
That hook to work, the module needs to be loaded under the muc component.

**Comment by rodrigo1254** [comment]
I was comparing the old code from the prosody image and I saw that the difference between the version that worked and this one is this line of code

RUN patch -d /usr/lib/prosody/modules/muc -p0 < /prosody-plugins/muc_owner_allow_kick.patch

I had removed it because it returned me this error

Step 17/27 : RUN patch -d /usr/lib/prosody/modules/muc -p0 < /prosody-plugins/muc_owner_allow_kick.patch
  ---> Running in 718d5c2dbe2a
patching file muc.lib.lua
Hunk #1 FAILED at 1256.
1 out of 1 hunk FAILED -- saving rejects to file muc.lib.lua.rej
The command '/bin/sh -c patch -d /usr/lib/prosody/modules/muc -p0 < /prosody-plugins/muc_owner_allow_kick.patch' returned a non-zero code: 1

Is it possible that this command is what is needed?

**Comment by saghul** [comment]
No, that functionality is now working without the patch.

**Comment by rodrigo1254** [comment]
I found the problem, and it was silly but I need to close the topic with a solution, my iframe meet wasn't setting my domain and that's why I wasn't receiving logs in my cluster
