### ISSUE TITLE
Blank remote video in Safari 16.0

### ISSUE THREAD

**Issue by denis-ionov** [jitsi/docker-jitsi-meet#1455]
Users can only see own video (local), but not remote (blank black screen). Audio is ok. This reproducing only in Safari and with "live" instances (on dev local env it's ok). I'm usually using Chrome and not sure from what version (Safari or Jitsi) this issue started. There is no errors in any logs (browser dev console, container logs, etc). Any ideas about this issue?

**Comment by saghul** [comment]
What version of the images did you install? Can you reproduce that on meet.jit.si ?

**Comment by denis-ionov** [comment]
@saghul i use `stable-7577-2` for all images. There is no issue on meet.jit.si on safari

**Comment by denis-ionov** [comment]
Search for issues in containers logs again and find following in jvb and jicofo containers:
`
JVB 2023-01-11 08:57:05.306 WARNING: [75] [confId=1015fd8767ee27f2 conf_name=04186dc6-8000-40be-8c76-a1c348203585@muc.meet.jitsi meeting_id=fbcfa173 epId=80cd4cbf stats_id=Allene-ffo] VideoQualityLayerLookup.transform#44: Unable to find encoding matching packet! packet=RtpPacket: PT=100, Ssrc=518917834, SeqNum=12282, M=false, X=true, Ts=1564802533, TID=0; sources=
`
and:
`
Jicofo 2023-01-11 08:57:03.958 WARNING: [302] [room=04186dc6-8000-40be-8c76-a1c348203585@muc.meet.jitsi meeting_id=fbcfa173-18d6-481e-977f-1ab2bd1648c2 participant=b7e74b1b] ParticipantInviteRunnable.lambda$doRun$0#194: Failed to convert ContentPacketExtension to Media: <content creator='initiator' name='data' senders='both'><transport xmlns='urn:xmpp:jingle:transports:ice-udp:1'><fingerprint xmlns='urn:xmpp:jingle:apps:dtls:0'/></transport><description xmlns='urn:xmpp:jingle:apps:rtp:1' media='application'/></content>
`

**Comment by saghul** [comment]
Please try the latest images.
