### ISSUE TITLE
jwt only works with JWT_ENABLE_DOMAIN_VERIFICATION=false

### ISSUE THREAD

**Issue by q16marvin** [jitsi/docker-jitsi-meet#1460]
Hi, 

i use Docker "stable-8218" and sadly JWT auth only works when JWT_ENABLE_DOMAIN_VERIFICATION=false is in .env

jitsi required "meet.jitsi" in jwt token in sub, with correct domain its not working:

![grafik](https://user-images.githubusercontent.com/19844709/212835630-806405f7-d148-43a9-89bf-efb14da8bada.png)

is this realy like expected

**Comment by saghul** [comment]
Sort of. In the Docker setup we use a "fake" XMPP domain since all the routing happens on the Docker layer.

@damencho Would it make sense to flip the default here, since in the Docker case, unless you change XMPP_DOMAIN and friends, the current default is bad?

**Comment by q16marvin** [comment]
so if i add 

XMPP_DOMAIN=meet.gut**** (like my PUBLIC_URL)

it should work?

**Comment by saghul** [comment]
I think so.

**Comment by q16marvin** [comment]
mhhh not working, i got logs like this:

`docker XMPPError: not-allowed - cancel [Communication with remote domains is not enabled]`

**Comment by saghul** [comment]
Please share the generated prosody config

**Comment by q16marvin** [comment]
you mean prosody.cfg?

[prosody.cfg.lua.txt](https://github.com/jitsi/docker-jitsi-meet/files/10435131/prosody.cfg.lua.txt)

**Comment by saghul** [comment]
No, the jitsi-meet.lua file inside conf.d. Sorry I wasn't specific.

**Comment by q16marvin** [comment]
okay here:

[jitsi-meet.cfg.lua.txt](https://github.com/jitsi/docker-jitsi-meet/files/10436249/jitsi-meet.cfg.lua.txt)

**Comment by debendraoli** [comment]
I'm using k8s setup, similar to docker, domain verification works but problem I found is with the Jibri, it fails to join the call.
I thought this meant to fix the issue but not sure why.
https://github.com/jitsi/docker-jitsi-meet/blob/8684b0b3d159712b6f786679b864b304a3fd6c67/prosody/rootfs/defaults/conf.d/jitsi-meet.cfg.lua#L46

Maybe we also needed to add to unlimited jids? IDK.
https://github.com/jitsi/docker-jitsi-meet/blob/8684b0b3d159712b6f786679b864b304a3fd6c67/prosody/rootfs/defaults/conf.d/jitsi-meet.cfg.lua#L53

**Comment by q16marvin** [comment]
me to, it fails to join the call... got timeout after 60 seconds... but same if i disable AUTH

**Comment by saghul** [comment]
@q16marvin I'm a bit confused now. Does JWT auth work for you now? With or without domain verification?

**Comment by q16marvin** [comment]
JWT only works with JWT_ENABLE_DOMAIN_VERIFICATION=false... if i set JWT_ENABLE_DOMAIN_VERIFICATION=true jitsi expected "meet.jitsi" in jwt sub and not like it should "meet.gut******" (my public domain name)

**Comment by saghul** [comment]
> JWT only works with JWT_ENABLE_DOMAIN_VERIFICATION=false... if i set JWT_ENABLE_DOMAIN_VERIFICATION=true jitsi expected "meet.jitsi" in jwt sub and not like it should "meet.gut******" (my public domain name)

So then we're back to the original problem. That has nothing to do with Jibri, so please let's stay on topic.



> okay here:
> 
> [jitsi-meet.cfg.lua.txt](https://github.com/jitsi/docker-jitsi-meet/files/10436249/jitsi-meet.cfg.lua.txt)

As you can see it says "meet.jitsi" everywhere, so you haven't properly set XMPP_DOMAIN and so on to match your public domain.

**Comment by q16marvin** [comment]
yes that works, i set ALL domain settings it works:

`XMPP_DOMAIN=meet.gut********
XMPP_AUTH_DOMAIN=auth.meet.gut********
XMPP_SERVER=xmpp.meet.gut********
XMPP_BOSH_URL_BASE=http://xmpp.meet.gut********:5280
XMPP_MUC_DOMAIN=muc.meet.gut********
XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.gut********
XMPP_GUEST_DOMAIN=guest.meet.gut********
XMPP_RECORDER_DOMAIN=recorder.meet.gut********`

i thought it would be better if jitsi communicate internal with this "meet.jitsi" network. Not everything goes over pulic url and internet correct?

**Comment by saghul** [comment]
Partially, but that's ok.

**Comment by q16marvin** [comment]
would be good to add in docs :)

https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker/#authentication-using-jwt-tokens

**Comment by saghul** [comment]
Indeed. Would you like to make a PR there?
