### ISSUE TITLE
jibri cant join call, timeout after 60 seconds

### ISSUE THREAD

**Issue by q16marvin** [jitsi/docker-jitsi-meet#1462]
Hey,

i useing latest docker... and started jitsi like this:

> docker-compose -f docker-compose.yml -f jibri.yml up --scale jibri=2 -d

everything is working fine, but not recording... 

here my .env file:
[env.txt](https://github.com/jitsi/jibri/files/10474502/env.txt)

and here jibri logs:

[browser.0.txt](https://github.com/jitsi/jibri/files/10474500/browser.0.txt)
[log.0.txt](https://github.com/jitsi/jibri/files/10474501/log.0.txt)

what could be the reason?

**Comment by saghul** [comment]
I see Jibri timing out when connecting to the meeting. Note it joing the meeting by visiting the public URL. Is that properly accessible?

**Comment by q16marvin** [comment]
yes of course, we can connect easy via https://meet.gut******

**Comment by saghul** [comment]
Can you edit jibri.yml and try to use the previous stable release instead?

**Comment by q16marvin** [comment]
forget it... i got it... it was depending to nat reflection... jibri tries to connect via public url, so also public ip... issue can closed. sorry
