### ISSUE TITLE
JWT auth: first as moderator, other as member

### ISSUE THREAD

**Issue by relleet** [jitsi/docker-jitsi-meet#1465]
Hello, we can't understand how the variable **ENABLE_AUTO_OWNER** works.

We use messengers such as Mattermost or RocketChat to connect to the Jitsi conference. We use Docker Compose (Jitsi Meet Release: stable-8218) and JWT token for Jitsi authentication. Our config:

.env
```
...
JVB_ADVERTISE_IPS=LOCAL_IP,PUBLIC_IP
ENABLE_AUTH=1
AUTH_TYPE=jwt

JWT_APP_ID=msg_app_id
JWT_APP_SECRET=msg_secret_key
JWT_ACCEPTED_AUDIENCES=msg_aud

JWT_ENABLE_DOMAIN_VERIFICATION=0
JWT_ALLOW_EMPTY=0
ENABLE_AUTO_OWNER=1
...
```

JWT Token:
```
{
  "iss": "msg_app_id",
  "sub": "URL_MSG_SRV",
  "exp": 1674744821,
  "aud": "msg_aud",
  "room": "63dd89t3e9g98ec868d",
  "context": {
    "user": {
      "name": "user1",
      "avatar": "AVATAR_URL",
      "email": "user1@MAIL_ADDR"
    }
  }
}
```
This configuration works perfectly well except for the fact that all the users who use this JWT token connect as moderators. We need the first user to connect as the moderator and all the rest as guests. 

In [post](https://community.jitsi.org/t/authenticated-users-with-jwt-first-participant-as-moderator-and-other-as-participants/114476/3) of the forum  offers us to use **ENABLE_AUTO_OWNER=1** variable to solve this problem. We tried to add it to .env without any positive results, as all the users who authorized using the same JWT token became moderators.

We can't use such plugins as [token_affiliation](https://github.com/jitsi-contrib/prosody-plugins/tree/main/token_affiliation) because Jitsi plugins for messengers don't let us add the "affiliation" field to the JWT token.

Could you please tell us how we can correct our solution or if there is another one?

**Comment by saghul** [comment]
Hi there!



> This configuration works perfectly well except for the fact that all the users who use this JWT token connect as moderators. We need the first user to connect as the moderator and all the rest as guests.

This is the expected default behavior when tokens are used. Users with a token are moderators, guests are not.



> In [post](https://community.jitsi.org/t/authenticated-users-with-jwt-first-participant-as-moderator-and-other-as-participants/114476/3) of the forum offers us to use **ENABLE_AUTO_OWNER=1** variable to solve this problem. We tried to add it to .env without any positive results, as all the users who authorized using the same JWT token became moderators.

That setting helps with what happens after a moderator leaves, for example.



> We can't use such plugins as [token_affiliation](https://github.com/jitsi-contrib/prosody-plugins/tree/main/token_affiliation) because Jitsi plugins for messengers don't let us add the "affiliation" field to the JWT token.
> 
> Could you please tell us how we can correct our solution or if there is another one?

If you cannot use affiliation then you need to solve this in your application. Have the "owner" of a meeting join with a token and the others without.

**Comment by relleet** [comment]
Thank you for responding so quickly!

We hope that messenger developers will add more flexible JWT token access settings to their Jitsi plugins. Such as the 'affiliation' field.

For now we will use your suggestion to:
> Have the 'owner' of a meeting join with a token and the others without.
