### ISSUE TITLE
Error while creating jitsi meet web build

### ISSUE THREAD

**Issue by amit-maurya-507464** [jitsi/docker-jitsi-meet#1466]
Err:1 https://download.jitsi.org stable/ InRelease
  Temporary failure resolving 'download.jitsi.org'
Err:2 http://deb.debian.org/debian bullseye InRelease
  Temporary failure resolving 'deb.debian.org'
Err:3 http://ftp.debian.org/debian bullseye-backports InRelease
  Temporary failure resolving 'ftp.debian.org'
Err:4 http://deb.debian.org/debian-security bullseye-security InRelease
  Temporary failure resolving 'deb.debian.org'
Err:5 http://deb.debian.org/debian bullseye-updates InRelease
  Temporary failure resolving 'deb.debian.org'

E: Unable to locate package cron
E: Unable to locate package nginx-extras
E: Unable to locate package jitsi-meet-web
E: Unable to locate package socat
E: Unable to locate package curl
E: Unable to locate package jq

**Comment by saghul** [comment]
You can't connect to Debian servers. You seem to have a connectivity problem.

**Comment by narayanan-ka** [comment]
> Err:1 https://download.jitsi.org stable/ InRelease Temporary failure resolving 'download.jitsi.org' Err:2 http://deb.debian.org/debian bullseye InRelease Temporary failure resolving 'deb.debian.org' Err:3 http://ftp.debian.org/debian bullseye-backports InRelease Temporary failure resolving 'ftp.debian.org' Err:4 http://deb.debian.org/debian-security bullseye-security InRelease Temporary failure resolving 'deb.debian.org' Err:5 http://deb.debian.org/debian bullseye-updates InRelease Temporary failure resolving 'deb.debian.org'
> 
> E: Unable to locate package cron E: Unable to locate package nginx-extras E: Unable to locate package jitsi-meet-web E: Unable to locate package socat E: Unable to locate package curl E: Unable to locate package jq

Hi amit. I'm getting the same errors. Have you been able to solve it ?
