### ISSUE TITLE
JWT auth via microsoft adfs

### ISSUE THREAD

**Issue by sumarokov89** [jitsi/docker-jitsi-meet#1470]
Is there any chance that jitsi can work with adfs?

I've create an application in adfs, so i've got app id and app secret
in .env file i add TOKEN_AUTH_URL=adfs.domain.name
so i add next in env:
ENABLE_AUTH=1
AUTH_TYPE=jwt
JWT_APP_ID=my_id
JWT_APP_SECRET=my_secret
TOKEN_AUTH_URL=adfs.domain.name

after creating room it constantly refreshing page and nothing else...

Do you have any instructions how it should be configured?
Or Jitsi can't work with ADFS?

**Comment by saghul** [comment]
It most certainly won't work like that. I think it may work if you connect it via the LDAP auth mechanism.

**Comment by sumarokov89** [comment]
Hi! Thats the problem is :)
We want to change LDAP auth to ADFS...

**Comment by saghul** [comment]
Than you need to find a Prosody module that implements that kind of auth.

Or implement a service which does the auth and generates a token, with the token auth URL option.

I'm not aware of a micro service that does this already though.

**Comment by sumarokov89** [comment]
Ok, thanks for your time! Have a good day!
