### ISSUE TITLE
Host not found - Fresh Docker Installation

### ISSUE THREAD

**Issue by jxs714** [jitsi/docker-jitsi-meet#1472]
Hey guys,

I installed Jitsi from the official docker. The only thing that I get is disconnects and never am able to use the software. I thought docker was supposed to be an easy setup to begin using software, but this is usually never the case. I am using Plesk + Docker. Here is the log error I am getting

xmpp.meet.jitsi could not be resolved (3: Host not found), client: 172.17.0.1, server: _, request: "POST /http-bind?room=test HTTP/1.0", host: "jitsi.MYDOMAIN.com", referrer: "https://jitsi.MYDOMAIN.com/test"

my configuration is default. Without the ENABLE_XMPP_WEBSOCKET=0 option, it never connects. With the option, itll just freeze until it disconnects. I am not able to use the software at all. Am I supposed to also install all other parts of jitsi docker.

Firewall is not the issue as its not enabled. I am using debian and the latest plesk. I am basically having the same issue as this issue: https://github.com/jitsi/docker-jitsi-meet/issues/1383

I even tried the Vultr.com preconfigured jitsi installation, but gave up because I could not get my URL to work. Kept getting an "connection error" with a yellow triangle.

How can I fix this issue?

**Comment by saghul** [comment]
I don't think it's related.

When you run Docker through Plesk, are you running docker-compose or running the different containers individually?

**Comment by jxs714** [comment]
Hello

I ran it through the docker installer for plesk, and also manually installed with the following tutorial

https://cloudinfrastructureservices.co.uk/how-to-setup-jitsi-meet-docker-container-image/

started from “download jitsi meet” at bottom of page. The plesk docker gave me the issue with the disconnects, the tutorial did the same even when i ran the command to download and install the latest stable release. The vultr app worked fine, but I couldnt get my url to work, it only worked by IP address. Id prefer to use my current server as its faster and cost efficient instead of vultr. Getting another server just for jitsi wouldnt be ideal.

please advise, thanks




> I don't think it's related.
> 
> When you run Docker through Plesk, are you running docker-compose or running the different containers individually?

**Comment by saghul** [comment]
We didn't write that tutorial nor do we have any Plesk specific documentation, sorry.

Please post in our community, some other users who have ran into the same might be able to help you.
