### ISSUE TITLE
Etherpad

### ISSUE THREAD

**Issue by CorvusGei** [jitsi/docker-jitsi-meet#1474]
I had several issues running Etherpad with Jitsi Meet on Docker:
- Etherpad didn't work with the self hosting guide on https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker - maybe you could update it with the suggestions from https://community.jitsi.org/t/etherpad-in-docker-version/24432/17 - these worked for me
- Where can I change the settings for Etherpad because of the DirtyDB-Warning?

**Comment by saghul** [comment]
HI there!

What didn't work? I just tried and had no issues.



> * Where can I change the settings for Etherpad because of the DirtyDB-Warning?

You can edit etherpad.yml to pass more settings there.

**Comment by CorvusGei** [comment]
Thank you very much for your help!
My first problem was the version of Etherpad - the guide in the linked community post helped.
Second issue: 
How can I suppress this warning? What settings should I pass in etherpad.yml?
![image](https://user-images.githubusercontent.com/101200194/217068477-88dcc59b-21a6-4281-a941-f21461f31c25.png)

**Comment by saghul** [comment]
See https://github.com/jitsi/docker-jitsi-meet/commit/4a0b48c4118b9df5242dd2152303edb810e5b942

**Comment by CorvusGei** [comment]
Thank you @saghul - worked perfectly!
