### ISSUE TITLE
manifest unknown

### ISSUE THREAD

**Issue by bunkerman** [jitsi/docker-jitsi-meet#1476]
Hi,

suddenly I get the error "Error response from daemon: manifest for jitsi/...:latest not found: manifest unknown: manifest unknown", when pulling the images via docker-compose. I changed the docker-compose.yml file from "jitsi/web:${JITSI_IMAGE_VERSION:-unstable}" to "jitsi/web:stable" (and so on). Then it works again.

**Comment by saghul** [comment]
The latest tag has been deprecated for a long time and got deleted.

You should be using a release tag to guarantee things won't break with upgrades.
