### ISSUE TITLE
Recording/live streaming older than 7439

### ISSUE THREAD

**Issue by iasbm** [jitsi/docker-jitsi-meet#1481]
i found the note at [here ](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#recording--live-streaming-configuration-with-jibri) suggesting some extra set up  of ALSA loop back  to be done on host ( explaining how to do on various OS)
Does it mean that if we are using any release after 7439, we don't have to do any ALSA Loop back on Host?
Just now i have tested the **stable-8252** on my laptop (Windows 10 with WSL2) and all went fine including recording without having to do any ALSA loopback config.
SO, is my understanding  true that there is no need for ALSA loop back config on HOSTS for any releases after 7439?

**Comment by saghul** [comment]
Correct. Starting with that release we switched over to PulseAudio and then the loop back device is created in user land.

**Comment by iasbm** [comment]
OK thanks and that's very cool @saghul .  But this brings up following points so that it becomes super clear to me and any one who sees this thread.
1. Given that now Jibri uses PuleAudio and Loop back device is created in user land (i.e. participant side) we no longer have to do "**asoundrc**" file configuration for JIBRI?
2.  Am i right in thinking that now the JIBRI hosting server and its capacity to record number of conferences is no longer limited by the number of Loop back interfaces supported by the Host ( i.e. i understand a host can have max 30 or 32 loop back interfaces and given that one JIBRI, before release 7439 of course, requires 2 loop back interfaces for recording, then that HOST can max record 30/2=15 or 32/2=16 conferences simultaneously irrespective of its CPU and RAM.
3. If the answer to above question (2) is YES, then from capacity planning can we say the number of conferences recorded by JIBRI host is based on its CPU and RAM?

I am not sure about others, but even now when i search online about JIBRI and its recording, still ALSA loop back related information is dominant and lots of K8S sample repos are also having JIBRI files with "asoundrc" files configured along with instruction on how to configure ALSA loop back etc.
So I request answers for the above 3 points so that this thread becomes more clearer to other community members about this.
thanks in advance.

**Comment by saghul** [comment]
Correct on all accounts! Running jibri containers is no longer dependent on any ALSA setup or limitations in the host system.
