### ISSUE TITLE
Docker Stable 8252 - Can not invite participant, no bridge available - room crash upon join

### ISSUE THREAD

**Issue by guemi** [jitsi/docker-jitsi-meet#1485]
Hello!

Trying to set up jitsi pn premises with docker and running into the issue that many seems to have that the room crashes when someone elses join - but none of the suggested fixes seems to work.

My environment looks the following:

Public IP 1.2.3.4 

1.2.3.4:80 and 1.2.3.4:443 is NAT:ed to 192.168.30.14 which is an NGINX reverse proxy.

1.2.3.4:10000 and 1.2.3.4:4443 is NAT:ed to 192.168.10.94 which is running docker and the jitsi containers.

.env file relevant bits: 

```
HTTP_PORT=8100
HTTPS_PORT=8200
PUBLIC_URL=https://meet.domain.com
JVB_ADVERTISE_IPS=1.2.3.4
```

NGINX Reverse config:

server {

  server_name meet.domain.com;

```
  location / {
        proxy_pass http://192.168.10.94:8100;
        proxy_set_header   X-Forwarded-For $remote_addr;
        proxy_set_header   Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto https;
        proxy_ssl_verify off;
  }

location /xmpp-websocket {
    proxy_pass http://192.168.10.94:8100;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}
location /colibri-ws {
    proxy_pass http://192.168.10.94:8100;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
}


[CERTBOT LET'S ENCRYPT SSL CONFIGURATION]

```

Everything works great until I try to join a meeting with two clients:

`jicofo_1   | 2023-03-01T18:42:27.277217450Z Jicofo 2023-03-01 18:42:27.277 SEVERE: [35] [room=test10@muc.meet.jitsi meeting_id=3076d7ab-5bd1-49e8-aa0e-7673a9a95a13 participant=0fd23f32] ParticipantInviteRunnable.doRun#213: Can not invite participant, no bridge available.`

I've tried:

Setting :
ENABLE_XMPP_WEBSOCKET=0

Testing both versions of the IPs on JVB_ADVERTISE_IPS:

JVB_ADVERTISE_IPS=1.2.3.4
JVB_ADVERTISE_IPS=192.168.10.94

Running the NGINX configuration over SSL - so proxy_pass to https://192.168.10.94:8200

What the hell am I missing? :(

**Comment by damencho** [comment]
Check jvb logs it will tell you why it cannot connect to prosody.

**Comment by guemi** [comment]
I didn't see anything of SEVERE / WARNING other than that, but then I went to sleep and figured I'd pick it back up tomorrow and then magically it worked. 

Maybe it takes a few minutes for everything to play nice after running docker-compose up. 

Testing it right now with 2 work calls going on, will test a bit more after work day.

**Comment by guemi** [comment]
Yup. Was able to reproduce it. Restart jitsi -> takes a few minutes before meetings start to work. Not the end of the world.
