### ISSUE TITLE
cant toggle "save recording file locally (Beta)" 

### ISSUE THREAD

**Issue by dprag** [jitsi/docker-jitsi-meet#1486]
Hi guys, 
I cant cant toggle "save recording file locally (Beta)"  when starting recording. The goal is to store the recording files on the Jitsi server not downloading it to the laptop 
Thanks
<img width="1380" alt="Screen Shot 2023-03-01 at 10 18 00 PM" src="https://user-images.githubusercontent.com/111251835/222359740-3a13ca14-b6bc-4e24-a76c-cab78ed3d894.png">

**Comment by saghul** [comment]
A server option is not present, did you enable it?

**Comment by duongprag** [comment]
ok great. I'm new to this. Any tutorial to enable the server option ? I have the Jibri container running already

**Comment by saghul** [comment]
What did you set in your .env file?

**Comment by duongprag** [comment]
JICOFO_AUTH_PASSWORD=xxxxx

JVB_AUTH_PASSWORD=xxxxxx

JIGASI_XMPP_PASSWORD=xxxxx
JIBRI_RECORDER_PASSWORD=xxxx
JIBRI_XMPP_PASSWORD=xxxx

**Comment by saghul** [comment]
You need to enable recording: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#recording--live-streaming-configuration-with-jibri

**Comment by dprag** [comment]
That fixed it. Thanks
