### ISSUE TITLE
Timed out receiving message from renderer

### ISSUE THREAD

**Issue by dprag** [jitsi/docker-jitsi-meet#1488]
Hi Guys, 
I got the below error from log.0.txt when hits "Start recording"  with option to "saved by recording service" "saved locally" works fine
[198] [session_id=yahltyhqzkssmjbe] JibriSelenium.joinCall$lambda-3#327: An error occurred while joining the call
org.openqa.selenium.TimeoutException: timeout: Timed out receiving message from renderer: -0.003

any idea what could be wrong ? 
Thanks

**Comment by damencho** [comment]
CPU or RAM for jibri

**Comment by dprag** [comment]
look like it uses about %15 cpu and still plenty of memory left on the docker host. Any settings I can change to increase the Jibri memory and cpu  ?

**Comment by saghul** [comment]
We don't support non-standard ports very well.

At the end of the day people won't be typing port numbers so using 443 is almost a must.

8443 is just there for development.
