### ISSUE TITLE
google speech to text transcription

### ISSUE THREAD

**Issue by dprag** [jitsi/docker-jitsi-meet#1490]
whenever I turn on the caption I got this error from jicofo :
"Transcription requested, but jigasiDetector is not configured"
I have added google api info in .env.  and enable the transcription. Any idea ? 
Thanks

**Comment by saghul** [comment]
Have you deployed Jigasi?

**Comment by dprag** [comment]
yes and enabled it in .env . The Jigasi container is running . 


ENABLE_TRANSCRIPTIONS | Enable Jigasi transcription in a conference | 1
GC_PROJECT_ID | project_id from Google Cloud Credentials |  
GC_PRIVATE_KEY_ID | private_key_id from Google Cloud Credentials |  
GC_PRIVATE_KEY | private_key from Google Cloud Credentials |  
GC_CLIENT_EMAIL | client_email from Google Cloud Credentials |  
GC_CLIENT_ID | client_id from Google Cloud Credentials |  
GC_CLIENT_CERT_URL | client_x509_cert_url from Google Cloud Credentials

<br class="Apple-interchange-newline">

**Comment by saghul** [comment]
Please share the whole log.

**Comment by dprag** [comment]
[jisagi.txt](https://github.com/jitsi/docker-jitsi-meet/files/10945252/jisagi.txt)
attached is the whole log 
thanks

**Comment by damencho** [comment]
There is some error:
```
panic: render template error: template: /defaults/sip-communicator.properties:44:88: executing "/defaults/sip-communicator.properties" at <b64enc>: invalid value; expected string
```
What is there on line 44?

**Comment by dprag** [comment]
line 44: net.java.sip.communicator.impl.protocol.sip.acc1.PASSWORD={{ .Env.JIGASI_SIP_PASSWORD | b64enc }}
Btw, I dont have the configuration for SIP gateway but for transcription only

**Comment by dprag** [comment]
So the issue has been fixed. The main issue is: 
2023-03-10 09:21:21.121 SEVERE: [14] net.java.sip.communicator.impl.configuration.ConfigurationActivator.fixPermissions: Error while fixing config file permissions
Thanks guys

**Comment by oerodriguezn** [comment]
Hi @dprag how did you fix it? please help, It seems I have the same issue
