### ISSUE TITLE
no bridge available

### ISSUE THREAD

**Issue by kennie-tsai** [jitsi/docker-jitsi-meet#15]
when person 2 join my muc room will crash.

```
Oct 01, 2018 10:14:18 AM net.java.sip.communicator.util.Logger info
INFO: Focus request for room: 123@muc.meet.jitsi
Oct 01, 2018 10:14:18 AM org.jitsi.util.LoggerImpl log
INFO: Created new focus for 123@muc.meet.jitsi@auth.meet.jitsi conferences count: 1 options:
    channelLastN: -1
    enableLipSync: true
    openSctp: true
    disableRtx: false
Oct 01, 2018 10:14:18 AM org.jitsi.util.LoggerImpl log
INFO: Lip-sync enabled in 123@muc.meet.jitsi
Oct 01, 2018 10:14:18 AM org.jitsi.util.LoggerImpl log
INFO: Joining the room: 123@muc.meet.jitsi
Oct 01, 2018 10:14:19 AM org.jitsi.util.LoggerImpl log
INFO: Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberJoined sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@6524612f member=ChatMember[123@muc.meet.jitsi/9c6efcea, jid: null]@504758532]
Oct 01, 2018 10:14:19 AM org.jitsi.util.LoggerImpl log
INFO: Granted owner to 123@muc.meet.jitsi/9c6efcea
Oct 01, 2018 10:14:19 AM org.jitsi.util.LoggerImpl log
INFO: Member 123@muc.meet.jitsi/9c6efcea joined.
Oct 01, 2018 10:14:50 AM net.java.sip.communicator.util.Logger info
INFO: Focus request for room: 123@muc.meet.jitsi
Oct 01, 2018 10:14:50 AM org.jitsi.util.LoggerImpl log
INFO: Chat room event ChatRoomMemberPresenceChangeEvent[type=MemberJoined sourceRoom=org.jitsi.impl.protocol.xmpp.ChatRoomImpl@6524612f member=ChatMember[123@muc.meet.jitsi/ac2fda61, jid: null]@10255114]
Oct 01, 2018 10:14:50 AM org.jitsi.util.LoggerImpl log
INFO: Member 123@muc.meet.jitsi/ac2fda61 joined.
Oct 01, 2018 10:14:50 AM org.jitsi.util.LoggerImpl log
SEVERE: Can not invite participant -- no bridge available.
Oct 01, 2018 10:14:50 AM org.jitsi.util.LoggerImpl log
SEVERE: Can not invite participant -- no bridge available.
Oct 01, 2018 10:14:51 AM org.jitsi.util.LoggerImpl log
```

**Comment by saghul** [comment]
Can you check the logs for the jvb? I suspect it may have failed to start.

**Comment by kennie-tsai** [comment]
This jvb log is generated during initialization.

```
JVB 2018-10-02 12:04:30.812 FINE: [50] org.jitsi.videobridge.xmpp.ComponentImpl.log() SENT: <iq to="focus@auth.meet.jitsi/focus92037461352391" from="jitsi-videobridge.meet.jitsi" id="ydqRN-41" type="error"><error type="cancel"><internal-server-error xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"></internal-server-error><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" xml:lang="en">Address discovery through STUN failed</text></error></iq>
JVB 2018-10-02 12:04:30.813 FINE: [50] org.jitsi.videobridge.xmpp.ComponentImpl.processIQ() (serving component 'JitsiVideobridge') Responding to IQ (packetId ydqRN-41) with: <iq to="focus@auth.meet.jitsi/focus92037461352391" from="jitsi-videobridge.meet.jitsi" id="ydqRN-41" type="error"><error type="cancel"><internal-server-error xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"></internal-server-error><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" xml:lang="en">Address discovery through STUN failed</text></error></iq>

```

You can see the video when there is only one person in the room, and it will crash when the second person joins the same room.

**Comment by saghul** [comment]
Please gist the entire log.

**Comment by kennie-tsai** [comment]
> Please gist the entire log.

https://gist.github.com/kennie-tsai/60c6021bf9e5c993d4dc25f3233024b5

**Comment by saghul** [comment]
Can you do the same for the jicofo logs?

**Comment by kennie-tsai** [comment]
> Can you do the same for the jicofo logs?

https://gist.github.com/kennie-tsai/26816185885ae2f74dae7e71e687c7bf

**Comment by saghul** [comment]
Calling in the cavalry: @damencho @bgrozev can you guys help? What could be causing this `Address discovery through STUN failed` error which triggers jicofo to remove the jvb?

**Comment by damencho** [comment]
That is strange, there is no exception in jvb it just replays with that error ... I wonder can it happen if jvb there is no internet on the jvb machine ...

**Comment by spuckydaslama** [comment]
got the exact same behaviour here with similar log. the only output indication an error is the one where discovery failing through STUN.

**Comment by saghul** [comment]
The prosody error is harmless.

Is your outbound traffic filtered by a firewall?

**Comment by spuckydaslama** [comment]
Yes there is a firewall and it might block outgoing stuff.

Saúl Ibarra Corretgé <notifications@github.com> schrieb am Mo., 8. Okt.
2018, 07:43:

**Comment by saghul** [comment]
I suspect that the bridge if somehow failing to start if it fails to do the outgoing STUN check. Can you try to disable it and see if things change?

**Comment by spuckydaslama** [comment]
Do i need public address discovery in a local network? I'd like to use jitsi in a VPN and naivly think i dont need this. What do you think?

**Comment by saghul** [comment]
TBH I'm not sure. I suggest the inductive approach: try without the VPN, then enable it. If things stop working, there is a bug related to it.

**Comment by saghul** [comment]
Closing as there has been no follow-up. Please reopen if needed.

**Comment by tvld** [comment]
No idea how to reopen.... but I am getting same "Second participant can't connect, grey or red screens appear on both devices"  as in https://github.com/jitsi/docker-jitsi-meet/issues/11  and in this Issue here it seems.

All used to work just fine. I think it stopped working after last reboot and a ``docker-compose up -d --force-recreate`` . On the server or proxy there are no changes.
I tried to ``DISABLE_HTTPS=1`` in ``.env`` and use locally http://  but that also did not do any good...
Jitsi became unusable and for now the company is back on ``talky.io``  ...

**Comment by saghul** [comment]
@tvld Only the original reporter (or any admin) can reopen.

Please open a new issue and provide as many details as possible. I'd rather have a new issue since while the synthoms seem to be the same, the problem might be totally different.

Note that .env file changes are ignored after the first continer start. Once the config files are generated they are not updated anymore, so you need to remove the files from the CONFIG directory and restart the containers so the config is regenerated.
