### ISSUE TITLE
Use Fully Qualified Image Name in base/Dockerfile FROM statement.

### ISSUE THREAD

**Issue by gitouche-sur-osm** [jitsi/docker-jitsi-meet#1510]
Hello,

Docker uses hardcoded configuration values in order to search for "unqualified image names" (e.g. `debian:bullseye-slim`) on docker.io registry : 
```
echo $(docker info | grep -oP "(?<=Registry: ).*")
https://index.docker.io/v1/
```
The use of these short names is not recommended as the registry it pulls from might depend on current configuration. This is explained in  [containers-registries.conf man page](https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md#note-risk-of-using-unqualified-image-names), and can be true for `docker` as well (if `registry-mirrors` is configured in `daemon.json`).

Please consider changing the `FROM` statement in order to use the Fully Qualified Image Name (FQIN), in https://github.com/jitsi/docker-jitsi-meet/blob/2fdc643e7c01a3213aa749b7582255ccc30249e4/base/Dockerfile#L1

FQIN format would be : 
```
FROM docker.io/library/debian:bullseye-slim
```
This would improve support for docker alternatives as well (e.g. `podman`), while staying 100% docker compatible.  
`base/Dockerfile` first line is the only place this change would be needed in `docker-jitsi-meet` repo :)

I can provide a PR if you need me to.

PS : despite the timing, this is not related to the current docker hub news!

**Comment by saghul** [comment]
LGTM, care to send a PR?
