### ISSUE TITLE
finalize.sh is not working in jibri, getting permission error

### ISSUE THREAD

**Issue by makkarss929** [jitsi/docker-jitsi-meet#1511]
![image](https://user-images.githubusercontent.com/41613183/228519910-8a9db1e0-d3bb-41a7-abc6-0c0f37a4ce80.png)

**Comment by aaronkvanmeerten** [comment]
Do you have executable permissions on for finalize.sh?  The dockerfile just does a 
`COPY rootfs/ /`
So as long as finalize.sh has a chmod +x I would think it would work as expected.

**Comment by makkarss929** [comment]
![image](https://user-images.githubusercontent.com/41613183/228531285-f5d1fa76-30fb-4625-a9bc-c5bcc8f48875.png)

**Comment by saghul** [comment]
> I want to store recording files in firebase, Can u provide script, I am new to this, I don't how to write script for this. Please help me

Please use our community for asking such questions, we try to keep the repository for code related issues only.
