### ISSUE TITLE
when second participants connects

### ISSUE THREAD

**Issue by ncamacho97** [jitsi/docker-jitsi-meet#1513]
so I'm able to spin up the  container and create a room no problem but as soon as second participant joins its crashes and i have a console error 

https://i.imgur.com/ugmOjcT.png

**Comment by ncamacho97** [comment]
error from second participant console error  

https://i.imgur.com/VcdVT81.png

**Comment by ncamacho97** [comment]
okay done 
https://gist.github.com/ncamacho97/5992b2daf9199f6dd6e5f852d40c0d37

**Comment by damencho** [comment]
Are there errors in the jicofo logs.

**Comment by ncamacho97** [comment]
@damencho so whayt do you want to see seems that this update has a problem when a second participants connects room crashes but one can join?

**Comment by damencho** [comment]
What are the jicofo errors, to figure out what is the problem...

**Comment by ncamacho97** [comment]
can you walk me through on getting the logs please

**Comment by saghul** [comment]
You can do `docker-compose logs jicofo`

**Comment by ncamacho97** [comment]
i should of known that lol thanks

**Comment by ncamacho97** [comment]
jicofo logs

https://gist.github.com/ncamacho97/5987f16c0d194678152f6e5670bfba9c.js

**Comment by damencho** [comment]
`Can not invite participant, no bridge available.`
Now check ivb logs.

**Comment by ncamacho97** [comment]
i think u mean jvb 

https://gist.github.com/ncamacho97/d5a99a99fa80cf3cd8e1b2c194a7f5d9

**Comment by ncamacho97** [comment]
FIXED IT @saghul @damencho  you guys need to edit that docker-compose.yml and remove ${JITSI_IMAGE_VERSION:-unstable} thats broken i added the newer versions

**Comment by saghul** [comment]
That means you didn't follow the instructions on the handbook and used a git clone instead of a stable release.
