### ISSUE TITLE
Typo in jvb.cfg

### ISSUE THREAD

**Issue by agemuend** [jitsi/docker-jitsi-meet#1520]
There seems to be a slight typo here: 

https://github.com/jitsi/docker-jitsi-meet/blob/master/jvb/rootfs/defaults/jvb.conf#L4

Env is missing a dot.

At least for us this led to JVB not starting properly after upgrading to the latest Git. It was introduced in ed095bc28e912601c7231657f9fbc7bccb52adcb (#1495)

**Comment by aaronkvanmeerten** [comment]
Ah this was likely me, I've got a PR here: https://github.com/jitsi/docker-jitsi-meet/pull/1521
