### ISSUE TITLE
jicofo.conf using wrong domain for authentication

### ISSUE THREAD

**Issue by jmozd** [jitsi/docker-jitsi-meet#1527]
- fresh install of Jitsi in K8s, using jitsi/jicofo:stable-8319
- ENABLE_AUTH=1
- ENABLE_GUESTS=1
- XMPP_DOMAIN=jitsi.example.com
- XMPP_GUEST_DOMAIN=guests.example.com
- XMPP_AUTH_DOMAIN=example.com

When trying to open a Jitsi conference room, after providing proper credentials (XMPP user), the "login" stalls, waiting for a session id (at least it says so - I can see in the browser console, that a session Id was returned).

Searching the web gave pointers to the auth settings in jifico.conf. I found it to contain the XMPP_DOMAIN value for jifio.authentication.login-url, and manually changed that to the value of XMPP_AUTH_DOMAIN. From then on, users could log in successfully.

The config is generated (https://github.com/jitsi/docker-jitsi-meet/blob/master/jicofo/rootfs/defaults/jicofo.conf#L42) - I blieve it needs to be changed to use XMPP_AUTH_DOMAIN instead of XMPP_DOMAIN.

Can anyone confirm?

**Comment by saghul** [comment]
The current value is correct, for our expected type of setup.

```
XMPP_DOMAIN=jitsi.example.com
XMPP_GUEST_DOMAIN=guests.example.com
XMPP_AUTH_DOMAIN=example.com
```

Generally speaking, all domains needs to be subdomains of XMPP_DOMAIN. Also, when enabling auth for your users, you'd do that in the main domain, XMPP_DOMAIN. See: https://github.com/jitsi/docker-jitsi-meet/blob/35685424e14d44102b03e4897e7188f560e01d91/prosody/rootfs/defaults/conf.d/jitsi-meet.cfg.lua#L113

**Comment by jmozd** [comment]
OK, I see - I'm coming from a different type of setup (probably not the most common) where XMPP is providing XMPP_DOMAIN for authentication of users and different types of services (plain end2end chat, Jitsi and so on) and thus Jitsi itself would be running in a sub-domain.

As things are working the way you intended it, I'll simply close this issue.
