### ISSUE TITLE
You have been disconnected, please check your network

### ISSUE THREAD

**Issue by Zzt1993** [jitsi/docker-jitsi-meet#1530]
After I unblocked these ports, I encountered a network error and was unable to enter the conference. Is there any other port that needs to be unblocked
![image](https://user-images.githubusercontent.com/95836616/231042296-fe347d92-7194-4875-9de3-f6c751c9a96c.png)
![image](https://user-images.githubusercontent.com/95836616/231042579-8254fe62-a008-4a97-a9ca-afa2f0f1a3b2.png)

**Comment by Zzt1993** [comment]
Everything is normal for me to access the internal network. Currently, there should only be issues with port opening. When I deployed using Docker on Centos

**Comment by damencho** [comment]
Check js console logs in the browser, what errors do you see?

**Comment by Zzt1993** [comment]
I saw these errors
![image](https://user-images.githubusercontent.com/95836616/231051516-761a1739-3a34-44c0-b0f2-7ea0d123a9a2.png)

![image](https://user-images.githubusercontent.com/95836616/231051485-e285bf9a-9690-4b26-93fb-039d518932b2.png)
