### ISSUE TITLE
Beginner-friendly instructions?

### ISSUE THREAD

**Issue by TheNomad11** [jitsi/docker-jitsi-meet#154]
It is supposed to be easier than ever to install Jitsi-meet with Docker, but the install instructions do not seem to be complete or presuppose some extra steps? I could not make it work.

I suppose that one has to pull the archive by git clone and then create the env file (what to change is not so clear neither) and than run docker compose within that folder? 

Thanks!

**Comment by kostmetallist** [comment]
Your step sequence description seems to be correct. What problems did you face at?

**Comment by saghul** [comment]
What instructions did you follow? https://github.com/jitsi/docker-jitsi-meet#quick-start should contain everything except the git clone part, which I will add right now, thanks!

**Comment by 0187773933** [comment]
installing via docker compose is one thing, setting it up successfully on a subdomain with nginx proxy pass is difficult to understand.

**Comment by vorburger** [comment]
I found the README of this project reasonable beginner friendly.

**Comment by normen** [comment]
> installing via docker compose is one thing, setting it up successfully on a subdomain with nginx proxy pass is difficult to understand.

Did you get that to work? I am having an issue where I can install and reach the server on the main domain but not when I try it on a subdomain - the web page shows but the conference doesn't work.
