### ISSUE TITLE
unable to access bosh url using public IP

### ISSUE THREAD

**Issue by prathibhacdac** [jitsi/docker-jitsi-meet#1541]
unable to access bosh URL using public ip. However when I run curl using the private of the docker-jitsi-meet-prosody-1 container I get the following result:

**curl https://192.168.16.2:5281/http-bind --insecure**
```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Prosody BOSH endpoint</title>
<style>
body{margin-top:14%;text-align:center;background-color:#f8f8f8;font-family:sans-serif}
h1{font-size:xx-large}
p{font-size:x-large}
p.warning>span{font-size:large;background-color:yellow}
p.extra{font-size:large;font-family:courier}
@media(prefers-color-scheme:dark){
body{background-color:#161616;color:#eee}
p.warning>span{background-color:inherit;color:yellow}
}
</style>
</head>
<body>
<h1> Prosody BOSH endpoint</h1>
<p>It works! Now point your BOSH client to this URL to connect to Prosody.</p>


</body>
</html>

```

How to set the bosh URL?

**Comment by saghul** [comment]
Did you forward the ports correctly?

**Comment by prathibhacdac** [comment]
The docker ip changes each time.

**Comment by saghul** [comment]
What exactly are you trying to accomplish? The Docker address is irrelevant since the bosh endpoint is proxied through the Http port which is exposed to the host.

**Comment by prathibhacdac** [comment]
> ward the ports correctly?

How to forward the ports?

**Comment by saghul** [comment]
You need to forward the ports in your firewall / router.

**Comment by prathibhacdac** [comment]
> You need to forward the ports in your firewall / router.

The prosody-docker ip is getting changed. How to prevent that?
Once it is showing 192.168.16.3
Next time it is changing to 192.168.16.2

**Comment by prathibhacdac** [comment]
https://10.176.16.170:1443/http-bind?room=cdac is working in browser but when I run the application it throws 

504 Bad Gateway.

**Comment by prathibhacdac** [comment]
> ess is irrelevant since the bosh endpoint is proxied through the Http port which is exposed to the host.

The bosh endpoint is not proxied to the https port. How to do it?

**Comment by prathibhacdac** [comment]
prosody container ports are not exposed to the host port.

8152a6286464   jitsi/prosody:unstable   "/init"   6 minutes ago   Up 6 minutes   0/tcp, 5222/tcp, 5280/tcp                                                        docker-jitsi-meet-prosody-1

**Comment by saghul** [comment]
The web container proxies bosh requests to the prosody container already, you don't need to configure anything.

I really don't understand what you want here.
