### ISSUE TITLE
Jicofo session gets restarted continuously

### ISSUE THREAD

**Issue by UsamaAbdulAziz** [jitsi/docker-jitsi-meet#1557]
I have set up Jitsi on an offline environment with docker.

- I start the meeting with 1 person (moderator). Works fine.
- As soon as I add a participant, The jicofo session gets restarted continuously.

This restart starts with line: 

```
docker-jitsi-meet-stable-8615-jicofo-1   | Jicofo 2023-05-24 15:36:51.565 INFO: [47] [room=test@muc.meet.jitsi meeting_id=33191ee7-7f2e-4aef-8309-c8e23494a3fe participant=c21ed0e8] Participant$JingleRequestHandlerImpl.onSessionTerminate#501: Received session-terminate, bsId=5f50b7fc-6d30-456d-a24d-10225e574a15, restartRequested=true
```

Complete logs (issue starts at line 56):
https://pastebin.com/gczbG5Gy

I would really appreciate some help here.
Thanks in advance.

**Comment by damencho** [comment]
ICE FAILED, probably the clients cannot send media to the videobridge, either there is a firewall blocking the UDP port 10000, There is no portforwarding from public address to jvb, or JVB is sending wrong addresses to clients.

What have you setup here: https://github.com/jitsi/docker-jitsi-meet/blob/ce59d1ed5d2878bc7ff3367e77508dec861391da/env.example#L37

**Comment by UsamaAbdulAziz** [comment]
Perfect. It got solved as soon as I set IPs correctly. Thank you.
