### ISSUE TITLE
Scaling whole Jitsi docker setup

### ISSUE THREAD

**Issue by UsamaAbdulAziz** [jitsi/docker-jitsi-meet#1558]
I set up jitsi setup with docker. I am able to run the whole scenario with all components on a single node server. I tried different implementation to do following, in order to achieve load balancing and failover:

- Install the whole package (nginx, Jitsi Meet,  jitsi-videobridge, prosody, jicofo) on 2 servers
- Put these servers behind a load balancer

I already did the above but each server of jitsi is unable to communicate with the other.
Means if a user A connects to server A, user B is unable to see the conference meeting in server B.

Is there some sort of connectivity configuration I need to put in order for this architecture to work?

Thanks in advance.

**Comment by saghul** [comment]
Generally speaking the first scaling problem you'll face is at the JVB level, so you can add multiple JVB containers and the load will be balanced automatically.

The next step would be to have multiple setups of the signalling side (frontend, prosody, jicofo) in which case you'll need to take care of making sure the same meeting name (URL) arrives at the same signalling entry point.

**Comment by UsamaAbdulAziz** [comment]
Thanks alot.
