### ISSUE TITLE
NGINX conf?

### ISSUE THREAD

**Issue by xthursdayx** [jitsi/docker-jitsi-meet#157]
I've gotten Jitsi running on a VM using this docker-compose stack and am now able to access the WebUI via http://<vm_ip>:8000 or https://<vm_ip>:8444. I would like to make Jitsi accessible on WAN at https://meet.my.domain via an NGINX reverse proxy, so I was wondering if you all have a suggested NGINX conf and if you can tell me what ports need to opened and forwarded to the VM? Would it just be https://my.domain:443 > http://<vm_ip>:8000?

Based on the Jitsi docs, I've come up with this, but I don't know if it is correct:
```
server {
        listen 80;
        server_name meet.my.domain;

        location / {
                return 301 https://$http_host$request_uri;
        }
}

server {
        listen 443 ssl http2;
        listen [::]:443 ssl http2;

        server_name meet.my.domain;
        ssl on;
        ssl_certificate /config/keys/letsencrypt/fullchain.pem;
        ssl_certificate_key /config/keys/letsencrypt/privkey.pem;
        ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
        ssl_ecdh_curve secp521r1;
        ssl_session_timeout 5m;  #SPDY timeout=180sec, keepalive=20sec; connection close=session expires
        ssl_session_cache shared:SSL:12m;
        ssl_stapling on;

        add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";

        location ~ ^/([a-zA-Z0-9]+)$ {
            rewrite ^/(.*)$ / break;
        }

        location / {
            ssi on;
            proxy_pass http://10.66.0.17:8000;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Host $http_host;
        }

       	# BOSH
	location /http-bind {
            proxy_pass      http://10.66.0.17:8000/http-bind;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Host $http_host;
        }
       	# xmpp websockets
        location /xmpp-websocket {
            proxy_pass http://10.66.0.17:8000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            tcp_nodelay on;
        }
 }
```

**Comment by lbeltrame** [comment]
```
location ~ ^/([a-zA-Z0-9]+)$ {
```

This block will break actually accessing rooms, remove it (everything is handled inside the nginx process inside the container)

```
location / {
proxy_set_header Host $http_host;
```

In the case `http_host` is not the same as the `server_name`, it'll break. I tested with  `$host` and "seems" to work.

**Comment by xthursdayx** [comment]
Okay, thanks for the clarification, I'll try that out.

**Comment by geekyayush** [comment]
Hey,
sorry for opening this old thread.
Did that work for you?
If yes, could you please send the Nginx config file content here?
That would be great.
Thanks.

**Comment by f1rf1n** [comment]
Or is there a tutorial or howto configuring this somewhere in the documentation?
Also how do you test on a server if this is actually working. You have no GUI tot start a webbrowser on localhost.  So before you get some sort of reverse proxy set up there is no way to test your set up?
