### ISSUE TITLE
hope to support event_sync_component

### ISSUE THREAD

**Issue by GalensGan** [jitsi/docker-jitsi-meet#1570]
I deployed Jitsi Meet using Docker on a Windows Server. 
I want to use the `event_sync_component plugin` to register callbacks for room creation and destruction in Prosody. However, I cannot configure it through `jitsi-meet.cfg.lua`, and the configuration is reset every time I restart the Docker container. I hope to add this plugin to the configuration, or find a way to use custom plugins
Thanks!

**Comment by saghul** [comment]
You'll need to mount the file and add it to XMPP_MUC_MODULES, that should do...

**Comment by GalensGan** [comment]
Thanks for your idea，it has been of great help to me。This is my solution：

If  you install jitsi-meet via Docker, the `conf.d\jitsi-meet.cfg.lua` file is reset by Prosody upon service restart, making it impossible to register plugins using the `Component` method in the `jitsi-meet.cfg.lua` file.

To solve this issue, you can follow these steps:

1. Save your custom plugin file to the `.jitsi-meet-cfg\prosody\prosody-plugins-custom` directory, which is mounted by Prosody.
2. Modify the source files of the plugin to match your own usage environment.
3. Use `XMPP_MUC_MODULES=event_sync_component` in the `.env ` file to enable the `event_sync_component`.

**Comment by danilvalov** [comment]
I just save it here because I spent some time to find how to pass parameters to custom plugins:
```env
XMPP_MUC_MODULES=event_sync_component
XMPP_MUC_CONFIGURATION="muc_component='muc.meet.jitsi', breakout_component='breakout.meet.jitsi', api_prefix='http://host.docker.internal:9000/api', api_headers={['Authorization']='123456789'}"
```
It works with base docker-jitsi-meet configuration running using `docker-compose.yml` from this repo

**Comment by iamtakingiteasy** [comment]
Worth noting that at least by default, plugin loading expects module entrypoint to be in `$module_name/mod_$module_name.lua`; but event_sync module in contrib repository unfortunately named outside of this convention: `event_sync/mod_event_sync_component.lua`; placing it custom plugins and removing `_component` resolves the issue.

**Comment by damencho** [comment]
The name is correct cause that is a component, it is not a regular module https://github.com/jitsi-contrib/prosody-plugins/tree/main/event_sync#installation

**Comment by iamtakingiteasy** [comment]
Maybe an example of complete .env configuration would be helpful. Defining XMPP_MUC_MODULES and XMPP_MUC_CONFIGURATION as provided above alone is not sufficient, without renaming it leads to error
```
modulemanager                                                error	Unable to load module 'event_sync': /usr/lib/prosody/modules/share/lua/5.4/mod_event_sync/mod_event_sync.lua: No such file or directory
```

**Comment by damencho** [comment]
Cause you need to add it as a component, as shown in the link I pasted above. You cannot do that from env if there is no special configuration for it.

**Comment by damencho** [comment]
You need to create a cfg.lua file like the rest and save it /config next to the other prosody configs.
