### ISSUE TITLE
RFC: add contrib plugins to the base image

### ISSUE THREAD

**Issue by saghul** [jitsi/docker-jitsi-meet#1571]
Should we add them? They could go in some /prosody-plugins-contrib directory

**Comment by denzs** [comment]
We would really like to use some of the plugins from the contrib repository (like lobby_autostart and token_lobby_bypass) as they provide some good additional value to us.. on the other hand we have a strong interest on keeping the modifications to the upstream container images as minimal as possible..

So from our point of view adding these to the upstream image (propably to the already existing and considered /prosody-plugins-custom folder) would be a great improvement! :)

As long as they are not explicitly loaded via the corresponding Environment Variables i would expect there should be no impact to the known behaviour as long as the plugin names do not collide - which does not seem to be the case..

**Comment by denzs** [comment]
I could also make a pull request if desired :+1:
