### ISSUE TITLE
prosody Error: Creating user failed

### ISSUE THREAD

**Issue by jcalfee** [jitsi/docker-jitsi-meet#1572]
```bash
docker-jitsi-meet-stable-8719$ docker-compose exec prosody /bin/bash
root@c945915e1b37:/# prosodyctl --config /config/prosody.cfg.lua register User meet.jitsi Password
Error: Creating user failed
```

**Comment by jcalfee** [comment]
Possibly related, I enabled JWT then when that did not work I tried to go back to internal auth.

https://github.com/jitsi/docker-jitsi-meet/issues/477

**Comment by saghul** [comment]
Do you get any logs in the container logs?

**Comment by jcalfee** [comment]
No errors.  I reset the volumes and commented out some more JWT and restarted and it works.  Now I need to figure out why it can't stay connected.  thanks
