### ISSUE TITLE
Jitsi websocket rejoin issue error 

### ISSUE THREAD

**Issue by dvlpathak** [jitsi/docker-jitsi-meet#1578]
i had a issue while running jitsi url through aws ecs
![Screenshot 2023-07-13 021348](https://github.com/jitsi/docker-jitsi-meet/assets/109200761/bfce2e43-cbbe-4c11-b541-ee6a1dd957e6)

**Comment by damencho** [comment]
You cannot use a webrtc app served on http location. Per browser specifications you need https.

**Comment by dvlpathak** [comment]
i don't know this app and i want to ask that it is complusory to use this app
i am using docker compose to create docker file and i push to aws ECR and then use ecs to run services

**Comment by damencho** [comment]
You cannot access your deployment using `http://ipaddress` you need to use `https://ipaddress`

**Comment by dvlpathak** [comment]
yes, i  also try that still the error comes.

**Comment by dvlpathak** [comment]
i also set the domain on that ip but still its not working.

**Comment by damencho** [comment]
Show the errors you get when using https.

**Comment by dvlpathak** [comment]
please see this is the error after i using https
![image](https://github.com/jitsi/docker-jitsi-meet/assets/109200761/7416b9fd-f8a0-411a-9f4f-8be176c970cf)

**Comment by damencho** [comment]
When you try to open the link how does it look like?
It should look like this: https://meet.jit.si/xmpp-websocket
Probably nginx that is fronting jitsi-meet has some misconfiguration.

**Comment by damencho** [comment]
Check your prosody logs for errors.

**Comment by dvlpathak** [comment]
> When you try to open the link how does it look like? It should look like this: https://meet.jit.si/xmpp-websocket Probably nginx that is fronting jitsi-meet has some misconfiguration.

![image](https://github.com/jitsi/docker-jitsi-meet/assets/109200761/cf83e572-4d96-42fa-9f29-2f4a76d08de0)
It should look like this

**Comment by damencho** [comment]
These are the instructions for proxing it: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#running-behind-a-reverse-proxy

**Comment by damencho** [comment]
I was talking about this link: https://rumournews.in/xmpp-websocket it returns 502 as you are not proxing it correctly. 
If you open the similar link on meet.jit.si you will see how it needs to look like.

**Comment by dvlpathak** [comment]
okay but i want to ask you that if there was anything change in aws ecs because if i change in conf file there will be no effect on ecs service so please tell me the changes that would done in ecs

**Comment by damencho** [comment]
I have no idea what is aws ecs and how it works and be configured. You need a websocket established to that address.

**Comment by dvlpathak** [comment]
so please tell me how it's works?

**Comment by damencho** [comment]
You need a websocket established to that address.  https://rumournews.in/xmpp-websocket  and when you open that address it must look like https://meet.jit.si/xmpp-websocket

**Comment by damencho** [comment]
In the nginx or apache where you are proxing the connections.

**Comment by dvlpathak** [comment]
> In the nginx or apache where you are proxing the connections.

we are running on nginx proxy connection and please tell me as i am fresher in this

**Comment by damencho** [comment]
Share your config from that nginx.
