### ISSUE TITLE
Multiple authentication methods

### ISSUE THREAD

**Issue by tikoflano** [jitsi/docker-jitsi-meet#158]
I'm interested on using Jitsi Meet and integrating it with my RocketChat instance. 

I don't want to allow public access so I set up LDAP authentication with guest access and it is working great but if I use LDAP authentication then when an user makes a call from RocketChat it asks for the credentials again (not ideal). 

On the other hand I can use JWT authentication, which worked great when making calls from RocketChat but now users can't create rooms from Jitse Meet Web.

Is there a way to enable both authentication methods? So when an user makes a call form RocketChat it doesn't ask for credentials while at the same time users can create rooms from Jitse Meet Web using their LDAP credentials?

**Comment by tikoflano** [comment]
When JWT authentication is enabled and a room is created, a username/password is shown. Maybe you could use the credentials given there to query the LDAP server and generate a JWT for that user.

Anyway, the username/password prompt mentioned before... is it checking the credentials against something? Or it is just a way to say that the user isn't authorized.

**Comment by saghul** [comment]
When JWT is used the user and password fields are really just an indication that authentication is needed.

As for the multiple authentication methods, I don't think Prosody (the XMPP server we use here) supports it.

**Comment by adolfombarros** [comment]
I have a RocketChat + Jitsi Meet implementation that work with JWT auth to create and login at the rooms.
I'd like to use LDAP auth as additional auth mode for users without rocketchat accounts.
Is this possible ??

**Comment by stepcellwolf** [comment]
For me, it is the other way around. I have an LDAP auth setup which works perfect, but would like to integrate with matrix and Nextcloud which requires a JWT auth. Is it possible?
