### ISSUE TITLE
Jitsi-meet with low video qulity( 360p )

### ISSUE THREAD

**Issue by limuzi2231** [jitsi/docker-jitsi-meet#1586]
hi, I installed jitsi-meet with docker. In the course of operation, when connecting to the video conference, the video display quality is very poor, only 360p or even lower (320x180). How to improve the video quality, 720p or 1080p is the best.

TIPS: the device I use is an Android phone with a camera above 1080p.

Thanks.

**Comment by saghul** [comment]
If you are using the Jitsi Meet app, it's currently limited to 360p.

**Comment by limuzi2231** [comment]
> If you are using the Jitsi Meet app, it's currently limited to 360p.

i tried with all jitsi meet app and mobile browser，but they both had poor video quality.
![image](https://github.com/jitsi/docker-jitsi-meet/assets/68209505/01d3354a-0460-427f-93db-78757ce37350)
this is by mobile browser.
![image](https://github.com/jitsi/docker-jitsi-meet/assets/68209505/066a991b-ad48-4f19-a090-6784d1676596)
this is by jitsi-meet app.

**Comment by saghul** [comment]
What do you mean by poor? As long as there is no packet loss (the first picture shows packet loss) you should get good quality video. Limited to 360p however.

**Comment by saghul** [comment]
Currently only the app is.

**Comment by limuzi2231** [comment]
> Currently only the app is.

Get.  Thanks.
