### ISSUE TITLE
Everyone is muted

### ISSUE THREAD

**Issue by tikoflano** [jitsi/docker-jitsi-meet#159]
When someone enters the room he is muted for me and I am muted for him. We both accepted the borwsers permissions and can see that or mic is up and running ok .But we can't hear each other.

I've tried adding DOCKER_HOST_ADDRESS with no luck.

**Comment by saghul** [comment]
What do you see in the JS console?

**Comment by tikoflano** [comment]
It says `Error: Rejecting session-initiate from non-focus` when the other participant connects. Then it says several times `Error: Strophe: TypeError: Cannot set property 'onicecandidate' of undefined`

**Comment by tikoflano** [comment]
It seems I was missing `JICOFO_AUTH_USER=focus` on the jitsi-web container. 

Sory for wasting your time.

**Comment by saghul** [comment]
No worries, good to know you got it working!

**Comment by bateradt** [comment]
Hello, sorry to reopen this issue, but i'm using iFrameAPI and using the server of jitsi (https://meet.jit.si) and this exactly error that occurs in my application. The console log shows the same error "UnhandledError: Rejecting session-initiate from non-focus." Can you help me?
