### ISSUE TITLE
Can't get moderator rights in a room without authentication.

### ISSUE THREAD

**Issue by ragnarblackmane** [jitsi/docker-jitsi-meet#1593]
I'm running Matrix, Element and Jitsi in docker. When I create a room I don't get moderator rights, this is what I get in the logs.

Prosody Log:
`
matrix-jitsi-prosody[1724]: 2023-08-29 19:35:25 muc.meet.jitsi:matrix_power_sync                             info        Setting focus@auth.meet.jitsi as owner of room roundpassagesrescuepromptly@muc.meet.jitsi based on Matrix power levels
`
(this happens 3 times)

Jicofo Log:
`
matrix-jitsi-jicofo[1868]: Jicofo 2023-08-29 19:34:31.329 INFO: [50] AutoOwnerRoleManager.electNewOwner$lambda-2#102: Electing new owner: ChatMember[id=0138785d role=PARTICIPANT]
matrix-jitsi-jicofo[1868]: Jicofo 2023-08-29 19:34:31.330 INFO: [49] [room=roundpassagesrescuepromptly@muc.meet.jitsi meeting_id=71e62af0-cd8b-4711-aea2-ff8eb3885849] JitsiMeetConferenceImpl.onMemberJoined#684: Member joined:0138785d stats-id=Deborah-bJN region=null audioMuted=true videoMuted=true role=PARTICIPANT isJibri=false isJigasi=false isTranscriber=false, room=main
matrix-jitsi-jicofo[1868]: Jicofo 2023-08-29 19:34:31.336 WARNING: [50] [room=roundpassagesrescuepromptly@muc.meet.jitsi meeting_id=71e62af0-cd8b-4711-aea2-ff8eb3885849] ChatRoomImpl.grantOwnership#313: Failed to grant ownership: <iq xmlns='jabber:client' to='focus@auth.meet.jitsi/focus' from='roundpassagesrescuepromptly@muc.meet.jitsi' id='VRARD-1243' type='error'><error type='modify'><not-acceptable xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></iq>
`

Last line is what I think is the error.

**Comment by damencho** [comment]
This seems like jicofo not being an admin.

**Comment by damencho** [comment]
Although I see it here:
https://github.com/jitsi/docker-jitsi-meet/blob/1cbb8f8cec9b29036cf6f24ebd087b8ea58958ee/prosody/rootfs/defaults/conf.d/jitsi-meet.cfg.lua#L62

Can you easily test by removing this from the prosody config: https://github.com/jitsi/docker-jitsi-meet/blob/1cbb8f8cec9b29036cf6f24ebd087b8ea58958ee/prosody/rootfs/defaults/prosody.cfg.lua#L33

**Comment by ragnarblackmane** [comment]
> Although I see it here:
> 
> https://github.com/jitsi/docker-jitsi-meet/blob/1cbb8f8cec9b29036cf6f24ebd087b8ea58958ee/prosody/rootfs/defaults/conf.d/jitsi-meet.cfg.lua#L62
> 
> Can you easily test by removing this from the prosody config:
> 
> https://github.com/jitsi/docker-jitsi-meet/blob/1cbb8f8cec9b29036cf6f24ebd087b8ea58958ee/prosody/rootfs/defaults/prosody.cfg.lua#L33

I just tried, I still have the same issue.
Also restarted everything and the removed setting came back.
Then tried to make the file immutable and read only to keep it without the removed line. Still same issue.

Just to be sure, is it right that in jitsi-meet.cfg.lua it's focus@auth.meet.jitsi
but in the error it's focus@auth.meet.jitsi/focus
?

focus@auth.meet.jitsi/focus

**Comment by damencho** [comment]
> So on prosody's side it seems that everything is ok.

Well, there is no log that jicofo is an admin.

Maybe in order to test it when you start the containers you need to edit the file, connect to the container and restart prosody.

**Comment by ragnarblackmane** [comment]
Just tried that. Still the same logs. But I'll follow this trail and try to find why jicofo doesn't get admin rights from prosody.

**Comment by ragnarblackmane** [comment]
FOUND THE ISSUE!
It was the  "matrix_power_sync" module. It was enabled (probably since I tested matrix user verification).
You pointed me the right way. Thank you!
