### ISSUE TITLE
updating docker-jitsi-meet

### ISSUE THREAD

**Issue by gmtdu** [jitsi/docker-jitsi-meet#1597]
The installation manual says:
Download and extract the latest release. DO NOT clone the git repository.

So I'm wondering what is the recommended way to do an update, since you can't just pull new changes like in a git repo.

should the new archive just be unpacked in the same directory and the files replaced?
What about customizations? Do these then have to be inserted each time again?

**Comment by Rassilion** [comment]
but why the "DO NOT clone" part? Whats the problem with checkouting release tag? and updating by checkouting latest release tag?

**Comment by saghul** [comment]
You can checkout a release tag, but I found that people generally just git clone and expect things to continue working, while that leads to having a mismatch between the compose file and the images.

**Comment by AnonymousWP** [comment]
@saghul 
Why is there no such documentation available? https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker/#quick-start is pretty basic and is only for getting started, not for updating. It's pretty confusing for me, as there are several ways as steps aren't explicit:

- Change the version numbers in the Docker Compose file (but then you only made modifications to the Docker Compose file, not other files that have been modified by a new release/update)
- Perform a `docker compose pull`, but that's not really useful as long as you have pinned versioning in your Docker Compose file
- Perform a `git pull`, but that's not recommended
- Probably some other ways too

Would be useful if some commands are provided for updating as well. You can put it in this issue, then I can open a PR if needed.

**Comment by saghul** [comment]
Bacause... we never got around writing it :-/



> * Change the version numbers in the Docker Compose file (but then you only made modifications to the Docker Compose file, not other files that have been modified by a new release/update)
> 
>     * Perform a `docker compose pull`, but that's not really useful as long as you have pinned versioning in your Docker Compose file
> 
>     * Perform a `git pull`, but that's not recommended
> 
>     * Probably some other ways too

None of those. The key is to get the new compose file, it's really the only thing that matters. It contains the list of env vars to be passed to each container (including new ones) and it pins the images to the specific release.

> Also: when performing an update, how do we make sure everything is still working? Asking because I can imagine that when you download the ZIP, environment variables have also been added.

Having new env vars is ok, we do use default values and strive for no-broken-updates. You don't need to set every env var in your .env file.



> But you don't want to lose those values of course, so how do you safely merge that for example? If you'd overwrite them, your config would be overwritten too, no? In case of the `.env` file for example.

The .env file is never overwritten, so your env vars are safe.

**Comment by AnonymousWP** [comment]
> None of those. The key is to get the new compose file, it's really the only thing that matters. It contains the list of env vars to be passed to each container (including new ones) and it pins the images to the specific release.

Yeah and how do you do that easily without having to rename the current Docker Compose file and *then* having to download the new one again from the repo using curl for example?

> Having new env vars is ok, we do use default values and strive for no-broken-updates. You don't need to set every env var in your .env file.

Alright, so what if there'll be a new setting I'd like to use but isn't in my current setup? I'll have to do a lot of copy-pasting to ensure my current config isn't lost. Yeah, we don't really use a lot of environment variables, but you never know. Perhaps in the future.

**Comment by saghul** [comment]
> Yeah and how do you do that easily without having to rename the current Docker Compose file and _then_ having to download the new one again from the repo using curl for example?

You should just overwrite the compose file you have. All env vars should go on the .env file, there are very few reasons to modify the compose file. If are doing that I expect you to be proficient enough to do the update.



> Alright, so what if there'll be a new setting I'd like to use but isn't in my current setup? I'll have to do a lot of copy-pasting to ensure my current config isn't lost. Yeah, we don't really use a lot of environment variables, but you never know. Perhaps in the future.

There is nothing to copy and paste. You just add the new env var to your .env and restart the containers with the new images.

**Comment by AnonymousWP** [comment]
> > Yeah and how do you do that easily without having to rename the current Docker Compose file and _then_ having to download the new one again from the repo using curl for example?
> 
> You should just overwrite the compose file you have. All env vars should go on the .env file, there are very few reasons to modify the compose file. If are doing that I expect you to be proficient enough to do the update.
> 
> > Alright, so what if there'll be a new setting I'd like to use but isn't in my current setup? I'll have to do a lot of copy-pasting to ensure my current config isn't lost. Yeah, we don't really use a lot of environment variables, but you never know. Perhaps in the future.
> 
> There is nothing to copy and paste. You just add the new env var to your .env and restart the containers with the new images.

This doesn't cost too much time to write for documentation, I assume? It just sounds a bit overcomplicated with how other applications are updated via Docker in my opinion.

Do you plan on writing documentation if you find the time? If not, I can see if I can come up with some documentation.

**Comment by saghul** [comment]
If you can come up with some text I'll be happy to review it.

**Comment by Irfan-Ali-14** [comment]
Hi, there is no final solution at this point also. Are we still following the same step? like replacing .env and docker-compose file on each update? As I have had made some changes to docker-compose file as well. This is so complicated by the way.
