### ISSUE TITLE
Authentication mode internal

### ISSUE THREAD

**Issue by alisalemeniso** [jitsi/docker-jitsi-meet#160]
Hello fellow Jitsiers,
So I wanted to test the internal mode of Authentication: I followed the readMe docs:
`docker-compose exec prosody /bin/bash`
then `prosodyctl --config /config/prosody.cfg.lua register username.exemple myHost` the I put the password, but it returns 

> The given username is invalid in a Jabber ID

can anyone explains for me why ?
Thanks !

**Comment by saghul** [comment]
Maybe the dot is not supported? have you tried just with "user" (no quotes)

**Comment by alisalemeniso** [comment]
thanks @saghul for the reply, you are right: now when I tried with a username without the dot, the returned message have changed for this:

> The given hostname does not exist in the config

I'm running the project on my localhost FYI with the basic provided conf.
What should I do ?

**Comment by saghul** [comment]
then the host is meet.jitsi

**Comment by alisalemeniso** [comment]
So how can I change it to my host and add users and test this authentication mode (I suppose I can't add users on meet.jitsi host)

**Comment by saghul** [comment]
You can add users to the meet.jitsi host. In fact they don't need to write the domain since it's the default anyway.

**Comment by adriavidal** [comment]
trying to setup these way, but after web ask for user/pw get all the time a message "someting goes wrong, trying to fix, reconnecting" any tip about where find more info?

**Comment by lucrus73** [comment]
> trying to setup these way, but after web ask for user/pw get all the time a message "someting goes wrong, trying to fix, reconnecting" any tip about where find more info?

Most probably this is a different problem (just google for it, first of all double check that your server UDP port 10000 is reachable from the internet).

**Comment by filwu8** [comment]
> Hello fellow Jitsiers, So I wanted to test the internal mode of Authentication: I followed the readMe docs: `docker-compose exec prosody /bin/bash` then `prosodyctl --config /config/prosody.cfg.lua register username.exemple myHost` the I put the password, but it returns
> 
> > The given username is invalid in a Jabber ID
> 
> can anyone explains for me why ? Thanks !

look here，if you copy from Rich Text Editor ？

![企业微信截图_17109906556023](https://github.com/jitsi/docker-jitsi-meet/assets/54697960/b2a4b3fe-0a21-480b-adeb-0828ae23ae84)
