### ISSUE TITLE
Welcome page

### ISSUE THREAD

**Issue by JMonteiro01** [jitsi/docker-jitsi-meet#1604]
Hello guys, 

I am trying to disable the welcome page editing the following file: docker-jitsi-meet-stable-8922-1/web/rootfs/defaults/settings-config.js

{{ $ENABLE_WELCOME_PAGE := .Env.ENABLE_WELCOME_PAGE | default "true" | toBool -}}

// Welcome page.
config.enableWelcomePage = {{ $ENABLE_WELCOME_PAGE }};

**I changed to:**

{{ $DISABLE_WELCOME_PAGE := .Env.DISABLE_WELCOME_PAGE | default "false" | toBool -}}

// Welcome page.
config.disableWelcomePage = {{ $DISABLE_WELCOME_PAGE }};

Thanks in advance!

**Comment by zafer-guler** [comment]
Self-Hosted Jitsi Meet: For self-hosted Jitsi, you can configure it to skip the welcome page and go directly to a specific room.

In the interface_config.js file (usually located in /usr/share/jitsi-meet or the equivalent path on your server), you can add or modify the following setting:


DEFAULT_WELCOME_PAGE_ENABLED: false,
This disables the welcome page, so users who access your Jitsi Meet URL (e.g., https://your-jitsi-domain) will be prompted to join or create a meeting room directly.
