### ISSUE TITLE
Empty `jibri.conf`

### ISSUE THREAD

**Issue by ribeaud** [jitsi/docker-jitsi-meet#1607]
I think there is a problem with **jibri** in the latest version (`stable-8960`). `docker exec jitsi-jibri-1 cat /etc/jitsi/jibri/jibri.conf` returns an empty string on my end. This was NOT the case with the previous version.

I am not an expert here but I would guess that `jibri.conf` generation does not work anymore. And [this](https://github.com/jitsi/docker-jitsi-meet/commit/5c5575cd89370711d97c3d313f784fa89a05338f) could be the culprit commit... 😶

Could this be related to missing double quotes (again, not an expert and just tossing some theories around)?

Did I miss something? Could someone please infirm or confirm this thesis?

**Comment by saghul** [comment]
Can you check the logs of the Jibri container?

**Comment by ribeaud** [comment]
Hi. I attached the [logs](https://github.com/jitsi/docker-jitsi-meet/files/12697122/logs.txt). Do you see something?

**Comment by saghul** [comment]
panic: unable to parse template file: template: /defaults/jibri.conf:7: bad character U+0024 '$'

This is what's broken. I'll fix it now and make a new release.

**Comment by ribeaud** [comment]
I could test the release. I see the problem now: `.Env.$JIBRI_RECORDING_FRAMERATE` instead of `.Env.JIBRI_RECORDING_FRAMERATE`. Wouah, tricky, tricky, ... Sorry for the inconvenience. And thanks for the quick fix.

**Comment by ribeaud** [comment]
Will test now.

**Comment by ribeaud** [comment]
Works like a charm. Thank you!
