### ISSUE TITLE
Jitsi network

### ISSUE THREAD

**Issue by gaurishsharma** [jitsi/docker-jitsi-meet#161]
I have done custom installation of Jitsi on my local server.

I am trying to setup a reverse proxy through nginx-proxy (https://github.com/jwilder/nginx-proxy) that is running on docker network ('nginx-proxy'). 

Now in order to have reverse proxy working, I need to have Jitsi container running on the same network (i.e. nginx-proxy), I have updated Jitsi containers to be associated to nginx-proxy network along with  existing entry of meet.jitsi like below.

`
version: '3'

services:

    # Frontend
    web:
        image: jitsi/web
        ports:
            - '${HTTP_PORT}:80'
            - '${HTTPS_PORT}:443'
        expose:
            - '80'
        volumes:
            - ${CONFIG}/web:/config
            - ${CONFIG}/web/letsencrypt:/etc/letsencrypt
            - ${CONFIG}/transcripts:/usr/share/jitsi-meet/transcripts
        environment:
            - VIRTUAL_HOST=abc.mydomain.com.com
            - VIRTUAL_PORT=80
            - LETSENCRYPT_HOST=abc.mydomain.com.com
            - ENABLE_AUTH
            - ENABLE_GUESTS
            - ENABLE_LETSENCRYPT
            - ENABLE_HTTP_REDIRECT
            - ENABLE_TRANSCRIPTIONS
            - DISABLE_HTTPS
            - JICOFO_AUTH_USER
            - LETSENCRYPT_DOMAIN
            - LETSENCRYPT_EMAIL=xyz@mydomain.com
            - PUBLIC_URL
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_BOSH_URL_BASE
            - XMPP_GUEST_DOMAIN
            - XMPP_MUC_DOMAIN
            - ETHERPAD_URL_BASE
            - TZ
        networks:
            nginx-proxy:
            meet.jitsi:

    # XMPP server
    prosody:
        image: jitsi/prosody
        expose:
            - '5222'
            - '5347'
            - '5280'
        volumes:
            - ${CONFIG}/prosody:/config
        environment:
            - AUTH_TYPE
            - ENABLE_AUTH
            - ENABLE_GUESTS
            - GLOBAL_MODULES
            - GLOBAL_CONFIG
            - LDAP_URL
            - LDAP_BASE
            - LDAP_BINDDN
            - LDAP_BINDPW
            - LDAP_FILTER
            - LDAP_AUTH_METHOD
            - LDAP_VERSION
            - LDAP_USE_TLS
            - LDAP_TLS_CIPHERS
            - LDAP_TLS_CHECK_PEER
            - LDAP_TLS_CACERT_FILE
            - LDAP_TLS_CACERT_DIR
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_GUEST_DOMAIN
            - XMPP_MUC_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_MODULES
            - XMPP_MUC_MODULES
            - XMPP_INTERNAL_MUC_MODULES
            - JICOFO_COMPONENT_SECRET
            - JICOFO_AUTH_USER
            - JICOFO_AUTH_PASSWORD
            - JVB_AUTH_USER
            - JVB_AUTH_PASSWORD
            - JIGASI_XMPP_USER
            - JIGASI_XMPP_PASSWORD
            - JWT_APP_ID
            - JWT_APP_SECRET
            - JWT_ACCEPTED_ISSUERS
            - JWT_ACCEPTED_AUDIENCES
            - JWT_ASAP_KEYSERVER
            - JWT_ALLOW_EMPTY
            - JWT_AUTH_TYPE
            - JWT_TOKEN_AUTH_MODULE
            - LOG_LEVEL
            - TZ
        networks:
            nginx-proxy:
            meet.jitsi:
                aliases:
                    - ${XMPP_SERVER}

    # Focus component
    jicofo:
        image: jitsi/jicofo
        volumes:
            - ${CONFIG}/jicofo:/config
        environment:
            - ENABLE_AUTH
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_SERVER
            - JICOFO_COMPONENT_SECRET
            - JICOFO_AUTH_USER
            - JICOFO_AUTH_PASSWORD
            - JVB_BREWERY_MUC
            - JIGASI_BREWERY_MUC
            - TZ
        depends_on:
            - prosody
        networks:
            nginx-proxy:
            meet.jitsi:

    # Video bridge
    jvb:
        image: jitsi/jvb
        ports:
            - '${JVB_PORT}:${JVB_PORT}/udp'
            - '${JVB_TCP_PORT}:${JVB_TCP_PORT}'
        volumes:
            - ${CONFIG}/jvb:/config
        environment:
            - DOCKER_HOST_ADDRESS
            - XMPP_AUTH_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_SERVER
            - JVB_AUTH_USER
            - JVB_AUTH_PASSWORD
            - JVB_BREWERY_MUC
            - JVB_PORT
            - JVB_TCP_HARVESTER_DISABLED
            - JVB_TCP_PORT
            - JVB_STUN_SERVERS
            - JVB_ENABLE_APIS
            - JICOFO_AUTH_USER
            - TZ
        depends_on:
            - prosody
        networks:
            nginx-proxy:
            meet.jitsi:

` 

But when I execute docker-compose up -d and check the networks through

`docker inspect --format='{{json .NetworkSettings.Networks}}' d4fdc33e1395`

I get:

```
{"docker-jitsi-meet_meet.jitsi":{"IPAMConfig":null,"Links":null,"Aliases":["d4fdc33e1395","web"],"NetworkID":"261a6c886e158e45b200b74c1208d474d0ae0247923a6efb80de44994b 288d88","EndpointID":"692af6c4160090204d069c5d412b68f6013d6136f625b1de935bfb884e7e85","Gateway":"172.20.0.1","IPAddress":"172.20.0.3","IPPrefixLen":16,"IPv6Gateway":" ","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:14:00:03","DriverOpts":null}
,"**docker-jitsi-meet_nginx-proxy**":{"IPAMConfig":null,"Links":null,"Alia ses":["d4fdc33e1395","web"],"NetworkID":"2903b540335d001202dff379bf9ed6eed43cc9268d944495bc97e2e9e274b46f","EndpointID":"987a64bd771227b41bacf008a89f57cfbdea74b3504cf58 6092e38b1ca10cfb3","Gateway":"172.24.0.1","IPAddress":"172.24.0.3","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42: ac:18:00:03","DriverOpts":null}}

```
Note, that 2 networks get added : docker-jitsi-meet_meet.jitsi and docker-jitsi-meet_nginx-proxy

While, for nginx-proxy docker container, the network we get is nginx-proxy :

`{"nginx-proxy":{"IPAMConfig":null,"Links":null,"Aliases":["c214236f6be9","nginx"],"NetworkID":"4a1a4e289a6f0b2cdd1b64e2a85d296a063766a93462a6f876b8fdcdb75af207","Endpoint ID":"d57b15fc0b8b828495ca654131ccfccf3040f8619075380324565172ef3b0daf","Gateway":"172.25.0.1","IPAddress":"172.25.0.5","IPPrefixLen":16,"IPv6Gateway":"","GlobalIPv6Addr ess":"","GlobalIPv6PrefixLen":0,"MacAddress":"02:42:ac:19:00:05","DriverOpts":null}}`

Jitsi adds **docker-jitsi-meet_** (docker-jitsi-meet_nginx-proxy) ahead of the desired network name (i.e. nginx-proxy) and adds a new network instead of associating with the nginx-proxy network

How can I enable Jitsi to connect to existing docker network instead of creating new?

Thanks,
Gaurish

**Comment by saghul** [comment]
What exactly are you trying to setup? Why do you need the reverse proxy?

As for the network thing, I don't know.

**Comment by gaurishsharma** [comment]
I am hosting services, web of my application and Jitsi as separate docker containers on a single server. Nginx-proxy is listening to requests on 80 and 443 and redirecting the request to appropriate container as per sub domain defined in the VIRTUAL_HOST setting in docker-compose.yml

**Comment by saghul** [comment]
I think you need to configure the nginx-proxy network as external. See https://docs.docker.com/compose/networking/ (the "Use a pre-existing network" section)

**Comment by gaurishsharma** [comment]
Thanks for your inputs, let me try that.

**Comment by gaurishsharma** [comment]
It worked, thanks. Closing it.

**Comment by JesHansen** [comment]
@gaurishsharma Can you post the configuration that worked for you?
Using
```
# Custom network so all services can communicate using a FQDN
networks:
    meet.jitsi:
    external:
        name: nginx-proxy:

```
results in 
ERROR: yaml.scanner.ScannerError: mapping values are not allowed here
  in "./docker-compose.yml", line 174, column 26

**Comment by gaurishsharma** [comment]
@JesHansen I just added the following and it worked

networks:
  meet.jitsi:
  nginx-proxy:

Can you please try the same?

**Comment by Jsalim** [comment]
@gaurishsharma Could you share your yaml, please. 
Facing the same problem.

Thanks
