### ISSUE TITLE
Deploy docker-jitsi-meet and jibri on different servers will cause an error RemoteConnectionEndpointLookupFailure

### ISSUE THREAD

**Issue by UTF0731** [jitsi/docker-jitsi-meet#1618]
my jibri docker env,192.168.31.177 is my docker-jitsi-meet ip.
```
XMPP_DOMAIN=192.168.31.177
XMPP_SERVER=xmpp.192.168.31.177
XMPP_BOSH_URL_BASE=http://xmpp.192.168.31.177:5280
XMPP_AUTH_DOMAIN=auth.192.168.31.177
XMPP_MUC_DOMAIN=muc.192.168.31.177
XMPP_INTERNAL_MUC_DOMAIN=internal-muc.192.168.31.177
XMPP_GUEST_DOMAIN=guest.192.168.31.177
XMPP_RECORDER_DOMAIN=recorder.192.168.31.177
```
when I start jibri docker,Jibri will encounter the following errors:
```
Jibri 2023-10-06 18:22:44.654 WARNING: [33] [hostname=xmpp.192.168.31.177 id=xmpp.192.168.31.177] 
MucClient.lambda$getConnectAndLoginCallable$9#631: Error connecting:
org.jivesoftware.smack.SmackException$EndpointConnectionException: 
Could not lookup the following endpoints: RemoteConnectionEndpointLookupFailure(
description='DNS lookup exception for xmpp.192.168.31.177' exception='java.net.UnknownHostException: 
xmpp.192.168.31.177: Name or service not known')
```
How can I fix this, or is there another way to deploy jibri on different servers？

**Comment by saghul** [comment]
You need to have a user defined network to connect them.

Docker Swarm could be one way or k8s, etc.

**Comment by UTF0731** [comment]
> You need to have a user defined network to connect them.
> 
> Docker Swarm could be one way or k8s, etc.

K8s is too complex, and I'm working on a simple project using Jitsi with only two servers. I've tried Docker Swarm, but it didn't work. Do you have any information on implementing this functionality with Docker Swarm that I can take a look at?

**Comment by saghul** [comment]
What didn't work?

**Comment by UTF0731** [comment]
@saghul thank you guy, I have solved the problem
