### ISSUE TITLE
jitsi connection problem

### ISSUE THREAD

**Issue by Zell40** [jitsi/docker-jitsi-meet#1619]
hello.

I can't create a meeting with jitsi. I installed then configured jitsi-docker. I'm running Ubuntu with Apache2 as a web server. I can access the jisti login page but when I create a meeting, I am immediately disconnected. Could anyone help me on this? THANKS ;)

![image](https://github.com/jitsi/docker-jitsi-meet/assets/77941996/034f9548-b50c-4c6f-8262-2e34f89a1085)

[http://pastebin.fr/131503](http://pastebin.fr/131503)

PS: Sorry for the translation, I'm French

**Comment by kunimasu** [comment]
Do you have WebSocket error in browser console?

**Comment by Zell40** [comment]
FIREFOX:

GET | wss://visio.reseau-entrenous.fr/xmpp-websocket?room=test

</span>
</body>
</html>GET
wss://visio.reseau-entrenous.fr/xmpp-websocket?room=test

	
GET
	wss://visio.reseau-entrenous.fr/xmpp-websocket?room=test
État
400
Bad Request
VersionHTTP/1.1
Transfert211 o (taille 0 o)
Résolution DNSSystème

	
Connection
	close
Content-Type
	text/html; charset=utf8
Date
	Fri, 13 Oct 2023 07:18:16 GMT
Server
	nginx
Strict-Transport-Security
	max-age=63072000
Transfer-Encoding
	chunked
	
Accept
	*/*
Accept-Encoding
	gzip, deflate, br
Accept-Language
	fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Cache-Control
	no-cache
Connection
	keep-alive, Upgrade
Host
	visio.reseau-entrenous.fr
Origin
	https://visio.reseau-entrenous.fr/
Pragma
	no-cache
Sec-Fetch-Dest
	empty
Sec-Fetch-Mode
	websocket
Sec-Fetch-Site
	same-origin
Sec-WebSocket-Extensions
	permessage-deflate
Sec-WebSocket-Key
	eqFMtoGFQVRYonAKOEWVmA==
Sec-WebSocket-Protocol
	xmpp
Sec-WebSocket-Version
	13
Upgrade
	websocket
User-Agent
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0

EDGE
strophe.umd.js:5779  WebSocket connection to 'wss://visio.reseau-entrenous.fr/xmpp-websocket?room=test' failed: 
_connect @ strophe.umd.js:5779
connect @ strophe.umd.js:3040
_interceptConnectArgs @ strophe.stream-management.js:224
connect @ XmppConnection.js:273
_connect @ xmpp.js:598
connect @ xmpp.js:702
Ku.connect @ JitsiConnection.js:73
(anonymous) @ actions.any.ts:225
(anonymous) @ actions.any.ts:147
(anonymous) @ index.js:16
(anonymous) @ middleware.ts:20
(anonymous) @ middleware.ts:29
(anonymous) @ middleware.ts:19
(anonymous) @ middleware.ts:14
(anonymous) @ middleware.web.ts:23
(anonymous) @ middleware.any.ts:33
(anonymous) @ middleware.ts:63
(anonymous) @ middleware.ts:48
(anonymous) @ middleware.ts:60
(anonymous) @ middleware.ts:102
(anonymous) @ middleware.ts:50
(anonymous) @ middleware.ts:46
(anonymous) @ middleware.ts:28
(anonymous) @ middleware.ts:155
(anonymous) @ middleware.ts:44
(anonymous) @ middleware.ts:22
(anonymous) @ middleware.ts:52
(anonymous) @ middleware.ts:50
(anonymous) @ middleware.web.ts:35
(anonymous) @ middleware.web.ts:19
(anonymous) @ middleware.any.ts:52
(anonymous) @ middleware.ts:60
(anonymous) @ middleware.web.ts:273
(anonymous) @ middleware.ts:39
(anonymous) @ middleware.ts:21
(anonymous) @ middleware.ts:11
(anonymous) @ middleware.ts:16
(anonymous) @ middleware.ts:18
(anonymous) @ middleware.web.ts:24
(anonymous) @ middleware.any.ts:35
(anonymous) @ middleware.ts:12
(anonymous) @ middleware.ts:83
(anonymous) @ middleware.ts:26
(anonymous) @ middleware.web.ts:90
(anonymous) @ middleware.any.ts:83
(anonymous) @ middleware.ts:27
(anonymous) @ middleware.web.ts:17
(anonymous) @ middleware.any.ts:19
(anonymous) @ middleware.web.ts:17
(anonymous) @ middleware.any.ts:18
(anonymous) @ middleware.ts:32
(anonymous) @ middleware.web.ts:15
(anonymous) @ middleware.ts:254
(anonymous) @ middleware.ts:15
(anonymous) @ middleware.ts:36
(anonymous) @ middleware.ts:38
(anonymous) @ middleware.ts:65
(anonymous) @ middleware.ts:8
(anonymous) @ middleware.ts:29
(anonymous) @ middleware.ts:20
(anonymous) @ middleware.web.ts:105
(anonymous) @ middleware.any.ts:71
(anonymous) @ middleware.ts:42
(anonymous) @ middleware.ts:152
(anonymous) @ middleware.ts:160
(anonymous) @ middleware.ts:87
(anonymous) @ middleware.ts:82
(anonymous) @ middleware.any.ts:38
(anonymous) @ middleware.ts:35
(anonymous) @ middleware.web.ts:28
(anonymous) @ middleware.ts:18
(anonymous) @ middleware.web.ts:10
(anonymous) @ middleware.ts:28
(anonymous) @ middleware.web.ts:28
(anonymous) @ middleware.any.ts:108
(anonymous) @ middleware.ts:13
(anonymous) @ middleware.ts:73
(anonymous) @ middleware.web.ts:61
(anonymous) @ middleware.ts:9
(anonymous) @ middleware.tsx:13
(anonymous) @ middleware.ts:12
(anonymous) @ middleware.ts:135
(anonymous) @ middleware.tsx:17
(anonymous) @ middleware.ts:31
(anonymous) @ middleware.ts:55
(anonymous) @ middleware.ts:102
(anonymous) @ middleware.web.ts:20
(anonymous) @ middleware.any.ts:22
(anonymous) @ middleware.web.ts:35
(anonymous) @ middleware.any.ts:100
(anonymous) @ middleware.web.ts:170
(anonymous) @ middleware.ts:33
(anonymous) @ middleware.web.ts:22
(anonymous) @ middleware.ts:141
dispatch @ redux.js:636
(anonymous) @ actions.web.ts:43
(anonymous) @ index.js:16
(anonymous) @ middleware.ts:20
(anonymous) @ middleware.ts:29
(anonymous) @ middleware.ts:19
(anonymous) @ middleware.ts:14
(anonymous) @ middleware.web.ts:23
(anonymous) @ middleware.any.ts:33
(anonymous) @ middleware.ts:63
(anonymous) @ middleware.ts:48
(anonymous) @ middleware.ts:60
(anonymous) @ middleware.ts:102
(anonymous) @ middleware.ts:50
(anonymous) @ middleware.ts:46
(anonymous) @ middleware.ts:28
(anonymous) @ middleware.ts:155
(anonymous) @ middleware.ts:44
(anonymous) @ middleware.ts:22
(anonymous) @ middleware.ts:52
(anonymous) @ middleware.ts:50
(anonymous) @ middleware.web.ts:35
(anonymous) @ middleware.web.ts:19
(anonymous) @ middleware.any.ts:52
(anonymous) @ middleware.ts:60
(anonymous) @ middleware.web.ts:273
(anonymous) @ middleware.ts:39
(anonymous) @ middleware.ts:21
(anonymous) @ middleware.ts:11
(anonymous) @ middleware.ts:16
(anonymous) @ middleware.ts:18
(anonymous) @ middleware.web.ts:24
(anonymous) @ middleware.any.ts:35
(anonymous) @ middleware.ts:12
(anonymous) @ middleware.ts:83
(anonymous) @ middleware.ts:26
(anonymous) @ middleware.web.ts:90
(anonymous) @ middleware.any.ts:83
(anonymous) @ middleware.ts:27
(anonymous) @ middleware.web.ts:17
(anonymous) @ middleware.any.ts:19
(anonymous) @ middleware.web.ts:17
(anonymous) @ middleware.any.ts:18
(anonymous) @ middleware.ts:32
(anonymous) @ middleware.web.ts:15
(anonymous) @ middleware.ts:254
(anonymous) @ middleware.ts:15
(anonymous) @ middleware.ts:36
(anonymous) @ middleware.ts:38
(anonymous) @ middleware.ts:65
(anonymous) @ middleware.ts:8
(anonymous) @ middleware.ts:29
(anonymous) @ middleware.ts:20
(anonymous) @ middleware.web.ts:105
(anonymous) @ middleware.any.ts:71
(anonymous) @ middleware.ts:42
(anonymous) @ middleware.ts:152
(anonymous) @ middleware.ts:160
(anonymous) @ middleware.ts:87
(anonymous) @ middleware.ts:82
(anonymous) @ middleware.any.ts:38
(anonymous) @ middleware.ts:35
(anonymous) @ middleware.web.ts:28
(anonymous) @ middleware.ts:18
(anonymous) @ middleware.web.ts:10
(anonymous) @ middleware.ts:28
(anonymous) @ middleware.web.ts:28
(anonymous) @ middleware.any.ts:108
(anonymous) @ middleware.ts:13
(anonymous) @ middleware.ts:73
(anonymous) @ middleware.web.ts:61
(anonymous) @ middleware.ts:9
(anonymous) @ middleware.tsx:13
(anonymous) @ middleware.ts:12
(anonymous) @ middleware.ts:135
(anonymous) @ middleware.tsx:17
(anonymous) @ middleware.ts:31
(anonymous) @ middleware.ts:55
(anonymous) @ middleware.ts:102
(anonymous) @ middleware.web.ts:20
(anonymous) @ middleware.any.ts:22
(anonymous) @ middleware.web.ts:35
(anonymous) @ middleware.any.ts:100
(anonymous) @ middleware.web.ts:170
(anonymous) @ middleware.ts:33
(anonymous) @ middleware.web.ts:22
(anonymous) @ middleware.ts:141
dispatch @ redux.js:636
(anonymous) @ actions.web.ts:177
(anonymous) @ index.js:16
(anonymous) @ middleware.ts:20
(anonymous) @ middleware.ts:29
(anonymous) @ middleware.ts:19
(anonymous) @ middleware.ts:14
(anonymous) @ middleware.web.ts:23
(anonymous) @ middleware.any.ts:33
(anonymous) @ middleware.ts:63
(anonymous) @ middleware.ts:48
(anonymous) @ middleware.ts:60
(anonymous) @ middleware.ts:102
(anonymous) @ middleware.ts:50
(anonymous) @ middleware.ts:46
(anonymous) @ middleware.ts:28
(anonymous) @ middleware.ts:155
(anonymous) @ middleware.ts:44
(anonymous) @ middleware.ts:22
Logger.js:155  2023-10-13T07:20:29.267Z [JitsiMeetJS.ts] <Object.getGlobalOnErrorHandler>:  UnhandledError: Strophe: Websocket error {"isTrusted":true} Script: null Line: null Column: null StackTrace:  Error: Strophe: Websocket error {"isTrusted":true}
    at Da.St.Strophe.log (https://visio.reseau-entrenous.fr/libs/lib-jitsi-meet.min.js?v=7531:2:821513)
    at Object.error (https://visio.reseau-entrenous.fr/libs/lib-jitsi-meet.min.js?v=7531:2:500190)
    at F.Websocket._onError (https://visio.reseau-entrenous.fr/libs/lib-jitsi-meet.min.js?v=7531:2:538003)
    at socket.onerror (https://visio.reseau-entrenous.fr/libs/lib-jitsi-meet.min.js?v=7531:2:534981)
r @ Logger.js:155
getGlobalOnErrorHandler @ JitsiMeetJS.ts:533
window.onerror @ middleware.ts:84
callErrorHandler @ GlobalOnErrorHandler.js:61
Da.St.Strophe.log @ strophe.util.js:88
error @ strophe.umd.js:2020
_onError @ strophe.umd.js:6079
socket.onerror @ strophe.umd.js:5783
error (asynchrone)
_connect @ strophe.umd.js:5783
connect @ strophe.umd.js:3040
_interceptConnectArgs @ strophe.stream-management.js:224
connect @ XmppConnection.js:273
_connect @ xmpp.js:598
connect @ xmpp.js:702
Ku.connect @ JitsiConnection.js:73
(anonymous) @ actions.any.ts:225
(anonymous) @ actions.any.ts:147
(anonymous) @ index.js:16
(anonymous) @ middleware.ts:20
(anonymous) @ middleware.ts:29
(anonymous) @ middleware.ts:19
(anonymous) @ middleware.ts:14
(anonymous) @ middleware.web.ts:23
(anonymous) @ middleware.any.ts:33
(anonymous) @ middleware.ts:63
(anonymous) @ middleware.ts:48
(anonymous) @ middleware.ts:60
(anonymous) @ middleware.ts:102
(anonymous) @ middleware.ts:50
(anonymous) @ middleware.ts:46
(anonymous) @ middleware.ts:28
(anonymous) @ middleware.ts:155
(anonymous) @ middleware.ts:44
(anonymous) @ middleware.ts:22
(anonymous) @ middleware.ts:52
(anonymous) @ middleware.ts:50
(anonymous) @ middleware.web.ts:35
(anonymous) @ middleware.web.ts:19
(anonymous) @ middleware.any.ts:52
(anonymous) @ middleware.ts:60
(anonymous) @ middleware.web.ts:273
(anonymous) @ middleware.ts:39
(anonymous) @ middleware.ts:21
(anonymous) @ middleware.ts:11
(anonymous) @ middleware.ts:16
(anonymous) @ middleware.ts:18
(anonymous) @ middleware.web.ts:24
(anonymous) @ middleware.any.ts:35
(anonymous) @ middleware.ts:12
(anonymous) @ middleware.ts:83
(anonymous) @ middleware.ts:26
(anonymous) @ middleware.web.ts:90
(anonymous) @ middleware.any.ts:83
(anonymous) @ middleware.ts:27
(anonymous) @ middleware.web.ts:17
(anonymous) @ middleware.any.ts:19
(anonymous) @ middleware.web.ts:17
(anonymous) @ middleware.any.ts:18
(anonymous) @ middleware.ts:32
(anonymous) @ middleware.web.ts:15
(anonymous) @ middleware.ts:254
(anonymous) @ middleware.ts:15
(anonymous) @ middleware.ts:36
(anonymous) @ middleware.ts:38
(anonymous) @ middleware.ts:65
(anonymous) @ middleware.ts:8
(anonymous) @ middleware.ts:29
(anonymous) @ middleware.ts:20
(anonymous) @ middleware.web.ts:105
(anonymous) @ middleware.any.ts:71
(anonymous) @ middleware.ts:42
(anonymous) @ middleware.ts:152
(anonymous) @ middleware.ts:160
(anonymous) @ middleware.ts:87
(anonymous) @ middleware.ts:82
(anonymous) @ middleware.any.ts:38
(anonymous) @ middleware.ts:35
(anonymous) @ middleware.web.ts:28
(anonymous) @ middleware.ts:18
(anonymous) @ middleware.web.ts:10
(anonymous) @ middleware.ts:28
(anonymous) @ middleware.web.ts:28
(anonymous) @ middleware.any.ts:108
(anonymous) @ middleware.ts:13
(anonymous) @ middleware.ts:73
(anonymous) @ middleware.web.ts:61
(anonymous) @ middleware.ts:9
(anonymous) @ middleware.tsx:13
(anonymous) @ middleware.ts:12
(anonymous) @ middleware.ts:135
(anonymous) @ middleware.tsx:17
(anonymous) @ middleware.ts:31
(anonymous) @ middleware.ts:55
(anonymous) @ middleware.ts:102
(anonymous) @ middleware.web.ts:20
(anonymous) @ middleware.any.ts:22
(anonymous) @ middleware.web.ts:35
(anonymous) @ middleware.any.ts:100
(anonymous) @ middleware.web.ts:170
(anonymous) @ middleware.ts:33
(anonymous) @ middleware.web.ts:22
(anonymous) @ middleware.ts:141
dispatch @ redux.js:636
(anonymous) @ actions.web.ts:43
(anonymous) @ index.js:16
(anonymous) @ middleware.ts:20
(anonymous) @ middleware.ts:29
(anonymous) @ middleware.ts:19
(anonymous) @ middleware.ts:14
(anonymous) @ middleware.web.ts:23
(anonymous) @ middleware.any.ts:33
(anonymous) @ middleware.ts:63
(anonymous) @ middleware.ts:48
(anonymous) @ middleware.ts:60
(anonymous) @ middleware.ts:102
(anonymous) @ middleware.ts:50
(anonymous) @ middleware.ts:46
(anonymous) @ middleware.ts:28
(anonymous) @ middleware.ts:155
(anonymous) @ middleware.ts:44
(anonymous) @ middleware.ts:22
(anonymous) @ middleware.ts:52
(anonymous) @ middleware.ts:50
(anonymous) @ middleware.web.ts:35
(anonymous) @ middleware.web.ts:19
(anonymous) @ middleware.any.ts:52
(anonymous) @ middleware.ts:60
(anonymous) @ middleware.web.ts:273
(anonymous) @ middleware.ts:39
(anonymous) @ middleware.ts:21
(anonymous) @ middleware.ts:11
(anonymous) @ middleware.ts:16
(anonymous) @ middleware.ts:18
(anonymous) @ middleware.web.ts:24
(anonymous) @ middleware.any.ts:35
(anonymous) @ middleware.ts:12
(anonymous) @ middleware.ts:83
(anonymous) @ middleware.ts:26
(anonymous) @ middleware.web.ts:90
(anonymous) @ middleware.any.ts:83
(anonymous) @ middleware.ts:27
(anonymous) @ middleware.web.ts:17
(anonymous) @ middleware.any.ts:19
(anonymous) @ middleware.web.ts:17
(anonymous) @ middleware.any.ts:18
(anonymous) @ middleware.ts:32
(anonymous) @ middleware.web.ts:15
(anonymous) @ middleware.ts:254
(anonymous) @ middleware.ts:15
(anonymous) @ middleware.ts:36
(anonymous) @ middleware.ts:38
(anonymous) @ middleware.ts:65
(anonymous) @ middleware.ts:8
(anonymous) @ middleware.ts:29
(anonymous) @ middleware.ts:20
(anonymous) @ middleware.web.ts:105
(anonymous) @ middleware.any.ts:71
(anonymous) @ middleware.ts:42
(anonymous) @ middleware.ts:152
(anonymous) @ middleware.ts:160
(anonymous) @ middleware.ts:87
(anonymous) @ middleware.ts:82
(anonymous) @ middleware.any.ts:38
(anonymous) @ middleware.ts:35
(anonymous) @ middleware.web.ts:28
(anonymous) @ middleware.ts:18
(anonymous) @ middleware.web.ts:10
(anonymous) @ middleware.ts:28
(anonymous) @ middleware.web.ts:28
(anonymous) @ middleware.any.ts:108
(anonymous) @ middleware.ts:13
(anonymous) @ middleware.ts:73
(anonymous) @ middleware.web.ts:61
(anonymous) @ middleware.ts:9
(anonymous) @ middleware.tsx:13
(anonymous) @ middleware.ts:12
(anonymous) @ middleware.ts:135
(anonymous) @ middleware.tsx:17
(anonymous) @ middleware.ts:31
(anonymous) @ middleware.ts:55
(anonymous) @ middleware.ts:102
(anonymous) @ middleware.web.ts:20
(anonymous) @ middleware.any.ts:22
(anonymous) @ middleware.web.ts:35
(anonymous) @ middleware.any.ts:100
(anonymous) @ middleware.web.ts:170
(anonymous) @ middleware.ts:33
(anonymous) @ middleware.web.ts:22
(anonymous) @ middleware.ts:141
dispatch @ redux.js:636
(anonymous) @ actions.web.ts:177
(anonymous) @ index.js:16
(anonymous) @ middleware.ts:20
(anonymous) @ middleware.ts:29
(anonymous) @ middleware.ts:19
(anonymous) @ middleware.ts:14
(anonymous) @ middleware.web.ts:23
(anonymous) @ middleware.any.ts:33
(anonymous) @ middleware.ts:63
(anonymous) @ middleware.ts:48
(anonymous) @ middleware.ts:60
(anonymous) @ middleware.ts:102
(anonymous) @ middleware.ts:50
(anonymous) @ middleware.ts:46
(anonymous) @ middleware.ts:28
(anonymous) @ middleware.ts:155
(anonymous) @ middleware.ts:44
(anonymous) @ middleware.ts:22
Logger.js:155  2023-10-13T07:20:29.268Z [modules/xmpp/strophe.util.js] <Da.St.Strophe.log>:  Strophe: Websocket error {"isTrusted":true}
r @ Logger.js:155
Da.St.Strophe.log @ strophe.util.js:89
error @ strophe.umd.js:2020
_onError @ strophe.umd.js:6079
socket.onerror @ strophe.umd.js:5783
error (asynchrone)
_connect @ strophe.umd.js:5783
connect @ strophe.umd.js:3040
_interceptConnectArgs @ strophe.stream-management.js:224
connect @ XmppConnection.js:273
_connect @ xmpp.js:598
connect @ xmpp.js:702
Ku.connect @ JitsiConnection.js:73
(anonymous) @ actions.any.ts:225
(anonymous) @ actions.any.ts:147
(anonymous) @ index.js:16
(anonymous) @ middleware.ts:20
(anonymous) @ middleware.ts:29
(anonymous) @ middleware.ts:19
(anonymous) @ middleware.ts:14
(anonymous) @ middleware.web.ts:23
(anonymous) @ middleware.any.ts:33
(anonymous) @ middleware.ts:63
(anonymous) @ middleware.ts:48
(anonymous) @ middleware.ts:60
(anonymous) @ middleware.ts:102
(anonymous) @ middleware.ts:50
(anonymous) @ middleware.ts:46
(anonymous) @ middleware.ts:28
(anonymous) @ middleware.ts:155
(anonymous) @ middleware.ts:44
(anonymous) @ middleware.ts:22
(anonymous) @ middleware.ts:52
(anonymous) @ middleware.ts:50
(anonymous) @ middleware.web.ts:35
(anonymous) @ middleware.web.ts:19
(anonymous) @ middleware.any.ts:52
(anonymous) @ middleware.ts:60
(anonymous) @ middleware.web.ts:273
(anonymous) @ middleware.ts:39
(anonymous) @ middleware.ts:21
(anonymous) @ middleware.ts:11
(anonymous) @ middleware.ts:16
(anonymous) @ middleware.ts:18
(anonymous) @ middleware.web.ts:24
(anonymous) @ middleware.any.ts:35
(anonymous) @ middleware.ts:12
(anonymous) @ middleware.ts:83
(anonymous) @ middleware.ts:26
(anonymous) @ middleware.web.ts:90
(anonymous) @ middleware.any.ts:83
(anonymous) @ middleware.ts:27
(anonymous) @ middleware.web.ts:17
(anonymous) @ middleware.any.ts:19
(anonymous) @ middleware.web.ts:17
(anonymous) @ middleware.any.ts:18
(anonymous) @ middleware.ts:32
(anonymous) @ middleware.web.ts:15
(anonymous) @ middleware.ts:254
(anonymous) @ middleware.ts:15
(anonymous) @ middleware.ts:36
(anonymous) @ middleware.ts:38
(anonymous) @ middleware.ts:65
(anonymous) @ middleware.ts:8
(anonymous) @ middleware.ts:29
(anonymous) @ middleware.ts:20
(anonymous) @ middleware.web.ts:105
(anonymous) @ middleware.any.ts:71
(anonymous) @ middleware.ts:42
(anonymous) @ middleware.ts:152
(anonymous) @ middleware.ts:160
(anonymous) @ middleware.ts:87
(anonymous) @ middleware.ts:82
(anonymous) @ middleware.any.ts:38
(anonymous) @ middleware.ts:35
(anonymous) @ middleware.web.ts:28
(anonymous) @ middleware.ts:18
(anonymous) @ middleware.web.ts:10
(anonymous) @ middleware.ts:28
(anonymous) @ middleware.web.ts:28
(anonymous) @ middleware.any.ts:108
(anonymous) @ middleware.ts:13
(anonymous) @ middleware.ts:73
(anonymous) @ middleware.web.ts:61
(anonymous) @ middleware.ts:9
(anonymous) @ middleware.tsx:13
(anonymous) @ middleware.ts:12
(anonymous) @ middleware.ts:135
(anonymous) @ middleware.tsx:17
(anonymous) @ middleware.ts:31
(anonymous) @ middleware.ts:55
(anonymous) @ middleware.ts:102
(anonymous) @ middleware.web.ts:20
(anonymous) @ middleware.any.ts:22
(anonymous) @ middleware.web.ts:35
(anonymous) @ middleware.any.ts:100
(anonymous) @ middleware.web.ts:170
(anonymous) @ middleware.ts:33
(anonymous) @ middleware.web.ts:22
(anonymous) @ middleware.ts:141
dispatch @ redux.js:636
(anonymous) @ actions.web.ts:43
(anonymous) @ index.js:16
(anonymous) @ middleware.ts:20
(anonymous) @ middleware.ts:29
(anonymous) @ middleware.ts:19
(anonymous) @ middleware.ts:14
(anonymous) @ middleware.web.ts:23
(anonymous) @ middleware.any.ts:33
(anonymous) @ middleware.ts:63
(anonymous) @ middleware.ts:48
(anonymous) @ middleware.ts:60
(anonymous) @ middleware.ts:102
(anonymous) @ middleware.ts:50
(anonymous) @ middleware.ts:46
(anonymous) @ middleware.ts:28
(anonymous) @ middleware.ts:155
(anonymous) @ middleware.ts:44
(anonymous) @ middleware.ts:22
(anonymous) @ middleware.ts:52
(anonymous) @ middleware.ts:50
(anonymous) @ middleware.web.ts:35
(anonymous) @ middleware.web.ts:19
(anonymous) @ middleware.any.ts:52
(anonymous) @ middleware.ts:60
(anonymous) @ middleware.web.ts:273
(anonymous) @ middleware.ts:39
(anonymous) @ middleware.ts:21
(anonymous) @ middleware.ts:11
(anonymous) @ middleware.ts:16
(anonymous) @ middleware.ts:18
(anonymous) @ middleware.web.ts:24
(anonymous) @ middleware.any.ts:35
(anonymous) @ middleware.ts:12
(anonymous) @ middleware.ts:83
(anonymous) @ middleware.ts:26
(anonymous) @ middleware.web.ts:90
(anonymous) @ middleware.any.ts:83
(anonymous) @ middleware.ts:27
(anonymous) @ middleware.web.ts:17
(anonymous) @ middleware.any.ts:19
(anonymous) @ middleware.web.ts:17
(anonymous) @ middleware.any.ts:18
(anonymous) @ middleware.ts:32
(anonymous) @ middleware.web.ts:15
(anonymous) @ middleware.ts:254
(anonymous) @ middleware.ts:15
(anonymous) @ middleware.ts:36
(anonymous) @ middleware.ts:38
(anonymous) @ middleware.ts:65
(anonymous) @ middleware.ts:8
(anonymous) @ middleware.ts:29
(anonymous) @ middleware.ts:20
(anonymous) @ middleware.web.ts:105
(anonymous) @ middleware.any.ts:71
(anonymous) @ middleware.ts:42
(anonymous) @ middleware.ts:152
(anonymous) @ middleware.ts:160
(anonymous) @ middleware.ts:87
(anonymous) @ middleware.ts:82
(anonymous) @ middleware.any.ts:38
(anonymous) @ middleware.ts:35
(anonymous) @ middleware.web.ts:28
(anonymous) @ middleware.ts:18
(anonymous) @ middleware.web.ts:10
(anonymous) @ middleware.ts:28
(anonymous) @ middleware.web.ts:28
(anonymous) @ middleware.any.ts:108
(anonymous) @ middleware.ts:13
(anonymous) @ middleware.ts:73
(anonymous) @ middleware.web.ts:61
(anonymous) @ middleware.ts:9
(anonymous) @ middleware.tsx:13
(anonymous) @ middleware.ts:12
(anonymous) @ middleware.ts:135
(anonymous) @ middleware.tsx:17
(anonymous) @ middleware.ts:31
(anonymous) @ middleware.ts:55
(anonymous) @ middleware.ts:102
(anonymous) @ middleware.web.ts:20
(anonymous) @ middleware.any.ts:22
(anonymous) @ middleware.web.ts:35
(anonymous) @ middleware.any.ts:100
(anonymous) @ middleware.web.ts:170
(anonymous) @ middleware.ts:33
(anonymous) @ middleware.web.ts:22
(anonymous) @ middleware.ts:141
dispatch @ redux.js:636
(anonymous) @ actions.web.ts:177
(anonymous) @ index.js:16
(anonymous) @ middleware.ts:20
(anonymous) @ middleware.ts:29
(anonymous) @ middleware.ts:19
(anonymous) @ middleware.ts:14
(anonymous) @ middleware.web.ts:23
(anonymous) @ middleware.any.ts:33
(anonymous) @ middleware.ts:63
(anonymous) @ middleware.ts:48
(anonymous) @ middleware.ts:60
(anonymous) @ middleware.ts:102
(anonymous) @ middleware.ts:50
(anonymous) @ middleware.ts:46
(anonymous) @ middleware.ts:28
(anonymous) @ middleware.ts:155
(anonymous) @ middleware.ts:44
(anonymous) @ middleware.ts:22
Logger.js:155 2023-10-13T07:20:29.268Z [modules/xmpp/xmpp.js] <Da.connectionHandler>:  (TIME) Strophe connfail[The WebSocket connection could not be established or was disconnected.]:	 230564
Logger.js:155  2023-10-13T07:20:29.269Z [JitsiMeetJS.ts] <Object.getGlobalOnErrorHandler>:  UnhandledError: Strophe: Websocket closed unexcectedly Script: null Line: null Column: null StackTrace:  Error: Strophe: Websocket closed unexcectedly
    at Da.St.Strophe.log (https://visio.reseau-entrenous.fr/libs/lib-jitsi-meet.min.js?v=7531:2:821513)
    at Object.error (https://visio.reseau-entrenous.fr/libs/lib-jitsi-meet.min.js?v=7531:2:500190)
    at F.Websocket._onClose (https://visio.reseau-entrenous.fr/libs/lib-jitsi-meet.min.js?v=7531:2:537505)
    at socket.onclose (https://visio.reseau-entrenous.fr/libs/lib-jitsi-meet.min.js?v=7531:2:535021)
r @ Logger.js:155
getGlobalOnErrorHandler @ JitsiMeetJS.ts:533
window.onerror @ middleware.ts:84
callErrorHandler @ GlobalOnErrorHandler.js:61
Da.St.Strophe.log @ strophe.util.js:88
error @ strophe.umd.js:2020
_onClose @ strophe.umd.js:6027
socket.onclose @ strophe.umd.js:5785
Logger.js:155  2023-10-13T07:20:29.270Z [modules/xmpp/strophe.util.js] <Da.St.Strophe.log>:  Strophe: Websocket closed unexcectedly

**Comment by saghul** [comment]
Your WebSocket proxy seems to be wrong, it's giving you a 400 error. Check your Apache configuration.

**Comment by Zell40** [comment]
proxy.conf

<IfModule mod_proxy.c>

	# If you want to use apache2 as a forward proxy, uncomment the
	# 'ProxyRequests On' line and the <Proxy *> block below.
	# WARNING: Be careful to restrict access inside the <Proxy *> block.
	# Open proxy servers are dangerous both to your network and to the
	# Internet at large.
	#
	# If you only want to use apache2 as a reverse proxy/gateway in
	# front of some web application server, you DON'T need
	# 'ProxyRequests On'.

	#ProxyRequests On
	#<Proxy *>
	#   AddDefaultCharset off
	#   Require all denied
	#   #Require local
	#</Proxy>

	# Enable/disable the handling of HTTP/1.1 "Via:" headers.
	# ("Full" adds the server version; "Block" removes all outgoing Via: headers)
	# Set to one of: Off | On | Full | Block
	#ProxyVia Off

        <IfModule mod_proxy_wstunnel.c>
          ProxyTimeout 900
          <Location "/xmpp-websocket">
              ProxyPass "wss://localhost:5443/xmpp-websocket"
          </Location>
          <Location "/colibri-ws/">
              ProxyPass "wss://localhost:5443/colibri-ws/"
          </Location>
        </IfModule>

</IfModule>

vhost

<VirtualHost *:80>
    ServerAdmin zell@reseau-entrenous.fr
    ServerName visio.reseau-entrenous.fr
    Redirect permanent / https://visio.reseau-entrenous.fr
    RewriteEngine On
    RewriteCond %{HTTPS} off
    RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
</VirtualHost>

<VirtualHost *:443>
    ServerAdmin zell@reseau-entrenous.fr
    ServerName visio.reseau-entrenous.fr

    # Reverse proxy http connections
    # requires: a2enmod proxy proxy_http
    ProxyVia On
    ProxyRequests Off
    ProxyPass "/" "https://localhost:5443/"
    ProxyPassReverse "/" "https://localhost:5443/"
    ProxyPass "/http-bind" "https://localhost:5443/http-bind/"
    ProxyPassReverse "/http-bind" "https://localhost:5443/http-bind/"
    ProxyPreserveHost on
    SSLEngine on
    SSLProxyEngine on
    SSLProxyVerify none
    SSLProxyCheckPeerName off
    SSLProxyCheckPeerCN off
    RewriteEngine on

    RewriteCond %{HTTP:Connection} Upgrade [NC]
    RewriteCond %{HTTP:Upgrade} websocket [NC]
    RewriteRule ^/?(.*) "ws://localhost:5443/$1" [P,L]
    ErrorLog     /var/log/apache2/meet-error_log
    CustomLog    /var/log/apache2/meet-access_log common

    # Set header to allow the irc connection to be marked as secure
    # requires: a2enmod headers
    RequestHeader set "X-Forwarded-Proto" expr=%{REQUEST_SCHEME}

	# directives obligatoires pour TLS
    SSLEngine on
    SSLProtocol All -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
    SSLCipherSuite HIGH:!aNULL:!MD5:!ADH:!RC4:!DH:!RSA
    SSLHonorCipherOrder on
    SSLCertificateFile "/etc/apache2/ssl/reseau-entrenous.fr.ssl.crt"
    SSLCertificateKeyFile "/etc/apache2/ssl/reseau-entrenous.fr.key"

    Header always set Strict-Transport-Security "max-age=15768000"

</VirtualHost>

**Comment by Zell40** [comment]
I tried to modify the config several times but I still get this error...

**Comment by Zell40** [comment]
Ok.... erreur : RewriteRule ^/?(.*) "ws://localhost:5443/$1" [P,L] => RewriteRule ^/?(.*) "**wss**://localhost:5443/$1" [P,L] 
Thanks ;)
