### ISSUE TITLE
whiteBoard

### ISSUE THREAD

**Issue by longuto** [jitsi/docker-jitsi-meet#1620]
1、  I use whiteBoard in docker-compose

2、I disable websocket in the .env  

3、 I start up excalidraw-backend server  in  443

4、 I config the config.js  with whiteboard

5、 it is error , WebSocket is closed before the connection is established
![Dingtalk_20231009171125](https://github.com/jitsi/docker-jitsi-meet/assets/21220020/fa0894d4-00e5-4010-afff-912f9744e769)
![Dingtalk_20231009171137](https://github.com/jitsi/docker-jitsi-meet/assets/21220020/8fc1684a-f494-468a-8c67-93274e747481)
![Dingtalk_20231009171206](https://github.com/jitsi/docker-jitsi-meet/assets/21220020/9501f236-9947-4264-bc34-20c481ec9afa)
![Dingtalk_20231009171030](https://github.com/jitsi/docker-jitsi-meet/assets/21220020/7c6f9dfd-96da-4e22-9fa6-03f767971d08)

**Comment by longuto** [comment]
@saghul  can you help me

**Comment by saghul** [comment]
Check the network tab in developer tools to see if you get any clue as to why the socket is closed.

**Comment by longuto** [comment]
1. I used the configuration with the docs
2. if i not use the configuration, it always 
![Uploading 微信截图_20231009220835.png…]()
get disconnected

**Comment by longuto** [comment]
1. I used the configuration with the docs
2. if i not use the configuration, it always get disconnected
![微信截图_20231009220835](https://github.com/jitsi/docker-jitsi-meet/assets/21220020/8c557e5c-aa98-45af-ab82-0de708fec733)

**Comment by saghul** [comment]
Are you using some kind of reverse proxy?

**Comment by longuto** [comment]
i use docker-compose,  the proxy in docker container.   i have not use in host machine.   i request url in https://ip:8443

**Comment by longuto** [comment]
it is ok, if i not use whiteboard.  There was an error when I used whiteboard.

i want to know if i not use websocket , can i use whiteboard.
![Dingtalk_20231009171030](https://github.com/jitsi/docker-jitsi-meet/assets/21220020/7c60084d-30a9-4b71-b4d5-076c899df203)

**Comment by longuto** [comment]
I have solved this issue. thank you @saghul

**Comment by sakiphandursun** [comment]
@longuto Hi, Can you explain the solution?
