### ISSUE TITLE
Jibri failed to join the call

### ISSUE THREAD

**Issue by hari36135** [jitsi/docker-jitsi-meet#1638]
I have followed the below blog to setup Jitsi and Jibri in aws ec2 ubuntu 18.04. Jitsi is working fine but not able to record the meeting. below are the logs of the Jibri container.
https://sesamedisk.com/build-free-conference-jitsi-with-docker/
-----------------
  ConfigSourceSupplier: key: 'jibri.recording.recordings-directory', type: 'kotlin.String', source: 'config'
Jibri 2023-11-07 13:43:56.245 FINE: [101] MainKt$setupMetaconfigLogger$1.debug#232: LambdaSupplier: Trying to retrieve value via JibriConfig::recordingDirectory
Jibri 2023-11-07 13:43:56.246 FINE: [101] MainKt$setupMetaconfigLogger$1.debug#232: FallbackSupplier: failed to find value via LambdaSupplier: 'JibriConfig::recordingDirectory': org.jitsi.metaconfig.ConfigException$UnableToRetrieve$Error: class java.lang.NullPointerException
Jibri 2023-11-07 13:43:56.246 FINE: [101] MainKt$setupMetaconfigLogger$1.debug#232: ConfigSourceSupplier: Trying to retrieve key 'jibri.recording.recordings-directory' from source 'config' as type kotlin.String
Jibri 2023-11-07 13:43:56.247 FINE: [101] MainKt$setupMetaconfigLogger$1.debug#232: ConfigSourceSupplier: Found value /config/recordings for key 'jibri.recording.recordings-directory' from source 'config' as type kotlin.String
Jibri 2023-11-07 13:43:56.247 FINE: [101] MainKt$setupMetaconfigLogger$1.debug#232: FallbackSupplier: value found via ConfigSourceSupplier: key: 'jibri.recording.recordings-directory', type: 'kotlin.String', source: 'config'
Jibri 2023-11-07 13:43:56.248 FINE: [101] MainKt$setupMetaconfigLogger$1.debug#232: FallbackSupplier: checking for value via suppliers:
  LambdaSupplier: 'JibriConfig::finalizeRecordingScriptPath'
  ConfigSourceSupplier: key: 'jibri.recording.finalize-script', type: 'kotlin.String', source: 'config'
Jibri 2023-11-07 13:43:56.248 FINE: [101] MainKt$setupMetaconfigLogger$1.debug#232: LambdaSupplier: Trying to retrieve value via JibriConfig::finalizeRecordingScriptPath
Jibri 2023-11-07 13:43:56.249 FINE: [101] MainKt$setupMetaconfigLogger$1.debug#232: FallbackSupplier: failed to find value via LambdaSupplier: 'JibriConfig::finalizeRecordingScriptPath': org.jitsi.metaconfig.ConfigException$UnableToRetrieve$Error: class java.lang.NullPointerException
Jibri 2023-11-07 13:43:56.249 FINE: [101] MainKt$setupMetaconfigLogger$1.debug#232: ConfigSourceSupplier: Trying to retrieve key 'jibri.recording.finalize-script' from source 'config' as type kotlin.String
Jibri 2023-11-07 13:43:56.250 FINE: [101] MainKt$setupMetaconfigLogger$1.debug#232: ConfigSourceSupplier: Found value /path/to/finalize for key 'jibri.recording.finalize-script' from source 'config' as type kotlin.String
Jibri 2023-11-07 13:43:56.250 FINE: [101] MainKt$setupMetaconfigLogger$1.debug#232: FallbackSupplier: value found via ConfigSourceSupplier: key: 'jibri.recording.finalize-script', type: 'kotlin.String', source: 'config'
Jibri 2023-11-07 13:43:56.250 INFO: [101] [session_id=aejmdasqibdezxmh] FileRecordingJibriService.<init>#134: Writing recording to /config/recordings/aejmdasqibdezxmh, finalize script path /path/to/finalize
Jibri 2023-11-07 13:43:56.251 FINE: [101] JibriStatsDClient.incrementCounter#38: Incrementing statsd counter: start:recording
Jibri 2023-11-07 13:43:56.251 INFO: [101] JibriStatusManager$special$$inlined$observable$1.afterChange#75: Busy status has changed: IDLE -> BUSY
Jibri 2023-11-07 13:43:56.251 FINE: [101] WebhookClient$updateStatus$1.invokeSuspend#109: Updating 0 subscribers of status
Jibri 2023-11-07 13:43:56.252 INFO: [101] XmppApi.updatePresence#212: Jibri reports its status is now JibriStatus(busyStatus=BUSY, health=OverallHealth(healthStatus=HEALTHY, details={})), publishing presence to connections
Jibri 2023-11-07 13:43:56.254 FINE: [101] MucClientManager.setPresenceExtension#160: Setting a presence extension: org.jitsi.xmpp.extensions.jibri.JibriStatusPacketExt@536b1f7d
Jibri 2023-11-07 13:43:56.254 FINE: [101] MucClientManager.saveExtension#185: Replacing presence extension: org.jitsi.xmpp.extensions.jibri.JibriStatusPacketExt@435a26a9
Jibri 2023-11-07 13:43:56.257 FINE: [45] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse: Could not add a provider for element busy-status from namespace http://jitsi.org/protocol/jibri
Jibri 2023-11-07 13:43:56.258 INFO: [101] XmppApi.handleStartJibriIq#284: Sending 'pending' response to start IQ
Jibri 2023-11-07 13:43:56.258 INFO: [109] AbstractPageObject.visit#32: Visiting url https://jitsi.mydomain.com
Jibri 2023-11-07 13:43:56.261 FINE: [45] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse: Could not add a provider for element health-status from namespace http://jitsi.org/protocol/health
Jibri 2023-11-07 13:43:56.537 SEVERE: [109] [session_id=aejmdasqibdezxmh] JibriSelenium.joinCall$lambda$3#327: An error occurred while joining the call
org.openqa.selenium.WebDriverException: unknown error: net::ERR_NAME_NOT_RESOLVED
  (Session info: chrome=116.0.5845.96)
  (Driver info: chromedriver=116.0.5845.96 (1a391816688002153ef791ffe60d9e899a71a037-refs/branch-heads/5845@{#1382}),platform=Linux 4.15.0-213-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 0 milliseconds
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: '0e306c058975', ip: '172.20.0.6', os.name: 'Linux', os.arch: 'amd64', os.version: '4.15.0-213-generic', java.version: '11.0.21'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities {acceptInsecureCerts: false, acceptSslCerts: false, browserConnectionEnabled: false, browserName: chrome, chrome: {chromedriverVersion: 116.0.5845.96 (1a3918166880..., userDataDir: /tmp/.org.chromium.Chromium...}, cssSelectorsEnabled: true, databaseEnabled: false, fedcm:accounts: true, goog:chromeOptions: {debuggerAddress: localhost:41083}, handlesAlerts: true, hasTouchScreen: false, javascriptEnabled: true, locationContextEnabled: true, mobileEmulationEnabled: false, nativeEvents: true, networkConnectionEnabled: false, pageLoadStrategy: normal, platform: LINUX, platformName: LINUX, proxy: Proxy(), rotatable: false, setWindowRect: true, strictFileInteractability: false, takesHeapSnapshot: true, takesScreenshot: true, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unexpectedAlertBehaviour: ignore, unhandledPromptBehavior: ignore, version: 116.0.5845.96, webStorageEnabled: true, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:extension:minPinLength: true, webauthn:extension:prf: true, webauthn:virtualAuthenticators: true}
Session ID: 76650ff30a9096294c6b3e32184d7f8e
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
        at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
        at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
        at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:158)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:83)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
        at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:271)
        at org.jitsi.jibri.selenium.pageobjects.AbstractPageObject.visit(AbstractPageObject.kt:35)
        at org.jitsi.jibri.selenium.JibriSelenium.joinCall$lambda$3(JibriSelenium.kt:295)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Jibri 2023-11-07 13:43:56.542 INFO: [109] [session_id=aejmdasqibdezxmh] JibriSelenium.onSeleniumStateChange#216: Transitioning from state Starting up to Error: FailedToJoinCall SESSION Failed to join the call
Jibri 2023-11-07 13:43:56.543 INFO: [109] [session_id=aejmdasqibdezxmh] StatefulJibriService.onServiceStateChange#39: File recording service transitioning from state Starting up to Error: FailedToJoinCall SESSION Failed to join the call
Jibri 2023-11-07 13:43:56.544 INFO: [109] XmppApi$createServiceStatusHandler$1.invoke#320: Current service had an error Error: FailedToJoinCall SESSION Failed to join the call, sending error iq <iq xmlns='jabber:client' to='jibribrewery@internal-muc.jitsi.mydomain.com/focus' id='1ZAE7-125' type='set'><jibri xmlns='http://jitsi.org/protocol/jibri' status='off' failure_reason='error' should_retry='true'/></iq>
Jibri 2023-11-07 13:43:56.544 FINE: [109] JibriStatsDClient.incrementCounter#38: Incrementing statsd counter: stop:recording
Jibri 2023-11-07 13:43:56.548 INFO: [109] JibriManager.stopService#274: Stopping the current service
Jibri 2023-11-07 13:43:56.552 INFO: [109] [session_id=aejmdasqibdezxmh] FileRecordingJibriService.stop#182: Stopping capturer
Jibri 2023-11-07 13:43:56.553 INFO: [109] [session_id=aejmdasqibdezxmh] JibriSubprocess.stop#75: Stopping ffmpeg process
Jibri 2023-11-07 13:43:56.553 INFO: [109] [session_id=aejmdasqibdezxmh] JibriSubprocess.stop#89: ffmpeg exited with value null
Jibri 2023-11-07 13:43:56.554 INFO: [109] [session_id=aejmdasqibdezxmh] FileRecordingJibriService.stop#184: Quitting selenium
Jibri 2023-11-07 13:43:56.555 INFO: [109] [session_id=aejmdasqibdezxmh] FileRecordingJibriService.stop#191: No media was recorded, deleting directory and skipping metadata file & finalize
Jibri 2023-11-07 13:43:56.555 INFO: [109] [session_id=aejmdasqibdezxmh] JibriSelenium.leaveCallAndQuitBrowser#338: Leaving call and quitting browser
Jibri 2023-11-07 13:43:56.556 INFO: [109] [session_id=aejmdasqibdezxmh] JibriSelenium.leaveCallAndQuitBrowser#341: Recurring call status checks cancelled
Jibri 2023-11-07 13:43:56.577 INFO: [109] [session_id=aejmdasqibdezxmh] JibriSelenium.leaveCallAndQuitBrowser#347: Got 3 log entries for type browser
Jibri 2023-11-07 13:43:56.587 INFO: [109] [session_id=aejmdasqibdezxmh] JibriSelenium.leaveCallAndQuitBrowser#347: Got 120 log entries for type driver
Jibri 2023-11-07 13:43:56.600 INFO: [109] [session_id=aejmdasqibdezxmh] JibriSelenium.leaveCallAndQuitBrowser#347: Got 0 log entries for type client
Jibri 2023-11-07 13:43:56.600 INFO: [109] [session_id=aejmdasqibdezxmh] JibriSelenium.leaveCallAndQuitBrowser#356: Leaving web call
Jibri 2023-11-07 13:43:56.625 INFO: [109] [session_id=aejmdasqibdezxmh] JibriSelenium.leaveCallAndQuitBrowser#363: Quitting chrome driver
Jibri 2023-11-07 13:43:56.696 INFO: [109] [session_id=aejmdasqibdezxmh] JibriSelenium.leaveCallAndQuitBrowser#365: Chrome driver quit
Jibri 2023-11-07 13:43:56.696 INFO: [109] JibriStatusManager$special$$inlined$observable$1.afterChange#75: Busy status has changed: BUSY -> IDLE
Jibri 2023-11-07 13:43:56.697 FINE: [109] WebhookClient$updateStatus$1.invokeSuspend#109: Updating 0 subscribers of status
Jibri 2023-11-07 13:43:56.697 INFO: [109] XmppApi.updatePresence#212: Jibri reports its status is now JibriStatus(busyStatus=IDLE, health=OverallHealth(healthStatus=HEALTHY, details={})), publishing presence to connections
Jibri 2023-11-07 13:43:56.698 FINE: [109] MucClientManager.setPresenceExtension#160: Setting a presence extension: org.jitsi.xmpp.extensions.jibri.JibriStatusPacketExt@4ea4844e
Jibri 2023-11-07 13:43:56.698 FINE: [109] MucClientManager.saveExtension#185: Replacing presence extension: org.jitsi.xmpp.extensions.jibri.JibriStatusPacketExt@536b1f7d
Jibri 2023-11-07 13:43:56.700 FINE: [45] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse: Could not add a provider for element busy-status from namespace http://jitsi.org/protocol/jibri
Jibri 2023-11-07 13:43:56.701 FINE: [45] org.jitsi.xmpp.extensions.DefaultPacketExtensionProvider.parse: Could not add a provider for element health-status from namespace http://jitsi.org/protocol/health

Note: I just replaced my actual domain name with mydomain.com in above logs

**Comment by saghul** [comment]
Is PUBLIC_URL set? Does it have the right certificate chain and is the Jibri container able to connect to it?

**Comment by hari36135** [comment]
> Is PUBLIC_URL set? Does it have the right certificate chain and is the Jibri container able to connect to it?

yeah, PUBLIC_URL  is there in env and ssl certificate also available. how to check jibri container able to connect?

**Comment by hari36135** [comment]
if you can share some blogs or docs to set up Jibri on docker compose it will be really helpful.

**Comment by borbuevbeksultan** [comment]
org.openqa.selenium.WebDriverException: unknown error: net::ERR_NAME_NOT_RESOLVED
(Session info: chrome=116.0.5845.96) here is the root cause. i'll try to set it manually in /etc/hosts and try again
