### ISSUE TITLE
Outdated meet.conf as per main jitsi-meet repository

### ISSUE THREAD

**Issue by tmcgee123** [jitsi/docker-jitsi-meet#164]
The NGINX config is out of date or missing this commit : https://github.com/jitsi/jitsi-meet/pull/541/commits/5ca21d8a1959fb2d8c3d212ab43344447693e2bc

I'm not sure how these repos were set up but I use UUID's for roomNames which is why I found this. Here's the end result of my meet.conf file

````
server_name _;

client_max_body_size 0;

root /usr/share/jitsi-meet;
index index.html
error_page 404 /static/404.html;

location ~ ^/([a-zA-Z0-9=_\-\?]+)$ {
    rewrite ^/(.*)$ / break;
}

location /config.js {
    alias /config/config.js;
}

location /interface_config.js {
    alias /config/interface_config.js;
}

location /external_api.js {
    alias /usr/share/jitsi-meet/libs/external_api.min.js;
}

location / {
    ssi on;
}

# BOSH
location = /http-bind {
    proxy_pass http://xmpp.meet.jitsi:5280/http-bind;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header Host meet.jitsi;
}
````

changing
````
^/([a-zA-Z0-9=\?]+)$
````
to

````
^/([a-zA-Z0-9=_\-\?]+)$
````

and add ````=```` to the http-bind location block

**Comment by saghul** [comment]
Yep we need to update it. If you’re up for sending a PR that would be most welcome

**Comment by tmcgee123** [comment]
I will make a PR tonight when I get home, my work computer has a different git user and I'm too lazy to configure multiple users and privates keys 😺

**Comment by saghul** [comment]
Thank you!

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/docker-jitsi-meet/pull/245
