### ISSUE TITLE
prosody in docker, Error: Creating user failed

### ISSUE THREAD

**Issue by eppesuig** [jitsi/docker-jitsi-meet#1643]
Hello,
I just followed all instructions for the [self hosting guide](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker/), and I am trying to create a user in prosody. So I typed, from a root prompt and from the directory where my `.env` file is, the command `docker-compose exec prosody /bin/bash` and then, in the prosody container, this happens:

```
root@b0e711a509af:/# prosodyctl --config /config/prosody.cfg.lua register giuseppe meet.jitsi 'Not+That,SeCr3t'
Error: Creating user failed
```

In order to collect more data, I enabled log at debug level and restarted all containers, but no lines are recorderd while executing these commands.

I then checked for any existing users, folllowing the same self hosting guide.

```
root@b0e711a509af:/# find /config/data/meet%2ejitsi/accounts -type f -exec basename {} .dat \;
find: '/config/data/meet%2ejitsi/accounts': No such file or directory
root@b0e711a509af:/# ls -ld /config/data/meet%2ejitsi/
ls: cannot access '/config/data/meet%2ejitsi/': No such file or directory
root@b0e711a509af:/# ls -l /config/data/
total 8
drwxr-x--- 5 prosody prosody 4096 Nov 10 16:23 auth%2emeet%2ejitsi
-rw-r----- 1 prosody prosody    3 Nov 14 16:09 prosody.pid
```

So, it seems that the account directory is not created at all, or the directory name is different and it should be `auth%2emeet%2ejitsi`.

Do you have any suggestion about what to do?

Thank you,
Giuseppe

**Comment by saghul** [comment]
Did you run Docker as root?

**Comment by eppesuig** [comment]
Yes, I did it.

**Comment by saghul** [comment]
Don't, it will cause you trouble. Make sure you run `docker-compose` as a user.

**Comment by eppesuig** [comment]
Hello @saghul , I am not sure about what you mean. I usually run docker as root, in fact when I try to run it as normal user, I get this:

```
jitsi@jitsitest:~/docker-jitsi-meet-stable-8960-1$ docker-compose up -d
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 704, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 399, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.11/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.11/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.11/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/docker/transport/unixconn.py", line 30, in connect
    sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied

```
I searched on the Internet about running docker as normal user, and I found [this page on docker rootless mode](https://docs.docker.com/engine/security/rootless/). Is this what you are referring about?

Thank you,
Giuseppe

**Comment by saghul** [comment]
You will want to add your user to the "docker" group and reboot or logout / login so the changes are applied.
