### ISSUE TITLE
allow jvb max memory value to be altered

### ISSUE THREAD

**Issue by gottaeat** [jitsi/docker-jitsi-meet#1647]
users who deploy via docker are unable to alter the default value of 3072 in a permanent matter as the `VIDEOBRIDGE_MAX_MEMORY` env var (https://github.com/jitsi/jitsi-videobridge/blob/814bffd6cf050001a020288e70e942fa0d505d64/jvb/resources/jvb.sh#L19) is not defined within the docker compose or the `env.example`

edit:
doing a little more digging, although not expressed anywhere within the docker related jitsi files, simply exporting 
- JICOFO_MAX_MEMORY=N
- VIDEOBRIDGE_MAX_MEMORY=N
in the compose allows the max mem to be altered.

**Comment by gottaeat** [comment]
```diff
compose yaml
--- a/docker-compose.yml  2023-09-22 08:44:45.000000000 +0000
+++ b/docker-compose.yml  2023-11-25 22:14:05.479998766 +0000
@@ -326,6 +326,7 @@
             - XMPP_RECORDER_DOMAIN
             - XMPP_SERVER
             - XMPP_PORT
+            - JICOFO_MAX_MEMORY
         depends_on:
             - prosody
         networks:
@@ -374,6 +375,7 @@
             - XMPP_INTERNAL_MUC_DOMAIN
             - XMPP_SERVER
             - XMPP_PORT
+            - VIDEOBRIDGE_MAX_MEMORY
         depends_on:
             - prosody
         networks:
```

```sh
# .env
JICOFO_MAX_MEMORY=1536m
VIDEOBRIDGE_MAX_MEMORY=1536m
```

**Comment by saghul** [comment]
A PR would be welcome!
