### ISSUE TITLE
Jigasi JIGASI_TRANSCRIBER_SEND_TEXT not working

### ISSUE THREAD

**Issue by celuck1** [jitsi/docker-jitsi-meet#1651]
Hello,

I've been working on getting transcriptions working in my docker jitsi. I've been able to get the subtitles working and showing up properly, however, when I enable the JIGASI_TRANSCRIBER_SEND_TEXT to send the messages to the chat it doesn't seem to have any effect. Any advice to get that to work would be appreciated.

**Comment by tukanFrozen** [comment]
The correct variable name is `JIGASI_TRANSCRIBER_SEND_TXT`
