### ISSUE TITLE
SENTRY_DSN can not be defined

### ISSUE THREAD

**Issue by krombel** [jitsi/docker-jitsi-meet#1655]
When trying to set SENTRY_DSN I get the following error
```
docker compose logs jicofo       
jitsi-jicofo-1  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
jitsi-jicofo-1  | [s6-init] ensuring user provided files have correct perms...exited 0.
jitsi-jicofo-1  | [fix-attrs.d] applying ownership & permissions fixes...
jitsi-jicofo-1  | [fix-attrs.d] done.
jitsi-jicofo-1  | [cont-init.d] executing container initialization scripts...
jitsi-jicofo-1  | [cont-init.d] 01-set-timezone: executing... 
jitsi-jicofo-1  | [cont-init.d] 01-set-timezone: exited 0.
jitsi-jicofo-1  | [cont-init.d] 10-config: executing... 
jitsi-jicofo-1  | panic: render template error: template: /defaults/logging.properties:1:38: executing "/defaults/logging.properties" at <toBool>: error calling toBool: strconv.ParseBool: parsing "https://<redacted>": invalid syntax
jitsi-jicofo-1  | 
jitsi-jicofo-1  | goroutine 1 [running]:
jitsi-jicofo-1  | main.templateExecute(0xc0000b2580?, {0x7ffc4ab18e22, 0x1c})
jitsi-jicofo-1  |       /Users/runner/work/tpl/tpl/main.go:48 +0x1b5
jitsi-jicofo-1  | main.main()
jitsi-jicofo-1  |       /Users/runner/work/tpl/tpl/main.go:69 +0x226
jitsi-jicofo-1  | [cont-init.d] 10-config: exited 0.
jitsi-jicofo-1  | [cont-init.d] done.
jitsi-jicofo-1  | [services.d] starting services
jitsi-jicofo-1  | [services.d] done.
```

`logging.properties` is then empty.

jicofo here just stands as example. The same code is present in jigasi and jvb

**Comment by saghul** [comment]
I actually think Sentry support was removed from Jicofo, wasn't it @bgrozev ? If so we should drop it from here too.

**Comment by DanielMcAssey** [comment]
Just looking at the pom.xml and logging.properties on Jicofo, Jigasi and JVB, it seem to still have a reference to sentry:

https://github.com/jitsi/jitsi-videobridge/blob/73fb0cf07e5627d1a6ed7131b6309af26afacd52/jvb/lib/logging.properties#L3
https://github.com/jitsi/jitsi-videobridge/blob/73fb0cf07e5627d1a6ed7131b6309af26afacd52/jvb/pom.xml#L205

https://github.com/jitsi/jicofo/blob/660d7057f3db61f75a732169760ab59e79c5afaa/lib/logging.properties#L9
https://github.com/jitsi/jicofo/blob/660d7057f3db61f75a732169760ab59e79c5afaa/pom.xml#L233

Looking at the config generated through the template on this repo, it shouldnt cast `toBool`?

Should it just check for SENTRY_DSN environment variable?

Interested in this as we use Sentry too

**Comment by bgrozev** [comment]
@saghul The PRs that remove Sentry (jitsi/jitsi-videobridge#1785 and jitsi/jicofo#854) haven't been merged. I'd still like to merge them, so they are included as dependencies only where needed. Do you have an alternative way of pulling them in for docker?
