### ISSUE TITLE
Etherpad < 1.9 does not support arm64

### ISSUE THREAD

**Issue by waja** [jitsi/docker-jitsi-meet#1665]
Looking into `etherpad.yml`, you are using tag `1.8.6`, but this is not available for arm64. Starting with 1.9 arm64 is [provided](https://hub.docker.com/r/etherpad/etherpad/tags).

**Comment by waja** [comment]
Looks like adjusting the image to `etherpad/etherpad:1.9` seems to work. Should I open a PR?

**Comment by saghul** [comment]
Please do!
