### ISSUE TITLE
Screen share starts with a low resolution, screens are unreadable for ~30 seconds

### ISSUE THREAD

**Issue by cedricroijakkers** [jitsi/docker-jitsi-meet#1668]
Jitsi version: stable-9111

Since the last two releases, when a user starts a screen share, the resolution of the share usually starts very low. When starting the screen share, it starts with a resolution of 512x288 (totally unreadable). Then after a few seconds, it upgrades itself to 1027x576 (better, but still pretty hard to read text) and finally it goes to 1536x864 (perfect).

The problem eventually corrects itself, but it takes a good 30 seconds for the screen to become perfectly readable for people watching. This is quite a long time, and other tools (like Teams) start with a decent screen share resolution immediately.

Is there any way to configure Jitsi to start with a specific screen share resolution, possibly in a percentage of the screen/window size that is being shared, as this can vary on the size of the window or the resolution of the full screen being shared. Ideally, you would want the share to start at 80% or maybe even 100% of the original screen size. There really is no point to start lower, since a screen share has a different function than a camera view: lowering the resolution makes no sense. While a lower camera resolution is still usable, a lower screen share resolution is not.

**Update**: I've noticed that if you shared screen in a call, then stopped sharing screen but remain in the call, and then later start sharing your screen again, it immediately starts at the higher resolution. As if it remembers that you have shared at this resolution before, and then immediately starts with it. Now only to have this same feature at the first time to share screen would be perfect.

**Comment by saghul** [comment]
Ping @jallamsetty1

**Comment by jallamsetty1** [comment]
We have enabled full SVC for VP9 in the last two releases. What endpoints are you seeing this on? Also do you have any max bitrates set on your deployment?

**Comment by cedricroijakkers** [comment]
No specific configuration is set for max or min bitrates, and as for codecs, the following are enabled:

```yaml
  ENABLE_CODEC_VP8: "true"
  ENABLE_CODEC_VP9: "true"
  ENABLE_CODEC_H264: "true"
  ENABLE_CODEC_OPUS_RED: "true"
  ENABLE_CODEC_AV1: "true"
```

I have tried switching these around: only enabling H264 or only enabling VP9, the behaviour remains the same. Eventually the screen share is perfect, but it takes quite some time to get there.

**Comment by jallamsetty1** [comment]
Are you able to reproduce this on meet.jit.si ?

**Comment by cedricroijakkers** [comment]
I've tested it on meet.jit.si. There the screen share starts with the higher resolution immediately. I've taken a look in the debug console of the browser that is sharing the screen.

On meet.jit.si I can see the following:

```
Logger.js:155 2023-12-14T07:42:23.551Z [modules/RTC/BridgeChannel.js] <Na.sendReceiverVideoConstraintsMessage>:  Sending ReceiverVideoConstraints with {"assumedBandwidthBps":-1,"constraints":{},"defaultConstraints":{"maxHeight":2160},"lastN":10}
```

After that, no more mentions of resolutions etc.

On my own server (running in containers) I see this:

```
JingleSessionPC.js:650 2023-12-14T07:45:39.581Z [modules/xmpp/JingleSessionPC.js] <peerconnection.onnegotiationneeded>:  JingleSessionPC[session=JVB,initiator=false,sid=18b4aosquuo15] onnegotiationneeded fired on TPC[id=1,type=JVB]
JingleSessionPC.js:2709 2023-12-14T07:45:39.621Z [modules/xmpp/JingleSessionPC.js] <ya.notifyMySSRCUpdate>:  JingleSessionPC[session=JVB,initiator=false,sid=18b4aosquuo15] Sending source-add for video ssrcs=2808408713,3743353241
BridgeChannel.js:343 2023-12-14T07:45:39.647Z [modules/RTC/BridgeChannel.js] <e.onmessage>:  SenderSourceConstraints: c340ab1c-v0 - 2160
JingleSessionPC.js:1563 2023-12-14T07:45:39.648Z [modules/xmpp/JingleSessionPC.js] <ya.setSenderVideoConstraint>:  JingleSessionPC[session=JVB,initiator=false,sid=18b4aosquuo15] setSenderVideoConstraint: 2160, sourceName: c340ab1c-v0
TraceablePeerConnection.js:2805 2023-12-14T07:45:39.651Z [modules/RTC/TraceablePeerConnection.js] <Tl._updateVideoSenderEncodings>:  TPC[id=1,type=JVB] Setting degradation preference [preference=maintain-framerate,track=LocalTrack[2,video]
TraceablePeerConnection.js:2835 2023-12-14T07:45:39.654Z [modules/RTC/TraceablePeerConnection.js] <Tl._updateVideoSenderEncodings>:  TPC[id=1,type=JVB] setting max height=2160,encodings=[{"active":true,"adaptivePtime":false,"networkPriority":"low","priority":"low","maxBitrate":2500000,"scaleResolutionDownBy":1}]
BridgeChannel.js:343 2023-12-14T07:45:39.654Z [modules/RTC/BridgeChannel.js] <e.onmessage>:  SenderSourceConstraints: c340ab1c-v0 - 2160
BridgeChannel.js:343 2023-12-14T07:45:39.714Z [modules/RTC/BridgeChannel.js] <e.onmessage>:  SenderSourceConstraints: c340ab1c-v0 - 720
JingleSessionPC.js:1563 2023-12-14T07:45:39.715Z [modules/xmpp/JingleSessionPC.js] <ya.setSenderVideoConstraint>:  JingleSessionPC[session=JVB,initiator=false,sid=18b4aosquuo15] setSenderVideoConstraint: 720, sourceName: c340ab1c-v0
BridgeChannel.js:343 2023-12-14T07:45:39.719Z [modules/RTC/BridgeChannel.js] <e.onmessage>:  SenderSourceConstraints: c340ab1c-v0 - 360
JingleSessionPC.js:1563 2023-12-14T07:45:39.720Z [modules/xmpp/JingleSessionPC.js] <ya.setSenderVideoConstraint>:  JingleSessionPC[session=JVB,initiator=false,sid=18b4aosquuo15] setSenderVideoConstraint: 360, sourceName: c340ab1c-v0
BridgeChannel.js:343 2023-12-14T07:45:39.755Z [modules/RTC/BridgeChannel.js] <e.onmessage>:  SenderSourceConstraints: c340ab1c-v0 - 180
JingleSessionPC.js:1563 2023-12-14T07:45:39.756Z [modules/xmpp/JingleSessionPC.js] <ya.setSenderVideoConstraint>:  JingleSessionPC[session=JVB,initiator=false,sid=18b4aosquuo15] setSenderVideoConstraint: 180, sourceName: c340ab1c-v0
BridgeChannel.js:343 2023-12-14T07:45:39.805Z [modules/RTC/BridgeChannel.js] <e.onmessage>:  SenderSourceConstraints: c340ab1c-v0 - -1
JingleSessionPC.js:1563 2023-12-14T07:45:39.805Z [modules/xmpp/JingleSessionPC.js] <ya.setSenderVideoConstraint>:  JingleSessionPC[session=JVB,initiator=false,sid=18b4aosquuo15] setSenderVideoConstraint: 2160, sourceName: c340ab1c-v0
```

I can see things like `preference=maintain-framerate` which might cause this. The frame rate stays high, but the resolution seems to be immediately scaled down. Is there some way to configure this in the Jitsi frontend? Then it might be worth for me to look into a PR to make this configurable in Docker too?

**Comment by jallamsetty1** [comment]
> I can see things like `preference=maintain-framerate` which might cause this. The frame rate stays high, but the resolution seems to be immediately scaled down. Is there some way to configure this in the Jitsi frontend? Then it might be worth for me to look into a PR to make this configurable in Docker too?

This means that the client is configured to prefer high fps for screenshare over resolution. Therefore the browser will start with high fps and scale the resolution up slowly based on the available uplink and compute power on the local endpoint. Do you have `DESKTOP_SHARING_FRAMERATE_MAX` set to > 5 fps?

**Comment by cedricroijakkers** [comment]
> Do you have `DESKTOP_SHARING_FRAMERATE_MAX` set to > 5 fps?

I have:

```yaml
DESKTOP_SHARING_FRAMERATE_MIN: "5"
DESKTOP_SHARING_FRAMERATE_MAX: "30"
```

But I don't want to limit the clients to 5fps all the time. So setting the MAX to 5 might probably solve this issue, but will have abysmal screen sharing all the time.

I checked in my client by the way, it is set to 5fps. So I would not expect it to start with such a high fps rate (and therefore low resolution).

**Comment by jallamsetty1** [comment]
> But I don't want to limit the clients to 5fps all the time. So setting the MAX to 5 might probably solve this issue, but will have abysmal screen sharing all the time.

In our experience, not setting the min. and max. produces the best results for screensharing. Since the browser is not constrained in any way, it captures the screenshare track at the best resolution and fps possible. The settings are needed only when you want the client to prioritize resolution (max. 5 fps) or motion (max. 30 fps). 
This is how meet.jit.si is currently configured.

**Comment by cedricroijakkers** [comment]
> In our experience, not setting the min. and max. produces the best results for screensharing. Since the browser is not constrained in any way, it captures the screenshare track at the best resolution and fps possible. The settings are needed only when you want the client to prioritize resolution (max. 5 fps) or motion (max. 30 fps). This is how meet.jit.si is currently configured.

I have tested this out, and this indeed works much better. The problem is that the configuration block `config.desktopSharingFrameRate` is *always* present in the `web` container. I have created a PR (https://github.com/jitsi/docker-jitsi-meet/pull/1674) to introduce a new environment variable `DESKTOP_SHARING_FRAMERATE_AUTO` which removes the configuration block alltogether, but also still allows (when set to `false`) to configure the min and max framerates as before for those who wish to use that functionality.
