### ISSUE TITLE
HTTP2HTTPS redirect not working

### ISSUE THREAD

**Issue by Tekcraft** [jitsi/docker-jitsi-meet#167]
After enabled the HTTPS redirect (using standard 80 and 443 ports), I'm still able to curl/connect to the port 80

**Comment by saghul** [comment]
That’s correct. Check the response though. You’ll get a 301 response with the HTTPS URL in the Location header.

**Comment by Tekcraft** [comment]
When I curl to the 80 port I get the normal page of jitsi and not the 301 response as expected.  So what else?

**Comment by saghul** [comment]
How does the generated nginx config look like?

**Comment by kouinkouin** [comment]
Hi,

Here my nginx generated config:
```
# cat web/nginx/site-confs/default 
server {
	listen 80 default_server;

	
	include /config/nginx/meet.conf;
	
}


server {
	listen 443 ssl;

	include /config/nginx/ssl.conf;
	include /config/nginx/meet.conf;
}
```
In my file .ENV, there is the 3 letsencrypt lines:
```
LETSENCRYPT_DOMAIN=***.***
ENABLE_LETSENCRYPT=1
LETSENCRYPT_EMAIL=***@***.***
```

The HTTPS endpoint works fine (certificate and dhparam generated).
I already remove all $CONFIG dir and regenerate it. I use the last image (fresh install this evening).

Thanks!

**Comment by saghul** [comment]
@kouinkouin Have you changed your env file and not removed the CONFIG directory perchance?

**Comment by kouinkouin** [comment]
Indeed, I removed all my $CONFIG folder, and docker-compose up, and I received again a 200 instead of 301
