### ISSUE TITLE
failed to access your camera 

### ISSUE THREAD

**Issue by ihornet** [jitsi/docker-jitsi-meet#168]
[react/features/base/tracks/functions.js] <>:  Failed to create local tracks Array(2) TypeError: Cannot read property 'getUserMedia' of undefined
    at RTCUtils.js:982
    at new Promise (<anonymous>)
    at t.value (RTCUtils.js:981)
    at t.<anonymous> (RTCUtils.js:1334)

**Comment by saghul** [comment]
Your browser doesn't seem to support WebRTC.

**Comment by dgtlmoon** [comment]
@saghul Why did you close this? You didnt even ask what version browser he was using!!

**Comment by dgtlmoon** [comment]
@ihornet I don't know why, but I get the same issue when I run the project using the regular ports (80+443), when I use the custom (default) higher ports everything works fine.

in my `.env`

```# Exposed HTTP port.
HTTP_PORT=8000
# Exposed HTTPS port.
HTTPS_PORT=8443
```

This works.

I got that same error in Firefox 73 "TypeError: Cannot read property 'getUserMedia' of undefined"

@saghul Really poor issue handling by OpenSource projects is also a factor in to why we are losing our privacy as a society, at the moment the other solutions are too convenient compared to being told "it's your fault", this is an old opensource grumpy mentality that HAS to change.

**Comment by dgtlmoon** [comment]
You didn't even ask the poor guy to paste in his bloody configuration!!!

**Comment by saghul** [comment]
> @saghul Really poor issue handling by OpenSource projects is also a factor in to why we are losing our privacy as a society, at the moment the other solutions are too convenient compared to being told "it's your fault", this is an old opensource grumpy mentality that HAS to change.

Save your speech, nobody needs it, even less right now. We reply to as many issues as we can, and it's hard to keep up, so one has to try to simplify.

Are you accessing your setup via HTTP or HTTPS? If you accesss via HTTP browsers don't allow the use of WebRTC, and I think that is one way it cacn manifest.

**Comment by dgtlmoon** [comment]
@saghul wow that has to be one of the most embarrassing and unprofessional responses from a project "professional" I've ever seen, I'm saving this one to WayBackMachine!

In my situation I had a fully functioning LetsEncrypt SSL certificate in place and I checked the SSL with a few validation websites and all seemed to be OK.

The problem I believe is that if there is a known edge case then it should detect that webRTC is not working and give a better error, I'm really happy to try identify what that edge case is and provide a patch.

I accessed the site via `https://mysite.com/meetingname...`

Same result in Chrome and Firefo (latest)

**Comment by saghul** [comment]
> @saghul wow that has to be one of the most embarrassing and unprofessional responses from a project "professional" I've ever seen, I'm saving this one to WayBackMachine!

Whatever floats your boat, but first check your entitlement at the door.



> The problem I believe is that if there is a known edge case then it should detect that webRTC is not working and give a better error, I'm really happy to try identify what that edge case is and provide a patch.

Not having the core WebRTC APIs available in a browser is a very weird thing, are you perhaps running an extension which does that? Did you get the exact error: `Cannot read property 'getUserMedia' of undefined` ?
