### ISSUE TITLE
Do you have a tutorial how to use docker desktop for jitsi meet?

### ISSUE THREAD

**Issue by seonggookang** [jitsi/docker-jitsi-meet#1703]
I'm a window user. and I found that jitsi meet doesn't support windows user. So my acquaintance said docker desktop can help me to open the jitsi meet open source. Can you help me with dealing this problem?

And I wonder is there a special reason that your company used class component for jitsi meet.

**Comment by saghul** [comment]
Please use our community forum (https://community.jitsi.org) for these kind of broad questions.
