### ISSUE TITLE
All dockers beside the web one keep restarting

### ISSUE THREAD

**Issue by Nik-Potokar** [jitsi/docker-jitsi-meet#1721]
Have an issue where only the web module works and i am prompted with an infinite "you have been disconnected issue". I have done some research and found out that some of my dockers keep restarting but i am unable to get down to the bottom of why?

![image](https://github.com/jitsi/docker-jitsi-meet/assets/76532587/e0b23b93-6a85-4101-898e-2f0c3a15c2b1)

![image](https://github.com/jitsi/docker-jitsi-meet/assets/76532587/fc7fa0c1-dc8c-4ab5-9bd6-6e2ebec8e980)

**Comment by saghul** [comment]
Please paste the logs for each container that keeps restarting.

**Comment by Nik-Potokar** [comment]
When running logs i saw that "FATAL ERROR: Jicofo auth password must be set" appears and i tried running ./gen-passwords.sh which does generate passwords in .env file but sadly dosent solve the issue as it did for some other.

I am running this on RHEL 9 if it helps


Logs: [message (2).txt](https://github.com/jitsi/docker-jitsi-meet/files/14067392/message.2.txt)

**Comment by saghul** [comment]
Please share the browser console logs, the web container logs don't help much here.

**Comment by Nik-Potokar** [comment]
[chromelog1706296002618.log](https://github.com/jitsi/docker-jitsi-meet/files/14068480/chromelog1706296002618.log)
Hopefully this helps

**Comment by Maknollram** [comment]
Hi, I tried to run jitsi with docker in oracle 9 and had the same problem, when I try to connect in the room, same message as your image, can you tell me how you solutioned the issue? I'm new using docker and servers
