### ISSUE TITLE
How to import pdf and images in etherpad on jitsi meet

### ISSUE THREAD

**Issue by kamleshboi69** [jitsi/docker-jitsi-meet#1740]
hi i am running jitsi meet through docker and i want to import pdf files and images it is given in the etherpad website how to do it but not in a detailed way    can you please help me with this 
this is my etherpad.yml file 

version: '3.5'

services:
  etherpad:
    image: etherpad/etherpad:1.9.6
    restart: ${RESTART_POLICY:-unless-stopped}
    environment:
      - TITLE=${ETHERPAD_TITLE}
      - DEFAULT_PAD_TEXT=${ETHERPAD_DEFAULT_PAD_TEXT}
      - SKIN_NAME=${ETHERPAD_SKIN_NAME}
      - SKIN_VARIANTS=${ETHERPAD_SKIN_VARIANTS}
      - SUPPRESS_ERRORS_IN_PAD_TEXT=true
    networks:
      meet.jitsi:
        aliases:
          - etherpad.meet.jitsi

if you need any config files please ask

**Comment by saghul** [comment]
We are not the maintainers of Etherpad, we just integrate with it.

Please ask the Etherpad forums.
