### ISSUE TITLE
Can not join any meeting. It automatically disconnect me.

### ISSUE THREAD

**Issue by aimedey19** [jitsi/docker-jitsi-meet#1749]
<img width="1912" alt="Screen Shot 2024-02-24 at 00 59 57" src="https://github.com/jitsi/docker-jitsi-meet/assets/89580257/83823f2c-77c8-41a9-b3a0-6829be306753">

**Comment by saghul** [comment]
You need to set the PUBLIC_URL env var.

**Comment by aimedey19** [comment]
Thank you
