### ISSUE TITLE
arm64 specific error - tries to launch google-chrome even though chromium was successfully installed

### ISSUE THREAD

**Issue by DevelopingEntitiesWithFuntations** [jitsi/docker-jitsi-meet#1756]
When running a arm64 architecture the following gets printed out in the jibri container:

```
_XSERVTranss6-applyuidgid: fatal: unable to exec /usr/bin/google-chrome: No such file or directory
mkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
```

Seems like chromium gets installed successfully on arm64(checked manually by running `docker exec -it containerid`), but it seems to try to exec google-chrome still after that

**Comment by saghul** [comment]
What Jibri image are you using?

**Comment by aaronkvanmeerten** [comment]
This is likely because of the warm-up script. I will take a look at it shortly, but it's likely that we need to adapt that to detect and run the appropriate chrome path

**Comment by DevelopingEntitiesWithFuntations** [comment]
@saghul stable-8960

**Comment by saghul** [comment]
> This is likely because of the warm-up script. I will take a look at it shortly, but it's likely that we need to adapt that to detect and run the appropriate chrome path

Good call.

**Comment by DevelopingEntitiesWithFuntations** [comment]
The issue appears to be in the ./jibri/rootfs/etc/services.d/40-jibri/run but when I fix it to `/usr/bin/chromium` it throws out an error on line 7 in the jibri.conf template? Huh?

**Comment by aaronkvanmeerten** [comment]
>  line 7 on in the jibri.conf template?: `panic: unable to parse template file: template: /defaults/jibri.conf:7: bad character U+0024 '$'` Huh?

line 7 is currently defined as:

https://github.com/jitsi/docker-jitsi-meet/blob/648612f1bcfd8688547a97fd74f69da83e33b5b2/jibri/rootfs/defaults/jibri.conf#L7


It doesn't look misdefined: is there something else there for you?

**Comment by DevelopingEntitiesWithFuntations** [comment]
> Can you share more details about what changes you made to 40-jibri/run? Are you detecting chromium or just hard-coding it to test?

Gladly. I just changed the /usr/bin/google-chrome to /usr/bin/chromium for testing purposes.

**Comment by DevelopingEntitiesWithFuntations** [comment]
> > line 7 on in the jibri.conf template?: `panic: unable to parse template file: template: /defaults/jibri.conf:7: bad character U+0024 '$'` Huh?
> 
> line 7 is currently defined as:
> 
> https://github.com/jitsi/docker-jitsi-meet/blob/648612f1bcfd8688547a97fd74f69da83e33b5b2/jibri/rootfs/defaults/jibri.conf#L7
> 
> It doesn't look misdefined: is there something else there for you?

I replaced the unicode $ with a regular $ and now the error appears to be gone, but the google-chrome error still appears which is fatal apparently...

**Comment by DevelopingEntitiesWithFuntations** [comment]
I think I have checked and saw a difference in the file and hence made changes like the following, bear with me: (in the run file)
```
#!/usr/bin/with-contenv bash

# we have to set it, otherwise chrome won't find ~/.asoundrc file
HOME=/home/jibri

DAEMON=/opt/jitsi/jibri/launch.sh
# pre-warm google chrome before jibri launches to ensure fast chrome launch during recordings
s6-setuidgid jibri /usr/bin/chromium --timeout=1000 --headless about:blank
exec s6-setuidgid jibri /bin/bash -c "exec $DAEMON"

```

**Comment by aaronkvanmeerten** [comment]
I have a new PR for the chrome check here:

https://github.com/jitsi/docker-jitsi-meet/pull/1757

Let me know if you can test it?

**Comment by DevelopingEntitiesWithFuntations** [comment]
Just tried it:
`s6-applyuidgid: fatal: unable to exec /usr/bin/google-chrome: No such file or directory`

The error must be somewhere else I'm afraid :/ or I'm messing smth up.

Should I try to git clone the new repo and take the newest stable release or smth?

Thank you for your help.

**Comment by DevelopingEntitiesWithFuntations** [comment]
Yeah, but the error is different: it was `_XSERVTranss6-applyuidgid:` now it's just `s6-applyuidgid`

**Comment by aaronkvanmeerten** [comment]
As of the latest workflow run you should be able to pull and run the jitsi/jibri:unstable-2024-03-12 image to see the changes

**Comment by DevelopingEntitiesWithFuntations** [comment]
I manually edited the file and after the edit (as mentioned above) the error occurs somewhere else it seems, so likely in an another script :/

**Comment by DevelopingEntitiesWithFuntations** [comment]
Ok, so I pulled the newest master to try it again and it now I get the same error and more:
when I try to exec chromedriver on the machine it crashes:
```
root@8f33d9f8bd19:/# chromedriver
Trace/breakpoint trap (core dumped)
root@8f33d9f8bd19:/# chromedriver --version
Trace/breakpoint trap (core dumped)
```
ChromeDriver seems to not start because of the error above as it is printed out in the logs below:
```
org.openqa.selenium.WebDriverException: Timed out waiting for driver server to start.
Build info: version: 'unknown', revision: 'unknown', time: 'unknown'
System info: host: '8f33d9f8bd19', ip: '10.5.0.13', os.name: 'Linux', os.arch: 'aarch64', os.version: '5.4.17-2136.327.2.el8uek.aarch64', java.version: '11.0.22'
Driver info: driver.version: ChromeDriver
        at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:192)
        at org.openqa.selenium.remote.service.DriverService.start(DriverService.java:178)
        at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:79)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:543)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:207)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:130)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:181)
        at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:168)
        at org.jitsi.jibri.selenium.JibriSelenium.<init>(JibriSelenium.kt:199)
        at org.jitsi.jibri.selenium.JibriSelenium.<init>(JibriSelenium.kt:167)
        at org.jitsi.jibri.service.impl.FileRecordingJibriService.<init>(FileRecordingJibriService.kt:109)
        at org.jitsi.jibri.service.impl.FileRecordingJibriService.<init>(FileRecordingJibriService.kt:96)
        at org.jitsi.jibri.JibriManager.startFileRecording(JibriManager.kt:153)
        at org.jitsi.jibri.api.xmpp.XmppApi.handleStartService(XmppApi.kt:386)
        at org.jitsi.jibri.api.xmpp.XmppApi.handleStartJibriIq(XmppApi.kt:278)
        at org.jitsi.jibri.api.xmpp.XmppApi.handleJibriIq(XmppApi.kt:246)
        at org.jitsi.jibri.api.xmpp.XmppApi.handleIq(XmppApi.kt:228)
        at org.jitsi.xmpp.mucclient.MucClient.handleIq(MucClient.java:551)
        at org.jitsi.xmpp.mucclient.MucClient$3.handleIQRequest(MucClient.java:514)
        at org.jivesoftware.smack.AbstractXMPPConnection$3.run(AbstractXMPPConnection.java:1561)
        at org.jivesoftware.smack.AbstractXMPPConnection$10.run(AbstractXMPPConnection.java:2146)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://localhost:11314/status] to be available after 20000 ms
        at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:100)
        at org.openqa.selenium.remote.service.DriverService.waitUntilAvailable(DriverService.java:187)
        ... 23 more
Caused by: java.util.concurrent.TimeoutException
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
        at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:148)
        at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:75)
        ... 24 more

```
The error is still with `s6-applyuidgid` as noted above. Any idea what/how to fix? Or is it just incompatible with Oracle Linux?

**Comment by saghul** [comment]
I don't think your base OS is the problem, as the images still run Debian...

**Comment by DevelopingEntitiesWithFuntations** [comment]
@saghul you're absolutely correct in that matter. Then why do I get the same error from another spot, which I can't even find with grep?

**Comment by DevelopingEntitiesWithFuntations** [comment]
Ok, my bad I've been using the wrong image. Now that I've been using the right one the chromedriver crashes just like tried manually above in the logs above: `./run: line 10:   362 Trace/breakpoint trap   (core dumped) s6-setuidgid jibri $CHROME_BIN_PATH --timeout=1000 --headless about:blank`

**Comment by DevelopingEntitiesWithFuntations** [comment]
I've tried `manually` changing the owner to `jibri:jibri but that didn't work either... same error

**Comment by DevelopingEntitiesWithFuntations** [comment]
I straced the `chromium --headless` and found this: 🤔

```
openat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/pulseaudio/tls/aarch64/atomics/libpulsecommon-14.2.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/pulseaudio/tls/aarch64/atomics", 0xffffe214d990, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/pulseaudio/tls/aarch64/libpulsecommon-14.2.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/pulseaudio/tls/aarch64", 0xffffe214d990, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/pulseaudio/tls/atomics/libpulsecommon-14.2.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/pulseaudio/tls/atomics", 0xffffe214d990, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/pulseaudio/tls/libpulsecommon-14.2.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/pulseaudio/tls", 0xffffe214d990, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/pulseaudio/aarch64/atomics/libpulsecommon-14.2.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/pulseaudio/aarch64/atomics", 0xffffe214d990, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/pulseaudio/aarch64/libpulsecommon-14.2.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/pulseaudio/aarch64", 0xffffe214d990, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/pulseaudio/atomics/libpulsecommon-14.2.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
newfstatat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/pulseaudio/atomics", 0xffffe214d990, 0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/pulseaudio/libpulsecommon-14.2.so", O_RDONLY|O_CLOEXEC) = 3

```

**Comment by DevelopingEntitiesWithFuntations** [comment]
If I try executing it in gdb I only get the following: `warning: Error disabling address space randomization: Operation not permitted` while running under jibri user

**Comment by DevelopingEntitiesWithFuntations** [comment]
Managed to run chromium in gdb mode ( `/usr/bin/chromium -g`) and got this:
```
(gdb) backtrace
#0  0x0000aaaea3d41a64 in ?? ()
#1  0x0000fffef464e000 in sys_sigabbrev () from /lib/aarch64-linux-gnu/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) x 0x0000aaaea3d41a64 
0xaaaea3d41a64: 0xd4200000
(gdb) x 0x0000fffef464e000
0xfffef464e000 <sys_sigabbrev+368>:     0x00000000
```

**Comment by saghul** [comment]
That is really weird and alas it doesn't show the cause :-/ 

By the looks of the Chromium package in Debian is busted right now...

**Comment by DevelopingEntitiesWithFuntations** [comment]
I tried installing the Chromium Debian sid build (chromium/unstable,now 122.0.6261.128-1 arm64), but still core dumps :/

Maybe the deb package is meant for Android only? I can't find arm64 Chromium on the download page, which is meant for non-Android

**Comment by DevelopingEntitiesWithFuntations** [comment]
I tried setting up a Jibri docker instance and it still errors (different errors though):
```
[0317/093558.262640:ERROR:bus.cc(407)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[0317/093558.374209:ERROR:command_buffer_proxy_impl.cc(131)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
```

Weird because on amd64 it does seem to succesfully authenticate with my other domain...

**Comment by saghul** [comment]
Hold on. Weren't you testing Docker all this time?!

**Comment by DevelopingEntitiesWithFuntations** [comment]
> Hold on. Weren't you testing Docker all this time?!

@saghul yes I've have been testing only Docker the whole time... I just used `docker exec -it` to get on the machine. Running the docker container on amd64 seems to hit a wall too in Docker (did not try setting up on bare metal at all)

**Comment by saghul** [comment]
Ok. I'll give it a try, it worked last I tried...

**Comment by DevelopingEntitiesWithFuntations** [comment]
@saghul make sure to test on arm64

**Comment by saghul** [comment]
👍 My usual testing scenario is on an M1 Mac host.

**Comment by DevelopingEntitiesWithFuntations** [comment]
> 👍 My usual testing scenario is on an M1 Mac host.

I think an Ampere CPU on Oracle Linux is a bit different..

But did it work on a M1 Mac?

**Comment by saghul** [comment]
Just tested. It did!

Does standard Debian for arm64 run on that platform?

**Comment by aaronkvanmeerten** [comment]
I have run a test on the latest `jitsi/jibri` image, `jitsi/jibri:jibri-8.0-168-g03d63f3-1` on an oracle cloud VM.Standard.A1.Flex instance which is arm64.  The host OS is ubuntu 22.04.4

It runs without the above-reported error, and successfully live streams.

**Comment by DevelopingEntitiesWithFuntations** [comment]
> Does standard Debian for arm64 run on that platform?

Just googled - according to https://www.debian.org/ports/arm/ it shouldn't be an issue

**Comment by DevelopingEntitiesWithFuntations** [comment]
> I have run a test on the latest `jitsi/jibri` image, `jitsi/jibri:jibri-8.0-168-g03d63f3-1` on an oracle cloud VM.Standard.A1.Flex instance which is arm64. The host OS is ubuntu 22.04.4
> 
> It runs without the above-reported error, and successfully live streams.

I am the running the same, just that the host OS is Oracle Linux. Is that the issue? Or do the new default settings from the cloud provider have different settings?

**Comment by DevelopingEntitiesWithFuntations** [comment]
I also don't have the Oracle Cloud Agent installed, can that be problematic? :/

**Comment by aaronkvanmeerten** [comment]
No the oracle cloud agent isn't relevant (we do not run it either).

**Comment by aaronkvanmeerten** [comment]
are you running the docker with at least a 2gb shm?  Are you running with any capabilities granted?
we run using nomad so I'm not running docker run directly:

Here's a snippet from our config:
```
      config {
        image        = "jitsi/jibri:${var.jibri_tag}"
        cap_add = ["SYS_ADMIN"]
        # 2gb shm
        shm_size = 2147483648

**Comment by DevelopingEntitiesWithFuntations** [comment]
> are you running the docker with at least a 2gb shm? Are you running with any capabilities granted? we run using nomad so I'm not running docker run directly:

I run docker directly on the VM with a 2gb shm:
```
jibri:
        image: jitsi/jibri:${JITSI_IMAGE_VERSION:-unstable}
        restart: ${RESTART_POLICY:-unless-stopped}
        volumes:
            - ${CONFIG}/jibri:/config:Z
        shm_size: '2gb'

```
> Are you running with any capabilities granted?
What do you mean?

**Comment by saghul** [comment]
Our compose file sets this:

```
        cap_add:
            - SYS_ADMIN
```

Whis is needed. I can't remember why though.

**Comment by saghul** [comment]
I added an SHM check so if it's not enough the container will fail to start.

**Comment by DevelopingEntitiesWithFuntations** [comment]
> Our compose file sets this:
> 
> ```
>         cap_add:
>             - SYS_ADMIN
> ```
> 
> Whis is needed. I can't remember why though.

I just added a snippet, not the whole thing. I'm using what's in the repo basically

**Comment by saghul** [comment]
Doh. Then I'm at a loss here :-/

**Comment by DevelopingEntitiesWithFuntations** [comment]
@saghul is there any further debugging steps that are possible to take?

**Comment by saghul** [comment]
I honestly don't know.

**Comment by saghul** [comment]
You are using Docker right? No podman or anything else. Is it the latest version?

**Comment by DevelopingEntitiesWithFuntations** [comment]
> You are using Docker right? No podman or anything else. Is it the latest version?

I am using `Docker version 25.0.4, build 1a576c5` which is the latest version and yes, it is Docker, not Podman.

**Comment by saghul** [comment]
I ran out of talent on this one, sorry!

**Comment by DevelopingEntitiesWithFuntations** [comment]
I tried running ltrace on the chromium executable (because it doesn't follow bash scripts apparently and I can't read out 40+ args from strace...):
```
$ ltrace /usr/lib/chromium/chromium
memset(0xaaae460b9b48, '\0', 5161)                                                                                                                                                                  = 0xaaae460b9b48
memset(0xaaae460bafe8, '\0', 1074)                                                                                                                                                                  = 0xaaae460bafe8
getpagesize()                                                                                                                                                                                       = 65536
unexpected breakpoint at 0xaaae3f710c00
```
The last line keeps repeating itself in an endless loop with ltrace.

The weird part is that I ran it again and now this happens:
```
$  ltrace /usr/lib/chromium/chromium
memset(0xaaab32039b48, '\0', 5161)                                                                                                                                                                  = 0xaaab32039b48
memset(0xaaab3203afe8, '\0', 1074)                                                                                                                                                                  = 0xaaab3203afe8
getpagesize()                                                                                                                                                                                       = 65536
unexpected breakpoint at 0xaaab2b690c00
```
This is very weird, because the first memset seems to be identical in start and size and the second one changed and the breakpoint changes as well. Any hints?

**Comment by DevelopingEntitiesWithFuntations** [comment]
Updated the Host OS from Oracle Linux 8.9 to 9.3 and the issue is completely gone!!!

There are other errors but they don't seem to matter.

Thank you so much!

**Comment by saghul** [comment]
🤯 glad to hear!
