### ISSUE TITLE
Inquiry about Disabling SSL Certificate Verification

### ISSUE THREAD

**Issue by Noah1991** [jitsi/docker-jitsi-meet#1762]
I hope this message finds you well. I am currently using Jitsi Meet in a Docker environment and would like to inquire about the process of disabling SSL certificate verification within the application.

Could you please provide guidance or steps on how to disable SSL certificate verification in Jitsi Meet? I have attempted to modify the Nginx configuration within the Docker container as per general guidelines, but I encountered difficulties and the service failed to run properly.

Any insights, instructions, or recommendations you can provide on this matter would be greatly appreciated.

Thank you for your attention to this inquiry.

Best regards,

**Comment by saghul** [comment]
You want to access it via plain HTTP?

**Comment by Noah1991** [comment]
> You want to access it via plain HTTP?

Yes, that's correct. I want to access it via plain HTTP because I am using it in an internal network, so HTTPS is not necessary. Additionally, the Android SDK doesn't support private SSL certificates. Thank you for understanding.

**Comment by saghul** [comment]
You can just access port 8080 rather than 8443.

Note that nothing will work, that port is just there in case you have your own proxy.

Browsers will not enable WebRTC functionality over http and the mobile apps won't work.

You need a valid TLS certificate.

**Comment by Noah1991** [comment]
Thank you for the suggestion. I'm wondering if it's possible to modify the Android SDK to allow access to private SSL certificates, so that no changes are needed on the web end. Do you have any resources or suggestions regarding this?

**Comment by saghul** [comment]
In the Android SDK we support reading certificates the user has added to the trust store, but you need to put one in there yourself.

With let's encrypt being free I don't know why you are trying to do this. You can just get the cert but not expose the service.

**Comment by Noah1991** [comment]
Thank you for providing information about reading certificates from the trust store in the Android SDK. I understand the benefits of Let's Encrypt certificates; however, for internal network purposes, we prefer using private SSL certificates. Can you provide guidance on how to add a private SSL certificate to the trust store in the Android SDK? Your help is appreciated.

**Comment by saghul** [comment]
> Can you provide guidance on how to add a private SSL certificate to the trust store in the Android SDK?

This is not specific to our SDK, it's an Android feature. I just know we enabled something in our app / SDK to allow it to use the user provided certs. It was community contributed, so I don't know how to add a certificate to the user trust store, sorry.

**Comment by Noah1991** [comment]
Does the Jitsi Meet Android SDK support importing certificates? I found the Jitsi Meet Android SDK at this address: https://github.com/jitsi/jitsi-meet/tree/master/android/sdk. Thank you!

**Comment by Noah1991** [comment]
Thank you very much for your patient response. After recalling the WebRTC interaction mechanism, I realized that the certificate validation might not be handled by the Jitsi Meet SDK. I will try to generate the required certificate or resolve the issue from the Android system level. Thanks again. Wish you a happy life.
