### ISSUE TITLE
Add changelog for releases and CHANGELOG.md

### ISSUE THREAD

**Issue by sapkra** [jitsi/docker-jitsi-meet#177]
When we have some breaking changes or new feature it would be great to have them documented without going through all commits.

**Comment by saghul** [comment]
We can do that for changes on this repo, but I don’t think we can for all the individual projects. Would that be enough?

**Comment by sapkra** [comment]
It makes sense to have it just for the docker API changes like renaming, removing or adding environment variables.

But to be honest I like to have that for all API changes (I already asked for semver in the community call a few month ago) but it's not a topic for this issue.

**Comment by saghul** [comment]
I agree with you. Alas, I tried but didn’t succeed at getting some meaningful change logs from all projects. It’s hard, there are many moving parts and it needs to be done by hand.

I can commit to start doing changelogs for the Docker parts at least.

**Comment by sapkra** [comment]
We could use something like [standard version](https://github.com/conventional-changelog/standard-version) and switch to [conventional commits](https://www.conventionalcommits.org/) so that the changelogs can be generated automatically.

**Comment by saghul** [comment]
That sounds good on paper. Las I tried to convince everyone to use a convention I didn't succeed. I'll try again, I like the fact that we can automate changelogs, somewhat.

**Comment by sapkra** [comment]
Maybe we could add a git hook for it:
https://dev.to/prahladyeri/how-to-enforce-conventional-commit-messages-using-git-hooks-2bmk

**Comment by saghul** [comment]
The lack of tooling is not the problem :-) I'm now realizing we might be talking about different things here: I'm thinking about the commits in the jitsi-meet, jicofo, etc. projects, are you also thinking in that line or just for this very project?

**Comment by sapkra** [comment]
It would be great to have conventional commits for all repositories. Otherwise you have to switch between multiple different formats and this would be really confusing.

I think it's similar to coding conventions. If you want to enforce them you have to use linters on the client side and on a pipeline which checks for the right format before this commit lands in master.

**Comment by saghul** [comment]
Fully agreed. Then there is some convincing to do. I'll give it s ahot.
