### ISSUE TITLE
How to set custom properties in Prosody config files?

### ISSUE THREAD

**Issue by LetrixZ** [jitsi/docker-jitsi-meet#1773]
I want to use a module that requires to set a custom property in a component but I can't do it because config files are regenerated.

Is there any alternative to this?

**Comment by LetrixZ** [comment]
I'm trying to modify jitsi-meet.cfg.lua which is autogenerated.

**Comment by LetrixZ** [comment]
It worked creating a `custom-jitsi-meet.cfg.lua` file and adding only the part that I needed:
```lua
Component "muc.meet.jitsi" "muc"
  party_empty = true
 ```
 
 Wasn't sure if Lua allowed this.

**Comment by damencho** [comment]
> Wasn't sure if Lua allowed this.

Hah, interesting. Thanks for sharing :)
