### ISSUE TITLE
FYI Cant find this repo in the docker hub registry

### ISSUE THREAD

**Issue by brimur** [jitsi/docker-jitsi-meet#1775]
Just an FYI. I use a GUI for docker and that GUI searches the Docker Hub registry when I am installing a container. I searched for docker-jitsi-meet but it is not found there. Below is a screenshot of everything found under the jitsi account...

![image](https://github.com/jitsi/docker-jitsi-meet/assets/8918706/a8fa132d-fc41-43c1-a6ca-eac9cc28ce99)

**Comment by aaronkvanmeerten** [comment]
There is no repo named docker-jitsi-meet, we have many separate components which have their own repo.
