### ISSUE TITLE
ArtifactHub group ownership

### ISSUE THREAD

**Issue by spijet** [jitsi/docker-jitsi-meet#1788]
Hello everyone!

I published the Jitsi Meet Helm Chart to [ArtifactHub](https://artifacthub.io/packages/helm/jitsi-meet/jitsi-meet) as per https://github.com/jitsi-contrib/jitsi-helm/issues/14, and while doing so I registered a `jitsi` org there as well. Since I'm not really a member of Jitsi organization, I'd like to add some of you guys and transfer the org ownership, if possible. Probably @saghul, @damencho or @aaronkvanmeerten? :)

**Comment by saghul** [comment]
All 3 of us please :-) Thanks a lot for your efforts!

**Comment by spijet** [comment]
Will do! :)Can you please check that all 3 of you have ArtifactHub accounts? It's possible to authorize it using your GitHub profile, this way the account name will be the same.23 апр. 2024 г., в 10:20, Saúl Ibarra Corretgé ***@***.***> написал(а):﻿
All 3 of us please :-) Thanks a lot for your efforts!

**Comment by spijet** [comment]
Done, please accept. :)

**Comment by saghul** [comment]
Done!

**Comment by spijet** [comment]
Nice! Now you can add @damencho and @aaronkvanmeerten when they sign up as well.

I also thought about adding an "official" badge to the Chart page, but I think that'd be overkill, since it's still a jitsi-contrib project. :)

**Comment by damencho** [comment]
I'm in with my github account.

**Comment by aaronkvanmeerten** [comment]
Same here, thanks for organizing this!

Cheers,

-Aaron

**Comment by spijet** [comment]
@damencho, @aaronkvanmeerten: done and done! :)

**Comment by spijet** [comment]
I think this issue can be closed as completed, since everyone mentioned is a member of the org now. :)

Thank you!
