### ISSUE TITLE
latest (9457) has pull problems

### ISSUE THREAD

**Issue by joukj** [jitsi/docker-jitsi-meet#1793]
with the latest release I get:

Pulling web (jitsi/web:stable-9457)...
ERROR: manifest for jitsi/web:stable-9457 not found: manifest unknown: manifest unknown

Someting missing?

**Comment by saghul** [comment]
Thanks for the heads up, looks like something was botched with the web image push.

**Comment by saghul** [comment]
I pushed stable-9457-1
