### ISSUE TITLE
meeting joining issue

### ISSUE THREAD

**Issue by linkzeeshan** [jitsi/docker-jitsi-meet#1802]
I am following Jitsi doc to done all installation on Azure VM

I installed docker, docker compose and latest jitsi meet and done some following changes in .env  
HTTP = 80 
HTTPS=443
PUBLIC_URL=https://meet2.medchois.com

I am unable to start meeting . Please help me how can i fix.

![image](https://github.com/jitsi/docker-jitsi-meet/assets/66298499/444f6c53-ad5d-4cda-8e55-3388a9c574a7)

![image](https://github.com/jitsi/docker-jitsi-meet/assets/66298499/2ccf83e0-ce2d-4130-9b1c-4a74793f4bff)

![jitsi](https://github.com/jitsi/docker-jitsi-meet/assets/66298499/41c28624-fd67-428a-a5ff-419cef07a99c)

**Comment by saghul** [comment]
Can you please share your browser console logs?

**Comment by linkzeeshan** [comment]
[saghul](https://github.com/saghul) Now I am running on VM IP and still same issue is coming. Please guide me how can I resolve this issue.

**Comment by saghul** [comment]
What is the exact problem? What happens when you click Join Meeting?

**Comment by linkzeeshan** [comment]
Whenever I click on **join meeting** button Same above screen is showing once finish splash bar popup

**Comment by linkzeeshan** [comment]
in .env I have added public_URL is :  40.121.83.229

![image](https://github.com/jitsi/docker-jitsi-meet/assets/66298499/002474ab-d56f-4942-a195-491fdab4ab76)

**Comment by saghul** [comment]
Please click on the "41 messages" part so all logs are visible and share the text, not a screenshot.

Also, I don't know why you changed the domain for the IP, you should be using the domain.

**Comment by linkzeeshan** [comment]
[saghul](https://github.com/saghul) Thank you for your help issue has been resolved
