### ISSUE TITLE
Sentry not supported?

### ISSUE THREAD

**Issue by DanielMcAssey** [jitsi/docker-jitsi-meet#1804]
Hey, just took the time to update our infra to the latest Jitsi (Thank you for the amazing work).

Is using Sentry supported by Jitsi? Getting the following

`panic: render template error: template: /defaults/logging.properties:1:24: executing "/defaults/logging.properties" at <toBool>: error calling toBool: strconv.ParseBool: parsing "https://[REMOVED]@sentry.[REMOVED]/[REMOVED]": invalid syntax`

Which is because of this change https://github.com/jitsi/docker-jitsi-meet/commit/b0092bcf6537cc917a500a96e2328f75ad6489f8 but this was to resolve #1724.

So is there a final say on whether we can use Sentry or not? Just to see if I need to find a workaround

**Comment by saghul** [comment]
Hum, I think I broke that with some updates to `tpl`. If there is an error parsing a boolean but the string is not empty we should return `true`.

I'll fix it up.

Context: https://github.com/jitsi/tpl/blob/bbdb11979c7d7163d27a7d7a9ca4b65d1c0854f6/func.go#L56C18-L56C35

**Comment by DanielMcAssey** [comment]
Ah cool!

If it helps, the standard Sentry DSN is the following format (Can be http): 

`https://randomGuid01d34db33f@sentry.domain.tld/randomString0123`

**Comment by saghul** [comment]
Not sure what the overall state of Sentry is (we don't use it ourselves) but I just fixed `toBool` in https://github.com/jitsi/docker-jitsi-meet/pull/1805
