### ISSUE TITLE
setting JVB_ADVERTISE_IPS 'dynamically' in a Docker context ? s6 script maybe ?

### ISSUE THREAD

**Issue by squalou** [jitsi/docker-jitsi-meet#1817]
Hi,

I'm experimenting with Jitsi Docker setup in AWS ECS (see this https://github.com/jitsi/docker-jitsi-meet/issues/1813 for previous episodes :-) 

In order to make things work, following documentation so far I

- disabled WEBSOCKET (even if port 10000 is open and all but that will be for next épisode)
- manually set  JVB_ADVERTISE_IPS

In this situation, I managed to have good quality meetings, no issue being with 4 or 5 participants

Without JVB_ADVERTISE_IPS, third participant caused sound and video to cut.

Long story short, things are not publicly accessible but hidden behind a VPN and maybe it's related, or not.  things are also behind all sorts of load balancers.

Anyway : my issue is that the value of JVB_ADVERTISE_IPS may change. I probably could have it "fixed" for "long enough", I'll manage this, but still.

There's a DNS associated to it, that answers the right IP on container start.

Would there be an "easy" way to set this env var at container startup, instead of setting a value in .env ?

I was thinking about a custom script somewhere in the s6 init process ... but I much prefer to ask before I loose hours on it :) .

Thank you !

**Comment by squalou** [comment]
maybe setting COLIBRI_WEBSOCKET_JVB_LOOKUP_NAME  does the trick ? I admit I'm a bit lost in all env vars :)

**Comment by aaronkvanmeerten** [comment]
I suspect you are on the right track w.r.t. a custom script in the s6 init process, or even injected as a variable from wherever your provisioning occurs.  From my limited understanding of the protocol, the JVB must advertise an IP address (rather than DNS).  It must also be consistent throughout the lifecycle of the container, as we do not current have support for dynamic addresses for a JVB.

For reference, the websocket path is meant to be proxied through valid SSL and then hit a different port on the JVB.  It is used for data channel communications if SCTP is not enabled.  In the newest JVB the SCTP support is more stable and takes care of all of the data channel within the UDP stream to 10000, meaning no need to proxy or configure anything separately for the JVB websocket.  So I suggest using that instead of the websocket if you are using a newer JVB version.

**Comment by squalou** [comment]
Thanks !

Well, to be honest I'm new to all this ... and until know I thougt SCTP and Websocket were opposite things.

So far I managed to have this running fine : 

- ENABLE_SCTP=1
- ENABLE_COLIBRI_WEBSOCKET=0
- ENABLE_XMPP_WEBSOCKET=0

I'm running latest stable version (stable-9457-2)

Would this setting be 'OK' ? performance wise I mean ? 
From what I see in this case I have no traffic over port 10 000. Wouldn't UDP be 'better' (since we don't care if some packets are lost).

**Comment by squalou** [comment]
ok, here's my tweak

Added in `/etc/cont-init.d/custom-script`

```
#!/bin/bash
cp /etc/services.d/jvb/run /etc/services.d/jvb/run.orig

cat << 'EOF' > /etc/services.d/jvb/run
#!/usr/bin/with-contenv bash
IP=$(dig +short $(echo $PUBLIC_URL | cut -d / -f 3))
echo -n $IP > /var/run/s6/container_environment/JVB_ADVERTISE_IPS
export JVB_ADVERTISE_IPS=$IP
EOF

cat /etc/services.d/jvb/run.orig >> /etc/services.d/jvb/run

```

it's a bit ugly to edit `/etc/services.d/jvb/run` but... when /etc/cont-init.d/custom-script runs, looks like dns resolution does not work yet. Otherwise I would simply have added IP value in  `/var/run/s6/container_environment/JVB_ADVERTISE_IPS`. (I tried but there was garbage in it)

**Comment by squalou** [comment]
That would be awesome.

BTW I reopen (for myself) since .. I thought my tweak did work but apparently no

**Comment by squalou** [comment]
final (hopefully) edit : it does work ! Provided the custom scripts gets executed in the proper order.

SO

finally I have this

in `/etc/cont-init.d/00-custom-script`

```
#!/usr/bin/with-contenv bash
if [ _z ${PUBLIC_URL} ]; then
   echo "ERROR: PUBLIC_URL must be defined"
   exit 1
fi
IP=$(dig +short $(echo $PUBLIC_URL | cut -d / -f 3))
echo -n $IP > /var/run/s6/container_environment/JVB_ADVERTISE_IPS

```

and now it works fine :)

**Comment by pysen** [comment]
For anyone else looking into this, the shebang in the above script has been changed in recent s6 version to:
 `#!/command/with-contenv bash`

Example for the jitsi helm `values.yaml`
```
jvb:
  extraFiles:
  - path: /etc/cont-init.d/00-public-ip
    mode: "0755"
    content: |
      #!/command/with-contenv bash
      if [ -z ${PUBLIC_URL} ]; then
         echo "ERROR: PUBLIC_URL must be defined"
         exit 1
      fi

      # join with commas if several ips, which also remove last \n
      IPS=$(dig +short $(echo $PUBLIC_URL | cut -d / -f 3) | tr '\n' ',')
      #remove trailing ','
      IPS=${IPS::-1}
      echo -n $IPS > /var/run/s6/container_environment/JVB_ADVERTISE_IPS

```
