### ISSUE TITLE
Customization advice, volumes, use of SQL backend, scaling.

### ISSUE THREAD

**Issue by squalou** [jitsi/docker-jitsi-meet#1820]
Hi,

opening an "issue" here may seem rude, I' more looking for understanding and advice regarding my jitsi deployment, and don't know where to ask.
So first things first : my apologies if it's not the right way to proceed, feel free to close this. (with a pointer to the right way would be great :) )

I would like to customize things, but apparently lots of config gets overridden when service start. From what I read, it's supposed to be configured by `.env` variables, and that's a perfectly fine approach. (especially with containers where storage could be completely disposable, no persistent volumes required)

That being said I did'nt find all, for instance things like "App Title". Or Welcome background image.

So first question : should I edit the docker image or build it myself ? what would be recommended ?

Then second question, regarding Prosody accounts storage. It's much more convenient to use a database rather than flat files. Especially if I ever consider several Prosody running (is this really a good idea, by the way). How would I accomplish that using these containers ?

And finally, I would need 'confirmation' regarding scaling up.
Jitsi documentation is well made (https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-scalable)
so, from my understanding : I'd rather start several JVB containers, and probably only one of each other would do the trick.
Right ?

Thank you for *any* kind of answer,

best regards

**Comment by squalou** [comment]
Partial answer to myself, that raises another question

I can add a custom `/defaults/pr/defaults/prosody.cfg.luaosody.cfg.lua` inside the container (and for instance add storage = "sql" etc)

The question is : I tried to add a custom file in `/defaults/conf.d/my-file.cfg.lua`, it indeed gets copied to `/config/conf.d/` at startup BUT `.Env.VAR_NAMES` are not interpreted.

is it expected ?

**Comment by aaronkvanmeerten** [comment]
These are all great questions, which is why I took too long to respond before.

The templating is all done in the s6 /etc/cont-init.d/10-config: https://github.com/jitsi/docker-jitsi-meet/blob/master/prosody/rootfs/etc/cont-init.d/10-config

So if you want templating, you'd need to add another script like 11-myconfig that runs `tpl /defaults/whatever.conf > /config/whatever.conf`

**Comment by squalou** [comment]
Thank you ! 
That's exactly the pointer I needed.
