### ISSUE TITLE
disable recordings has no effect

### ISSUE THREAD

**Issue by squalou** [jitsi/docker-jitsi-meet#1828]
Hi,

I'm trying to disable any form of recodings (local or whatever).

I'm using stable-9457-2.

I've set these variables in web jicofo, and prosody containers

```
ENABLE_RECORDING=false
ENABLE_SERVICE_RECORDING=false
DISABLE_LOCAL_RECORDING=true
ENABLE_FILE_RECORDING_SHARING=false
ENABLE_LIVESTREAMING=false

```

As a result if I check config.js in web/config for instance, I see that these options have been correctly set from the templating mechanism:

```

// Recording.
//

// Local recording configuration.
config.localRecording = {
    disable: true,
    notifyAllParticipants: false,
    disableSelfRecording: false
};

```

BUT

record option is still available ?!

I wonder if I'm missing something.

Thank you for any idea, I must admit I'm out of ideas.

![image](https://github.com/jitsi/docker-jitsi-meet/assets/4623644/12ee9b52-d17d-4481-aa53-9850a6c40315)

**Comment by squalou** [comment]
DAMN ME

it was a caching issue with my CDN in front of it all ! 

sorry for the noise, ONCE AGAIN.

**Comment by saghul** [comment]
No worries, glad you sorted it out!
