### ISSUE TITLE
Mobile Jitsi Meet sometimes needs BOSH URL setting in Docker

### ISSUE THREAD

**Issue by PhilGPk** [jitsi/docker-jitsi-meet#183]
I have a jitsi Meet server running via Docker.  It's running behind a NAT gateway, has a properly issued Let's Encrypt SSL certificate and port-forwarding is configured from the gateway.  The default 443 port has been changed to a higher port because of existing services in the environment.  There is a split-horizon DNS locally (which may be part of the issue, but isn't unusual in some of the environments I hope to deploy jitsi Meet).

Testing shows desktop/browser sessions working without fuss (thank you to all involved!).  Testing with Android mobile and iOS (an iPad) resulted in immediate disconnection.  Testing with Android Firefox and forcing the desktop site works.

A possible clue is in issue #2 and specifically https://github.com/jitsi/docker-jitsi-meet/issues/2#issuecomment-409202397 re: the BOSH_URL in .jitsi-meet-cfg/web/config.js.  On setting this to the full URL rather than the relative /http-bind fixes the symptoms above.

Is there a clean way to configure this via the .env file?  (I can't see one although there are a lot of details in there.)

I spent a while searching before solving this for myself and wonder if it's related to https://github.com/jitsi/jitsi-meet/issues/4805 or https://github.com/jitsi/jitsi-meet/issues/3103.

**Comment by saghul** [comment]
What version of the mobile apps are you using? I believe we solved the relative URL issue there...

**Comment by PhilGPk** [comment]
One of the Android devices shows version 19.5.1 build 3228528.  Downloaded via Play Store.

**Comment by saghul** [comment]
I'll need to check that out, we do have the code inplace to handle this: https://github.com/jitsi/jitsi-meet/blob/470c115e7ca6436b7a072110155ccaeec0d7fdaa/react/features/base/connection/actions.native.js#L295-L308 Something must have gotten broken. Oh well.

**Comment by saghul** [comment]
How does your (real) URL look like? Feel free to conceal the domain. I wonder if the non-standard port is the culprit here.

> There is a split-horizon DNS locally (which may be part of the issue, but isn't unusual in some of the environments I hope to deploy jitsi Meet).

What do you mean here?

**Comment by PhilGPk** [comment]
The real URL looks something like 
  https://not.actual.url:4567/
(it's a different port number, too).

For the IPv4 case: the split horizon bit means there are two IP addresses.  A client from inside the "intranet" bit will get the 10.x.y.z IP address, from outside, the real public IP address.  Otherwise things get a little bit weird with routing.  Doesn't seem to cause any problem for the desktop/web versions.

**Comment by saghul** [comment]
> The real URL looks something like
> https://not.actual.url:4567/
> (it's a different port number, too).

Yeah, that looks like a good candidate for the problem.  I'll give it a test and let you know.

**Comment by saghul** [comment]
I think a way to solve this would also be to use PUBLIC_URL to generate an appropriate BOSH URL, if defined.

**Comment by saghul** [comment]
I caught a bug in our code. We should've been using `url.host` instead of `hostname`, since the former includes the port. PR: https://github.com/jitsi/jitsi-meet/pull/5042

**Comment by Neustradamus** [comment]
@saghul: It is solved no?

**Comment by saghul** [comment]
Forgot to close this one. Yes, it's fixed in version >= 20.
