### ISSUE TITLE
DYNAMIC_BRANDING_URL or BRANDING_DATA_URL not being pulled from target server

### ISSUE THREAD

**Issue by mircsicz** [jitsi/docker-jitsi-meet#1833]
Dear all,

I'm well aware of this [issue](https://github.com/jitsi/jitsi-meet/issues/8183) and also this Changelog [entry](https://github.com/jitsi/docker-jitsi-meet/blob/master/CHANGELOG.md#stable-5390-3)

After adding the following to my .env
```
BRANDING_DATA_URL=https://s3.eu-xxx-y.amazonaws.com/mybucketid/jitsibranding.json
DYNAMIC_BRANDING_URL=${BRANDING_DATA_URL}
```
and recreating the container I see the following inside the web container:
```
root@company-talk:/srv/docker/meet-company-cloud# docker exec -ti  meet-company-cloud_web_1 /bin/bash
root@70678e8917fe:/# env
---
DYNAMIC_BRANDING_URL=https://s3.eu-xxx-y.amazonaws.com/mybucketid/jitsibranding.json
BRANDING_DATA_URL=https://s3.eu-xxx-y.amazonaws.com/mybucketid/jitsibranding.json
---
```

Where my json content looks like this:
```
{
          "inviteDomain":"meet.company.xyz",
          "backgroundColor":"#000",
          "logoClickUrl":"https://www.company.xx",
          "logoImageUrl":"https://s3.eu-xxx-y.amazonaws.com/mybucketid/company-logo-white.svg"   
}
```

So I would expect some changes in the frontend...

Please help me out and let me know what am I missing on this one?

**Comment by damencho** [comment]
Do you see your file being fetched from the client? Do you see dynamicBrandingUrl and brandingDataUrl being set in the config.js in the client?

**Comment by mircsicz** [comment]
Sorry forgot to add that to my initial Post:
```
root@70678e8917fe:/# grep Url /config/config.js 
config.dynamicBrandingUrl = 'https://s3.eu-xxx-y.amazonaws.com/mybucketid/jitsibranding.json';
    collabServerBaseUrl: ''
```

**Comment by damencho** [comment]
Nope, check the Network tab in the developer's tools in the browser to check whether that URL is requested and what is the response.

**Comment by mircsicz** [comment]
Thx a ton for the hint...

I was expecting that the json would be loaded from the server only, so the Bucket is quite restricted!
<img width="288" alt="Bildschirmfoto 2024-06-25 um 9 41 24 AM" src="https://github.com/jitsi/docker-jitsi-meet/assets/7398305/e9b7f982-c5ef-4763-ac43-e64edecb7b16">

**Comment by damencho** [comment]
Nope, the configuration for the url is in config.js which is read from the client and the clients are those requesting the resource.

**Comment by mircsicz** [comment]
It is now loading:
![Bildschirmfoto 2024-06-25 um 10 59 09 PM](https://github.com/jitsi/docker-jitsi-meet/assets/7398305/a78de687-5065-493b-85dc-fd58787be180)
but still I don't see the configured BG color nor the Logo or logo-click-url being changed...

**Comment by damencho** [comment]
Set headers to the file in s3
```
Access-Control-Allow-Origin: *
```

**Comment by mircsicz** [comment]
@damencho Thanks a ton, with that change it's fixed <3
