### ISSUE TITLE
Problem with more than two participants

### ISSUE THREAD

**Issue by denis-ionov** [jitsi/docker-jitsi-meet#1835]
When the third participant joins the call, i get an error in the console:
`[Failed to execute 'setRemoteDescription' on 'RTCPeerConnection']`
and a problem with a participant's video (blank video).

I read all related issues here, and tried the following:

- Setting DOCKER_HOST_ADDRESS to `public ip`/`127.0.0.1`/`docker host ip` and unsetting it

- Turning off all firewalls everywhere

None of these attempts worked.
I built the latest stable version. 
Here is the port mapping from the `docker ps` command:
`jvb - 127.0.0.1:8080->8080/tcp, 0.0.0.0:10000->10000/udp, :::10000->10000/udp`
`web - 0.0.0.0:8000->80/tcp, :::8000->80/tcp, 0.0.0.0:8443->443/tcp, :::8443->443/tcp`
`prosody - 5222/tcp, 5280/tcp, 5347/tcp`

What am I doing wrong? I have no more ideas on how to fix this.

**Comment by damencho** [comment]
> I built the latest stable version.

What steps did you follow? You updated from on old version?
.

**Comment by denis-ionov** [comment]
@damencho I updated from `stable-7577-2` to `stable-9457-2`. I have my own custom build flow, integrating everything from the `docker-jitsi-meet` Docker Compose file into my Docker Compose file. I build from Dockerfiles, not from images. Everything worked fine on `stable-7577-2` last year. Then, I didn't use Jitsi for some time and switched it off from my UI. When I returned to it, I saw that it was not working, so I updated to the latest version. Everything seems to be working, except for the problem mentioned in the topic.

**Comment by damencho** [comment]
That error makes me think it uses an old version. 

If you open the index page what is the version you see for `<script src="libs/app.bundle.min.js?v=7952"></script>`
For stable-9457 it should be `v=7952`.

**Comment by denis-ionov** [comment]
`<script src="libs/lib-jitsi-meet.min.js?v=7952"></script>`
`<script src="libs/app.bundle.min.js?v=7952"></script>`

**Comment by damencho** [comment]
hum... if you try incognito do you experience the same problem?

**Comment by denis-ionov** [comment]
@damencho Yeah, I tried it - it's the same.

**Comment by damencho** [comment]
Do you experience the same on meet.jit.si? What browser and version is this?

**Comment by denis-ionov** [comment]
> Do you experience the same on meet.jit.si?
Just tested, it seems ok.
> What browser and version is this?
Latest Chrome

**Comment by damencho** [comment]
Are you rebuilding jitsi-meet and lib-jitsi-meet with some custom changes?

**Comment by damencho** [comment]
Try with the official images, does it work with those?

**Comment by denis-ionov** [comment]
@damencho I forgot to mention a very important detail: I am not using the Jitsi web interface itself. Instead, I am using the JS API to build my own custom interface and flow. Additionally, I forgot about updating the frontend part. I am using https://github.com/solydhq/lib-jitsi-meet, which seems to be outdated. This means your guess about the script version is correct. It looks like I need to update the frontend part and test my case again. Can you advise on the latest lib-jitsi-meet library with TypeScript support? Thanks for your feedback!

**Comment by damencho** [comment]
lib-jitsi-meet needs to be in sync with the backend. So source the version that comes with your backend.

<script src="libs/lib-jitsi-meet.min.js?v=7952"></script>
