### ISSUE TITLE
jitsi room Crash when another user joins

### ISSUE THREAD

**Issue by pansj2020** [jitsi/docker-jitsi-meet#185]
Hello , I am from  China , Now WuHan virus is serious. We want to use jitsi-meet  to reduce people gather. I also hope it can help students study at their home. 

But when I use docker-jitsi-meet ,  ./docker-compose up , it come's some error. When I jion the meeting, it works OK . But when second one join in , room crash , and show reconnecting.

I have read some comments in issues before, but I cann't resolve it , give me some help, thanks

my .env
[root@node2 docker-jitsi-meet]# more .env 
#
# Basic configuration options
#

# Directory where all configuration will be stored.
CONFIG=/opt/jitsi-config

# Exposed HTTP port.
HTTP_PORT=80

# Exposed HTTPS port.
HTTPS_PORT=443

# System time zone.
TZ=Asia/Shanghai

# Public URL for the web service.
#PUBLIC_URL="https://meet.example.com"

# IP address of the Docker host. See the "Running on a LAN environment" section
# in the README.
DOCKER_HOST_ADDRESS=125.210.100.177

#
# Let's Encrypt configuration
#

# Enable Let's Encrypt certificate generation.
#ENABLE_LETSENCRYPT=1

# Domain for which to generate the certificate.
#LETSENCRYPT_DOMAIN=meet.example.com

# E-Mail for receiving important account notifications (mandatory).
#LETSENCRYPT_EMAIL=alice@atlanta.net

#
# Etherpad integration (for document sharing)
#

# Set etherpad-lite URL (uncomment to enable).
#ETHERPAD_URL_BASE=http://etherpad.meet.jitsi:9001

#
# Basic Jigasi configuration options (needed for SIP gateway support)
#

# SIP URI for incoming / outgoing calls.
#JIGASI_SIP_URI=test@sip2sip.info

# Password for the specified SIP account as a clear text
#JIGASI_SIP_PASSWORD=passw0rd

# SIP server (use the SIP account domain if in doubt).
#JIGASI_SIP_SERVER=sip2sip.info

# SIP server port
#JIGASI_SIP_PORT=5060

# SIP server transport
#JIGASI_SIP_TRANSPORT=UDP

#
# Authentication configuration (see README for details)
#

# Enable authentication.
#ENABLE_AUTH=1

# Enable guest access.
#ENABLE_GUESTS=1

# Select authentication type: internal, jwt or ldap
#AUTH_TYPE=internal

# JWT auuthentication
#

# Application identifier.
#JWT_APP_ID=my_jitsi_app_id

# Application secret known only to your token.
#JWT_APP_SECRET=my_jitsi_app_secret

# (Optional) Set asap_accepted_issuers as a comma separated list.
#JWT_ACCEPTED_ISSUERS=my_web_client,my_app_client

# (Optional) Set asap_accepted_audiences as a comma separated list.
#JWT_ACCEPTED_AUDIENCES=my_server1,my_server2

# LDAP authentication (for more information see the Cyrus SASL saslauthd.conf man page)
#

# LDAP url for connection.
#LDAP_URL=ldaps://ldap.domain.com/

# LDAP base DN. Can be empty
#LDAP_BASE=DC=example,DC=domain,DC=com

# LDAP user DN. Do not specify this parameter for the anonymous bind.
#LDAP_BINDDN=CN=binduser,OU=users,DC=example,DC=domain,DC=com

# LDAP user password. Do not specify this parameter for the anonymous bind.
#LDAP_BINDPW=LdapUserPassw0rd

# LDAP filter. Tokens example:
# %1-9 - if the input key is user@mail.domain.com, then %1 is com, %2 is domain and %3 is mail.
# %s - %s is replaced by the complete service string.
# %r - %r is replaced by the complete realm string.
#LDAP_FILTER=(sAMAccountName=%u)

# LDAP authentication method
#LDAP_AUTH_METHOD=bind

# LDAP version
#LDAP_VERSION=3

# LDAP TLS using
#LDAP_USE_TLS=1

# List of SSL/TLS ciphers to allow.
#LDAP_TLS_CIPHERS=SECURE256:SECURE128:!AES-128-CBC:!ARCFOUR-128:!CAMELLIA-128-CBC:!3DES-CBC:!CAMELLIA-128-CBC

# Require and verify server certificate
#LDAP_TLS_CHECK_PEER=1

# Path to CA cert file. Used when server sertificate verify is enabled.
#LDAP_TLS_CACERT_FILE=/etc/ssl/certs/ca-certificates.crt

# Path to CA certs directory. Used when server sertificate verify is enabled.
#LDAP_TLS_CACERT_DIR=/etc/ssl/certs

#
# Advanced configuration options (you generally don't need to change these)
#

# Internal XMPP domain.
XMPP_DOMAIN=meet.jitsi

# Internal XMPP server
XMPP_SERVER=xmpp.meet.jitsi

# Internal XMPP server URL
XMPP_BOSH_URL_BASE=http://xmpp.meet.jitsi:5280

# Internal XMPP domain for authenticated services.
XMPP_AUTH_DOMAIN=auth.meet.jitsi

# XMPP domain for the MUC.
XMPP_MUC_DOMAIN=muc.meet.jitsi

# XMPP domain for the internal MUC used for jibri, jigasi and jvb pools.
XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi

# XMPP domain for unauthenticated users.
XMPP_GUEST_DOMAIN=guest.meet.jitsi

# Custom Prosody modules for XMPP_DOMAIN (comma separated)
XMPP_MODULES=

# Custom Prosody modules for MUC component (comma separated)
XMPP_MUC_MODULES=

# Custom Prosody modules for internal MUC component (comma separated)
XMPP_INTERNAL_MUC_MODULES=

# MUC for the JVB pool.
JVB_BREWERY_MUC=jvbbrewery

# XMPP user for JVB client connections.
JVB_AUTH_USER=jvb

# XMPP password for JVB client connections.
JVB_AUTH_PASSWORD=passw0rd

# STUN servers used to discover the server's public IP.
#JVB_STUN_SERVERS=stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302
JVB_STUN_SERVERS=stun.freeswitch.org,stun.ideasip.com

# Media port for the Jitsi Videobridge
JVB_PORT=10000

# TCP Fallback for Jitsi Videobridge for when UDP isn't available
JVB_TCP_HARVESTER_DISABLED=true
JVB_TCP_PORT=4443

# A comma separated list of APIs to enable when the JVB is started. The default is none.
# See https://github.com/jitsi/jitsi-videobridge/blob/master/doc/rest.md for more information
#JVB_ENABLE_APIS=rest,colibri

# XMPP component password for Jicofo.
JICOFO_COMPONENT_SECRET=s3cr37

# XMPP user for Jicofo client connections. NOTE: this option doesn't currently work due to a bug.
JICOFO_AUTH_USER=focus

# XMPP password for Jicofo client connections.
JICOFO_AUTH_PASSWORD=passw0rd

# Base URL of Jicofo's reservation REST API
#JICOFO_RESERVATION_REST_BASE_URL=http://reservation.example.com

# XMPP user for Jigasi MUC client connections.
JIGASI_XMPP_USER=jigasi

# XMPP password for Jigasi MUC client connections.
JIGASI_XMPP_PASSWORD=passw0rd

# MUC name for the Jigasi pool.
JIGASI_BREWERY_MUC=jigasibrewery

# Minimum port for media used by Jigasi.
JIGASI_PORT_MIN=20000

# Maximum port for media used by Jigasi.
JIGASI_PORT_MAX=20050

# Enable SDES srtp
#JIGASI_ENABLE_SDES_SRTP=1

# Keepalive method
#JIGASI_SIP_KEEP_ALIVE_METHOD=OPTIONS

# Health-check extension
#JIGASI_HEALTH_CHECK_SIP_URI=keepalive

# Health-check interval
#JIGASI_HEALTH_CHECK_INTERVAL=300000
#
# Enable Jigasi transcription.
#ENABLE_TRANSCRIPTIONS=1

# Jigasi will recordord an audio when transcriber is on. Default false.
#JIGASI_TRANSCRIBER_RECORD_AUDIO=true

# Jigasi will send transcribed text to the chat when transcriber is on. Default false.
#JIGASI_TRANSCRIBER_SEND_TXT=true

# Jigasi post to the chat an url with transcription file. Default false.
#JIGASI_TRANSCRIBER_ADVERTISE_URL=true

# Credentials for connect to Cloud Google API from Jigasi. Path located inside the container.
# Please read https://cloud.google.com/text-to-speech/docs/quickstart-protocol
# section "Before you begin" from 1 to 5 paragraph. Copy the key on
# the docker host to ${CONFIG}/jigasi/key.json and to enable this setting:
#GOOGLE_APPLICATION_CREDENTIALS=/config/key.json

# Enable recording
#ENABLE_RECORDING=1

# XMPP domain for the jibri recorder
XMPP_RECORDER_DOMAIN=recorder.meet.jitsi

# XMPP recorder user for Jibri client connections.
JIBRI_RECORDER_USER=recorder

# XMPP recorder password for Jibri client connections.
JIBRI_RECORDER_PASSWORD=passw0rd

# Directory for recordings inside Jibri container.
JIBRI_RECORDING_DIR=/config/recordings

# The finalizing script. Will run after recording is complete.
JIBRI_FINALIZE_RECORDING_SCRIPT_PATH=/config/finalize.sh

# XMPP user for Jibri client connections.
JIBRI_XMPP_USER=jibri

# XMPP password for Jibri client connections.
JIBRI_XMPP_PASSWORD=passw0rd

# MUC name for the Jibri pool.
JIBRI_BREWERY_MUC=jibribrewery

# MUC connection timeout
JIBRI_PENDING_TIMEOUT=90

# When jibri gets a request to start a service for a room, the room
# jid will look like: roomName@optional.prefixes.subdomain.xmpp_domain
# We'll build the url for the call by transforming that into:
# https://xmpp_domain/subdomain/roomName
# So if there are any prefixes in the jid (like jitsi meet, which
# has its participants join a muc at conference.xmpp_domain) then
# list that prefix here so it can be stripped out to generate
# the call url correctly.
JIBRI_STRIP_DOMAIN_JID=muc

# Directory for logs inside Jibri container.
JIBRI_LOGS_DIR=/config/logs

# Disable HTTPS. This can be useful if TLS connections are going to be handled outside of this setup.
#DISABLE_HTTPS=1

# Redirects HTTP traffic to HTTPS. Only works with the standard HTTPS port (443).
#ENABLE_HTTP_REDIRECT=1

The main err log is 
jicofo_1_d174c70fe1f3 | Jicofo 2020-02-08 12:19:35.278 SEVERE: [10] **impl.configuration.ConfigurationActivator.log() Error creating c lib instance for fixing file permissions
jicofo_1_d174c70fe1f3 | java.nio.file.FileSystemException: /config: Operation not permitted**
jicofo_1_d174c70fe1f3 |         at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
jicofo_1_d174c70fe1f3 |         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
jicofo_1_d174c70fe1f3 |         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
jicofo_1_d174c70fe1f3 |         at sun.nio.fs.UnixFileAttributeViews$Posix.setMode(UnixFileAttributeViews.java:238)
jicofo_1_d174c70fe1f3 |         at sun.nio.fs.UnixFileAttributeViews$Posix.setPermissions(UnixFileAttributeViews.java:260)
jicofo_1_d174c70fe1f3 |         at java.nio.file.Files.setPosixFilePermissions(Files.java:2045)
jicofo_1_d174c70fe1f3 |         at net.java.sip.communicator.impl.configuration.ConfigurationActivator.fixPermissions(ConfigurationActivator.java:167)
jicofo_1_d174c70fe1f3 |         at net.java.sip.communicator.impl.configuration.ConfigurationActivator.start(ConfigurationActivator.java:88)
jicofo_1_d174c70fe1f3 |         at org.jitsi.impl.osgi.framework.BundleImpl.start(BundleImpl.java:307)
jicofo_1_d174c70fe1f3 |         at org.jitsi.impl.osgi.framework.launch.FrameworkImpl.startLevelChanged(FrameworkImpl.java:472)
jicofo_1_d174c70fe1f3 |         at org.jitsi.impl.osgi.framework.startlevel.FrameworkStartLevelImpl$Command.run(FrameworkStartLevelImpl.java:137)
jicofo_1_d174c70fe1f3 |         at org.jitsi.impl.osgi.framework.AsyncExecutor.runInThread(AsyncExecutor.java:122)
jicofo_1_d174c70fe1f3 |         at org.jitsi.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:28)
jicofo_1_d174c70fe1f3 |         at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:231)

jvb_1_422405a66ca1 | JVB 2020-02-08 12:19:42.424 WARNING: [14] org.jitsi.videobridge.stats.MucStatsTransport.publishStatistics().69 Can not publish via presence, no ClientConnectionImpl.
jicofo_1_d174c70fe1f3 | Jicofo 2020-02-08 12:19:42.457 INFO: [16] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.doConnect().299 XMPP provider Jabber:focus@auth.meet.jitsi/focus9406846407542403@xmpp.meet.jitsi connected (JID: focus@auth.meet.jitsi/focus9406846407542403)
jvb_1_422405a66ca1 | JVB 2020-02-08 12:19:43.215 SEVERE: [18] **org.jitsi.videobridge.health.Health.log() Health check failed in 5092ms:**
jvb_1_422405a66ca1 | java.lang.NullPointerException
jvb_1_422405a66ca1 |    at org.ice4j.ice.Agent.<init>(Agent.java:407)
jvb_1_422405a66ca1 |    at org.jitsi.videobridge.IceUdpTransportManager.createIceAgent(IceUdpTransportManager.java:1070)
jvb_1_422405a66ca1 |    at org.jitsi.videobridge.IceUdpTransportManager.<init>(IceUdpTransportManager.java:566)
jvb_1_422405a66ca1 |    at org.jitsi.videobridge.IceUdpTransportManager.<init>(IceUdpTransportManager.java:527)
jvb_1_422405a66ca1 |    at org.jitsi.videobridge.Channel.createTransportManager(Channel.java:323)
jvb_1_422405a66ca1 |    at org.jitsi.videobridge.Channel.initialize(Channel.java:674)
jvb_1_422405a66ca1 |    at org.jitsi.videobridge.RtpChannel.initialize(RtpChannel.java:895)
jvb_1_422405a66ca1 |    at org.jitsi.videobridge.Content.createRtpChannel(Content.java:340)
jvb_1_422405a66ca1 |    at org.jitsi.videobridge.Content.createRtpChannel(Content.java:264)
jvb_1_422405a66ca1 |    at org.jitsi.videobridge.health.Health.check(Health.java:152)
jvb_1_422405a66ca1 |    at org.jitsi.videobridge.health.Health.doCheck(Health.java:244)
jvb_1_422405a66ca1 |    at org.jitsi.videobridge.health.Health.doRun(Health.java:495)
jvb_1_422405a66ca1 |    at org.jitsi.utils.concurrent.PeriodicRunnableWithObject.run(PeriodicRunnableWithObject.java:87)
jvb_1_422405a66ca1 |    at org.jitsi.utils.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)
jvb_1_422405a66ca1 |    at org.jitsi.utils.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)
jvb_1_422405a66ca1 |    at org.jitsi.utils.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
jvb_1_422405a66ca1 |    at org.jitsi.utils.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)

**Comment by saghul** [comment]
Can you extract the jicofo, JVB and web logs and upload then as a gist? It’s hard to read them like this. Also, running the setup as root is not a good idea and you may run into problems, I suggest you use a regular user.

Also, if you modified the .env file after starting the containers, you’ll need to delete the $CONFIG directory, so it’s regenerated.

**Comment by pansj2020** [comment]
Thank you for your replay . I follow your suggestion . Create user jitsi , use jitsi run ./docker-compose up. But  the same error . I can see the log after run ./docker-compose up.

1. I don't konw how to extract the jicofo, JVB and web logs from docker
2. how to upload log as a gist

**Comment by pansj2020** [comment]
[jicofo.log](https://github.com/jitsi/docker-jitsi-meet/files/4173973/jicofo.log)
[jvb.log](https://github.com/jitsi/docker-jitsi-meet/files/4173974/jvb.log)
[web.log](https://github.com/jitsi/docker-jitsi-meet/files/4173975/web.log)
[env.log](https://github.com/jitsi/docker-jitsi-meet/files/4173977/env.log)


I have upload jicofo/jvb/web  log , and my .env

**Comment by pansj2020** [comment]
OS：CentOS Linux release 7.6.1810 (Core) 
Docker：Docker version 19.03.5, build 633a0ea
Server：vsphere VM  1CPU  /  8GB Memory

**Comment by pansj2020** [comment]
> Can you extract the jicofo, JVB and web logs and upload then as a gist? It’s hard to read them like this. Also, running the setup as root is not a good idea and you may run into problems, I suggest you use a regular user.
> 
> Also, if you modified the .env file after starting the containers, you’ll need to delete the $CONFIG directory, so it’s regenerated.

I followed your suggestion , create user jitsi , and use jitsi to run docker-compose up , but get the same error. The error log is upload . Can you give me some advice ? I confuse it many days

**Comment by saghul** [comment]
Did you intend to close this?
