### ISSUE TITLE
How do you change the logo?

### ISSUE THREAD

**Issue by 0187773933** [jitsi/docker-jitsi-meet#187]
https://github.com/jitsi/jitsi-meet/issues/797

I can't find any of the html or css files after installing via docker

**Comment by 0187773933** [comment]
Modifying interface_config.js didn't change anything. Even after 
docker-compose up -d --force-recreate

**Comment by saghul** [comment]
You need to change the interface_config.js in the $CONFIG directory.

**Comment by jabiertxof** [comment]
how you do it?

**Comment by saghul** [comment]
Oops, I was wrong. You need to replace the /usr/share/jitsi-meet/images/watermark.png file in the web container.

**Comment by jabiertxof** [comment]
thanks also found in my home folder the hidden $CONFIG directory, for help configuring further people

**Comment by ovimano** [comment]
You can create a new volume in docker-compose.yml for the png.

volumes:
               - .....
               - .......
               - /home/user/watermark.png:/usr/share/jitsi-meet/images/watermark.png

And recreate the containers.

Put the png in /home/user/watermark.png and that's it!

**Comment by jabiertxof** [comment]
thanks!

**Comment by TheoOliveira** [comment]
I've tried to add like you guys did, but it doesn't work. What it could be? Says image not found. Not sure why.

**Comment by JacBra** [comment]
I think there was a change in interface_config.js:

    DEFAULT_LOGO_URL: 'images/watermark.png',
    DEFAULT_WELCOME_PAGE_LOGO_URL: 'images/watermark.png',

was changed to 

    DEFAULT_LOGO_URL: 'images/watermark.svg',
    DEFAULT_WELCOME_PAGE_LOGO_URL: 'images/watermark.svg',

so by default you now need an svg file (or change it in interface_config.js back to png)

**Comment by hypocinose** [comment]
Hi!
I had the same problem and I changed the config file to
```
DEFAULT_LOGO_URL: 'images/mywatermark.png',
DEFAULT_WELCOME_PAGE_LOGO_URL: 'images/mywatermark.png',
```
and copied mywatermark.png into the container using docker cp
That worked quite well, but the new watermark is extremely tiny, because there is a size limit on it. You can see that when you inspect that element in your browser:
```
background-image: url("images/mywatermark.png"); max-width: 140px; max-height: 70px;
```
Where does that come from?
BR

**Comment by TonyMugwump** [comment]
> and copied mywatermark.png into the container using docker cp That worked quite well, but the new watermark is extremely tiny, because there is a size limit on it. You can see that when you inspect that element in your browser:
> ```
> background-image: url("images/mywatermark.png"); max-width: 140px; max-height: 70px;
> ```
> Where does that come from? BR

from all.css
look for ".welcome-watermark .watermark.leftwatermark" , there the logo size is defined

**Comment by Tring-Bhavesh** [comment]
Add this line to the volume of the web container

volumes:
- path/watermark.svg:/usr/share/jitsi-meet/images/watermark.svg

Put the svg in the path mentions and restart or start the containers

**Comment by e1ke** [comment]
i found out that the /usr/share/jitsi-meet/images directory in the jitsi web container is empty, is that intended?
Eitherway I put a watermark.svg in it, it got changed but now i cannot change it again and the test svg (a compact-disc svg :D) is stuck to it forever.
How can i change it again? I cant find the 'acutal' watermark.svg. Also i would like to change the Website titel 'Jitsi Meet' to my own...
