### ISSUE TITLE
I can't start with docker ,pls help me ,the log is 

### ISSUE THREAD

**Issue by xieqq8** [jitsi/docker-jitsi-meet#1870]
✔ Container docker-jitsi-meet-prosody-1  Created                                                                                                  0.0s 
 ✔ Container docker-jitsi-meet-jvb-1      Created                                                                                                  0.0s 
 ✔ Container docker-jitsi-meet-web-1      Created                                                                                                  0.0s 
 ✔ Container docker-jitsi-meet-jicofo-1   Created                                                                                                  0.0s 
Attaching to jicofo-1, jvb-1, prosody-1, web-1
prosody-1  | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
prosody-1  | [s6-init] ensuring user provided files have correct perms...exited 0.
prosody-1  | [fix-attrs.d] applying ownership & permissions fixes...
prosody-1  | [fix-attrs.d] done.
prosody-1  | [cont-init.d] executing container initialization scripts...
prosody-1  | [cont-init.d] 01-set-timezone: executing... 
prosody-1  | [cont-init.d] 01-set-timezone: exited 0.
prosody-1  | [cont-init.d] 10-config: executing... 
prosody-1  | fatal: render template error, caused:
prosody-1  | 
prosody-1  |    template: /defaults/conf.d/jitsi-meet.cfg.lua:15:45: executing "/defaults/conf.d/jitsi-meet.cfg.lua" at <.Env.XMPP_MUC_DOMAIN>: invalid value; expected string
prosody-1  | 
prosody-1  | Please specify which host you want to register the user on
prosody-1  | Usage: /usr/bin/prosodyctl register USER HOST [PASSWORD]
prosody-1  |  Register a user on the server, with the given password
prosody-1  | modulemanager       error  Unable to load module 'roster_command': /usr/lib/prosody/modules/mod_roster_command.lua: No such file or directory
prosody-1  | Failed to load module 'roster_command': /usr/lib/prosody/modules/mod_roster_command.lua: No such file or directory
prosody-1  | Please specify which host you want to register the user on
prosody-1  | Usage: /usr/bin/prosodyctl register USER HOST [PASSWORD]
prosody-1  |  Register a user on the server, with the given password
prosody-1  | You need to supply at least one hostname
prosody-1  | Usage: /usr/bin/prosodyctl cert generate HOSTNAME [HOSTNAME+]
prosody-1  |  Generates a self-signed certificate for the current hostname(s)
prosody-1  | You need to supply at least one hostname
prosody-1  | Usage: /usr/bin/prosodyctl cert generate HOSTNAME [HOSTNAME+]
prosody-1  |  Generates a self-signed certificate for the current hostname(s)
prosody-1  | mv: cannot stat '/config/data/*.crt': No such file or directory
prosody-1  | mv: cannot stat '/config/data/*.key': No such file or directory
jicofo-1   | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
prosody-1  | [cont-init.d] 10-config: exited 0.
prosody-1  | [cont-init.d] done.
prosody-1  | [services.d] starting services
prosody-1  | [services.d] done.
prosody-1  | saslauthd[234] :num_procs  : 5
prosody-1  | saslauthd[234] :mech_option: /etc/saslauthd.conf
prosody-1  | saslauthd[234] :run_path   : /var/run/saslauthd
prosody-1  | saslauthd[234] :auth_mech  : ldap
prosody-1  | startup             error  No enabled VirtualHost entries found in the config file.
prosody-1  | startup             error  At least one active host is required for Prosody to function. Exiting...
prosody-1  | saslauthd[234] :mmaped shared memory segment on file: /var/run/saslauthd/cache.mmap
prosody-1  | saslauthd[234] :bucket size: 96 bytes
prosody-1  | saslauthd[234] :stats size : 36 bytes
prosody-1  | saslauthd[234] :timeout    : 28800 seconds
prosody-1  | saslauthd[234] :cache table: 985828 total bytes
prosody-1  | saslauthd[234] :cache table: 1711 slots
prosody-1  | saslauthd[234] :cache table: 10266 buckets
prosody-1  | saslauthd[234] :flock file opened at /var/run/saslauthd/cache.flock
prosody-1  | saslauthd[234] :using accept lock file: /var/run/saslauthd/mux.accept
prosody-1  | saslauthd[234] :master pid is: 0
prosody-1  | saslauthd[234] :listening on socket: /var/run/saslauthd/mux
prosody-1  | saslauthd[234] :using process model
prosody-1  | saslauthd[234] :forked child: 252
prosody-1  | saslauthd[252] :acquired accept lock
prosody-1  | saslauthd[234] :forked child: 253
prosody-1  | saslauthd[234] :forked child: 254
prosody-1  | saslauthd[234] :forked child: 255
jicofo-1   | [s6-init] ensuring user provided files have correct perms...exited 0.
jicofo-1   | [fix-attrs.d] applying ownership & permissions fixes...
jicofo-1   | [fix-attrs.d] done.
jicofo-1   | [cont-init.d] executing container initialization scripts...
jicofo-1   | [cont-init.d] 01-set-timezone: executing... 
jvb-1      | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
jicofo-1   | [cont-init.d] 01-set-timezone: exited 0.
jicofo-1   | [cont-init.d] 10-config: executing... 
jicofo-1   | [cont-init.d] 10-config: exited 0.
jvb-1      | [s6-init] ensuring user provided files have correct perms...exited 0.
jicofo-1   | [cont-init.d] done.
jicofo-1   | [services.d] starting services
jvb-1      | [fix-attrs.d] applying ownership & permissions fixes...
jvb-1      | [fix-attrs.d] done.
jvb-1      | [cont-init.d] executing container initialization scripts...
jvb-1      | [cont-init.d] 01-set-timezone: executing... 
jicofo-1   | [services.d] done.
jvb-1      | [cont-init.d] 01-set-timezone: exited 0.
jvb-1      | [cont-init.d] 10-config: executing... 
jvb-1      | Error: any valid prefix is expected rather than "l.root-servers.net.".
jvb-1      | [cont-init.d] 10-config: exited 0.
jvb-1      | [cont-init.d] done.
jvb-1      | [services.d] starting services
jvb-1      | [services.d] done.
web-1      | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
jicofo-1   | Aug 02, 2024 4:24:18 PM org.jitsi.utils.logging2.LoggerImpl log
jicofo-1   | INFO: Starting Jicofo.
jicofo-1   | Aug 02, 2024 4:24:18 PM org.jitsi.utils.logging.LoggerImpl log
jicofo-1   | WARNING: Skipped empty cmd line argument: domain=
jicofo-1   | Aug 02, 2024 4:24:18 PM org.jitsi.utils.logging.LoggerImpl log
jicofo-1   | WARNING: Skipped empty cmd line argument: host=
jicofo-1   | Aug 02, 2024 4:24:18 PM org.jitsi.utils.logging.LoggerImpl log
jicofo-1   | WARNING: Skipped empty cmd line argument: user_name=
jicofo-1   | Aug 02, 2024 4:24:18 PM org.jitsi.utils.logging.LoggerImpl log
jicofo-1   | WARNING: Skipped empty cmd line argument: user_domain=
web-1      | [s6-init] ensuring user provided files have correct perms...exited 0.
web-1      | [fix-attrs.d] applying ownership & permissions fixes...
web-1      | [fix-attrs.d] done.
web-1      | [cont-init.d] executing container initialization scripts...
web-1      | [cont-init.d] 01-set-timezone: executing... 
web-1      | [cont-init.d] 01-set-timezone: exited 0.
web-1      | [cont-init.d] 10-config: executing... 
web-1      | using keys found in /config/keys
web-1      | fatal: render template error, caused:
web-1      | 
web-1      |    template: /defaults/system-config.js:11:45: executing "/defaults/system-config.js" at <.Env.XMPP_MUC_DOMAIN>: invalid value; expected string
web-1      | 
web-1      | [cont-init.d] 10-config: exited 0.
web-1      | [cont-init.d] done.
web-1      | [services.d] starting services
web-1      | [services.d] done.
web-1      | nginx: [emerg] invalid number of arguments in "proxy_pass" directive in /config/nginx/meet.conf:59
jicofo-1   | Aug 02, 2024 4:24:19 PM org.jitsi.utils.logging2.LoggerImpl log
jicofo-1   | INFO: Initialized newConfig: merge of /config/jicofo.conf: 1,system properties,reference.conf @ jar:file:/usr/share/jicofo/jicofo.jar!/reference.conf: 1
jicofo-1   | Aug 02, 2024 4:24:19 PM org.jitsi.utils.logging2.LoggerImpl log
jicofo-1   | INFO: net.java.sip.communicator.SC_HOME_DIR_LOCATION not set
jicofo-1   | Aug 02, 2024 4:24:19 PM org.jitsi.utils.logging2.LoggerImpl log
jicofo-1   | INFO: Initialized legacyConfig: sip communicator props (no description provided)
jicofo-1   | Aug 02, 2024 4:24:19 PM org.jitsi.utils.logging2.LoggerImpl log
jicofo-1   | INFO: Reloading the Typesafe config source (previously reloaded 0 times).

**Comment by xieqq8** [comment]
prosody-1  | modulemanager       error  Unable to load module 'roster_command': /usr/lib/prosody/modules/mod_roster_command.lua: No such file or directory

prosody-1  | startup             error  No enabled VirtualHost entries found in the config file.
prosody-1  | startup             error  At least one active host is required for Prosody to function. Exiting...

web-1      | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
web-1      | [s6-init] ensuring user provided files have correct perms...exited 0.


this is the error log

**Comment by xieqq8** [comment]
docker-jitsi-meet-web-1 log:
nginx: [emerg] invalid number of arguments in "proxy_pass" directive in /config/nginx/meet.conf:59

docker-jitsi-meet-prosody-1 log:
startup             error       No enabled VirtualHost entries found in the config file.
startup             error       At least one active host is required for Prosody to function. Exiting...

docker-jitsi-meet-jicofo-1 log:
SEVERE: Failed to connect/login: The following addresses failed: 'RFC 6120 A/AAAA Endpoint + [localhost:5222] (localhost/127.0.0.1:5222)' failed because: java.net.ConnectException: Connection refused (Connection refused), 'RFC 6120 A/AAAA Endpoint + [localhost:5222] (localhost/0:0:0:0:0:0:0:1:5222)' failed because: java.net.ConnectException: Connection refused (Connection refused)
org.jivesoftware.smack.SmackException$EndpointConnectionException: The following addresses failed: 'RFC 6120 A/AAAA Endpoint + [localhost:5222] (localhost/127.0.0.1:5222)' failed because: java.net.ConnectException: Connection refused (Connection refused), 'RFC 6120 A/AAAA Endpoint + [localhost:5222] (localhost/0:0:0:0:0:0:0:1:5222)' failed because: java.net.ConnectException: Connection refused (Connection refused)
        at org.jivesoftware.smack.SmackException$EndpointConnectionException.from(SmackException.java:334)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectUsingConfiguration(XMPPTCPConnection.java:663)
        at org.jivesoftware.smack.tcp.XMPPTCPConnection.connectInternal(XMPPTCPConnection.java:846)
        at org.jivesoftware.smack.AbstractXMPPConnection.connect(AbstractXMPPConnection.java:529)
        at org.jitsi.impl.protocol.xmpp.XmppProviderImpl.doConnect(XmppProviderImpl.java:205)
        at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:167)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by saghul** [comment]
Do you have an .env file? What does it contain?

**Comment by xieqq8** [comment]
> Do you have an .env file? What does it contain?

yes, I have .env file. 
JITSI_IMAGE_VERSION=latest

ENABLE_XMPP_WEBSOCKET=0
ENABLE_GUESTS=1

JVB_PORT=10000
JVB_AUTH_USER=jvb
JVB_BREWERY_MUC=jvbbrewery
JVB_XMPP_INTERNAL_MUC_DOMAIN=muc.jvb.meet.jitsi
XMPP_INTERNAL_MUC_DOMAIN=internal-muc.meet.jitsi
JVB_XMPP_SERVER=xmpp.jvb.meet.jitsi
JIGASI_XMPP_USER=jigasi
JIBRI_XMPP_USER=jibri
XMPP_DOMAIN=meet.jitsi
XMPP_AUTH_DOMAIN=auth.meet.jitsi
XMPP_MUC_DOMAIN=muc.meet.jitsi
XMPP_BOSH_URL_BASE=http://xmpp.meet.jitsi:5280

but the general config has <no value>, such as admins = {
    "<no value>@auth.meet.jitsi",
    "jvb@auth.meet.jitsi"
}

unlimited_jids = {
    "<no value>@auth.meet.jitsi",
    "jvb@auth.meet.jitsi"
}


    xmpp {
      client {
        enabled = true
        hostname = "<no value>"
        domain = "auth.meet.jitsi"
        username = "<no value>"
        password = "ac74ce366cb07937b93f506a10066a0a"  
        conference-muc-jid = "muc.meet.jitsi"
        client-proxy = "focus.meet.jitsi"
        disable-certificate-verification = true
      }
    }

**Comment by saghul** [comment]
Please follow these instructions: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker

The "latest" tag is deprecated.

**Comment by xieqq8** [comment]
tks, I start  success
