### ISSUE TITLE
Docker Based Jitsi Setup

### ISSUE THREAD

**Issue by DeepJoshi4393** [jitsi/docker-jitsi-meet#1873]
How can I achieve this in a Docker-based Jitsi environment? Also, what do you mean by '{api_prefix}'?

**Comment by saghul** [comment]
Achieve what exactly? You can get started here: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#quick-start



> Also, what do you mean by '{api_prefix}'?

Where does that coome from?

**Comment by DeepJoshi4393** [comment]
Sorry for not mentioning details earlier. I am trying to integrate the custom prosody module https://github.com/jitsi-contrib/prosody-plugins/tree/main/event_sync with our setup. Could you please help me on that or Is there a way to retrieve all conference details from our server, including the conference name, attendee first names, last names, emails, number of participants, total conference time, start time, end time of the conference, and information for each attendee?

**Comment by saghul** [comment]
Please use our community forum (https://community.jitsi.org) for deployment questions. We use thebug tracker for issues and feature requests.
