### ISSUE TITLE
Error When Starting a Meeting in Jitsi XMPP Server on Kubernetes

### ISSUE THREAD

**Issue by jayrajmeh0** [jitsi/docker-jitsi-meet#1875]
**Description**:
- I'm currently working on setting up a Jitsi XMPP server for a video call application in Kubernetes. The setup is complete, and all pods are running as expected. However, when I attempt to start a meeting, I encounter an error.

**Steps to Reproduce:**
- Deploy Jitsi XMPP server on Kubernetes.
- Start a meeting using the application.
- Observe the error that occurs.

**Expected Behavior:**
- The meeting should start successfully without errors.

**Actual Behavior:**
- An error occurs when starting the meeting. (Please refer to the attached screenshot for more details.)

**Environment:**
- Jitsi XMPP server version: [insert version]
- Kubernetes version: [insert version]
- Any relevant configurations or logs.
- Additional Information:

**Please find the attached screenshot of the error message.**
![Screenshot_786](https://github.com/user-attachments/assets/9217da5d-ef8d-4061-8a1c-c16f3d2047c8)
![Screenshot_785](https://github.com/user-attachments/assets/31e63165-7594-464d-ac05-3a74c53d89f5)
![Screenshot_787](https://github.com/user-attachments/assets/e6d84899-b323-49c3-bb41-92d86d663320)
![Screenshot_788](https://github.com/user-attachments/assets/9d85520b-01a6-474e-8c7c-44f544429acf)

**Comment by jayrajmeh0** [comment]
**@madmatah @duritong @soletan @JakubOnderka Do you have any answers related to how to resolve this issue? Please provide me with an answer.**

**Comment by aaronkvanmeerten** [comment]
Are you using the helm charts from https://github.com/jitsi-contrib/jitsi-helm ? If so, this is not the correct repo to report any problems. please use that repo instead. 

Also, I noticed you did not include any logs. The web browser is not going to be able to show you what is happening inside the containers. When reporting such issues in future, please include logs from all of the containers and not simply screenshots from your web browser.
