### ISSUE TITLE
Jitsi room Crash when another user joins

### ISSUE THREAD

**Issue by pansj2020** [jitsi/docker-jitsi-meet#188]
Hello , I am from China , Now WuHan virus is serious. We want to use jitsi-meet to reduce people gather. I also hope it can help students study at their home.

But when I use docker-jitsi-meet , ./docker-compose up , it come's some error. When I jion the meeting, it works OK . But when second one join in , room crash , and show reconnecting.

I have read some comments in issues before, but I cann't resolve it , please give me some help, thanks

My environment
OS：CentOS Linux release 7.6.1810 (Core)
Docker：Docker version 19.03.5, build 633a0ea
Server：vsphere VM 1CPU / 8GB Memory

My install setup 
1、git clone https://github.com/jitsi/docker-jitsi-meet && cd docker-jitsi-meet
2、cp env.example .env
3、vi .env  (modiy config)
4、./docker-compose up
I aslo use root or normal user  run it. But the same error.

[env.log](https://github.com/jitsi/docker-jitsi-meet/files/4179176/env.log)
[jicofo.log](https://github.com/jitsi/docker-jitsi-meet/files/4179177/jicofo.log)
[jvb.log](https://github.com/jitsi/docker-jitsi-meet/files/4179178/jvb.log)
[web.log](https://github.com/jitsi/docker-jitsi-meet/files/4179179/web.log)

**Comment by saghul** [comment]
Why did you close https://github.com/jitsi/docker-jitsi-meet/issues/185 and open this one?

**Comment by pansj2020** [comment]
I reorganize text  for see  clearly ，and  hope someone can help me

**Comment by Stones3ma** [comment]
I had the same problem！！！

**Comment by petjiang** [comment]
the same problem too !!! expecting !!

**Comment by petjiang** [comment]
the same problem too !!! expecting !!

----------
when the second user join the conference, both session crashed.and in jvb log , i saw these:
jvb_1      | JVB 2020-02-11 05:14:20.089 WARNING: [32] org.jitsi.videobridge.EndpointMessageTransport.log() SCTP connection with 6d2b383a not ready yet. 
jvb_1      | JVB 2020-02-11 05:14:20.147 WARNING: [32] org.jitsi.videobridge.EndpointMessageTransport.log() SCTP connection with 13e462ef not ready yet. 
jvb_1      | JVB 2020-02-11 05:14:20.301 INFO: [266] org.jitsi.videobridge.SctpConnection.log() SCTP socket accepted on conf_id=6686b9fa8de5de95,content=data,ch_id=86642c9b96a268e,endp_id=6d2b383a 
jvb_1      | JVB 2020-02-11 05:14:20.449 WARNING: [270] org.jitsi.videobridge.EndpointMessageTransport.log() SCTP connection with 13e462ef not ready yet. 
jvb_1      | JVB 2020-02-11 05:14:21.528 WARNING: [32] org.jitsi.videobridge.EndpointMessageTransport.log() SCTP connection with 6d2b383a not ready yet. 
jvb_1      | JVB 2020-02-11 05:14:21.528 WARNING: [222] org.jitsi.videobridge.EndpointMessageTransport.log() SCTP connection with 13e462ef not ready yet. 
jvb_1      | JVB 2020-02-11 05:14:21.528 WARNING: [32] org.jitsi.videobridge.EndpointMessageTransport.log() SCTP connection with 13e462ef not ready yet. 
jvb_1      | JVB 2020-02-11 05:14:21.560 SEVERE: [256] org.jitsi.videobridge.SctpConnection.log() Error accepting SCTP connection conf_id=6686b9fa8de5de95,content=data,ch_id=326296dddc54c59b,endp_id=13e462ef

**Comment by pansj2020** [comment]
When I docker-compose up , do you see this error ?

Jicofo.log 
`jicofo_1_d0b2d814e78a | Jicofo 2020-02-10 06:54:51.182 SEVERE: [10] impl.configuration.ConfigurationActivator.log() Error creating c lib instance for fixing file permissions
jicofo_1_d0b2d814e78a | java.nio.file.FileSystemException: /config: Operation not permitted
jicofo_1_d0b2d814e78a |         at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
jicofo_1_d0b2d814e78a |         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
jicofo_1_d0b2d814e78a |         at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
jicofo_1_d0b2d814e78a |         at sun.nio.fs.UnixFileAttributeViews$Posix.setMode(UnixFileAttributeViews.java:238)
jicofo_1_d0b2d814e78a |         at sun.nio.fs.UnixFileAttributeViews$Posix.setPermissions(UnixFileAttributeViews.java:260)
jicofo_1_d0b2d814e78a |         at java.nio.file.Files.setPosixFilePermissions(Files.java:2045)
jicofo_1_d0b2d814e78a |         at net.java.sip.communicator.impl.configuration.ConfigurationActivator.fixPermissions(ConfigurationActivator.java:167)
jicofo_1_d0b2d814e78a |         at net.java.sip.communicator.impl.configuration.ConfigurationActivator.start(ConfigurationActivator.java:88)
jicofo_1_d0b2d814e78a |         at org.jitsi.impl.osgi.framework.BundleImpl.start(BundleImpl.java:307)
jicofo_1_d0b2d814e78a |         at org.jitsi.impl.osgi.framework.launch.FrameworkImpl.startLevelChanged(FrameworkImpl.java:472)
jicofo_1_d0b2d814e78a |         at org.jitsi.impl.osgi.framework.startlevel.FrameworkStartLevelImpl$Command.run(FrameworkStartLevelImpl.java:137)
jicofo_1_d0b2d814e78a |         at org.jitsi.impl.osgi.framework.AsyncExecutor.runInThread(AsyncExecutor.java:122)
jicofo_1_d0b2d814e78a |         at org.jitsi.impl.osgi.framework.AsyncExecutor.access$000(AsyncExecutor.java:28)
jicofo_1_d0b2d814e78a |         at org.jitsi.impl.osgi.framework.AsyncExecutor$1.run(AsyncExecutor.java:231)
jicofo_1_d0b2d814e78a | Jicofo 2020-02-10 06:54:51.298 INFO: [10] util.NetworkUtils.<clinit>().117 java.net.preferIPv6Addresses=null
jicofo_1_d0b2d814e78a | Jicofo 2020-02-10 06:54:51.298 INFO: [10] util.NetworkUtils.<clinit>().118 java.net.preferIPv4Stack=null`

JVB.log
`jvb_1_8de8ac39c21a | JVB 2020-02-10 06:54:57.523 SEVERE: [20] util.UtilActivator.uncaughtException().122 An uncaught exception occurred in thread=Thread[Thread-8,5,main] and message was: null
jvb_1_8de8ac39c21a | java.lang.IllegalArgumentException
jvb_1_8de8ac39c21a |    at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1314)
jvb_1_8de8ac39c21a |    at java.util.concurrent.ThreadPoolExecutor.<init>(ThreadPoolExecutor.java:1202)
jvb_1_8de8ac39c21a |    at java.util.concurrent.Executors.newFixedThreadPool(Executors.java:89)
jvb_1_8de8ac39c21a |    at org.ice4j.ice.harvest.MappingCandidateHarvesters.createStunHarvesters(MappingCandidateHarvesters.java:327)
jvb_1_8de8ac39c21a |    at org.ice4j.ice.harvest.MappingCandidateHarvesters.initialize(MappingCandidateHarvesters.java:171)
jvb_1_8de8ac39c21a |    at java.lang.Thread.run(Thread.java:748)
jvb_1_8de8ac39c21a | JVB 2020-02-10 06:54:58.167 WARNING: [14] org.jitsi.videobridge.stats.MucStatsTransport.publishStatistics().69 Can not publish via presence, no ClientConnectionImpl.
jvb_1_8de8ac39c21a | JVB 2020-02-10 06:54:58.549 SEVERE: [18] org.jitsi.videobridge.health.Health.log() Health check failed in 4432ms:
jvb_1_8de8ac39c21a | java.lang.NullPointerException
jvb_1_8de8ac39c21a |    at org.ice4j.ice.Agent.<init>(Agent.java:407)
jvb_1_8de8ac39c21a |    at org.jitsi.videobridge.IceUdpTransportManager.createIceAgent(IceUdpTransportManager.java:1070)
jvb_1_8de8ac39c21a |    at org.jitsi.videobridge.IceUdpTransportManager.<init>(IceUdpTransportManager.java:566)
jvb_1_8de8ac39c21a |    at org.jitsi.videobridge.IceUdpTransportManager.<init>(IceUdpTransportManager.java:527)
jvb_1_8de8ac39c21a |    at org.jitsi.videobridge.Channel.createTransportManager(Channel.java:323)
jvb_1_8de8ac39c21a |    at org.jitsi.videobridge.Channel.initialize(Channel.java:674)
jvb_1_8de8ac39c21a |    at org.jitsi.videobridge.RtpChannel.initialize(RtpChannel.java:895)
jvb_1_8de8ac39c21a |    at org.jitsi.videobridge.Content.createRtpChannel(Content.java:340)
jvb_1_8de8ac39c21a |    at org.jitsi.videobridge.Content.createRtpChannel(Content.java:264)
jvb_1_8de8ac39c21a |    at org.jitsi.videobridge.health.Health.check(Health.java:152)
jvb_1_8de8ac39c21a |    at org.jitsi.videobridge.health.Health.doCheck(Health.java:244)
jvb_1_8de8ac39c21a |    at org.jitsi.videobridge.health.Health.doRun(Health.java:495)
jvb_1_8de8ac39c21a |    at org.jitsi.utils.concurrent.PeriodicRunnableWithObject.run(PeriodicRunnableWithObject.java:87)
jvb_1_8de8ac39c21a |    at org.jitsi.utils.concurrent.RecurringRunnableExecutor.run(RecurringRunnableExecutor.java:216)
jvb_1_8de8ac39c21a |    at org.jitsi.utils.concurrent.RecurringRunnableExecutor.runInThread(RecurringRunnableExecutor.java:292)
jvb_1_8de8ac39c21a |    at org.jitsi.utils.concurrent.RecurringRunnableExecutor.access$000(RecurringRunnableExecutor.java:36)
jvb_1_8de8ac39c21a |    at org.jitsi.utils.concurrent.RecurringRunnableExecutor$1.run(RecurringRunnableExecutor.java:328)`

**Comment by zzt8899** [comment]
I had the same problem！！！

**Comment by VanherpeDries** [comment]
found that the prosody docker image isn't working it looks inside /etc/prosody but there isn't anything inside it.

**Comment by VanherpeDries** [comment]
made it work  in the following github :

https://github.com/VanherpeDries/kube-istio-jitsi

**Comment by pansj2020** [comment]
Thank you for your help. But I didn't see difference between&nbsp;https://github.com/jitsi/docker-jitsi-meet&nbsp;and&nbsp;https://github.com/VanherpeDries/kube-istio-jitsi




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"VanherpeDries"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月27日(星期四) 晚上6:12
收件人:&nbsp;"jitsi/docker-jitsi-meet"<docker-jitsi-meet@noreply.github.com&gt;;
抄送:&nbsp;"猫王"<53054827@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jitsi/docker-jitsi-meet] Jitsi room Crash when another user joins (#188)




made it work  in the following github :
 
https://github.com/VanherpeDries/kube-istio-jitsi

**Comment by VanherpeDries** [comment]
i had the same error this, the biggest problem is that the image isn't correctly pulled on the prosody, ive change it to jisti/prosody and seems to work

**Comment by pansj2020** [comment]
OK，thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"VanherpeDries"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月28日(星期五) 下午5:23
收件人:&nbsp;"jitsi/docker-jitsi-meet"<docker-jitsi-meet@noreply.github.com&gt;;
抄送:&nbsp;"猫王"<53054827@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jitsi/docker-jitsi-meet] Jitsi room Crash when another user joins (#188)




i had the same error this, the biggest problem is that the image isn't correctly pulled on the prosody, ive change it to jisti/prosody and seems to work

**Comment by VanherpeDries** [comment]
> OK，thanks
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"VanherpeDries"<notifications@github.com&gt;; 发送时间:&nbsp;2020年2月28日(星期五) 下午5:23 收件人:&nbsp;"jitsi/docker-jitsi-meet"<docker-jitsi-meet@noreply.github.com&gt;; 抄送:&nbsp;"猫王"<53054827@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [jitsi/docker-jitsi-meet] Jitsi room Crash when another user joins (#188) i had the same error this, the biggest problem is that the image isn't correctly pulled on the prosody, ive change it to jisti/prosody and seems to work — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

can you confirm that it works ?

**Comment by VanherpeDries** [comment]
I'm sorry it's the JVB who refuses to pull
`  image: 103425057857.dkr.ecr.us-west-2.amazonaws.com/jitsi/jvb`
i've changed it to the official repo :
`  image: /jitsi/jvb`

**Comment by saghul** [comment]
I'm closing this. Sorry but we cannot help unless you are using this same setup, as I don't know what changes you made to it.

**Comment by samsk** [comment]
Workaround: Enable JVB TCP harvester, in env set JVB_TCP_HARVESTER_DISABLED=false

**Comment by zioalex** [comment]
> Workaround: Enable JVB TCP harvester, in env set JVB_TCP_HARVESTER_DISABLED=false
@samsk can you please explain why did it help?
