### ISSUE TITLE
Whiteboard Button Not Visible in Jitsi Docker Setup (Stable-9646)

### ISSUE THREAD

**Issue by DanielnetoDotCom** [jitsi/docker-jitsi-meet#1888]
**Environment:**
- **Jitsi Docker Version:** stable-9646
- **Excalidraw Backend Image:** `ypt/excalidraw-backend:21`
- **Web Server:** Nginx (with SSL proxy configuration)

**Configuration Details:**

**`.env` File:**
```env
WHITEBOARD_ENABLED=true
WHITEBOARD_COLLAB_SERVER_URL_BASE=http://whiteboard.meet.jitsi
WHITEBOARD_COLLAB_SERVER_PUBLIC_URL=https://whiteboard.meet.my.domain
```

**Docker Container Status:**
```bash
docker ps
CONTAINER ID   IMAGE                       COMMAND                  CREATED         STATUS         PORTS                                                                            NAMES
9d21c5c74b90   ypt/excalidraw-backend:21   "docker-entrypoint.s…"   6 minutes ago   Up 6 minutes   80/tcp, 9090/tcp                                                                 meet-whiteboard-1
5d951be207e6   meet-web                    "/init"                  6 minutes ago   Up 6 minutes   0.0.0.0:8080->80/tcp, :::8080->80/tcp, 0.0.0.0:8443->443/tcp, :::8443->443/tcp   meet-web-1
0a354db93132   ypt/jvb:stable-9646         "/init"                  6 minutes ago   Up 6 minutes   0.0.0.0:7702->7702/udp, :::7702->7702/udp, 127.0.0.1:7703->8080/tcp              meet-jvb-1
887f43799e91   ypt/jicofo:stable-9646      "/init"                  6 minutes ago   Up 6 minutes   127.0.0.1:8888->8888/tcp                                                         meet-jicofo-1
1023b2b94c21   meet-prosody                "/init"                  6 minutes ago   Up 6 minutes   5222/tcp, 5269/tcp, 5280/tcp, 5347/tcp                                           meet-prosody-1
```

**Nginx Proxy Configuration:**
```nginx
server {
    server_name mysite.com;
    
    location / {
        proxy_pass https://localhost:8443;
        proxy_set_header HTTP_REFERER $http_referer;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
    }
    
    location /xmpp-websocket {
        proxy_pass https://localhost:8443/xmpp-websocket;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
    
    location /colibri-ws/ {
        proxy_pass https://localhost:8443/colibri-ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    listen 80; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    
    ssl_certificate /etc/letsencrypt/live/mysite.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mysite.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
```

**Issue Description:**
I am running the Jitsi Docker version `stable-9646`, and I have configured the `.env` file to enable the whiteboard feature using the Excalidraw backend. Despite the Excalidraw backend being up and running, I am unable to see the whiteboard button in the Jitsi interface.

The `curl` command inside the `web` container confirms that the Excalidraw backend is accessible:

```bash
docker exec -it meet-web-1 curl http://whiteboard.meet.jitsi
Excalidraw backend is up :)
```

**Steps Taken:**
1. Verified the `WHITEBOARD_ENABLED` and `WHITEBOARD_COLLAB_SERVER_*` environment variables are set correctly.
2. Confirmed the Excalidraw backend is accessible from the `web` container.
3. Checked the Nginx proxy configuration for proper SSL handling and forwarding.
4. Inspected the browser console for any relevant errors, but no issues were reported.

**Expected Behavior:**
The whiteboard button should be visible in the Jitsi meeting toolbar when the whiteboard feature is enabled and correctly configured.

**Actual Behavior:**
The whiteboard button does not appear in the Jitsi interface, despite the backend service being up and accessible.

**Questions/Request for Assistance:**
- Is there any additional configuration required in the Jitsi web container to enable the whiteboard feature?
- Are there known issues with the stable-9646 version and the Excalidraw backend integration?
- Can you provide guidance on any other logs or settings to inspect?

**Additional Information:**
Please advise on any other configurations or steps needed to troubleshoot this issue. Any help or pointers would be greatly appreciated.

**Comment by saghul** [comment]
Those are not our images. Please try to reproduce it with ours.

**Comment by DanielnetoDotCom** [comment]
Those are yours I just downloaded them and rename it, I want to redeploy it multiple times without redownload them each time

**Comment by DanielnetoDotCom** [comment]
Does the excalidraw should have a public port (same as web) or it will resolve internally?

**Comment by DanielnetoDotCom** [comment]
Neverming, I got it working.

I was using the API to start the meeting, and I had to add this in my toolbar 
```
TOOLBAR_BUTTONS: [
        // other buttons...
        'whiteboard', // Add whiteboard to the toolbar
        // other buttons...
    ]
```

also I just realize that the WHITEBOARD_COLLAB_SERVER_PUBLIC_URL is the same URL as the PUBLIC_URL
