### ISSUE TITLE
Video Crashes as soon as third user joins the conference

### ISSUE THREAD

**Issue by tvollstaedt** [jitsi/docker-jitsi-meet#189]
Hi,

I'm trying to set up jitsi for some weeks now within Docker + Kubernetes (single Node). I successfully established a P2P connection with video, but the third user joining causes a video drop since Jitsi tries to switch from P2P into central mode. I looked at a alot of issues and tried everything I can imaging, but no success so far.

JVB exposes it's port directly to the node (NodePort), web will be routed through an HTTPS-enabled nginx ingress controller. I've also tried to downgrade ingress to TLSv1, which didn't work either.

[YML config and Logs](https://gist.github.com/tvollstaedt/0941fd27dc29502a089a10a6c62d58a8)

(Sensitive data is replaced with <> brackets, authorization errors come from auth dialog - authorization is successful after I entered credentials for prosody user I created).

I'm really frustrated right now, I would be very happy for every little hint.

**Comment by damencho** [comment]
Have you forwarded/open udp port 10000 from the public address to the jvb internal address 
`org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=<public-ip>`?
Ignore me if I'm talking no-sense in the context of docker (not very familiar with its network model), but basically clients will be sending media traffic to udp <public-ip> port 10000 and that needs to reach jvb.

**Comment by tvollstaedt** [comment]
> Have you forwarded/open udp port 10000 from the public address to the jvb internal address
> `org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=<public-ip>`?
> Ignore me if I'm talking no-sense in the context of docker (not very familiar with its network model), but basically clients will be sending media traffic to udp port 10000 and that needs to reach jvb.

Port 10000/udp and 4333/tcp will be directly forwarded to JVB, so that shouldn't be an issue. Is there any way to confirm these ports are working? Are there log messages etc.?

**Comment by damencho** [comment]
You can check using the browser. Open chrome://webrtc-internals, enter a meeting with 3 participants and you will see 6 tabs (one for p2p and one for jvb connection for each user). You can distinguish peer connection by that on the p2p tab on the tob with bold you sill see some stun server. So you need to find a tab for jvb connection find the last setRemoteDescriptionn, unfold it and check the ip addresses and ports that jvb advertizes.

**Comment by tvollstaedt** [comment]
> You can check using the browser. Open chrome://webrtc-internals, enter a meeting with 3 participants and you will see 6 tabs (one for p2p and one for jvb connection for each user). You can distinguish peer connection by that on the p2p tab on the top with bold you sill see some stun servers. So you need to find a tab for jvb connection find the last setRemoteDescription, unfold it and check the ip addresses and ports that jvb advertizes.

Thanks, it seems i've found the right tab (ICE connection), but `setDescription` (the only one) does not seem to offer any ip addresses: https://gist.github.com/tvollstaedt/c66fa73e269a2f6865f4de2cee59935b

**Comment by damencho** [comment]
Seems correct to me:
```
a=candidate:1 1 ssltcp 2130706431 10.42.209.231 4443 typ host generation 0
a=candidate:3 1 udp 2130706431 10.42.209.231 10000 typ host generation 0
a=candidate:2 1 ssltcp 1694498815 <public-ip> 4443 typ srflx raddr 10.42.209.231 rport 4443 generation 0
a=candidate:4 1 udp 1677724415 <public-ip> 10000 typ srflx raddr 10.42.209.231 rport 10000 generation 0
```
This is how it looks on meet.jit.si:
![image](https://user-images.githubusercontent.com/3263098/74570053-c0a39200-4f73-11ea-93c7-23c0635b4510.png)

**Comment by tvollstaedt** [comment]
BTW: Browser console says:

`Logger.js:125 [modules/RTC/BridgeChannel.js] <e.value>:  Bridge Channel send: no opened channel.`

**Comment by damencho** [comment]
Firewall?

**Comment by tvollstaedt** [comment]
I've played around with some things, but most notably I've changed from NodePort to HostPort and now it finally works. Thank you very much for your time & help and for pushing me in the right direction again (UDP Port)! 👏 👍

**Comment by JoeyJia** [comment]
> I've played around with some things, but most notably I've changed from NodePort (Port opens on all nodes) to HostPort (Port opens on all nodes only running this pod) and now it finally works 🎉 (even though it should make no difference with only one node) . Thank you very much for your time & help and for pushing me in the right direction again (UDP Port)! 👏 👍

hi @tvollstaedt I faced same issue. Could u tell me how to fix this issue step by step? I don't know how chang NodePort (Port opens on all nodes) to HostPort .Thank you very much.

**Comment by iGoogledYouYesterday** [comment]
@tvollstaedt 
I have the same issue as you - also the same setup: 

I access my deployment trough NGINX ingress controller for HTTP & HTTPS content, but Im having trouble now exposing my deployments UDP port. 

Can I ask you for more information about what exactly did you do to mitigate it?

**Comment by tvollstaedt** [comment]
> @tvollstaedt
> I have the same issue as you - also the same setup:
> 
> I access my deployment trough NGINX ingress controller for HTTP & HTTPS content, but Im having trouble now exposing my deployments UDP port.
> 
> Can I ask you for more information about what exactly did you do to mitigate it?

My solution was to deploy the jvb service with UDP/10000 as HostPost instead of NodePort. Heres the relevant part of my deployment definition:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
     [...]
  labels:
	 [...]
  name: jvb
  namespace: jitsi
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
		[...]
    spec:
      containers:
      - env:
        - [...]
        image: jitsi/jvb
        imagePullPolicy: Always
        name: jvb
        ports:
        - containerPort: 10000
          hostPort: 10000
          name: 10000udp100000
          protocol: UDP
[...]
```
