### ISSUE TITLE
Incorrect port used by the xmpp_websocket in browser UI

### ISSUE THREAD

**Issue by alexpyattaev** [jitsi/docker-jitsi-meet#1901]
The browser is directed to connect to 
wss://domain.com/xmpp-websocket?room=roomname
when the correct address should be 
wss://domain.com:8443/xmpp-websocket?room=roomname 

With incorrect port, the meeting connection does not work right (times out). 

The docker env.example should be changed as follows:

```dockerfile
# Public URL for the web service (required)
#PUBLIC_URL=https://meet.example.com:8443
```
or alternatively the correct port needs to be somehow patched in later.
PS: thanks for the great work on Jitsi=)

**Comment by saghul** [comment]
You need to put the real public URL. Since you can change the port we cannot guess that.

**Comment by alexpyattaev** [comment]
Yes, the point is, in the example the port is non-standard. But there is no hint that this needs to be patched into the URL. I've spent nearly an hour trying to figure that one out, some users may not be as persistent=)

**Comment by saghul** [comment]
Fair enough, mind sending a PR?

**Comment by alexpyattaev** [comment]
Sure, https://github.com/jitsi/docker-jitsi-meet/pull/1902

**Comment by saghul** [comment]
Merged, cheers!
