### ISSUE TITLE
Expose enable-moderator-checks in jicofo

### ISSUE THREAD

**Issue by dnna** [jitsi/docker-jitsi-meet#1918]
Jicofo has a new config option enable-moderator-checks:
https://github.com/jitsi/jicofo/blob/eb53e1946c103bba16edb5319a10880a2bee6f09/jicofo-selector/src/main/resources/reference.conf#L190

It would be great if this could be exposed as an env variable in docker to be able to set it.

**Comment by saghul** [comment]
A PR would be welcome if you're up for it!

**Comment by dnna** [comment]
@saghul ready https://github.com/jitsi/docker-jitsi-meet/pull/1919
