### ISSUE TITLE
Clarify the documentation to mention that PUBLIC_URL is mandatory in reverse proxy setup

### ISSUE THREAD

**Issue by Utopiah** [jitsi/docker-jitsi-meet#1921]
I just update my setup and it worked quickly... except I got the "infamous" message "You have been disconnected".

I say infamous because I somehow struggle with it every time I do a clean setup. I usually find back the solution after few minutes by coming here.

Anyway my point is that it's a recurring issue with newcomers hitting that problem often enough to open a new issue every few months. 

I suggest that the note right after the [7 step setups](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker/) saying "...that's e.g. for a reverse proxy setup; ..." also mentions that `PUBLIC_URL` is mandatory in such a context.

I imagine most people relying on containers do so with a reverse proxy so it's an important information.

**Comment by saghul** [comment]
I just pushed an update to the handbook, thanks for the feedback!

**Comment by Utopiah** [comment]
Wonderful, thanks a lot for incorporating that feedback and obviously the project itself, helping me daily to conduct meetings on my own infrastructure!

**Comment by Diyalkumar-dev** [comment]
l like you
