### ISSUE TITLE
Whisper private key invalid key format

### ISSUE THREAD

**Issue by L3o-pold** [jitsi/docker-jitsi-meet#1923]
I tried a single string (`cat ./private_key.pem | tr -d '\n'`) or a base64 encoded version of the private key without any luck.

JIGASI_TRANSCRIBER_WHISPER_PRIVATE_KEY=xxxx

```
2024-10-01 12:20:41.564 SEVERE: [69] WhisperWebsocket.connect#189: Failed connecting to wss://*/streaming-whisper/ws/abf2d3ab-aedd-442e-a559-85327f534e5b. Retrying in 25seconds for another 3 times.
2024-10-01 12:20:41.564 SEVERE: [69] WhisperWebsocket.connect#191: java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: invalid key format
```

**Comment by aaronkvanmeerten** [comment]
Great question. Removing /n is actually very close, but you will also need to remove the --- BEGIN and ---- END lines as well. I will try to update the documentation for this parameter to reflect this.

**Comment by E-pic-C** [comment]
> I tried a single string (`cat ./private_key.pem | tr -d '\n'`) or a base64 encoded version of the private key without any luck.
> 
> JIGASI_TRANSCRIBER_WHISPER_PRIVATE_KEY=xxxx
> 
> ```
> 2024-10-01 12:20:41.564 SEVERE: [69] WhisperWebsocket.connect#189: Failed connecting to wss://*/streaming-whisper/ws/abf2d3ab-aedd-442e-a559-85327f534e5b. Retrying in 25seconds for another 3 times.
> 2024-10-01 12:20:41.564 SEVERE: [69] WhisperWebsocket.connect#191: java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: invalid key format
> ```

Try using xn--2 at the begining of the code. And if that don't work puta right facing arrow with a circle before the xn.

**Comment by L3o-pold** [comment]
Removing end of line and --- BEGIN and ---- END lines worked great.
