### ISSUE TITLE
Self Hosting Jitsi behind Apache Reverse Proxy

### ISSUE THREAD

**Issue by ralfi** [jitsi/docker-jitsi-meet#193]
Hi jitsis,

i am try to integrate jitsi in my local LAN environment. There are a lot of docker based apps like nextcloud behind a reverse proxy with LE certs. If i looking at the readme of jitsi install i see that implementation of TURN is outstanding in development. Depend on this, it is possible the setup jitsi in the same way as docker image like described above and of course to use it for web conferencing? Nextcloud Talk as talk-to-talk audio / video chat works well.

Thanks in advance for explanation.
Regards

**Comment by saghul** [comment]
Moved to the right repo.

We already have TURN support in a PR, but that has nothing to do with a reverse proxy setup.

You cacn setup the docker images just fine and use an apache to front it and proxy everything to the docker setup.

**Comment by ralfi** [comment]
Hi saghul,

thanks for quick reply, now i am try this ...

**Comment by ralfi** [comment]
YEAH, ist really cooool -
ten minutes of looking around the docs, setting up with docker-compose and it works. 

Great!
THANKS everyone how is involved.

**Comment by saghul** [comment]
Nice to hear!

**Comment by richardrey** [comment]
Hello help me please

I have deployed docker compose from jitsi and it works correctly on local network pointing to internal network ip with ip: port works

The problem has come when I want to make a proxy pass against Jitsi from my frontal Apache web, this does not work correctly, I do not know what part I have done wrong or if I have to add something to the nginx.

**My proxypass config against jitsi from apache is:**

```
                ProxyRequests Off
                ProxyPreserveHost On
                ProxyPass / http: // ip: 80
                ProxyPassReverse / http: // ip: 80

```
**What the web teaches me is:**

```
Uh oh! We couldn't fully download everything we needed :(
We will try again shortly. In the mean time, check for problems with your Internet connection!


Missing https://meeting.dominio.com/css/all.css?v=3729
```

**From the browser in inspection mode it indicates the following:**

```
DevTools failed to parse SourceMap: chrome-extension: //gighmmpiobklfepjocnamgkkbiglidom/include.preload.js.map
DevTools failed to parse SourceMap: chrome-extension: //hdokiejnpimakedhajhdlcegeplioahd/sourcemaps/onloadwff.js.map
? rCounter = 8: 9 GET https://meeting.dominio.com/css/all.css?v=3729 net :: ERR_ABORTED 502 (Proxy Error)
? rCounter = 8: 625 GET https://meeting.dominio.com/libs/do_external_connect.min.js?v=1 net :: ERR_ABORTED 502 (Proxy Error)
? rCounter = 8: 19 (TIME) index.html loaded: 270.81499999621883
? rCounter = 8: 880 GET https://meeting.dominio.com/libs/lib-jitsi-meet.min.js?v=3729 net :: ERR_ABORTED 502 (Proxy Error)
? rCounter = 8: 881 GET https://meeting.domain.com/libs/app.bundle.min.js?v=3729 net :: ERR_ABORTED 502 (Proxy Error)
? rCounter = 8: 625 GET https://meeting.dominio.com/libs/do_external_connect.min.js?v=1 net :: ERR_ABORTED 502 (Proxy Error)
? rCounter = 8: 880 GET https://meeting.dominio.com/libs/lib-jitsi-meet.min.js?v=3729 net :: ERR_ABORTED 502 (Proxy Error)
? rCounter = 8: 881 GET https://meeting.domain.com/libs/app.bundle.min.js?v=3729 net :: ERR_ABORTED 502 (Proxy Error)
DevTools failed to parse SourceMap: chrome-extension: //gighmmpiobklfepjocnamgkkbiglidom/include.postload.js.map
favicon.ico: 1 GET https://meeting.dominio.com/images/favicon.ico?v=1 502 (Proxy Error)
```

**Comment by ralfi** [comment]
All you need is

ProxyPass "/" "http://localhost:8000/"
ProxyPassReverse "/" "http://localhost:8000/"

ProxyPass "/http-bind" "http://localhost:8000/http-bind/"
ProxyPassReverse "/http-bind" "http://localhost:8000/http-bind"

I am using docker-jitsi-meet 
To check your setup use curl -v http://localhost:8000/ and http://localhost:8000/http-bind

**Comment by richardrey** [comment]
Thank you very much It works now perfectly

**Comment by zypro** [comment]
This worked for me too. But I have issues with websockets (Bridge Channel is getting closed). Any solution known?
