### ISSUE TITLE
Jigasi (SIP service) fails to connect to port 5222 on the public address

### ISSUE THREAD

**Issue by syserr0r** [jitsi/docker-jitsi-meet#1941]
To get this working for now I have exposed port 5222 in docker-compose by changing:

```
        expose:
            - '${XMPP_PORT:-5222}'
            - '${PROSODY_S2S_PORT:-5269}'
            - '5347'
            - '${PROSODY_HTTP_PORT:-5280}'
```
to
```
        ports:
            - '${XMPP_PORT:-5222}:${XMPP_PORT:-5222}'
        expose:
            - '${PROSODY_S2S_PORT:-5269}'
            - '5347'
            - '${PROSODY_HTTP_PORT:-5280}'
```

I suspect this is not ideal and it would be better if Jigasi tried to connect to `${XMPP_SERVER:-xmpp.meet.jitsi}` instead.

I attempted to change `org.jitsi.jigasi.xmpp.acc.SERVER_ADDRESS=jitsi.mydomain.com` in `.jitsi-meet-cfg/jigasi/sip-communicator.properties` but these changes were lost as it appears the file is regenerated on service start.

**Comment by damencho** [comment]
This had been fixed here and will be available on next stable release. 
https://github.com/jitsi/docker-jitsi-meet/commit/0b75cd16898600058d421b3f79ec3a04c06927c9



> `.jitsi-meet-cfg/jigasi/sip-communicator.properties` but these changes were lost as it appears the file is regenerated on service start.

You need to create a custom file `custom-sip-communicator.properties` and that should be ....SERVER_ADDRESS=xmpp.meet.jitsi
