### ISSUE TITLE
Does exist an docker image with all Jitsi's component included ?

### ISSUE THREAD

**Issue by ChrisPices** [jitsi/docker-jitsi-meet#1947]
Hey there, i'd like to know if there is an docker image including all the components of Jitsi (JVB, Prosody, Jicofo, Jitsi web...) insteed of multiple images.

I need to deploy multiple standalone jitsi's instance, but i can't actually, because of the ports..

thanks you !

**Comment by aaronkvanmeerten** [comment]
This isn't planned and I'd suggest looking at the variables to control ports. It's definitely possible to run the containers for multiple installs of jitsi on the same machine. 

It should be possible to override all ports in all components.   If you find any issue with missing ports to be reconfigured we would welcome a Pull Request for any fixes.

**Comment by ChrisPices** [comment]
Thanks for response, i tried to +1 every port without changing http & https, and run :

XMPP_PORT=5223 \
PROSODY_S2S_PORT=5270 \
PROSODY_HTTP_PORT=5281 \
JICOFO_REST_PORT=8889 \
JVB_PORT=10001 \
JVB_COLIBRI_PORT=8081 \
CONFIG=~/.jitsi-meet-cfg \
HTTP_PORT=8000 \
HTTPS_PORT=8443 \
TZ=UTC \
ENABLE_GUESTS=1 \
AUTH_TYPE=internal \
PUBLIC_URL=https://my.public-url.com:$HTTPS_PORT \
docker-compose -f docker-compose.yml -f jibri.yml up -d

but no possibility to join the call, instantly connexion error...

![image](https://github.com/user-attachments/assets/1d44a2b6-c465-4bba-b5e2-42185d0a594c)

Any solution?

**Comment by saghul** [comment]
Why do you feel the need to run all the components in multiples? What needs to be different across them? If it's just the frontend for example, you could have multiple web containers connected to different Prosody / Jicofo / JVB containers.

**Comment by aaronkvanmeerten** [comment]
You would need to post some logs with errors to show what was specifically going wrong in your install.

**Comment by ChrisPices** [comment]
> Pourquoi ressentez-vous le besoin d'exécuter tous les composants en multiples ? Qu'est-ce qui doit être différent à travers eux? S'il s'agit juste de la face avant par exemple, vous pourriez avoir plusieurs conteneurs web connectés à différents conteneurs Prosody / Jicofo / JVB.

so i tryed, but if on both front i use the same roomname, they are on the same call. I need them to be on 2 differents call even if the roomname are the same

**Comment by ChrisPices** [comment]
> You would need to post some logs with errors to show what was specifically going wrong in your install.

2024/10/21 15:08:55 [error] 281#281: *73 connect() failed (111: Connection refused) while connecting to upstream, client: XX.XX.XX.XX server: _, request: "GET /xmpp-websocket?room=test HTTP/1.1", upstream: "http://172.19.0.2:5280/xmpp-websocket?prefix=&room=test", host: "my.public-url.com:8443"

this is the only log i found when i try to join a call

also, find that ports are not mapping right : 

![image](https://github.com/user-attachments/assets/7e3c7b9c-b34c-4886-9d31-6fc5e97b8b90)

Probably why it's not working. I try to modify the docker-compose.yml : 

Old one : 

![image](https://github.com/user-attachments/assets/1b61c46b-ccb8-4bdc-8710-f0fdb7c28e63)

New one : 

![image](https://github.com/user-attachments/assets/84a30c0a-7c57-4def-bc52-dfb534a08546)

but it looks like it doesn't wan't to remove the default port assigned

**Comment by saghul** [comment]
I feel like some more details of your use case would help us give you a better answer.

**Comment by sakiphan** [comment]
Are you cloning the repo directly and trying to run it? @ChrisPices

**Comment by saghul** [comment]
I think is a topic for discussion in our forum rather than an issue here. Closing.
