### ISSUE TITLE
i can't access the HTTP metrics

### ISSUE THREAD

**Issue by tapionx** [jitsi/docker-jitsi-meet#196]
I tried to edit different settings in .env and jvb/rootfs/defaults/sip-communicator.properties, but i cannot access the metrics on the private HTTP interface.

```
docker-compose ps
          Name              Command   State                        Ports                      
----------------------------------------------------------------------------------------------
dockerjitsimeet_jicofo_1    /init     Up                                                      
dockerjitsimeet_jvb_1       /init     Up      0.0.0.0:10000->10000/udp, 0.0.0.0:4443->4443/tcp
dockerjitsimeet_prosody_1   /init     Up      5222/tcp, 5269/tcp, 5280/tcp, 5347/tcp          
dockerjitsimeet_web_1       /init     Up      0.0.0.0:8443->443/tcp, 0.0.0.0:8000->80/tcp     
```
What configuration do I need to change and on what port should i connect to pull the metrics?

**Comment by tapionx** [comment]
i managed to access the internal HTTP metrics.
Here are the steps to achieve the goal for future readers:

`JVB_ENABLE_APIS=rest,colibri` in `.env`

```
org.jitsi.videobridge.ENABLE_STATISTICS=true
org.jitsi.videobridge.STATISTICS_TRANSPORT=muc,colibri
org.jitsi.videobridge.STATISTICS_INTERVAL=5000
```
in `jvb/rootfs/defaults/sip-communicator.properties`

Now you can connect to `localhost:8000/colibri/stats`

**Comment by ccoenen** [comment]
tiny addition to the above: I needed to add the port `8080` to the JVB container, and then i could navigate to `http://localhost:8080/colibri/stats` (note the different port! 8080 vs 8000!)

**Comment by Tieantono** [comment]
> tiny addition to the above: I needed to add the port `8080` to the JVB container, and then i could navigate to `http://localhost:8080/colibri/stats` (note the different port! 8080 vs 8000!)

Yeah, you should bind the `jvb` container configuration in Docker Compose file, example:
```
jvb:
        image: jitsi/jvb:latest
        restart: ${RESTART_POLICY}
        ports:
            - '8080:8080' # New port binding.
```

The thing is, it seems I haven't found the official statement in the documentation that port `8080` is colibri port.

**Comment by sapkra** [comment]
The port is documented in the docs the http API because colibri is part of it.

https://github.com/jitsi/jitsi-videobridge/blob/08554aa982a8de10db0d245e5de1caf7196330b5/doc/rest.md

**Comment by Tieantono** [comment]
> The port is documented in the docs the rest API because colibri is part of it.
> 
> https://github.com/jitsi/jitsi-videobridge/blob/08554aa982a8de10db0d245e5de1caf7196330b5/doc/rest.md

Whoops, I see, thank you for sharing.
