### ISSUE TITLE
Connection error at initiation

### ISSUE THREAD

**Issue by Softbox44** [jitsi/docker-jitsi-meet#1962]
*This Issue tracker is only for reporting bugs and tracking code related issues.*

Before posting, please make sure you check community.jitsi.org to see if the same or similar bugs have already been discussed. General questions, installation help, and feature requests can also be posted to community.jitsi.org.

## Description
Connection doesnt work

## Current behavior
I am using Jitsi only on my internal network. No reverse proxy and outside domain is configured yet.
So I am accessing the Jitsi server via `https://192.x.x.x:8443`
I can launch a meeting and the status on the left side is green saying "Everything is working properly"

When I then click '**Join Meeting**', I immediatelly get the error messager
>> You have been disconnected. You may want to check your network connection.
>> Rejoin now

## Expected Behavior
Connect to a meeting

## Possible Solution
I tried different **ports** but still the same issue
I also set `JVB_ADVERTISE_IPS` to my docker host IP

## Steps to reproduce
Launch of meeting

# Environment details
Docker on Debian
For .env I used the provied default values

**Comment by damencho** [comment]
Have you set the PUBLIC_URL that is required?

https://github.com/jitsi/docker-jitsi-meet/blob/47d974d88cba7d1e70a88ea83f65394e96787cc1/env.example#L30

**Comment by Softbox44** [comment]
No. I am testing it only internally. Is this not possible?

**Comment by damencho** [comment]
It is but you need to set the public URL, you are testing internally so your public URL is https://192.x.x.x:8443. 
Otherwise it defaults to localhost: https://github.com/jitsi/docker-jitsi-meet/blob/47d974d88cba7d1e70a88ea83f65394e96787cc1/web/rootfs/defaults/system-config.js#L7
but you are not using it on localhost but with an IP address.

**Comment by damencho** [comment]
Please, when you have questions or problems use the community forum before opening new issues, thank you.

**Comment by Softbox44** [comment]
I have set this in my .env
JVB_ADVERTISE_IPS=192.x.x.207

**Comment by Softbox44** [comment]
It works now I added PUBLIC_URL
thanks for your help!!
