### ISSUE TITLE
How to add time controls to recorded video.

### ISSUE THREAD

**Issue by Howie2024** [jitsi/docker-jitsi-meet#1984]
How to add time controls to recorded video. As shown below

![image](https://github.com/user-attachments/assets/330e2d9b-6579-436b-aa78-1ae42ce38508)

**Comment by saghul** [comment]
You would need to use ffmpeg or some other tool to add it in post. This is not something that's done out of the box.

**Comment by Howie2024** [comment]
> You would need to use ffmpeg or some other tool to add it in post. This is not something that's done out of the box.

We secondary development, can use the implementation? Can you provide the corresponding code?

**Comment by saghul** [comment]
I don't have any code to do that at hand.
