### ISSUE TITLE
Jitsi k8s - you have been disconnected

### ISSUE THREAD

**Issue by Alfr3d022** [jitsi/docker-jitsi-meet#1986]
I have a problem with jitsi, when I start a meeting it disconnects me and the following error appears in the console

![image](https://github.com/user-attachments/assets/1aa54962-7b0d-426c-a4cf-c2fe6d48a62c)

**Comment by damencho** [comment]
Have you taken care of the websockets on your proxy that fronts the deployment? 
https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#reverse-proxy-configuration

**Comment by Alfr3d022** [comment]
> Você já cuidou dos websockets em seu proxy que lidera a implantação? https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#reverse-proxy-configuration

Can I perform the configuration in ingress?

**Comment by aaronkvanmeerten** [comment]
This is probably not the appropriate place for such an issue. Please go to community.jitsi.org and ask your questions there.  In addition, the Kubernetes helm charts are a part of the community contributed offerings at https://github.com/jitsi-contrib/jitsi-helm and are not part of this repository.
