### ISSUE TITLE
Remove http as it seems to be broken and only https actually works

### ISSUE THREAD

**Issue by vorburger** [jitsi/docker-jitsi-meet#199]
I followed the README which currently suggests to _"Access the web UI at https://localhost:8443 (or http://localhost:8000 for HTTP)"_ and so when I got the self signed SSL cert warning on https naively used http as documented, but got:

On Chrome: _Cannot use microphone for an unknown reason. Cannot read property 'getUserMedia' of undefined_

On Firefox: _Cannot use microphone for an unknown reason. navigator.mediaDevices is undefined._

When I used https these errors went away and it seemed to work.

It looks like in recent modern browsers WebRTC only works on https? (I'm a WebRTC noob, just guessing.)

To avoid confusing for future users running into this, how about we remove http? I'll propose a PR.

**Comment by saghul** [comment]
That's a bad idea. There are many reasons why you'd want to use HTTP on this setup, but not necesssarily expossed to the outside world. Imagine a typical reverse proxy setup.

A PR explaining the limiations of HTTP on the README would be welcome though!
