### ISSUE TITLE
Cannot get a video connection working

### ISSUE THREAD

**Issue by MaxNoe** [jitsi/docker-jitsi-meet#208]
Client says: 
```
[modules/RTC/BridgeChannel.js] <value>: Bridge Channel send: no opened channel.
```

JVB log:
[jvb.log](https://github.com/jitsi/docker-jitsi-meet/files/4332967/jvb.log)

I tested udp traffic with netcat on the needed ports, it works.

**Comment by saghul** [comment]
Have you configured the DOCKED_HOST_ADDRESS env variable correctly?

**Comment by MaxNoe** [comment]
No, I had not. Sorry. Now it works fine! thanks.

**Comment by saghul** [comment]
Excellent, great to hear!

**Comment by MaxNoe** [comment]
@saghul could you push a new release to dockerhub? or should I build the images myself.

**Comment by MaxNoe** [comment]
To clarify: DOCKER_HOST_ADDRESS is only needed if there is no `PUBLIC_URL`?

**Comment by saghul** [comment]
> @saghul could you push a new release to dockerhub? or should I build the images myself.

We're kinda swamped right now, I'll try but I cannot guarantee I'll find the time to do it.



> To clarify: DOCKER_HOST_ADDRESS is only needed if there is no `PUBLIC_URL`?

No, those 2 are not related. DOCKER_HOST_ADDRESS is used for the JVB media, see the NAT traversal section of the README.

**Comment by MaxNoe** [comment]
> No, those 2 are not related. DOCKER_HOST_ADDRESS is used for the JVB media, see the NAT traversal section of the README.

Aren't those pretty strongly related?
As in:
`DOCKER_HOST_ADDRESS == nslookup $PUBLIC_URL` ?

**Comment by saghul** [comment]
You need not run the web and jvb containers on the same host.

**Comment by godpit** [comment]
It is still not successful when i set the ENV DOCKER_HOST_ADDRESS.
the jvb log : Pair failed: 172.20.0.5:10000/udp/host -> 192.168.3.13:53994/udp/host
