### ISSUE TITLE
Changing .env after running doesn't change variables 

### ISSUE THREAD

**Issue by wreiske** [jitsi/docker-jitsi-meet#21]
Running on 136460578d7fb5ae601643114a9e289c6fd2d758

1. Edit .env to include sip credentials
2. Run `docker-compose -f docker-compose.yml -f jigasi.yml up -d`
3. Change sip credentials in .env
4. Run `docker-compose -f docker-compose.yml -f jigasi.yml up -d`

No matter what you try, the sip credentials won't go away! I've tried logging out and back in to reset environment, I've tried [blowing away the docker containers](http://blog.baudson.de/blog/stop-and-remove-all-docker-containers-and-images), images, etc. I've tried  --force-recreate... It seems like to matter what I try, it is using the old credentials from the first time I ran the docker command. 

Any ideas?

**Comment by saghul** [comment]
If you want the new credentials to be taken into account you need to delete the jigasi config. That's in $CONFIG/jigasi ($CONFIG being whatever you specified there).

The configuration is only applied the first time the container is started without any config. The reason for doing this is to allow full customization: once the config has been created you can go ahead and edit it to your needs and the system won't mess it up.

**Comment by wreiske** [comment]
Where is $CONFIG/jigasi? Inside the container itself? Blowing away the container completely and rebuilding it from scratch does not change the credentials for me. 

**Stop all running containers**
`docker stop $(docker ps -aq)`

**Remove all containers**
`docker rm $(docker ps -aq)`

**Remove all images**
`docker rmi $(docker images -q)`

**Recreate containers from scratch**
`docker-compose -f docker-compose.yml -f jigasi.yml up -d --force-recreate`

The credentials will be the same as the first time it ran.

**Comment by saghul** [comment]
I'll explain this again.

Blowing the container does nothing, because the config is on a volume which is mounted into it. If you don't remove the config it will not be regenerated with the new credentials.

CONFIG is defined in the env file, so check your `.env` file, it's right at the top. Go to that directory and remove the `jigasi` directory. Then start the container again.

**Comment by wreiske** [comment]
Ahh, I found it.
```
# Directory where all configuration will be stored.
CONFIG=~/.jitsi-meet-cfg
```
I was looking in my home directory for that folder, but it doesn't exist! It's actually in:
`/root/snap/docker/current/.jitsi-meet-cfg/`

Thanks.
