### ISSUE TITLE
How can I access Etherpad in Jitsi?

### ISSUE THREAD

**Issue by hirschnase** [jitsi/docker-jitsi-meet#213]
Hello,

I run Jitsi via docker-composer and I enabled Etherpad as described in the documentation:

```docker-compose -f docker-compose.yml -f etherpad.yml up -d```
```ETHERPAD_URL_BASE=http://etherpad.meet.jitsi:9001```

The etherpad container runs and exposes tcp/9100 to the internal docker network.

My question is: how can I access Etherpad from a Jitsi Meeting? I have not found any link/button/icon that starts an Etherpad session. I tried to access https://myserver.domain/etherpad/ but this does not work either. I can not find anything useful in the documentation.

Please help!

**Comment by saghul** [comment]
There should be an whereas button in the 3 dots menu saying “open shared documents”. Do you not see it?

**Comment by hirschnase** [comment]
Hello Saghul,

no, I dont see this menu entry. I have attached a screenshot of how it looks like for me.

![2020-03-16 16_33_08-Jitsi Meet](https://user-images.githubusercontent.com/163801/76774634-76951280-67a4-11ea-918d-48319e35e9df.png)

**Comment by hirschnase** [comment]
Ok, I finally found out what the problem is: I activated etherpad at a later state when I already had started the whole stack already. It seems like the menu entry will only be added when etherpad is activated _before_ the stack is started for the first time. I deleted ~/.jitsi* and now I can see the menu entry.

**Comment by JanoschDeurer** [comment]
I'm having the same Issue, it seems like the `etherpad_base` is not set correctly in `/config/config.js`. 
```shell
root@0d14d9b0de02:/config# cat config.js | grep -i etherpad
     etherpad_base
```

I think the problem is in this grep: https://github.com/jitsi/docker-jitsi-meet/blob/76acc6502734d9bca5fa78b67102cfbc7a4ad29c/web/rootfs/etc/cont-init.d/10-config#L93

**Comment by codev** [comment]
Hi @hirschnase I have the same problem, can you give me a bit more information on what you did. I have an instance that is running fine without etherpad. I edited .env to enable the etherpad url.

Then did:
docker stop $(docker ps -a -q)
docker rm $(docker ps -a -q)
docker rmi $(docker images -q)
rm ~/.jitsi-meet-cfg
docker-compose -f docker-compose.yml -f etherpad.yml up -d

The button doesn't appear under the three dots menu when the server comes back up. I looked at:

docker-compose -f docker-compose.yml -f etherpad.yml logs | grep etherpad

And the only things that come up are the etherpad container logs which say nothing interesting

I can get the IP of the etherpad container and curl the page to see it is running but still jitsi doesn't display "Open shared documents" on the three dots menu.

Can you tell me your steps hirschnase? Or anyone else help. Thanks,

**Comment by hirschnase** [comment]
Hi @codev 
I just activated the line
```
ETHERPAD_URL_BASE=http://etherpad.meet.jitsi:9001
```
in the .env file and then stopped the whole stack, removed the directory ~/.jitsi-meet-cfg and started the stack again. After I was doing that, the menu entry appeared within the "three dots menu".

**Comment by codev** [comment]
Thanks I'd done that, my issue is actually #305 as I saw the message about /etherpad/p/ is not a valid URL in the javascript console.

**Comment by kamleshboi69** [comment]
ok for this issue i am geeting this error in the etherpad logs   etherpad_1  | exec /usr/local/bin/docker-entrypoint.sh: exec format error
etherpad_1  | exec /usr/local/bin/docker-entrypoint.sh: exec format error
etherpad_1  | exec /usr/local/bin/docker-entrypoint.sh: exec format error
etherpad_1  | exec /usr/local/bin/docker-entrypoint.sh: exec format error
etherpad_1  | exec /usr/local/bin/docker-entrypoint.sh: exec format error

**Comment by kamleshboi69** [comment]
when i try to access share document in jitsi meet it shows 502 bad gateway nginx

**Comment by saghul** [comment]
What erherpad image version are you using and on what architecture?

**Comment by kamleshboi69** [comment]
see my etherpad.yml file  

  GNU nano 7.2                                                             etherpad.yml                                                                       
version: '3.5'

services:
    # Etherpad: real-time collaborative document editing
    etherpad:
        image: etherpad/etherpad:1.8.6
        restart: ${RESTART_POLICY:-unless-stopped}
        environment:
            - TITLE=${ETHERPAD_TITLE}
            - DEFAULT_PAD_TEXT=${ETHERPAD_DEFAULT_PAD_TEXT}
            - SKIN_NAME=${ETHERPAD_SKIN_NAME}
            - SKIN_VARIANTS=${ETHERPAD_SKIN_VARIANTS}
            - SUPPRESS_ERRORS_IN_PAD_TEXT=true
        networks:
            meet.jitsi:
                aliases:
                    - etherpad.meet.jitsi

**Comment by saghul** [comment]
Use the official etherpad 1.9.6

**Comment by kamleshboi69** [comment]
can you import pdf files and jpg files

**Comment by kamleshboi69** [comment]
please tell me how to add pdf and images functionality

**Comment by saghul** [comment]
You need to ask the Etherpad maintainers about that. We just use it.
