### ISSUE TITLE
Jitsi Meet On DigitalOcean Marketplace

### ISSUE THREAD

**Issue by lanaschuhmacher** [jitsi/docker-jitsi-meet#215]
What do you think of putting Jitsi Meet on the [DigitalOcean Marketplace](https://marketplace.digitalocean.com/)?
That would allow noobs like me to setup an own instance and reduce the load on [https://meet.jit.si/](https://meet.jit.si/).

**Comment by Galzk** [comment]
Just installed Jitsi using the docker image on a DigitalOcean droplet,
Would love to have it on the marketplace!
That'll certainly expose more people to this awesome project.

**Comment by saghul** [comment]
We're happy if someone does that, but have no spare time to do that right now I'm afraid!

**Comment by jrgong420** [comment]
Also interested. Would be amazing

**Comment by nlochschmidt** [comment]
I found this, but haven't tried it yet:
https://marketplace.digitalocean.com/apps/jitsi-server

**Comment by lanaschuhmacher** [comment]
Thanks, @nlochschmidt. It seems to be working so far and the setup is easy. 😎

**Comment by mayailkour** [comment]
Jitsi is now available on [CapRover](https://marketplace.digitalocean.com/apps/caprover) too. 😁
