### ISSUE TITLE
Default video quality

### ISSUE THREAD

**Issue by MaxNoe** [jitsi/docker-jitsi-meet#217]
Is it possible to set a default video quality?

**Comment by saghul** [comment]
Yes, this values need to be tweaked: https://github.com/jitsi/jitsi-meet/blob/master/config.js#L116

**Comment by MaxNoe** [comment]
so just changing `ideal: 480` should request 480p by default?

**Comment by saghul** [comment]
Yep. You may also want to adapt the width to match.

**Comment by MaxNoe** [comment]
Mmh. In the web interface there are 4 settings. "low bandwidth" "low definition" "standard definition" and "high definition". Default being "high definition".

I don't really see how this maps to the settings in config.js 116

**Comment by saghul** [comment]
It doesn’t. That applies to e received bandwidth, not the sent one.

**Comment by MaxNoe** [comment]
So to clarify, the user has no direct way to set the video quality for uploading and the server can only provide a global default for that?

**Comment by saghul** [comment]
Correct.

**Comment by davewood** [comment]
That should be a rather simple change to make the default something else but "highest"
in a first step possibly without even making it configurable.

possibly somewhere around here: https://github.com/jitsi/jitsi-meet/blob/5a934c071a5cbe64de275a25d0ed62d8193cdd03/react/features/video-quality/components/VideoQualitySlider.web.js#L111 written initially by https://github.com/virtuacoplenny

cheers

**Comment by hasanbozok** [comment]
Hi, anyone solved this default video quality issue?

**Comment by saghul** [comment]
> So to clarify, the user has no direct way to set the video quality for uploading and the server can only provide a global default for that?

Update. THis has now changed. The manage video quality setting is now also applied on the sending side. This will be part of the next stable release.

**Comment by castillofrancodamian** [comment]
> > So to clarify, the user has no direct way to set the video quality for uploading and the server can only provide a global default for that?
> 
> Update. THis has now changed. The manage video quality setting is now also applied on the sending side. This will be part of the next stable release.

Already implemented?

**Comment by saghul** [comment]
Yes, this is already available.

**Comment by andreas1107** [comment]
Hi, is there an env variable that can be set for this? Or where exactly is this configured in a usual jitsi docker setup? thanks!

**Comment by saghul** [comment]
Check the list of env vars passed to the web container, yes it's configurable.
