### ISSUE TITLE
Update to Debian "buster

### ISSUE THREAD

**Issue by bkempe** [jitsi/docker-jitsi-meet#218]
According to [Jitsi Call on 3/9](https://www.youtube.com/watch?v=UfYRt20um4U), https://meet.jit.si uses [epoll](https://prosody.im/doc/network_backend).

This has not yet been incorporated into `docker-jisti-meet`.

There are some important epoll fixes in [Prosody 0.11.3](https://blog.prosody.im/prosody-0.11.3-released/)

Stretch-backports (which `docker-jitsi-meet` currently uses) only [provides 0.11.2](https://packages.debian.org/stretch-backports/prosody).

Buster is the [current stable Debian release](https://www.debian.org/releases/stable/).
Buster-backports [provides 0.11.4](https://packages.debian.org/buster-backports/prosody).

**Comment by saghul** [comment]
Did you intend to close this?

Yes we will migrate to buster, alas we are a bit short on time at the moment.

A pull request would be very welcome, if this is something you’d like to contribute.

**Comment by bkempe** [comment]
I closed it because I accidentally created a separate one here https://github.com/jitsi/docker-jitsi-meet/issues/219
