### ISSUE TITLE
adding JVB to the party

### ISSUE THREAD

**Issue by roeycohen** [jitsi/docker-jitsi-meet#224]
Hi, 
docker-jitsi-meet really works well for me!

now with COVID-19 in the air, everybody wants online conferencing, causing my CPU to sweat :)

what's the best way to add new JVB? 
which ports should I expose out in the original installation?
maybe someone has a YML file for JVB only?
what about sending statistics? should I turn this on? https://github.com/jitsi/jitsi-videobridge/blob/master/doc/statistics.md

10x!

**Comment by sapkra** [comment]
Closing it in favor of #372 
There you can also find a link to a yaml file for JVB only including an explaination.

Information for statistics you can find here: https://github.com/jitsi/docker-jitsi-meet/issues/196#issuecomment-599498182
