### ISSUE TITLE
jibri start failed

### ISSUE THREAD

**Issue by zhouya2010** [jitsi/docker-jitsi-meet#229]
I deployed the jitsi-meet server by docker,but there were problems while I was recording,then jibri start failed and logs as:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-set-timezone: executing...
[cont-init.d] 01-set-timezone: exited 0.
[cont-init.d] 10-config: executing...
ERROR: Please load snd-aloop module on the docker host.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] syncing disks.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

![image](https://user-images.githubusercontent.com/15059113/77051835-df7bc500-6a06-11ea-804f-50f810198acc.png)

**Comment by saghul** [comment]
Well, have you done what the error message says?

**Comment by zhouya2010** [comment]
Thank you for your reply!
web error message:
![image](https://user-images.githubusercontent.com/15059113/77129661-c0754580-6a8f-11ea-89cf-2544fb896e42.png)

![image](https://user-images.githubusercontent.com/15059113/77129696-e7cc1280-6a8f-11ea-8441-c3e8efac5b38.png)

**Comment by saghul** [comment]
Can you expand the error in the JS console? can you paste the jibri logs?

**Comment by zhouya2010** [comment]
The problem is  solved~
https://github.com/jitsi/jibri#pre-requisites

```
echo "snd-aloop" >> /etc/modules
modprobe snd-aloop
lsmod | grep snd_aloop
```
jibri will be start success and recording ok.

**Comment by varkalaramalingam** [comment]
Where I have execute these commands. In docker container or docker host machine???

**Comment by magicdrums** [comment]
> Where I have execute these commands. In docker container or docker host machine???

in the host machine
