### ISSUE TITLE
Enabling guest access disables auth alltogether

### ISSUE THREAD

**Issue by LuLeRoemer** [jitsi/docker-jitsi-meet#231]
After setting `ENABLE_GUESTS=1`, the entire internal authentication mechanism stops working. I expected a registered user to authenticate in order to create a room, allowing guests to join without authentication. Currently, nobody has to authenticate to create a new room.
Thanks in advance for your response!

**Comment by saghul** [comment]
Did you modify the env file after you started the containers by any chance? If so you’ll need to remove the config directory do its auto created

**Comment by LuLeRoemer** [comment]
I'm sorry, you are correct. I had to remove the `~/.jitsi-meet-cfg/jicofo` directory. Thanks for your response! It would be nice if the build process would recognize these changes automatically because right now I need to remove the respective directories manually each time. Removing the entire config directory deletes the Let’s Encrypt certificates, which is not intended.

**Comment by saghul** [comment]
I agree it’s not ideal, we’ll try to improve this.
