### ISSUE TITLE
Init system failed to create config files with correct env vars

### ISSUE THREAD

**Issue by valkum** [jitsi/docker-jitsi-meet#233]
After running docker-compose up -d my containers had <no value> entries in some config files.
After exec bash in the container I managed to delete the configs and execute the init script again. That created the right config files.
Is it possible that s6 ran the init script before obtaining the correct env vars?

**Comment by saghul** [comment]
That's not possible, they are collected before init. Can you check the logs of the containers that failed to start? Also, the broken config files are usually a good indication of what went wrong.

**Comment by valkum** [comment]
I might have an idea for the problem. Found out that the configs are persistently stored in the created dir. (Not sure why an .env is needed then)
First I tried using podman which failed because podman-compose is missing important features.
I did not delete the config folder after that so the wrong config files where still there when i finally used docker.

Nevertheless thanks for your work.
