### ISSUE TITLE
${CONFIG}/prosody/saslauthd.conf template is not filled

### ISSUE THREAD

**Issue by elor** [jitsi/docker-jitsi-meet#234]
After configuring LDAP configuration in the .env file, all authentication fails.
The contents of /config/saslauthd.conf in the prosody container are as follows:

    {{ if eq (.Env.AUTH_TYPE | default "internal") "ldap" }}
    ldap_servers: {{ .Env.LDAP_URL }}
    ldap_search_base: {{ .Env.LDAP_BASE }}
    ldap_bind_dn: {{ .Env.LDAP_BINDDN }}
    ldap_bind_pw: {{ .Env.LDAP_BINDPW }}
    ldap_filter: {{ .Env.LDAP_FILTER | default "uid=%u" }}
    ldap_version: {{ .Env.LDAP_VERSION | default "3" }}
    ldap_auth_method: {{ .Env.LDAP_AUTH_METHOD | default "bind" }}
      {{ if .Env.LDAP_USE_TLS | default "0" | toBool }}
    ldap_tls_key: /config/certs/{{ .Env.XMPP_DOMAIN }}.key
    ldap_tls_cert: /config/certs/{{ .Env.XMPP_DOMAIN }}.crt
        {{ if .Env.LDAP_TLS_CHECK_PEER | default "0" | toBool }}
    ldap_tls_check_peer: yes
    ldap_tls_cacert_file: {{ .Env.LDAP_TLS_CACERT_FILE | default "/etc/ssl/certs/ca-certificates.crt" }}
    ldap_tls_cacert_dir: {{ .Env.LDAP_TLS_CACERT_DIR | default "/etc/ssl/certs" }}
        {{ end }}
        {{ if .Env.LDAP_TLS_CIPHERS }}
    ldap_tls_ciphers: {{ .Env.LDAP_TLS_CIPHERS }}
        {{ end }}
      {{ end }}
    {{ end }}

It looks as if a templating step wasn't triggered during `docker-compose up`.
The logs of the prosody container don't contain anything about a malformed saslauthd.conf file.

After manual configuration of the saslauthd.conf file, everything works as expected.

What did I do wrong? Is this expected?

**Comment by gloacai** [comment]
@elor I've been running into other problems with LDAP that I haven't worked my through yet but I did see that /etc/cont-init.d/10-config is supposed to be using /config/saslauthd.conf as a template to create /etc/saslauthd.conf. The /etc version has been rendered correctly for me.

Was a /etc/saslauthd.conf getting rendered for you and was it's content different than what you're manually configuring?

**Comment by elor** [comment]
Now I get it. /config only contains the template.

Looks like the default values for bind_dn and bind_pw get expanded to `<no value>`:

    root@c3504cab8a06:/# cat /etc/saslauthd.conf
    
    ldap_servers: ldap://my.server.de:389
    ldap_search_base: OU=People,DC=my,DC=server,DC=de
    ldap_bind_dn: <no value>
    ldap_bind_pw: <no value>
    ldap_filter: (uid=%u)
    ldap_version: 3
    ldap_auth_method: bind

What's strange is that `/config/saslauthd.conf` differs from `prosody/rootfs/defaults/saslauthd.conf`.
The latter contains a guard against empty LDAP_BINDDN entries:
https://github.com/jitsi/docker-jitsi-meet/blob/76acc6502734d9bca5fa78b67102cfbc7a4ad29c/prosody/rootfs/defaults/saslauthd.conf#L4-L7

This template fails unfortunately.
It prints the first lines (ldap_servers and ldap_search_base).
Is line 4 is missing a toBool statement?

This template in /config/saslauthd.conf is working for me:

    [...]
    {{ if .Env.LDAP_BINDDN | default "" | toBool }}
    ldap_bind_dn: {{ .Env.LDAP_BINDDN }}
    ldap_bind_pw: {{ .Env.LDAP_BINDPW }}
    {{ end }}

I can provide a patch for `./prosody/rootfs/defaults/saslauthd.conf`, but why is it different from`/config/saslauthd.conf`?

**Comment by elor** [comment]
This is definitely related to commit e92a00ca199ab4f64acc39a245f354164ce8f13a, which was commited just 5 days ago.

As stated above, this commit does not fix the issue.
Instead, rendering of the template aborts.

**Comment by elor** [comment]
And from the looks of it, the abovementioned commit has not made its way into the latest docker image yet ("Updated 3 months ago" according to Docker Hub).

**Comment by saghul** [comment]
We haven't updated the  images with those changes yet. Can you rebuildd them yourself (just run `make`) and try again?

**Comment by elor** [comment]
I rebuilt and deployed the images.
They did not work.

Here's the resulting saslauthd.conf file:

    ldap_servers: ldap://my.server.de:389
    ldap_search_base: OU=People,DC=my,DC=server,DC=de

The rest is missing.

Using the proposed change to the template file fixes the issue:

    ldap_servers: ldap://my.server.de:389
    ldap_search_base: OU=People,DC=my,DC=server,DC=de
    ldap_filter: (uid=%u)
    ldap_version: 3
    ldap_auth_method: bind

The rendering seems to stop at line 4.
Hence merge request #238

**Comment by saghul** [comment]
Do you see any errors in the prosody startup?

**Comment by elor** [comment]
No errors.
Just incomplete config files, nonfunctional saslauthd and hence a broken deployment.
Not even when running template rendering explicitly.

Recap of the template rendering pipeline:
`/usr/bin/tpl` -> `/usr/bin/frep` (subchen/frep) -> golang pkg text/template

According to the [golang text/template package docs](https://golang.org/pkg/text/template/):

    {{if pipeline}} T1 {{end}}
	If the value of the pipeline is empty, no output is generated;
	otherwise, T1 is executed. The empty values are false, 0, any
	nil pointer or interface value, and any array, slice, map, or
	string of length zero.

subchen/frep provides `Env` as a map (`map[string]interface{}`), so undefined config variables result in the desired zero value.
Template rendering should not stop, but it does for our systems.

The mentioned workaround has been incorporated into our deployment pipeline.
This is where my participation ends.

Thank you for your time.

Stay healthy.

**Comment by saghul** [comment]
Thanks @elor I see we use both... andd I think it's working by accident because some valuess will always be defined. Thanks for the patch, just merged it! I'll be reviewing other similar occurrences as time allows.
