### ISSUE TITLE
should passwords in .env be changed?

### ISSUE THREAD

**Issue by roeycohen** [jitsi/docker-jitsi-meet#239]
should one change default passwords for prosody in .env even though prosody ports are internal?

I know the web-server http-bind route is a proxy to prosody - is it possible for an attacker to gain access to non-users rooms such as JVB brewery?

how changing the password should be done? 
will deleting all configurations on the host machine and starting services again, work?

**Comment by roeycohen** [comment]
tried changing the passwords... everything stopped working.
anyone had success with this?

**Comment by saghul** [comment]
If you change the passwords you need to wipe the config volumes so the new settings are applied on the next boot.

In general, I'd suggest you change them, better be safe than sorry.

**Comment by roeycohen** [comment]
i've tried a fresh install, changed the passw0rd and s3cr3t strings in the .env file and now thing doesn't work.
in jicofo docker I get the following message:

`Jicofo 2020-03-20 18:01:24.435 SEVERE: [102] org.jitsi.jicofo.JvbDoctor.log() Unexpected error returned by the bridge: jvb@auth.meet.jitsi/jdzWomnJ, err: <iq to='focus@auth.meet.jitsi/focus1547061600516' from='jvb@auth.meet.jitsi/jdzWomnJ' id='gHSiO-827' type='error'><error type='auth'><forbidden xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></iq>
`

**Comment by roeycohen** [comment]
nevermind, it happened because i've added the following line to docker-compose.yml
![image](https://user-images.githubusercontent.com/2613845/77225572-f2aea200-6b78-11ea-9f26-83bda873cbda.png)
don't understand how and why, but removing the line fixed the problem.
