### ISSUE TITLE
 Jitsi server in Docker enviroment conectivity from mobile client

### ISSUE THREAD

**Issue by danielgimeno** [jitsi/docker-jitsi-meet#24]
I have installed Jitsi environment in Docker. The docker-compose command creates the 4 containers and everything seems to work fine. I can even make a conference between several members, in my local network, every member points its web browser to docker host successfully. Great job Jitsiers!!

The thing here is that my official mobile Jitsi clients cannot join any conversation in the Docker Jitsi server.

We have opened ports 8000 and 8443 and it seems that is enough for web clients connect. It is possible that mobile clients use some additional port? Perhaps, they connect directly to 10000 port?

**Comment by saghul** [comment]
Hello!

Thanks for the kind words!

By default the Docker setup uses a self-signed certificate (I plan to add LetsEnvrypt soon, but it's not there yet), which won't work on mobile.

You do need to open port 10000 though, but I don't think it's related to your failure, or you'd have seen it fail already on your desktop client tests.

**Comment by danielgimeno** [comment]
Finally I have managed to get the mobile logs, and I found this:

10-31 18:04:48.455  8329  8485 E unknown:ReactNative: console.error: "[modules/xmpp/strophe.util.js]", "<n>: ", "Strophe: request id 23.1 error 0 happened", stack:
10-31 18:04:48.455  8329  8485 E unknown:ReactNative: <unknown>@321:2451
10-31 18:04:48.455  8329  8485 E unknown:ReactNative: n@696:150076
10-31 18:04:48.455  8329  8485 E unknown:ReactNative: log@696:813299
10-31 18:04:48.455  8329  8485 E unknown:ReactNative: error@696:20122
10-31 18:04:48.455  8329  8485 E unknown:ReactNative: _onRequestStateChange@696:50951
10-31 18:04:48.455  8329  8485 E unknown:ReactNative: value@73:1501
10-31 18:04:48.455  8329  8485 E unknown:ReactNative: value@72:6294
10-31 18:04:48.455  8329  8485 E unknown:ReactNative: value@72:3038
10-31 18:04:48.455  8329  8485 E unknown:ReactNative: value@42:1292
10-31 18:04:48.455  8329  8485 E unknown:ReactNative: value@29:3471
10-31 18:04:48.455  8329  8485 E unknown:ReactNative: <unknown>@29:956
10-31 18:04:48.455  8329  8485 E unknown:ReactNative: value@29:2898
10-31 18:04:48.455  8329  8485 E unknown:ReactNative: value@29:928
10-31 18:04:48.467  8329  8483 E ReactNativeJS: '[modules/xmpp/strophe.util.js]', '<n>: ', 'Strophe: request id 24.2 error 0 happened'
10-31 18:04:48.468  8329  8483 W ReactNativeJS: '[modules/xmpp/strophe.util.js]', '<n>: ', 'Strophe: request errored, status: 0, number of errors: 2'
10-31 18:04:48.474  8329  8485 E unknown:ReactNative: console.error: "[modules/xmpp/strophe.util.js]", "<n>: ", "Strophe: request id 24.2 error 0 happened", stack:
10-31 18:04:48.474  8329  8485 E unknown:ReactNative: <unknown>@321:2451
10-31 18:04:48.474  8329  8485 E unknown:ReactNative: n@696:150076
10-31 18:04:48.474  8329  8485 E unknown:ReactNative: log@696:813299
10-31 18:04:48.474  8329  8485 E unknown:ReactNative: error@696:20122
10-31 18:04:48.474  8329  8485 E unknown:ReactNative: _onRequestStateChange@696:50951
10-31 18:04:48.474  8329  8485 E unknown:ReactNative: value@73:1501
10-31 18:04:48.474  8329  8485 E unknown:ReactNative: value@72:6294
10-31 18:04:48.474  8329  8485 E unknown:ReactNative: value@72:3038
10-31 18:04:48.474  8329  8485 E unknown:ReactNative: value@42:1292
10-31 18:04:48.474  8329  8485 E unknown:ReactNative: value@29:3471
10-31 18:04:48.474  8329  8485 E unknown:ReactNative: <unknown>@29:956
10-31 18:04:48.474  8329  8485 E unknown:ReactNative: value@29:2898
10-31 18:04:48.474  8329  8485 E unknown:ReactNative: value@29:928

Here is the whole log:


10-31 18:07:29.321  1212  1236 I PowerManagerService: setInteractiveWhileDozingInternal - false
10-31 18:07:29.456  8329  8483 W ReactNativeJS: '[JitsiMeetJS.js]', '<n>: ', 'Analytics disabled, disposing.'
10-31 18:07:29.457  8329  8483 W ReactNativeJS: '[modules/statistics/AnalyticsAdapter.js]', '<n>: ', 'Disposing of analytics adapter.'
10-31 18:07:29.459  8329  8483 I ReactNativeJS: '[modules/RTC/ScreenObtainer.js]', '<n>: ', 'Screen sharing not supported by the current browser: ', 'react-native'
10-31 18:07:29.460  8329  8483 I ReactNativeJS: '[modules/RTC/ScreenObtainer.js]', '<n>: ', 'Desktop sharing disabled'
10-31 18:07:29.464  8329  8483 D ReactNativeJS: '[modules/RTC/RTCUtils.js]', '<n>: ', 'Available devices: ', []
10-31 18:07:29.466  8329  8483 I ReactNativeJS: '[__filename]', '<i>: ', 'Start muted: '
10-31 18:07:29.474  8329  8483 I ReactNativeJS: '[__filename]', '<i>: ', 'Start audio only set to false'
10-31 18:07:29.618  8329  8483 I ReactNativeJS: '[modules/xmpp/xmpp.js]', '<n>: ', 'P2P STUN servers: ', [ { urls: 'stun:stun.l.google.com:19302' },
10-31 18:07:29.618  8329  8483 I ReactNativeJS:   { urls: 'stun:stun1.l.google.com:19302' },
10-31 18:07:29.618  8329  8483 I ReactNativeJS:   { urls: 'stun:stun2.l.google.com:19302' } ]
10-31 18:07:29.626  8329  8483 I ReactNativeJS: '[modules/xmpp/xmpp.js]', '<n>: ', '(TIME) Strophe connecting:\t', 1541005649625
10-31 18:07:29.640  1212 25422 D DnsEventListenerService: Logging 100 results for netId 175
10-31 18:07:29.654  8329  8483 W ReactNativeJS: '[__filename]', '<i>: ', 'Calendar access not granted.'
10-31 18:07:29.655  8329  8483 E ReactNativeJS: '[modules/xmpp/strophe.util.js]', '<n>: ', 'Strophe: request id 35.1 error 0 happened'
10-31 18:07:29.655  8329  8483 W ReactNativeJS: '[modules/xmpp/strophe.util.js]', '<n>: ', 'Strophe: request errored, status: 0, number of errors: 1'
10-31 18:07:29.662  8329  8485 E unknown:ReactNative: console.error: "[modules/xmpp/strophe.util.js]", "<n>: ", "Strophe: request id 35.1 error 0 happened", stack:
10-31 18:07:29.662  8329  8485 E unknown:ReactNative: <unknown>@321:2451
10-31 18:07:29.662  8329  8485 E unknown:ReactNative: n@696:150076
10-31 18:07:29.662  8329  8485 E unknown:ReactNative: log@696:813299
10-31 18:07:29.662  8329  8485 E unknown:ReactNative: error@696:20122
10-31 18:07:29.662  8329  8485 E unknown:ReactNative: _onRequestStateChange@696:50951
10-31 18:07:29.662  8329  8485 E unknown:ReactNative: value@73:1501
10-31 18:07:29.662  8329  8485 E unknown:ReactNative: value@72:6294
10-31 18:07:29.662  8329  8485 E unknown:ReactNative: value@72:3038
10-31 18:07:29.662  8329  8485 E unknown:ReactNative: value@42:1292
10-31 18:07:29.662  8329  8485 E unknown:ReactNative: value@29:3471
10-31 18:07:29.662  8329  8485 E unknown:ReactNative: <unknown>@29:956
10-31 18:07:29.662  8329  8485 E unknown:ReactNative: value@29:2898
10-31 18:07:29.662  8329  8485 E unknown:ReactNative: value@29:928
10-31 18:07:29.664  8329  8329 W ResourceType: No known package when getting name for resource number 0xffffffff
10-31 18:07:29.665  8329  8329 I org.webrtc.Logging: EglRenderer: setMirror: true
10-31 18:07:29.675  8329  8483 E ReactNativeJS: '[modules/xmpp/strophe.util.js]', '<n>: ', 'Strophe: request id 36.2 error 0 happened'
10-31 18:07:29.675  8329  8483 W ReactNativeJS: '[modules/xmpp/strophe.util.js]', '<n>: ', 'Strophe: request errored, status: 0, number of errors: 2'
10-31 18:07:29.677  1212 19560 I WindowManager: Destroying surface Surface(name=SurfaceView - org.jitsi.meet/org.jitsi.meet.MainActivity) called by com.android.server.wm.WindowStateAnimator.destroyDeferredSurfaceLocked:926 com.android.server.wm.WindowManagerService.performDeferredDestroyWindow:3197 com.android.server.wm.Session.performDeferredDestroy:234 android.view.IWindowSession$Stub.onTransact:398 com.android.server.wm.Session.onTransact:145 android.os.Binder.execTransact:565 <bottom of call stack> <bottom of call stack> 
10-31 18:07:29.681  8329 12727 I org.webrtc.Logging: EglRenderer: Dropping frame - No surface
10-31 18:07:29.682   450   450 I SFPerfTracer:       trigger: frame rate (-31.408%)	(41.155 fps)	(24.298 ms) 	(115 drops)	(278 frames)
10-31 18:07:29.682   450   450 I SFPerfTracer:      triggers: (rate: 5390:255873) (compose: 3:938) (post: 0:327) (render: 0:4959) (278:851334 frames) (279:915076)
10-31 18:07:29.682   450   450 D SFPerfTracer:        layers: (4:8) (StatusBar (0x7f29289000): 12:128637) (com.android.systemui.ImageWallpaper (0x7f2928c800): 12:87084)* (DimLayerController/Stack=0 (0x7f2928e400): 0:1452)* (animation background stackId=1 (0x7f2922e000): 0:536)* (NavigationBar (0x7f2cc9c400): 12:2381) (org.jitsi.meet/org.jitsi.meet.MainActivity (0x7f2922fc00): 150:9398) (SurfaceView - org.jitsi.meet/org.jitsi.meet.MainActivity (0x7f2cc93800): 12:18)* (SurfaceView - org.jitsi.meet/org.jitsi.meet.MainActivity (0x7f2928ac00): 209:215) 
10-31 18:07:29.684  8329  8485 E unknown:ReactNative: console.error: "[modules/xmpp/strophe.util.js]", "<n>: ", "Strophe: request id 36.2 error 0 happened", stack:
10-31 18:07:29.684  8329  8485 E unknown:ReactNative: <unknown>@321:2451
10-31 18:07:29.684  8329  8485 E unknown:ReactNative: n@696:150076
10-31 18:07:29.684  8329  8485 E unknown:ReactNative: log@696:813299
10-31 18:07:29.684  8329  8485 E unknown:ReactNative: error@696:20122
10-31 18:07:29.684  8329  8485 E unknown:ReactNative: _onRequestStateChange@696:50951
10-31 18:07:29.684  8329  8485 E unknown:ReactNative: value@73:1501
10-31 18:07:29.684  8329  8485 E unknown:ReactNative: value@72:6294
10-31 18:07:29.684  8329  8485 E unknown:ReactNative: value@72:3038
10-31 18:07:29.684  8329  8485 E unknown:ReactNative: value@42:1292
10-31 18:07:29.684  8329  8485 E unknown:ReactNative: value@29:3471
10-31 18:07:29.684  8329  8485 E unknown:ReactNative: <unknown>@29:956
10-31 18:07:29.684  8329  8485 E unknown:ReactNative: value@29:2898
10-31 18:07:29.684  8329  8485 E unknown:ReactNative: value@29:928
10-31 18:07:29.684  8329  8329 I org.webrtc.Logging: EglRenderer: Releasing.
10-31 18:07:29.684  8329 12727 I org.webrtc.Logging: GlShader: Deleting shader.
10-31 18:07:29.684  8329 12727 E libEGL  : call to OpenGL ES API with no current context (logged once per thread)
10-31 18:07:29.684  8329 12727 I org.webrtc.Logging: EglRenderer: eglBase detach and release.
10-31 18:07:29.689  8329 12727 I org.webrtc.Logging: EglRenderer: Quitting render thread.
10-31 18:07:29.689  8329  8329 I org.webrtc.Logging: EglRenderer: Releasing done.
10-31 18:07:29.694  8329  8329 W ViewPager: Requested offscreen page limit 0 too small; defaulting to 1
10-31 18:07:29.694  8329  8329 I org.webrtc.Logging: EglRenderer: Initializing EglRenderer
10-31 18:07:29.696  8329 12737 I org.webrtc.Logging: EglRenderer: EglBase.create shared context
10-31 18:07:29.696  8329 12737 I org.webrtc.Logging: EglBase14: SDK version: 24. isEGL14Supported: true
10-31 18:07:29.714  8329  8681 I org.webrtc.Logging: SurfaceEglRenderer: : Reporting first rendered frame.
10-31 18:07:29.714  8329  8681 I org.webrtc.Logging: SurfaceEglRenderer: : Reporting frame resolution changed to 1280x720 with rotation 270
10-31 18:07:29.714  8329 12737 I org.webrtc.Logging: EglRenderer: Dropping frame - No surface
10-31 18:07:29.724  8329  8329 I org.webrtc.Logging: EglRenderer: setLayoutAspectRatio: 1.0
10-31 18:07:29.738  8329  8329 I org.webrtc.Logging: SurfaceEglRenderer: : surfaceChanged: format: 4 size: 1344x1344
10-31 18:07:29.746  8329  8329 D com.oney.WebRTCModule.WebRTCModule: First frame rendered.
10-31 18:07:29.862  2864  2864 D HeadsetPhoneState: Enter onSignalStrengthsChanged
10-31 18:07:29.862  2864  2864 D HeadsetPhoneState: Exit onSignalStrengthsChanged
10-31 18:07:30.521  8329  8681 I org.webrtc.Logging: CameraStatistics: Camera fps: 30.
10-31 18:07:31.381  8329  8483 I ReactNativeJS: '[__filename]', '<i>: ', 'redux state persisted. f788039c7ae09db48dc4189c6f765572 -> 1b957a59240b486b729cb08021c1cf8f'
10-31 18:07:32.521  8329  8681 I org.webrtc.Logging: CameraStatistics: Camera fps: 30.

**Comment by saghul** [comment]
I don't see anything obvious in the log :-/ Can you reproduce it with the version from the Store?

**Comment by saghul** [comment]
This should Just Work (TM) now that Let's Encrypt is built right in.

**Comment by hasgardee** [comment]
@saghul same issue..only for few android phone have this issue, I installed letsencrypt. I'm getting black screen only while connecting to the call from those devices. but after 10-15 seconds other participants can see their camera and audio. but in that device only black screen

[logcat.txt](https://github.com/jitsi/docker-jitsi-meet/files/4858016/logcat.txt)
