### ISSUE TITLE
Everybody is a moderator?

### ISSUE THREAD

**Issue by ErrorInPersona** [jitsi/docker-jitsi-meet#242]
Starting jitsi with the default config and latest images, everybody can create and join every room and everybody is a moderator.
Activating Auth via jwt works fine, still everybody is a moderator. 
Activating Auth via jwt and enable gues access + allow empty token results in everybody joining and still everybody, also guests, being set as moderator.

That way the moderator-feature does not make any sense in my opinion.
What am I missing? Or is this behavior intended?
My goal would be: Persons who join via valid jwt become moderators, the rest is set as a normal user.

Kind regards!

**Comment by saghul** [comment]
I think we should have a way to disable the everyone is a moderator thing indeed.

**Comment by ErrorInPersona** [comment]
If the situation as it is now is on purpose: Yes! Because if everybody is a moderator, no one is.

**Comment by ortomind** [comment]
I have the same issue with the docker and also there are mentioned some caveats that may be overcome if that feature will be added in the main image.
Since all my users I require to join via API with JWT I would need to assign moderator to a specific JWT. jitsi-token-moderation-plugin do that in API but looks like that breaks some other features are essential in a group meeting like banning people...
I hope I will see that feature in the main install soon :)

**Comment by enoch85** [comment]
What we want: Only the one with the token should be moderator
What we have: Anyone that joins the room as the first person becomes a moderator.

This is with `allow_empty_token = true`

Any update on this issue?

**Comment by anonid64** [comment]
i have been solved this issue. In my server, in file `/etc/jitsi/jicofo/jicofo.conf`

remove code 

```
authentication: {
    enabled: true
    type: XMPP
    login-url: <your_domain>
  }
```

After remove, only first one person is set as moderator. I double check in my server, that's work!

**Comment by saghul** [comment]
Indeed the all owners module is not enabled by default so I think this is good to close.

**Comment by gauravBasra07** [comment]
I receive the same issue @ErrorInPersona,   could you please tell me how you were get rid from this problem?

**Comment by karthikeyanreactdev** [comment]
I'm also facing the same issue, In the JWT token I have set moderator:false but after I joined the meet via token , showing the message that you`re joined as a moderator. Please help me to sort this issue. 

I have self hosted Jitsi in AWS EC2 Ubuntu 22.04

**Comment by pouriamoosavi** [comment]
No answer for this?

**Comment by gauravBasra07** [comment]
@pouriamoosavi 

Try this goto this ` /etc/jitsi/jicofo` location on your server. Open jicofo.conf file and add

`conference: {
    enable-auto-owner: false
  }
`
Now the complete view of the file should be

  
# Jicofo HOCON configuration. See reference.conf in /usr/share/jicofo/jicofo.jar for
#available options, syntax, and default values.
jicofo {
  xmpp: {
    client: {
      client-proxy: "focus.myDomain.com"
      xmpp-domain: "myDomain.com"
      domain: "auth.myDomain.com"
      username: "userName"
      password: "mypassword"
    }
    trusted-domains: [ "recorder.myDomain.com" ]
  }
  bridge: {
    brewery-jid: "JvbBrewery@internal.auth.myDomain.com"
  }
  conference: {
    enable-auto-owner: false
  }
  jibri: {
    brewery-jid: "JibriBrewery@internal.auth.myDomain.com"
    pending-timeout: 90 seconds
  }
}

**Comment by AmirMehr** [comment]
> [@pouriamoosavi](https://github.com/pouriamoosavi)
> 
> Try this goto this ` /etc/jitsi/jicofo` location on your server. Open jicofo.conf file and add
> 
> `conference: { enable-auto-owner: false } ` Now the complete view of the file should be
> 
> # Jicofo HOCON configuration. See reference.conf in /usr/share/jicofo/jicofo.jar for
> #available options, syntax, and default values. jicofo { xmpp: { client: { client-proxy: "focus.myDomain.com" xmpp-domain: "myDomain.com" domain: "auth.myDomain.com" username: "userName" password: "mypassword" } trusted-domains: [ "recorder.myDomain.com" ] } bridge: { brewery-jid: "[JvbBrewery@internal.auth.myDomain.com](mailto:JvbBrewery@internal.auth.myDomain.com)" } conference: { enable-auto-owner: false } jibri: { brewery-jid: "[JibriBrewery@internal.auth.myDomain.com](mailto:JibriBrewery@internal.auth.myDomain.com)" pending-timeout: 90 seconds } }

I did this on my own vps still the same, everyone is a moderator.
and also I add `ENABLE_AUTO_OWNER=0` to the `.env` file.


Any solution will be appreciated. My auth is with JWT.

**Comment by amsnek** [comment]
hmm also have this issue, when using JWT where moderator is true for the person joining with a token, users without a JWT (joining via lobby knock) are moderators. 

in jicofo: 
enable-auto-owner: false 
(this should only affect if the current moderator leaves however?)

dont think this matters, but I also use lobby_autostart, token_lobby_bypass, token_affiliation, token_verification.

If I use a Token with moderator: false -> it works, but Users that join without a token *at all* seem to always be automatically moderators.
