### ISSUE TITLE
[Feature Request] Disable Access Logging

### ISSUE THREAD

**Issue by valkum** [jitsi/docker-jitsi-meet#243]
Would be nice if you could set a flag in the .env file that would disable all access logging in nginx and the other services.

**Comment by saghul** [comment]
Good idea! Are you willing to give it a shot?

**Comment by flecno** [comment]
I have added a PR to allow the control of logs for all components - not only nginx access logs

**Comment by saghul** [comment]
Nice, let' continue on #434
