### ISSUE TITLE
get full name while using ldap

### ISSUE THREAD

**Issue by mboogert** [jitsi/docker-jitsi-meet#244]
It would be great if the full name could be retrieved and used whenever using ldap for authentication.

**Comment by saghul** [comment]
This would need prosody to extract that info and attach it to the user, not surre if it'ss capable of doing that.

**Comment by Gelmir** [comment]
Hello, any info on this?

With `mod_lib_ldap` and `mod_auth_ldap2` + `mod_storage_ldap` prosody can populate vcard from LDAP.
After connecting to prosody directly with Psi I got vcard with whatever LDAP mappings I defined in config. Still no name in meet though.

**Comment by federico-ntr** [comment]
@mboogert I see you closed the issue, did you manage to find a solution? If so, how did you solve this problem? 

I'm required to get full name from LDAP and show it in Jitsi Meet as display name. I tried looking into the mentioned lua modules, but I'm too dumb to understand them apparently and I don't know what to change to get the full name.

**Comment by thunders82** [comment]
Same here! Is it possible?
