### ISSUE TITLE
feature request:

### ISSUE THREAD

**Issue by cocoonkid** [jitsi/docker-jitsi-meet#251]
Jitsi is the best there is. No question about it.
I found it is missing just very minimal additions to make it truly unique.

- Allow password protecting a whole server instance
- Add a away to sticky rooms for a specific instance
- Add controlling others screen (I think this is already being implemented)
- Allow moderators to mute/unmute room notifications - I would like to get small notifications if and who enters another room. Like a small ping.
- Add a "waiting room" where people can get queued and maybe even speak with a service person
- Allow to prepare a form which can be pulled by a JSON API for the data to be available for the service desk.
- AI-based camera framing might be slicker than the background morph or a blue screen option.
- Option to zoom in like with the mobile app.
- Option for a recording (audio or both, audio and video)

These would help tremendously.
(PDF support/presentation mode is just a nice to have)

Thank everyone for making this possible!

In light of the global corona outbreak these would be features that would be standing out immensely! I'd love to deploy this for many many small teams !

**Comment by Echolon** [comment]
@cocoonkid would you be so kind and split and/or summarize you request with proper titles (just shortly describe your request)? That would make a realization more likely.

Please review if your ideas have been state before.

**Comment by Echolon** [comment]
Unfortunately, I have to close this until it is better stated :(
Ping me and I will reopen

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
