### ISSUE TITLE
Why Jitsi works using just port 443 from behind NAT?

### ISSUE THREAD

**Issue by dowhiletrue** [jitsi/docker-jitsi-meet#255]
I set up an Apache reverse proxy in front of the web docker container, which is exposed to the internet on port 443, terminates tls and forwards the traffic to port 8000 of the web container. None of the other ports were forwarded to the internet. I then connected from two different locations (both behind separate NAT) to the the apache based host. Video streaming between the two participiants works without any problem, I just can't explain why? I see higher cpu load on the bridge, which makes me believe, that the video stream is mediated on the bridge. Is there any magic multiplixing happening on that single exposed port?

**Comment by damencho** [comment]
The default installation does multiplexing on 443 when using jetty (current stable) and the current unstable, which will be next stable is multiplexing on nginx between turn server and web. 

Please use the community forum when you have questions or problems before opening new issues.

**Comment by damencho** [comment]
Oh I didn't noticed the docker repo when replying. I was taking about jitsi-meet deployed directly from debian package on a Linux.

**Comment by dowhiletrue** [comment]
Thanks for your answer @damencho, I just noticed, that docker creates an iptables forward rule, which answers my question.
