### ISSUE TITLE
creating own jitsi-web Dockerfile

### ISSUE THREAD

**Issue by f1-outsourcing** [jitsi/docker-jitsi-meet#256]
I was just testing a bit if I could build my own docker image from an own Dockerfile composed from some data in the base and web Dockerfile. 

However when I open the image in bash, I do not see any jitsi configuration file in the nginx configuration folder. Where is this file?

**Comment by f1-outsourcing** [comment]
sorry I think everything is here

https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md

**Comment by f1-outsourcing** [comment]
root@65739706d685:/# apt-get install jitsi-meet-web-config
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  jitsi-meet-web-config
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 13.1 kB of archives.
After this operation, 54.3 kB of additional disk space will be used.
Get:1 https://download.jitsi.org stable/ jitsi-meet-web-config 1.0.3729-1 [13.1 kB]
Fetched 13.1 kB in 0s (52.1 kB/s)
Preconfiguring packages ...
Selecting previously unselected package jitsi-meet-web-config.
(Reading database ... 12372 files and directories currently installed.)
Preparing to unpack .../jitsi-meet-web-config_1.0.3729-1_all.deb ...
Unpacking jitsi-meet-web-config (1.0.3729-1) ...
Setting up jitsi-meet-web-config (1.0.3729-1) ...
Generating a RSA private key
.......................................++++
..............++++
writing new private key to '/etc/jitsi/meet/localhost.key'
-----
cp: cannot stat '/usr/share/doc/jitsi-meet-web-config/config.js': No such file or directory
dpkg: error processing package jitsi-meet-web-config (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 jitsi-meet-web-config
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by saghul** [comment]
How does your Dockerfile look so far? What exactly are you trying to accomplish?

**Comment by f1-outsourcing** [comment]
At the moment I do not have one yet for meet. I have now done 3, one for prosody based on the original prosody package, the videobridge and the conference focus. These seem to connect ok. 
I want to have more 'clean' docker images. No offense meant, but yours look a bit like a mess. I think they would not even run on mesos. 
I like that you emphasize the use of keys on your repository when using your packages and spent time on it in your video. And then in your docker images you download blobs from everywhere. I tried first a few of yours, and one started making certificates and keys. 
Anyway, I want to provision my containers with certificates and configuration files, by fetching files at deployment and have the option to configure them via environment variables. Also I want to keep tasks that do not need to be internet facing on a local network, and tasks that need to be internet facing multihomed (ip on localnet and public one) Or behind a load balancer ;) don't know yet. 

If I understand now correctly the meet component is a nodejs project? It is being(can be) accessed by nginx fronted (via this proxy_pass). Is this a correct assumption? Because this graph[1] indicates meet are just files.

Here is described how to get meet
https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md#deploy-jitsi-meet

But if I check out that, I am getting android and ios code?? How do I just get the meet files, so I can make a docker image just for meet.
Ideally I would like to have something like in [2] where we can maybe autoscale tasks. So if the load increases on the meet task, we spawn a new instance.



[1]
```
               +-------+  
               |       |  
               | Nginx |  
               |       |  
               +--+-+--+  
                  |       
+------------+    |       
|            |    |       
| jitsi-meet +<---+       
|            |files       
+------------+        
```    

[2]
```
               +-------+                                 
               |       |                                 
               | Nginx |                                 
               |       |                                 
               +--+-+--+                                 
                  | |                                    
+------------+    | |    +--------------+                
|            |    | |    |              |                
| jitsi-meet +----+ +----+ prosody/xmpp |                
|            |           |              |                
+------------+           +----+----+----+                
                              |    |                     
                +--------+    |    |    +-------------+  
                |        |    |    |    |             |  
                | jicofo +----+    +----+ videobridge |  
                |        |              |             |  
                +--------+              +-------------+  
```

**Comment by saghul** [comment]
> I want to have more 'clean' docker images. No offense meant, but yours look a bit like a mess. I think they would not even run on mesos.

Offense taken.

We don't intend to make it work with every single container-running-thing in the planet.

You don't like these images? Great, build your own. But asking for help and shitting all over other's work while not even understanding the project at hand won't get you very far, pal.

**Comment by f1-outsourcing** [comment]
Learn and do not whine about criticism, act a bit more professional. 

If I understand now correctly the meet component is a nodejs project? It is being(can be) accessed by nginx fronted (via this proxy_pass). Is this a correct assumption? 

And if so how/where to get this?
