### ISSUE TITLE
fullchain.pem missing letsencrypt

### ISSUE THREAD

**Issue by ayounggun** [jitsi/docker-jitsi-meet#257]
Hi jitsi team

I can't connect to the web UI at port 8443 on the public URL I specified in the .env file. It fails with refused to connect in chrome.

`docker logs docker-jitsi-meet_web_1` gives the following error repeated:

```
nginx: [emerg] BIO_new_file("/etc/letsencrypt/live/[redacted]/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/[redacted]/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file
```

I'm having problem with your letsencrypt built in support I think.

`docker-compose up -d
` runs without errors.

I have opened the relevant ports on the host I believe.

Do you know what I can do to correct this problem?

Thanks

**Comment by c-goes** [comment]
change the ports to 443 and 80

**Comment by ayounggun** [comment]
> try change the ports to 443 and 80

Hi c-goes

Thanks for the quick reply!

Is that referring to the ports in the env file here

```
# Exposed HTTP port.
HTTP_PORT=8000

# Exposed HTTPS port.
HTTPS_PORT=8443

```
so they would become the following?
```
# Exposed HTTP port.
HTTP_PORT=80

# Exposed HTTPS port.
HTTPS_PORT=443

```

**Comment by c-goes** [comment]
yes, otherwise let's encrypt won't give you a certificate

**Comment by funkyfuture** [comment]
i'm having the same issue. i see two problems:

- the path segment that @ayounggun marked as `[redacted]` is a URL and thus contains forward slashes, despite having `LETSENCRYPT_DOMAIN` set to solely a domain name w/o URL scheme
- the directory `etc/letsencrypt/live` doesn't exist

**Comment by funkyfuture** [comment]
in my case issue stemmed from the facts that i initially had `LETSENCRYPT_DOMAIN` set with a URL scheme and that the contents in the config folder (`web/nginx/ssl.conf` in particular) persist after changing this variable's value. as a solution for the immediate problem i recommend:

    docker-compose down --volumes  # in the Docker-Compose project folder
    rm -rf *  # in the config folder

generally, persisting derivatives are a problem creator, not only with Docker.

this doesn't solve the issue that the `/etc/letsencrypt/live` directory is missing.

**Comment by funkyfuture** [comment]
in my case i figured that the firewall isn't yet configured to allow incoming requests from the world and hence `certbot`'s verification is failing. thus, that failure should be handled by exiting the container. i'll see that i address that in a pr when i have the time.
