### ISSUE TITLE
binaries for jicofo

### ISSUE THREAD

**Issue by f1-outsourcing** [jitsi/docker-jitsi-meet#259]
Is there something for jicofo like for videobridge here?

https://download.jitsi.org/jitsi-videobridge/linux/

**Comment by ulab** [comment]
I am not sure if this is the right place to ask. This project is to build docker images for jitsi, not about the project or its parts per se.

Also a better place to ask something like this is on the [Jitsi community](https://community.jitsi.org/). "Issues" are usually reserved for bugs or feature requests, but not for general questions or discussions.

**Comment by f1-outsourcing** [comment]
> 
> 
> I am not sure if this is the right place to ask. This project is to build docker images for jitsi, not about the project or its parts per se.
> 
> Also a better place to ask something like this is on the [Jitsi community](https://community.jitsi.org/). "Issues" are usually reserved for bugs or feature requests, but not for general questions or discussions.

I am not getting the activation email, who should I contact?
