### ISSUE TITLE
jwt_allow_empty = 1 permitting room creation from guests

### ISSUE THREAD

**Issue by ClundXIII** [jitsi/docker-jitsi-meet#268]
Hello,

according to this thread:
https://community.jitsi.org/t/jwt-tokens-and-guest-access/18119/18
I can disallow guest access in general but allow guests to join a room via link if I specify the following parameter:

```
# Enable authentication.
ENABLE_AUTH=1

# Enable guest access.
ENABLE_GUESTS=0

# Select authentication type: internal, jwt or ldap
AUTH_TYPE=jwt

# JWT auuthentication
#

# Application identifier.
JWT_APP_ID=<removed>

# Application secret known only to your token.
JWT_APP_SECRET=<removed>

JWT_ALLOW_EMPTY=1
```

However this config also allows guests to create rooms. I deleted the cfg folder and also used incognito mode to make sure the browser had no leftover authenticated cookie.

Is this behaviour intended? And if yes, is there any other way to only restrict room creation but not invite via link?

**Comment by saghul** [comment]
I think you'll want ENABLE_GUESTS=0 and JWT_ALLOW_EMPTY=0 This way when a user joins via a link they'll be challenged for authentiication or they can wait for the owner to arrive.

**Comment by ClundXIII** [comment]
> I think you'll want ENABLE_GUESTS=0 and JWT_ALLOW_EMPTY=0 This way when a user joins via a link they'll be challenged for authentiication or they can wait for the owner to arrive.

nope. that setting wants to have a username and password.

**Comment by saghul** [comment]
Scratch that. I think you need ENABLE_GUESTS=1, but you also need a fix in the tokens module which is not yet on a stable release: https://github.com/jitsi/jitsi-meet/pull/5025

**Comment by ClundXIII** [comment]
> Scratch that. I think you need ENABLE_GUESTS=1, but you also need a fix in the tokens module which is not yet on a stable release: [jitsi/jitsi-meet#5025](https://github.com/jitsi/jitsi-meet/pull/5025)

is it possible to change the branch via the docker-compose.yml ?

**Comment by saghul** [comment]
you can test by using the unstable repository. Rebuild the images as follows: `FORCE_REBUILD=1 JITSI_RELEASE=unstable make` then delete the config folder, then `docker-compose up` as usual.

**Comment by ClundXIII** [comment]
```
ENABLE_GUESTS=1

JWT_ALLOW_EMPTY=0
```

Still promts me for a password.

```
ENABLE_GUESTS=1

JWT_ALLOW_EMPTY=1
```
wants a password as well o.O (Both for joining a room I already created and creating a new room)

**Comment by saghul** [comment]
Doesn't it ask you if you want to wait for a moderator?

**Comment by ClundXIII** [comment]
> Doesn't it ask you if you want to wait for a moderator?

No. should it?

**Comment by saghul** [comment]
Yeah, that should be the behavior when guests are allowed. Note that we have never ussed JWT like this, and the fix I mentioned was  provided to us recently. There might be some other bug in there...

**Comment by ClundXIII** [comment]
Does the Guest access work properly with LDAP? In that case I would use that authentication mode instead.

**Comment by saghul** [comment]
It should, yeah.

**Comment by ClundXIII** [comment]
For various reasons I switched to the non-dockerized version (on a dedicated vm).

Do I need to switch to the unstable repository in order to get this working?

**Comment by saghul** [comment]
No, the unstable repo change was for the JWT fix. We are preparing a new stable release, so unstable shouldn't even work right now...

**Comment by ClundXIII** [comment]
You can close this issue if you want. I solved it by setting up a new jitsi instance inside a dedicated vm. And by using sasl + ldap.
