### ISSUE TITLE
Jibri docker image fails on start

### ISSUE THREAD

**Issue by OctoOsmo** [jitsi/docker-jitsi-meet#269]
I am trying to start jitsi with jibri on a clean install according to readme
docker-compose -f docker-compose.yml -f jibri.yml up -d
I have this error
ERROR: for jibri  Cannot start service jibri: error gathering device information while adding custom device "/dev/snd": no such file or directory

other services are fine 
Starting docker-jitsi-meet_prosody_1 ... 
Starting docker-jitsi-meet_jibri_1   ... error
Starting docker-jitsi-meet_prosody_1 ... done
Starting docker-jitsi-meet_web_1     ... done
Starting docker-jitsi-meet_jicofo_1  ... done
Starting docker-jitsi-meet_jvb_1     ... done

**Comment by please-wait** [comment]
See the readme's Jibri section. You don't have `snd-aloop` on your system. You need to install it and make sure the commands in that part of readme work.

**Comment by saghul** [comment]
What @please-wait saidd :-)

**Comment by OctoOsmo** [comment]
You mean on a host system?
But what if run it on mac or windows?

**Comment by saghul** [comment]
Yes, on the host system. Jibri can only run on a Linux host system.
