### ISSUE TITLE
Integrating into existing reverse proxy setup

### ISSUE THREAD

**Issue by frispete** [jitsi/docker-jitsi-meet#270]
Hi, 

I try to wrap my head around the configuration of this project in such a way, that the existing rev-proxy setup isn't harmed. Some services {gitlab, discourse} are available with the pattern service.e xample.org already and nginx relays them to local host/docker instances, redirects http to https as well as provides the certbot certs. 

Access from LAN works well, but the rev-proxy access via `https://meet.example.org` fails with: 
```
400 Bad Request
The plain HTTP request was sent to HTTPS port
```
Any idea, what I'm missing?

Here's the relevant config:
```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name meet.example.org;
    server_tokens off; 
    access_log  /var/log/nginx/meet_access.log;
    error_log   /var/log/nginx/meet_error.log;

    location / {
        proxy_redirect off;
        proxy_set_header Host $http_host;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Ssl on;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://localhost:8443;
    }

    ssl_certificate /etc/letsencrypt/live/example.org/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/example.org/privkey.pem; # managed by Certbot
}
```

If such a setup is of broader interest (I think so), I may provide the configuration changes, once this is working and I've figured out, how to push the certbot certs into the jitsi setup.

**Comment by frispete** [comment]
Moved to:
https://community.jitsi.org/t/integrating-into-existing-reverse-proxy-setup/25166

**Comment by saghul** [comment]
> proxy_pass http://localhost:8443;

8443 is the HTTPS port, you want to proxy to 8000.

**Comment by frispete** [comment]
Thanks @saghul that did the trick, but unfortunately, it is still not [operational](#294). :cry:

**Comment by laenan8466** [comment]
Hi @frispete :  I'm trying to archive the same thing, but with no success so far. Did you had any success?

**Comment by frispete** [comment]
@laenan8466 Sure, it's working mostly fine here now. You will find most configuration deviations/woes of my setup in #294 as well as a couple of bumpy roads, that I mistakenly followed, over there.

You may want to fully read that issue and call back, if you're stuck again.

I've created a small [script](https://gist.github.com/frispete/c99c5bd46aede1505b004494d2e4fe65), that does the handwork. If it proves useful for you, let me know.
