### ISSUE TITLE
How to edit web config.js and interface_config.js

### ISSUE THREAD

**Issue by rayhaanq** [jitsi/docker-jitsi-meet#275]
Hi there, I was wondering how I would edit the config.js and interface_config.js files for the web without editing the source code itself? Otherwise I would need to create my own image to point the docker compose file to. Or is that what I'm supposed to do?

I've tried adding my own config files to the `.jitsi-meet-cfg/web` directory but it doesn't seem to have any effect.
Thanks

**Comment by rob-otter** [comment]
> I've tried adding my own config files to the .jitsi-meet-cfg/web directory but it doesn't seem to have any effect.
I have the same issue.

I also wanted to ask, if there exists a way of editing the index page without building https://github.com/jitsi/jitsi-meet?

Thanks!

**Comment by saghul** [comment]
@rayhaanq You can edit them after the container starts, since they are generated at boot.

**Comment by digital-codes** [comment]
Hi was not able to find how to create the docker image for the web container from the jitsi-meet git repository. The instructions how to do this are the only thing I'm missing from this project, which I appreciate a lot!
Meanwhile, I'm using a script to do some customization (run after the containers are started):

#!/bin/bash
# modify logo and css for background color and German translation
export WID=`docker container ls -f name=web --format "{{.ID}}"`
echo "Web ID: $WID"
docker container cp praxlogo.png $WID:/usr/share/jitsi-meet/images/watermark.png
docker container cp all.css $WID:/usr/share/jitsi-meet/css/
docker container cp main-de.json $WID:/usr/share/jitsi-meet/lang/
# copy prosody accounts for local authorisation
export PID=`docker container ls -f name=prosody --format "{{.ID}}"`
echo "Prosody ID: $PID"
# wildcards dont work with exec ...
docker container cp xxx.dat $PID:/config/data/meet%2ejitsi/accounts/
docker-compose exec prosody chown prosody.prosody /config/data/meet%2ejitsi/accounts/xxx.dat

You have to run this after each reboot/restart.

**Comment by rayhaanq** [comment]
If I want to edit the `interface_config.js` file after the docker container is running where is the file located? I've looked in the container and there doesn't seem to be a file called `interface_config.js` or `config.js`. I had a look at this https://community.jitsi.org/t/jitsi-users-how-to-remove-logo-name-of-window-and-protect-welcome-screen-with-a-password/11191

The post is from 2016 though so maybe out of date. John_Lightfoot suggested replicating the nginx config for the `interface_config.js`. If that's what I need to do, how do I do it? @saghul @digital-codes

**Comment by rayhaanq** [comment]
Nevermind, I found it. Both config files are located in the /config directory on the container. Copying over the files using docker container cp after the container was running worked fine. Thanks

**Comment by cs8898** [comment]
Use the ~/.jitsi-meet-cfg/web folder, its a mounted volume, makes it easier ;D

**Comment by dinesh547** [comment]
I also have the same issue. I am runnig jitsi-meet at localhost. using command make dev.
But the changes i made in interface_config.js never reflects while debugging,
Can anyone please guide how to do that and in which file i need to make changes to make it work,

**Comment by dinesh547** [comment]
> Use the ~/.jitsi-meet-cfg/web folder, its a mounted volume, makes it easier ;D

where is this folder? i am not seeing any such folder on mac,

**Comment by dinesh547** [comment]
> Nevermind, I found it. Both config files are located in the /config directory on the container. Copying over the files using docker container cp after the container was running worked fine. Thanks

can you please tell me the container location ? I am running at local host just using make dev command.

**Comment by cs8898** [comment]
Did you use the docker-compose?

Then the configs are there where i told earlier...
`~/.jitsi-meet-cfg`

But you have to use the .env also...

**Comment by dinesh547** [comment]
> Did you use the docker-compose?
> 
> Then the configs are there where i told earlier...
> `~/.jitsi-meet-cfg`
> 
> But you have to use the .env also...

I dont have any /.jitsi-meet-cfg file on my machine.
not sure what is .env?

**Comment by sapkra** [comment]
It's not in the root directory. `~` means the user directory of your current user.
A `.env` file just simulates environment variables for docker-compose in this example.

**Comment by wivaku** [comment]
I am having trouble with the custom configuration.
Using `~/.jitsi-meet-cfg/web/custom-interface_config.js`: 

```
var interfaceConfig = {
        DEFAULT_REMOTE_DISPLAY_NAME: 'Guest', // default: Fellow Jitser
}
```

But after docker-compose down/up the site is incomplete: I can type in a new room name but the history or page footer are not shown. So: the top part of the screen is shown, the bottom parts are missing.

And when starting a session -after logging in as host- my camera is shown at 50% in the middle of the screen (and behind it: full screen a blurred version) and the moderator menu looks mangled.

No browser error messages in the console, or obvious error messages in the log of the Docker containers.

**Comment by cs8898** [comment]
@wivaku you are on the right Track...

What you did: redefined `interfaceConfig` variable

Instead use JS to set only the values

```js
//CUSTOM CONFIG
interfaceConfig.DEFAULT_REMOTE_DISPLAY_NAME = "Guest";
```


I also tried setting the `APP_NAME`, what actually works for the Title but not for the `H1` on the welcome page...


After restarting the container you will notice that the custom-*.js gets appendet to the corresponding conf js file.

**Comment by wivaku** [comment]
Thanks so much, that was it. I (incorrectly) assumed the objects would get merged.
