### ISSUE TITLE
My Jitsi-Docker Server is working significant less reliable then jitsi.org

### ISSUE THREAD

**Issue by mogoh** [jitsi/docker-jitsi-meet#276]
Hello,

first of all, if this is the wrong place to ask, please point me to the right place and close this question.

I have installed an instance of this jitsi-meet docker and it is not working reliably.

The Problems:

People connecting not always having audio and/or video.
Reconnecting/Changing browser sometimes helps.

Then we tried the server on jitsi.org and it worked immediately.

### Question 1:

Is jitsi.org using some different software/version?
It has a slightly different user interface.

### Question 2:

How can I test if the hardware is sufficient?
Are there some hardware recommendations?

### Question 3:

I am using Ubuntu 16.04. Is this a problem? I guess not.

### Question 4:

Are there some tipps for finding the cause of Problems?
Currently I am just typing `docker-compose logs | grep` and it is not very effective.

**Comment by SebastianKobs** [comment]
Did you set your public id in .env? Not doing this caused me a bit of trouble. See https://github.com/jitsi/docker-jitsi-meet/pull/280

**Comment by saghul** [comment]
> Is jitsi.org using some different software/version?
> It has a slightly different user interface.

Yes, it has a more up to date version. You can get it by rebuildding the images with `JITSI_RELEASE=unstable`

We are working on upgrading our stable release right now.



> How can I test if the hardware is sufficient?
> Are there some hardware recommendations?

Depends on many factors. What hardware do you have?

> I am using Ubuntu 16.04. Is this a problem? I guess not.

That should be fine.



> Are there some tipps for finding the cause of Problems?
> Currently I am just typing `docker-compose logs | grep` and it is not very effective.

That's all there is I'm afraid. You can go container by container. If there is a video lag issue, you'd checkc the jvb container for example.

**Comment by mogoh** [comment]
> Did you set your public id in .env? Not doing this caused me a bit of trouble. See #280

I think this is not my problem.
I am not behind a NAT.
But thanks for the tip.

> Yes, it has a more up to date version. You can get it by rebuildding the images with `JITSI_RELEASE=unstable`

I'll try that, thanks :D

> We are working on upgrading our stable release right now.

Good to hear! :+1: 

> Depends on many factors. What hardware do you have?

```
$ lshw -sanitize -short -class cpu -class memory

H/W path             Device       Class      Description
========================================================
/0/1                              processor  Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz
/0/e2/0                           memory     512MiB DIMM DRAM EDO
...
```

(It's a VM)
I know, it is not much, but it is more a test.
If jitsi works, we might mirgrate to a bigger machine.
But I don't think that hardware is the main problem.


Thanks again, for the help!

**Comment by hmharshit** [comment]
Hi @saghul 

This is the hardware configuration of the instance on which I'm running my docker server
```
$ lshw -sanitize -short -class cpu -class memory
H/W path      Device           Class      Description
=====================================================
/0/0                           memory     96KiB BIOS
/0/401                         processor  Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
/0/402                         processor  Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
/0/403                         processor  Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
/0/404                         processor  Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
/0/1000                        memory     8GiB System Memory
/0/1000/0                      memory     8GiB DIMM RAM
```

But when I try to load the homepage or any room, it takes a significant amount of time to load the full page compared to [http://meet.jit.si/](http://meet.jit.si/).

The above instance is not running any other service apart from the docker-jitsi-meet.

What can be the actual reason?

**Comment by saghul** [comment]
Can you check the network tab in your bworser's Developer Tools to see if there is an asset that takes too long to load?

**Comment by hmharshit** [comment]
Yes, so I compared network tabs of both. These are the files that are taking time above 25 seconds to load.
```
Name | Status | Type | Initiator | Size | Time
lib-jitsi-meet.min.js?v=3729 | 200 | script | (index) | 670 KB | 15.57 s
app.bundle.min.js?v=3729 | 200 | script | (index) | 2.7 MB | 24.44
```

When I compared my instance is loading these files from the server while the jitsi meet website is loading these files from web cdn.

**Comment by saghul** [comment]
Ok, good stuff, we have a place to start. The Docker setup is self-contained, it won't download assets from the CDN.

Any chance your containers use some slow storage?

**Comment by hmharshit** [comment]
I'm using the DigitalOcean for my VM. The instance is using standard 25 GB SSD by default.

**Comment by saghul** [comment]
Can you consistently reproduce this behavior?

**Comment by hmharshit** [comment]
Yes, I'm consistently facing this slow loading issue.

**Comment by saghul** [comment]
How much RAM does your server have? Any chance it's swapping?

**Comment by hmharshit** [comment]
Currently it's 8 GiB of RAM. No, it's not swapping.

**Comment by saghul** [comment]
😞  Sorry I don't know. I cannot reproduce those load times on a server on AWS or my own laptop even.

**Comment by hmharshit** [comment]
No worries @saghul. Thank you for your help and time.

I have customized the docker image by replacing the assets link to load from the CDN. This fix has drastically improved the load time. 

Thanks for your support :smile:

**Comment by saghul** [comment]
> I have customized the docker image by replacing the assets link to load from the CDN instead of my instance. This fix has drastically improved the load time.

Note that this is not a good idea. The assets on the CDN are paired with backend versions we run, which are ahead of stable, so things may break in subtle ways.

**Comment by hmharshit** [comment]
Okay. I'll definitely keep this in mind. I'll try to debug more and check if I can find a better solution than this.

**Comment by dinigo** [comment]
I'm running mine in the basic Digital a ocean too. Video is not as hd as Skype, but works out of the box

**Comment by digital-codes** [comment]
Harshit, you have very long long times. My instance is like:

> GEThttps://meet.ok-lab-karlsruhe.de/
> [HTTP/1.1 200 OK 764ms]
> GEThttps://meet.ok-lab-karlsruhe.de/css/all.css?v=3577
> [HTTP/1.1 200 OK 111ms]
> GEThttps://meet.ok-lab-karlsruhe.de/libs/do_external_connect.min.js?v=1
> [HTTP/1.1 200 OK 246ms]
> GEThttps://meet.ok-lab-karlsruhe.de/libs/lib-jitsi-meet.min.js?v=3577
> [HTTP/1.1 200 OK 772ms]
> GEThttps://meet.ok-lab-karlsruhe.de/libs/app.bundle.min.js?v=3577
> [HTTP/1.1 200 OK 1234ms]
> 

Anything wrong with you hosts network, or your local one?

**Comment by hmharshit** [comment]
Oh, there must be something wrong with my droplet. I'll see if I can re-create the droplet. I'll also check the hosts.

**Comment by mogoh** [comment]
> 512MB is way too little to run Jitsi. You need at least 4GB, though I'd recommend 8.

Ok, thanks. :)

**Comment by mogoh** [comment]
As far as I am concerned, this issue can be closed.
But other has started to use it.
So I don't know ... feel free to close if not needed any more.

**Comment by saghul** [comment]
Indeed it derailed a little. If the answer provided to the original question is ok, then let's close. Please open follow-up issues if need be.
