### ISSUE TITLE
LDAP_BINDDN is set in env but not in saslauthd.conf 

### ISSUE THREAD

**Issue by tabacha** [jitsi/docker-jitsi-meet#277]
Hi,

we have set in .env file: 
```
LDAP_URL=ldap://dcbackup.ham.company.de:7389
LDAP_BASE=cn=users,dc=company,dc=de
LDAP_BINDDN=uid=auth,cn=users,dc=company,dc=de
LDAP_BINDPW=SECRET
LDAP_FILTER=(uid=%u)
LDAP_AUTH_METHOD=bind
LDAP_USE_TLS=1
LDAP_TLS_CHECK_PEER=0
LDAP_START_TLS=0
```
But our saslauth.d looks like this:
```
root@vm-meet:/usr/src/docker-jitsi-meet# docker-compose exec prosody /bin/bash       
root@63ed533fe2da:/# cat /etc/saslauthd.conf 

ldap_servers: ldap://dcbackup.ham.copany.de:7389
ldap_search_base: cn=users,dc=company,dc=de

ldap_filter: (uid=%u)
ldap_version: 3
ldap_auth_method: bind
  
ldap_tls_key: /config/certs/meet.company.de.key
ldap_tls_cert: /config/certs/meet.company.de.crt
    
    
  


root@63ed533fe2da:/# 
```
I would expect that we can find the content of **LDAP_BINDDN**  in it.

On a fresh installed Debian Buster

**Comment by saghul** [comment]
We have landed a number of fixes on that area, the last one just minutes ago. I assume you are not running latest master because it doesn't use Buster. Please update to latest master, rebuild the images and give it a go!

**Comment by m4tze** [comment]
Using a repo that was freshly pulled, the config was unfortunately not adjusted. I also deleted the directory `~/.jitsi-meet-cfg` containing all the configs but the configs created still contained the '| toBool'. As a fix that should remain even after `docker-compose down` is to edit `~/.jitsi-meet-cfg/prosody/saslauthd.conf` and change ```{{ if .Env.LDAP_BINDDN | default "" | toBool }}``` to ```{{ if .Env.LDAP_BINDDN | default "" }}``` then down and up and everything went well.

**Comment by saghul** [comment]
That was comitted to master earlier, you need to rebuild the images for it to take effect.
