### ISSUE TITLE
Etherpad not working with latest images

### ISSUE THREAD

**Issue by SteffenDE** [jitsi/docker-jitsi-meet#281]
I just updated my containers and the Etherpad button is not showing up any more:

<img width="763" alt="Bildschirmfoto 2020-03-24 um 21 25 17" src="https://user-images.githubusercontent.com/4116351/77473672-16dadf00-6e16-11ea-9235-217ad283ce81.png">

**Comment by saghul** [comment]
Dang, that's a bug in Jitsi Meet. You can fix it by putting a full URL in `etherpad_base` in config.js.

Thanks for the report!

**Comment by mcnesium** [comment]
so I am on the latest commit [ebb4536](https://github.com/jitsi/docker-jitsi-meet/commit/ebb4536) and  in `${CONFIG}/web/config.js` I set this:

        etherpad_base: 'https://pad.mydomain.de/p/',

also the domain is set in Apache, TLS cert etc is fine, exposed the port in `etherpad.yml` and the pad itself is reachable in the browser via that domain. so it should work from that side.

then in `.env` I set this:

    ETHERPAD_URL_BASE=https://pad.mydomain.de:443

and restarted the entire docker stack using 

    docker-compose -f docker-compose.yml -f etherpad.yml down --remove-orphans
    docker-compose -f docker-compose.yml -f etherpad.yml up -d

still, no *Open Shared Document* entry in the three-dots-menu :(

**Comment by SteffenDE** [comment]
@mcnesium this should also work fine if you leave ETHERPAD_URL_BASE at its default value. With your current config nginx will proxy to your apache instead of using the shorter path inside the docker network.

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/docker-jitsi-meet/commit/5e6faced4ff7724b65d608f6fe93fabe70743efd you can rebuild the containers and it should be working. See https://github.com/jitsi/docker-jitsi-meet/issues/311 a new release is coming up on monday.

**Comment by madmath03** [comment]
@saghul Shouldn't we prefix `etherpad_base` with `ETHERPAD_URL_BASE` rather than `PUBLIC_URL`.

In this repo, ETHERPAD_URL_BASE points to the container in the docker network (`http://etherpad.meet.jitsi:9001`), while `PUBLIC_URL` is the public.

With the fix applied using `PUBLIC_URL`, the nginx will proxy to the public url instead of going the shorter way through the docker network (quoting @SteffenDE), or even preventing use of an external / independant from Jitsi Etherpad instance.

**Comment by saghul** [comment]
Incorrect. etherpad_base is what the client browser will open. ETHERPAD_URL_BASE is what etherpad_base will proxy to.

**Comment by madmath03** [comment]
> Incorrect. etherpad_base is what the client browser will open. ETHERPAD_URL_BASE is what etherpad_base will proxy to.

Okay, I misunderstood that. My bad.

**Comment by saghul** [comment]
No worries! Note that the bug is really in Jitsi Meet. It should Just Work with a relative path, but yours truly broke it by mistake. This is a simpler fix for the interim.
