### ISSUE TITLE
Jitsi randomly timeouts of all clients. 

### ISSUE THREAD

**Issue by J3n50m4t** [jitsi/docker-jitsi-meet#283]
Hi together, 
I'm trying to set up a jitsi server behind Traefik. A Tomcat creates JWT token and users need the token to join a meeting.
Users then join the meetings and can meet up.
After a few minutes, it isn't possible to create another meeting. (Meeting 1 is still in progress).
The Jitsi domain delivers a gateway timeout to the accessing browser. 
If you retry often enough, you may get access to your meeting, but then meeting 1 crashes. 

I've created a gist with all configs and logs. The crash happened at 10:21:10 - you will see a timeout in jitsi-weblogs. 
https://gist.github.com/J3n50m4t/b0e3706ed8f20c4688cdbc97089414e5 

I have no idea where to start, as it works perfectly.

Side note: No matter if 2 participants or 10 - meetings crash randomly. 
The server load is around 20 - 30 % avg. 60% max

**Comment by J3n50m4t** [comment]
Nailing Images to 4101 fixed it for me. Latest and 4101-1 are broken over here.
Not closing because this is a real issue for new setups.

**Comment by saghul** [comment]
I can't see why the backend would timeout, there is nothing in the logs, alas.

**Comment by saghul** [comment]
We did change Prosody to use epoll instead of selet and a newer version of it has fixes. I hope to release a -2 today, hopefully that does it.

**Comment by saghul** [comment]
Can you test 4101-2 images? They contain a more updated Prosody, which I think was the culprit here.

**Comment by J3n50m4t** [comment]
> I can't see why the backend would timeout, there is nothing in the logs, alas.

Had the same problem. I will test 4101-2 on another server. I can't touch the running system, as I heavily modified it and need it to be stable. 

I will reply here in a few days.

**Comment by J3n50m4t** [comment]
Sorry - it took some time.
I've tested the -2 tag and it works fine so far with the same config.
