### ISSUE TITLE
Suggestion: advise mac/pc users to set DOCKER_HOST_ADDRESS to host.docker.internal 

### ISSUE THREAD

**Issue by jonascript** [jitsi/docker-jitsi-meet#293]
For windows & mac docker instances you can use "host.docker.internal" which makes it easier to setup.  

Perhaps suggesting this in the documentation might save configuration headaches and come in handy for people needing to spin up ad hoc instances from their machines.

DOCKER_HOST_ADDRESS=host.docker.internal 

https://docs.docker.com/docker-for-windows/networking/#use-cases-and-workarounds
https://docs.docker.com/docker-for-mac/networking/#use-cases-and-workarounds

**Comment by saghul** [comment]
I don’t think that would work because I think we expect an IP there. We’d need to resolve it.

The option is ill named and I plan on renaming it and better documenting it once we make the next stable release.

**Comment by almereyda** [comment]
Indeed a better naming can help here. It could be called something like `STUN_FALLBACK_IP`, `PUBLIC_IP` or similarily. In

https://github.com/jitsi/docker-jitsi-meet/blob/ae3e7e765126c8c46b3aeb229b9ce1bcfd2a048e/jvb/rootfs/defaults/jvb.conf#L92

where it's reused it's `public-address`.

**Comment by saghul** [comment]
Closing since the returned IP address is not actually the one we need for a LAN environment. It's the host side of the Docker bridge, which is not reachable by anyone else on the LAN.

Closing in favor of https://github.com/jitsi/docker-jitsi-meet/issues/1199
