### ISSUE TITLE
special room names (etherpad, http-bind, ..)

### ISSUE THREAD

**Issue by Craeckie** [jitsi/docker-jitsi-meet#295]
There are some room names, which should be prevented in the GUI:
- http-bind
- etherpad
- config.js
- interface_config.js
- external_api.js
- anything containing a dash `/`

Maybe a better approach would be to append something before the room name like
`https://meet.example.com/r/<room name>`
That would avoid all exceptions, even dashes are possible then.

**Comment by saghul** [comment]
Nobody types that by mistake. They are trying to poke the system.
