### ISSUE TITLE
Question about JVB_TCP_HARVESTER_DISABLED env variable.

### ISSUE THREAD

**Issue by Dextroz** [jitsi/docker-jitsi-meet#296]
Hi,
The environment variable `JVB_TCP_HARVESTER_DISABLED` defaults to `false`.
If I want TCP fallback, is this the setting which I need to set? Furthermore, will this setting help people with connections which are not as good?

Also, does anyone know what determines the connection quality?

Thanks.

EDIT: Please can you not refer me to the forums :P

**Comment by saghul** [comment]
The TCP harvester is not disabled, which means it’s working by default.

This won’t help people with poor connections but people behind spartan firewalls.

Note that the experience will be worse when TCP is used.
