### ISSUE TITLE
Not able to get a fresh docker installation running properly

### ISSUE THREAD

**Issue by worreby** [jitsi/docker-jitsi-meet#297]
Getting a lot of errors in all of the con this as well for a fresh docker compose installation, the .env is rudimentary changed

Single docker server (no swarm mode), accessing the docker server directly from internal network.

1. Jicofo 2020-03-25 21:25:18.138 SEVERE: [31] org.jitsi.meet.ComponentMain.log() java.net.NoRouteToHostException: No route to host (Host unreachable), host:xmpp.ksrv04.example.com, port:5347
org.xmpp.component.ComponentException: java.net.NoRouteToHostException: No route to host (Host unreachable)
2. JVB 2020-03-25 21:25:57.611 SEVERE: [19] org.jitsi.videobridge.health.Health.log() Health check failed in 0ms:
java.lang.Exception: Address discovery through STUN faile
3. Prosody container running without errors :-)
4. Web container running without errors

Is there a working .env example anywhere around?
Do someone got any further links/instructions (have been searching around)

Got similar rejoin problems as in https://community.jitsi.org/t/after-quick-install-you-have-been-disconnected-rejoin-now-2-minute-loop/25731/5 as well

Regards
Robert

**Comment by J3n50m4t** [comment]
https://github.com/jitsi/docker-jitsi-meet/blob/master/env.example

This one was working yesterday. I've tried to reproduce my problems with minimal examples.

**Comment by saghul** [comment]
Do you have a firewall in your host?

**Comment by worreby** [comment]
No firewall, single server with docker on it, accessing it directly using chrome

_Jicofo 2020-03-26 22:29:35.546 SEVERE: [38] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.doConnect().309 Failed to connect/login: The following addresses failed: 'xmpp.meet.jitsi:5222' failed because: xmpp.meet.jitsi/172.18.0.3 exception: java.net.NoRouteToHostException: No route to host (Host unreachable)
org.jivesoftware.smack.SmackException$ConnectionException: The following addresses failed: 'xmpp.meet.jitsi:5222' failed because: xmpp.meet.jitsi/172.18.0.3 exception: java.net.NoRouteToHostException: No route to host (Host unreachable)_

Using Docker version 19.03.8, build afacb8b on CentOS Linux release 8.1.1911 (Core) 

If the env example is working, it must be the networking in my docker setup that is spooking

The only thing I've changed in the .env is the following
#TZ=Europe/Amsterdam
TZ=Europe/Zurich
#PUBLIC_URL=https://meet.example.com
PUBLIC_URL=https://ksrv04.example.com
#DOCKER_HOST_ADDRESS=192.168.1.1
DOCKER_HOST_ADDRESS=192.168.101.104

Will check the docker network setup

Do somebody got some other suggestion?

**Comment by davebenvenuti** [comment]
I'm also trying to get a fresh docker installation working.  I can access the instance via localhost, but can't access it via the instance's public ip.  I'm pretty sure the problem lies in the docker iptables rules somewhere, but I haven't for the life of me been able to figure out how to directly publish ports opened by docker publicly.

**Comment by saghul** [comment]
>     2\. JVB 2020-03-25 21:25:57.611 SEVERE: [19] org.jitsi.videobridge.health.Health.log() Health check failed in 0ms:
>         java.lang.Exception: Address discovery through STUN faile

This means your server couldn't contact Google's STUN servers. That suggests firewalling.

At any rate, try this: empty this variable: https://github.com/jitsi/docker-jitsi-meet/blob/master/env.example#L185 from your .env file, remove your CONFIG directory and restart the containers.

**Comment by worreby** [comment]
Thanks for the STUN hint, 
you're right I do got I firewall, my point of view was that I did a local installation inside my network and never intended jitsi to go outside of my local network... So far for assumptions :-)
Removed it and rerun it again, same issue, I'll need debug it more thorough
Will get back when I got it so far

**Comment by saghul** [comment]
For a local install you need to disable STUN on the JVB by removing that variable and set DOCKER_HOST_ADDRESS to your machines LAN adresss. That should do.
