### ISSUE TITLE
Use existing letsencrypt certificate

### ISSUE THREAD

**Issue by rwaeselynck** [jitsi/docker-jitsi-meet#299]
Hi dear developpers and thanks a lot for your amazing work.
I installed jetsi-meet on my synology but I do not find anything about using my synology letsencrypt certificate...
Any help would be greatly appreciated.

**Comment by saghul** [comment]
We don't support that setup. If you already have a web server with a valid TLS cert, the recommendation is to just proxy via HTTP to the container port 8000. In that case tthere is no need to manage the cert in the container.

**Comment by rwaeselynck** [comment]
Thanks for you answer ; not sure to know how to achieve that with DSM, but I presume this is not a priority for you. If anybody in your team has a working setup with synology, I take the help ;)

**Comment by saghul** [comment]
I don't know if anyone has that setup, but here is what you're looking for: "reverse proxy". Your NAS must have a web server running with Let's Encrypt, you want to reverse proxy to the Docker setup's HTTP port.

**Comment by digital-codes** [comment]
I left 
#ENABLE_LETSENCRYPT=1
in .env commented out, so it doesn't create a new one. The you install an apache proxy with your (new or) existing certificate like so:
... add here your virtual host config, then inside:
		ProxyPreserveHost on
		RequestHeader set X-Forwarded-Proto "https"
		ProxyPass / http://127.0.0.1:8000/
		ProxyPassReverse / http://127.0.0.1:8000/
      
		ProxyPass /http-bind http://localhost:8000/http-bind/
		ProxyPassReverse /http-bind http://localhost:8000/http-bind/

See also https://community.jitsi.org/t/solved-looking-for-help-with-apache-reverse-proxy-for-docker-deployment/18535/21

**Comment by reesericci** [comment]
+1 I'd like to see custom SSL certificate support
