### ISSUE TITLE
ENABLE_HTTP_REDIRECT=0 does not disable HTTPS redirect

### ISSUE THREAD

**Issue by SimmyD** [jitsi/docker-jitsi-meet#30]
When creating a fresh docker instance when setting ENABLE_HTTP_REDIRECT=0 in the .env file the if else statement doesn't seem to be working in web/rootfs/defaults/default.

In my install "return 301 https://$host$request_uri;" was placed there instead of "include /config/nginx/meet.conf;"

manually changing this worked

**Comment by saghul** [comment]
Setting it to 0 should work as expected, so I'll treat this as a bug and try to find a way to make it work. As @sapkra said, you can just omit it for the time being.

**Comment by sapkra** [comment]
0 should work but I think environment variables are always strings so the go template engine detects an array of one char and this is true

**Comment by dgruss** [comment]
I've been using jitsi meet behind an https proxy for a while but this **stopped** working after updating to current master.

Tried
#ENABLE_HTTP_REDIRECT=...
ENABLE_HTTP_REDIRECT=0
ENABLE_HTTP_REDIRECT="0"
ENABLE_HTTP_REDIRECT=

None worked... always 301.

I manually edited the generated nginx.conf in the container -> then it works again... not sure what went wrong there...

**Comment by saghul** [comment]
Have you wiped the config volume after changing the env file?

**Comment by dgruss** [comment]
No. Is this documented somewhere?

**Comment by saghul** [comment]
Yes, on the README (which is now moved into the handbook): https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#configuration (see the important note)

**Comment by dgruss** [comment]
Thanks!
