### ISSUE TITLE
Starting a publicly-accessible jitsi meet stack

### ISSUE THREAD

**Issue by davebenvenuti** [jitsi/docker-jitsi-meet#309]
Some system information:

Docker version 19.03.6, build 369ce74a3c
docker-compose version 1.17.1, build unknown
Ubuntu 18.04.3 LTS

I'm having trouble starting up a publicly-accessible jitsi meet server.  I followed the instructions in the README and am able to access the web ui via localhost (eg: `wget https://localhost`).  However, the webui isn't publicly accessible.  I can't reach it from an outside host, nor can i reach it from the host by wgetting the public ip.  The issue appears to be in the docker iptables rules but I'm not sure what the correct way to address it is.  I've confirmed this by starting a different webserver and successfully reaching it via public ip.  I received some advice about putting the network_mode in `host` mode, but that would undo the necessary `network` settings required for the stack to work correctly.  I'd like to avoid using a reverse proxy if possible so that I can take advantage of jitsi's built-in letsencrypt support.

**Comment by saghul** [comment]
When enabling Let's Encrypt, did you change the ports to 80 and 443 in your `.env` file ?

**Comment by davebenvenuti** [comment]
Yes.  Again, the instance is accessible via ports 80 and 443 if i `wget localhost`, but not if i `wget [publicip]`.  I'm happy to provide any other information that might help.  I think it's pretty easily reproducable.

**Comment by saghul** [comment]
Check if the port reddirecctions are ok, and also that your firewall is off:

```
saghul@saghul-dev1:~/src/docker-jitsi-meet$ docker-compose ps
           Name               Command   State                        Ports
------------------------------------------------------------------------------------------------
docker-jitsi-meet_jicofo_1    /init     Up
docker-jitsi-meet_jvb_1       /init     Up      0.0.0.0:10000->10000/udp, 0.0.0.0:4443->4443/tcp
docker-jitsi-meet_prosody_1   /init     Up      5222/tcp, 5269/tcp, 5280/tcp, 5347/tcp
docker-jitsi-meet_web_1       /init     Up      0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp
saghul@saghul-dev1:~/src/docker-jitsi-meet$ sudo ufw status
Status: inactive
```

Also, when you changed your .env file, did you remove the CONFIG volume?

**Comment by davebenvenuti** [comment]
I did not remove the CONFIG volume.  I've been blowing away the context of the CONFIG folder every time i change the `.env` file, too.  Firewall is definitely off, I can reach a different web server running on the instance from the outside world.  I think the issue lies somewhere in the bowels of the docker iptables rules.

Here's the output of `docker-compose ps`.  Looks a lot like yours

```
dockerjitsimeet_jicofo_1    /init     Up                                                                                                                               
dockerjitsimeet_jvb_1       /init     Up      0.0.0.0:10000->10000/udp, 0.0.0.0:4443->4443/tcp                                                                         
dockerjitsimeet_prosody_1   /init     Up      5222/tcp, 5269/tcp, 5280/tcp, 5347/tcp                                                                                   
dockerjitsimeet_web_1       /init     Up      0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp 
```

**Comment by davebenvenuti** [comment]
Huh.  I have no idea what happened, but I just restarted everything and it's all of a sudden publicly accessible.  I have no idea why but I'll take it.  I'll close this for now, and reopen if it happens again
