### ISSUE TITLE
PSA: New stable release coming on monday

### ISSUE THREAD

**Issue by saghul** [jitsi/docker-jitsi-meet#311]
We have just made unstable the next RC. The master branch of this repo is ready for the upgrade, this includes JVB 2.0!

The next stable version is what has been running on meet.jit.si the past few days and we have tested it ssignificantly, it has gotten tons of use due to the current cirumstanes.

If you want to take it for a spin, you can do so by building your own images: `FORCE_REBUILD=1 JITSI_RELEASE=unstable make`

If you experience issues, please let us know!

**Comment by aksdb** [comment]
@saghul I built the images with a checkout from `master` yesterday, reset the config folder and started fresh. But whenever I connect, the browser goes into a reconnect loop.

```
Logger.js:154 2020-03-31T07:04:00.205Z [modules/xmpp/xmpp.js] <t.value>:  (TIME) Strophe disconnecting:	 2354.285000008531
Logger.js:154 2020-03-31T07:04:00.207Z [modules/xmpp/xmpp.js] <t.value>:  (TIME) Strophe disconnected:	 2355.550000007497
Logger.js:154 2020-03-31T07:04:00.207Z [modules/xmpp/xmpp.js] <t.value>:  XMPP connection dropped!
....
Logger.js:154 2020-03-31T07:04:00.212Z [features/overlay] <Object.componentDidMount>:  The conference will be reloaded after 22 seconds.
Logger.js:154 2020-03-31T07:04:00.216Z [features/base/connection] connection.droppedError
```

Serverside I see nothing suspicios in the services; only in the `web` container:
```
web_1      | 2020/03/31 09:03:46 [error] 234#234: *2 open() "/usr/share/jitsi-meet/"https:/meet.my.domain"/http-bind" failed (2: No such file or directory), client: 192.168.64.1, server: _, request: "POST /%22https://meet.my.domain%22/http-bind?room=foo HTTP/1.1", host: "meet.my.domain", referrer: "https://meet.my.domain/foo"
```

**Comment by saghul** [comment]
What is your setup? Are you proxying from another container or using the builtin web one?

**Comment by aksdb** [comment]
I have another reverse proxy in front of it (caddy with `transparent`; i.e. all headers are passed through). The same proxy definition worked before (with the "old" stable version).

**Comment by saghul** [comment]
We re-did the nginx config. I have no experience with Cadddy, so I don't know how it operates.

Are you serving the Docker setup from a subdirectory?

**Comment by aksdb** [comment]
Nope, no subdirectory. The setup in a nutshell:

```
meet.my.domain {
  proxy / 127.0.0.1:8080 {
    transparent
  }
}
```

The HTTP port of Jitsi Web is exposed on `127.0.0.1:8080`. HTTPS is handled by Caddy.

`transparent` basically sets the following headers:

```
header_upstream Host {host}
header_upstream X-Real-IP {remote}
header_upstream X-Forwarded-For {remote}
header_upstream X-Forwarded-Port {server_port}
header_upstream X-Forwarded-Proto {scheme}
```

**Comment by aksdb** [comment]
The part in the log that's weird is: `POST /%22https://meet.my.domain%22/http-bind?room=foo HTTP/1.1`

That seems like the frontend is doing a bad POST request. I'll check if I find something strange in the generated web config.

**Comment by saghul** [comment]
That's my suspiccion as well. Let us know how it goess.

**Comment by aksdb** [comment]
:man_facepalming: I had the `PUBLIC_URL` in `.env` with quotes.
That ended with the following line in `config.js`:
```
bosh: '"https://meet.my.domain"/http-bind'
```
... and therefore in the error. It seems fine now. Sorry for the trouble :-)

**Comment by skupfer** [comment]
Running docker-jitsi-meet behind a nginx reverse proxy. Etherpad doesn't work. Uncommented the line in .env and didn't touch it.

Did a `git pull` for this repository and `FORCE_REBUILD=1 make`. To start: `docker-compose -f docker-compose.yml -f etherpad.yml up -d`

Maybe it's the reverse proxy?

I get `meet.domain.tld refused t connect`

**Comment by saghul** [comment]
> 🤦‍♂ I had the `PUBLIC_URL` in `.env` with quotes.
> That ended with the following line in `config.js`:
> 
> ```
> bosh: '"https://meet.my.domain"/http-bind'
> ```
> 
> ... and therefore in the error. It seems fine now. Sorry for the trouble :-)

No worries! It used to be with quotes by mistake, to that's totally on us.

**Comment by saghul** [comment]
@skupfer Can you share your nginx error log?

**Comment by skupfer** [comment]
@saghul no errors in my log. I'll post my config. Maybe it's a problem there. Unfortunately I couldn't find proper examples so I used what I have for mattermost, confluence, jira etc. pp

ports: 8081 and 9443

Nginx config
```
server {
    listen 80;
    server_name meet.domain.tld;

    location ^~ /.well-known/acme-challenge/ {
       default_type "text/plain";
       root         /var/www/html;
    }
    location = /.well-known/acme-challenge/ {
       return 404;
    }
    location / {
       return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name meet.domain.tld;
    server_tokens off;

    access_log  /var/log/nginx/meet_access.log;
    error_log   /var/log/nginx/meet_error.log;

    include /etc/nginx/snippets/ssl-jitsi-meet.conf;
    include /etc/nginx/snippets/ssl-params.conf;

    location / {
        proxy_redirect off;
        proxy_set_header Host $http_host;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Ssl on;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_pass http://localhost:8081;
    }
}
```

ssl-params.conf
```
# from https://cipherli.st/
# and https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html

ssl on;
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_prefer_server_ciphers on;
ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:ECDHE-RSA-AES128-GCM-SHA256:AES256+EECDH:DHE-RSA-AES128-GCM-SHA256:AES256+EDH:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";
ssl_ecdh_curve secp384r1;
ssl_session_cache shared:SSL:10m;
ssl_session_tickets off;

# OCSP stapling: nginx will poll the CA for signed OCSP responses, and
# send them to clients so clients don't make their own OCSP calls.
#
# The ssl_trusted_certificate is a chain of intermediates *including* the
# root certificate, and *excluding* the cert for your domain.
#
# See https://sslmate.com/blog/post/ocsp_stapling_in_apache_and_nginx
ssl_stapling on;
ssl_stapling_verify on;
resolver 8.8.8.8 8.8.4.4 valid=86400;
resolver_timeout 10s;
# See domain conf for ssl_trusted_certificate path

# Disable preloading HSTS for now.  You can use the commented out header line that includes
# the "preload" directive if you understand the implications.
#add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
add_header Strict-Transport-Security "max-age=63072000; includeSubdomains";
add_header X-Frame-Options DENY;
add_header X-Content-Type-Options nosniff;
add_header X-XSS-Protection "1; mode=block";
add_header X-Robots-Tag none;

# Diffie-Hellman parameter for DHE ciphersuites, recommended 2048 bits
# openssl dhparam -out /etc/ssl/nginx/dhparam.pem 4096
ssl_dhparam /etc/ssl/nginx/dhparam.pem;
```

access.log right before/after calling etherpad
```
91.35.217.240 - - [31/Mar/2020:13:42:58 +0000] "POST /http-bind?room=inclinedcopyrightssuggestsuddenly HTTP/2.0" 200 4084 "https://meet.domain.tld/InclinedCopyrightsSuggestSuddenly" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"
91.35.217.240 - - [31/Mar/2020:13:43:05 +0000] "GET /etherpad/p/539e9c3ec09d47e8ba43cf4a09a3a65a?showControls=true&showChat=false&showLineNumbers=true&useMonospaceFont=false&userName=sk HTTP/2.0" 200 7777 "https://meet.domain.tld/InclinedCopyrightsSuggestSuddenly" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"
91.35.217.240 - - [31/Mar/2020:13:43:06 +0000] "POST /http-bind?room=inclinedcopyrightssuggestsuddenly HTTP/2.0" 200 298 "https://meet.domain.tld/InclinedCopyrightsSuggestSuddenly" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"
```

**Comment by foer** [comment]
I just wan't to ask if the new release with jvb2 is already released? Where can I see which version of jvb i'm using at the moment. I am on the latest stable release.

Thanks!

**Comment by saghul** [comment]
Some last moment problems arose so we are holding the release. I'm hopeful it will be done this week. It ddoes include JVB2.

As for performane, what system do you currently have?

**Comment by foer** [comment]
We have jitsi running in a kvm Ubuntu 18.04 VM with 10vCPU, 16 GB RAM and a 220MBit Internet connection. There is no problem with the system load or io but over 20 students there are a lot of lags and disconnects.

**Comment by saghul** [comment]
@foer Please open a new issue, please give the new release a try and open an issue otherwise!

**Comment by saghul** [comment]
Folks, release has been made: https://github.com/jitsi/docker-jitsi-meet/blob/master/CHANGELOG.md#stable-4384 all hail JVB2!
