### ISSUE TITLE
Persistent Etherpads

### ISSUE THREAD

**Issue by mcnesium** [jitsi/docker-jitsi-meet#326]
When the last person leaves a Jitsi session with an Etherpad opened within as "Shared Document", the next time, a Jitsi session with the same URL is opened, the originally linked Etherpad session is lost and a new one is created. Is this the default expected behaviour?

If so, let this be a feature request to have persistent Etherpad links. My assumption is that Jitsi just connects to `my.etherpad.container/p/` and thus Etherpad creates a new session. If Jitsi would in turn add a defined string to the path, Etherpad would create or re-open a pad with that name. It would propably be the easiest to just use the name of the current Jitsi session, so no extra string needs to be remembered.

**Comment by damencho** [comment]
Well as everything else there is no persistence between meetings as this is a privacy issue. You may leak important information for someone to read it ...

**Comment by mcnesium** [comment]
You're right, that sure is a problem… :thinking: 
As always, it would be best if there was an opt-in for it. But I guess without further work on the UI this is not easily to solve.

**Comment by sapkra** [comment]
@mcnesium You may be able to use this option in the config.js but I've not tested it:

```javascript
useRoomAsSharedDocumentName: true
```
