### ISSUE TITLE
How to use web custom UI

### ISSUE THREAD

**Issue by ashirwad007786** [jitsi/docker-jitsi-meet#327]
I have customized the [jits meet](https://github.com/jitsi/jitsi-meet) web and added some features according to my requirements. 

How can I add that changes to the docker web instance?

**Comment by ashirwad007786** [comment]
Will I have to refer my customized repository somewhere in the docker instance?

**Comment by trev-dev** [comment]
@ashirwad007786 I've been thinking about this, too. This would require learning enough about docker to create your own build image of your custom jitsi-web image...then use that image instead of the one provided in the current docker-compose.

**Comment by retani** [comment]
According to this article (in german, march 2020 https://www.golem.de/news/homeoffice-videokonferenzen-auf-eigenen-servern-mit-jitsi-meet-2003-147239.html) you need to delete .jitsi-meet-cfg/ when you change the variables in .env so it can recreate it on docker-compose up. So the question really is how to persist these settings, or, even better, how to control them from .env file.

**Comment by valueerrorx** [comment]
i just "mounted" my altered version of the web folder via docker-compose.yml into the docker image (to /usr/share/jitsi-meet ) and it worked.

that way i'm in full control about the visual appearance of the welcome page

`# Frontend
    web:
        image: jitsi/web
        restart: always
        ports:
            - '${HTTP_PORT}:80'
            - '${HTTPS_PORT}:443'
        volumes:
            - ${CONFIG}/web:/config
            - ${CONFIG}/web/letsencrypt:/etc/letsencrypt
            - ${CONFIG}/transcripts:/usr/share/jitsi-meet/transcripts
            - /root/DOCKER/docker-jitsi-meet/jitsi-meet-web/:/usr/share/jitsi-meet`

**Comment by njoye** [comment]
@valueerrorx 's way worked fine for me even without having jitsi-meet installed before. You can simply clone the repo, make your changes and then run `npm install` and `make`. Afterwards just add the line `- /path/to/jitsi-meet-repo/:/usr/share/jitsi-meet` under `volumes` in your `docker-compose.yml`. After rerunning `docker-compose up -d` your changes should be visible.

**Comment by wuriyanto48** [comment]
hey guys, i just use my own docker images, you may take a look

just clone jitsi-meet repo, then mount that repository into Docker image.

here's my version of Dockerfile

```
FROM nginx:latest

USER root

RUN apt-get update && apt-get -y install --reinstall build-essential \
    && apt-get -y install curl gnupg git \
    && curl -sL https://deb.nodesource.com/setup_10.x  | bash - \
    && apt-get -y install nodejs

COPY /config /config

# create site folder
RUN mkdir -p /srv

# copy site file to container site folder
COPY /jitsi-meet /srv/jitsi-meet

RUN cd srv/jitsi-meet/ \
    && npm install \
    && make

# create SSL folder
# RUN mkdir -p /etc/nginx/ssl

# copy ssl files to container ssl folder
# COPY ./ssl /etc/nginx/ssl/

EXPOSE 80
EXPOSE 443

# VOLUME ["/config", "/etc/letsencrypt", "/srv/jitsi-meet/transcripts"]

COPY /config/nginx/nginx.conf /etc/nginx/nginx.conf
```

**Comment by trev-dev** [comment]
Thanks to everyone who have shared their methods in this thread and for taking a lot of the trial and error off of the minds of people like me.

**Comment by JacBra** [comment]
Hi, wanted to share my setup:

**I added the following the meet.conf**
```
  location = / {
      rewrite ^ /static/custom/index.html;
  }
```
**I changed this in config.js**
```
  enableClosePage: true
```

**I added this to my Docker-compose.yml**
```
  - /somelocalpath/web/static/custom:/usr/share/jitsi-meet/static/custom:Z
  - /somelocalpath/web/static/close2.html:/usr/share/jitsi-meet/static/close2.html:Z
```

I created my own frontpage and put that in /static/custom/. As a result when I browse to https://MyJitsiURL I enter on my customized start page that also contains a textbox (for the room name) and a Start button. The button redirects to https://MyExternalJitsiURL/roomname which opens the meeting as original.

**In my customized close2.html I only added a redirect to https://MyExternalJitsiURL**
```
<html>
	<meta http-equiv="refresh" content="0; url=https://MyExternalJitsiURL/" />
</html>
```
so when a user closes the meeting, my customized start page is shown again.

**Comment by saghul** [comment]
Good tips shared over here :-) Until we have a better way to do this, that’s why you can do.

Closing for now.

**Comment by jliauw** [comment]
@JacBra Thanks for your solution for using a custom welcomepage with the NGINX rewrite! It works great!

**Comment by kevz93** [comment]
This thread should be in the docs ! Thank you guys for saving us some dev time!

**Comment by JacBra** [comment]
Unfortunately, my setup doesn't work anymore with the newest releases. The reason is that meet.conf is now regenerated when the docker container is restarted (not happy with that). So I am looking for a way to get this working again. I was thinking of putting a reverse proxy in front of the setup. Is that the way to go? Or is there another solution to this?

**Comment by scriptshadow** [comment]
> i just "mounted" my altered version of the web folder via docker-compose.yml into the docker image (to /usr/share/jitsi-meet ) and it worked.
> 
> that way i'm in full control about the visual appearance of the welcome page
> 
> `# Frontend
> 
> ```
> web:
>     image: jitsi/web
>     restart: always
>     ports:
>         - '${HTTP_PORT}:80'
>         - '${HTTPS_PORT}:443'
>     volumes:
>         - ${CONFIG}/web:/config
>         - ${CONFIG}/web/letsencrypt:/etc/letsencrypt
>         - ${CONFIG}/transcripts:/usr/share/jitsi-meet/transcripts
>         - /root/DOCKER/docker-jitsi-meet/jitsi-meet-web/:/usr/share/jitsi-meet`
> ```

Thank you

**Comment by gebo007** [comment]
> > i just "mounted" my altered version of the web folder via docker-compose.yml into the docker image (to /usr/share/jitsi-meet ) and it worked.
> > that way i'm in full control about the visual appearance of the welcome page
> > `# Frontend
> > ```
> > web:
> >     image: jitsi/web
> >     restart: always
> >     ports:
> >         - '${HTTP_PORT}:80'
> >         - '${HTTPS_PORT}:443'
> >     volumes:
> >         - ${CONFIG}/web:/config
> >         - ${CONFIG}/web/letsencrypt:/etc/letsencrypt
> >         - ${CONFIG}/transcripts:/usr/share/jitsi-meet/transcripts
> >         - /root/DOCKER/docker-jitsi-meet/jitsi-meet-web/:/usr/share/jitsi-meet`
> > ```
> 
> Thank you

Hello there , im quiet new to docker , where are the original web files i can start modifying , so that i can later map it through docker-compse.yml ?
