### ISSUE TITLE
How to disable "notifications" in WebUI?

### ISSUE THREAD

**Issue by mrWodoo** [jitsi/docker-jitsi-meet#328]
![image](https://user-images.githubusercontent.com/763209/77853655-802b6b00-71e5-11ea-812b-278f291ea1da.png)
How can I disable this notifications?

**Comment by saghul** [comment]
You can set this option in interface_config.js: https://github.com/jitsi/jitsi-meet/blob/ed8009883b1f65abab0c4ff758a16bafcdeb0077/interface_config.js#L202 It's on /config/, on the web container. You can edit it after it has started.

**Comment by mrWodoo** [comment]
Thanks. It works but I also want to hide every possible notification like the one in screenshot: Moderator privilages granted.

**Comment by saghul** [comment]
It'ss not possible to disable that one, sorry.

**Comment by ZedLove** [comment]
@saghul That's confusing, because the conversation from [this non-docker jitsi issue](https://github.com/jitsi/jitsi-meet/issues/5948) suggests that it _can_ be disabled us setting `DISABLE_FOCUS_INDICATOR` to `true`. @mrWodoo this may be of interest to you

**Comment by saghul** [comment]
Oops, I had forgotten about that one, you are right.
