### ISSUE TITLE
Recording and Streaming not working

### ISSUE THREAD

**Issue by mikavro** [jitsi/docker-jitsi-meet#331]
Hello !

I try to make a recording or a video streaming to youtube but a gray box down left of the screen appears say Recording.. but in next second a lady say recording stop and an orange (i dont like orange boxes :P ) appears say Recording failed to start .
I check ALL the logs jvb,jibri and nothing :/

Can you help me please i blow my mind 3 days now :/
Thank you in advance :) !

**Comment by mikavro** [comment]
i forgot to paste log from jibri sorry ...

[log.4.txt](https://github.com/jitsi/docker-jitsi-meet/files/4401626/log.4.txt)

**Comment by sapkra** [comment]
I think this is the same problem regarding the not accessible localStorage: https://github.com/jitsi/docker-jitsi-meet/issues/240

**Comment by saghul** [comment]
Pleasse see #240

**Comment by mikavro** [comment]
Thanks alot guys :) !
