### ISSUE TITLE
Jigasi SIP connection registers with wrong IP address

### ISSUE THREAD

**Issue by albe** [jitsi/docker-jitsi-meet#335]
The registration to a SIP gateway ends up registering with the wrong IP address (of the docker container):

![image](https://user-images.githubusercontent.com/4259532/77932024-3908ad00-72ad-11ea-814a-c3de1f057098.png)

I tried to find any option or code where this registration will send the IP, but I couldn't get to find the right place.
From what I can see, the register request is built at https://github.com/jitsi/jitsi/blob/848ef195b2481c67d4766c6efebb9132570acb07/src/net/java/sip/communicator/impl/protocol/sip/SipRegistrarConnection.java#L268 but the `getAddressOfRecord()` is the `useraccount@sipgateway` address. So I'm unsure where this IP is coming from. Probably from the transport level headers?

It seems to have no direct effect on the functionality though.

**Comment by saghul** [comment]
This is not a bug. Servers are supposed to implement SIP "rport", so that address is irrelevant.
