### ISSUE TITLE
Automatic restart after boot does not work

### ISSUE THREAD

**Issue by tvld** [jitsi/docker-jitsi-meet#34]
Even though all four containers have ``restart: always`` marked, the containers do **not** restart automatically after a reboot...  What could this be?
Now I have to run after each reboot of the server:
```
cd ~/<myprojects>/jitsi
docker-comnpose up -d --force-recreate
docker stats
```

**Comment by saghul** [comment]
To be honest I have no idea. That's a Docker thing really... they should just come up 🤷‍♂️

**Comment by tvld** [comment]
Yeah.. also no idea... but since latest docker update it started to work again... closed ;-)
