### ISSUE TITLE
Let's Encrypt certificate ignored when configured afterward

### ISSUE THREAD

**Issue by pini-gh** [jitsi/docker-jitsi-meet#347]
Hi,
I've had troubles making the Let's Encrypt configuration to work. This is because I first gave a try without enabling it, then enabled it afterward.
The Let's encrypt certificate was successfully created, but the nginx ssl configuration was not updated and still pointed to the self-signed certificate into /config/keys.
It would save time if this configuration could be automatically updated after enabling Let's Encrypt.
Thanks.

**Comment by saghul** [comment]
Please check the README. Any change to the env file must be followed by a wipe of the CONFIG volume or the config files won’t be created properly.
