### ISSUE TITLE
Open Shared Document button not visible/ etherpad integration not working / broken

### ISSUE THREAD

**Issue by tele-tom** [jitsi/docker-jitsi-meet#350]
I get those javascript errors during page load:

[JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  TypeError: Failed to construct 'URL': Invalid base URL

[modules/xmpp/ChatRoom.js] <t.value>:  Error processing:etherpad node. TypeError: Failed to construct 'URL': Invalid base URL

[modules/xmpp/ChatRoom.js] <t.value>:  Error processing:etherpad node. TypeError: Failed to construct 'URL': Invalid base URL

Etherpad works when opened via https: //meet.mydomain.tld/etherpad
Couldn't find a solution.

Access is behind Apache reverse proxy with SSL-Termination and plain http to port 8000 of the jistsi web container. (with https disbled setting in .env)
When using port 8443 with https enabled it's not working either.

Apache 2.4 vhost setup for this site:
```
<VirtualHost *:443>
        ServerName meet.mydomain.tld
        SSLEngine on
        SSLProxyEngine on
        SSLProxyCheckPeerCN off
        SSLProxyCheckPeerName off
        SSLProxyCheckPeerExpire off
        SSLCertificateFile /etc/univention/letsencrypt/signed_chain.crt
        SSLCertificateKeyFile /etc/univention/letsencrypt/domain.key
        SSLCACertificateFile /etc/univention/ssl/ucsCA/CAcert.pem
        ### To enable special log format for HTTPS-access
        LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\" %p" combinedssl
        CustomLog /var/log/apache2/jitsi_ssl.log combinedssl
        ## with port number
        ProxyPass / http://127.0.0.1:8000/ retry=0
        ProxyPassReverse / http://127.0.0.1:8000/
</VirtualHost>
```
Changed .env settings:
```
# Public URL for the web service
PUBLIC_URL=https://meet.mydomain.tld

# IP address of the Docker host
# See the "Running behind NAT or on a LAN environment" section in the README
DOCKER_HOST_ADDRESS=192.168.8.3

#
# Etherpad integration (for document sharing)
#

# Set etherpad-lite URL (uncomment to enable)
ETHERPAD_URL_BASE=http://etherpad.meet.jitsi:9001

(...)

# Disable HTTPS: handle TLS connections outside of this setup
DISABLE_HTTPS=1
```

**Comment by retani** [comment]
duplicate https://github.com/jitsi/docker-jitsi-meet/issues/305
