### ISSUE TITLE
Use >2048 bits as key length for (self-signed/LE) certificates

### ISSUE THREAD

**Issue by heylix** [jitsi/docker-jitsi-meet#352]
Am I right to assume that these self-signed certificates' keys only have a length of 2048 bit by default?

https://github.com/jitsi/docker-jitsi-meet/blob/fabfb2a676175894510f78ec8de5d10ae8c10e8c/web/rootfs/etc/cont-init.d/10-config#L47

I'm not sure if that's the only place where there are still 2048 bit keys as the generated Letsencrypt cert from our docker-compose setup has a key length of 2048 as well.

This should probably be 4096 bits. Maybe someone else can find other places in jitsi's code with searching for `openssl req` or `certbot`. I found another line here, for example:

https://github.com/jitsi/docker-jitsi-meet/blob/fabfb2a676175894510f78ec8de5d10ae8c10e8c/web/rootfs/etc/cont-init.d/10-config#L14

Maybe also related: https://github.com/certbot/certbot/issues/2080

meet.jit.si also only uses 2048 bit by default; maybe this is intentional? In other places jitsi uses 4096 as far as I can see:

https://github.com/jitsi/jitsi-meet/blob/cb0cea4ebd504e61faa423a6747e0c5192705ad0/debian/jitsi-meet-web-config.postinst#L94

**Comment by saghul** [comment]
We are not specifying 2048 anywhere AFAICT. We are using the certbot default, and in casse of the self-signed one, I'd argue it ddoesn't even matter since it's for testing only.

If there is a parameter for certbot, happy to have it. Please send a PR!
