### ISSUE TITLE
base URLs as FQDN in config.js (etherpad, bosh) need use of CORS now?

### ISSUE THREAD

**Issue by tele-tom** [jitsi/docker-jitsi-meet#355]
With etherpad base-URL set to FQDN what this fix seems to be for:
 [(https://github.com/jitsi/docker-jitsi-meet/commit/5e6faced4ff7724b65d608f6fe93fabe70743efd)](https://github.com/jitsi/docker-jitsi-meet/commit/5e6faced4ff7724b65d608f6fe93fabe70743efd)

we have this problem now:

[JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>: UnhandledError: Uncaught SecurityError: Blocked a frame with origin "https://meet.mydomain.tld" from accessing a cross-origin frame. Script: https://meet.mydomain.tld/libs/app.bundle.min.js?v=3729 Line: 152 Column: 126770 StackTrace: DOMException: Blocked a frame with origin "https://meet.mydomain.tld" from accessing a cross-origin frame.
at c (https://meet.mydomain.tld/libs/app.bundle.min.js?v=3729:152:126770)
at HTMLIFrameElement.t.onload (https://meet.mydomain.tld/libs/app.bundle.min.js?v=3729:152:127408)

**Comment by tele-tom** [comment]
Some extra Information when using Firefox:

Websites prove their identity via certificates. Firefox does not trust this site because it uses a certificate that is not valid for meet.mydomain.tld. The certificate is only valid for the following names: *.evanzo-server.de, evanzo-server.de
 
Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by tele-tom** [comment]
I don't get that. When I call https://meet.mydomain.tld/etherpad/p/... the browser gets the correct certificate from my public domain.

**Comment by tele-tom** [comment]
Don't know what happened in the meanwhile, but now it works that way...

**Comment by saghul** [comment]
I am able to reproduce the CORS problem when using the iframe API, but I cannot understand why, since the origin is the same.

**Comment by tele-tom** [comment]
Could it be same-site-cookies policy? 
Google did a rollback to former behavior. This would explain why it worked after a while for my setup

**Comment by tele-tom** [comment]
I think this one can be closed.
