### ISSUE TITLE
Is OCTO not supported yet in this version of docker?

### ISSUE THREAD

**Issue by creativeguitar** [jitsi/docker-jitsi-meet#356]
When  I enable Octo in jicofo/rootfs/defaults/sip-communicator.properties 
`org.jitsi.jicofo.BridgeSelector.BRIDGE_SELECTION_STRATEGY=RegionBasedBridgeSelectionStrategy`
`#org.jitsi.jicofo.BridgeSelector.BRIDGE_SELECTION_STRATEGY=SplitBridgeSelectionStrategy`

i get the following error for either option that I enable

jicofo_1   | Jicofo 2020-04-01 09:37:09.864 SEVERE: [11] **org.jitsi.jicofo.bridge.BridgeSelector.log() Failed to find class for: RegionBasedBridgeSelectionStrategy**
jicofo_1   | Jicofo 2020-04-01 09:37:09.865 INFO: [11] org.jitsi.jicofo.bridge.BridgeSelector.log() Using org.jitsi.jicofo.bridge.SingleBridgeSelectionStrategy
jicofo_1   | Jicofo 2020-04-01 09:37:09.865 INFO: [11] org.jitsi.jicofo.bridge.BridgeSelector.log() Bridge failure reset threshold: 300000
jicofo_1   | Jicofo 2020-04-01 09:37:09.865 INFO: [11] org.jitsi.jicofo.bridge.BridgeSelector.log() Local region: null

**Comment by netaskd** [comment]
Please check PR #130
