### ISSUE TITLE
Use own SSL certificate

### ISSUE THREAD

**Issue by TeGuy** [jitsi/docker-jitsi-meet#359]
Hi, 

I can't use Let's Encrypt - but I do have a valid SSL certificate on my own.

There's no such information on how to provide it in the README....

**Comment by saghul** [comment]
It's not supported in our setup. We recommend you setup a web web container were you place your own certs and proxy-pass to the HTTP port of this setup.

**Comment by TeGuy** [comment]
Ah, ok. You may add this hint to your README for others. Thank you for the very fast response!

(I thought about this earlier and only understood that port 80 is for ssl-redirect ONLY, so I didn't test it)

**Comment by inreh** [comment]
@saghul Hi! Sorry for reopen this post, but i have a problem using your setup, i have installed a reverse proxy to redirect to port 80 of the docker, but it does not work with more than 2 connections, that is, it only works with the let's encrypt certificate. Is there any way to fix it?

Thnx!

**Comment by helloncanella** [comment]
@inreh did you find a workaround to this. I'm facing exactly the same problem.
