### ISSUE TITLE
can i use the nginx to proxy the udp port 10000 for jvb if the machine does not have a public ip?

### ISSUE THREAD

**Issue by ryanli870929** [jitsi/docker-jitsi-meet#364]
hi, i am a new user for jitsi meet.i have installed the jitsi-meet by docker in a server machine which  did not have a publice address.
Now, i want to add a nginx proxy for  the https request. At the same time  i have noticed that nginx can support the UDP proxy,  so can i use the nginx to proxy the UDP port 10000 for JVB?

**Comment by topelrapha** [comment]
Yes it is possible.

You have to set the DOCKER_HOST_ADDRESS .env to your nginx public IP Adress and configure the stream in nginx.
