### ISSUE TITLE
Why no videobridge2 container / new release tag?

### ISSUE THREAD

**Issue by ralfbecker** [jitsi/docker-jitsi-meet#369]
Is there any reason you did not create a new release / container with videobridge2?

The commits (jvb/Dockerfile) seem all in place.

Kind regards

Ralf

**Comment by sapkra** [comment]
https://github.com/jitsi/docker-jitsi-meet/issues/311#issuecomment-607488695

**Comment by ralfbecker** [comment]
Thanks, it's sometimes hard in a project you don't know, to find the information already there.

Ralf
