### ISSUE TITLE
You need to remove the CONFIG directory every time you modify the .env file. https://github.com/jitsi/docker-jitsi-meet#configuration

### ISSUE THREAD

**Issue by balmmva** [jitsi/docker-jitsi-meet#371]
Hi

 where is the "config directory" that must be cleaned when .env file is modified ?

thx

"You need to remove the CONFIG directory every time you mnodify the .env file. https://github.com/jitsi/docker-jitsi-meet#configuration

_Originally posted by @saghul in https://github.com/jitsi/docker-jitsi-meet/issues/92#issuecomment-483547414_"

**Comment by werthd** [comment]
look in your .env file. The path is at the top. But remember to run 
`mkdir -p ~/.jitsi-meet-cfg/{web/letsencrypt,transcripts,prosody,jicofo,jvb}`
agin.

**Comment by balmmva** [comment]
thank you
