### ISSUE TITLE
Set Docker restart policy

### ISSUE THREAD

**Issue by dbrgn** [jitsi/docker-jitsi-meet#376]
Would it make sense to add a [restart policy](https://docs.docker.com/compose/compose-file/#restart_policy) to the docker-compose file, so that the containers are automatically restarted if they fail (and on system start)?

For example, something like this:

      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 6

**Comment by robvella** [comment]
Agree with this. I manually did docker update --restart=always on every container in the mean time.

**Comment by sapkra** [comment]
See #377

**Comment by saghul** [comment]
Let’s continue in 377
