### ISSUE TITLE
Suddenly 2nd participant gives "reconnecting" on first and second screen

### ISSUE THREAD

**Issue by tvld** [jitsi/docker-jitsi-meet#38]
![screenshot from 2018-12-04 20-52-23](https://user-images.githubusercontent.com/986182/49471416-22fbf100-f80d-11e8-855b-f703e03aaab9.png)

Jitsi have been working ok for some months, but after last Friday ``docker-compose up -d --force-recreate``:
- first participant shows working setup and own webcam image
- as soon as 2nd participant arrives, **both** screens get grey (or red screen on Android) and a reconnecting timer shows.

I just cloned latest repo, but no result...

**Comment by tvld** [comment]
Got it working. After tip from @saghul  in https://github.com/jitsi/docker-jitsi-meet/issues/15  I removed folder ``rm -rf ~/.jitsi-meet-cfg``  it worked as it took over my ``.env`` changes: ``DISABLE_HTTPS=1``  (I am running on nginx proxy and now forward to http instead of https. Dont know if that was main cause, just guessing for now)

**Comment by tvld** [comment]
> I'll look into lifting this limitation.

Excellent. 

When you are at it, maybe also think for a moment about the .gitignore for ``.env``?  As for us, there's nothing that needs to be kept secure in that file. 

_Idea_ 
Maybe replace ``.env`` with two files: 

- an optional file ``secure.env`` which is in .gitignore: this file would overwrite duplicate settings in:
-  ``config.env``, copy of the current ``.env`` file

This approach would remove the need to keep the ``.env`` and ``example.env`` files.  Which is appreciated as ``.env`` file put me off track when first installing: I never saw the hidden ``.env`` in the Linux folder...

**Comment by saghul** [comment]
Well, that would mean the command people need to type to run this is longer, for not a good reason. The choice for `.env` is not arbitrary, is what Docker Compose picks up by default.

There are certainly things you want to be secret, such as the SIP password for Jigasi.

**Comment by tvld** [comment]
Sounds logical.. so I like to retract my last thoughts ;)))) Sorry ))

**Comment by saghul** [comment]
No worries!
