### ISSUE TITLE
defining different ports for jitsi-meet

### ISSUE THREAD

**Issue by hakova** [jitsi/docker-jitsi-meet#380]
Dear all,

I am sorry to take your time/space for this personal and novice question. I have a web-based database set up on my physical server that runs both apache and postgresql containers. I would like to install a jitsi-meet container on the same server. However, I am kind of lost how to make this happen without messing up the running database/containers, which currently use port #80. I guess my questions are:
1. Is it possible to set up jitsi-meet container(s) to use ports other than 80 and 443 on the host machine? 
2. If so, is there a guide/documentation/tutorial about this?

Thank you for your replies in advance.

**Comment by axilleas** [comment]
:wave: have you read the configuration section https://github.com/jitsi/docker-jitsi-meet#configuration? By default the ports are `8000` and `8443` for HTTP and HTTPS respectively.

**Comment by hakova** [comment]
I am sorry for my oversight. I was able to get this work yesterday with a little bit effort. I wanted to express my gratitude to all developers for developing and making this amazing software available as a docker container. Thank you!
