### ISSUE TITLE
Missing bak file

### ISSUE THREAD

**Issue by ColinFay** [jitsi/docker-jitsi-meet#384]
The README advices to run `./gen-password.sh`. 

This script does a sed of ".bak", which is missing from the cloned repo: 

```
~/docker-jitsi-meet# bash ./gen-passwords.sh
sed: can't read .bak: No such file or directory
```

**Comment by ColinFay** [comment]
at https://github.com/jitsi/docker-jitsi-meet/blob/master/gen-passwords.sh#L14

**Comment by saghul** [comment]
Fixedd in https://github.com/jitsi/docker-jitsi-meet/commit/12595119d6a0cfe5f8b351c088f02060aebd2842 please pull and try again.
