### ISSUE TITLE
Display error message instead of login dialog when no jwt provided

### ISSUE THREAD

**Issue by rayhaanq** [jitsi/docker-jitsi-meet#389]
Is there any way to display an error message instead of a login dialog when jwt validation fails? I get a login dialog when I don't provide a jwt token. Shouldn't this show the same authentication error message as when an invalid jwt token is provided?

I have jwt configured as well as ENABLE_GUESTS=0 and JWT_ALLOW_EMPTY=0.

Is this what's supposed to happen?

**Comment by saghul** [comment]
Yes, that is normal. Jitsi itself doesn't know about the auth mechaism being used.
