### ISSUE TITLE
Regenerate config on every container boot

### ISSUE THREAD

**Issue by saghul** [jitsi/docker-jitsi-meet#39]
People are confused by the need to remove the config directory. Very rightfully so. The config should be regerated on every boot, based on the given env variables.

Potential trouble ahead:

- Prosody users
- Lets Encrypt config

**Comment by drexlerux** [comment]
I have the same problem, I could not enable https to the server domain

**Comment by sapkra** [comment]
I've just removed the `/config` volume mount - after that the containers are generating the config on every boot.

**Comment by roeycohen** [comment]
@sapkra can you elaborate? i'm a rookie when it comes to dockers...

**Comment by sapkra** [comment]
There is an open PR.

**Comment by roeycohen** [comment]
still, can you explain how you removed the "/config volume mount" so me and others can get more educated? :)

**Comment by sapkra** [comment]
Sorry, I thought it is another ticket - I removed my comment which made no sense.

Just remove all lines they are similar to this one. This line mounts a local path in the container so that all settings are saved on your host instead of in the container itself.
https://github.com/jitsi/docker-jitsi-meet/blob/master/docker-compose.yml#L38

**Comment by roeycohen** [comment]
ok, finally got it, it's the directly created on the host:
default: /root/.jitsi-meet-cfg/
10x!

**Comment by HichamBali** [comment]
Microphone/Camera does not function throw the internet, i set my in the public_url my public ip and in the docker_host_ip the private ip of my machine in the LAN. Any help please

**Comment by satoshinotdead** [comment]
This can be causing the local changes are overwritten on every docker run (from docker-compose)?

I'm looking the way to make the manually config.js changes permanent.

**Comment by damencho** [comment]
Use custom-config.js 
https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#jitsi-meet-configuration

**Comment by saghul** [comment]
Forgot to close this, we have been doing it for a while already.
