### ISSUE TITLE
Cannot start docker

### ISSUE THREAD

**Issue by nephilim75** [jitsi/docker-jitsi-meet#392]
Hi,

followed the instructions to install Jitsi using Docker-Compose. I tried on Ubuntu 18.04 and ran into error:

```
root@ubuntu-32gb-nbg1-1:~/docker-jitsi-meet# docker-compose up -d
ERROR: Couldn't connect to Docker daemon. You might need to install Docker:

https://docs.docker.com/engine/installation/ubuntulinux/
root@ubuntu-32gb-nbg1-1:~/docker-jitsi-meet#
```

Correct me if I am wrong, but I thought it should be able to run now. Checked version:
```
root@ubuntu-32gb-nbg1-1:~/docker-jitsi-meet# docker-compose -v
docker-compose version 1.17.1, build unknown
root@ubuntu-32gb-nbg1-1:~/docker-jitsi-meet#
```

How can I fix this?

Kind regards
/neph

**Comment by ToniSoftware** [comment]
Hey neph,

this rather looks like you don't have docker installed than not having docker-compose installed
I know, stupid question, but could you check for that?

Regards
Toni

**Comment by mertmr** [comment]
Maybe you installed docker but forgot to start the service?

`sudo service docker start
`

**Comment by clpacheco90** [comment]
try this:
```sh
sudo usermod -aG docker $(whoami)
newgrp docker
```

**Comment by nephilim75** [comment]
Well, I was just stupid and thought Docker was already installed. But it wasn't. It started properly well after Docker was installed.

I am sorry.

Kind regards
//neph
