### ISSUE TITLE
Jigasi interoperability problems with FreeSWITCH

### ISSUE THREAD

**Issue by ginkel** [jitsi/docker-jitsi-meet#393]
In order to be able to interface Jigasi with FreeSWITCH for dial-in, setting the option 

```
net.java.sip.communicator.impl.protocol.sip.SKIP_REINVITE_ON_FOCUS_CHANGE_PROP=true
```

is required in order to get dial-in working (cf. https://community.jitsi.org/t/recently-updated-jigasi-and-jvb-jitsi-meet-incoming-calls-no-longer-get-answered/21182/24).

This is currently not possible with this Docker image.

It would be great if you could add support for this config switch.

**Comment by saghul** [comment]
Should be fixed in the new release: stable-4416

**Comment by ginkel** [comment]
ACK, stable-4416 works like a charm w/o supplying the config option. Thank you!
