### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by dmytroshokha** [jitsi/docker-jitsi-meet#397]
Hi, i have done steps to quickly run Jitsi Meet but firstly not all services were launched the first time, and now i have an error - 400 Bad Request The plain HTTP request was sent to HTTPS port. But I did not change the ports.
Docker web logs:
`
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.

[s6-init] ensuring user provided files have correct perms...exited 0.

[fix-attrs.d] applying ownership & permissions fixes...

[fix-attrs.d] done.

[cont-init.d] executing container initialization scripts...

[cont-init.d] 01-set-timezone: executing...

[cont-init.d] 01-set-timezone: exited 0.

[cont-init.d] 10-config: executing...

using keys found in /config/keys

[cont-init.d] 10-config: exited 0.

[cont-init.d] done.

[services.d] starting services

[services.d] done.

172.21.0.1 - - [07/Apr/2020:16:33:59 +0300] "GET / HTTP/1.1" 400 685 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"

172.21.0.1 - - [07/Apr/2020:16:33:59 +0300] "GET /favicon.ico HTTP/1.1" 400 685 "http://localhost:8443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"

172.21.0.1 - - [07/Apr/2020:16:34:28 +0300] "GET /favicon.ico HTTP/1.1" 400 685 "http://localhost:8443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"

172.21.0.1 - - [07/Apr/2020:16:35:05 +0300] "GET /favicon.ico HTTP/1.1" 400 685 "http://localhost:8443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"

172.21.0.1 - - [07/Apr/2020:16:36:37 +0300] "GET /favicon.ico HTTP/1.1" 400 685 "http://localhost:8443/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36"

172.21.0.1 - - [07/Apr/2020:16:37:47 +0300] "GET / HTTP/1.1" 400 283 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0"

172.21.0.1 - - [07/Apr/2020:16:37:47 +0300] "GET /favicon.ico HTTP/1.1" 400 283 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:75.0) Gecko/20100101 Firefox/75.0"
`

**Comment by saghul** [comment]
Port 8443 is HTTPS, you sshould use https://localhost:8443
