### ISSUE TITLE
Even after enabling letsencrypt still it shows https  insecure 

### ISSUE THREAD

**Issue by sbganesh** [jitsi/docker-jitsi-meet#399]
Hi, Even after enabling ENABLE_LETSENCRYPT to '1' and setting the domain name and mail id. I'm still getting https insecure. I have set up the docker in the DigitalOcean droplet.

Kindly let me know how to fix this issue?

**Comment by akramer-zibra** [comment]
Same issue here. Installed it on plain docker machine with docker-compose. Still debugging...

**Comment by akramer-zibra** [comment]
Letsencrypt keys are created by certbot within the [10-config](https://github.com/jitsi/docker-jitsi-meet/blob/fabfb2a676175894510f78ec8de5d10ae8c10e8c/web/rootfs/etc/cont-init.d/10-config#L10) script. Seems correct. But anyhow nginx does not load the correct keys from `/etc/letsencrypt/live/...`?

**Comment by saghul** [comment]
That may happen if you started the containers earlier. The config templates are filled one on the first boot.

**Comment by sbganesh** [comment]
The issue is resolved. Let me explain the steps I have taken.
docker-compose down
docker system prune -a

\rm -r ~/.jitsi-meet-cfg/
 mkdir -p ~/.jitsi-meet-cfg/{web/letsencrypt,transcripts,prosody,jicofo,jvb,jigasi,jibri}

docker-compose up -d

Apparently it seems, the local config which was created before enabling the Letsencrypt was used in creating the docker container. so I removed the local config and recreated the docker. It works fine.
