### ISSUE TITLE
Special configuration required for mobile clients?

### ISSUE THREAD

**Issue by ztl8702** [jitsi/docker-jitsi-meet#4]
## Question
Are there anything special that needs to be configured for a Jitsi Meet instance deployed with Docker to be able to serve Jisit Meet mobile (React Native) clients?

## Details

I deployed an instance of Jitsi Meet using the Docker setup in this repo. 

My only modifications are:
 - I generated an SSL certificate with Letsencrypt and replaced the default ones in `config/meet/ssl`
 - In `nginx/site-confs/default` I added alias rules for `external_api.js`
 - I expose the `web` container at port `80` and `443` instead of `8000` and `8443`. In other words I am not using another nginx server to do SSL termination. Rather I use the nginx server inside `jitsi/web` directly with a Letsencrypt certificate.

The instance works well when accessed from browsers, and with the jisit-meet-electron client. However, on the mobile (React Native) client, when I try to join a conference on my custom instance, the indicator keeps "spinning":

<img src="https://user-images.githubusercontent.com/2714446/43679591-c231eb92-986a-11e8-8aaa-d40092559f7c.png" width="200"/>

And after a while, it failed with the "you are disconnect screen":

<img src="https://user-images.githubusercontent.com/2714446/43679595-c7fc49d2-986a-11e8-82de-39515faec14c.png" width="200"/>

### Attempts to debug 1: Android simulator

Then, in order to debug this, I built the mobile client from source, launched it in the Android emulator and attached the React Native debugger.

When I tried joining a conference on my Jisit Meet instance, the mobile app produced 2 errors in the format of this:

```
[modules\xmpp\strophe.util.js] <Object.i.Strophe.log>:  Strophe: request id 66.4 error 0 happened
``` 

<img src="https://user-images.githubusercontent.com/2714446/43679674-4db202a0-986c-11e8-8edf-4570570cb5f9.png"/>

<img src="https://user-images.githubusercontent.com/2714446/43679550-12d61a92-986a-11e8-8b54-0c1b467c4aa0.png" width="200"/>

After which the room-joining attempt failed with the "you are disconnected" screen (same as on a physical device).

<img src="https://user-images.githubusercontent.com/2714446/43679575-5ded3bdc-986a-11e8-92a6-89de660f37d6.png" width="200"/>

### Attempts to debug 2: server logs

On the server I watched the nginx access logs with `docker-compose logs -f web`:

When the mobile client attempts to join a conference, there is only one HTTP request:
```
web_1      | 103.44.xxx.xxx - - [04/Aug/2018:17:45:08 +0000] "GET /config.js?room=sdfsdf HTTP/1.1" 200 0 "-" "okhttp/3.6.0"
```

Whereas on another Jitsi Meet instance (radium2.jitsi.net; which is provisioned by the jitsi team) that works correctly with mobile clients, the first `/config.js` HTTP request is immediately followed by several requests to `/http-bind`.
```
103.44.xxx.xxx - - [04/Aug/2018:17:45:01 +0000] "GET /config.js?room=dd HTTP/1.1" 200 5245 "-" "okhttp/3.6.0" "-"
103.44.xxx.xxx - - [04/Aug/2018:17:45:01 +0000] "GET /libs/analytics-ga.js HTTP/1.1" 200 5598 "-" "okhttp/3.6.0" "-"
103.44.xxx.xxx - - [04/Aug/2018:17:45:01 +0000] "GET /libs/jitsi-analytics-web-client.min.js HTTP/1.1" 404 395 "-" "okhttp/3.6.0" "-"
103.44.xxx.xxx  - - [04/Aug/2018:17:45:01 +0000] "POST /http-bind?room=dd HTTP/1.1" 200 622 "-" "okhttp/3.6.0" "-"
103.44.xxx.xxx - - [04/Aug/2018:17:45:02 +0000] "POST /http-bind?room=dd HTTP/1.1" 200 199 "-" "okhttp/3.6.0" "-"
103.44.xxx.xxx - - [04/Aug/2018:17:45:02 +0000] "POST /http-bind?room=dd HTTP/1.1" 200 386 "-" "okhttp/3.6.0" "-"
103.44.xxx.xxx - - [04/Aug/2018:17:45:02 +0000] "POST /http-bind?room=dd HTTP/1.1" 200 367 "-" "okhttp/3.6.0" "-"
103.44.xxx.xxx - - [04/Aug/2018:17:45:02 +0000] "POST /http-bind?room=dd HTTP/1.1" 200 307 "-" "okhttp/3.6.0" "-"
103.44.xxx.xxx  - - [04/Aug/2018:17:45:02 +0000] "POST /http-bind?room=dd HTTP/1.1" 200 2348 "-" "okhttp/3.6.0" "-"
103.44.xxx.xxx - - [04/Aug/2018:17:45:02 +0000] "POST /http-bind?room=dd HTTP/1.1" 200 623 "-" "okhttp/3.6.0" "-"
103.44.xxx.xxx - - [04/Aug/2018:17:45:02 +0000] "POST /http-bind?room=dd HTTP/1.1" 200 2204 "-" "okhttp/3.6.0" "-"
103.44.xxx.xxx - - [04/Aug/2018:17:45:03 +0000] "POST /http-bind?room=dd HTTP/1.1" 200 2058 "-" "okhttp/3.6.0" "-"
103.44.xxx.xxx - - [04/Aug/2018:17:45:03 +0000] "POST /http-bind?room=dd HTTP/1.1" 200 563 "-" "okhttp/3.6.0" "-"
103.44.xxx.xxx - - [04/Aug/2018:17:45:04 +0000] "POST /http-bind?room=dd HTTP/1.1" 200 316 "-" "okhttp/3.6.0" "-"
103.44.xxx.xxx - - [04/Aug/2018:17:45:04 +0000] "POST /http-bind?room=dd HTTP/1.1" 200 116 "-" "okhttp/3.6.0" "-"
```

**Comment by damencho** [comment]
Have you checked this? https://github.com/jitsi/docker-jitsi-meet/issues/2#issuecomment-409202397

**Comment by ztl8702** [comment]
@damencho  I had not. And setting BOSH url to absolute url solves the issue. Thanks!
