### ISSUE TITLE
Jitsi on Kubernetes - jvb -> Error: Could not find or load main class the

### ISSUE THREAD

**Issue by danilorsilva** [jitsi/docker-jitsi-meet#401]
Hello all,

I just finished to install jitsi on kubernetes using this guide: https://github.com/jitsi/docker-jitsi-meet/tree/master/examples/kubernetes

All the components are running but on JVB container i have this error:
Logs:
*Error: Could not find or load main class the*

Another point:
I configured a ingress and i have success to access it. The meeting works fine with me in the room. When a guest try to enter in a meeting i have a error and the session reconnect. At this moment, the meeting only works with one person on the room. If someone try to enter the session crash and reconnect, crash and reconnect in a loop.

Anyone can help me with these two problems?

Thank you so much!

**Comment by danilorsilva** [comment]
I found my problem, thanks.

**Comment by glaudiston** [comment]
> I found my problem, thanks.

What was the problem?

**Comment by rhajamor** [comment]
see https://github.com/jitsi/docker-jitsi-meet/issues/310
