### ISSUE TITLE
Audio/Video Probem more than 2 users - kubernetes

### ISSUE THREAD

**Issue by danilorsilva** [jitsi/docker-jitsi-meet#403]
Hello, i have installed jitsi on kubernetes cluster (GKE).

Everything works fine with 1 and 2 participants on the conference. 

When a third person join the conference all the problem starts... audio and video stop working and only came back when the third person exit the conference.

Anyone can help me?

Thanks!

**Comment by Zakspeed** [comment]
The same happens to me,
But I docker-compose with NAT

it doesn't work with + of 2

**Comment by danilorsilva** [comment]
I figure out that with 1 and 2 in conference it works with p2p.

When conference more than 2 users, the jvb is used. 

So, the problem is probably on JVB.

**Comment by Zakspeed** [comment]
Log in this container:


JVB 2020-04-08 21:27:05.528 WARNING: [426] org.jitsi.videobridge.EndpointMessageTransport.log() No available transport channel, can't send a message


JVB 2020-04-08 21:27:07.262 INFO: [19] org.jitsi.videobridge.Videobridge.log() CAT=stat create_conf,conf_id=e1b54fc1fd01fbd0 conf_name=null,logging=false,conf_count=2,ch_count=6,v_streams=4


JVB 2020-04-08 21:27:07.286 INFO: [19] org.jitsi.videobridge.health.Health.log() Performed a successful health check in 25ms. Sticky failure: false


JVB 2020-04-08 21:27:07.524 WARNING: [445] org.jitsi.videobridge.EndpointMessageTransport.log() SCTP connection with 79040a34 not ready yet.


JVB 2020-04-08 21:27:07.524 WARNING: [445] org.jitsi.videobridge.EndpointMessageTransport.log() No available transport channel, can't send a message


JVB 2020-04-08 21:27:07.528 WARNING: [445] org.jitsi.videobridge.EndpointMessageTransport.log() SCTP connection with 79040a34 not ready yet.

**Comment by rodrigopavezi** [comment]
This should you guys https://github.com/jitsi/docker-jitsi-meet/pull/415. I was facing the same issue until I figured out that JVB needs to be open accessible in the internet. So I create a LoadBalance service for it.

**Comment by Zakspeed** [comment]
> JVB

In my case I have to open the ports, (firewall)
The ports that the "JVB" expose "default" are: 10000 and 4443

Do I open the 2 ports to the internet? or which of them?

THANKS

**Comment by PolynomialDivision** [comment]
Please look for errors in the Console of your browser.

We had similar problems behing a NAT. Replacing
> org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=<Local_Adress>
> org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=<Public_Adress>

with

> org.jitsi.videobridge.NAT_HARVESTER_LOCAL_ADDRESS=<Local_Adress>
> org.jitsi.videobridge.NAT_HARVESTER_PUBLIC_ADDRESS=<Public_Adress>
> on sip-communicator.properties

as descirbed [here](https://community.jitsi.org/t/bridge-channel-send-no-opened-channel/18765/9) was fixing this problem!
