### ISSUE TITLE
new image fails connecting after upgrading

### ISSUE THREAD

**Issue by brunoamaral** [jitsi/docker-jitsi-meet#404]
I am using the docker-compose.yaml file in the repo, and right now jitsi fails to connect after I upgraded the image with `docker-compose pull`
![image](https://user-images.githubusercontent.com/543344/78714910-87a0f180-7914-11ea-96be-55531a68580d.png)
From the console, I am getting a few warnings but no error:
```

prosody_1  | focus.meet.jitsi:component                warn	Component not connected, bouncing error for: <iq to='focus.meet.jitsi' id='edb00480-10ad-4d5a-9470-2067777e2432:sendIQ' type='set' from='ppvuemibcauouotj@meet.jitsi/4zHvm8Bw'>
web_1      | 172.19.0.1 - - [07/Apr/2020:21:09:35 +0100] "POST /http-bind?room=testing HTTP/1.1" 200 2962 "https://host.domain.tld/testing" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"
prosody_1  | focus.meet.jitsi:component                warn	Component not connected, bouncing error for: <iq to='focus.meet.jitsi' id='11fad196-de08-4d79-b87b-9760c34e666c:sendIQ' type='set' from='ppvuemibcauouotj@meet.jitsi/4zHvm8Bw'>
web_1      | 172.19.0.1 - - [07/Apr/2020:21:09:36 +0100] "POST /http-bind?room=testing HTTP/1.1" 200 478 "https://host.domain.tld/testing" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"
prosody_1  | focus.meet.jitsi:component                warn	Component not connected, bouncing error for: <iq to='focus.meet.jitsi' id='1a602011-10d6-4412-9b1f-e3e89b806a5b:sendIQ' type='set' from='ppvuemibcauouotj@meet.jitsi/4zHvm8Bw'>
web_1      | 172.19.0.1 - - [07/Apr/2020:21:09:38 +0100] "POST /http-bind?room=testing HTTP/1.1" 200 478 "https://host.domain.tld/testing" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"
prosody_1  | focus.meet.jitsi:component                warn	Component not connected, bouncing error for: <iq to='focus.meet.jitsi' id='1a602011-10d6-4412-9b1f-e3e89b806a5b:sendIQ' type='set' from='ppvuemibcauouotj@meet.jitsi/4zHvm8Bw'>
```

**Comment by brooqs** [comment]
Hi,

I had the same situation, so far I have found 2 errors. The first one was http-bind wrong, I fixed this. Then it wrote component-secret no-value in the prosody/conf.d/jitsi-meet.cfg.lua file. When I replaced this with the secret in the .env file it has been working right now. I Hope this help.

Stay Healty.

**Comment by porjo** [comment]
I can confirm same issue. jifcofo and jvb containers exit on first connection from web:
```
# docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED              STATUS                          PORTS                                      NAMES
e0bd97847ef8        jitsi/jicofo        "/init"             About a minute ago   Exited (1) About a minute ago                                              docker-jitsi-meet_jicofo_1
61669dc467d0        jitsi/jvb           "/init"             About a minute ago   Exited (1) About a minute ago                                              docker-jitsi-meet_jvb_1
1449799842ce        jitsi/web           "/init"             About a minute ago   Up About a minute               0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   docker-jitsi-meet_web_1
7f6831b85040        jitsi/prosody       "/init"             About a minute ago   Up About a minute               5222/tcp, 5269/tcp, 5280/tcp, 5347/tcp     docker-jitsi-meet_prosody_1
```

**Comment by brooqs** [comment]
Currently only p2p is running on my server. When the 3rd person enters the meeting, all communication is interrupted. When the third person leaves the meeting, everything returns to normal.

**Comment by teutat3s** [comment]
might be this commit https://github.com/jitsi/docker-jitsi-meet/commit/5e6faced4ff7724b65d608f6fe93fabe70743efd

**Comment by immanuelfodor** [comment]
I also removed the public url config to fix the http bind error but I still get a focus unauthorized error. The secret is written to the lua config right, though. 

```
jicofo_1   | Jicofo 2020-04-08 06:27:36.360 SEVERE: [52] org.jitsi.jicofo.JvbDoctor.log() Unexpected error returned by the bridge: jvb@auth.meet.jitsi/YUNYe7LS, err: <iq to='focus@auth.meet.jitsi/focus85943495815418' from='jvb@auth.meet.jitsi/YUNYe7LS' id='D3lzk-163' type='error'><error type='auth'><not-authorized xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/></error></iq>
```

Maybe it's related?

**Comment by immanuelfodor** [comment]
I've found this line, it doesn't look good: 

```bash
cat .jitsi-config/jvb/sip-communicator.properties
org.jitsi.videobridge.AUTHORIZED_SOURCE_REGEXP=<no value>@auth.meet.jitsi/.*
```

What should be at the no value?

**Comment by immanuelfodor** [comment]
I replaced the no value with focus as best guess, restarted the docker compose, and now it works.

**Comment by ahoeg** [comment]
I tried to install my second test instance with some days delay and also run into problems.

It looks like security was improved in the last days. jicofo container fails with the following error message with the same ENV file and newer images automatically pulled during deploy the containers.
```
jitsi_jicofo.1.uhm8ge1defy0@rancher.it-dengler.de    | FATAL ERROR: Jicofo auth password must be changed, check the README
```

See changed .env file
```
# Security
#
# Set these to strong passwords to avoid intruders from impersonating a service account
# The service(s) won't start unless these are specified
# Running ./gen-passwords.sh will update .env with strong passwords
# You may skip the Jigasi and Jibri passwords if you are not using those
# DO NOT reuse passwords
#

# XMPP component password for Jicofo
JICOFO_COMPONENT_SECRET=

# XMPP password for Jicofo client connections
JICOFO_AUTH_PASSWORD=

# XMPP password for JVB client connections
JVB_AUTH_PASSWORD=

# XMPP password for Jigasi MUC client connections
JIGASI_XMPP_PASSWORD=

# XMPP recorder password for Jibri client connections
JIBRI_RECORDER_PASSWORD=

# XMPP password for Jibri client connections
JIBRI_XMPP_PASSWORD=
```

I tried new images (auto pull) with my old ENV file and it fails to. So it looks like simple passwords reject and need to be set secure to start the containers / jitsi service?

**Comment by ahoeg** [comment]
With the new images I have still errors in the container logs and old images not work with the new env file. So I rolled back my deployed instance.

**Comment by alexruf** [comment]
I had the same issue. Problem is the outdated `.env` config. When generating a new one ensure to run `./gen-passwords.sh` before.

**Comment by gerroon** [comment]
I have the exact same problem. I had perfectly working docker container for over a year with Apache reverse proxy.

I started a totally new git pull with a fresh. I generated the passwords, made sure I have the correct ports, IP, disabled ssl, etc  and I get the exact same problem. 

What is the solution?

**Comment by gerroon** [comment]
> I had the same situation, so far I have found 2 errors. The first one was http-bind wrong, I fixed this. Then it wrote component-secret no-value in the prosody/conf.d/jitsi-meet.cfg.lua file. When I replaced this with the secret in the .env file it has been working right now. I Hope this help.
> 
> Stay Healty.


How did you fix the http-bind error? I have aworking http-bind as far as I can tell.

The password is set properly in the file you mention. It still does not work.

**Comment by gerroon** [comment]
`"/usr/share/jitsi-meet/"https:/DOMAIN"/http-bind" failed (2: No such file or directory), client: 172.22.0.1, server`

maybe it is a single slash problem?

**Comment by Zakspeed** [comment]
> Currently only p2p is running on my server. When the 3rd person enters the meeting, all communication is interrupted. When the third person leaves the meeting, everything returns to normal.

Duplicate of #403

**Comment by chadwallacehart** [comment]
I had the same issues. I ended up doing the following:
```
git pull
cp env. backup.env
cp env.example .env
nano .env
rm -r ~/.jitsi-meet-cfg/jicofo/
rm -r ~/.jitsi-meet-cfg/transcripts/
rm -r ~/.jitsi-meet-cfg/jvb/
rm -r ~/.jitsi-meet-cfg/prosody/
./gen-passwords.sh 
docker-compose up -d
```

I had to rebuild the .env file and set the passwords. The only configs I cared about were in rm -r ~/.jitsi-meet-cfg/web/, so I deleted the others so they would be regenerated. It looked like the autogenerated password was not making its way into `~/.jitsi-meet-cfg/jvb/sip-communicator.properties` for some reason.

**Comment by gerroon** [comment]
@ chadwallacehart 


Those are the exact steps I used and it does not work for me. 

The only non  standard thing I did was to modify couple ports in .env since those ports are already used by my system.

Also the jvb password was set properly for me

**Comment by dedors** [comment]
I also had 
`FATAL ERROR: Jicofo auth password must be changed, check the README`

the commands of @chadwallacehart helped. the "git pull" is really important, otherwise the env.example is not updated.

**Comment by ahoeg** [comment]
> With the new images I have still errors in the container logs and old images not work with the new env file. So I rolled back my deployed instance ti image tags `4101-2`.

I tested with the new env file too. It doesn't work for me...

**Comment by antonanders** [comment]
We've had the same issue after upgrading this morning.

seems that the http-bind issue comes from the char " at the beginning of a configured url.
In our case we had to modifiy **.jitsi-meet-cfg/web/config.js**
```
        // bosh: '"https://meet.droidnet.de/http-bind', <--- this is wrong!
        bosh: 'https://meet.droidnet.de/http-bind',
```
and the same for etherpad:
```
    // etherpad_base: '"https://meet.droidnet.de/etherpad/p/', <-- this is wrong!
    etherpad_base: 'https://meet.droidnet.de/etherpad/p/',
```

the FATAL ERROR from @dedors is simply resolved by adding the new security settings from env.example (see top of the file) to your **.env file** and running **./gen-passwords.sh**
You need to make sure that you first remove/move your **.jitsi-meet-cfg/** folder as to my knowlegte it needs  to be regenerated.

**Comment by brunoamaral** [comment]
**For anyone upgrading**, I can confirm that changing the .env file to the new version and running gen-passwords.sh fixes the problem. You will also need to delete .jitsi-meet-cfg or whatever your config directory is.

**Comment by gerroon** [comment]
@antonanders 

Your solution definetely takes care of the http-bind issue, so this is clearly a bug, since none of us creates those urls manually.

I can now join the room but I cant see my camera feed, nor I can enbable the microphone or the camera even though the browser has permissions to do so, I get the error below


```
2020/04/09 09:03:20 [error] 241#241: *11 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.23.0.1, server: _, request: "POST /http-bind?room=problematicspinsarriveeast HTTP/1.1", upstream: "http://172.23.0.3:5280/http-bind?room=problematicspinsarriveeast", host: "DOMAIN", referrer: "https://DOMAIN/ProblematicSpinsArriveEast"
web_1      | 172.23.0.1 - - [09/Apr/2020:09:03:20 -0500] "POST /http-bind?room=problematicspinsarriveeast HTTP/1.1" 504 597 "https://DOMAIN/ProblematicSpinsArriveEast" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36"



```

**Comment by freechelmi** [comment]
This why the docker-compose need a tag env param for all docker images.

**Comment by freechelmi** [comment]
For now I went back to git tag stable-4101-1 and used the tag 4101-1 for each of the 4 docker images.

This is 15 days old but it works.

**Comment by yosoyfunes** [comment]
**it work for me**

```
# down containers
docker-compose down

# reset config to tag stable-4101-1
git checkout stable-4101-1

# delete data
rm -r ~/.jitsi-meet-cfg/jicofo/
rm -r ~/.jitsi-meet-cfg/transcripts/
rm -r ~/.jitsi-meet-cfg/jvb/
rm -r ~/.jitsi-meet-cfg/prosody/

# backup environment
cp .env backup.env

# create new environment from tag stable-4101-1
cp env.example .env

# configure .env again
vim .env

# build images to tag stable-4101-1
make all

# start services 
docker-compose up -d
```

:)

**Comment by freechelmi** [comment]
I guess most people won't do the "make all" step and just pull the latest images from docker hub , which would IMO not work

**Comment by carchrae** [comment]
instead of rebuilding, you can just change docker-compose.yml.

change all 4 lines that refer to image, eg
```
image: jitsi/web
```
to
```
image: jitsi/web:4101-1
```

**Comment by EliterScripts** [comment]
> # build images to tag stable-4101-1
> make all

I am very concerned, because I just wanted to contain Jitsi within Docker, now it's doing all sorts of sketchy stuff.

**Comment by dg-otrs** [comment]
> We've had the same issue after upgrading this morning.
> 
> seems that the http-bind issue comes from the char " at the beginning of a configured url.
> In our case we had to modifiy **.jitsi-meet-cfg/web/config.js**
> 
> ```
>         // bosh: '"https://meet.droidnet.de/http-bind', <--- this is wrong!
>         bosh: 'https://meet.droidnet.de/http-bind',
> ```
> 
> and the same for etherpad:
> 
> ```
>     // etherpad_base: '"https://meet.droidnet.de/etherpad/p/', <-- this is wrong!
>     etherpad_base: 'https://meet.droidnet.de/etherpad/p/',
> ```
> 
> the FATAL ERROR @dedors reported, is simply resolved by adding the new security settings from env.example (see top of the file) to your **.env file** and running **./gen-passwords.sh** (see [#404 (comment)](https://github.com/jitsi/docker-jitsi-meet/issues/404#issuecomment-610756545) )
> You need to make sure that you first remove/move your **.jitsi-meet-cfg/** folder as to my knowlegte it needs to be regenerated.

Make sure **not** to set the PUBLIC_URL within " " this will lead into the issue.

Just PUBLIC_URL=meet.xxx.com and you are fine without the http-bind issue. Just solved it in my local instance.

DD

**Comment by saghul** [comment]
Hey all, apologies for the trouble with the update.

This was mostly caused by the fix we made to fix a security problem: https://github.com/jitsi/docker-jitsi-meet/blob/master/CHANGELOG.md#stable-4384-1

In order to fix it I intentionally broke installations on upgrade, so one would not be able to run an insecure installation. It's harsh, yes, but needed.

Wiping the config volume and starting from scratch with a fresh .env file off env.example should yield a working setup. If it ddoesn't, please open a new issue.

I'm closing this one since it has accumulated some noise, with a number of unrelated issues being intertwined.

Apologies.

**Comment by EliterScripts** [comment]
@saghul yeah, I just looked at it. It is NOT fixed.

**Comment by saghul** [comment]
Please open a new issue and include all logs.
