### ISSUE TITLE
JWT not working using standard config

### ISSUE THREAD

**Issue by eythork** [jitsi/docker-jitsi-meet#412]
There seems to be something wrong with the JWT configuration.  JWT authentication always fails even if the JWT token is valid.  It's fairly easy to reproduce the problem on your local machine:

git clone https://github.com/jitsi/docker-jitsi-meet && cd docker-jitsi-meet
cp env.example .env

Change the following vars in .env:

ENABLE_AUTH=1
ENABLE_GUESTS=0
AUTH_TYPE=jwt
JWT_APP_ID=myapp
JWT_APP_SECRET=my_secret_key
JWT_AUTH_TYPE=token
JWT_TOKEN_AUTH_MODULE=token_verification

Run:
mkdir -p ~/.jitsi-meet-cfg/{web/letsencrypt,transcripts,prosody,jicofo,jvb,jigasi,jibri}
./gen-passwords.sh
docker-compose up -d

Generate a valid JWT token using your favorite libarary 
Sample jwt:
{
  "typ": "JWT",
  "alg": "HS256"
}
"context": {
    "user": {
      "avatar": "https://robohash.org/john-doe",
      "name": "Someone",
      "email": "joe@hotmail.com"
    },
    "aud": "myapp",
    "iss": "myapp",
    "sub": "localhost",
    "room": "*",
    "exp": 1646854187
  }
}

Then go to: https://localhost:8443/someroom?jwt=your_toke_here

You immediatly get a notification saying "Authentication failed"

Response from BOSH/http-bind is:
<body xmlns='http://jabber.org/protocol/httpbind' xmlns:stream='http://etherx.jabber.org/streams' sid='2601b5da-f23f-460a-86fa-150af28030ab'><failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'><not-allowed/><text>token required</text></failure></body>

JWT signature is verifed on jwt.io debugger.  The jitsi docker setup refuses to accept the token.

**Comment by eythork** [comment]
I forgot to mention that 

`docker-compose logs|grep token `

returns:

`prosody_1  | general                     warn	Error verifying token err:not-allowed, reason:token required`

I've tried downgrading to the 4101 tagged images on dockerhub from 4 months ago.  I get the same errors.  I'm starting to think that something is missing in my configuration.  I've tried messing with lots of other ENV vars as well as the config files for the web and prosody containers that get generated in ~/.jitsi-meet-cfg  Havn't found anything that works. 

Any pointers as to what could be wrong with the config above would be greatly appreciated.

**Comment by hoatle** [comment]
@eythork make sure to generate the jwt token by providing the payload and `JWT_APP_SECRET` value on the `VERIFY SIGNATURE` section from https://jwt.io/#debugger-io

**Comment by eythork** [comment]
Thanks for the reply @hoatle !  I believe that I have been generating the jwt token correctly.  For instance, using the payload and secret key in the example above my token generator creates the token 

`eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb250ZXh0Ijp7InVzZXIiOnsiYXZhdGFyIjoiaHR0cHM6XC9cL3JvYm9oYXNoLm9yZ1wvam9obi1kb2UiLCJuYW1lIjoiU29tZW9uZSIsImVtYWlsIjoiam9lQGhvdG1haWwuY29tIn0sImF1ZCI6Im15YXBwIiwiaXNzIjoibXlhcHAiLCJzdWIiOiJsb2NhbGhvc3QiLCJyb29tIjoiKiIsImV4cCI6IjE2NDY4NTQxODcifX0.fu3NyJ-EixS0PAaw5Iep8bxKZ17ixx-W0cBI_ngeuYw`

When I enter the token into https://jwt.io/#debugger-io and use "my_secret_key" as the secret I get "Signature Verified"

<img width="335" alt="image" src="https://user-images.githubusercontent.com/15385409/78951757-c07ec900-7ac2-11ea-863d-3c773b8319d0.png">


However when I go to 

https://localhost:8443/mytestroom?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb250ZXh0Ijp7InVzZXIiOnsiYXZhdGFyIjoiaHR0cHM6XC9cL3JvYm9oYXNoLm9yZ1wvam9obi1kb2UiLCJuYW1lIjoiU29tZW9uZSIsImVtYWlsIjoiam9lQGhvdG1haWwuY29tIn0sImF1ZCI6Im15YXBwIiwiaXNzIjoibXlhcHAiLCJzdWIiOiJsb2NhbGhvc3QiLCJyb29tIjoiKiIsImV4cCI6IjE2NDY4NTQxODcifX0.fu3NyJ-EixS0PAaw5Iep8bxKZ17ixx-W0cBI_ngeuYw  

I get the errors I mention in the posts above.

<img width="442" alt="image" src="https://user-images.githubusercontent.com/15385409/78951850-10f62680-7ac3-11ea-8581-1c87ae26b623.png">

This is the payload:

`{
  "context": {
    "user": {
      "avatar": "https://robohash.org/john-doe",
      "name": "Someone",
      "email": "joe@hotmail.com"
    },
    "aud": "myapp",
    "iss": "myapp",
    "sub": "localhost",
    "room": "*",
    "exp": "1646854187"
  }
}`

And this is the header:

`{
  "typ": "JWT",
  "alg": "HS256"
}`

**Comment by eythork** [comment]
Problem Solved.  Turned I had everything in the context array in the payload.  Needed to move some of the vars outside:

Before:

{
"typ": "JWT",
"alg": "HS256"
}
"context": {
"user": {
"avatar": "https://robohash.org/john-doe",
"name": "Someone",
"email": "joe@hotmail.com"
},
"aud": "myapp",
"iss": "myapp",
"sub": "localhost",
"room": "*",
"exp": 1646854187
}
}

After:

{
"typ": "JWT",
"alg": "HS256"
}
"context": {
"user": {
"avatar": "https://robohash.org/john-doe",
"name": "Someone",
"email": "joe@hotmail.com"
}
},
"aud": "myapp",
"iss": "myapp",
"sub": "localhost",
"room": "*",
"exp": 1646854187
}

Works fine now!

**Comment by tuanaturkmen** [comment]
@eythork  Hello, I am trying to enable Jitsi jwt authentication on Docker too. I have made the changes you made in my .env file but when I try to join a room without a token, I am able to join. Thus I think token authentication is not working at all. But our configuration is the same, I do not understand. I would like to ask did you additionally install or enable a prosody authentication plugin? Or did you do anything differend than the things you wrote here?
