### ISSUE TITLE
Address RTP in SDP & PROXY PORT 

### ISSUE THREAD

**Issue by XHAGBARD** [jitsi/docker-jitsi-meet#42]
Hello, I have an installation with docker-compose in a Centos7, I'm having problems with jigasi, exactly two:
The option PROXY_PORT in .env is omitted in practice, I need the port to be 5062 but ignore it and continue transmitting to 5060.

The address in SDP to transmit RTP is the IP of the Docker container:
```
v = 0
o = 117225-jitsi.org 0 0 IN IP4 **172.18.0.6**
s = -
c = IN IP4 172.18.0.6
t = 0 0
m = audio 20004 RTP / AVP 96 97 9 0 8 98 101
a = rtpmap: 96 opus / 48000/2
a = fmtp: 96 usedtx = 1
a = ptime: 20
a = rtpmap: 97 AMR-WB / 16000
a = rtpmap: 9 G722 / 8000
a = rtpmap: 0 PCMU / 8000
a = rtpmap: 8 PCMA / 8000
a = rtpmap: 98 iLBC / 8000
a = rtpmap: 101 telephone-event / 8000
a = extmap: 1 urn: ietf: params: rtp-hdrext: csrc-audio-level
a = extmap: 2 urn: ietf: params: rtp-hdrext: ssrc-audio-level
a = rtcp-xr: voip-metrics
```

This causes that there is no audio in one direction of the call.

**Comment by saghul** [comment]
> The option PROXY_PORT in .env is omitted in practice

No image has been pushed with this option yet, you can either wait for updated images or build your own by using the provided Makefile.

> The address in SDP to transmit RTP is the IP of the Docker container:

Your server should be able to handle this properly if you enable "NAT mode" of some kind.

**Comment by XHAGBARD** [comment]
> > The option PROXY_PORT in .env is omitted in practice
> 
> No image has been pushed with this option yet, you can either wait for updated images or build your own by using the provided Makefile.
> 

Sorry, I was referring to the "JIGASI_SIP_PORT" option in .env. When compiled, the entry "net.java.sip.communicator.impl.protocol.sip.acc1.PROXY_PORT = {{.Env.JIGASI_SIP_PORT}}" is generated in sip-communicator.properties

**Comment by saghul** [comment]
Same answer, unless you build the images yourself this option is ignored. Or are you referring to something else?

**Comment by saghul** [comment]
Yes, it's there, but the Docker image doesn't currently read it. The image in DockerHub, that is. That is because I haven't pushed new images after that change was introduced.

**Comment by saghul** [comment]
Updated the Docker images. You can pull now and the settings will work. Don't forget to wipe your config first.
