### ISSUE TITLE
Feature update April 2020

### ISSUE THREAD

**Issue by MaxNoe** [jitsi/docker-jitsi-meet#421]
I excitedly read the following announcement:
https://jitsi.org/news/features-update-april-2020/

And saw that at the same time, also saw that the docker images got update to 4384-1.
But it seems that this version does not yet include the announced new features.

Is that correct or did I do something wrong when applying the update?

**Comment by damencho** [comment]
That was still not pushed to stable and so docker does not have it yet. But it is coming soon.

Please use the community forum for questions before opening issues.
