### ISSUE TITLE
Add support for prosody custom plugins

### ISSUE THREAD

**Issue by reysy** [jitsi/docker-jitsi-meet#426]
Is there a way to add custom prosody plugins without changing jitsi/prosody docker-image?

Right now I am thinking of changing **Dockerfile** and **rootfs/etc/conf-init.d/10-config** script of prosody image, but I'm afraid that way I will be limited with future updates.

Can you add support of custom plugins for it or recommend proper way to implement it?

**Comment by sapkra** [comment]
You can add them by using a volume at the `/prosody-plugins-custom` path and enable them using the following env vars:

```
XMPP_MODULES
XMPP_MUC_MODULES
XMPP_INTERNAL_MUC_MODULES
GLOBAL_MODULES
```

For more information have a look at the README and [Dockerfile](https://github.com/jitsi/docker-jitsi-meet/blob/master/prosody/Dockerfile#L55).

But you're right this should be documented a bit better.

**Comment by reysy** [comment]
Yes, I saw those lines. Anyway, thanks @sapkra

**Comment by sapkra** [comment]
Ok how can I help you then? I'm using custom prosody plugins with this method.

**Comment by reysy** [comment]
I Ended up with writing bash script and added one line in **docker-compose.yml**
This is the script:
```
envFile=".env"

if [ -f $envFile ]; then
  set -a
  source $envFile

  if [ -d "$CONFIG" ]; then
    if [ ! -d "$CONFIG/prosody-plugins-custom" ]; then
      mkdir "$CONFIG/prosody-plugins-custom"
    fi
    cp custom/prosody-plugins-custom/* "$CONFIG/prosody-plugins-custom/"
  fi

  set +a
fi
```
And this change was added to volumes block in **docker-compose.yml**
```- ${CONFIG}/prosody-plugins-custom:/prosody-plugins-custom```

Thanks, @sapkra

**Comment by sapkra** [comment]
You can also define relative volumes like
```yaml
volumes:
- ./custom/prosody-plugins-custom:/prosody-plugins-custom
```

**Comment by satoshinotdead** [comment]
> You can add them by using a volume at the `/prosody-plugins-custom` path and enable them using the following env vars:
> 
> ```
> XMPP_MODULES
> XMPP_MUC_MODULES
> XMPP_INTERNAL_MUC_MODULES
> GLOBAL_MODULES
> ```
> 
> For more information have a look at the README and [Dockerfile](https://github.com/jitsi/docker-jitsi-meet/blob/master/prosody/Dockerfile#L55).
> 
> But you're right this should be documented a bit better.

That should be enough to enable whiteboard on Docker instance, if I updated my config.js and have the backend proxied to a specific -and working- domain?
