### ISSUE TITLE
JVB Crash if removing JVB_STUN_SERVERS 

### ISSUE THREAD

**Issue by daimoc** [jitsi/docker-jitsi-meet#43]
Hi,
I'm trying to deploy a jitsi-meet docker instance in a environment where JVB can't connect to external STUN server.
So I want to remove STUN discovery mechanism and set JVB Public IP with DOCKER_HOST_ADDRESS by removing JVB_STUN_SERVERS  env variable.

But there an issue in sip-communicator.properties generation from  template. 
If I set an empty value for JVB_STUN_SERVERS or if I remove it in .env file, the specified environment variable is empty on jvb container but  template generation with frep write \<no value\> in config file.
This \<no value\> is not valid and it crash Health check mechanism in JVB.
I had to stop my jvb container and correct by hand the jvb configuration file.
  
This \<no value\> instead of an empty string comes from default Golang template parse function used by frep (https://stackoverflow.com/questions/49933684/prevent-no-value-being-inserted-by-golang-text-template-library). 

Possible solution is to sanitize config file with a sed command to remove the \<no value\> after frep call  (or to made a PR in frep to configure is template parse  behavior.....)
-> sed -i 's/\<no value\>//' /config/sip-communicator.properties

Regards,
Damien

**Comment by saghul** [comment]
Hey Damien,

This is a known issue I plan on addressing soon. In the interim you can edit the sip-communicator.properties file by hand once it was generated on the first start.
