### ISSUE TITLE
QA: User friendly JTW token creation?

### ISSUE THREAD

**Issue by gerroon** [jitsi/docker-jitsi-meet#435]
Hi

Is there some kind of app, desktop app etc that will let me create rooms with JWT tokens? At the moment I am using the jwt.io to create them manually but it would be nice if I can do this on my desktop or phoen without internet.

thanks_

**Comment by saghul** [comment]
We don't have a web UI for that, sorry.

**Comment by gerroon** [comment]
I did not mean an integrated solution, any tool that someone might know of that is more user friendly for regular users.
