### ISSUE TITLE
Update images (maybe add CI)

### ISSUE THREAD

**Issue by sapkra** [jitsi/docker-jitsi-meet#44]
The published image is two month old - there are newer changes in the repository.
It would be great to have them up to date. Maybe with a CI tool.

**Comment by sapkra** [comment]
That the image are release every time jitsi itself has a new release make absolutely sense.
But we should still add a CI pipeline for releasing new images on each repository change.

PS: You're welcome. This project is awesome - props to all contributers. I'm working on another PR, so I will definitely continue supporting this project.

**Comment by saghul** [comment]
Quick heads up: a new release will hit stable soon, so I'll build new images then. I'll land some PRs while doing so.

As for the CI: I've never done that with this kind of setup, do you have any pointers?

**Comment by sapkra** [comment]
Nice to hear that.
I noticed that a lot of open source projects are using CircleCI. Maybe we can either.

https://circleci.com/docs/2.0/building-docker-images/

**Comment by saghul** [comment]
✨ ✨ https://community.jitsi.org/t/psa-new-docker-images-released/16622 ✨ ✨  The new release is up!

I'm going to close this and think about the CI thing some more. We do have a Jenkins setup for Jitsi Meet we could use, but unless the CI also runs end-to-end tests on the Docker setup, it doesn't give us much.

At any rate. new release, now with image tags referencing the Jitsi Meet stable release number!
