### ISSUE TITLE
Run Jitsi behind Cloudflare and with Let's Encrypt

### ISSUE THREAD

**Issue by omnidepp** [jitsi/docker-jitsi-meet#441]
Hi all,
when trying to get jitsi in docker up and running with cloudflare and ssl/tls "full" enabled, the web-component fails to obtain a certificate with this error:

```
Failed authorization procedure. meet.keller.jp (http-01): urn:ietf:params:acme:error:unauthorized :: The client lacks sufficient authorization :: Invalid response from http://XXX/.well-known/acme-challenge/jr9UjOAQ41VJf-hTwMyIVM9lGjRfHWzSxq9zJiWOzww [2606:4700:3036::6818:62b3]: "<!DOCTYPE html>\n<!--[if lt IE 7]> <html class=\"no-js ie6 oldie\" lang=\"en-US\"> <![endif]-->\n<!--[if IE 7]>    <html class=\"no-js "
web_1      | Failed to obtain a certificate from the Let's Encrypt CA.
```

This is no surprise, because according to [this](https://support.cloudflare.com/hc/en-us/articles/214820528-Validating-a-Let-s-Encrypt-Certificate-on-a-Site-Already-Active-on-Cloudflare) setup guide, one should use Let's Encrypt with "webroot" verification instead, when using cloudflare.

It would be aweseome if this could be integrated and toggled via the .env-config.

Cheers!

**Comment by saghul** [comment]
A PR would be welcome!

**Comment by muhviehstah** [comment]
Here is a PR :)

https://github.com/jitsi/docker-jitsi-meet/pull/462

**Comment by airdogvan** [comment]
Just wondering if you found solution.
