### ISSUE TITLE
Invalid server URL or external API not enabled when using the jitsi electron app to connect to jitsi on docker

### ISSUE THREAD

**Issue by MarkIannucci** [jitsi/docker-jitsi-meet#444]
I just deployed Jitsi Meet using docker compose and the conference works well internally and externally using the phone and web apps.  Unfortunately, I am unable to get the electron app to work.  When I populate my jitsi server's external address in the electron app, I get an error on validation which states:

    Invalid server URL or external API not enabled

In searching I found this [issue in the electron app repo](https://github.com/jitsi/jitsi-meet-electron/issues/189), which I think may be related.  Is anyone else running into this problem with their docker deployment?

**Comment by saghul** [comment]
Are you usisng a valid cert? This setup should have the external API properly configured.

**Comment by saghul** [comment]
Do you have an HTTP proxy of your own perhaps setting these headers: https://github.com/jitsi/jitsi-meet-electron#using-it-with-your-own-jitsi-meet-installation

**Comment by MarkIannucci** [comment]
@saghul , thanks for piping up on this.  I am using a valid cert from LetsEncrypt.  The instance is accessible at https://foxstreet.duckdns.org/, feel free to take a look to confirm.

When I tested this out, the client running the electron app was on the same network as my machine.  I did set the `DOCKER_HOST_ADDRESS` configuration value to the correct IP in my `.env` file.  To see if perhaps it is a NAT issue, I connected that client to a hotspot and am still getting the same error.

I updated the electron app to 2.02 today.

**Comment by MarkIannucci** [comment]
There is not a proxy between the linux box and the internet, so the headers that could be at issue are not the culprit.

**Comment by saghul** [comment]
I just tested it myself and worked fine:

<img width="1380" alt="Screen Shot 2020-04-16 at 09 50 34" src="https://user-images.githubusercontent.com/317464/79429448-ce06e800-7fc7-11ea-8a05-303dca2c2a06.png">

**Comment by MarkIannucci** [comment]
@saghul , was that with my server?  In that case, I suspect it is something with the client on my end.  Looking at your screenshot, I'm guessing that's a Mac client?  I'm using Windows. 

![image](https://user-images.githubusercontent.com/16762974/79490485-2b0b9980-7fda-11ea-8840-a3faba155a89.png)

I'm thinking this may be a better issue for the electron app repo.

**Comment by duanwujie** [comment]
I hava the same problem, which install jisi-meet on the debian

**Comment by GeorgSommer** [comment]
Same Problem here. But obviously you fixed it @MarkIannucci 
 I just tried with your server. So what was your fix please?

**Comment by MarkIannucci** [comment]
Hey @GeorgSommer , I'm afraid when I test it within my network, I still get the same issue :(

**Comment by mindrunner** [comment]
I have the same problem. 

Client is Arch Linux, if that matters. Other servers are working fine, but my `docker-jitsi-meet` instance complains about not enabled API.

- Proper SSL: yes
- https://server.domain.com/external_api.js returns a proper Javascript file.

in my server/nginx logs, all requests are HTTP 200.

Where else could the issue be?

**Comment by saghul** [comment]
Did you set any CSP or X-Frame-Origin headers on your web server?

**Comment by mindrunner** [comment]
I am not sure. I am using
https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion
for the SSL termination

**Comment by saghul** [comment]
Can you share the URL of your deployment? saghul @ jitsi . org if you'd rather not share it here.

**Comment by mindrunner** [comment]
Thanks @saghul for jumping in and testing this. Indeed, it seems to work, but I think I figured out why there is such a confusion about this.

Some servers need the trailing slash `https://server.domain.com/` and without `https://server.domain.com` it will produce the `API not enabled message`. On other servers, it is exactly the other way around. Make sure you try both! :)

**Comment by saghul** [comment]
Interesting! I'll give that a check!

**Comment by saghul** [comment]
I recently refactored the server URL handling in the Electron app. In addition, it's no longer necessary to load external_api remotely.
