### ISSUE TITLE
Letsencrypt Staging URL

### ISSUE THREAD

**Issue by yodaphone** [jitsi/docker-jitsi-meet#445]
Hi

Is there a setting that i can use in .env or docker-compose file to use letsencrypt staging URL ? thsi will eliminate Rate Limit issue till we get the containers up & running

**Comment by sych74** [comment]
I faced the same problem. Allowing to issue test certificates will be useful during development / testing phases.

**Comment by sapkra** [comment]
https://github.com/jitsi/docker-jitsi-meet/issues/71#issuecomment-469598336

**Comment by sych74** [comment]
> [#71 (comment)](https://github.com/jitsi/docker-jitsi-meet/issues/71#issuecomment-469523565)
>> Untrusted certs won't work on mobile. We already get tons of bogus reports from people trying to use self-signed certs on mobile, so I'd rather explore other solutions that don't involve untrusted certs.

People who do development and testing can easily understand that test certs won't work on mobile,  while at the same time they do not have an easy option to avoid hitting the limits of issued certs . 

As a quick workaround: 
1. Create small script for updating python3-acme https://github.com/jelastic/docker-jitsi-meet/blob/master/certbot-update and add it as volume like here https://github.com/jelastic/docker-jitsi-meet/blob/master/docker-compose.yml#L14
2. Add special options to _LETSENCRYPT_EMAIL="my@email.com __--test-cert --break-my-certs__"_

I hope it helps, but in general I believe enabling issuing of test certs should be improved and implemented via a dedicated env variable LETSENCRYPT_TEST_CERT=1.

**Comment by saghul** [comment]
> People who do development and testing can easily understand that test certs won't work on mobile,

You'd be surprised.

> I hope it helps, but in general I believe enabling issuing of test certs should be improved and implemented via a dedicated env variable LETSENCRYPT_TEST_CERT=1.

This makes sense. Let's have it. As long as the docs have a big warning saying it won't work on mobile we should be fine.

**Comment by yodaphone** [comment]
in the meanwhile i posted a TIP as to how to use it now

https://community.jitsi.org/t/tip-test-letsencrypt-to-avoid-hitting-rate-limits/38890

**Comment by ravibf** [comment]
Hi,

Atleast as of now, 

`LETSENCRYPT_USE_STAGING=0`

is actually getting a certificate issued by some  dummy CA of lets encrypt

When the above flag is made 1 then we are getting proper cetificate from lets encrypt and we dont see any certificate issues on the browser 

But remember, that if you change the above config in .env then on the host machine you need to remove 

`rm -rf ~/.jitsi-meet-cfg/ `
`mkdir -p ~/.jitsi-meet-cfg/{web/letsencrypt,transcripts,prosody,jicofo,jvb}`

unless this is done, the starting docker container sees the old cert and doesnt attempt renew.

**Comment by saghul** [comment]
Oops, I forgot to close this one, LETSENCRYPT_USE_STAGING has been added a while ago.
