### ISSUE TITLE
Invalid Cert from Quick Start

### ISSUE THREAD

**Issue by tooolbox** [jitsi/docker-jitsi-meet#447]
I followed the instructions in the [quick start](https://github.com/jitsi/docker-jitsi-meet#quick-start) and got Jitsi Meet running via docker-compose.  When I visit https://localhost:8443 I get an error in Chrome saying that the certificate is invalid: `NET::ERR_CERT_INVALID`.  Here's what I see on the cert:

<img width="499" alt="screenshot" src="https://user-images.githubusercontent.com/4984708/79144470-dd8df300-7d73-11ea-8ca4-e32be87c8e90.png">

I can't seem to add the cert to Keychain.  I *can* visit the Web UI on port 8000, just HTTP, and everything seems to work normally.

Apologies in advance if this is a mistake on my part or some kind of silly issue, but since I followed the directions to the letter I'm not sure what occurred.  I did look through the existing issues and didn't see that this was reported earlier.

If it helps, I'm running macOS Catalina on a 2017 MacBook Pro.

**Comment by Dextroz** [comment]
Hi 👋🏻 
I believe this is correct behaviour. When following the quick start steps, Jitsi meet generates a self-signed cert and this is why you see the error in your browser. The code decision flow for self-signed cert generation can be found [here](https://github.com/jitsi/docker-jitsi-meet/blob/master/web/rootfs/etc/cont-init.d/10-config#L41)
