### ISSUE TITLE
Move readme/docs to jitsi handbook

### ISSUE THREAD

**Issue by sapkra** [jitsi/docker-jitsi-meet#448]
Like all other jitsi repositories, this repository should have a docs directory that contains all information on how to configure the project in a sorted manner.

To do that we can just split the README into multiple files and link to them from the README. The README should just contain a list to the docs and some basic information.

I will may do this when I find some time.

**Comment by saghul** [comment]
Sounds like a good idea.

**Comment by TheoOliveira** [comment]
Iwould like to contribute to that. It's simple but as I am starting to contribute on github I just want some guidence towards. I've seen other repos don't have this idea and the main one is now on handbook. Could you give more detail so i can do that?

**Comment by sapkra** [comment]
I'm also thinking about what the focus will be for the handbook. Currently the doc for docker is just copied to the handbook repository. Should we update the docs over there and just link to them from this repository or should be add a script which copies the doc on build time of handbook to always be in sync with this repository. I've already wrote a script for it but it has to be adapted.

**Comment by saghul** [comment]
Hey folks! Yeah the plan is to start moving everything there. I haven’t gotten around updating the README here to point to the handbook. If anyone wants to take that, please and thank you :-)

**Comment by sapkra** [comment]
So the docs are getting removed from all code repositories and moved the the handbook repository, right?
I just want to clarify it because in "TheCall" there where some complains about it about 1-2 month ago. So if someone is changing the code the docs also have to be changed in the handbook?

**Comment by saghul** [comment]
That is my aim yes. We’ll see if it makes sense to keep some in their respective repos.

As for moving them, I have manually applied some PRs already, not to bug users into redoing it, so that’s fine.

**Comment by sapkra** [comment]
https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker
