### ISSUE TITLE
ACMEv2 support

### ISSUE THREAD

**Issue by oliv3** [jitsi/docker-jitsi-meet#451]
Hi,
Is ACMEv2 support planned or already existing ? I just got this mail from letsencrypt.org:
`
According to our records, the software client you're using to get Let's 
Encrypt TLS/SSL certificates issued or renewed at least one HTTPS certificate 
in the past two weeks using the ACMEv1 protocol. Here are the details of one 
recent ACMEv1 request from each of your account(s):
[...]
Beginning June 1, 2020, we will stop allowing new domains to validate using 
the ACMEv1 protocol. You should upgrade to an ACMEv2 compatible client before 
then, or certificate issuance will fail.
[...]
`
Thanks !

**Comment by saghul** [comment]
We are using certbot for creating the certs. Maybe we need to update the version?

**Comment by yodaphone** [comment]
> We are using certbot for creating the certs. Maybe we need to update the version?

AFAIK if you use the latest version certbot it automatically defaults to v2

**Comment by saghul** [comment]
Yeah, I think we'll switchc to certbot-auto with the next upgrae, not to be stuck with the current and old Debian package.

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/docker-jitsi-meet/commit/b039b29b7aeeee28f9f7395ec87e8aa69105ce9f
