### ISSUE TITLE
Q: meet.jit.si vs localhost:8443

### ISSUE THREAD

**Issue by pieter-janDB** [jitsi/docker-jitsi-meet#452]
Hi,

What is the difference in the jitsi meet dashboard between online and this docker version?
Is it possible to integrate the agenda in the docker version? Or say invite someone for a call at 2pm?
Is it a different version or just configured differently?

https://ibb.co/8g6BLyK (left = meet.jit.si / right = docker local)

Thanks in advance.

**Comment by sapkra** [comment]
I think you can enable it by setting the following value in the config.js.

```javascript
enableCalendarIntegration: true
```

**Comment by pieter-janDB** [comment]
Found this in tge config.js
`    // Enables calendar integration, depends on googleApiApplicationClientID
    // and microsoftApiApplicationClientID
    enableCalendarIntegration: true,`
googleApiApplicationClientID is undocumented.. it it possible to get some explanation about how we can implement it ? Only setting enableCalendarIntegration to true does not seem to do the trick

**Comment by sapkra** [comment]
This may help you. Otherwise have a look in the community forum. There are some threads about this topic. This is not related to the docker setup.
https://weblizar.com/blog/get-google-calendar-client-id-and-client-secret-key/
