### ISSUE TITLE
Infinite Loop "rejoin"  on new deployment

### ISSUE THREAD

**Issue by NightDragon1** [jitsi/docker-jitsi-meet#454]
Hi!
I just updated to the latest github data (git pull) recreated the .env file and started via docker-compose. All containers are running / are up. If i try to join any room I get immediately the message "You have been disconnected. You may want to check your network connection. Reconnecting in .. seconds".... 

(You can test it yourself: https://meet.shgn.org)

[jitsi-web.log](https://github.com/jitsi/docker-jitsi-meet/files/4477135/jitsi-web.log)
[jibri.log](https://github.com/jitsi/docker-jitsi-meet/files/4477134/jibri.log)

**Comment by NightDragon1** [comment]
Yes and of course i deleted the config-dir and all the containers before. So it was a blank installation ;)

**Comment by haggl** [comment]
I can confirm this: https://meet.hasi.it

**Comment by haggl** [comment]
Hmm ok changing
```
bosh: '//jitsi-meet.example.com/http-bind',
```
to
```
bosh: '/http-bind',
```
as suggested in 2c95ab7c9f828e64a0b823d1d523e02e7767ba99 seems to have fixed *this* particular error, however Jitsi seems to be utterly broken still.

**Comment by NightDragon1** [comment]
I justed checked my copy of the code and the 10-config contains the already fixed part:
``` 
sed -i \
        -e "s#jitsi-meet.example.com#$XMPP_DOMAIN#g" \
        -e "s#bosh:.*#bosh: '/http-bind',#" \
        -e "s#muc:.*#muc: '${XMPP_MUC_DOMAIN}',#" \
        -e "s#// focusUserJid:.*#focusUserJid: '${JICOFO_AUTH_USER}@${XMPP_AUTH_DOMAIN}',#" \
        /config/config.js
```

**Comment by haggl** [comment]
> I justed checked my copy of the code and the 10-config contains the already fixed part:
> 
> ```
> sed -i \
>         -e "s#jitsi-meet.example.com#$XMPP_DOMAIN#g" \
>         -e "s#bosh:.*#bosh: '/http-bind',#" \
>         -e "s#muc:.*#muc: '${XMPP_MUC_DOMAIN}',#" \
>         -e "s#// focusUserJid:.*#focusUserJid: '${JICOFO_AUTH_USER}@${XMPP_AUTH_DOMAIN}',#" \
>         /config/config.js
> ```

That applies only when you build the images yourself. Default is downloading them from Docker Hub. I also have the fixed script but it generated a faulty config.

**Comment by haggl** [comment]
HA!! Got it! That block you mentioned didn't seem to get executed when the image was built. Do the search&replace operations manually and it works again!

Care to test?
https://meet.hasi.it/debug

**Comment by saghul** [comment]
It must have existed, otherwise it's be templated. Also note that when updating you'll want to pull the new images with `docker-compose pull`.
