### ISSUE TITLE
Will Jibri work on a Synology NAS ?

### ISSUE THREAD

**Issue by Thumpermat** [jitsi/docker-jitsi-meet#455]
As I am not a Linux expert, I'm not sure if the Jibri container will work on a Synology NAS (x86) using the instructions for Centos7.

If not, what package do I need to install and where do I find it ?.

FYI, the standard Jitsi-meet docker works fine.

**Comment by Thumpermat** [comment]
P.S. : On the Synology OS I have found the following directories:
- /proc/sys/kernel/modprobe
- /usr/sbin/modprobe

So chances are that it should work, correct ?

**Comment by saghul** [comment]
Jibri is pretty resource hungry: it runs a Chrome instance, with ffmpeg recorrding its outout on a dummy Xorg server. Last I checked Synology NAS's diddn't have very powerful CPUs.

**Comment by Thumpermat** [comment]
Will give it a go and let you know.

I will use the instructions as per Centos7
