### ISSUE TITLE
stuck on 'recording has stopped' on new docker installation

### ISSUE THREAD

**Issue by 4khi1** [jitsi/docker-jitsi-meet#456]
jicofo_1 | Jicofo 2020-04-15 13:17:05.574 INFO: [108] org.jitsi.jicofo.recording.jibri.JibriSession.log() Starting session with Jibri jibribrewery@internal-muc.meet.jitsi/jibri-instanse-046985901
jicofo_1 | Jicofo 2020-04-15 13:17:05.574 INFO: [108] org.jitsi.jicofo.recording.jibri.JibriSession.log() Starting Jibri jibribrewery@internal-muc.meet.jitsi/jibri-instanse-046985901 for stream ID: null in room: test6@muc.meet.jitsi
jicofo_1 | Jicofo 2020-04-15 13:17:05.577 INFO: [108] org.jitsi.jicofo.recording.jibri.JibriSession.log() Updating status from JIBRI: for test6@muc.meet.jitsi
jicofo_1 | Jicofo 2020-04-15 13:17:05.578 INFO: [108] org.jitsi.jicofo.recording.jibri.JibriSession.log() Got Jibri status update: Jibri jibribrewery@internal-muc.meet.jitsi/jibri-instanse-046985901 has status pending and failure reason null, current Jibri jid is jibribrewery@internal-muc.meet.jitsi/jibri-instanse-046985901
jicofo_1 | Jicofo 2020-04-15 13:17:05.578 INFO: [108] org.jitsi.jicofo.recording.jibri.JibriRecorder.log() Started Jibri session
web_1 | 115.98.2.181 - - [15/Apr/2020:13:17:05 +0530] “POST /http-bind?room=test6 HTTP/1.1” 200 386 “https://mydomain.jitsi.in/test6” “Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36”
jicofo_1 | Jicofo 2020-04-15 13:17:05.844 INFO: [29] org.jitsi.jicofo.recording.jibri.JibriDetector.onInstanceStatusChanged().137 Received Jibri jibribrewery@internal-muc.meet.jitsi/jibri-instanse-046985901 status
jicofo_1 | Jicofo 2020-04-15 13:17:05.845 INFO: [29] org.jitsi.jicofo.recording.jibri.JibriDetector.notifyJibriStatus().175 Jibri: jibribrewery@internal-muc.meet.jitsi/jibri-instanse-046985901 available: false
jicofo_1 | Jicofo 2020-04-15 13:17:06.014 INFO: [108] org.jitsi.jicofo.recording.jibri.JibriSession.log() Updating status from JIBRI: for test6@muc.meet.jitsi
jicofo_1 | Jicofo 2020-04-15 13:17:06.014 INFO: [108] org.jitsi.jicofo.recording.jibri.JibriSession.log() Got Jibri status update: Jibri jibribrewery@internal-muc.meet.jitsi/jibri-instanse-046985901 has status off and failure reason error, current Jibri jid is jibribrewery@internal-muc.meet.jitsi/jibri-instanse-046985901
jicofo_1 | Jicofo 2020-04-15 13:17:06.015 INFO: [108] org.jitsi.jicofo.recording.jibri.JibriSession.log() Jibri is no longer pending, cancelling pending timeout task
jicofo_1 | Jicofo 2020-04-15 13:17:06.015 WARNING: [108] org.jitsi.jicofo.recording.jibri.JibriSession.log() failureReason was non-null but shouldRetry wasn’t set, will NOT retry
jicofo_1 | Jicofo 2020-04-15 13:17:06.015 INFO: [108] org.jitsi.jicofo.recording.jibri.JibriSession.log() Jibri failed and signaled that we should not retry the same request
jicofo_1 | Jicofo 2020-04-15 13:17:06.015 INFO: [108] org.jitsi.jicofo.recording.jibri.JibriRecorder.log() Got jibri status off and failure error
jicofo_1 | Jicofo 2020-04-15 13:17:06.016 INFO: [108] org.jitsi.jicofo.recording.jibri.JibriRecorder.log() Publishing new jibri-recording-status: in: test6@muc.meet.jitsi
jicofo_1 | Jicofo 2020-04-15 13:17:06.017 INFO: [108] org.jitsi.jicofo.recording.jibri.JibriSession.log() Cleaning up current JibriSession
web_1 | 115.98.2.181 - - [15/Apr/2020:13:17:06 +0530] “POST /http-bind?room=test6 HTTP/1.1” 200 1225 “https://mydomain.jitsi.in/test6” “Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.92 Safari/537.36”
jicofo_1 | Jicofo 2020-04-15 13:17:06.138 INFO: [29] org.jitsi.jicofo.recording.jibri.JibriDetector.onInstanceStatusChanged().137 Received Jibri jibribrewery@internal-muc.meet.jitsi/jibri-instanse-046985901 status
jicofo_1 | Jicofo 2020-04-15 13:17:06.138 INFO: [29] org.jitsi.jicofo.recording.jibri.JibriDetector.notifyJibriStatus().175 Jibri: jibribrewery@internal-muc.meet.jitsi/jibri-instanse-046985901 available: true

**Comment by 4khi1** [comment]
branch:  stable-4101
jitsi docker build tag:  4101
is working fine.

**Comment by martinbehrens** [comment]
Able to reproduce with stable-4416.

**Comment by martinbehrens** [comment]
@4khi1 Can you reopen please, so it's on the agenda and get's fixed eventually?

**Comment by saghul** [comment]
This should be fixed in stable-4548
