### ISSUE TITLE
Docker-Compose is failing

### ISSUE THREAD

**Issue by klm46** [jitsi/docker-jitsi-meet#46]
Hi,

even with correkt -env-File and your Docker-Compose.yml the Building of the Service is failing with following:

docker stack deploy -c docker-compose.yml meet1
1 error(s) decoding:

* error decoding 'Ports': No port specified: :/udp<empty>

In the Basic Conf Sektion i did this:

#
# Basic configuration options
#

# Directory where all configuration will be stored.
CONFIG=~/.jitsi-meet-cfg

# Exposed HTTP port.
HTTP_PORT=80

# Exposed HTTPS port.
HTTPS_PORT=443

# System time zone.
TZ=Europe/Amsterdam

# IP address of the Docker host. See the "Running on a LAN environment" section
# in the README.
DOCKER_HOST_ADDRESS=10.12.10.94

Any Ideas?

**Comment by saghul** [comment]
Did you build the containers yourself or did you pull from DockerHub? Currently there are some extra options which haven't been released to DockerHub yet so you need to build the images. You can do that by typing `make`.

**Comment by klm46** [comment]
Hi,

i did pull this project and than did docker-compose as written here. Where shpould I execute "make ."?

Thanks for your answer
