### ISSUE TITLE
Tag Container Pulls in docker-compose.yml

### ISSUE THREAD

**Issue by davepage-mcr** [jitsi/docker-jitsi-meet#461]
`docker-jitsi-meet` provides tagged releases as per https://github.com/jitsi/docker-jitsi-meet/releases which correlate with upstream Jitsi releases. This repository contains subfolders with the relevant Dockerfiles and rootfs entries to build each component of jitsi locally.

However, the `docker-compose.yml` file in each release will always pull the latest image for each component from Docker Hub. This means that for example pulling the 4101 release of docker-jitsi-meet will give you a configuration file for that release, but running `docker-compose up` will give you containers from the latest release 4384, for which that configuration is invalid (doesn't contain `gen-passwords.sh`). This is confusing behaviour causing unexpected problems.

Either this repository shouldn't provide tagged releases, or the docker-compose file should use the same tags. i.e. pulling the 4101 release of docker-jitsi-meet should give you a `docker-compose.yml` which pulls the 4101-tagged image.

Perhaps the tagging operation could check that these tags are applied in the `docker-compose.yml` and match the tag being applied to this repo?

**Comment by saghul** [comment]
What about in-between releases? Would latest be ok there? I'm happy to adjust it when tagging the (new) releases.

**Comment by mtyurt** [comment]
That's why I added `${TAG}` to image definitions and added `TAG=` to `.env` file.

**Comment by saghul** [comment]
@mtyurt Did you send a PR with that? Can't find it.

**Comment by nobbs** [comment]
@saghul As there was no PR, I've created one in #476.

**Comment by saghul** [comment]
Solved it by adding a release script which tags images: https://github.com/jitsi/docker-jitsi-meet/commit/a79fc0c9149265e1e32c944c4f7d8d3f2bff1665 master will always have the latest.
