### ISSUE TITLE
Jibri's docker :  dropbox integration

### ISSUE THREAD

**Issue by nyok92** [jitsi/docker-jitsi-meet#471]
Hi ,
I manged to record meeting inetrnally using jibri. 
Now, i want to record and use the dropbox integration.
Dropbox api is working, it creates the right folder on my dropbox account but the file is never pushed. I think it is because there is no script available in the jibri's official image. Maybe we could add this by default ? :
https://github.com/jitsi/jitsi-upload-integrations

Maybe i missed somehting ... 
I'll try to put the dropbox script  to my JIBRI_FINALIZE_RECORDING_SCRIPT_PATH

**Comment by nyok92** [comment]
I managed to get it working by replacing the finalize.sh script with jitsi_uploader.sh content and adding the dropbox_uploader in jibri's config. Then change chmod of theese file to 755. I had to relink the right place of dropbox_uploader.sh in jitsi_uploader.sh file.

**Comment by rajeshworld123** [comment]
Hi @nyok92 
Can you please guide me how to do this in docker setup
