### ISSUE TITLE
Force Guests to choose a name

### ISSUE THREAD

**Issue by trev-dev** [jitsi/docker-jitsi-meet#473]
Heya,

Just a quick question but is there a way to require people to set a name while joining? I'm using Jitsi for remote lessons, and I'm noticing parents/students are signing in anonymously and are often camera shy. I have to interrupt the lesson to work at who that person is and it's freaked me out enough to setup authenticated sessions, and next week I'll probably set a password for the session to make sure only parents/students can get in...but adding more steps to the process makes it harder for people to show up.

The more I think about this the more I realize it's a trivial problem but I don't want randos in these sessions.

**Comment by miguelpeixe** [comment]
The `config.js` contains the setting `requireDisplayName`, which you can set to true. This file is located at your web config files (`~/.jitsi-meet-cfg/web/config.js`). You change it directly, since its not available as an env variable.

**Comment by trev-dev** [comment]
Thank you!
