### ISSUE TITLE
Using Jitsi with 3rd party client

### ISSUE THREAD

**Issue by chuabingquan** [jitsi/docker-jitsi-meet#475]
Hello, is it possible to use Jitsi Meet with a 3rd party client (e.g. with Flutter through a WebRTC library)?

**Comment by sapkra** [comment]
Flutter: https://pub.dev/packages/jitsi_meet
JavaScript: https://github.com/jitsi/lib-jitsi-meet
Android: https://github.com/jitsi/jitsi-meet/blob/master/android/README.md
iOS: https://github.com/jitsi/jitsi-meet/blob/master/ios/README.md

**Comment by chuabingquan** [comment]
@sapkra could I use a custom UI instead of the default Jitsi UI?

**Comment by sapkra** [comment]
Yeah. That's possible. The Jitsi Meet UI is like a reference implementation of these SDKs.

**Comment by chuabingquan** [comment]
@sapkra thank you, I'm closing this issue now

**Comment by kleeb** [comment]
any small hints on customising the UI of flutter integration ?
like extracting each video and buttons to a separate Flutter widgets
