### ISSUE TITLE
Make jigasi completely optional

### ISSUE THREAD

**Issue by sapkra** [jitsi/docker-jitsi-meet#48]
I noticed that when I want to setup a cluster without jigasi some jigasi specific code will be executed.

For example:
```bash
prosodyctl --config $PROSODY_CFG register $JIGASI_XMPP_USER $XMPP_AUTH_DOMAIN $JIGASI_XMPP_PASSWORD
```

All `JIGASI_*` variables should be optional.
To achieve this we should implement an environment variable like `JIGASI_ENABLE`.

**Edit:**
Or maybe the following is also good enough.

```
if [[ ! -z $JIGASI_XMPP_USER ]] && [[ ! -z $JIGASI_XMPP_PASSWORD ]]; then
    prosodyctl --config $PROSODY_CFG register $JIGASI_XMPP_USER $XMPP_AUTH_DOMAIN $JIGASI_XMPP_PASSWORD
fi
```

**Comment by saghul** [comment]
Sounds good.

**Comment by saghul** [comment]
#49 landed, closing.
