### ISSUE TITLE
apt-key add should not be used

### ISSUE THREAD

**Issue by 532910** [jitsi/docker-jitsi-meet#480]
https://manpages.debian.org/buster/apt/apt-key.8.en.html says:

> **add**
> ...
> Note: Instead of using this command a keyring should be placed directly in the /etc/apt/trusted.gpg.d/ directory with a descriptive name and either "gpg" or "asc" as file extension.

Please update https://github.com/jitsi/docker-jitsi-meet/blob/master/prosody/Dockerfile and https://github.com/jitsi/docker-jitsi-meet/blob/master/jibri/Dockerfile

**Comment by saghul** [comment]
Any chance you could submit a PR?

**Comment by 532910** [comment]
yep, but next week, I hope
