### ISSUE TITLE
JVB generates high CPU usage with only one conference with three participants

### ISSUE THREAD

**Issue by BC-M** [jitsi/docker-jitsi-meet#482]
## Server
- hosted by Strato.de
- it is a dedicated Linux server

### Hardware
- Intel® Xeon E-2288G, 8 x 3.7 GHz (16 Threads)
- 64 GB RAM
- 480 GB SSD

### Software
- Ubuntu 18.04 LTS, fresh installed
- Docker version 19.03.8, build afacb8b7f0
- docker-compose version 1.25.5, build 8a1c60f6

## Configuration
- only activated HTTPS in .env-file.

## Problem description
JVB requires ~60% CPU (from one core) for a single conference with three participants. So theoretically the whole server can only hold a conference like this 25 times if JVB can use all 16 CPU threads.

On a conference with seven participants the server needs ~200% CPU.

### top (with one active three-participants conference)
![Bildschirmfoto 2020-04-18 um 23 11 06](https://user-images.githubusercontent.com/40334865/79671349-ee05f980-81c9-11ea-9761-bb7303814b5f.png)

### docker-stats -a (with one active three-participants conference)
![Bildschirmfoto 2020-04-18 um 22 55 39](https://user-images.githubusercontent.com/40334865/79671064-bb5b0180-81c7-11ea-9c8a-9d9c1692d45e.png)

## Steps to reproduce
*  setup a clean Ubuntu 18.04 LTS server
*  install docker
```
# install docker
sudo apt update
sudo apt install apt-transport-https ca-certificates curl software-properties-common -y
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
sudo apt update
apt-cache policy docker-ce
sudo apt install docker-ce -y

# install docker-compose
sudo curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

# check
docker --version
docker-compose --version
```

*  install jitsi-meet docker-project
   * Clone this repository to your computer.
      * `git clone https://github.com/jitsi/docker-jitsi-meet && cd docker-jitsi-meet`
   * Create a ``.env`` file by copying and adjusting ``env.example``
      * `cp env.example .env`
      *  enable HTTPS
      * Set strong passwords in the security section options: `./gen-passwords.sh`
   * Create required `CONFIG` directories
      * `mkdir -p ~/.jitsi-meet-cfg/{web/letsencrypt,transcripts,prosody,jicofo,jvb,jigasi,jibri}`
    * Run ``docker-compose up -d``.
* create a conference with three participants
* check `top` / `docker stats -a`

**Comment by nemaniarjun** [comment]
When JVB is installed, the Debian script adds a file for setting the sysctl options for `net.core.*`

This does not work inside docker containers as it's inherited from the host. So you need to make the changes on host.

Changes are here: https://github.com/jitsi/jitsi-videobridge/blob/master/config/20-jvb-udp-buffers.conf

**Comment by BC-M** [comment]
Thanks for your help. I made the changes. Unfortunately, the situation is unchanged.

It appears that the cpu load at this level is normal. I'll follow up on similar tickets at JVB repo.
