### ISSUE TITLE
Jitsi Meet behind an existing letsencrypt nginx?

### ISSUE THREAD

**Issue by ThomasDalla** [jitsi/docker-jitsi-meet#484]
I don't want to expose the jitsi meet web container on port 80/443 directly as my server serves many web applications that all want to do that.
Instead, I have a nginx reverse proxy (using [linuxserver:docker-letsencrypt](https://github.com/linuxserver/docker-letsencrypt/blob/master/README.md)) that serves as the entry point and redirects to desired applications internally (using subfolders in my case).

It works fine for my applications that have already an example setup, like pihole: [pihole.subfolder.conf.sample](https://github.com/linuxserver/reverse-proxy-confs/blob/master/pihole.subfolder.conf.sample)

Based on that one, I tried to setup a similar one to serve /jitsi, but it doesn't work (blank page):
```
location /jitsi {
    return 301 $scheme://$host/jitsi/;
}
location ^~ /jitsi/ {
    # enable the next two lines for http auth
    #auth_basic "Restricted";
    #auth_basic_user_file /config/nginx/.htpasswd;

    # enable the next two lines for ldap auth, also customize and enable ldap.conf in the default conf
    #auth_request /auth;
    #error_page 401 =200 /login;

    include /config/nginx/proxy.conf;
    #resolver 127.0.0.11 valid=30s;
    proxy_pass https://172.20.0.1:8444;

    rewrite /jitsi(.*) $1 break;
    proxy_hide_header X-Frame-Options;
}
```

Would it be possible to add a sample config for serving jitsi via an existing nginx instance (that uses let's encrypt already in my case, so no need for jitsi to do that part).

**Comment by ThomasDalla** [comment]
Worked with the subdomain version: `jitsi.subdomain.conf`

```
server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name jitsi.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    location / {
        # enable the next two lines for http auth
        #auth_basic "Restricted";
        #auth_basic_user_file /config/nginx/.htpasswd;

        # enable the next two lines for ldap auth
        #auth_request /auth;
        #error_page 401 =200 /login;

        include /config/nginx/proxy.conf;
        proxy_pass https://172.20.0.1:8444;

        proxy_hide_header X-Frame-Options;
    }
}
```

Very custom as I hardcode the proxy_pass but can be adapted.

**Comment by con-f-use** [comment]
Hi also very interested in that, just not sure where `/config/nginx/ssl.conf` and `/config/nginx/proxy.conf` come from. Be so kind and elaborate, please.

**Comment by ThomasDalla** [comment]
As I'm using [linuxserver:docker-letsencrypt](https://github.com/linuxserver/docker-letsencrypt/blob/master/README.md), these come for free in my case.

More info on the [reverse-config-confs](https://github.com/linuxserver/reverse-proxy-confs/blob/master/README.md) GitHub

**Comment by con-f-use** [comment]
Okay thanks, they are here:
https://github.com/linuxserver/docker-letsencrypt/blob/master/root/defaults/ssl.conf
https://github.com/linuxserver/docker-letsencrypt/blob/master/root/defaults/proxy.conf
