### ISSUE TITLE
I want to ask why the body with id = react under index.html has no content. I want to change this code.

### ISSUE THREAD

**Issue by whr845736938** [jitsi/docker-jitsi-meet#487]
I want to ask why the body with id = react under index.html has no content. I want to change this code.

**Comment by sapkra** [comment]
Because it's the div where the react app will be mounted. The DOM is generated out of javascript.

https://github.com/jitsi/jitsi-meet/blob/5a934c071a5cbe64de275a25d0ed62d8193cdd03/react/index.web.js#L25

**Comment by whr845736938** [comment]
Then I want to change the code, is there no way, right?

**Comment by sapkra** [comment]
You can fork it and change the code of cause.

This may help you: https://github.com/jitsi/docker-jitsi-meet/issues/327#issuecomment-612486937

**Comment by Echolon** [comment]
@whr845736938 would you be so kind and provide a more clear and shorter title?

@sapkra close?
