### ISSUE TITLE
[Jicofo] Special char in environment variables

### ISSUE THREAD

**Issue by noe-charmet** [jitsi/docker-jitsi-meet#488]
Hello,
I have been setting up a Jicofo server, using randomly generated passwords. The container would crash on launch. Looking at the logs, the '&' character in the passwords was interpreted by the shell as a command separator. I looked into the codebase and I guess that this script would `jicofo/rootfs/etc/services.d/jicofo/run` need to have quoting around the environment variables.

I'm not really familiar with Java so I'm not sure if the software itself would be able to interpret it correctly after that.
I could make a PR if you think that this is sufficient.

Best regards

**Comment by saghul** [comment]
Did you type the password by hand? The gen-passwords helper shouldn't have generated that.

**Comment by noe-charmet** [comment]
Yes, it's a password generated by a third party tool that is added to the env var at deployment time

**Comment by saghul** [comment]
I see. Yeah, quoting should fix it. Care to send a PR?

**Comment by noe-charmet** [comment]
Sure, i'll test it and offer a PR in the next few days
