### ISSUE TITLE
It is not possible to run jvb in Docker behind NAT

### ISSUE THREAD

**Issue by JakubOnderka** [jitsi/docker-jitsi-meet#492]
Hello,

my network setup is like this:

* Docker container IP with jvb: 172.18.0.3
* Machine internal IP: 10.0.1.3
* Machine public IP: 3.3.3.3

Problem is, that `jvb` always announce docker container IP that is not reachable outside of Docker world. 

The second problem is that I cannot announce both machine internal and public IP, `DOCKER_HOST_ADDRESS` just accept one address.

How to fix this:
* Allow to specify exact IP address, that will jvb announce or
* Allow to add multiple IP address in `DOCKER_HOST_ADDRESS` variable.

Thanks.

**Comment by j2l** [comment]
It works fine for me, same setup.
`DOCKER_HOST_ADDRESS` is for your public address.
I had to tweak my internet router/fw to allow 80, 443 (TCP) and 10000 (UDP) from outside.
JVB needs SSL too, getting valid certificates is dependent of your registrar and DNS.

**Comment by saghul** [comment]
You can set DOCKER_HOST_ADDRESS to your private IP, and STUN should be able to find your public one. (it's enabled by default)

**Comment by bilalshahzad139** [comment]
> It works fine for me, same setup.
> `DOCKER_HOST_ADDRESS` is for your public address.
> I had to tweak my internet router/fw to allow 80, 443 (TCP) and 10000 (UDP) from outside.
> JVB needs SSL too, getting valid certificates is dependent of your registrar and DNS.

@j2l So it means we can't hold conference of more than 2 people without having valid SSL or domain with SSL?

**Comment by saghul** [comment]
That has nothing to with SSL. You must be on a seure domain otherwise the browser itself disables WebRTC features.

**Comment by saghul** [comment]
Also, I realize this got no follow-up, so closing for now.

**Comment by shubham2110** [comment]
Hi Saghul,

Is it possible to run JVB in Docker behind NAT. I don't want to use STUN server. 
I want to use only JVB with UDP port.
