### ISSUE TITLE
Security headers are not set for HTTP version

### ISSUE THREAD

**Issue by JakubOnderka** [jitsi/docker-jitsi-meet#493]
For `jitsi/web` container, two security headers:
* `X-Content-Type-Options` and
* `X-XSS-Protection` 

are set just in for ssl version.

https://github.com/jitsi/docker-jitsi-meet/blob/d44230e2b121e72542a60b6dfbce9b07e84ed706/web/rootfs/defaults/ssl.conf#L23-L24

 So if somebody uses HTTPS reverse proxy in front of this container, these headers are not set. They should be moved to https://github.com/jitsi/docker-jitsi-meet/blob/master/web/rootfs/defaults/meet.conf file.

**Comment by saghul** [comment]
Sounds reasonable. Care to send a PR?
