### ISSUE TITLE
Using CodiMD in place of etherpad.

### ISSUE THREAD

**Issue by sunjam** [jitsi/docker-jitsi-meet#494]
Hi, I'm curious on if anyone has replaced etherpad with [codimd](https://github.com/codimd/server).  Here is the [etherpad-lite migration guide](https://hackmd.io/c/codimd-documentation/%2Fs%2Fcodimd-migration-etherpad).

**Comment by saghul** [comment]
Support for it would be nedded on Jitsi Meet. Please feel free to start a disussion on our forum: https://community.jitsi.org/

**Comment by vmario89** [comment]
looking for this feature too. We use Jitsi and CodiMD instead Etherpad. I tried to configure "etherpad_base" to use CodiMD. Rendering works fine but the special handling does not work. So somebody needs to add code into Jitsi Meet.
