### ISSUE TITLE
No Time Counter in docker-jitisi-meet ?

### ISSUE THREAD

**Issue by JacBra** [jitsi/docker-jitsi-meet#496]
The latest release includes a time counter for conferences shown in the middle top of the video, so I have read (it is also visible on meet.jit.si). However, I can't find it in my (recent) docker-jitsi-meet setup. Am I missing something here, or is it indeed missing here?

**Comment by saghul** [comment]
It reliess on a Prosody module which is not currently enabled in the Docker setup. I'll try to squeeze than in for the enxt release.

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/docker-jitsi-meet/commit/3c3fc195d158a1e513e818ee1b831e0f13f88bca

**Comment by JacBra** [comment]
Thanks a lot saghul! Just a newbie question: I saw that it was merged in the master branch. When will this be pushed to the docker hub? Is that an automated process like a nightly build?

**Comment by saghul** [comment]
I'll make a new stable release this week.

**Comment by JacBra** [comment]
Thanks in advance. (When I build the containers for myself (make), the prosody container won't build.)

**Comment by saghul** [comment]
What error do you get?

**Comment by JacBra** [comment]
Installing https://luarocks.org/cyrussasl-1.1.0-1.rockspec
Cloning into 'lua-cyrussasl'...
fatal: unable to connect to github.com:
github.com[0: 140.82.118.4]: errno=Connection timed out

Error: Failed cloning git repository.

In my firewall log, I noticed dropped traffic to 140.82.118.4 on port tcp/9418.
We have the git protocol blocked by default. I don't know if this is within your influence but why not using ssh or https for this git cloning?

**Comment by saghul** [comment]
That's luarocks doing it's thing, if you know a way to disable it I'd be happy to add it!

**Comment by JacBra** [comment]
Thanks saghul for all your quick answers! The counter is visible now (I opened tcp/9418 in our firewall and was able to build the docker image). I have one strange thing though: when I start a new meeting it starts the counter with 0:00:00. After 1 second it changes to 1:00:03 and then starts counting upwards. Is this a known issue perhaps? Could it be a timezone thing?

**Comment by saghul** [comment]
I thhink this was fixedd in master, though not released yet. You can change the timezone in your env file to UTC and it will work properly.

**Comment by JacBra** [comment]
thanks!
