### ISSUE TITLE
in absent of $JVB_TCP_MAPPED_PORT in .env startup fails

### ISSUE THREAD

**Issue by kinafu** [jitsi/docker-jitsi-meet#497]
I just upgraded (`docker-compose pull`) my installation and updated `git pull` this repo, but did not modify my .env.

Upon restart it says:
```
WARNING: The JVB_TCP_MAPPED_PORT variable is not set. Defaulting to a blank string.
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.jvb.ports is invalid: Port ranges don't match in length
```

After manually setting `JVB_TCP_MAPPED_PORT ` in my `.env` everything worked like before.

I guess there's no default value deposed for the `JVB_TCP_MAPPED_PORT`.
Or it is just something with my installation, I did not check much further.

**Comment by saghul** [comment]
Oops, I added it to the example file just now: https://github.com/jitsi/docker-jitsi-meet/commit/f911df2a427a5f4ebddd79a78c16412e396d7bff Thanks for the report!
