### ISSUE TITLE
secure domain config via docker-compose  / .env setup for restricting guest usage

### ISSUE THREAD

**Issue by devZer0** [jitsi/docker-jitsi-meet#507]
Hello, 
how can i setup docker-jitsi-meet to reflect "secure domain" feature ? 

i want that my jitsi server on the internet cannot be abused by "anybody on the net" as a video conferencing system.

i want a larger private community be able to run video conferencing sessions but it would be hindering to provide a username+password to everybody, i.e. there should be "priviledged" users who are able to create rooms and then share the secret room url with any other community internal or external user.

at https://github.com/jitsi/jicofo under "secure domain" there is a description how to setup such, but i don't want to touch docker-compose genrated configuration afterwards which may get lost

is there a way via .env or could you add such feature ?

thank you
roland

**Comment by please-wait** [comment]
See authentication section in the readme here: https://github.com/jitsi/docker-jitsi-meet#authentication

that part is exactly what you want. Make credentials for your "privileged" users and they are the only people who can get a room going.

**Comment by devZer0** [comment]
sorry, it was my fault, i did test the wrong way and did not recognize that credentials for login being cached on the client

**Comment by serfer2** [comment]
> See authentication section in the readme here: https://github.com/jitsi/docker-jitsi-meet#authentication
> 
> that part is exactly what you want. Make credentials for your "privileged" users and they are the only people who can get a room going.

Hi, I've been looking for documentation, in order to make credentials for privileged users. But seems to be missing at `https://github.com/jitsi/docker-jitsi-meet#authentication`.  
If you can help me finding how to configure it in docker-jitsi-meet, I really would appreciate your help.

Regards :smiley:

**Comment by please-wait** [comment]
As it points out in the readme, they have moved the installation docs here: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker

**Comment by serfer2** [comment]
> As it points out in the readme, they have moved the installation docs here: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker

Thanks for your quick response. 
I saw the guide. I think [Secure domain configuration instructions](https://jitsi.github.io/handbook/docs/devops-guide/secure-domain) are good for a regular installation, not for docker-jitsi-meet. After destroying docker containers, all config files will be lost. So I guess that modifying `.env` file will do the trick, but not sure how to configure `.env` vars to do that.

**Comment by filwu8** [comment]
you can create custom-jitsi-meet.cfg.lua   in  jitsi-meet-cfg\prosody\config\conf.d\custom-jitsi-meet.cfg.lua

**Comment by AlbanDAVID** [comment]
I also had some issues with docker compose to secure domain.

This article helped me a lot : https://medium.com/@GuzmanBenjamin/set-up-a-self-hosted-video-conference-server-jitsi-383e433f3f06

In fact, when you install prosody with docker container, you don't have to configure each configuration files as mentioned in this link https://jitsi.github.io/handbook/docs/devops-guide/secure-domain/ 
You just have to configure .env file.

Step 1 : follow instruction to install jitsi : https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker/
Step 2 : open .env and and uncomment ENABLE_AUTH=1 and ENABLE_GUESTS=1
Step 3 : going inside prosody container (ex : sudo docker exec -it prosody_container-name /bin/bash
Step 3.1 :Create a new user :  prosodyctl --config /config/prosody.cfg.lua register <username> meet.jitsi <password>
It's not necessary to change "meet.jitsi"  with your hostname. 
Step 4 : docker-compose up -d
