### ISSUE TITLE
Jibri: Failed to read the ‘localStorage’ property from ‘Window’: Access is denied for this document.

### ISSUE THREAD

**Issue by nestorconde** [jitsi/docker-jitsi-meet#508]
After following the instructions in the README in a digital ocean Ubuntu 18.04.3 (LTS) x64. When the user clicks in the browser to start the recording he sees a message stating: “Recording Failed to Start”

When analyzing the logs in log.0.txt this line stands out as a SEVERE error:

> 2020-04-22 12:42:55.159 SEVERE: [71] org.jitsi.jibri.selenium.JibriSelenium.run() An error occurred while joining the call: org.openqa.selenium.WebDriverException: : Failed to read the ‘localStorage’ property from ‘Window’: Access is denied for this document.
(Session info: chrome=81.0.4044.113)

I also posted about this issue in https://community.jitsi.org/t/issue-with-recording-installation-of-docker-jitsi-meet-with-jibri-recording-failed-to-start/41613, not sure whether it's more appropiate to submit an issue or create a post for this type of problem. I could post here the whole log that I already posted there if it can help.

**Comment by netaskd** [comment]
related to #240 ?

**Comment by nestorconde** [comment]
I think you are right, I close this while investigating it since I think it's probably just a duplicate. I'll also reference #240 in community.jitsi.org. Thanks!
