### ISSUE TITLE
Self-hosted XMPP

### ISSUE THREAD

**Issue by WyseNynja** [jitsi/docker-jitsi-meet#509]
I was looking through the configs and noticed that docker-jitsi-meet defaults to using xmpp.meet.jitsi and some other meet.jitsi domains. 

I would really prefer the entirety of my communications to be self hosted. Are there steps for running my own XMPP server and configuring docker-jitsi-meet to use it?

I'm guessing OTR is used for everything and so a shared server should be safe. But I want to be sure.

**Comment by sapkra** [comment]
These are just internal aliases. Evetything is hosted by yourself except the TURN server which is still WIP but it's already possible.

FYI: prosody is the xmpp server

**Comment by WyseNynja** [comment]
Aha. that makes sense. thank you!
