### ISSUE TITLE
Problem with 3 and more participants

### ISSUE THREAD

**Issue by maraism** [jitsi/docker-jitsi-meet#517]
Hy, 

I use docker-jitsi-meet on our self-hosted server. it's ok for 2 participants but with more I have no camera and no microphone. 
I have set DOCKER_HOST_ADDRESS with ou public IP but it's not resolve. 

Would you have a solution ?

Thank's.

**Comment by laurenceaa** [comment]
Hello@maraism, I saw that I closed the issue. How did you solve the problem?
