### ISSUE TITLE
Recording problem

### ISSUE THREAD

**Issue by djarril** [jitsi/docker-jitsi-meet#520]
Hello...

I installed docker-jitsi-meet on a single server and it's working fine. 
When I try the option 
ENABLE_RECORDING=1
A problem occurs.
XMPP_DOMAIN=meet.intranet.mydomain.net 
is the name of my server and obviously the URL (my internet domain is intranet.mydomain.net)
As Jibri allways wants to strip the domain with a container, it never works.
Even if I clear the option
JIBRI_STRIP_DOMAIN_JID=
witch generates an error.

It's then impossible for Jibri to retreive the link
https://meet.intranet.mydomain.net/room
from
root@meet.intranet.mydomain.net.

Is there a possibility to add an option like : 
SINGLE_SERVER=1
or can jibri ignore the stripping in case of null JIBRI_STRIP_DOMAIN_JID option ?
With this kind of configuration on single server, everything should work.

Thanks for this amazing product
Best regards

**Comment by saghul** [comment]
Please try the latest images, they contains fix made specifically to address recording problems.
