### ISSUE TITLE
Internal authenicaion stores passwords as plain text

### ISSUE THREAD

**Issue by Ladsgroup** [jitsi/docker-jitsi-meet#523]
Currently I maintain a jitsi docker setup and its authentication is "internal". I have root rights and I was checking the files of the config volume and I found all of the users and the passwords in plain text stored in .jitsi-meet-cfg/prosody/data/meet%2ejitsi/accounts

Can this be encrypted with one of the secret keys set at the beginning so I would be able to migrate and backup users data?

(btw. I'm sorry if it's a duplicate or I'm making an issue against wrong repo).

**Comment by saghul** [comment]
We have since switched to `internal_hashed`.
