### ISSUE TITLE
[web] Make watermark customizable using environment variables

### ISSUE THREAD

**Issue by ludovicm67** [jitsi/docker-jitsi-meet#527]
It could be really useful if the watermark can be customized using environment variables, for example:
 - `WEB_WATERMARK_IMAGE`: the watermark can be an other internal path or a complete url to a logo which is hosted outside of the container, like on a CDN for example.
 - `WEB_WATERMARK_LINK`: the link where the user will be redirected after clicking on the watermark.

**Comment by dinigo** [comment]
hi. I opened a similar issue some time ago that got transfered to the jitsi web repo 

https://github.com/jitsi/adocker-jitsi-meet/issues/301
