### ISSUE TITLE
Graceful_shutdown script can not be run, as curl, jq are missing in videobridge container

### ISSUE THREAD

**Issue by mvakert** [jitsi/docker-jitsi-meet#535]
There is a graceful_shutdown.sh script in usr/share/jitsi-videobridge in the JVB-container which can't be run as the dependencies curl and jq are not installed. However, this script can probably be used for scaling the JVBs.

**Comment by nyok92** [comment]
Yes,and  jq is missing too in jibri (to make dropbox integration works)

**Comment by saghul** [comment]
Good points, care to send a PR?

**Comment by MatthewCroughan** [comment]
@saghul The jibri.yml in the releases and repo uses the Docker Hub image for Jibri rather than the local dockerfile in the repository. When we modify the dockerfile for Jibri in this repo, does that update the Dockerhub image also?

**Comment by sapkra** [comment]
@MatthewCroughan When the Dockerfile is changed in the master branch it will be used to build the new images for DockerHub. This will not happen automatically but after saghul manueally released a new version (which he is doing regularly).

**Comment by MatthewCroughan** [comment]
@sapkra Excellent. Do you think we should add a new layer in the Dockerfile to add the integrations, or do you think that it should go in the layer described here?

https://github.com/jitsi/docker-jitsi-meet/blob/2d063ad162370b600aa5d986aaebbe2cd8bf435d/jibri/Dockerfile#L9-L12

I see that the integrations are installed, but it is interesting that all of the dependencies required by the bash scripts in those integrations are not included. Perhaps it should be included on this layer?

https://github.com/jitsi/docker-jitsi-meet/blob/2d063ad162370b600aa5d986aaebbe2cd8bf435d/jibri/Dockerfile#L40-L45
