### ISSUE TITLE
docker-jitsi-meet problem

### ISSUE THREAD

**Issue by kashifsaeed79** [jitsi/docker-jitsi-meet#541]
I install jisti-meet via docker 
two container in Jitsi-meet restart again again

- Jitsi/Jvb
- Jitsi/Jicofo
Command Line Error:
![jitsi error](https://user-images.githubusercontent.com/31384726/80869320-3a1c6800-8cb9-11ea-984f-ba7b1e2d213a.JPG)

Front End Error:
![jitsi error front end](https://user-images.githubusercontent.com/31384726/80869401-a5663a00-8cb9-11ea-9984-2abe90debe91.JPG)

**Comment by lawzava** [comment]
same issue.

**Comment by ccoenen** [comment]
did you run the setup script that generates the internal passwords? `./gen-passwords.sh` in the project's root directory.

also `docker-compose logs` could give you more insight into what went wrong.

**Comment by RoderickVM** [comment]
> I install jisti-meet via docker
> two container in Jitsi-meet restart again again
> 
> * Jitsi/Jvb
> * Jitsi/Jicofo
>   Command Line Error:
>   ![jitsi error](https://user-images.githubusercontent.com/31384726/80869320-3a1c6800-8cb9-11ea-984f-ba7b1e2d213a.JPG)
> 
> Front End Error:
> ![jitsi error front end](https://user-images.githubusercontent.com/31384726/80869401-a5663a00-8cb9-11ea-9984-2abe90debe91.JPG)

The way I fixed it was to delete the entire jitsi-meet-cfg folder. Then created the empty folders again: 
`mkdir -p ~/.jitsi-meet-cfg/{web/letsencrypt,transcripts,prosody,jicofo,jvb,jigasi,jibri}`. Finally, ran `docker-compose up -d`.

**Comment by saghul** [comment]
@RoderickVM any change in the values in the .env file requires a full config wipe. This is not ideal, but it is documented in the README.

**Comment by hophat** [comment]
![image](https://user-images.githubusercontent.com/21335957/99365626-200b4580-28ea-11eb-9b73-e4500770a55a.png)
![image](https://user-images.githubusercontent.com/21335957/99365651-28fc1700-28ea-11eb-9dc3-cf26be18dbca.png)
![image](https://user-images.githubusercontent.com/21335957/99365725-40d39b00-28ea-11eb-9718-b57513ce177d.png)
![image](https://user-images.githubusercontent.com/21335957/99365796-534dd480-28ea-11eb-88b7-5a5fe690932e.png)


I also have a similar problem. Please need help.
No error messages occurred. But it doesn't work

**Comment by ccoenen** [comment]
@hophat I do not believe that your problem is at all related to this issue here. If I had to guess from the screenshots:
- this will deploy to ports 80 and 443 (not port 8443!)
- your iptables or firewall may also interfere
- `docker-compose logs` might also give you clues what went wrong

**Comment by hophat** [comment]
Many thanks for helping me.
I just learned about docker + server and the project was urgent. I configured port 8443 and 8000. I saw the log appear as shown.
Hope you can help me
![image](https://user-images.githubusercontent.com/21335957/99483946-eb52c900-2991-11eb-8d2d-b597feee1a15.png)

**Comment by hophat** [comment]
![image](https://user-images.githubusercontent.com/21335957/99484005-0ae9f180-2992-11eb-895f-495fc6a71d41.png)
