### ISSUE TITLE
REST API access

### ISSUE THREAD

**Issue by ptrxyz** [jitsi/docker-jitsi-meet#544]
Hello!

I setup a nice and working environment using this container, however I really do not know how to access the API. usually I should be able to access it using doamin.com:8080/colibri/about/health (According to the docs) but I don't think that port is getting forwarded in the container.
I enabled rest,colibri in the env file (JVB_ENABLE_APIS=rest,colibri).

What do I do wrong? Can I somehow configure the jvb and set a nother port which the container then can expose?

**Comment by sapkra** [comment]
Can you create a PR which will add them to the docker compose file or to the docs? They are just missing there.

### Ports for REST APIs
JVB: `8080`
Jicofo: `8888`

**Comment by prayagsingh** [comment]
its `curl -v domain_name:8080/about/health` for `JVB`

**Comment by sapkra** [comment]
I don't know. I'm just using the http code to check the health of a service.

**Comment by tux-00** [comment]
Same here, I enabled `JVB_ENABLE_APIS=rest,colibri` in the env file and added to the compose file but nothing happens, the path `http://localhost:8080/colibri/stats` still returning 404.

**Comment by sapkra** [comment]
@tux-00 `COLIBRI_REST_ENABLED=true` is the new variable
