### ISSUE TITLE
jitsi-upload-integrations aren't installed in Jibri despite dockerfile definition?

### ISSUE THREAD

**Issue by MatthewCroughan** [jitsi/docker-jitsi-meet#548]
I'm really confused, it seems that the jitsi-upload-integrations really aren't present in any version of Jibri and have not been for some time despite the definition being clear here:

https://github.com/jitsi/docker-jitsi-meet/blob/2d063ad162370b600aa5d986aaebbe2cd8bf435d/jibri/Dockerfile#L40-L45

Is this a consequence of the silly `|| true` which allows this to build without failure? Why has this been done? This seems to be a longstanding issue that people are really pulling their hair out over. 

https://community.jitsi.org/t/need-help-with-dropbox-integration/17896/19

When we do figure out why there's a `|| true`, can we please comment this into the dockerfile so people have some clue as to why this is defined but non functional?

**Comment by sapkra** [comment]
> Is this a consequence of the silly || true which allows this to build without failure?

It is basically an inline `if` statement. So if `JITSI_RELEASE` is `stable` for example the build would fail if `true` is not returned.

The main question is why @netaskd added `jitsi-upload-integrations` just for `unstable` builds.

**Comment by saghul** [comment]
Let's install them for everyone. A PR would be welcome!

**Comment by MatthewCroughan** [comment]
@mesouug I'm thankful that you've removed the `|| true` as I believe this to be a hack that defeats the purpose of the docker build system, but I feel that the removal of `[ "$JITSI_RELEASE" = "unstable" ] \` is improper, as it probably exists there for a reason. If we set `unstable` to `stable` will this not have the same effect? I have created #553 to address these questions, as the importance of these variables or what they exist for is not precisely described anywhere and is necessary for contributing.

**Comment by mesouug** [comment]
@MatthewCroughan Just followed suggestion from @saghul 
> Let's install them for everyone.

I though that If I change from *unstable* to *stable* that will break compatibility for *unstable*. Which is kinda pointless.

**Comment by saghul** [comment]
@MatthewCroughan I'd be ok with removing the check altogether.

**Comment by MatthewCroughan** [comment]
I see, I thought this may be for some sort of build system that is undocumented, or some other concept that is not explained. I was just wary, as every other RUN layer contains some sort of variable.

**Comment by mesouug** [comment]
@saghul Do you mean to remove lines 4,5,15,21,24,29,32,38,41,45 from https://github.com/jitsi/docker-jitsi-meet/blob/2d063ad162370b600aa5d986aaebbe2cd8bf435d/jibri/Dockerfile ?

**Comment by saghul** [comment]
No, just the checks for JITSI_RELEASE, the CHROME_RELEASE checks are independent.

**Comment by mesouug** [comment]
@saghul This is what PR does. Unless you want to remove it everywhere from project. Which I don't think is good idea.

**Comment by netaskd** [comment]
Please, pay atention, integration tools still is not avalable from the stable repo.

**Comment by saghul** [comment]
Oh I may have forgotten about that. I’ll check and make sure they are.

**Comment by damencho** [comment]
> Oh I may have forgotten about that. I’ll check and make sure they are.

It is now in stable.
