### ISSUE TITLE
nginx issue when starting project

### ISSUE THREAD

**Issue by legrandjeremy** [jitsi/docker-jitsi-meet#55]
Hello,

I tried to start the project on a Mac with Docker, I followed this comment https://github.com/jitsi/docker-jitsi-meet/issues/16#issuecomment-432158782 in order to have a fresh install of jitsi.

Unfortunatelly I have an issue with nginx : 

![image](https://user-images.githubusercontent.com/3063650/52077723-edb41b00-2591-11e9-9155-68c0ed70e94e.png)

When I go to localhost:8000 I have "connection refused" issue.

Thanks in advance for any help,

**Comment by netaskd** [comment]
You see it because certificate dhparams.pem was not builded correctly.
try to remove `$CONFIG/web/nginx/dhparams.pem`, restart, and wait about 10 sec
