### ISSUE TITLE
How to change the logo with jitsi/web

### ISSUE THREAD

**Issue by cs35-owncloud** [jitsi/docker-jitsi-meet#551]
Hello everyone,

I'm running a docker-jitsi-meet instance and I'd like to change the jitsi logo of the jitsi/web docker.
I know it's in **/usr/share/jitsi-meet/** but sadly the [Dockerfile](https://github.com/jitsi/docker-jitsi-meet/blob/master/web/Dockerfile) doesn't expose it to the host.
Is there any reason not to set as a volume **/usr/share/jitsi-meet/** so one could change the logo or other things ?
I tried to change the docker composer of jitsi/web to export **/usr/share/jitsi-meet/** but it simply crashes the container.
I know one could simply build its own jitsi/web with the ressources but I'd prefer the volume export version for simplicity.
If anyone has an idea :)
Thanks.

**Comment by mesouug** [comment]
Maybe a little bit hacky and not cool but I solved it by mounting watermark.png as volume in docker-compose.yml
```version: '3'

services:
    # Frontend
    web:
        image: jitsi/web
        restart: ${RESTART_POLICY}
        ports:
            - '${HTTP_PORT}:80'
            - '${HTTPS_PORT}:443'
        volumes:
            - ${CONFIG}/web:/config:Z
            - ${CONFIG}/web/letsencrypt:/etc/letsencrypt:Z
            - ${CONFIG}/transcripts:/usr/share/jitsi-meet/transcripts:Z
            - ./watermark.png:/usr/share/jitsi-meet/images/watermark.png
```

**Comment by cs35-owncloud** [comment]
Hello @mesouug 

thanks ! It's indeed not the nicest solution, but it works well !
I tried to share the whole **/usr/share/jitsi-meet/** but it didn't work so I didn't think about just sharing one item, nice trick.
Did you change some other items like that in your docker-compose.yml ?
Thanks again :)

**Comment by mesouug** [comment]
> Did you change some other items like that in your docker-compose.yml ?

Nope.

**Comment by cs35-owncloud** [comment]
Alrighty then, thanks for your help :)
I'll keep this issue opened if there is any other solutions.

**Comment by prayagsingh** [comment]
Other option is to edit the `css.all` file and then execute `docker image build -t image_name .` inside `web` directory. 
STEPS:
1. Copy `css.all` file present in `usr/share/jitsi-meet/css/` directory from web container to your local machine using `docker cp docker-jitsi-meet_web_1:/usr/share/jitsi-meet/css/css.all ./web` command.
2. Change `background-image:url("https://logo-regis.png")` in `css.all` file. 
3. Build docker image by modifying `Dockerfile` inside `web` directory. 
```
ARG JITSI_REPO=jitsi
FROM ${JITSI_REPO}/base

ADD https://dl.eff.org/certbot-auto /usr/local/bin/

COPY rootfs/ /

RUN \
	apt-dpkg-wrap apt-get update --fix-missing && \
	apt-dpkg-wrap apt-get install -y cron nginx-extras jitsi-meet-web && \
	apt-dpkg-wrap apt-get -d install -y jitsi-meet-web-config && \
        dpkg -x /var/cache/apt/archives/jitsi-meet-web-config*.deb /tmp/pkg && \
        #mv /tmp/pkg/usr/share/jitsi-meet-web-config/config.js /defaults && \
	#mv /usr/share/jitsi-meet/interface_config.js /defaults && \
	apt-cleanup && \
	rm -f /etc/nginx/conf.d/default.conf && \
	rm -rf /tmp/pkg /var/cache/apt

RUN \
	chmod a+x /usr/local/bin/certbot-auto && \
	certbot-auto --noninteractive --install-only

# copying css file from local
COPY css/all.css /usr/share/jitsi-meet/css/all.css

EXPOSE 80 443

VOLUME ["/config", "/etc/letsencrypt", "/usr/share/jitsi-meet/transcripts"]
```
4. Execute `docker image build -t web:v1 .`
5. change the image name to `web:v1` in `docker-compose.yaml` file
I followed this approach because I did some modification in `interface_config.js` and `config.js` files too.

**Comment by cs35-owncloud** [comment]
Hello @prayagsingh 

thanks for your answer ! It's nice to have several options :)
In my case it's a bit complicated to use this one since I might have to create many Jitsi with different watermarks. It would mean I have to build a web image for each watermark which is not very practical.
Nevertheless your approach gives the ability to modify everything needed.
I wish the "official" web image expose **/ usr/share/jitsi-meet** some day to ease the customisation with docker.
It's nice to have constructive answers :)
Thanks again.

**Comment by spprod35** [comment]
> 1. docker cp docker-jitsi-meet_web_1:/usr/share/jitsi-meet/css/css.all

Hi, thank for this method.
I comment just for EDIT, After 3 hours of work to find out why "docker cp" does not work 👍 
Edit : docker cp docker-jitsi-meet_web_1:/usr/share/jitsi-meet/css/css.all
To : docker cp docker-jitsi-meet_web_1:/usr/share/jitsi-meet/css/**all.css**

But thank you for your method it is magic

**Comment by BlackLanzer** [comment]
> Maybe a little bit hacky and not cool but I solved it by mounting watermark.png as volume in docker-compose.yml
> 
> ```
> 
> services:
>     # Frontend
>     web:
>         image: jitsi/web
>         restart: ${RESTART_POLICY}
>         ports:
>             - '${HTTP_PORT}:80'
>             - '${HTTPS_PORT}:443'
>         volumes:
>             - ${CONFIG}/web:/config:Z
>             - ${CONFIG}/web/letsencrypt:/etc/letsencrypt:Z
>             - ${CONFIG}/transcripts:/usr/share/jitsi-meet/transcripts:Z
>             - ./watermark.png:/usr/share/jitsi-meet/images/watermark.png
> ```

I tried to use this, but then /usr/share/jits-meet/images lose all the images. Only watermark.png stay in the folder.

Does anyone know why this happen?

**Comment by cs35-owncloud** [comment]
Hello,

well I'm not sure but it could be because you don't use the ${CONFIG} there. Where's your watermark located on the host ?In my case I put it in my ${CONFIG} directory.

`        volumes:
            - ${CONFIG}/web:/config:Z
            - ${CONFIG}/web/letsencrypt:/etc/letsencrypt:Z
            - ${CONFIG}/transcripts:/usr/share/jitsi-meet/transcripts:Z
            - ${CONFIG}/watermark.png:/usr/share/jitsi-meet/images/watermark.png`

And it works fine, I have my watermark.png and the other pictures stay there.
Cheers.

**Comment by tronics** [comment]
Hello @prayagsingh,

This is very well documented, but it does not work for me to make any changes.
Jitsy works well, but none of my settings get incorporated when I start the container.

I want to use my own:
- CSS file (for the Logo) 
- config.js
- interface-config.js
- include vim in the image

Copying the files from the image to the host computers filesystem worked well (docker cp docker-jitsi-meet_web_1:/usr/share/jitsi-meet/css/all.css .)
But when starting the dockerimage the new files are not copied back.

Also in your example:
docker image build -t web:v1 command does not work. 
docker image build -t web:latest ./web command works, but does not bring the result and returns this:
`Download complete and in download only mode
Removing intermediate container d4001f86df4f
 ---> b5c17537669d
Step 5/14 : RUN         chmod a+x /usr/local/bin/certbot-auto &&        certbot-auto --noninteractive --install-only
 ---> Running in 07dbe77ecd03
Skipping bootstrap because certbot-auto is deprecated on this system.
WARNING: couldn't find Python 2.7+ to check for updates.
Your system is not supported by certbot-auto anymore.
Certbot cannot be installed.
Please visit https://certbot.eff.org/ to check for other alternatives.
The command '/bin/sh -c chmod a+x /usr/local/bin/certbot-auto &&        certbot-auto --noninteractive --install-only' returned a non-zero code: 1
`

--

dockerfile
`
ARG JITSI_REPO=jitsi
FROM ${JITSI_REPO}/base

ADD https://dl.eff.org/certbot-auto /usr/local/bin/

RUN \
	apt-dpkg-wrap apt-get update && \
	apt-dpkg-wrap apt-get install -y cron nginx-extras jitsi-meet-web && \
	apt-dpkg-wrap apt-get -d install -y jitsi-meet-web-config && \
	apt-dpkg-wrap apt-get -d install -y jitsi-meet-web-config && \
	**apt-dpkg-wrap apt-get -d install vim -y && \**
    dpkg -x /var/cache/apt/archives/jitsi-meet-web-config*.deb /tmp/pkg && \
    mv /tmp/pkg/usr/share/jitsi-meet-web-config/config.js /defaults && \
	mv /usr/share/jitsi-meet/interface_config.js /defaults && \
	apt-cleanup && \
	rm -f /etc/nginx/conf.d/default.conf && \
	rm -rf /tmp/pkg /var/cache/apt

RUN \
	chmod a+x /usr/local/bin/certbot-auto && \
	certbot-auto --noninteractive --install-only

COPY rootfs/ /

**COPY all.css /usr/share/jitsi-meet/css/all.css
COPY config.css /config/config.js
COPY interface-config.css /config/interface-config.js**

EXPOSE 80 443

VOLUME ["/config", "/etc/letsencrypt", "/usr/share/jitsi-meet/transcripts"]
`
yaml file:

`version: '3'

services:
    # Frontend
    web:
        **image: jitsi/web:latest**
        restart: ${RESTART_POLICY}
        ports:
            **- '101.68.45.101:80:80'
            - '101.68.45.101:443:443'**
        volumes:
            - ${CONFIG}/web:/config:Z
            - ${CONFIG}/web/letsencrypt:/etc/letsencrypt:Z
            - ${CONFIG}/transcripts:/usr/share/jitsi-meet/transcripts:Z
        environment:
            - ENABLE_AUTH
            - ENABLE_GUESTS
            - ENABLE_LETSENCRYPT
            - ENABLE_HTTP_REDIRECT
            - ENABLE_TRANSCRIPTIONS
            - DISABLE_HTTPS
            - JICOFO_AUTH_USER
            - LETSENCRYPT_DOMAIN
            - LETSENCRYPT_EMAIL
            - PUBLIC_URL
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_BOSH_URL_BASE
            - XMPP_GUEST_DOMAIN
            - XMPP_MUC_DOMAIN
            - XMPP_RECORDER_DOMAIN
            - ETHERPAD_URL_BASE
            - ETHERPAD_PUBLIC_URL
            - TZ
            - JIBRI_BREWERY_MUC
            - JIBRI_PENDING_TIMEOUT
            - JIBRI_XMPP_USER
            - JIBRI_XMPP_PASSWORD
            - JIBRI_RECORDER_USER
            - JIBRI_RECORDER_PASSWORD
            - ENABLE_RECORDING
        networks:
            meet.jitsi:
                aliases:
                    - ${XMPP_DOMAIN}

    # XMPP server
    prosody:
        image: jitsi/prosody:latest
        restart: ${RESTART_POLICY}
        expose:
            - '5222'
            - '5347'
            - '5280'
        volumes:
            - ${CONFIG}/prosody/config:/config:Z
            - ${CONFIG}/prosody/prosody-plugins-custom:/prosody-plugins-custom:Z
        environment:
            - AUTH_TYPE
            - ENABLE_AUTH
            - ENABLE_GUESTS
            - ENABLE_LOBBY
            - GLOBAL_MODULES
            - GLOBAL_CONFIG
            - LDAP_URL
            - LDAP_BASE
            - LDAP_BINDDN
            - LDAP_BINDPW
            - LDAP_FILTER
            - LDAP_AUTH_METHOD
            - LDAP_VERSION
            - LDAP_USE_TLS
            - LDAP_TLS_CIPHERS
            - LDAP_TLS_CHECK_PEER
            - LDAP_TLS_CACERT_FILE
            - LDAP_TLS_CACERT_DIR
            - LDAP_START_TLS
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_GUEST_DOMAIN
            - XMPP_MUC_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_MODULES
            - XMPP_MUC_MODULES
            - XMPP_INTERNAL_MUC_MODULES
            - XMPP_RECORDER_DOMAIN
            - JICOFO_COMPONENT_SECRET
            - JICOFO_AUTH_USER
            - JICOFO_AUTH_PASSWORD
            - JVB_AUTH_USER
            - JVB_AUTH_PASSWORD
            - JIGASI_XMPP_USER
            - JIGASI_XMPP_PASSWORD
            - JIBRI_XMPP_USER
            - JIBRI_XMPP_PASSWORD
            - JIBRI_RECORDER_USER
            - JIBRI_RECORDER_PASSWORD
            - JWT_APP_ID
            - JWT_APP_SECRET
            - JWT_ACCEPTED_ISSUERS
            - JWT_ACCEPTED_AUDIENCES
            - JWT_ASAP_KEYSERVER
            - JWT_ALLOW_EMPTY
            - JWT_AUTH_TYPE
            - JWT_TOKEN_AUTH_MODULE
            - LOG_LEVEL
            - TZ
        networks:
            meet.jitsi:
                aliases:
                    - ${XMPP_SERVER}

    # Focus component
    jicofo:
        image: jitsi/jicofo:latest
        restart: ${RESTART_POLICY}
        volumes:
            - ${CONFIG}/jicofo:/config:Z
        environment:
            - AUTH_TYPE
            - ENABLE_AUTH
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_MUC_DOMAIN
            - XMPP_SERVER
            - JICOFO_COMPONENT_SECRET
            - JICOFO_AUTH_USER
            - JICOFO_AUTH_PASSWORD
            - JICOFO_RESERVATION_REST_BASE_URL
            - JVB_BREWERY_MUC
            - JIGASI_BREWERY_MUC
            - JIGASI_SIP_URI
            - JIBRI_BREWERY_MUC
            - JIBRI_PENDING_TIMEOUT
            - TZ
        depends_on:
            - prosody
        networks:
            meet.jitsi:

    # Video bridge
    jvb:
        image: jitsi/jvb:latest
        restart: ${RESTART_POLICY}
        ports:
            - '${JVB_PORT}:${JVB_PORT}/udp'
            - '${JVB_TCP_PORT}:${JVB_TCP_PORT}'
        volumes:
            - ${CONFIG}/jvb:/config:Z
        environment:
            - DOCKER_HOST_ADDRESS
            - XMPP_AUTH_DOMAIN
            - XMPP_INTERNAL_MUC_DOMAIN
            - XMPP_SERVER
            - JVB_AUTH_USER
            - JVB_AUTH_PASSWORD
            - JVB_BREWERY_MUC
            - JVB_PORT
            - JVB_TCP_HARVESTER_DISABLED
            - JVB_TCP_PORT
            - JVB_STUN_SERVERS
            - JVB_ENABLE_APIS
            - TZ
        depends_on:
            - prosody
        networks:
            meet.jitsi:

# Custom network so all services can communicate using a FQDN
networks:
    meet.jitsi:
`

**Comment by tronics** [comment]
Changing the image in the yaml always brings me a manifest unknown. Why is that?

version: '3'

services:
    # Frontend
    web:
        image: jitsi/web:v1
        restart: ${RESTART_POLICY}

**Comment by tuanaturkmen** [comment]
I receive an error like this while trying to run `sudo docker image build -t web:v1 .`
COPY failed: stat /var/lib/docker/tmp/docker-builder251306092/css/all.css: no such file or directory

This is the Dockerfile:

```
ARG JITSI_REPO=jitsi
FROM ${JITSI_REPO}/base

ADD https://raw.githubusercontent.com/acmesh-official/acme.sh/2.8.8/acme.sh /opt


RUN \
	apt-dpkg-wrap apt-get update --fix-missing && \
	apt-dpkg-wrap apt-get install -y cron nginx-extras jitsi-meet-web socat && \
	apt-dpkg-wrap apt-get -d install -y jitsi-meet-web-config && \
    dpkg -x /var/cache/apt/archives/jitsi-meet-web-config*.deb /tmp/pkg && \
    mv /tmp/pkg/usr/share/jitsi-meet-web-config/config.js /defaults && \
	mv /usr/share/jitsi-meet/interface_config.js /defaults && \
	rm -f /etc/nginx/conf.d/default.conf && \
	apt-cleanup && \
	rm -rf /tmp/pkg /var/cache/apt



COPY rootfs/ /
COPY css/all.css /usr/share/jitsi-meet/css/all.css
EXPOSE 80 443

VOLUME ["config", "/usr/share/jitsi-meet/transcripts"]

```
Any idea why? @prayagsingh  @spprod35 @cs35-owncloud

**Comment by prayagsingh** [comment]
Where's your all.css file? Is it in css directory?

**Comment by tuanaturkmen** [comment]
> Where's your all.css file? Is it in css directory?

Hello thank you, that was the reason. Now it executes. After this in docker-compose.yaml, I did what you said like this: 
 
```
web:
        image: jitsi/web:v1
```
Then I did `sudo docker-compose down `and `sudo docker-compose up -d `and received this:
```

Pulling web (jitsi/web:v1)...
ERROR: manifest for jitsi/web:v1 not found: manifest unknown: manifest unknown
```

**Comment by tuanaturkmen** [comment]
Thank you @prayagsingh , that was the reason. Now it executes. After this in docker-compose.yaml, I did what you said like this:
```

web:
        image: jitsi/web:v1
```
Then I did sudo docker-compose down and sudo docker-compose up -d and received this:

```

Pulling web (jitsi/web:v1)...
ERROR: manifest for jitsi/web:v1 not found: manifest unknown: manifest unknown
```

**Comment by saghul** [comment]
Answers have been provided, so I'm closing this.

FWIW, I don't recommend editing all.css, mounting the watermark file is a lot more future proof.

**Comment by tuanaturkmen** [comment]
> Answers have been provided, so I'm closing this.
> 
> FWIW, I don't recommend editing all.css, mounting the watermark file is a lot more future proof.

@saghul  Do you know why I am havıng the ıssue above?

**Comment by saghul** [comment]
I don't know, sorry.

**Comment by tuanaturkmen** [comment]
> Changing the image in the yaml always brings me a manifest unknown. Why is that?
> 
> version: '3'
> 
> services:
> # Frontend
> web:
> image: jitsi/web:v1
> restart: ${RESTART_POLICY}

Hey we are having the exact same situation. Have you found the answer?

**Comment by tronics** [comment]
@tuanaturkmen no I could not solve this. I have tried flags to be sure that everything is properly regenerated. I even started again from scratch.

Same problem here: https://community.jitsi.org/t/building-a-new-image-of-web-directory-to-remove-logo-it-gives-unkown-manifest-error-when-image-name-of-web-is-changed-in-docker-compose-yml/87757

I think it would be really much appreciated if a complete solution was posted for others that have the same problem.

**Comment by tuanaturkmen** [comment]
> @tuanaturkmen no I could not solve this.
> I have tried flags to be sure that everything is properly regenerated. I even started again from scratch.
> 
> Same problem here: https://community.jitsi.org/t/building-a-new-image-of-web-directory-to-remove-logo-it-gives-unkown-manifest-error-when-image-name-of-web-is-changed-in-docker-compose-yml/87757
> 
> I really want to understand why it does not work. What was it that @prayagsingh did differently?
> I have checked the path a couple of times.

Above @mesouug  talks about replacing the image via volumes, do you or @mesouug know how to remove the logo via volumes instead of replacing it?

**Comment by tronics** [comment]
> Above @mesouug talks about replacing the image via volumes, do you or @mesouug know how to remove the logo via volumes instead of replacing it?

You could just use a transparent png or gif I suppose.

Also you can replace the css and add a display:none in the css.

I have to look into this again. I hoped to solve it the other way.

**Comment by mesouug** [comment]
> Above @mesouug talks about replacing the image via volumes, do you or @mesouug know how to remove the logo via volumes instead of replacing it?

@tuanaturkmen If you delete file inside container then it will cause 404 error in browser. @tronics suggest right solution. Transparent 1px image will do the trick. Or delete link to image in CSS but this is more complicated to maintain.
