### ISSUE TITLE
Only one moderator in Docker deployment with JWT tokens authorization

### ISSUE THREAD

**Issue by ankar84** [jitsi/docker-jitsi-meet#554]
My problem described a little [here](https://community.jitsi.org/t/how-are-modersators-selected/29100)  and [here](https://community.jitsi.org/t/allow-only-one-moderator/22389/13)
My deployment details:
All components are in Docker
Jitsi is used as video conferencing system for Rocket.Chat
We use JWT authentications from Rocket.Chat and guest access for non Rocket.Chat users
Thanks to @damencho we disabled annoying "User grander moderator rights" notifications by [this](https://github.com/jitsi/jitsi-meet/issues/5948#issuecomment-624421771) 

Anyway, any authenticated by JWT user (or just any user from Rocket.Chat) get moderator rights.
 But we need that first room user (who create root) get moderator rights and can grant it to another user if needed.
I deleted **mod_muc_allowners.lua** file from **prosody-plugins** folder in Docker container and restarted all containers - no luck.
[Here](https://community.jitsi.org/t/how-to-make-a-single-moderator/15332/12) is a [solution](https://github.com/nvonahsen/jitsi-token-moderation-plugin) for my problem. 
But Rocket.Chat integration limits me for such solution - I have no ability to add something to jitsi URL from Rocket.Chat (no settings for that).

So, I need somehow that JWT token enabled, Rocket.Chat integrated Jitsi in Docker grant moderator  rights only to room creator.

@saghul can you help with that?

**Comment by saghul** [comment]
There is nothing we can do really. If you want to use that module, great, but then you need the application to generate the JWT token with the "moderator" field.
