### ISSUE TITLE
Make possible to choose JITSI_RELEASE version in environments

### ISSUE THREAD

**Issue by reysy** [jitsi/docker-jitsi-meet#558]
Main purpose of this is ability to choose version of the jitsi libs/packages. Right now when you are building some images locally you are pulling the latest and other images are sticked to the git repository version.
For example I have the `docker-jitsi-meet` project for the 20th April on my server and I need to build `web` image on that server to have some customizations on frontend. But when I build it and then start the docker-compose I have 2 different versions of libs, `web` is using latest version and other images are versioned from 20th April.

Or I'm getting it wrong? Or is there a right way to choose the release version of packages?

**Comment by saghul** [comment]
There is no way to do that. Containers are built with the Debian packages from our stable Debian repository, not from git. So there is no way to build an image for an old release with the current Dockerfiles.

You can always pin your image versions to the one you want.
