### ISSUE TITLE
Neither Video, nor Audio wit a second participant

### ISSUE THREAD

**Issue by tux1980** [jitsi/docker-jitsi-meet#573]
Hi,
I'm working with "docker-jitsi" on docker 18.06-3-ce on a public server by Hetzner (german service provider) with Red Hat Enterprise 8.2 as OS. I'm also using let's encrypt. 

I can create a room and I see myself through my web camera in the created jitsi-room.  But as soon a second participant has been entered, I notice that, but no video, no audio at all. I was checking the container logs (with "docker logs" and in the container itself with -it exec) but nothing special there. There also, apparently, no firewall problems (Open is: 443 TCP,80 TCP,10000 UDP, 4443 TCP) .So I'm really getting nuts here... 

I'm not using any kind of NAT, no router in between, nothing. It is an public IP with an public FQDN (web.kimmlingen-online.com). 

Any Ideas? 

Thanks!

**Comment by slackmage** [comment]
@tux1980 I'm working on the same issue right now. I've noticed that the jvb service isn't running in its container.

**Comment by slackmage** [comment]
Correction. I do see it running. But web isn't connecting to it.

![image](https://user-images.githubusercontent.com/230274/81482709-156b4780-9207-11ea-935c-2dd74bdd1f0e.png)

**Comment by tux1980** [comment]
@slackmage: that's weird.... If you do experience anything more on that, I'm glad to learn about that.

**Comment by slackmage** [comment]
jvb status says it is not running

![image](https://user-images.githubusercontent.com/230274/81483007-05ecfe00-9209-11ea-86a3-4417b3fadbdc.png)

even though I can see the processing running 

![image](https://user-images.githubusercontent.com/230274/81483046-49476c80-9209-11ea-8d85-2cffa0c0174b.png)

**Comment by slackmage** [comment]
@tux1980 try and uncomment DOCKER_HOST_ADDRESS in the .env file, delete the .jitsi-meet-config directory and restart your jitsi containers

**Comment by slackmage** [comment]
Firefox worked. If you don't have your ssl cert set up Chrome doesn't like it.

**Comment by tux1980** [comment]
![Screenshot-20200510071114-488x39](https://user-images.githubusercontent.com/46625474/81491313-75a4cc80-928d-11ea-9cb2-b315c42bb84e.png)

It didn't help.... I'm using Firefox and I also tried it with different other sort of browsers. Even my Jitsi-Videobridge is working right now. The Cert is trusted as well.

**Comment by tux1980** [comment]
Is working now! 

You have to adapt the following config paramters as well:

DOCKER_HOST_ADDRESS="your public IP Address" 
JVB_TCP_HARVESTER_DISABLED=false

After the changes, restart docker Containers.... 
TA

**Comment by tux1980** [comment]
has been solved

**Comment by slackmage** [comment]
@tux1980 thank you! this worked for me.
