### ISSUE TITLE
Setting a general password

### ISSUE THREAD

**Issue by tux1980** [jitsi/docker-jitsi-meet#576]
Hi,

how can I set an all-over password to force the user you is willing to enter any Jitsi room to put in a general password? I mean ONE password for all rooms, an allover Jitsi password. I can't find the appropriate parameter in the .env file

Thanks

**Comment by normen** [comment]
Theres no such thing. You either have a per-server password to make sessions or you have a per-room password.

**Comment by tux1980** [comment]
And how can I set this per-server password in the .env file?
Thanks

**Comment by normen** [comment]
As described in the README: https://github.com/jitsi/docker-jitsi-meet#internal-authentication

**Comment by tux1980** [comment]
Perfect, it is working just fine. Thank you
