### ISSUE TITLE
Remove the Blur Option in the server settings (.env file?)

### ISSUE THREAD

**Issue by tux1980** [jitsi/docker-jitsi-meet#577]
Hi,

I can't find the option to disable the blur option on the server side? I mean to take away this option at all from their client options. They shouldn't see it. 

I did find something like that, but that resolve is not meant for docker approach. 
```You may also just navigate to your jitsi main page and enter javascript:window.localStorage.removeItem('features/blur') into the URL bar, or open the javascript console and enter window.localStorage.removeItem('features/blur'); there. ```

Thanks for giving me a hint!

**Comment by normen** [comment]
interface_config.js in the .jitsi-meet/web folder

**Comment by tux1980** [comment]
Hi, yes this I do know. The thing is after restarting the containers the settings are in the originals data can. So how can a final Parameter in the .env file to do so?
Thanks

**Comment by normen** [comment]
They are only recreated when you recreate the container, not when you start it.

**Comment by tux1980** [comment]
It worked for me thanks!
