### ISSUE TITLE
web config/config.js config/interface_config.js Permission denied

### ISSUE THREAD

**Issue by troykelly** [jitsi/docker-jitsi-meet#579]
Clean docker install is unable to start per the instructions.
docker-compose is not running as root.

`web` log files show:
```text
web_1      | 2020/05/11 17:23:37 [error] 232#232: *7 open() "/config/config.js" failed (13: Permission denied), client: 172.20.0.1, server: _, request: "GET / HTTP/2.0", subrequest: "/config.js", host: "meet.example.com"
web_1      | 2020/05/11 17:23:37 [error] 232#232: *7 open() "/config/interface_config.js" failed (13: Permission denied), client: 172.20.0.1, server: _, request: "GET / HTTP/2.0", subrequest: "/interface_config.js", host: "meet.example.com"
```

I have tried entering the web container and `chmod`ing both the relevant files to 666 - and still the permission issue persists.

**Comment by troykelly** [comment]
This does not appear to be related to running `docker` / `docker-compose` as root.
I have just tried again with a clean build - and the exact same error is generated when docker-compose us run as `root`.

It appears that the [latest build](https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-4548-1) & current build are broken.

**Comment by saghul** [comment]
Can you please past the logs of the web container, from the start? Also, where is your CONFIG volume located, in the host?

**Comment by troykelly** [comment]
There's nothing more relevant before those lines in the log - just Let's Encrypt generating the cert.
The config is located exactly [per the instructions](https://github.com/jitsi/docker-jitsi-meet).
I've run up a new VM using Ubuntu rather than PhotonOS - and it works under ubuntu - so this appears to be a strange permissions issue in other OS's

**Comment by saghul** [comment]
Glad you got it working! I have neveer heard of PhotonOS before, so I can't help you further there, sorry.

**Comment by troykelly** [comment]
It's the container OS of choice for VMware. I'm not sure how/why it could introduce permissions issues like this, I've never seen it before.
I'm glad it's working with Ubuntu, now I just need to argue my way into getting into integrated with our PBX

**Comment by fanfelle** [comment]
I had a problem with the same symptoms.  I was able to resolve it by ensuring the folder holding the files had read permissions (not just the files themselves).

**Comment by Schnuecks** [comment]
Sorry for reactivation.
I setup from the docs and get the same error above.

[env.txt](https://github.com/jitsi/docker-jitsi-meet/files/5445998/env.txt)
[docker_logs.txt](https://github.com/jitsi/docker-jitsi-meet/files/5446001/docker_logs.txt)
[nginx.txt](https://github.com/jitsi/docker-jitsi-meet/files/5446062/nginx.txt)

i change the directory to .jitsi-meet-cfg permission is all root:root
i deleted and recreated it many time the config is stored in there but can't be access

if anything else is needed let me know. i don't have a clue. my system ist centos 7
