### ISSUE TITLE
How to prevent mirrored mode for local participant

### ISSUE THREAD

**Issue by JacBra** [jitsi/docker-jitsi-meet#583]
Is it possible to show the local camera always 'not mirrored'?
We use a virtual camera and want to show a message with instructions on how to couple it.
And this screen is now always in mirrored mode. (I am aware of the Flip option but I want show the screen immediately right to my end users.)
How can we prevent this? (ideally with a .env variable of course ;)

**Comment by saghul** [comment]
There is no option for that, sorry. Note that the setting is saved, so if you disable flipping, it will remain that way.

**Comment by parruc** [comment]
We also have this same problem. An option to disable flip by default would be cool.

**Comment by zsinba** [comment]
> We also have this same problem. An option to disable flip by default would be cool.

did you have other option?
