### ISSUE TITLE
Need warning about Let's Encrypt

### ISSUE THREAD

**Issue by codingthat** [jitsi/docker-jitsi-meet#585]
> That all was not the problem in my case. I started totally from scratch. The only thing i did is preserving my letsencrypt certificates (i already renewed them 4 times this week while testing) and put them in .jitsi-meet-cfg/web/letsencrypt before running docker-compose up -d. That caused the problem. I removed the certificates from the config directory and after an other docker-compose up -d everything works as intended.
It't would be nice if there was a possibility to safe the letsencrypt certificates while renewing the config directory, because the "five times renewing policy" of letsencrypt will be tripped fast while testing and playing with the config.

_Originally posted by @foer in https://github.com/jitsi/docker-jitsi-meet/issues/387#issuecomment-610192558_

Just got bitten by this one.  I didn't know beforehand that there was a rate limit, nor did I anticipate that it it was being used up by the Let's Encrypt part of the config even while I was debugging other problems in the config (like a particular time zone not being accepted.)

Ideally this would be handled automatically for new folks (and also for Let's Encrypt's sake, so we're not giving them extra work for nothing.)

But I know that's a lot of work...so in lieu of that, a huge warning in the readme seems appropriate...

**Comment by saghul** [comment]
Sure thing, mind making a PR?

**Comment by codingthat** [comment]
@saghul Thanks, I started working on one at https://github.com/jitsi/docker-jitsi-meet/compare/master...codingthat:patch-1 but then I noticed someone already has a PR in about it: https://github.com/jitsi/docker-jitsi-meet/pull/388

Also I'm not entirely clear on how to reuse the cert between cycles of "remove all config files, mkdir -p again, and docker-compose up -d again"  It would make sense for someone with more specific experience to add this.

**Comment by JaredRymer** [comment]
I recommend moving the folder instead of deleting it. Maybe someone should make another pull request to change the readme a bit? Not sure how to best word it in the readme... Maybe there is another best practice beyond moving the folder to a different location or name.
