### ISSUE TITLE
Jitsi web interface not available with Lets Encrypt

### ISSUE THREAD

**Issue by ff00** [jitsi/docker-jitsi-meet#587]
Followed official guide to setup Jitsi-docker
with enabled option ENABLE_LETSENCRYPT=1  
(set ports to 80, 443, set ENABLE_HTTP_REDIRECT)

Got 'site not available'.

If I comment out line # ENABLE_LETSENCRYPT=1  
I got NET::ERR_CERT_AUTHORITY_INVALID

please help how to make it working

**Comment by saghul** [comment]
Plase attach the web container logs.

**Comment by ff00** [comment]
how can I get them?

**Comment by ff00** [comment]
admin@cryspprod3:~/work-jitsi/docker-jitsi-meet$ docker logs  dockerjitsimeet_web_1
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-set-timezone: executing...
cp: '/usr/share/zoneinfo/UTC' and '/etc/localtime' are the same file
WARNING: UTC is not a valid time zone.
[cont-init.d] 01-set-timezone: exited 0.
[cont-init.d] 10-config: executing...
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
An unexpected error occurred:
There were too many requests of a given type :: Error creating new order :: too many failed authorizations recently: see https://letsencrypt.org/docs/rate-limits/
Please see the logfiles in /var/log/letsencrypt for more details.
Failed to obtain a certificate from the Let's Encrypt CA.
admin@cryspprod3:~/work-jitsi/docker-jitsi-meet$

**Comment by ff00** [comment]
I see, it is due to letsencrypt limits, how to specify own certificate then? without ENABLE_LETSENCRYPT ?

**Comment by saghul** [comment]
That's not currently possible. It's either Let's Encrypt or a self-signed one. If you want your own you can use your own web server and proxy to the HTTP port of this setup.
