### ISSUE TITLE
Jitsi Web Metadata

### ISSUE THREAD

**Issue by Tieantono** [jitsi/docker-jitsi-meet#593]
Hi, is there any configuration file to configure the web HTML metadata in the Docker image? I've searched on the internet but it seems this is only available when you change the [`title.html`](https://github.com/jitsi/jitsi-meet/blob/master/title.html) file and not using the Docker image build.

**Comment by saghul** [comment]
There is no way to do it easily at the moment. You’d have to edit the file inside the container.

**Comment by Tieantono** [comment]
I see, in that case, I'll have to wrap up the Jitsi Meet embed `iframe` inside my web app and only share the link of my own web app. Thank you for the clarification.

**Comment by sapkra** [comment]
You should be able to use a volume to replace this file in the container.

**Comment by Tieantono** [comment]
> You should be able to use a volume to replace this file in the container.

Yes, I think so too, will try it later. Thank you.
