### ISSUE TITLE
Add .env variables for external TURN with shared secrets

### ISSUE THREAD

**Issue by lab-at-nohl** [jitsi/docker-jitsi-meet#595]
Although you are working on a Docker with TURN-server (#163), I would like to use external servers. Atm I have to configure manually after creating the container (pain). 

Could we have a variable like `EXTERNAL_STUN_TURN="server1.com:80/udp server2.com:443/tcp"` which triggers 

- downloading and installing prosody/mod_turncredentials.lua
- enable it inside prosody.cfg.lua
- insert it into web/config.js

I would give it some effort but I fear that you would not take it when implementing an internal turn server.

**Comment by goacid** [comment]
+1

**Comment by RedJohn14** [comment]
+1

**Comment by hamletmun** [comment]
@lab-at-nohl can you explain what you are doing?
Would https://github.com/jitsi/docker-jitsi-meet/commit/856e414084876551fe29f0c72d54d476d9905bd0 be enough to use external turn servers?

**Comment by prayagsingh** [comment]
> Would [856e414](https://github.com/jitsi/docker-jitsi-meet/commit/856e414084876551fe29f0c72d54d476d9905bd0) be enough to use external turn servers?

yes

**Comment by saghul** [comment]
Closing since this has landed already.
