### ISSUE TITLE
Can I use jwt and ldap at the same time?

### ISSUE THREAD

**Issue by arpsyapathy** [jitsi/docker-jitsi-meet#599]
Hi all!

Can I use jwt and ldap at the same time?

I use JWT for Rocket.Chat.
But i want use ldap for users beyound Rocket.Chat.
Is it possible?

**Comment by saghul** [comment]
Yes, but not for the same virtual host. You’d need to define different ones.

**Comment by arpsyapathy** [comment]
> Yes, but not for the same virtual host. You’d need to define different ones.

Can you show example? Thank you
