### ISSUE TITLE
jigasi support

### ISSUE THREAD

**Issue by shierro** [jitsi/docker-jitsi-meet#6]
Hi guys, it's great to see the official jitsi docker set-up - this is amazing!

I would like to know if you have plans to add jigasi on the picture

**Comment by shierro** [comment]
silly me, it's on README

**Comment by shierro** [comment]
That's it, it's only a plan(TODO). no ETA, or any roadmap. So most likely, this feature won't be available anytime soon, unless someone work on it. or maybe someone is @saghul?

**Comment by saghul** [comment]
Yes, I will work on it, but I cannot provide an ETA, sorry.
