### ISSUE TITLE
web/config.js incorrect when using Etherpad

### ISSUE THREAD

**Issue by ryanmartinneutrino** [jitsi/docker-jitsi-meet#609]
In order for etherpad integration to work, I found that I needed to not only set the correct URL in the .env file (ETHERPAD_URL_BASE), but then had to go and replace the etherpad URL that is generated in web/config.js. 

In my setup, I am linking to an etherpad container that is running independently (i.e. not from the docker-compose of this project). 

This is discussed here, along with the solution that worked for me:
https://community.jitsi.org/t/etherpad-in-docker-version/24432/2

**Comment by cboylan** [comment]
I think that https://github.com/jitsi/docker-jitsi-meet/pull/619 may have fixed this issue. It sets the url via ETHERPAD_URL_BASE and appends /etherpad/p/ as well.

**Comment by saghul** [comment]
You can use ETHERPAD_PUBLIC_URL in that case.
