### ISSUE TITLE
web/prosody: OCI runtime create failed: this version of runc doesn't work on cgroups v2: unknown

### ISSUE THREAD

**Issue by Cyborgscode** [jitsi/docker-jitsi-meet#618]
System got upgraded from Fedora 30 to Fedora31. On first startup docker pulled a shitload of new data in, but failed to start the containers:

]# docker-compose up -d
Creating network "docker-jitsi-meet_meet.jitsi" with the default driver
Creating docker-jitsi-meet_prosody_1 ... error
Creating docker-jitsi-meet_web_1     ... 

Creating docker-jitsi-meet_web_1     ... error

ERROR: for docker-jitsi-meet_web_1  Cannot start service web: OCI runtime create failed: this version of runc doesn't work on cgroups v2: unknown

ERROR: for prosody  Cannot start service prosody: OCI runtime create failed: this version of runc doesn't work on cgroups v2: unknown

ERROR: for web  Cannot start service web: OCI runtime create failed: this version of runc doesn't work on cgroups v2: unknown
ERROR: Encountered errors while bringing up the project.

How can we fix this?

**Comment by Cyborgscode** [comment]
Fix (more a workaround):

add "systemd.unified_cgroup_hierarchy=0" the kernel line and reboot.

Or switch to podman for Fedora.

**Comment by jreiners** [comment]
just commenting to say changing to podman instead of docker fixed the issue for me. Thanks Cyborgscode

**Comment by Cyborgscode** [comment]
is it fixed now or why did you close it?

**Comment by saghul** [comment]
A solution was provided, so I was under the impression that was the end of it. Also, we don't support podman.

**Comment by Cyborgscode** [comment]
it's just a workround, not a solution. But as Docker has to fix this issue, you can't do much.
