### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by YUEJINYUAN** [jitsi/docker-jitsi-meet#62]
I hope this helps improve the server, or helps others solve the problem. When I first set up the service (without changing any configuration), it works.
But when docker stops all the servers at the same time, I can't talk properly (he always makes an error when the second or more clients connect to the room).
After that I cleared the previous server and rebuilt it, shutting down a server separately and then starting it according to the command (in order to find out which server is the problem), then there is no problem, (at this point I tested and restarted 4 servers, And found that they are all working well) and can be restarted even after all are turned off (calls work normally).
It's like a strange bug that disappeared under my gorgeous operation. . .

**Comment by YUEJINYUAN** [comment]
In order to locate this problem, after I restarted the first created server (docker stop all and docker-compose up -d), I created a room and entered it with two browser pages, then the error message on the console said
[conference.js] <e.value>: CONFERENCE FAILED: conference.videobridgeNotAvailable

**Comment by YUEJINYUAN** [comment]
Oh, it’s a crashing experience, the server is working again now, I tried to clear the previous docker server and redeploy it. After ensuring the first normal work, I tried to close the 4 parts separately. Only shut down one and then try to start), then start again, the server can work normally, then I shut down all the time (when I closed 4) and then start, the server is normal, and the previous secondary startup can not be accessed like A bug that is not working at any time, no matter how I can guarantee the restart of the service, LOL.

**Comment by YUEJINYUAN** [comment]
This seems to make me a bit confused, I initially thought it relied on the turn to achieve the connection ends, so I tried to build the turn service, but when I read the code, I found that only one to one will use the turn, and in the third It still uses jvb. So I need to configure turn for it? If it is from the perspective of load, is there a way to load multiple jvbs?

**Comment by saghul** [comment]
Please be specific. What is your problem exactly?

**Comment by YUEJINYUAN** [comment]
Wow, I didn't expect the reply to be so fast. I want to know if the turn is useful for jitsi. Can you replace the load with multiple jvb servers at the same time, or you can tell me the other role of turn?

**Comment by YUEJINYUAN** [comment]
Lame translation, I hope you understand what I mean

**Comment by YUEJINYUAN** [comment]
And another one.
After I restarted many times, I found that the users before the restart were still in the previous room and did not disappear. These users were generated by my previous tests.
At that time, I turned off the client audio and video and kept it in the room, then turned off the server. After the restart, the user is still in the room. Is there any way to eliminate it? This is like a bug that shields users of audio and video,after shutting down the server, it appeared.

**Comment by saghul** [comment]
Yes, you can use TURN, if you want to. It will help in 2 cases:

- 1-1 calls: there is no need to involve the JVB and so all the processing it does
- Firewalls and such

That said, these Docker images don't currently provide a TURN server.

About the multiple TURN servers: yes, you can use multiple, but at the moment this Docker setup only uses one, you'll have to change that yourself.

**Comment by damencho** [comment]
> After I restarted many times, I found that the users before the restart were still in the previous room and did not disappear. These users were generated by my previous tests.

This is due to the fact that there is storage set for the muc compoent:
https://github.com/jitsi/docker-jitsi-meet/blob/master/prosody/rootfs/defaults/conf.d/jitsi-meet.cfg.lua#L49

@saghul Is there a reason to enable storage, we do not use it and we want rooms to loose state on restart or when not used. 
In the default debian deployment this is disabled: https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example#L29

**Comment by saghul** [comment]
@damencho Ah, damn. IIRC we had to add it because of some failures in Prosody 0.11. Can you open an issue about it so I can take another look?

**Comment by damencho** [comment]
The failures are because it used to work for 0.10 and trunk with "null" and for 0.11 you need to change it to "none" :(
