### ISSUE TITLE
Running JVB on port 443 on same host as web

### ISSUE THREAD

**Issue by gorbypark** [jitsi/docker-jitsi-meet#625]
I'm attempting to run docker-jitsi-meet on one single host, but with web and jvb both listening on port 443 (on different IPs).  I have a secondary external IP for JVB to run on, how can I make just JVB bind to that secondary IP?  Setting JVB_HOST=50.50.50.50 (obviously not the real IP) in the .env doesn't seem to work.

**Comment by saghul** [comment]
I think you’d need to change the syntax used to expose the port.
