### ISSUE TITLE
Update to newer release without the need to check config file everytime

### ISSUE THREAD

**Issue by jonathanwerle** [jitsi/docker-jitsi-meet#627]
# How do i update to a newer release? 
## Current workflow:

1. Stop my running instance using `docker-compose down`
2. Download newest release from this repository
3. Copy old config to the new directory
4. **Check for any new entries in the new sample config**

## Expectation:
- Update process needs to be more automated
**OR**
- Step 4 is replaced via script

Am i doing it wrong or is there really no other way (than described) to update to a newer release?

**Comment by saghul** [comment]
The config file is now generated from environment variables, so you don't need to migrate settings by hand anymore.
