### ISSUE TITLE
video button sometime is not reacting

### ISSUE THREAD

**Issue by ortomind** [jitsi/docker-jitsi-meet#628]
Since the last version the vireo button either react very slow or is not responsive. Until now only some participants complained, but now I had it myself in a meeting.  I am using API connection.  docker-compose logs -f does not show any error: any other place / logs to look into?
in console log I see Logger.js:154 2020-06-04T16:08:51.890Z [modules/connectivity/ParticipantConnectionStatus.js] <S.onTrackRtcMuted>:  No participant for id: 26b523d1

**Comment by sapkra** [comment]
`No participant for id` is a know bug of lib-jitsi-meet. https://github.com/jitsi/lib-jitsi-meet/issues/859

For me it seems like your problem has nothing to do with the docker setup.

**Comment by saghul** [comment]
Agreed, please follow-up on the lib-jitsi-meet issue.
