### ISSUE TITLE
Reservation system error

### ISSUE THREAD

**Issue by viettranisnottaken** [jitsi/docker-jitsi-meet#636]
I keep getting this error when I fire up Jitsi:
![123](https://user-images.githubusercontent.com/48340676/84134941-8191d300-aa73-11ea-9f6e-f57786bed92f.png)

Here's what I've done:

- I've followed all these steps from the tutorial (https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#build-instructions): 
![jitsi-docker-tutorial](https://user-images.githubusercontent.com/48340676/84135663-73908200-aa74-11ea-9e47-431303e05bfc.png)
- I've configured my `.env` file so that Jitsi knows to call my api to check for room availability: 
```
# Base URL of Jicofo's reservation REST API
# JICOFO_RESERVATION_REST_BASE_URL=http://reservation.example.com

JICOFO_RESERVATION_REST_BASE_URL=http://localhost:3002

# Enable Jicofo's health check REST API (http://<jicofo_base_url>:8888/about/health)
JICOFO_ENABLE_HEALTH_CHECKS=false

```
- I've created my own api using Rails, which also has an endpoint of "/conference", returning json upon being called: 
```
{
  id: 364758328,
  name: params[:name],
  mail_owner:  params[:mail_owner],
  start_time: Time.zone.now,
  duration: 900000
}
```
Yet that error still shows up. 
Any idea how to solve this? Thanks in advance!

**Comment by oramirite** [comment]
I am struggling with this as well. When I set the JICOFO_RESERVATION_REST_BASE_URL to http://jicofo (which should be the docker hostname of the respective container), I actually get a "Connection Refused" message instead. But this might not mean anything. What's the correct URL to set this to?

**Comment by viettranisnottaken** [comment]
I have solved this problem by deleting the jitsi-meet-cfg folder and .evn.bak, then restarting my container.
