### ISSUE TITLE
JWT for RocketChat and LDAP for guests. Is it possible?

### ISSUE THREAD

**Issue by arpsyapathy** [jitsi/docker-jitsi-meet#638]
Hi all!

I configure JWT auth. RocketChat users can create rooms.
But i want that guests users (who log in in jitsi-meet room by link) will be auth by LDAP.

This is possible? Thank you advanced

**Comment by Echolon** [comment]
Hi,
If you have a question about Jitsi Meet that is not a bug report or feature request, please post it in https://community.jitsi.org.

Unfortunately, I have to close this issue.

---
*I'm a community contributor and not directly affiliated with the Jitsi team.*
