### ISSUE TITLE
Disable storage for muc components 

### ISSUE THREAD

**Issue by damencho** [jitsi/docker-jitsi-meet#64]
https://github.com/jitsi/docker-jitsi-meet/issues/62

https://github.com/jitsi/docker-jitsi-meet/blob/master/prosody/rootfs/defaults/conf.d/jitsi-meet.cfg.lua#L49

In jitsi-meet this is disabled: https://github.com/jitsi/jitsi-meet/blob/master/doc/debian/jitsi-meet-prosody/prosody.cfg.lua-jvb.example#L29

For 0.10 and -trunk version storage = "null" works, for 0.11 you need storage = "none"

**Comment by saghul** [comment]
I had it as none, and something was not working: https://github.com/jitsi/docker-jitsi-meet/commit/8e2964b0068013430696af5e31b7626027b323bc

How about using "memory": https://prosody.im/doc/storage - It's new on 0.11, basically it looks like it will store everything in memory, so a restart will wipe it.

WDYT?

**Comment by damencho** [comment]
Yeah, I think that will work ... I remember that this was fixing the restart issue. If something is wrong and you restart prosody, all participants will get the reload screen but when they reload they will see a bunch of ghosts because of storage ... 
Interesting what was not working as I hope we will move meet.jit.si to 0.11 at some point ...

**Comment by saghul** [comment]
Kewl, let's give it a try then. It's good that we are testing here then! :-)

**Comment by YUEJINYUAN** [comment]
Sorry to re-open this problem, I tried to modify the muc part to none or null failed, these ghosts are still in the previous room, I tried to delete the whole project, then re-git clone and create the server, unfortunately this is not Use, so where is the module for storing users in each room? Is it stored on the host machine?
Regarding the stranded user part, can you tell me how to clear this part of the storage?

**Comment by saghul** [comment]
Not sure how this is related to the discussion. If you delete the config directory then data for all containers is gone, since we pass subdirectories of the main config directory as volumes to the different containers.
