### ISSUE TITLE
Support external Etherpad

### ISSUE THREAD

**Issue by madmath03** [jitsi/docker-jitsi-meet#644]
Currently, we can set `ETHERPAD_URL_BASE` to enable use of Etherpad inside Jitsi, but we can only use a "_local_" Etherpad, not an external Etherpad which might already exist outside of Jitsi docker network.

I guess this could be fixed by adding a env var to define the value of `etherpad_base`:
https://github.com/jitsi/docker-jitsi-meet/blob/a7563d4f82d79cfaca6f5ff408299f7857f7cac7/web/rootfs/etc/cont-init.d/10-config#L100-L104

For instance:
* `ETHERPAD_PUBLIC_URL=https://etherpad.my.domain`

```shell
    if [[ -z "$(grep -om1 'etherpad_base:' /config/config.js)" ]]; then
        if [[ ! -z "${ETHERPAD_PUBLIC_URL}" ]]; then
            sed -i \
                -e "/enableWelcomePage/a\    etherpad_base: '${ETHERPAD_PUBLIC_URL}/p/'," \
                /config/config.js
        elif [[ ! -z "${ETHERPAD_URL_BASE}" ]]; then
            sed -i \
                -e "/enableWelcomePage/a\    etherpad_base: '${PUBLIC_URL}/etherpad/p/'," \
                /config/config.js
        fi
    fi
```

**Comment by ralfi** [comment]
This will be really cool!

**Comment by saghul** [comment]
Sounds good, care to send a PR?

**Comment by madmath03** [comment]
> Sounds good, care to send a PR?

Sure 😃 
Will send a PR today with this
