### ISSUE TITLE
tpl help

### ISSUE THREAD

**Issue by markmadlangbayan** [jitsi/docker-jitsi-meet#65]
Hi there,

I'm trying to modify one of the config files, and want to do the following:

```
{{- range (splitList "," .Env.XMPP_JVBS) }}
Component "{{.}}"
    component_secret "{{.ENV.Secret}}"
{{- end }}
```
I don't know how the templating works, but how do I access `.ENV.Secret` inside the loop. 

Thanks!

**Comment by saghul** [comment]
The `tpl` command uses `frep`: https://github.com/subchen/frep you can check the project's documentation there.
