### ISSUE TITLE
Frequency of updating public images

### ISSUE THREAD

**Issue by spprod35** [jitsi/docker-jitsi-meet#650]
Hello,

How often is the latest image rebuilded on dockerhub?
I see that the last creation of the public image dates from 23 day.
Since then there have been several releases made on the official jitsi meet repo.
A CI on this repot is envisaged?

Regards,

**Comment by saghul** [comment]
Releases are created when a stable release is created. We have not created a stable release since.

**Comment by spprod35** [comment]
I'm sorry, I hadn't seen the subtlety.
I just edited my docker-compose.yml by modifying image by build with the path of each service.
If I build the images on my side, could I try the lobby from my test server in a stack docker?

**Comment by saghul** [comment]
The Docker images have not been updated to support lobby. There is some extra Prosody configuration required.

**Comment by spprod35** [comment]
I'm looking to integrate.
I will look to make the necessary changes.
If I do, I come back here to keep you informed of the changes made to the files.

**Comment by sapkra** [comment]
I think the best would be to close this issue because the main question is answered. If you are going to implement the configs for the lobby feature please create a PR or a new issue.
