### ISSUE TITLE
Calling out to SIP can hear Jitsi members, but can't talk back.

### ISSUE THREAD

**Issue by wreiske** [jitsi/docker-jitsi-meet#66]
Calling out via SIP through our Asterisk system allows callers to hear the Jitsi meeting, but the caller can not speak back to the Jitsi room. 

![image](https://user-images.githubusercontent.com/6295044/52893684-1da41680-316d-11e9-837e-16a9f3fb04ed.png)

The caller shows up as "muted" and there is no way to unmute them.

I have made sure to follow the advanced configuration options [here](https://github.com/jitsi/jitsi-meet/blob/master/doc/quick-install.md#advanced-configuration).

Any ideas?

**Comment by wreiske** [comment]
Looking futher, the advanced config options might not do anything since the docker run file fills in the environment variables for you if you have a docker_host_address filled in...

```
if [[ ! -z "$DOCKER_HOST_ADDRESS" ]]; then
    LOCAL_ADDRESS=$(hostname -I | cut -d " " -f1)
    JAVA_SYS_PROPS="$JAVA_SYS_PROPS -Dorg.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS=$LOCAL_ADDRESS -Dorg.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS=$DOCKER_HOST_ADDRESS"
fi
```
So I don't think the config is a problem, unless I'm missing something there....

I noticed that none of the boxes are running services...
```
root@jitsi:~/docker-jitsi-meet# docker exec -it docker-jitsi-meet_jvb_1 /bin/bash
root@e76b97fc2f3c:/# service --status-all
 [ ? ]  hwclock.sh
 [ - ]  jitsi-videobridge
 [ - ]  procps
 [ - ]  x11-common
```
however, everything seems to be working except for the SIP stuff.

**Comment by damencho** [comment]
Please use the community forum for problems or questions.

You need to check the incoming traffic to jigasi. Is your sip side is sending rtp to jigasi? Does your sip side support nat traversal handling (latching)?
