### ISSUE TITLE
Certbot missing on Web Container

### ISSUE THREAD

**Issue by fjferdiez** [jitsi/docker-jitsi-meet#664]
Hello! I am trying to run an instance of jitsi and the web container is having issues, it cannot start the ssl (as exposed in #257 & #246)

But I noticed this error as well on the upper part which says that certbot command is missing:

![image](https://user-images.githubusercontent.com/37015808/86109858-6ad12000-baf7-11ea-8d32-ac7ffcc02338.png)

I am operating on Ubuntu 18.04, the ports are properly open on the server's firewall.

Any Ideas of what should I do?

Thanks in advance!

**Comment by saghul** [comment]
You must be using old images, we switched to certbot-auto. Please update and give it another try.
