### ISSUE TITLE
Adding lobby feature to configuration

### ISSUE THREAD

**Issue by mfts** [jitsi/docker-jitsi-meet#666]
Hi there, I was wondering when you are adding the lobby feature to the Docker images. This has been merged with the master branch of Jitsi-Meet Repo already (https://github.com/jitsi/jitsi-meet/pull/6621/commits/273f357131fa629bb11e9b2e429fb118ae9f3af2)

I understand there are some further configurations in Prosody necessary. 

Thanks for an ETA 

Cheers,
Marc

**Comment by bluikko** [comment]
docker-jitsi-meet seems to be far behind jitsi-meet...

**Comment by mfts** [comment]
From what I understand is that they only update the docker images when they release a stable version on jitsi-meet. So even though the master branch https://github.com/jitsi/jitsi-meet is code-complete it's not an official release
