### ISSUE TITLE
Adding etherpad plugins

### ISSUE THREAD

**Issue by gioragutt** [jitsi/docker-jitsi-meet#669]
How would you add plugins to the etherpad container?

Also, I wanted to change some settings, and ended up just creating a new image (based on `jitsi/etherpad`) which overrides the `settings.json` file.

Is there a cleaner way to do that without building an image? Is the cleanest solution to override the file with a volume perhaps?

**Comment by swathikrishna1** [comment]
Hi  @gioragutt 
How did you resolve this issue?

Regards
Swathi

**Comment by gioragutt** [comment]
Nope I did not?

**Comment by saghul** [comment]
We have switched to the upstream etherpad container. Unfortunately the only way to add plugins is to rebuild the image yourself.
