### ISSUE TITLE
FATAL ERROR: JVB auth password must be set

### ISSUE THREAD

**Issue by aguilard07** [jitsi/docker-jitsi-meet#670]
Hello, I already installed Jitsi Server using docker.
I opened the ports that the guide says: 443, 80, 4443 and UDP port 10000
but when I try to start a meet, it takes me to an "went wrong loop"

I checked the logs and in the **jvb log**, I got this message:
> FATAL ERROR: JVB auth password must be set
[cont-init.d] 10-config: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

and in the jicobo log I have:
> FATAL ERROR: Jicofo component secret and auth password must be set
[cont-init.d] 10-config: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

Any ideas of how to solve this issue? Thanks in advance

**Comment by prayagsingh** [comment]
Use `gen-password.sh` to add the password to `.env` file.
