### ISSUE TITLE
how to change the default stun server?

### ISSUE THREAD

**Issue by godpit** [jitsi/docker-jitsi-meet#675]
the ENV: 

JVB_STUN_SERVERS = stun:stun.l.google.com:19302,stun:stun1.l.google.com:19302,stun:stun2.l.google.com:19302

The P2P STUN Server is still stun:meet-jit-si-turnrelay.jitsi.net:443.

how can i solve it ？ thanks a lot!

**Comment by saghul** [comment]
You need to edit config.js inside the web container.

**Comment by RedJohn14** [comment]
Change lost after Docker Container restart.

**Comment by alexander-potemkin** [comment]
@saghul , is still so? It seems like documentation says that env variable shall work, might worth to change the docs or the code?

**Comment by saghul** [comment]
There is a dedicated env var for the P2P STUN servers indeed.

**Comment by alexander-potemkin** [comment]
Thanks! If it's `JVB_STUN_SERVERS` - it seems like ignored - I keep seeing `meet-jit-si-turnrelay.jitsi.net:443` in web browser console. Or am I missing something?

**Comment by alexander-potemkin** [comment]
Thank you. I disabled P2P, as it doesn't suit my goals, guess that means I can ignore the STUN message I see in the console.

One more question, though, if you don't mind: I can see *.json files being rewritten - how am I supposed to change it directly (that's what I've seen sometimes in the tickets)? Or they are only rewritten partially, where env variables exists?

**Comment by saghul** [comment]
What file specifically?

**Comment by alexander-potemkin** [comment]
I was working with `jvb.conf`

**Comment by saghul** [comment]
The entire file is templated at boot.

**Comment by alexander-potemkin** [comment]
Ok. Then, if I happen to need to override some of it's content, I need to submit a PR to do so, I guess?

**Comment by saghul** [comment]
Yep that would be the way.

**Comment by aaronkvanmeerten** [comment]
Alternately, after some discussion, we landed a PR that may have a different path:
https://github.com/jitsi/docker-jitsi-meet/pull/1960

You should be able to provide a custom-jvb.conf in /config and have it included and used it present.

**Comment by aaronkvanmeerten** [comment]
It's a template using a gotemplate-like syntax:

The file you want is to review is probably:

https://github.com/jitsi/docker-jitsi-meet/blob/master/jvb/rootfs/defaults/jvb.conf

Then the tpl command is run on every container startup:

[tpl /defaults/jvb.conf > /config/jvb.conf
](https://github.com/jitsi/docker-jitsi-meet/blob/47d974d88cba7d1e70a88ea83f65394e96787cc1/jvb/rootfs/etc/cont-init.d/10-config#L74C1-L75C1)

For tpl syntax you can see the project here:

https://github.com/jitsi/tpl

You can also see plenty of examples in the defaults/ directories in this repo.
