### ISSUE TITLE
I need to use an Intranet environment?

### ISSUE THREAD

**Issue by mr-kin** [jitsi/docker-jitsi-meet#68]
I need to use an Intranet environment and I need to use a mobile phone. Can let certificates be used? The internal network is all IP addresses.

**Comment by saghul** [comment]
No, you cannot use Let's Encrypt certificates AFAIK.

Our setup is not designed for intranet use, you'll have to figure it out on your own, sorry.

The apps don't require to be on the public internet, but they do require valid TLS certificates, so you may need to add them to the trust store by hand.
