### ISSUE TITLE
Change Redirect Url

### ISSUE THREAD

**Issue by DiptoChakrabarty** [jitsi/docker-jitsi-meet#685]
I would like to change the url which redirects to jitsi meet (on clicking the icon) to my own site when I setup a  jistsi meet server. 
Any way possible to do that .

**Comment by saghul** [comment]
What icon?

**Comment by DiptoChakrabarty** [comment]
The default jitsi icon for example the one in left top corner , I would like to redirect or open a another site when I click on that.

**Comment by DiptoChakrabarty** [comment]
So I came to know that we should modify the interface_config.js file  
Path: /usr/share/jitsi-meet
File: interface_config.js
Parameter: JITSI_WATERMARK_LINK
In the   web/Dockerfile the following command is issued : RUN   mv /tmp/pkg/usr/share/jitsi-meet-web-config/config.js /defaults

so I am copying the modified interface_config,js from my localhost to the defaults directory however it doesn't seem to be working

This is my command  COPY  interface_config.js   /defaults/interface_config.js
however the link doesn't change in the application even though the file has changed inside the container

**Comment by saghul** [comment]
You need to move it to /config/

**Comment by DiptoChakrabarty** [comment]
> You need to move it to /config/

Yes it worked thanks a lot
