### ISSUE TITLE
JVB settings

### ISSUE THREAD

**Issue by markmadlangbayan** [jitsi/docker-jitsi-meet#69]
hello,

I have a working Jitsi-meet install on a VM, but we want to evaluate Jitsi-Meet hosted in Docker containers.  I noticed that there are JVB settings that's not in our settings when not using Docker.  What are these?  We are hosting our JVB on a separate machine, if that helps.  

https://github.com/jitsi/docker-jitsi-meet/blob/5c0776b8ed80cb30278dde1ecc926f72347ebfa3/jvb/rootfs/defaults/sip-communicator.properties#L9-L15

**Comment by saghul** [comment]
This is a different (and better) way for using multiple JVBs: they join a MUC (which we call a brewery) and jicofo joins this MUC too, this how they communicate with each other.
