### ISSUE TITLE
Cannot use any rest apis!

### ISSUE THREAD

**Issue by mmdaz** [jitsi/docker-jitsi-meet#690]
Hey every one,
I want to communicate with the Jitsi in my backend of web server.
So I am using the docker configs from https://github.com/jitsi/docker-jitsi-meet
I don't change the docker-compose file but according to FQAs I am adding `JVB_ENABLE_APIS=rest,colibri` to my `.env` file.
I am starting and trying to connect to it with curl with this:
`curl -v  http://localhost:8080/colibri/conferences` 
and see this result:

    *   Trying 127.0.0.1...
    * TCP_NODELAY set
    * connect to 127.0.0.1 port 8080 failed: Connection refused
    * Failed to connect to localhost port 8080: Connection refused
    * Closing connection 0
    curl: (7) Failed to connect to localhost port 8080: Connection refused

I am also changing the port to 4443 and get this:

    *   Trying 127.0.0.1...
    * TCP_NODELAY set
    * Connected to localhost (127.0.0.1) port 4443 (#0)
    > GET /colibri/stats HTTP/1.1
    > Host: localhost:4443
    > User-Agent: curl/7.58.0
    > Accept: */*
    > 
    * Recv failure: Connection reset by peer
    * stopped the pause stream!
    * Closing connection 0
    curl: (56) Recv failure: Connection reset by peer

Any idea?

**Comment by prayagsingh** [comment]
publish port `8080` in the `compose.yaml` file under `jvb` service. You can't access it from outside without publishing the port.

**Comment by mmdaz** [comment]
> publish port `8080` in the `compose.yaml` file under `jvb` service. You can't access it from outside without publishing the port.

**Comment by mmdaz** [comment]
> publish port `8080` in the `compose.yaml` file under `jvb` service. You can't access it from outside without publishing the port.

Hmm
I tried this but It doesn't work. I wonder that is any server up with port 8080? I don't find it in `.env` file.
Should I try with other ports? Although as I said I am trying with 4443 and 10000 ports and none of them don't work
