### ISSUE TITLE
Lobby working ?  New changes.

### ISSUE THREAD

**Issue by MKlimowicz** [jitsi/docker-jitsi-meet#692]
Hi,
I saw that new lobby related changes have been added. Does it mean that the lobby on the docker is already working ?
@saghul  Thank you for your answer.

a81ad73 prosody: add support for lobby

**Comment by saghul** [comment]
Yep, lobby should be working just fine! Just set ENABLE_LOBBY=1 and you're off to the races!

You'll need the mobile apps >= 20.3.0 for it to work, or SDK >= 2.9.1

**Comment by vkruoso** [comment]
@saghul can you clarify what would be the customer experience when accessing a server with lobby enabled on the app with a version < 20.3.0 ? Would it simply not work or there is something there?

**Comment by saghul** [comment]
Yep, they would get the reload screen.

**Comment by MKlimowicz** [comment]
@saghul  Thank you very much. Everything works correctly.

Could it be on all the time? so that I don't have to turn it on every time.

**Comment by saghul** [comment]
We don't have that feature as of yet.

**Comment by MKlimowicz** [comment]
Thanks for response. Propably i try implement it .
https://github.com/jitsi/jitsi-meet/pull/7104/commits/743ebaa381c3b82029888949e81aaeb5d37e5e26
