### ISSUE TITLE
Toolbar buttons configuration ignored by Android client

### ISSUE THREAD

**Issue by bluikko** [jitsi/docker-jitsi-meet#693]
After updating docker-jitsi-meet to stable-4857, now the Android client (also updated to the latest version) is ignoring the `TOOLBAR_BUTTONS` configuration in `interface_config.js`.

For example, live stream and recording buttons were correctly removed from the Web interface after `interface_config.js` was changed - but they are still visible in the Android client.

Not sure if this should be filed in the Android client, Jitsi or docker-jitsi-meet?

**Comment by saghul** [comment]
The Android app doesn't use those settings, never has. Do you mean the mobile web?

**Comment by bluikko** [comment]
No I meant the Android app. I thought that I had them disabled before. Closing as invalid then, thanks.
