### ISSUE TITLE
issue to starting a conference

### ISSUE THREAD

**Issue by tebareinyu** [jitsi/docker-jitsi-meet#695]
I recently downloaded and updated the new version of jitsi for docker.

I would greatly appreciate your help and sorry for the inconvenience.

Starting the conference gives me an error and says:

Unfortunately, something went wrong

The error in console is:

react_devtools_backend.js: 2273 2020-07-26T23: 32: 37.728Z [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>: UnhandledError: null Script: null Line: null Column: null StackTrace: Error: Focus error, retry after 1000
    at u._allocateConferenceFocusError (UsernameGenerator.js: 102)
    at UsernameGenerator.js: 87
    at I. Handler.handler (strophe.umd.js: 2121)
    at I.Handler.run (strophe.umd.js: 1255)
    at strophe.umd.js: 2701
    at Object.forEachChild (strophe.umd.js: 340)
    at I.Connection._dataRecv (strophe.umd.js: 2684)
    at P.Bosh._onRequestStateChange (strophe.umd.js: 4680)

I followed these steps:
Download and extract the latest release
-Alternatively, to test the latest changes clone the repository: git clone https://github.com/jitsi/docker-jitsi-meet && cd docker-jitsi-meet
-Create a .env file by copying and adjusting env.example
-cp env.example .env
-Set strong passwords in the security section options of .env file by running the following bash script
-./gen-passwords.sh
-Create required CONFIG directories
-mkdir -p ~/.jitsi-meet-cfg/{web/letsencrypt,transcripts,prosody/config,prosody/prosody-plugins-custom,jicofo,jvb,jigasi,jibri}
-Run docker-compose up -d

attached image
<img width="1440" alt="Captura de Pantalla 2020-07-26 a la(s) 5 32 45 p  m" src="https://user-images.githubusercontent.com/24235106/88492199-2b66e980-cf66-11ea-94ce-66481fafb3bf.png">

**Comment by WolfganP** [comment]
Check `docker-compose logs -f` server side for easier troubleshooting

**Comment by tebareinyu** [comment]
fix them by removing all traces of the installation including the folder:

~ / .jitsi-meet-cfg / {web / letsencrypt, transcripts, prosody, jicofo, jvb, jigasi, jibri}

then i made git clone to the latest update and it worked properly.
