### ISSUE TITLE
Using lobby feature with ldap

### ISSUE THREAD

**Issue by prayagsingh** [jitsi/docker-jitsi-meet#697]
I have couple of questions related to lobby.

1. Is it possible to use lobby with ldap? 
2. Is there any kind of relation between `lobby` and `enable_guest` like do I need to set `enable_guest` to true for lobby feature?

**My Observations**
I tried to use `lobby` feature with `ldap`. Let's say the meeting url is `meet.example.in/test`. Once I enabled the `lobby` and when other user tried to join the meeting then it lands to a new meeting on a same url i.e `meet.example.in/test`.

***Few points to note here***
1.  Every user is authenticated using ldap. 
2. When second user joins then he/she isn't getting options like `request to join` or `enter password`. 
3. `ENABLE_GUEST` is set to false because of bug #538

**Comment by JacBra** [comment]
I want to enable Lobby too in combination with authentication (using ldap).

ENABLE_AUTH=0, ENABLE_LOBBY=1, ENABLE_GUESTS=1
--> this works

ENABLE_AUTH=1, ENABLE_LOBBY=1, ENABLE_GUESTS=0
--> this works, but then every user has to authenticate -> undesired for my use case

ENABLE_AUTH=1, ENABLE_LOBBY=1, ENABLE_GUESTS=1
--> this is the situation I want (only first to enter needs to authenticate, others are guests that get into the lobby). But this scenario does *not* work: the Lobby option is not visible in the gui when I click the Shield-icon.

Does anyone know how to get this working?

**Comment by prayagsingh** [comment]
@JacBra In first case `ENABLE_AUTH=0, ENABLE_LOBBY=1, ENABLE_GUESTS=1`, If you are disabling `AUTH` then who is going to be the `moderator`?  

I tried this `ENABLE_AUTH=1, ENABLE_LOBBY=1, ENABLE_GUESTS=0` case but In my case second user is unable too see the first person on the sam url like `meet.example.in/test`.

`ENABLE_AUTH=1, ENABLE_LOBBY=1, ENABLE_GUESTS=1` : you don't need to enable guest mode for lobby.  

here the best case is seconds one. If a first person started the meeting and enables lobby then it shouldn't ask for password for second user but it is not happening as of now.

**Comment by prayagsingh** [comment]
@JacBra Are you using `docker-swarm`?

**Comment by JacBra** [comment]
@prayagsingh: no I don't use docker-swarm.

**first case**
This was just for information: in that case every user will be guest (no authentication) and then the first one who enters the room will be the moderator.

**second case**
I don't understand why the second user is not able to see the first person. I think something else is going wrong there.

**third case**
When I don't enable guest mode here, the lobby functionality will work but then every user needs to authenticate. And that is something I don't want: I only want the first user to authenticate.
When I enable guest mode (which is what I want), then the Lobby functionality is not there. This is actually my problem.

**Comment by prayagsingh** [comment]
Yes the **third case** is bit confusing because it totally cancel out the purpose of lobby. I tried lobby with `internal` auth too and same result i.e asking for password every time and sometimes even not showing the `request join via lobby` for second user.

**Comment by saghul** [comment]
The lobby is independent to authentication.

The reason why it’s not working is because we haven’t added the lobby to the authenticated virtualhost in the Prosody config. I’ll look into that for the next release.

**Comment by prayagsingh** [comment]
Thanks @ChrisPortman for adding this feature. It's an awesome feature. 
If anyone wants to try this feature then you can pull `prayagsingh/prosody:14` from dockerhub. 

This image has couple of fixes:
1. Allow jibri to start recording when lobby is enable.
2. Allow jibri to start the meeting when moderator sets a meeting password. 

**NOTE: Don't use the image in production as this is for testing purpose only.**

**Comment by saghul** [comment]
This should be fixed as of stable-5390-2.
