### ISSUE TITLE
Matching the configuration files of a debian setup

### ISSUE THREAD

**Issue by bgrozev** [jitsi/docker-jitsi-meet#7]
As @ztl8702 noticed, the configuration of jicofo and jitsi-videobridge in a docker setup does not match the one you get by installing the debian packages. Notably the properties that configure pubsub (or muc) for jicofo and jitsi-videobridge are missing.

**Comment by saghul** [comment]
@bgrozev I believe they are pretty much aligned now, so I'm going to go ahead and close this.

The Docker and Debian setups are fundamentally different in a number of ways, so I don't think we can apply exactly the same options, but let's treat each missing option independently while we move this forward.
