### ISSUE TITLE
lobby not available when using authentication?

### ISSUE THREAD

**Issue by wivaku** [jitsi/docker-jitsi-meet#700]
When using authentication (in my case: internal) there's no option to activate the lobby. When clicking on the shield icon the only option is to add a password.

When **not** using authentication the lobby functionality works fine, although I have to enable it for each session by clicking the shield. 
Using ENABLE_AUTH=0, ENABLE_LOBBY=1, ENABLE_GUESTS=0 or =1

**Comment by wivaku** [comment]
Update, it seems that to use authentication + lobby you have to disable guests.
So:
ENABLE_AUTH=1, ENABLE_LOBBY=1, ENABLE_GUESTS=0

**Comment by ChrisPortman** [comment]
The issue is that the lobby config is always applied to the "main" virtualhost.  When auth is enabled, it must be applied to the guest virtual host.
