### ISSUE TITLE
activate lobby for each session (as opposed to: allow users to activate lobby for a session)?

### ISSUE THREAD

**Issue by wivaku** [jitsi/docker-jitsi-meet#701]
I am using ENABLE_LOBBY=1
When I click on the shield icon during the session I have the option to *activate* the lobby for that session.
So it seems ENABLE_LOBBY=1 means: allow users to activate the lobby during a session.

What is the configuration so that all sessions have the lobby activated by default?

**Comment by mfts** [comment]
Hi @wivaku 

this feature is indeed not available yet but I saw that the Jitsi team is testing it on meet.jit.si sporadically. 
I've already asked a similar issue in the main repo --> https://github.com/jitsi/jitsi-meet/issues/7385

**Comment by wivaku** [comment]
Thanks @mfts !

**Comment by saghul** [comment]
Closing this in favor of the jiti-meet issue, since that's where the change needs to happen.
