### ISSUE TITLE
How can I change the maximum, minimum and ideal resolution?

### ISSUE THREAD

**Issue by castillofrancodamian** [jitsi/docker-jitsi-meet#704]

**Comment by saghul** [comment]
This has been answered many times, please search existing issues. TLDR: edit /config/config.js inside the web container.

**Comment by castillofrancodamian** [comment]
> This has been answered many times, please search existing issues. TLDR: edit /config/config.js inside the web container.

This is located in the .jitsi-meet-cfg folder?

**Comment by saghul** [comment]
Correct
