### ISSUE TITLE
production build and deployment

### ISSUE THREAD

**Issue by shubhamvishwakarma19** [jitsi/docker-jitsi-meet#708]
Hello i'm trying to create a compile code in my react js project.
How can i create the build compile code like as  other react application i made some UI changes and i want to deploy my new code on the server can you please help how can i deploy the new code my own and where is the location of compile code.

i have tried 
npm install lib-jitsi-meet --force && make
npm install lib-jitsi-meet --force && make deploy-lib-jitsi-meet

but can't see any build folder 

Thanks

**Comment by saghul** [comment]
This has nothing to do with Docker.
