### ISSUE TITLE
身份认证问题

### ISSUE THREAD

**Issue by yuwanglang** [jitsi/docker-jitsi-meet#719]
您好,
我想配置身份认证，只允许特定的账号开启会议房间。当执行“prosodyctl --config /config/prosody.cfg.lua register ywl xx.xx.xx.xx（我的IP） 1234”时，就会出现“Error: Account creation/modification not supported.”。不支持创建用户。请问这是怎么回事？

**Comment by yuwanglang** [comment]
@sapkra yes.I create a user by "prosodyctl --config /config/prosody.cfg.lua register dayu xx.xx.xx.xx(IP) 1q2w3e".but when I enter the url "https://xx.xx.xx.xx(IP)",then enter room name like "qwer", the pop-up enter the username and password. when I enter "dayu" and "1q2w3e". Still tip username or password error.

**Comment by sapkra** [comment]
I only translated your Chinese into English. But to address your issue: What's the value of the `$XMPP_DOMAIN` env var in your environment?

**Comment by yuwanglang** [comment]
in my profile,XMPP_DOMAIN=xx.xx.xx.xx(my IP)

**Comment by yuwanglang** [comment]
also ,$XMPP_GUEST_DOMAIN,$XMPP_INTERNAL_MUC_DOMAIN,$XMPP_MUC_DOMAIN,$XMPP_AUTH_DOMAIN,$XMPP_BOSH_URL_BASE,$XMPP_SERVER,I substituted "xx.xx.xx.xx"(my IP) for "meet.jitsi".

**Comment by sapkra** [comment]
I'm not sure if it is working with an IP. Can you try changing it to a domain/hostname and also add your user to it?
If you're running it locally you can also map a hostname to an IP using the `hosts` file.
If this doesn't work I'm not able to help you right now.

**Comment by yuwanglang** [comment]
OK,I will try.thank you very much.
