### ISSUE TITLE
Do docker images follow jitsi release?

### ISSUE THREAD

**Issue by chamerling** [jitsi/docker-jitsi-meet#72]
Hello here and thanks a lot for this compose based solution

I wonder if this repo is following jitsi releases? Do you push images on Docker hub on each new jitsi release? For example in https://hub.docker.com/r/jitsi/web/tags, there are just 3 tags, all of them published one month ago.

**Comment by damencho** [comment]
Yes, they are. You can see the latest release was at about the same time. 
https://github.com/jitsi/jitsi-meet/releases/latest

Please use the community forum for questions and problems before opening new issues.
