### ISSUE TITLE
Feature request/idea: remove Jibri ALSA loopback dependency on the Docker host

### ISSUE THREAD

**Issue by Daan-xyz** [jitsi/docker-jitsi-meet#721]
Follow-up to #720, requiring the **Docker host** to have an ALSA sound system strikes me as a bit odd. 

Rationale: it adds an extra setup requirement to all Docker hosts and thus reduces the ease with which you can move Docker containers around. It seems to complicate other deployments as far as I have can see (which is not that far).

I'm not a Jitsi developer, but architecturally this probably means 'tapping' the audio stream to disk at a higher level than ALSA, which would enable Jibri to not depend on ALSA at all.

Thank you for this awesome product..

**Comment by saghul** [comment]
We are looking into switching to PulseAudio, which will avoid this problem.
