### ISSUE TITLE
会议录制

### ISSUE THREAD

**Issue by yuwanglang** [jitsi/docker-jitsi-meet#722]
当我录制会议的时候，点击“开始录制”，窗口左上角的网络状态刚开始是绿的，过一会就变红。然后页面崩溃。这是我的jibri日志文件。
log.0.txt，browser.0.txt，ffmpeg.0.txt
[browser.0.txt](https://github.com/jitsi/docker-jitsi-meet/files/5127752/browser.0.txt)
[ffmpeg.0.txt](https://github.com/jitsi/docker-jitsi-meet/files/5127753/ffmpeg.0.txt)
[log.0.txt](https://github.com/jitsi/docker-jitsi-meet/files/5127754/log.0.txt)
请问有人遇到这个问题吗

**Comment by sapkra** [comment]
@yuwanglang 
It would be great if you could write your issues in English. You can also use a translator (e.g. deepl.com) like I have to do:

When I was recording a meeting, I clicked on "Start recording" and the network status in the upper left corner of the window was green at first, then red after a while. Then the page crashes. Here is my jibri log file.
log.0.txt, browser.0.txt, ffmpeg.0.txt
browser.0.txt
ffmpeg.0.txt
log.0.txt
Does anyone have this problem?
