### ISSUE TITLE
Etherpad not being recorded

### ISSUE THREAD

**Issue by tusharsonawanes** [jitsi/docker-jitsi-meet#724]
Hello, I have a running instance of docker-jitsi-meet configured with etherpad. The issue is, when I start recording, and edit my etherpad with my team, it is not reflected in the video.. Any ideas how to fix this ? @damencho @saghul

**Comment by janpoo6427** [comment]
i have same problem.

**Comment by tusharsonawanes** [comment]
@saghul @damencho any updates on this ?

**Comment by saghul** [comment]
You probably need to enable "everyone follows me" in the settings dialog, more tab. That way the recorder will see what you see.

**Comment by tusharsonawanes** [comment]
Okaye. Tested. We can close this issue. :) Thanks for the help
