### ISSUE TITLE
docker部署之后，打开网页创建会议之后，提示不好意思出错了

### ISSUE THREAD

**Issue by yangyingdong** [jitsi/docker-jitsi-meet#726]
docker部署之后，打开网页创建会议之后，提示不好意思出错了，然后进度条读完无限循环，日志文件是在哪里呢？有人遇到过这个问题吗？

**Comment by sapkra** [comment]
@yangyingdong Please use a translator instead of writing your issues in Chinese. The next time I will not translate your issues anymore. Can you please edit this issue by using English text? Tip: use deepl.com it's currently the best translator IMO.

The translation:
> After the docker deployment and after opening the web page to create a meeting, it is showing an error prompt and then the progress bar seems to be in an infinite loop. Where is the log file? Has anyone had this problem?

**Comment by yangyingdong** [comment]
This is my logs:
FATAL ERROR: Jicofo component secret and auth password must be set
[cont-init.d] 10-config: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-set-timezone: executing... 
[cont-init.d] 01-set-timezone: exited 0.
[cont-init.d] 10-config: executing... 
FATAL ERROR: Jicofo component secret and auth password must be set
[cont-init.d] 10-config: exited 1.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
How to solve this problem？Thank you.

**Comment by prayagsingh** [comment]
@yangyingdong you can close this one too. same error here `Jicofo component secret and auth password must be set`

**Comment by yangyingdong** [comment]
succeed！my jitsi  log was not deleted.
