### ISSUE TITLE
After docker deployment, after opening the web page to create a meeting, you will be prompted that there is an error

### ISSUE THREAD

**Issue by yangyingdong** [jitsi/docker-jitsi-meet#727]
After docker deployment, after opening the web page to create a meeting, you will be prompted that there is an error. After reading the progress bar in an infinite loop, where is the log file? Has anyone encountered this problem?

**Comment by prayagsingh** [comment]
Have you tried `docker logs container_name` command?

**Comment by yangyingdong** [comment]
@prayagsingh

**Comment by yangyingdong** [comment]
Jicofo 2020-08-31 06:35:40.475 SEVERE: [16] org.jitsi.impl.protocol.xmpp.XmppProtocolProvider.log() Failed to connect/login: SASLError using SCRAM-SHA-1: not-authorized
org.jivesoftware.smack.sasl.SASLErrorException: SASLError using SCRAM-SHA-1: not-authorized
	at org.jivesoftware.smack.SASLAuthentication.authenticationFailed(SASLAuthentication.java:292)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.parsePackets(XMPPTCPConnection.java:1100)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader.access$300(XMPPTCPConnection.java:1000)
	at org.jivesoftware.smack.tcp.XMPPTCPConnection$PacketReader$1.run(XMPPTCPConnection.java:1016)
	at java.lang.Thread.run(Thread.java:748)

**Comment by prayagsingh** [comment]
@yangyingdong check this logs `Jicofo component secret and auth password must be set`.  You didn't set the password for Jicofo. 

follow below steps:

1. Create a file of `.env` using command `touch .env`
2. Copy `env.example` to `.env`
3. Use `./gen-passwords.sh` script to generate the password. 
4. Now remove the previous jitsi config. check the value of `CONFIG` using command `echo $CONFIG` and remove the directories present there and then re-create those directories.
5. Run docker-compose

**Comment by yangyingdong** [comment]
@prayagsingh  Thank you very much.Succeed!
