### ISSUE TITLE
jitsi-meet prosody modules not available

### ISSUE THREAD

**Issue by RCoanda** [jitsi/docker-jitsi-meet#73]
Are the jitsi-meet prosody modules available in the container? 

I tried loading the [mod_muc_size](https://github.com/jitsi/jitsi-meet/blob/master/resources/prosody-plugins/mod_muc_size.lua) without any success. I've added `mod_muc_size` as a **XMPP_MODULES** and as a **XMPP_MUC_MODULES** in the .env file, but when I access the prosody container it's nowhere to be found.

**Comment by saghul** [comment]
Have you edited the file *after* starting the container? The env variables are only considered on the first boot, you'll need to delete the config directory and restart the containers for them to take effect.

**Comment by sapkra** [comment]
You should add the module file with an volume. We are just adding prosody modules they are used in this container to decrease the image size.

Just have a look at the prosody Dockerfile - there you will find the path to mount the volume for your custom/additional module.

**Comment by RCoanda** [comment]
Cool, thank you.

**Comment by RCoanda** [comment]
I was able to mount the prosody module, but now I am confused on how to communicate with it. I have the `http` prosody module listening on the following endpoint `sessions`, but I am unaware of how to access it.

**Comment by saghul** [comment]
5280 is the BOSH port, I think you'd need a new port for that. Please check the prosody documentation.

**Comment by sapkra** [comment]
@saghul I'm using port 5280 for my prosody plugin and it's working fine. Bosh also just uses an endpoint called `/http-bind`. The port is just the default http port of prosody.

```bash
http://<INTERNAL_PROSODY_IP>:5280/my_endpoint

# or for this example
http://<INTERNAL_PROSODY_IP>:5280/sessions
```

@RCoanda If you want to be able to access the endpoint via the browser you have to add it to the [nginx proxy config](https://github.com/jitsi/docker-jitsi-meet/blob/master/web/rootfs/defaults/meet.conf#L29) in the web container.

**Comment by poying** [comment]
@sapkra I can't load modules by adding them to `XMPP_MODULES`. But modules can be loaded after I  add them to `~/.jitsi-meet-cfg/prosody/prosody.cfg.lua`.
Is this correct behavior?

**Comment by poying** [comment]
The `XMPP_MODULES ` option will be applied if `~/.jitsi-meet-cfg/prosody/conf.d` folder dose not exist. 😖

**Comment by sapkra** [comment]
Yes, because the `prosody.cfg.lua` is just generated on the first start. If you change some env vars you have to delete this file again or remove the `/config` volume to generate the config on every start of the container.

**Comment by sapkra** [comment]
@poying Not really but maybe you have to pull a more recent image.

**Comment by poying** [comment]
I found out that I have to remove config folder whenever `.env` is updated. :satisfied:

**Comment by sapkra** [comment]
Yeah this is common problem. The easiest way to disable this behavior is to remove the /config volume in the docker-compose.yml.
