### ISSUE TITLE
jitsi-meet  record

### ISSUE THREAD

**Issue by yuwanglang** [jitsi/docker-jitsi-meet#736]
I installed the JITSI-Meet with Docker.What should I do if I want to record a meeting and read all the meeting minutes files through the interface?

**Comment by prayagsingh** [comment]
you can follow [jitsi-handbook](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker) for setting `jibri` for recording meetings. To capture the stats you can setup Grafana dashboard but first you have to enable rest api in jvb and also expose the port `8080`. You can use `curl http://localhost:8080/colibri/stats` command to check the stats.  

you can follow jitsi community for tutorials. `https://community.jitsi.org/c/install-config/docker/13`
