### ISSUE TITLE
When is the latest stable version jitsi-meet_4966 updated in docker?

### ISSUE THREAD

**Issue by mfts** [jitsi/docker-jitsi-meet#737]
When is the latest stable version (https://github.com/jitsi/jitsi-meet/releases/tag/stable%2Fjitsi-meet_4966) coming to docker? 

I can build it myself in docker but would love official support.

**Comment by saghul** [comment]
Soon. I've been away for a few weeks and am still catching up.

**Comment by mfts** [comment]
For those who are interested, I containerized the latest stable version (https://github.com/jitsi/jitsi-meet/releases/tag/stable%2Fjitsi-meet_4966) myself and are available here: https://hub.docker.com/u/mfts/

**Comment by GallandJe** [comment]
@saghul any update ?

**Comment by mfts** [comment]
@GallandJe feel free to use my images (see my previous comment).  

However, there's already a new stable release `5076`:  https://github.com/jitsi/jitsi-meet/tree/stable/jitsi-meet_5076 I will also build these images and make them public on my docker hub.

**Comment by saghul** [comment]
I appreciate the effort, but please don't advertise your images here. It will only cause confusion when people have issues with them.
