### ISSUE TITLE
jibri start error synology

### ISSUE THREAD

**Issue by gpopesc** [jitsi/docker-jitsi-meet#739]
When I start the service I get following error.
I tried to edit the path in docker compose, but the same result

Starting jibri    ... error
ERROR: for jibri  Cannot start service jibri: linux runtime spec devices: error gathering device information while adding custom device "/dev/snd": no such file or directory
Jitsi-Web last error: 2020/09/14 02:00:26 [alert] 220#220: worker process 230 exited on signal 9

**Comment by gpopesc** [comment]
after reset, the path is taken into consideration but I still got Docker api failed when I tried to launch

**Comment by bossmanpl** [comment]
Is there any solution to this situation ?
Do i have to have soundcard in synology and pass it to docker ?

**Comment by saghul** [comment]
That is not currently possible.
