### ISSUE TITLE
tls_process_client_hello:version too low

### ISSUE THREAD

**Issue by godpit** [jitsi/docker-jitsi-meet#742]
SSL_do_handshake() failed (SSL: error:1417D18C:SSL routines:tls_process_client_hello:version too low) while SSL handshaking

how to solve it? thanks a lot !

**Comment by godpit** [comment]
wget --secure-protocol=SSLv -O https:xxxxx/
error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure

**Comment by godpit** [comment]
docker-jitsi-meet_web -> nginx -> ssl.conf:
ssl_protocols TLSv1.2;

**Comment by saghul** [comment]
What are you trying to do?

**Comment by saghul** [comment]
You really should better describe what your problem it for others to help you.

I think what's happening is that you are trying to force SSLv2-3 ciphers with wget but this Docker setup defaults to TLS 1.2. This is intentional as those ciphers are insecure.
