### ISSUE TITLE
Toggle lobby via IFrame API command

### ISSUE THREAD

**Issue by arashnikoo** [jitsi/docker-jitsi-meet#744]
The current API does not support the new toggleLobby command.

![image](https://user-images.githubusercontent.com/2483335/93724455-1cfb0f80-fb5c-11ea-8f02-450cc6404f3e.png)

Solution:
https://github.com/jitsi/jitsi-meet/pull/7104

**Comment by saghul** [comment]
https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-5076 just got released, it should have that API.
