### ISSUE TITLE
How to get DOCKER_HOST_ADDRESS

### ISSUE THREAD

**Issue by tomaswarynyca** [jitsi/docker-jitsi-meet#745]
I am configuring jitsi with traefik v2 and I need to get the DOCKER_HOST_ADDRESS, how do I get that value?
PD: My operating system is Linux

**Comment by asmaps** [comment]
It's most probably the public/internet facing IP of your server (it has to be the IP under which clients/participants can reach your server)

**Comment by almereyda** [comment]
You can `curl -sL` the API endpoints from https://www.ipify.org/ to find out your public address(es):

```shell
curl -sL https://api4.ipify.org
curl -sL https://api64.ipify.org
curl -sL https://api6.ipify.org
```

**Comment by saghul** [comment]
Generally speaking STUN should be enough. When not, one has to set them manually. I'll close this for https://github.com/jitsi/docker-jitsi-meet/issues/1199 since we are going to make it possible to set multiple addreses there.
