### ISSUE TITLE
Google chrome keeps disconnecting 

### ISSUE THREAD

**Issue by meyerjo** [jitsi/docker-jitsi-meet#746]
## Description

I can connect to a room on a self-hosted jitsi and communicate via video/audio. After a period - of a length I could not determine so far - I disconnect from the room. I can immediately press the button "Rejoin now" and re-renter the room. You can find the Google Chrome log from the Developer Tools attached below. 

A different computer in the same network does not have these connection issues. I tried to clear all temporary data from Google Chrome and the application storage for this web-page. I also reinstalled Google Chrome with no effect.

---

## Current behavior
Abrupt disconnection over time.

---

## Expected Behavior
Only disconnect if the network connection fails.

---

## Steps to reproduce
Unknown. 

---

# Environment details

Ubuntu 19.04
Google Chrome Version 80.0.3987.163 (Official Build) (64-bit)

Error Log from Google Chrome console, before reload occurs:
[jitsi.domain.tld-1585940456027.log](https://github.com/jitsi/jitsi-meet/files/4429445/jitsi.domain.tld-1585940456027.log)

---

**Comment by saghul** [comment]
I'm transferring the issue to the docker repo.

**Comment by saghul** [comment]
Can you reproduce this with the latest version?

**Comment by meyerjo** [comment]
I can not reproduce it with the current version.
