### ISSUE TITLE
Jitsi - Lobby

### ISSUE THREAD

**Issue by d-sumda** [jitsi/docker-jitsi-meet#747]
Hello!

Fairly new to docker and jitsi. 

Recently update to stable-4857 and noticed the lobby support? 
Any idea on how to enable the function?  

All and any help is appreciated.

**Comment by prayagsingh** [comment]
Did you try enabling it in `.env` file?

**Comment by d-sumda** [comment]
Yah, added ENABLE_LOBBY=1 in the .env file. There was no change on the web ui (no lobby function appears) 

Managed to get the lobby function by following : "Update, it seems that to use authentication + lobby you have to disable guests. So: ENABLE_AUTH=1, ENABLE_LOBBY=1, ENABLE_GUESTS=0"

https://www.gitmemory.com/issue/jitsi/docker-jitsi-meet/700/665488989

But now got the problem of not having guest, So any input?

**Comment by prayagsingh** [comment]
Can you try `prayagsingh/prosody:14` docker image and let me know if it works? 
I think this issue would be resolved in next release(upcoming release) OR clone the code and build your own image. I think last commit was related to this issue only.

**Comment by goacid** [comment]
Also remove config/ directory (or part of it, or just files), configuration files are not recreated if the exist.

**Comment by prayagsingh** [comment]
OK. So I have switched to latest release and even I can't see the `LOBBY` option and also `TILE View` icon isn't visible. 
`ENABLE_LOBBY: 1` in `.env` file. It's a new setup hence there isn't any scope of previous config. 

**CONFIG:**
`AUTH_TYPE: internal`
`ENABLE_GUEST: 1`
`ENABLE_LOBBY: 1`

**Comment by prayagsingh** [comment]
So In my case I have figure out the reason. I'm using `Brave` browser and by default it blocks all the cookies hence It wasn't showing the `Lobby` option. Then I select  `blocked cross-site cookies` and after reload it started showing `Lobby` option. 

@d-sumda Which browser are you using?

**Comment by saghul** [comment]
This should be working with latest master.
