### ISSUE TITLE
Google Analytics how can i add it.

### ISSUE THREAD

**Issue by JanisPlayer** [jitsi/docker-jitsi-meet#753]
Where can I find the config file?
https://github.com/jitsi/jitsi-meet/blob/5cc01b074e5a9a91b8706a81b9166c41c2b4f0f4/config.js#L351
I want to add my Google Analytics ID there.
Do I have to commit the Docker Container for this?
Maybe I missed something.

**Comment by sapkra** [comment]
You should be able to add the `GOOGLE_ANALYTICS_ID` variable to the `.env` file since the latest release.

**Comment by JanisPlayer** [comment]
Hi again, do I have to delete the Docker container or is that a bug in the new version?
I actually downloaded and replaced all files from Github and also ran the docker-compose pull.
Unfortunately, I now have this problem.
![image](https://user-images.githubusercontent.com/54918417/96666480-820e7480-1357-11eb-8c6f-c80a817d9997.png)
