### ISSUE TITLE
[Question] How to setup Jitsi Web UI to manage user accounts?

### ISSUE THREAD

**Issue by falconws** [jitsi/docker-jitsi-meet#754]
I was set up docker-jitsi-meet
https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker

My .env file's auth type is here.
```
# Select authentication type: internal, jwt or ldap
AUTH_TYPE=internal
```

Now, I'm able to manage Jitsi user using Linux command
```
docker-compose exec prosody prosodyctl --config /config/prosody.cfg.lua register username meet.jitsi password
```

But, I want to set up Web UI to manage Jitsi user accounts.
How to?

I've searched and found this.
https://modules.prosody.im/mod_admin_web.html

Is this the only way? Maybe this module is buggy.

I've set up this, but it's not working. Same thing posted here.
https://community.jitsi.org/t/prosody-admin-web-with-jitsi/33012

Please help me.
Thank you for reading.

**Comment by saghul** [comment]
We don't support any UI module for adding users.
