### ISSUE TITLE
Video on/off issue after joining...

### ISSUE THREAD

**Issue by vinayakathawle** [jitsi/docker-jitsi-meet#757]
@damencho, 

Hope you are doing well in this pandemic situation.

Working on building video conferencing app using jitsi-meet with react frontend. 
I have setup jitsi on google cloud by following youtube video - https://www.youtube.com/watch?v=kOSBxvL7Y4s&t=391s and it seem working fine me. 
I have added below code at to react to connect jitsi-service I have setup,

```
options = {
    hosts: {
      domain: process.env.REACT_APP_JITSI_ENDPOINT,
      muc: "conference." + process.env.REACT_APP_JITSI_ENDPOINT, // FIXME: use XEP-0030
    },
    bosh: `https://${process.env.REACT_APP_JITSI_ENDPOINT}/http-bind`, // FIXME: use xep-0156 for that

    // The name of client node advertised in XEP-0115 'c' stanza
    clientNode: "http://jitsi.org/jitsimeet",
  };
```

PROBLEM:
Created meeting and join via 2/3 people with video & audio ON. We all can see each other and talk. When I do audio on/off its working fine. 
Now When I do video off it will get off for all that fine But when I ON video again no one can see me in the call. I can't see any error.

Please help asap.

Thanks,

**Comment by vinayakathawle** [comment]
@aaronkvanmeerten, @bbaldino @bgrozev @emcho @gpolitis @hristoterezov @ibauersachs @jmacelroy @JonathanLennox @brother @paweldomas @saghul @yanas @zbettenbuk 

Guys can you please help me?

I followed this https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart as well but only issue with video ON/OFF after joining meeting.
Even If I join meeting with Video OFF and ON during meeting opponent can't see my video.

Thanks in Advance.

**Comment by saghul** [comment]
This is not related with the Docker setup, please post in our community.
