### ISSUE TITLE
jvb colibri is running on private (127.0.0.1) server and is no longer accessible

### ISSUE THREAD

**Issue by ccoenen** [jitsi/docker-jitsi-meet#758]
With the update to stable-5076, I can't use the colibri stats any more within my docker-setup. I believe the reason is [this change from jvb, where the `/colibri` endpoint is now only serverd on the loopback address](https://github.com/jitsi/jitsi-videobridge/commit/01bde07058fdb347b2169f92282be3b6158c3e87). This is of course a sensible choice for most setups, but within docker this means you can't access it any more at all.

from within that container, I can poll this:
```sh
docker-compose exec jvb curl http://localhost:8080/colibri/stats
  {"inactive_endpoints":0,"inactive_conferences":0,"total_ice_succeeded # shortened...
```
from the outside, not so much:
```sh
curl http://localhost:8080/colibri/stats
  curl: (56) Recv failure: Connection reset by peer
```

To make this 100% clear: this worked in the previous stable. I did set colibri and rest via `JVB_ENABLE_APIS=rest,colibri` in  my `.env`. And I also set up the additional port in my `docker-compose.yml`. This is a regression stemming from (probably) that mentioned jvb change.

According to [this config documentation](https://github.com/jitsi/jitsi-videobridge/blob/master/doc/rest.md#configuration) one should be able to set `org.jitsi.videobridge.rest.private.jetty.host` - if that was set to `0.0.0.0` that should bring back the previous behaviour, or so I thought. Putting this line into `jvb/rootfs/defaults/sip-communicator.properties` did _not_ fix the problem for me, sadly.

Can someone help me get the colibri stats back?

**Comment by ccoenen** [comment]
So, my config explained as above did not apply. So I went looking where the configuration is read:

https://github.com/jitsi/jitsi-videobridge/blob/25c5f8db14a300b6e1ef83e7c7214f79dbf7b342/jvb/src/main/kotlin/org/jitsi/videobridge/Main.kt#L123-L140

combined with

https://github.com/jitsi/jicoco/blob/55b408182a329a1d8624f3384902e145aa3710d3/jicoco/src/main/kotlin/org/jitsi/rest/JettyBundleActivatorConfig.kt#L33-L45

gives us this string for legacy config:
`org.jitsi.videobridge.rest.private.jetty.host` as seen above. Odd. Should work.

So I wondered, why this was not working. Turns out, this was not written to my `CONFIG`-location, even though I deleted it between restarts of `jvb`. I may have completely missed where those config files are coming from. Either way, adding

```
org.jitsi.videobridge.rest.private.jetty.host=0.0.0.0
```

directly to the generated config in `CONFIG` dir, works fine. But if I add this line to `jvb/rootfs...` it does not.

what is the right path to make these configurations a little bit more permanent?

**Comment by sapkra** [comment]
I had the same issue using health checks, applied your line and it works within my own built image. I've created a PR for it. #761

**Comment by tusharsonawanes** [comment]
Adding 

`org.jitsi.videobridge.rest.private.jetty.host=0.0.0.0
`

to jvb containers config/sip-communicator.properties 

solved the issue for me.

**Comment by tusharsonawanes** [comment]
@saghul can we please make these changes in 5076 ?

**Comment by saghul** [comment]
We'll have a new release soon 👍
