### ISSUE TITLE
end/terminate a session automatically

### ISSUE THREAD

**Issue by mmdaz** [jitsi/docker-jitsi-meet#759]
Hey there!
I want to end/terminate a session/room after a certain period of time.
Is there any API or configuration for this?

**Comment by sapkra** [comment]
I don't think there is but for those topics [the community forum](https://community.jitsi.org/) can be helpful or you could ask the jitsi team in the next [community call](https://jitsi.org/thecall/).

There are some ways to implement it by yourself for sure.

**Comment by mmdaz** [comment]
> I don't think there is but for those topics [the community forum](https://community.jitsi.org/) can be helpful or you could ask the jitsi team in the next [community call](https://jitsi.org/thecall/).
> 
> There are some ways to implement it by yourself for sure.

ok
Thanks!
