### ISSUE TITLE
How to properly configure config.js now

### ISSUE THREAD

**Issue by larscom** [jitsi/docker-jitsi-meet#768]
Hi,

I've seen alot of settings have moved to ENV variables in the latest version.

But alot of variables aren't available there, which means i have to edit config.js with the settings which aren't available as ENV.
The problem is that the edited config.js doesn't persist through a restart of the container...

How can i persist settings now?

**Comment by ludovicm67** [comment]
You can see my comment here: https://github.com/jitsi/docker-jitsi-meet/issues/764#issuecomment-704612908.

**Comment by larscom** [comment]
hi, i've seen that post. This post is actually a response to that one so to say.

For example:

Some settings as example which can't be set as ENV:

`preferredCodec`  or `disabledCodec` on the 'videoQuality' object.

`startAudioOnly` on the root object.

and many more specific settings.

You could change the default `rootfs/defaults/settings-config.js` and build your own docker image, but then i rather prefer the old situation where `jitsi-meet-cfg` is persisted through a volume.

Or i am completely wrong and missing something here ;)

**Comment by ludovicm67** [comment]
You can mont a volume at `/defaults`.

You will need to copy all files from `/web/rootfs/defaults` (from this repo) and create two files: `config.js` and `interface_config.js`.

In the two files you create you can setup your custom values as before.

I will also see if I have time to make a PR for the configuration keys you need, so that you can also configure them using environment variables directly.

**Comment by saghul** [comment]
You can have a config-custom.js file in the config volume which will always be applied last: https://github.com/jitsi/docker-jitsi-meet/blob/087f024fcb963a52243b3b04025ee3f1e7049657/web/rootfs/etc/cont-init.d/10-config#L72

If there is a missing option, however, please do open an issue (or even better a PR) so we can add it. The idea is to have them all covered with env variables. The last release was the first move in this direction.

**Comment by saghul** [comment]
There is an interface-config-custom.js now where you can add custom changes.

**Comment by pnunesdefensepoint** [comment]
Where can I find it? Thank you!

**Comment by saghul** [comment]
All you have to do is mount this file: https://github.com/jitsi/docker-jitsi-meet/blob/862986a6bdb76c2cd53417909a24a79787aa671a/web/rootfs/etc/cont-init.d/10-config#L132
