### ISSUE TITLE
Scaling Videobridge

### ISSUE THREAD

**Issue by cyril94440** [jitsi/docker-jitsi-meet#77]
Hi there,

Thanks for this docker which makes the install very easy.
However, I am trying to put in place a scalable architecture meaning that the Videobridge container must be able to scale and connects to prosody from another instance. What is the best way to achieve that? Is this docker suitable for such a use case? 

I tried to launch the videobridge on a second EC2 instance but it seems that it can't communicate with the XMPP server properly.

Thanks

**Comment by Blackclaws** [comment]
Have you tried docker swarm with replication set for this container? Usually requests to that container then get automatically load balanced

**Comment by v-deva** [comment]
Anyone update on this issue... ?

**Comment by cyril94440** [comment]
I mostly add issue related to ports available between containers but not on the host which is not a problem when all containers are on a single server. So I opened the ports of the XMPP server, I think there are 3 of them but I managed to find all the needed information on the internet. Then I restricted the access on this port from/to a single security group so that they can communicate with each other without exposing anything outside of the security group.
For the auto-scaling, I found a nice article/video on the jitsi website that describes how to setup a network bandwith rule to trigger scaling up and down. 
Finally everything was working well ;)

**Comment by YUEJINYUAN** [comment]
@cyril94440 Can you share your steps or that article/video? I'll be very grateful for your help.

**Comment by v-deva** [comment]
> I mostly add issue related to ports available between containers but not on the host which is not a problem when all containers are on a single server. So I opened the ports of the XMPP server, I think there are 3 of them but I managed to find all the needed information on the internet. Then I restricted the access on this port from/to a single security group so that they can communicate with each other without exposing anything outside of the security group.


Can you detail me the steps you have taken to configure multiple video bridge containers for a single XMPP host ? Thank you.

**Comment by sapkra** [comment]
@YUEJINYUAN  https://jitsi.org/tutorials/

**Comment by sapkra** [comment]
Closing it in favor of #372
