### ISSUE TITLE
Is JVB destination port random?

### ISSUE THREAD

**Issue by Daiki-Kawanuma** [jitsi/docker-jitsi-meet#775]
Hello everyone,

Could I ask a question about JVB destination port ?

I'm using Jitsi in LAN.
We can use video sharing with 3 or more people in place A(without FW).
(I have already set "DOCKER_HOST_ADDRESS" as Docker Host IP.)
```
# IP address of the Docker host
# See the "Running behind NAT or on a LAN environment" section in the README
DOCKER_HOST_ADDRESS=10.xx.xx.xx

# Media port for the Jitsi Videobridge
JVB_PORT=50001
```

But we cannot use video sharing 3 or more people in place B(with FW).
(If the number of attendance is two people, they can use video sharing because video is shared by P2P without JVB, I understand.)

![image](https://user-images.githubusercontent.com/15085341/95553955-5b446a00-0a4a-11eb-997d-abff692b7745.png)

According to my research, JVB seems to send data on UDP:5xxxx. These ports are blocked by the FW!
```
$ docker logs jitsi_jvb
INFO: new Pair added: 10.xx.xx.xx:50001/udp/srglx -> 10.aa.aa.aa:51259/udp/host (stream-8cf17952.RTP). Local ufrag 1k8fq1ek01epau
```

I hope JVB destination port can be static. Is it possible?

**Comment by saghul** [comment]
The destination port is dynamic because it's selected by the endpoints. You can only control the port in the JVB. You should allow anything with source or destination on that port.

**Comment by Daiki-Kawanuma** [comment]
@saghul Thank you for  your kind reply.

Is there a range of ports? (example: 50001~55000)
I think I can handle it if the port range is fixed.

**Comment by saghul** [comment]
There isn't. It's likely a random port (they probably bind to port 0).

**Comment by Daiki-Kawanuma** [comment]
Thanks!

**Comment by Daiki-Kawanuma** [comment]
@saghul I'm sorry but cloud you let me ask one more question?

After that, I set `JVB_TCP_HARVESTER_DISABLE=false`.
And then, below logs were shown.
```
INFO: new Pair added: 10.xx.xx.xx:50002/tcp/srflx -> 10.aa.aa.aa:9/tcp/host
```

Is TCP:9 port static?
