### ISSUE TITLE
Build interface config at runtime based on .env

### ISSUE THREAD

**Issue by parruc** [jitsi/docker-jitsi-meet#778]
A bunch of interface configuration option have been removed from whitelist in jitsi last release and cannot be overridden by the client anymore: for example 
SHOW_JITSI_WATERMARK and SHOW_WATERMARK_FOR_GUESTS.

Would be great if what have been recently done for config.is (runtime build based on .env vars) could be done also for interface_config.js, at least for not whitelisted configurations.

Reference to one of the discussion on the jitsi protect:
https://github.com/jitsi/jitsi-meet/issues/7843

**Comment by saghul** [comment]
We started to do this for config.js already, so yeah this one is coming.

**Comment by RES-1** [comment]
Meanwhile `TOOLBAR_BUTTONS` exists in the template for ".env". However, this parameter does not seem to have any effect yet. Is that because it's still being worked on?

**Comment by saghul** [comment]
Not it should actually be working just fine.

Please open an issue if it doesn't.

I'm closing this one since the config is now regenerated.
