### ISSUE TITLE
How do I install Jitsi from Docker Hub?

### ISSUE THREAD

**Issue by keunes** [jitsi/docker-jitsi-meet#779]
I've seen the install instructions in the [Jitsi Handbook](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker), but it instructs you to download and clone the repository and manually make an `.env` file. However, I started with following this [Digital Ocean guide to install and start using Docker](https://www.digitalocean.com/community/tutorials/how-to-install-and-use-docker-on-debian-10#step-4-%E2%80%94-working-with-docker-images).

In the Digital Ocean guide they don't use .env files, but take images from Docker Hub. I see that there are over 10 million pulls of [Jitsi Web on Docker Hub](https://hub.docker.com/r/jitsi/web). So I assume that can be used as well (otherwise there wouldn't be so many pulls).

However simply trying to run that image doesn't work. So my question is: how to proceed after pulling the image? Or would that not work?

**Comment by sapkra** [comment]
I think everything is described in the handbook. What exactly is you problem with those instruction?

You have to configure your environment using .env and then start docker-compose.

**Comment by keunes** [comment]
Hi @sapkra 

Thanks for chipping in. I should note I'm new to docker, and are just getting a basic understanding of images and containers.

As I wrote, I started using the Digital Ocean guide, which introduces these containers and images.
The manual in the handbook seems to describe a whole different process, with .env files and docker-compose (as you mention as well).

Is it not possible to get Jitsi running without this 'compose' process?

**Comment by sapkra** [comment]
Jitsi has not just one container you can start. Instead jitsi is splitted into several different servers which have to to communicate with each other. The docker-compose file orchestrates the connections in-between the containers. If you want to run it without docker-compose you have to do it manually or use other deploy configs you can find in the examples directory.
docker-compose is an official docker tool which just helps to configure and start such complex deployments. Of cause you can also use these configs of the `yml` file as parameters for the docker command.

Other methods than docker-compose are not official supported by this repo.

**Comment by keunes** [comment]
I watched some videos and learnt about docker-compose. Thank you!
