### ISSUE TITLE
Can't able to view video conference for more than two persons 

### ISSUE THREAD

**Issue by remin23** [jitsi/docker-jitsi-meet#78]

**Comment by saghul** [comment]
Aare you running your setup on the local LAN or on a public server? Did you set DOCKER_HOST_ADDRESS?

**Comment by remin23** [comment]
running on LAN. nope, not set any host address...

**Comment by saghul** [comment]
Then please read the documentation. It's excplicitly mentioned.

**Comment by remin23** [comment]
i have set the DOCKER_HOST_ADDRESS. Now it seems fine on LAN... Thanks for your info!!!

**Comment by HichamBali** [comment]
Hi, It's running in a LAN when i set a Docker Host Adress, but can't access from outside(Public) when publish it on the firewall
