### ISSUE TITLE
org.jitsi.jicofo.auth.URL only for XMPP

### ISSUE THREAD

**Issue by tsproesser** [jitsi/docker-jitsi-meet#780]
Right now the `.Env.XMPP_DOMAIN` is always prefixed with an `XMPP:` - this way `EXT_JWT:` can't be configured via variables and needs to be adopted after boot.

Furthermore the following properties can't be configured for Jvb:

```
org.ice4j.ice.harvest.NAT_HARVESTER_LOCAL_ADDRESS
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS
org.jitsi.videobridge.rest.COLIBRI_WS_DISABLE
```

**Comment by paweldomas** [comment]
`EXT_JWT` was never meant to be used with neither of the authentication methods configurable through `docker-jitsi-meet`

**Comment by tsproesser** [comment]
Sorry but I don't understand what you mean. I've set up a `docker-jitsi-meet` with token authentication and want only moderators to be able to create new rooms. Accordning to the documentation [https://jitsi.github.io/handbook/docs/devops-guide/secure-domain](Secure Domain setup) I've set these properties and they are working. Only problem is that I need to do this manually in the config files and can not use env-Variables.

But it is working.

**Comment by paweldomas** [comment]
Do you use two different XMPP domains? Or how do you differentiate between moderators and non-moderator users?

**Comment by tsproesser** [comment]
Moderators do have a token and guests dont. Or I set the `moderator="false"` property using this module:

[jitsi-token-moderation-plugin](https://github.com/nvonahsen/jitsi-token-moderation-plugin).

Anyway, it should work without and is a stock Jitsi-Setup: JWT plus moderators only can create room.

**Comment by paweldomas** [comment]
I'm not quite sure how Jicofo would differentiate between moderators and non-moderator users without 2 separate domains.
Do you have `JWT_ALLOW_EMPTY` set to `true`? I'm trying to find a combination of options which would make sense to bring back the `EXT_JWT` config. The thing is `EXT_JWT` is not recommended for use with just jwt authentication alone without guest+moderator access. That's because it will slow down conference startup and create authentication sessions in Jicofo.

**Comment by tsproesser** [comment]
Tbh I cant tell you - I just followed the guide https://jitsi.github.io/handbook/docs/devops-guide/secure-domain that tells me to use "EXT_JWT" when using tokens - and it works. Guessts cant open rooms. And yes, JWT_ALLOW_EMPTY is set to true.

**Comment by saghul** [comment]
We restored the EXT_JWT usage.
