### ISSUE TITLE
unable to load jitsisrtp: libcrypto.so.1.0.0 missing

### ISSUE THREAD

**Issue by ralfi** [jitsi/docker-jitsi-meet#781]
Hi all,

my jitsi videobridge (latest master pull today) log tells me ...

> INFO: ICE connected,
INFO: Starting DTLS handshake,
INFO: Harvester used for selected pair for stream-7c0eae1f.RTP: srflx,
INFO: Initialized a new PartitionedByteBufferPool with 8 partitions.,
INFO: Negotiated DTLS version DTLS 1.2,
INFO: DTLS handshake complete,
WARNING: Unable to load jitsisrtp: java.lang.UnsatisfiedLinkError: /usr/share/jitsi-videobridge/.cache/JNA/temp/jna8591833635793465133.tmp: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory,
WARNING: Chosen factory class "OpenSSL" not working for AES/CTR/NoPadding: No such algorithm: AES/CTR/NoPadding,
INFO: AES benchmark (of execution times expressed in nanoseconds): SunJCE 8593, BouncyCastle 33272, SunPKCS11 13959 for AES/CTR/NoPadding,
INFO: Will employ AES implemented by SunJCE for AES/CTR/NoPadding.

if a try to connect with my own turnserver. Everything else (for example without turnserver) works well. How can i solve this?

Thanks a lot!

**Comment by ralfi** [comment]
I get a look inside the image and - of course - this file is missed ...

**Comment by saghul** [comment]
That's a harmless warning. The fallback Java implementation will be used instead. We are ware of this and it will be fixed on the next release.

**Comment by ralfi** [comment]
Hi @saghul thanks for your reply. Please help me to understand this. Everything else works on my docker-jitsi-meet config but it is only not working with my own (provider-hosted, no firewalled) turnserver. How can i debug this? What is wrong if i have a successfull ICE connection state and DTLS handshake seeing above but no audio / video is transferred between the jitsi clients? If i take a deeper look inside the browser console no errors appears but a lot of warnings...

Regards

**Comment by ralfi** [comment]
Sorry, what do you mean with fallback Java implementation?

**Comment by saghul** [comment]
> Hi @saghul thanks for your reply. Please help me to understand this. Everything else works on my docker-jitsi-meet config but it is only not working with my own (provider-hosted, no firewalled) turnserver. How can i debug this? What is wrong if i have a successfull ICE connection state and DTLS handshake seeing above but no audio / video is transferred between the jitsi clients? If i take a deeper look inside the browser console no errors appears but a lot of warnings...

What type of TLS certificate are you using on your TURN server and what clients are you testing with?



> Sorry, what do you mean with fallback Java implementation?

We will use a slower Java based library in case the OpenSSL based one fail to be initialized.

**Comment by goacid** [comment]
https://github.com/jitsi/docker-jitsi-meet/pull/750/files#diff-6ba3189d8af59d28b873cc0790b058cf38fa12e20c2c39161da9f34b6fa1cfd4

**Comment by ralfi** [comment]
I am using letsencrypt Certs. Here is the turnserver config:

> listening-port=443
ts-listening-port=443
fingerprint
lt-cred-mech
use-auth-secret
static-auth-secret="my-own-secret"
relam="my-turnserver-fqdn"
no-tlsv1
no-tlsv1_1
cert=/etc/letsencrypt/live/"my-turnserver-fqdn"/fullchain.pem
cert=/etc/letsencrypt/live/"my-turnserver-fqdn"/privkey.pem
no-multicast-peers
verbose
no-stdout-log
log-file=/var/log/turnserver.log

**Comment by ralfi** [comment]
@goacid for testing purpose can i do this inside the container or should i modify the docker file?

**Comment by ralfi** [comment]
@saghul I am testing with FF81, Chrome 86 and Jitsi Meet Electron App 2.4.1 from ffmuc

**Comment by goacid** [comment]
> 
> 
> @goacid for testing purpose can i do this inside the container or should i modify the docker file?

Sur you can do it inside the container directly

**Comment by saghul** [comment]
I don't have an environment to test it now, sorry. You could try to symlink the existing libcrypto, since I don't think the API changed. Kinda an ugly hack but should do in the interim.

If that works I'll be happy to take a PR.

**Comment by ralfi** [comment]
@saghul Symlink ( to at the docker image existing libcrypto.so.1.0.2 or 1.1.0 ) do not work

**Comment by saghul** [comment]
What error do you see?

**Comment by goacid** [comment]
Simlink does'nt work because it seems the version is code in the lib. I've tested that also 👎

**Comment by ralfi** [comment]
Okay, install libssl1.0.0 inside the container as deb lets disappear the error message but no video connection established

**Comment by ralfi** [comment]
I am a little bit confused about the ip adresses because IMHO they should be okay 

172.21.0.4          local IP from the JVB docker container in my Home LAN
109.41.0.175      external Smartphone IP (with Jitsi Meet App)
87.146.16.160    external IP from my Home LAN where the Jitsi Install is

**Comment by ralfi** [comment]
Okay, another idea: My Jitsi besides behind a apache reverse proxy. Could a misconfigured apache reverse proxy caused this error?

**Comment by ralfi** [comment]
After adjusting apache reverse proxy config with removing all additional settings except the reverse config:

> INFO: Nomination confirmed for pair: 87.146.16.160:10000/udp/srflx -> 93.233.149.138:37563/udp/prflx (stream-0ed8e829.RTP).,
INFO: Selected pair for stream stream-0ed8e829.RTP: 87.146.16.160:10000/udp/srflx -> 93.233.149.138:37563/udp/prflx (stream-0ed8e829.RTP),
INFO: CheckList of stream stream-0ed8e829 is COMPLETED,
INFO: ICE state changed from Running to Completed.,
INFO: ICE state changed old=Running new=Completed,
INFO: ICE connected,
INFO: Starting DTLS handshake,
INFO: Harvester used for selected pair for stream-0ed8e829.RTP: srflx,
INFO: Initialized a new PartitionedByteBufferPool with 8 partitions.,
INFO: Initialized a new PartitionedByteBufferPool with 8 partitions.,
INFO: Initialized a new PartitionedByteBufferPool with 8 partitions.,
INFO: Negotiated DTLS version DTLS 1.2,
INFO: DTLS handshake complete,
INFO: jitsisrtp successfully loaded,
INFO: Will employ AES implemented by OpenSSL for AES/CTR/NoPadding.,

three seconds later

INFO: ICE state changed from Completed to Terminated.,
INFO: ICE state changed old=Completed new=Terminated,
INFO: Running expire(),

**Comment by saghul** [comment]
This should be working as of the latest stable release.
