### ISSUE TITLE
org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS does not seam to work with 5076

### ISSUE THREAD

**Issue by tsproesser** [jitsi/docker-jitsi-meet#783]
After several tries now I am not able to get the latest version to work behind a NAT. The setting `org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS` can't be set via environment variables and it seams like it doesn't work if i set it manually. When downgrading to `4857` it works even though JVB has a lot of errors I don't understand:

> INFO: Pair failed: 172.18.0.21:3478/udp/host -> 192.168.66.102:9/tcp/host (stream-693da90d.RTP)
Oct 12, 2020 10:28:02 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: Pair failed: 10.0.14.189:3478/udp/host -> 192.168.66.102:9/tcp/host (stream-5cb0cd06.RTP)
Oct 12, 2020 10:28:02 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: Pair succeeded: 144.252.101.241:3478/udp/srflx -> 10.255.0.8:50012/tcp/prflx (stream-693da90d.RTP).
Oct 12, 2020 10:28:02 PM org.jitsi.utils.logging2.LoggerImpl log

It's running in a Docker Swarm and seams like it tries several local addresses before it uses the remote one. With the latest version `(5067)` it still tries three different addresses:

> INFO: Pair failed: 10.255.0.187:3478/udp/host -> 192.168.66.102:9/tcp/host (stream-bd905080.RTP)
Oct 12, 2020 10:23:55 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: Pair failed: 172.18.0.11:3478/udp/host -> 192.168.66.102:57101/udp/host (stream-e774b056.RTP)
Oct 12, 2020 10:23:55 PM org.jitsi.utils.logging2.LoggerImpl log
INFO: Pair failed: 10.0.14.154:3478/udp/host -> 192.168.66.102:57101/udp/host (stream-e774b056.RTP)
Oct 12, 2020 10:23:55 PM org.jitsi.utils.logging2.LoggerImpl log

But not the one configured via `org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS`. I even sometimes have to restart JVZ since he does not use the external IP, but after some restarts it works. `5076` never uses the external IP, no matter how often it gets restartet.

Furthermore, since the latest version, the clients console drops several Colibri exceptions so I just disabled it: `org.jitsi.videobridge.rest.COLIBRI_WS_DISABLE=true`. What is this even used for? How has it become part of the configuration and I am not able to disabled it via environment variables? That all seams pretty hacky ... :/

**Comment by saghul** [comment]
> `org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS` can't be set via environment variables

DOCKER_HOST_ADDRESS was always the way to configure that. Did we break that?

> Furthermore, since the latest version, the clients console drops several Colibri exceptions so I just disabled it: `org.jitsi.videobridge.rest.COLIBRI_WS_DISABLE=true`. What is this even used for? How has it become part of the configuration and I am not able to disabled it via environment variables? That all seams pretty hacky ... :/

We switched from WebRTC datachannels to WebSocket for the bridge channel communication. This may require changes in your config (like setting PUBLIC_URL) this potential for breakage is mentioned in the release notes. WebRTC datachannels are being deprecated.

**Comment by tsproesser** [comment]
Thank you very much for clarification! :) I'll give the `DOCKER_HOST_ADDRESS` instead of `org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS` a try and let you know if it worked.

> We switched from WebRTC datachannels to WebSocket for the bridge channel communication. This may require changes in your config (like setting PUBLIC_URL) this potential for breakage is mentioned in the release notes. WebRTC datachannels are being deprecated.

Ok, got it. Guess it's the change mentioned here: https://github.com/jitsi/jitsi-videobridge/blob/master/doc/web-sockets.md. Anything I need to be aware of then using a reverse proxy doing the ssl negotiation? And would you be so kind and tell me what it is used for at all? Since it worked without any adoption before switching to WebSocket.

**Comment by saghul** [comment]
In principle you shouldn't need any chance because the web container does the proxy-pass ing. Just make sure PUBLIC_URL is set.

Those channels are used for communication between the JVB and endpoints. It sends important information such as who the active speaker is.

**Comment by tsproesser** [comment]
Our docker swarm is hosted behind a reverse proxy doing the ssl negotiation. So our jitsi setup works als plain http / ws. But since I got the exception in die clients console at least I can try to find the problem.

Any idea why it worked with `4857`? And can you tell me why both versions have several `Pair failed` messages?

**Comment by saghul** [comment]
> Any idea why it worked with `4857`?

We didn't have this WebSocket connection enabled.



> And can you tell me why both versions have several `Pair failed` messages?

That's ok, they are other IPs the JVB gathered which may not work, nothing to worry about.

**Comment by tsproesser** [comment]
Thank you so much! That really helped me a lot! I'll do some checks (`DOCKER_HOST_ADDRESS`, `PUBLIC_URL` etc.) and come back as soon as possible.

**Comment by tsproesser** [comment]
Setting `DOCKER_HOST_ADDRESS` instead of `org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS` works perfectly! I've probably just used some old documentation for this scenario. Anyway, property works.

Setting `PUBLIC_URL` does set the correct url for colibri, but the latest version `(5076)` doesn't work anyway: no video / audio. We needed to configure our http proxy (muting video wasn't possible before) but after that it worked and colibri is connected - so this can't be the cause.

Here are some logs that maybe can help finding this issue:

Message that show Colibri is working:
> 020-10-13T15:36:58.860Z [modules/RTC/BridgeChannel.js] <WebSocket.e.onmessage>:  Channel new dominant speaker event:  af30db4a
2020-10-13T15:36:58.899Z [modules/RTC/BridgeChannel.js] <WebSocket.e.onmessage>:  Endpoint connection status changed: 522a093d active ? false

Error in client console:
> 2020-10-13T15:39:00.827Z [modules/connectivity/ParticipantConnectionStatus.js] <g.onTrackRtcMuted>:  No participant for id: 8ba937d2

Warning in client console:
> Logger.js:154 2020-10-13T15:46:24.004Z [modules/RTC/JitsiLocalTrack.js] LocalTrack[1,audio] 'bytes sent' <= 0:                         0


Furthermore it would be great to be able to configure all the colibri settings in the future:

```
org.jitsi.videobridge.rest.COLIBRI_WS_DISABLE=false
org.jitsi.videobridge.rest.jetty.port=9090
org.jitsi.videobridge.rest.COLIBRI_WS_DOMAIN={{ $WS_DOMAIN }}
org.jitsi.videobridge.rest.COLIBRI_WS_TLS=true
```


Anyway: as far as I understood colibri it is not necessary for audio / video to work, right? So something else must cause this issue? Works perfectly with `4857` for us.

**Comment by saghul** [comment]
Do you get any other error? ICE failed perhaps?

**Comment by tsproesser** [comment]
You mean that client console error? Nope, no `ICE failed`. Jitsi isn't even disconnection after that period of 30 seconds (I guess)? Telling that something went wrong.

No issue. All clients stay in the lobby - just without a/v.

**Comment by saghul** [comment]
Is you deployment publicly accessible? If you can share the URL privately (GH username @ jitsi dot org) I can try to repro.

**Comment by tsproesser** [comment]
Thank you so much for your offer! Right now I'm back on `4857` since the latest version didn't work for me. If you could really take the time I'd setup the latest version again and will let you check.

Too bad I can't use the latest version anyway, since there are too much client properties not configurable yet. Sure I could modify the default config but I'd rather wait for a new version where the env variables have become more stable.

**Comment by githubkoma** [comment]
i used `org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS` to expose a second Public IP Address to let it also listen on TCP 443, like explained in Post https://community.jitsi.org/t/corporate-firewalls-use-port-443-for-videobridge-with-jitsi-docker/28285/5

How can i achieve this after that change in the architecture?

Scenario i want to cover:
- Jitsi Web on Public IP 1.1.1.1:443 TCP -> Port Forward to 192.168.1.2:443 TCP
- Jitsi JVB on Public 1.1.1.2:443 TCP and :10000 UDP -> Port Forward to 192.168.1.2:4443 TCP & 10000 UDP

**Comment by saghul** [comment]
That post is somewhat incorrect. DOCKER_HOST_ADDRESS is *only* used for `org.ice4j.ice.harvest.NAT_HARVESTER_PUBLIC_ADDRESS` so just set it to your 2nd external IP. Also set `JVB_TCP_MAPPED_PORT` to 443. IIRC this last option wasn't configurable before, but it is now.
