### ISSUE TITLE
Not working with Chrome version 86.0.4240.75 (and other browsers based on this version)

### ISSUE THREAD

**Issue by raufaser** [jitsi/docker-jitsi-meet#787]
Hi everyone.

There is already a fix in the lib-jitsi-meet repository, but it has not made it's way into the docker images yet.
https://github.com/jitsi/lib-jitsi-meet/pull/1326/commits/da2461af8f9c0e5a261f74b89eec37c02f4c5cc9

To still get it running you can search and replace the fixed code in /usr/share/jitsi-meet/libs/lib-jitsi-meet.min.js in your container jitsi-meet_web_1

`docker exec jitsi-meet_web_1 sed -i "s/supportsInsertableStreams(){return Boolean(void 0\!==window.RTCRtpSender&&(window.RTCRtpSender.prototype.createEncodedStreams||window.RTCRtpSender.prototype.createEncodedVideoStreams))}/supportsInsertableStreams(){if (\!(typeof window.RTCRtpSender\!==\'undefined\'\&\&(window.RTCRtpSender.prototype.createEncodedStreams||window.RTCRtpSender.prototype.createEncodedVideoStreams))){return false;}const stream=new ReadableStream();try{window.postMessage(stream,\'*\',[stream]);return true;}catch{return false;}}/" /usr/share/jitsi-meet/libs/lib-jitsi-meet.min.js`

Have a nice one.

**Comment by tusharsonawanes** [comment]
Worked for me. (y)

**Comment by DieserMerlin** [comment]
Thank you so much!

**Comment by saghul** [comment]
This should have made it to the last one though.

**Comment by raufaser** [comment]
> This should have made it to the last one though.

It somehow didn't. Any idea why? Or am I wrong?

**Comment by saghul** [comment]
You're right, the release was cut *just* before that commit. Sigh. I'll have a release made today.

**Comment by saghul** [comment]
Fixed in https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-5142
