### ISSUE TITLE
Unfortunately, something went wrong. We're trying to fix this . Reconnecting in 15 sec ...

### ISSUE THREAD

**Issue by GF157** [jitsi/docker-jitsi-meet#789]
Enter the room number after entering the display error, reload

**Comment by tusharsonawanes** [comment]
Can you paste jvb logs ?

**Comment by groche97** [comment]
Same problem with me, where are the jvb logs? I not found these in /var/log in jvf container

**Comment by foster86000** [comment]
Same probleme for me. but i fix it. by changing CONFIG=~/.jitsi-meet-cfg to CONFIG=.jitsi-meet-cfg in the .env file!
