### ISSUE TITLE
Own logging instead of CallStats

### ISSUE THREAD

**Issue by RCoanda** [jitsi/docker-jitsi-meet#79]
I know CallStats is an inbuilt integration to jitsi and I also understand it's very good, but it also expensive. Is there a way to collect the client-side statistics?

**Comment by saghul** [comment]
Not in the same capacity at the moment.

**Comment by RCoanda** [comment]
But in what capacity can I get logging data from the clients and how?

**Comment by saghul** [comment]
What kind of logging are you interested in?

**Comment by RCoanda** [comment]
I am interested in logging statistics regarding call quality. We noticed frame rate drops, as well as connection drops, and are therefore interested to debug where the problem lies. Could you please point me in the general direction of how to enable said statistics? I am also interested in logging more descriptive statistics on the server side. Until now the only statistics I was able to collect came from the Colibri interface via the /colibri/stats endpoint.

Thank you for your help.

**Comment by saghul** [comment]
@damencho Can you help here? I don't think I can enumerate all the stats we currently support without using callstats.

**Comment by damencho** [comment]
Hey @RCoanda the realtime stats are coming from the webrtc method getStats, the information is basically what you can see on webrtc-internals page. Currently, this is only available through callstats. 
Most probably we will be working the following months on abstracting callsats so you can replace it with your own implementation. I think you can currently hack it and also do it. You just need to call your lib callstats as there is a config where to load the library from: callStatsCustomScriptUrl.
https://github.com/jitsi/lib-jitsi-meet/blob/6eb3157a84e3747ea14a11206412ff475d31271d/modules/statistics/statistics.js#L40
https://github.com/jitsi/lib-jitsi-meet/blob/6eb3157a84e3747ea14a11206412ff475d31271d/modules/statistics/statistics.js#L61

Analytics handlers mostly push data for the usage of features, some startup information as join time, time to first media etc...
