### ISSUE TITLE
Low resolution (320x180) in latest stable 5142

### ISSUE THREAD

**Issue by RandomGHUser** [jitsi/docker-jitsi-meet#793]
I've noticed that all the video feeds are capped at 320x180 although I have massive bandwidth available (connections all green).  This was not an issue in earlier docker jitsi versions.  I've tried applying the env variable RESOLUTION=720, but the line is still commented out in config.js.  

If I apply the env variable ENABLE_SIMULCAST=0, the feeds do show in HD 720, although I'm not sure the ramifications or client-side performance with ~ 300-500KB/s stream.

**Comment by saghul** [comment]
This is somewhat intentional. If nobody is receiving your video in 720p we just stop sending it at that resolution to save resources.

This behavior should kick in when using tile view for example.

**Comment by RandomGHUser** [comment]
I do understand that sending a lower-res video in tile view may make sense, but when a participant camera is set to fullscreen, shouldn't it pull in a higher resolution video?  There are no bandwidth issues at all, this limitation seems like a regression, as there are no resource limitations in play here.

**Comment by saghul** [comment]
> but when a participant camera is set to fullscreen, shouldn't it pull in a higher resolution video?

Yes, this is what should be happening.

@jallamsetty1 do we have a bug here?

**Comment by kubrickfr** [comment]
Same issue here, everybody receives video in very low res regardless of the settings

**Comment by jallamsetty1** [comment]
This is not the expected behavior and we don't see that happening on meet.jit.si. Are you able to confirm what the  client is sending up to the bridge when this is happening ? You will be able to get this value from the connectivity stats for the local video thumbnail. 
![97008128-0d2e6c80-1508-11eb-9123-a8631fc7079b](https://user-images.githubusercontent.com/54324652/97020879-1aefec00-1520-11eb-88cd-06b663acd68a.png)
You can see the requested resolution from the bridge (send max) and the resolution sent by the client. If the user is being viewed on stage, a full 720p will be requested and sent.
If you are noticing low resolutions in tile view, this could be because of a recent change in the way we request resolutions based on the thumbnail height, please find more info here for the tile view case - https://community.jitsi.org/t/poor-video-quality-latest-jitsi-update-5142-1/82505

**Comment by RandomGHUser** [comment]
On local, when I have the remote user's video fullscreen, here are the stats:
![image](https://user-images.githubusercontent.com/40616218/97029862-d873e280-1512-11eb-93b7-374912c62c32.png)

On remote user's session, viewing the attached camera fullscreen:

![image](https://user-images.githubusercontent.com/40616218/97030157-415b5a80-1513-11eb-8702-d946dd3ed4dc.png)


If it isn't happening on the jitsi site, then it must be something to do with the docker build (if they are using the same jitsi builds).  
Are you able to test the actual docker build? 


Again, if I set ENABLE_SIMULCAST=0, I will get full resolution, but this didn't need to be set before and may hinder low bandwidth connections.

**Comment by jallamsetty1** [comment]
> On local, when I have the remote user's video fullscreen, here are the stats:
> ![image](https://user-images.githubusercontent.com/40616218/97029862-d873e280-1512-11eb-93b7-374912c62c32.png)
> 
> On remote user's session, viewing the attached camera fullscreen:
> 
> ![image](https://user-images.githubusercontent.com/40616218/97030157-415b5a80-1513-11eb-8702-d946dd3ed4dc.png)
> 
> If it isn't happening on the jitsi site, then it must be something to do with the docker build (if they are using the same jitsi builds).
> Are you able to test the actual docker build?
> 
> Again, if I set ENABLE_SIMULCAST=0, I will get full resolution, but this didn't need to be set before and may hinder low bandwidth connections.

Can you please explain this scenario in more detail, including information about what kind of clients are in the call and what are the stats on each of those clients ? Also please include the browser console logs for the client that is sending low resolution up to the bridge even when it is being viewed in full screen. You can grab only the relevant logs by applying the filter `setSenderVideoConstraint`, please make sure that all log levels are selected for display.

**Comment by RandomGHUser** [comment]
Apologies, it looks as though I forgot to transfer the PUBLIC_URL variable to my .env file upon upgrading.  After ensuring that variable was set via the env file, all the clients are connecting, the resolution of the cameras are scaling properly when going fullscreen now.

**Comment by mammo0** [comment]
I also encounter this problem... 
My `PUBLIC_URL` is probably set. The workaround to set `ENABLE_SIMULCAST=0` fixes the problem for the internal users but the externals are furthermore on low resolution.
