### ISSUE TITLE
Unable to add variables to config.js (jitsi web) via rootfs files

### ISSUE THREAD

**Issue by nwvaras** [jitsi/docker-jitsi-meet#796]
Hi,

I can't add variables to the config.js file via adding variables to the files system-config.js or settings.config.js. It seems that they are being overrided by the docker image of jitsi-web.

In /web/rootfs/defaults/system-config.js
if i add a variable like: a = 1;
this doesn't get appended at the end of config.js, like it says in the file /rootfs/etc/cont-init.d/10-config.js:
`tpl /defaults/system-config.js >> /config/config.js
tpl /defaults/settings-config.js >> /config/config.js`

**Comment by Sepphod** [comment]
hi 

I have an similar issue. the config.js is not updated with my preferences at all. I see just the default settings.
it seems that this line ´tpl /defaults/system-config.js >> /config/config.js` won't be called or whatever. Very weird for me..

**Comment by nwvaras** [comment]
@Sepphod 
It seems that the directory of rootfs is not used by jitsi-web docker image. I made a workaround editing the docker-compose.yml linking the file to the inner file:
`- ./web/rootfs/etc/cont-init.d/10-config:/etc/cont-init.d/10-config:Z`

You can try with the file with your preferences

**Comment by Sepphod** [comment]
@nwvaras 
Thnx But I don't think as in the docker file you can see that rootfs is copied to / and within the web container I am able to find the defaults directory. For me it seems that the til-command is not working or it is overwritten later in the boot process.

**Comment by nwvaras** [comment]
@Sepphod 

The docker image use the file in the previous post. It seems that uses another 10-config/system-config/settings-config file, not the one in the rootfs. Not even the ones in the /defaults folder in the docker, because if i edit them they are overwritten anyway.

**Comment by Sepphod** [comment]
@nwvaras 
Ok - but the meet.conf is filled correctly (this is line 58 in rootfs/etc/cont-init.d/10-config) 
But I am not able to understand when this script is called. I can see that defaults are installed via apt-get and are copied. Meet.conf is filled correctly but the rest not . I will try your proposed workaround..

**Comment by vincentrolfs** [comment]
@Sepphod The script located at `web/rootfs/etc/cont-init.d/10-config` is being run every time the `web` container is started.

Source: https://askubuntu.com/questions/1054664/run-script-when-dockercontainer-starts

**Comment by nwvaras** [comment]
> @Sepphod The script located at `web/rootfs/etc/cont-init.d/10-config` is being run every time the `web` container is started.
> 
> Source: https://askubuntu.com/questions/1054664/run-script-when-dockercontainer-starts

That's the problem. It is not. If you make changes in that file, it gets overwrited by another 10-config file.

**Comment by Sepphod** [comment]
@vincentrolfs thx I knew that and my issue is that the config.js is not updated with my preferences. it seems that this line ´tpl /defaults/system-config.js >> /config/config.js` won't be called or whatever. Very weird for me.

**Comment by saghul** [comment]
What image version are you using? Also, if you want to add custom config modifying the default file is not the way to go. Just have a file called `custom-config.js` in the config volume and that will get appended: https://github.com/jitsi/docker-jitsi-meet/blob/5f06c3a1e881cbf7623974f171af60c630d92fc7/web/rootfs/etc/cont-init.d/10-config#L79

**Comment by Lithimlin** [comment]
> [...] if you want to add custom config modifying the default file is not the way to go. Just have a file called `custom-config.js` in the config volume and that will get appended

It would be really helpful if this was properly documented. Same with the `custom-meet.conf` for nginx and I'd assume that there are more such possibilities.
