### ISSUE TITLE
colibri stats missing keys

### ISSUE THREAD

**Issue by Bodenhaltung** [jitsi/docker-jitsi-meet#797]
I noticed at the last updates the key "loss_rate_upload" and "loss_rate_download" disappeared from "http://localhost:8080/colibri/stats" is there a reason why?

The Doku has they still: https://github.com/jitsi/jitsi-videobridge/blob/master/doc/statistics.md

**Comment by mfts** [comment]
@Bodenhaltung for me `videostreams` is somehow missing :(

**Comment by saghul** [comment]
Please report this to the video bridge repository. The Docker setup just packages it.
