### ISSUE TITLE
Remove I am the host alert dialog from Jitsi

### ISSUE THREAD

**Issue by deadpool9987** [jitsi/docker-jitsi-meet#800]
Hi 

I am new to Jisti can you please help me or guide me on my current scenario. I want to remove I am the host alert dialog from Jitsi what I want is when a user joins the meeting as a guest then he should be able to join the meeting he should not receive any alert or dialog that says waiting for a host. I am using docker installation Please help me through this it is the last hurdle in my way. I am not intending to use JWT token.
![Screenshot 2020-10-27 at 7 18 47 PM](https://user-images.githubusercontent.com/35681183/97310913-cb941d80-1889-11eb-8119-1aacc65aa3d4.png)

**Comment by saghul** [comment]
Looks like you enabled authentication, didn't you? In that case, just disable it.

**Comment by deadpool9987** [comment]
Hi 

Yeah even I think so it has been enabled how can I disable it as you know I am very new to Jitsi and can't figure this out can you please just tell me the path from where can I disable it would be great and big help for me. I have used docker to install jitsi

**Comment by deadpool9987** [comment]
Hi 

Any help, please i have been trying for so long to achieve this please help me

**Comment by saghul** [comment]
Edit the .env file and set ENABLE_AUTH to 0. Then remove your CONFIG directory.
