### ISSUE TITLE
Problem with docker permission denied config.js

### ISSUE THREAD

**Issue by Schnuecks** [jitsi/docker-jitsi-meet#801]
I setup from the docs and get the same error above.
Its like #579 

[docker_logs.txt](https://github.com/jitsi/docker-jitsi-meet/files/5446396/docker_logs.txt)
[env.txt](https://github.com/jitsi/docker-jitsi-meet/files/5446397/env.txt)
[nginx.txt](https://github.com/jitsi/docker-jitsi-meet/files/5446398/nginx.txt)

i change the directory to .jitsi-meet-cfg permission is all root:root
i deleted and recreated it many time the config is stored in there but can't be access

if anything else is needed let me know. i don't have a clue. my system ist centos 7

**Comment by saghul** [comment]
Don't run docker-compose as root.

**Comment by Schnuecks** [comment]
Ok, that the problem, didn't see that, thanks.
