### ISSUE TITLE
more env variables

### ISSUE THREAD

**Issue by badsmoke** [jitsi/docker-jitsi-meet#802]
i still miss some possibilities to customize the web config with env variables.

Or the explanations for some variables are missing:

https://github.com/jitsi/docker-jitsi-meet/blob/master/web/rootfs/defaults/settings-config.js

i am still looking for 
```
disableAudioLevels
disableThirdPartyRequests
channelLastN
enableLayerSuspension
```

what is actually the difference between "start audio only" and "start audio muted

Until the right varialbes are available, I have no other choice than to mount the config.js from the outside.

if i'm writing here anyway, there are a few more performace tips besides the above mentioned and the resolution?

**Comment by saghul** [comment]
> Until the right varialbes are available, I have no other choice than to mount the config.js from the outside.

Or you could send a PR :-)

**Comment by RandomGHUser** [comment]
Also looking for
```
enableWelcomePage
SHOW_PROMOTIONAL_CLOSE_PAGE
```
Which don't seem to be listed in the docker-compose.yml file, so I assume they are not implemented yet.  Trying to change the config.js directly, these values will be overridden on restart/recreation of container.

**Comment by pitah81** [comment]
Being able to change the defaultLanguage would also be a nice feature.

**Comment by RedJohn14** [comment]
> i still miss some possibilities to customize the web config with env variables.
> 
> Or the explanations for some variables are missing:
> 
> https://github.com/jitsi/docker-jitsi-meet/blob/master/web/rootfs/defaults/settings-config.js
> 
> i am still looking for
> 
> ```
> disableAudioLevels
> disableThirdPartyRequests
> channelLastN
> enableLayerSuspension
> ```
> 
> what is actually the difference between "start audio only" and "start audio muted
> 
> Until the right varialbes are available, I have no other choice than to mount the config.js from the outside.
> 
> if i'm writing here anyway, there are a few more performace tips besides the above mentioned and the resolution?


How did. you mount the config.js from the outside? I have Problem with STUN Server p2p

**Comment by saghul** [comment]
Closing since this is too generic. Please do open PRs for the specific options you'd like to configure.
