### ISSUE TITLE
Enable WebSockets

### ISSUE THREAD

**Issue by enricol96** [jitsi/docker-jitsi-meet#803]
Hello,
how can I enable WebSockets? I've been trying for a while, but there are different solutions both in the issues in this repository and in the forum.
What is the latest and easiest way to do it?
Thanks

**Comment by saghul** [comment]
For XMPP signalling or data channels?

**Comment by enricol96** [comment]
For XMPP signaling, sorry for not being clear.

**Comment by saghul** [comment]
It's not currently possible. Please follow: https://github.com/jitsi/docker-jitsi-meet/pull/502
