### ISSUE TITLE
Jisti-meet stable-5142 and stable-5076 doesn't work on system without ipv6.

### ISSUE THREAD

**Issue by michaeloosh** [jitsi/docker-jitsi-meet#805]
Jisti-meet doesn't work on system without ipv6 since ipv6 support has been added in docker-jitsi-meet. Tested on two systems the latest Arch Linux and Centos 7. Doesn't work when ipv6 is disabled in OS. Tested versions: Jisti-meet stable-5142 and stable-5076. Both versons work after enabling ipv6.

**Comment by saghul** [comment]
Hum, does reverting this work? https://github.com/jitsi/docker-jitsi-meet/commit/5ceaf5fd025b005c6ddfbc87b18c77fe402a8893#diff-4b5e57f6eb2f42b9039b3d1e13929295f231749c510cbe341cd68036d9af97e2

Not sure why that would be problematic since it should listen also on IPv4.

**Comment by saghul** [comment]
Can you try to edit the file and set it as such: `listen [::]:80 ipv6only=off;`

**Comment by michaeloosh** [comment]
Adding `ipv6only=off` didn't help. I still got an errors in nginx error logs:
`[emerg] 369#369: socket() [::]:80 failed (97: Address family not supported by protocol)`
or
`[emerg] 596#596: socket() [::]:443 failed (97: Address family not supported by protocol)` when disabling `listen [::]:80`

Only complete  removal of ipv6 from nginx configuration helped to start nginx and run jitsi on host with ipv4 only, so yes. reverting to https://github.com/jitsi/docker-jitsi-meet/commit/5ceaf5fd025b005c6ddfbc87b18c77fe402a8893#diff-4b5e57f6eb2f42b9039b3d1e13929295f231749c510cbe341cd68036d9af97e2 helped.

https://admin-ahead.com/forum/general-linux/address-family-not-supported-by-protocol-nginx-error/

Another option is to enable ipv6 on the host OS.

**Comment by saghul** [comment]
Hum. If you can find a way to make it work on both cases I'd take a PR (an env var defaulting to true would suffice), but it's 2020, I don't think reverting is a good idea.

**Comment by ebricca** [comment]
this might be related .. when starting via docker-compose up on the latest version (5142)
.. nginx inside the web container does not start .. error shown .. 
nginx: [emerg] bind() to 0.0.0.0:80 failed (98: Address already in use) 
.. host is ubuntu 20.04 - with ipv4 adresses configured via netplan
