### ISSUE TITLE
Update images jitsi-meet

### ISSUE THREAD

**Issue by VitaliyDemchuk** [jitsi/docker-jitsi-meet#807]
Hello. We need a function `startRecording` in (iframe API) with params for RTMP streaming. This [feature](https://github.com/jitsi/jitsi-meet/commit/fbfaed07b249bd6c2e8d969b76d374c73dd3f85c) available in version upper [5207](https://github.com/jitsi/jitsi-meet/releases/tag/jitsi-meet_5207). Please, update images on docker-hub fo jitsi-meet. Thx.

**Comment by VitaliyMitrofanov** [comment]
Hi! I'm looking forward to the release of docker images too! This update will help us with organisation of webinars. Thank you for this feature!

**Comment by saghul** [comment]
That feature hasn't made it to a stable release yet. We only make Docker image releases of stable releases. You are welcome to build the unstable images yourself, check the makefile.
