### ISSUE TITLE
Prosody is unable to listen to disconnect/close event from users.

### ISSUE THREAD

**Issue by fais3000** [jitsi/docker-jitsi-meet#817]
Scenario.

We have a public jitsi chatroom. As it doesn't have password, bad users are able to spam it by opening multiple tabs. We are trying to limit one session per IP. We are able to restrict the user by detecting their IP in prosody when they authenticate. However we are unable to detect when a browser session is closed back in prosody. This event "resource-unbind" should fire when a session is closed. There is an issue with current version of prosody used by jitsi, where it is not notified when a browser is closed by a user. It is fixed in the latest version 0.11.7. Jitsi docker is using 0.11.5. 

**So we need to update prosody to 0.11.7.** 

These are relevant issues: https://issues.prosody.im/1234 & https://issues.prosody.im/1474

**Comment by saghul** [comment]
You can build the images yourself, or wait until we make a new release, which will include the latest and greatest.

**Comment by damencho** [comment]
@fais3000 I was reading the bug reports and the fix just optimizes the close to be earlier in certain cases. Check out the second report says that the close happens with a 20 seconds delay. 

So the web clients send presence-unavailable when the tab is closed or hangup button is clicked. And the session should be destroyed then ... If there was a network problem, that should happen after some time, like 60 seconds or so ...

**Comment by saghul** [comment]
There is a new stable version out which updates Prosody to 0.11.7.
