### ISSUE TITLE
Make settings in config.js without .ENV - every reboot from container delete settings

### ISSUE THREAD

**Issue by RedJohn14** [jitsi/docker-jitsi-meet#819]
Hello,

How can I make settings in config.js without .ENV variables? e.g. STUN Server and variable **useStunTurn: true,**.

Any idea what I must do to have this settings persistent? I mounted **config.js** like this:

`- ${CONFIG}/default-config/config.js:/defaults/config.js`

Will not work!

Any ideas?

**Comment by saghul** [comment]
You can't. The config.js file is rebuilt on every boot from the supplied env variables.

**Comment by RedJohn14** [comment]
> You can't. The config.js file is rebuilt on every boot from the supplied env variables.

And how I can set the settings and change STUN Server and active useStunTurn: true,

**Comment by saghul** [comment]
> And how I can set the settings and change STUN Server

Looks like we don't have an ENV variable for that yet! Care to send a PR?

>  active useStunTurn: true,

This is now the default.
