### ISSUE TITLE
JWT doesn't work on some version...

### ISSUE THREAD

**Issue by davide-medina** [jitsi/docker-jitsi-meet#821]
I installed different versions of docker jitsi because I had needed to use jitsi with JWT.
Only with stable-4857 I finally found the working version; I tried the stable-5142, stable-4627 and with the git clone of the repository.

After some tests, I found that if I change the AUTH_TYPE in 'jwt', the prosody config lua is generated always with authentication  'anonymous'. It looks like it doesn't take the if conditions. The env variables are correct inside the container but the config file is not generated correctly.

**Comment by saghul** [comment]
You need to remove the config volume for the config files to be generated, did you do that?

**Comment by davide-medina** [comment]
You're right!! My fault!
But it's not possible to update the config without delete the all .jitsi-meet-cfg folder?
Because if I use a prosody-plugin-custom, I have to reupload it every time.

**Comment by saghul** [comment]
Not at the moment, sorry.

**Comment by davide-medina** [comment]
Ok, thank you for your support.

**Comment by GGVidal** [comment]
The config file that you mentioned is ~/.jitsi-meet.cfg/ ? @saghul

**Comment by hiteshsaini33** [comment]
> I installed different versions of docker jitsi because I had needed to use jitsi with JWT.
> Only with stable-4857 I finally found the working version; I tried the stable-5142, stable-4627 and with the git clone of the repository.
> 
> After some tests, I found that if I change the AUTH_TYPE in 'jwt', the prosody config lua is generated always with authentication 'anonymous'. It looks like it doesn't take the if conditions. The env variables are correct inside the container but the config file is not generated correctly.

Bro can you tell me the env file settings for jwt and jwt code for jwt.io

**Comment by hiteshsaini33** [comment]
> You need to remove the config volume for the config files to be generated, did you do that?

bro, can you tell me the env file settings for jwt and jwt code for jwt.io

**Comment by davide-medina** [comment]
> > I installed different versions of docker jitsi because I had needed to use jitsi with JWT.
> > Only with stable-4857 I finally found the working version; I tried the stable-5142, stable-4627 and with the git clone of the repository.
> > After some tests, I found that if I change the AUTH_TYPE in 'jwt', the prosody config lua is generated always with authentication 'anonymous'. It looks like it doesn't take the if conditions. The env variables are correct inside the container but the config file is not generated correctly.
> 
> Bro can you tell me the env file settings for jwt and jwt code for jwt.io

You will find everything you need here: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#authentication-using-jwt-tokens
