### ISSUE TITLE
Jibri container not started on synology

### ISSUE THREAD

**Issue by bossmanpl** [jitsi/docker-jitsi-meet#824]
Is there a way to debug container that does not start on synology docker ?
Other containers work flawessly

**Comment by sapkra** [comment]
You could start the containers and look at the console output inside them. This would be very helpful.

**Comment by bossmanpl** [comment]
@sapkra, well it is started and right away stopped, no output in logs. How to debug that ?. If i set restart container on stop, it makes a loop constantly restarting.

**Comment by sapkra** [comment]
Do your synology has an ARM processor?

**Comment by bossmanpl** [comment]
Sorry i now see in main docker log: jitsi_jibri failed: {"message":"linux runtime spec devices: error gathering device information while adding custom device "/dev/snd": no such file or directory"}.

No it is intel, whole jitsi works fine, just only jibri is making problem.

**Comment by sapkra** [comment]
We already have an issue for it:
https://github.com/jitsi/docker-jitsi-meet/issues/739
