### ISSUE TITLE
Add tokenAuthUrl to .env config

### ISSUE THREAD

**Issue by D3473R** [jitsi/docker-jitsi-meet#827]
Hi,

during implementing a feature request in https://github.com/D3473R/jitsi-keycloak I noticed that the config.js is overwritten on ever container up. For this feature to work in need to set the `tokenAuthUrl` for jitsi redirecting me to my keycloak auth app.
Can you add a `TOKEN_AUTH_URL` parameter to the env file which sets it in the `config.js` file?

Regards,
D3473R

**Comment by saghul** [comment]
You can create a PR adding it here: https://github.com/jitsi/docker-jitsi-meet/blob/master/web/rootfs/defaults/settings-config.js the advanced section sounds about right. Otherwise I'll get to it as time allows.
