### ISSUE TITLE
Jitsi base debian image security support

### ISSUE THREAD

**Issue by akdsad** [jitsi/docker-jitsi-meet#836]
jitsi base docker file is based on debian stretch. Debian stretch security support ened on july 6 2020.

is there any plan to update debian package?

https://www.debian.org/News/2020/20200709#:~:text=The%20LTS%20Team%20has%20taken,ending%20on%20June%2030%2C%202022.

**Comment by saghul** [comment]
From https://wiki.debian.org/LTS/Using

~~~
Important: Debian 9 stretch LTS only supports i386, amd64, arm64, armel and armhf. Users of other architectures are encouraged to upgrade to Debian 10 buster.

The current LTS version is Debian 9 stretch and will be supported from 2020-07-06 to 2022-06-30
~~~

Am I missing something here? Stretch LTS gets support until 2022. Granted, we'll update before then! Work has been ongoing and we are 1 package away from being able to pull the trigger, but there is no security concern that I'm aware of at this time.

**Comment by prayagsingh** [comment]
@saghul There are so many vulnerabilities in terms of library that we are using. I created an issue on sep 2. So what I did that I scanned the jitsi image using Snyk(or trivy to check CVE). Please check below issue. I can understand it isn't easy to update the libraries with just a single click of button because of huge dependency. 

https://github.com/jitsi/docker-jitsi-meet/issues/732

**Comment by saghul** [comment]
Looks like I missed that one, sorry about that!

At a quick glance I don't see how updating Debian will solve any of those though. Jitsi Meet and Jicofo are provided by us, and we use the maintainers repo for Prosody, not Debian's.

Do you have a list of critical and / or explotable vulns? There is a lot of low severity noise in there.

**Comment by prayagsingh** [comment]
> Looks like I missed that one, sorry about that!
> 
> At a quick glance I don't see how updating Debian will solve any of those though. Jitsi Meet and Jicofo are provided by us, and we use the maintainers repo for Prosody, not Debian's.
> 
> Do you have a list of critical and / or explotable vulns? There is a lot of low severity noise in there.

I'll do it again with both stable and unstable build and will share the info.

**Comment by saghul** [comment]
Please help test https://github.com/jitsi/docker-jitsi-meet/pull/840

**Comment by prayagsingh** [comment]
Hello @saghul 
 I scanned latest docker images using `Snyk`. Below are the files.  You can use `docker scan image_name` command to scan the images. After 10 free scan it requires to login to `Snyk` account using command `docker scan --login --token value`. you can get the snyk token from [here](https://app.snyk.io/account)

Result:
[jicofo_medium_vul.txt](https://github.com/jitsi/docker-jitsi-meet/files/5637779/jicofo_medium_vul.txt)
[jvb_high_vul.txt](https://github.com/jitsi/docker-jitsi-meet/files/5637780/jvb_high_vul.txt)
[jvb_low_vul.txt](https://github.com/jitsi/docker-jitsi-meet/files/5637781/jvb_low_vul.txt)
[jvb_medium_vul.txt](https://github.com/jitsi/docker-jitsi-meet/files/5637783/jvb_medium_vul.txt)
[web_high_vulnerabilities.txt](https://github.com/jitsi/docker-jitsi-meet/files/5637784/web_high_vulnerabilities.txt)
[web_low_vul.txt](https://github.com/jitsi/docker-jitsi-meet/files/5637785/web_low_vul.txt)
[web_medium_vul.txt](https://github.com/jitsi/docker-jitsi-meet/files/5637786/web_medium_vul.txt)
[jibri_high_vul.txt](https://github.com/jitsi/docker-jitsi-meet/files/5637787/jibri_high_vul.txt)
[jibri_low_vul.txt](https://github.com/jitsi/docker-jitsi-meet/files/5637788/jibri_low_vul.txt)
[jibri_medium_vul.txt](https://github.com/jitsi/docker-jitsi-meet/files/5637789/jibri_medium_vul.txt)
[jicofo_high_vul.txt](https://github.com/jitsi/docker-jitsi-meet/files/5637790/jicofo_high_vul.txt)
[jicofo_low_vul.txt](https://github.com/jitsi/docker-jitsi-meet/files/5637791/jicofo_low_vul.txt)

**Comment by saghul** [comment]
This is not really something I can work with. Most of those issues can eo tb te be ignored because they are low or just used by build time tools or belong to applications not under our control like systemd.

It's a good starting point, but the signal to noise ratio us off the charts.

**Comment by saghul** [comment]
I'm going to close this issue since it started being about the base image update, which is already updated now.
