### ISSUE TITLE
Prosody not up-to-date causing broken JWT support with xmpp-websocket

### ISSUE THREAD

**Issue by sapkra** [jitsi/docker-jitsi-meet#839]
The latest prosody version currently is 0.11.7 but the stretch release is still at 0.11.5. Like [it's documented](https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md#patching-prosody), we need at least 0.11.6 to have working websockets with JWT.

### Problem
Even when force rebuilding the image it stays at 0.11.5

### Solutions
1. Maybe we should really consider to upgrade the base image.
2. It may work to download the `.tar.gz` and install it this way.

**Comment by saghul** [comment]
That's weird we use their Debian repo... maybe they haven't updated the version there?

**Comment by saghul** [comment]
Ah, they stopped updating the stretch distro. Crap.

**Comment by prayagsingh** [comment]
I changed the `prosody` to `prosody-0.11` in prosody Dockefile. it downloaded nightly build. Using it with JWT and it's working fine but its `nightly`. 
`Prosody version 0.11 nightly build 98 (2020-08-09, bacca65ce107)` . 

So the only thing is to upgrade the base image if we don't want nightly build.

**Comment by saghul** [comment]
Any chance you folks can test https://github.com/jitsi/docker-jitsi-meet/pull/840 ? It includes Prosody 0.11.7.

**Comment by prayagsingh** [comment]
> Any chance you folks can test https://github.com/jitsi/docker-jitsi-meet/pull/840 ? It includes Prosody 0.11.7.

Yes I will.

**Comment by sapkra** [comment]
It seems to work but I came across another problem within lib-jitsi-meet while trying to enable websockets: https://github.com/jitsi/lib-jitsi-meet/issues/1123

**Comment by saghul** [comment]
I did test the current XMPP WS setup, which is now the default. Did I miss anything?

**Comment by MarkusPaul1989** [comment]
After getting many issues upgrading last time, I descided to make a fresh installation today.

But now the JWT authentication doesn't work anymore.

I included Jitsi using the iFrame-API and pass the token in the URL as parameter ?jwt=sometoken wich worked properly before

Prosody shows the following error:
prosody_1 | general warn Error verifying token err:not-allowed, reason:token required

Is this issue coused by the prosody version as @sapkra descriped?

**Comment by sapkra** [comment]
That's the exact error I got using prosody 0.11.5 but it was gone after updating to 0.11.7 using the changes in #840.

**Comment by MarkusPaul1989** [comment]
Ok, my fault. 
Switched from master to stable-5142.
Now anything works fine.

**Comment by saghul** [comment]
Ok then I'm going to close this and let's continue on #840.
