### ISSUE TITLE
Is there a way to have more than 16 jibri containers on a single instance?

### ISSUE THREAD

**Issue by omazin** [jitsi/docker-jitsi-meet#847]
Because snd_aloop supports only 32 loopback interfaces, there's the 16 jibri containers per instance limit. Can the limit be extended?

**Comment by saghul** [comment]
I have no idea TBH. I wonder if switching to PulseAudio may lift that limitation.

**Comment by omazin** [comment]
Thanks, will try PulseAudio instead of ALSA.
