### ISSUE TITLE
"too many certificates already issued for exact set of domains" with latest release acme.sh

### ISSUE THREAD

**Issue by MarkErik** [jitsi/docker-jitsi-meet#849]
@saghul In regards to the change which replaces certbot with acme.sh, I have encountered a problem with the new implementation that I feel is a regression from the previous version.

Previously, I could start / stop the set of containers often, when testing changes on my server - with no issues regarding certificates. My understanding is that once the the certificate was created successfully the first time, it would check for its existence before requesting a new one from the issuing authority.

Today I pulled the latest docker versions and after bringing up and down the containers a few times, I got back "too many certificates already issued for exact set of domains", and no more certificates were issued - and thus my site is not accessible.

I see that there was a new option variable added to use the staging server during testing. https://github.com/jitsi/docker-jitsi-meet/commit/06012127e992eedb9657c3251b109257e4c6eed1

However, I feel like this is an extra step compared to what was previously available.

Or is it a bug that the existence of certificates are not being checked?

**Comment by MarkErik** [comment]
Additional note: I was able to successfully get the cert on the first few times I brought up the containers.
e.g.

```
web_1      | [Thu Dec  3 17:18:33 UTC 2020] Downloading cert.
web_1      | [Thu Dec  3 17:18:33 UTC 2020] Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/xxxxxxx'
web_1      | [Thu Dec  3 17:18:33 UTC 2020] Cert success.
web_1      | -----BEGIN CERTIFICATE-----
web_1      |xxxxxxxxxxxxxx
web_1      | -----END CERTIFICATE-----
web_1      | [Thu Dec  3 17:18:33 UTC 2020] Your cert is in  /root/.acme.sh/XYZ/XYZ.cer 
web_1      | [Thu Dec  3 17:18:33 UTC 2020] Your cert key is in  /root/.acme.sh/studio.dimitry.ca/XYZ.key 
web_1      | [Thu Dec  3 17:18:33 UTC 2020] The intermediate CA cert is in  /root/.acme.sh/XYZ/ca.cer 
web_1      | [Thu Dec  3 17:18:33 UTC 2020] And the full chain certs is there:  /root/.acme.sh/XYZ/fullchain.cer 
web_1      | [Thu Dec  3 17:18:33 UTC 2020] Run post hook:'if [[ -f /var/run/s6/services/nginx ]]; then s6-svc -u /var/run/s6/services/nginx; fi'
web_1      | [Thu Dec  3 17:18:34 UTC 2020] Installing key to:/etc/nginx/acme/XYZ/key.pem
web_1      | [Thu Dec  3 17:18:34 UTC 2020] Installing full chain to:/etc/nginx/acme/XYZ/fullchain.pem
web_1      | [cont-init.d] 10-config: exited 0.
web_1      | [cont-init.d] done.
```

**Comment by saghul** [comment]
There was previously no way to use the staging server, so what you observe was actually a problem.

Were you wiping the config volume in between runs?

Unless a bug crept in, we are only issuing the cert on container boot if it doesn't already exist. Can you check the logs and see if you see any errors? It might have failed to be copied.

**Comment by saghul** [comment]
This line prevents the cert from being issued on multiple container runs: https://github.com/jitsi/docker-jitsi-meet/blob/5f06c3a1e881cbf7623974f171af60c630d92fc7/web/rootfs/etc/cont-init.d/10-config#L19 Unless... are you recreating the container itself or just restarting it?

**Comment by MarkErik** [comment]
Dear @saghul thank you for responding so quickly.

The steps I was doing:
1. docker-compose up (note for the first run I don't use -d so that I can see if there are any issues)
2. Then ctrl-c to stop 
3. docker-compose down
4. docker-compose up -d
5. docker-compose down

And I repeat the above as I make changes to the config and interface-config. 

I've likely done that 100s of times, and never had an issue with certificates until this most recent release.

I am using the stock docker-compose.yml and following the installation steps from https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker

In the previous docker-compose.yml the certs were mounted into the container, ${CONFIG}/web/letsencrypt:/etc/letsencrypt:Z

I am not sure where the certs are stored now that will allow them to persist between runs?

**Comment by saghul** [comment]
Ah, I see now. There is a combination of 2 bugs happening! Fixed them in https://github.com/jitsi/docker-jitsi-meet/commit/1d2c68a32f4ec12e5340d0938a223e82356c3681 and https://github.com/jitsi/docker-jitsi-meet/commit/4cb181c1b2e01d97a0e8ba3b0147872f03783fe1

Any chance you can update your repo to master and build the image yourself to test? I tested here and things are created in the right place now.

**Comment by MarkErik** [comment]
I'll be happy to test in ~2 hours (have to quickly revert to old docker versions for an upcoming call in 30 minutes).

**Comment by saghul** [comment]
Hold on, found another one.

**Comment by saghul** [comment]
Ok, I pushed another fix and it's working now. Please test as follows:

- Clone latest master
- docker-compose pull
- make build_base
- make build_web
- docker-compose up --force-recreate

The certs are now stored in /config/acme-certs, but more importantly the acme.sh home dir is now used properly, so it doesn't really matter since they can be installed from the acmesh home, which is /config/acme.sh

**Comment by MarkErik** [comment]
Ok tested many times bringing the services up and down - no problem with certs.

**Comment by saghul** [comment]
`stable-5142-2` is out, thanks for your help testing!
