### ISSUE TITLE
Support NAT Setup

### ISSUE THREAD

**Issue by jkroepke** [jitsi/docker-jitsi-meet#86]
Like described here https://github.com/jitsi/jitsi-meet/blob/master/doc/manual-install.md#running-behind-nat

I want to define `org.jitsi.videobridge.NAT_HARVESTER_LOCAL_ADDRESS` and `org.jitsi.videobridge.NAT_HARVESTER_PUBLIC_ADDRESS` from `.env`

**Comment by damencho** [comment]
Mind that those properties were removed a long time ago, you need https://github.com/jitsi/ice4j/blob/master/doc/configuration.md#orgice4jiceharvestnat_harvester_local_address

But for docker you don't need to set that as there is this setting:
`JVB_STUN_SERVERS=stun.l.google.com:19302,stun1.l.google.com:19302,stun2.l.google.com:19302z
which will be used by the bridge to auto-discover those settings.

**Comment by jkroepke** [comment]
Ok. This helps me.
```
DOCKER_HOST_ADDRESS=
```
