### ISSUE TITLE
Prosody config recreation deletes custom modifications - please stop this!

### ISSUE THREAD

**Issue by pandel** [jitsi/docker-jitsi-meet#865]
Hi!

The new mechanism to re-create configuration files always on every start makes it impossible to implement changes to the prosody configuration file.

Up to now I made my own changes to support external TURN server setup, but with the current commit it is nearly impossible. My changes are overwritten every time.

ATM I wait for the container to start, make my changes and then kill prosody inside the container to let s6 take over. That works but is a rather dirty hack.
 
Please make this re-creation somehow configurable/stoppable!

Regards,
Holger

**Comment by saghul** [comment]
Support for external TURN servers can be added in the form of a new env variable (a PR is welcome). This applies in general to most config extensions.

After going through all the pain of people not expecting the config files to be regenerated and the problems is causes, we are not going back there.

So, adding ways to extend the configs with extra stuff is welcome, but we are going to continue the path of config regeneration, which is the industry standard for container based setups.

**Comment by pandel** [comment]
Ok, I understand the main argument - hard control to stop the unexperienced user to introduce problems right at the beginning.

But it would not have hurt anybody to introduce the possibility to simply stop regeneration if the more advanced users wishes to, with a switch like ENABLE_CONFIG_REBUILD or so.... or, like the custom-..conf options you introduced elsewhere, why not accept a custom conf if it is there and regenerate everything if it is not?

Simply destroying a configuration is somekind of patronization in my opinion. What if I want to try things out with my config? I am simply not able to because you kill my attempts! That is a little bit too short-sighted...

**Comment by saghul** [comment]
I used to think that way too (just look at how the project evolved, and continues to do so), but time has proven me wrong.

**Comment by pandel** [comment]
Understand... so atm I have to live with my hack, as the current TURN PRs don't fit my needs. If I find time I try to create a PR myself to add support for an external TURN server.
