### ISSUE TITLE
After upgrade to stable-5142-3 not able to open meeting

### ISSUE THREAD

**Issue by menzbua** [jitsi/docker-jitsi-meet#869]
Hi,

after upgrading to 5142-3 i have the same issue as described on #854 

In the Firefox console i see the error:
```
Firefox kann keine Verbindung zu dem Server unter wss://meet-test.menzns.de/xmpp-websocket?room=imminentbarrelspicturebriskly aufbauen. strophe.umd.js:5463:30
2020-12-09T15:48:50.843Z [JitsiMeetJS.js] <getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  Error: Strophe: Websocket error [object Event]
    log strophe.util.js:89
    error strophe.umd.js:1392
    _onError strophe.umd.js:5730
    _connect strophe.umd.js:5465
    connect strophe.umd.js:2368
    _interceptConnectArgs strophe.stream-management.js:224
    connect XmppConnection.js:231
    _connect xmpp.js:390
    connect xmpp.js:462
    connect JitsiConnection.js:61
    e connection.js:47
    d connection.js:178
    d connection.js:103
    p connection.js:208
    G conference.js:186
    createInitialLocalTracksAndConnect conference.js:634
    init conference.js:778
    p actions.web.js:31
    promise callback*p/< actions.web.js:30
    r Redux
    <anonymous> middleware.js:29
    <anonymous> middleware.js:32
    <anonymous> middleware.js:31
    <anonymous> middleware.web.js:33
    <anonymous> middleware.any.js:22
    <anonymous> middleware.js:67
    <anonymous> middleware.js:43
    <anonymous> middleware.js:61
    <anonymous> middleware.js:79
    <anonymous> middleware.js:71
    <anonymous> middleware.js:77
    <anonymous> middleware.js:39
    <anonymous> middleware.js:106
    <anonymous> middleware.js:38
    <anonymous> middleware.js:33
    <anonymous> middleware.web.js:24
    <anonymous> middleware.any.js:93
    <anonymous> middleware.js:77
    <anonymous> middleware.web.js:21
    <anonymous> middleware.js:44
    <anonymous> middleware.js:25
    <anonymous> middleware.js:16
    <anonymous> middleware.js:21
    <anonymous> middleware.js:23
    <anonymous> middleware.js:21
    <anonymous> middleware.js:111
    <anonymous> middleware.js:16
    <anonymous> middleware.js:35
Logger.js:154:22
2020-12-09T15:48:50.844Z [modules/xmpp/strophe.util.js] <t.a/r.Strophe.log>:  Strophe: Websocket error [object Event]
```

I've started with a fresh config folder. But this also does not solve the problem.

Thanks a lot.
Regards
Manuel

**Comment by saghul** [comment]
Do you have a proxy in front of the Docker setup? Can yo use the Network tab in the browser's dev tools to check what the WS failure is?

**Comment by menzbua** [comment]
Yes there is a Nginx proxy in front of the Jitsi setup. In the Network Tab i see 403 for the wss connection:

```
GET /xmpp-websocket?room=successfuldivorceslectureelse HTTP/1.1
Host: meet-test.menzns.de
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:83.0) Gecko/20100101 Firefox/83.0
Accept: */*
Accept-Language: de,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Sec-WebSocket-Version: 13
Origin: https://meet-test.menzns.de
Sec-WebSocket-Protocol: xmpp
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: cpj0c7jZQw7+NTPtlYqsXw==
Connection: keep-alive, Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket

HTTP/1.1 403 Forbidden
Server: nginx/1.19.5
Date: Wed, 09 Dec 2020 16:01:07 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Vary: Accept-Encoding
Content-Encoding: gzip
```

**Comment by tarator** [comment]
Same here since version `stable-5142-1`. When using Version `stable-5142` it works. Docker setup with Apache reverse proxy in front.
Installed with this guideline: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker

**Comment by croteb** [comment]
I have tried using the stable-5142-3 as well using a stock docker-compose up (exposed directly to internet). And /xmpp-websocket continues to not work when going into a room.  I get a 404.  I have gone into the web container and installed a few utils and tried to replicate the /xmpp-websocket nginx call and get a similar output:
`root@dfcdc4a7e490:/config/nginx# curl http://xmpp.meet.jitsi:5280/xmpp-websocket
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>404 Not Found</title>
<style>
body{
        margin-top:14%;
        text-align:center;
        background-color:#F8F8F8;
        font-family:sans-serif;
}
h1{
        font-size:xx-large;
}
p{
        font-size:x-large;
}
p+p {
        font-size:large;
        font-family:courier;
}
</style>
</head>
<body>
<h1>404 Not Found</h1>
<p>Whatever you were looking for is not here. It&apos;s behind you.</p>
<p>Unknown host: xmpp.meet.jitsi</p>
</body>
</html>`

and

`root@dfcdc4a7e490:/config/nginx# curl http://xmpp.meet.jitsi:5280/xmpp-websocket -H "Host: meet.jitsi"
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>404 Not Found</title>
<style>
body{
        margin-top:14%;
        text-align:center;
        background-color:#F8F8F8;
        font-family:sans-serif;
}
h1{
        font-size:xx-large;
}
p{
        font-size:x-large;
}
p+p {
        font-size:large;
        font-family:courier;
}
</style>
</head>
<body>
<h1>404 Not Found</h1>
<p>Whatever you were looking for is not here. Keep looking.</p>
<p>Unknown host: meet.jitsi</p>
</body>
</html>`

to mimic:

`# xmpp websockets
location = /xmpp-websocket {
    proxy_pass http://xmpp.meet.jitsi:5280/xmpp-websocket;
    proxy_http_version 1.1;

    proxy_set_header Connection "upgrade";
    proxy_set_header Upgrade $http_upgrade;

    proxy_set_header Host meet.jitsi;
    proxy_set_header X-Forwarded-For $remote_addr;
    tcp_nodelay on;
}`

**Comment by croteb** [comment]
I've also run inside the prosody container:
```
root@f9c02f5c36ef:/config/data# prosodyctl --config /config/prosody.cfg.lua check
Checking config...
Done.

Checking DNS for component muc.meet.jitsi...
    Host muc.meet.jitsi does not seem to resolve to this server (IPv4/IPv6)

Checking DNS for host guest.meet.jitsi...
    Host guest.meet.jitsi does not seem to resolve to this server (IPv4/IPv6)

Checking DNS for host recorder.meet.jitsi...
    Host recorder.meet.jitsi does not seem to resolve to this server (IPv4/IPv6)

Checking DNS for component focus.meet.jitsi...
    Host focus.meet.jitsi does not seem to resolve to this server (IPv4/IPv6)

Checking DNS for host meet.jitsi...
    meet.jitsi A record points to unknown address 172.18.0.3
    Host meet.jitsi does not seem to resolve to this server (IPv4/IPv6)
    No targets for meet.jitsi appear to resolve to this server.

Checking DNS for host auth.meet.jitsi...
    Host auth.meet.jitsi does not seem to resolve to this server (IPv4/IPv6)

Checking DNS for component internal-muc.meet.jitsi...
    Host internal-muc.meet.jitsi does not seem to resolve to this server (IPv4/IPv6)


For more information about DNS configuration please see https://prosody.im/doc/dns

Checking certificates...
Checking certificate for muc.meet.jitsi
  Certificate: /config/certs/meet.jitsi.crt
Checking certificate for guest.meet.jitsi
  Certificate: /config/certs/meet.jitsi.crt
Checking certificate for recorder.meet.jitsi
  Certificate: /config/certs/meet.jitsi.crt
Checking certificate for focus.meet.jitsi
  Certificate: /config/certs/meet.jitsi.crt
Checking certificate for meet.jitsi
  Certificate: /config/certs/meet.jitsi.crt
Checking certificate for auth.meet.jitsi
  Certificate: /config/certs/auth.meet.jitsi.crt
Checking certificate for internal-muc.meet.jitsi
  Certificate: /config/certs/meet.jitsi.crt

Problems found, see above.
```

**Comment by saghul** [comment]
> Yes there is a Nginx proxy in front of the Jitsi setup. In the Network Tab i see 403 for the wss connection:
> 
> 
> 
> ```
> 
> GET /xmpp-websocket?room=successfuldivorceslectureelse HTTP/1.1
> 
> Host: meet-test.menzns.de
> 
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.16; rv:83.0) Gecko/20100101 Firefox/83.0
> 
> Accept: */*
> 
> Accept-Language: de,en-US;q=0.7,en;q=0.3
> 
> Accept-Encoding: gzip, deflate, br
> 
> Sec-WebSocket-Version: 13
> 
> Origin: https://meet-test.menzns.de
> 
> Sec-WebSocket-Protocol: xmpp
> 
> Sec-WebSocket-Extensions: permessage-deflate
> 
> Sec-WebSocket-Key: cpj0c7jZQw7+NTPtlYqsXw==
> 
> Connection: keep-alive, Upgrade
> 
> Pragma: no-cache
> 
> Cache-Control: no-cache
> 
> Upgrade: websocket
> 
> 
> 
> HTTP/1.1 403 Forbidden
> 
> Server: nginx/1.19.5
> 
> Date: Wed, 09 Dec 2020 16:01:07 GMT
> 
> Content-Type: text/html; charset=utf-8
> 
> Transfer-Encoding: chunked
> 
> Connection: keep-alive
> 
> Vary: Accept-Encoding
> 
> Content-Encoding: gzip
> 
> ```

You need to proxy the WS connection to the /xmpp-websocket location.

**Comment by shanehughes1990** [comment]
Not to butt in here but I came across this as I was upgrading aswell, we have nginx-ingress kubernetes and one of the ENV params I needed to add was the PUBLIC_URL, I looked in console logs and it was trying to connect wss to localhost, setting that ENV in the container resolved that for me. We use terraform to deploy but concept applies to docker-compose env file aswell.
```
PUBLIC_URL = "https://${var.meet_domain}"
```

**Comment by dawidmalina** [comment]
I have also the same issue :( I am using docker-compose but in front of this setup I have AWS ALB not nginx or apache. Anyone know what must be modified? Is it even possible?

**Comment by saghul** [comment]
You can also set XMPP_WEBSOCKET to 0 to continue using regular HTTP.

**Comment by shanehughes1990** [comment]
> I have also the same issue :( I am using docker-compose but in front of this setup I have AWS ALB not nginx or apache. Anyone know what must be modified? Is it even possible?

I was doing some reading, we are on google platform but it says alb from aws support websocket it's likely just a setting in the lb somewhere to enable it.

**Comment by Turakar** [comment]
> Not to butt in here but I came across this as I was upgrading aswell, we have nginx-ingress kubernetes and one of the ENV params I needed to add was the PUBLIC_URL, I looked in console logs and it was trying to connect wss to localhost, setting that ENV in the container resolved that for me. We use terraform to deploy but concept applies to docker-compose env file aswell.
> 
> ```
> PUBLIC_URL = "https://${var.meet_domain}"
> ```

For me the problem was that I only set this on the web container and not on the prosody container. Setting this on the prosdy container solves the issue for me.

**Comment by menzbua** [comment]
Well, the PUBLIC_URL also solved the problem for me. I don't have to do any modifications in my nginx reverse proxy configuration. I have to set two things. 
First in the .env File add or uncomment the PUBLIC_URL variable. 
Second in the docker-compose.yml file add the env Variable to the prosody container:

```
    prosody:
        image: jitsi/prosody:latest
        .....
       environment:
            - AUTH_TYPE
             ....
            - PUBLIC_URL
```

After restarting the Containers everything is working with the latest Version from the repo.

Thanks to all for helping.

Regards
Manuel

**Comment by prayagsingh** [comment]
Is anyone using `WSL2` and `Docker for Desktop` to run jitsi-docker for testing? 
I'm continuously getting `websocket error 403` even with the latest images. If I remove below part from jvb.conf then everything works fine.
```
public {
            host = 0.0.0.0
            port = 9090
        }
```

Please let me know if someone else encountered similar issue and able to fix it.

**Comment by mcrapts** [comment]
Jitsi is not working for me either. Apparently a lot of Jitsi has changed but none of the documentation is updated. In any case it's impossible now to host your own Jitsi environment with a reverse proxy. I simply updated my Jitsi environment which has been working fine for years with a simple `docker-compose pull` and nothing works anymore all of a sudden.

**Comment by saghul** [comment]
Have you tried disabling WebSocket for XMPP as mentioned above?

**Comment by mcrapts** [comment]
That finally worked. Thanks. Though it is a workaround and not a fix.

**Comment by tarator** [comment]
@mcrapts if you have an Apache Webserver as Proxy in front you can use the Apache Config in this comment and reenable Websockets for XMPP again: https://github.com/jitsi/docker-jitsi-meet/issues/854#issuecomment-740681178

Don’t forget to enable the Apache module proxy_wstunnel (e.g. for Ubuntu: $ sudo a2enmod proxy_wstunnel

**Comment by alternadom** [comment]
Hi,
We are facing some issue to open a meeting with the 5142-3.
No error anywhere (console front or docker back), we just are alone on the meeting!
Disabled auth, lobby and many other things but still not working..
Nginx Reverse Proxy behind.. so maybe the same problem.
Can you give a tip on how to make sure that is this problem ?
Thanks,

**Comment by mcrapts** [comment]
> @mcrapts if you have an Apache Webserver as Proxy in front you can use the Apache Config in this comment and reenable Websockets for XMPP again: [#854 (comment)](https://github.com/jitsi/docker-jitsi-meet/issues/854#issuecomment-740681178)
> 
> Don’t forget to enable the Apache module proxy_wstunnel (e.g. for Ubuntu: $ sudo a2enmod proxy_wstunnel

I am using Caddy and not Apache.

**Comment by alternadom** [comment]
We put `ENABLE_XMPP_WEBSOCKET=0` and `PUBLIC=https://ourdomain.com` but still don't work..

**Comment by saghul** [comment]
What output do you see in the browser console?

**Comment by alternadom** [comment]
Seems that my config.js is not good now.. I put the config.js generated and "it's alive!" :)

**Comment by gensi0** [comment]
Hi, 

I managed to get the xmpp websocket working with Nginx but I had to set `XMPP_CROSS_DOMAIN=true`.

Also, I edited my nginx conf and add : 
![image](https://user-images.githubusercontent.com/71636603/102226070-38ba4b80-3ee8-11eb-9e3a-6272b6fc3115.png)


But it seems like XMPP_CROSS_DOMAIN is depreciated :/

**Comment by saghul** [comment]
> But it seems like XMPP_CROSS_DOMAIN is depreciated :/

Not really, we just added it recently!

**Comment by gensi0** [comment]
Oh ! So, that might be a solution ?

**Comment by manang** [comment]
Hi, are the containers updated?
Thank you very much

Angelo

**Comment by jomo** [comment]
> You can also set XMPP_WEBSOCKET to 0 to continue using regular HTTP.

Note: The environment variable is called `ENABLE_XMPP_WEBSOCKET`, not `XMPP_WEBSOCKET`.

**Comment by ManasJayanth** [comment]
If you're here before of an error in the browser logs about xmpp websocket and if you have an nginx proxy, saghul is right about allow websocket connections. After making sure `PUBLIC_URL` is set correctly, and with the following config (standard nginx websocket config), 5142 stable releases are working for me again

```
    location /xmpp-websocket {
        proxy_pass http://<ip>:8000; # or 8443 if it's secure connection
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    } 
```

**Comment by mcrapts** [comment]
In case someone is using Caddy like me, you can fix it by using the following configuration:

```
your.domain.name {
  reverse_proxy web:80
  reverse_proxy /xmpp-websocket prosody:5280
}
```
`web` and `prosody` refer to the service names in the docker-compose.yml.

**Comment by aushtin** [comment]
> Well, the PUBLIC_URL also solved the problem for me. I don't have to do any modifications in my nginx reverse proxy configuration. I have to set two things.
> First in the .env File add or uncomment the PUBLIC_URL variable.
> Second in the docker-compose.yml file add the env Variable to the prosody container:
> 
> ```
>     prosody:
>         image: jitsi/prosody:latest
>         .....
>        environment:
>             - AUTH_TYPE
>              ....
>             - PUBLIC_URL
> ```
> 
> After restarting the Containers everything is working with the latest Version from the repo.
> 
> Thanks to all for helping.
> 
> Regards
> Manuel

Can someone explain why this works? I was having a similar issue although my setup was different (using traefik as my proxy). 

Before implementing the solution described above, I could not connect to a meeting at all and got stuck in a "disconnected, will retry in XX seconds" loop. Inspecting the console showed a 403 error for the websocket handshake on every retry. 

Added the - PUBLIC_URL variable to the prosody container and now everything seems to work. Any insight as to why this solved the issue?

**Comment by laf0rge** [comment]
I am still experiencing this problem with stable-5142-4 behind a nginx reverse proxy. I evene deleted all the configs from ~/.jitsi-meet-cfg and started from scratch.  The only work-around that makes jitsi meet functional again is to use ENABLE_XMPP_WEBSOCKET=0

**Comment by fmoledina** [comment]
> ```
> your.domain.name {
>   reverse_proxy web:80
>   reverse_proxy /xmpp-websocket prosody:5280
> }
> ```

Thanks for this. This is exactly what I needed to get my Traefik v2 configuration working. I understood from the above that I needed to map `/xmpp-websocket` but it wasn't completely clear until it clicked with your post.

**Comment by developdeez** [comment]
Whats the trade-off of disabling xmpp?

**Comment by saghul** [comment]
I assume you mean `ENABLE_XMPP_WEBSOCKET=0`. That doesn't disable XMPP, it disables using WebSocket for XMPP, which makes the connection generally more reliable.

**Comment by dawidmalina** [comment]
@saghul what kind of traffic is going into xmpp? Video streaming is still exposed directly from jvb instance on port 10000/udp, right?

Currently I am exposing jitsi with AWS ALB and wondering the pros and cons disabling websocket and using only one target port or making ALB configuration a bit more complicated.

Additionally I am wondering as here usually everyone talks about `/xmpp-websocket` path that needs to be handled by prosody but based on the nginx configuration we should also use `/http-bind` path which also should be handled by prosody.

In addition there is also  `^/colibri-ws/` path which based on the regexp creates websocket to jvb instance and here I am confused what logic should be created on ALB side in order to make websocket works properly.

**Comment by renepardon** [comment]
I am using the docker installation without proxy and have the same problem with 403 error. When I set ENABLE_XMPP_WEBSOCKET to 0, i receive another weird error: Error during WebSocket handshake: Unexpected response code: 200

My configuration consists of a token authentication with JWT. Everything else is default because I use my own UI with lib-jitsi-meet. 

Hopefully someone has a hint for me here.

**Comment by saghul** [comment]
> what kind of traffic is going into xmpp? Video streaming is still exposed directly from jvb instance on port 10000/udp, right?

Signalling. All the session management stuff. Media still goes to UDP port 10000 on the JVB indeed.

> wondering the pros and cons disabling websocket

We enabled it because it makes the connection more reliable. This was battle tested on meet.jit.si.



> Additionally I am wondering as here usually everyone talks about `/xmpp-websocket` path that needs to be handled by prosody but based on the nginx configuration we should also use `/http-bind` path which also should be handled by prosody.

Correct. The former is the websocket path, with the latter being BOSH. BOSH is still used on mobile.



> In addition there is also `^/colibri-ws/` path which based on the regexp creates websocket to jvb instance and here I am confused what logic should be created on ALB side in order to make websocket works properly.

Sorry I have no idea about that one. I think it's safe to make it /colibri-ws/... though.

**Comment by snowzach** [comment]
I had the same problem with Kubernetes and a Traefik ingress and JVB on a separate IP:PORT
Under the web container I needed to ensure I had `PUBLIC_URL` and `DOCKER_HOST_ADDRESS` set to my outside URL IP and host. Under JVB I had to ensure I had `PUBLIC_URL` and `DOCKER_HOST_ADDRESS` set to my outside URL and host for JVB. (This was a different IP in my case)
