### ISSUE TITLE
using JitsiMeetJS api fails with Strophe error

### ISSUE THREAD

**Issue by roeycohen** [jitsi/docker-jitsi-meet#87]
I'm using JitsiMeetJS api for a custom UI and get an error:
_lib-jitsi-meet.min.js?1549199310:6 [modules/xmpp/strophe.util.js] <Object.i.Strophe.log>:  Strophe: Server did not offer a supported authentication mechanism_
![image](https://user-images.githubusercontent.com/2613845/55559376-bfb89780-56f6-11e9-8202-8151236f550c.png)

i didn't turn on ENABLE_AUTH or something like this.

i don't know that's related, but i've also added in meet.conf the following lines to be able to run my UI from another domain (which is quite a must when writing a custom UI)
add_header 'Access-Control-Allow-Origin' '*';
add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
add_header 'Access-Control-Allow-Headers' 'DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';

**Comment by damencho** [comment]
You need to add `consider_bosh_secure = true` to the prosody config.

**Comment by roeycohen** [comment]
tried adding it to prosody.cfg.lua - alas same problem :(
also tried adding cross_domain_bosh = true without success.

**Comment by roeycohen** [comment]
the weird thing is that accessing jitsi directly works... 
i've copied lib.jitsi.meet from the container to my website but still no success.

**Comment by roeycohen** [comment]
update: tried redirecting my code to https://meet.jit.si and it works... must be something i'm missing with the docker version... is it possible to select component version when using docker?
any ideas?

**Comment by roeycohen** [comment]
ok! got the problem!
when connecting from a remote address, the "VirtualHost "meet.jitsi"" in jitsi-meet.cfg.lua doesn't "catch the request, therefore does not return "authentication mechanism".
duplicating the virtual host with the remote address works!

now i have a new problem...
![image](https://user-images.githubusercontent.com/2613845/55577097-6c0c7500-571b-11e9-9767-e71ccd432dbe.png)

any ideas?

**Comment by roeycohen** [comment]
Hi it seems like strophe is sending the wrong "to" when connection from another domain:
![image](https://user-images.githubusercontent.com/2613845/55684482-8f216980-5953-11e9-9f3d-b2f6b8e300a9.png)
how can i change this to "meet.jitsi"?

**Comment by roeycohen** [comment]
for anyone in the same situation, trying to move from the regular install to docker this is what i had to change:
1. in prosody container, add the following 2 lines at the beginning of the jitsi-meet.cfg.lua file:
```
consider_bosh_secure = true
cross_domain_bosh = true
```
2. in the client side, change "JitsiMeetJS.JitsiConnection" configuration to:
```
hosts: {
  domain: 'meet.jitsi',
  : `muc.meet.jitsi`,
}
...
```

**Comment by Fuji1405116** [comment]
Hi, we used lib-jitsi-meet api with extra layer of rules and call to a docker jitsi server from a angular app. I was facing that problem I solved it primarily by the method above.
But now it is working fine in my pc, different tabs in chrome.. but problem starts when another pc in same network joins.. 
error:  "Bridge channel send : no opened channel "
I suspect jvb container ports are not accessible from outside even in same network.. what should I do now? @roeycohen

**Comment by roeycohen** [comment]
hi @Fuji1405116, not really sure how to help you... but it might be something else in your local network configuration..
maybe @damencho can help :)

**Comment by roeycohen** [comment]
@Fuji1405116 I believe our problem in common is that we built custom UI which is hosted on another domain name.
that's why my solution above worked.
I'm not an expert, but maybe when you're trying to access an intranet machine this doesn't work because prosody doesn't catch requests from this internal subnet.
try playing with jitsi-meet.cfg.lua hosts...
