### ISSUE TITLE
Chrome dependency

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [jitsi/docker-jitsi-meet#881]
Hello!

I am considering setting up a Jitsi-Meet server and thinking about whether I should use Docker or not. Inside a virtual machine I set up Jitsi-Meet without any bigger problems without Docker in Debian Buster. I then looked at this project here and saw, that the docker setup is quite elaborate and complex, compared to simply installing NGINX and jitsi-meet on Debian. So I looked into what those various services are, that are referenced in the docker-compose file and found out, that there is even a dependency of Chrome!?

I was looking into Jitsi-Meet initially, because I thought it was all free software, which is very important to me, for the potential purpose of the server. I thought about setting it up and offering it for a school, so that they can use free software instead of spyware like Zoom or Teams for their online classes. So you can imagine perhaps my worries, now that I saw a Chrome dependency in <https://github.com/jitsi/docker-jitsi-meet/blob/master/jibri/Dockerfile#L17-L21>.

So I have a few requests:

* Can you explain, why Chrome is installed in that container and what it is used for and what data flows through it or gets in touch with it?
* Does the installation without Docker on plain Debian also rely on Chrome? I think Chrome is not even in the Debian repositories, as it is non-free software.
* If the installation without docker does not depend on Chrome, why does the one with docker depend on Chrome?

**Comment by damencho** [comment]
As you can see that file is inside jibri part of the docker repo. This is how jibri https://github.com/jitsi/jibri works, uses chrome to stream and record a meeting. And is not a requirement for jitsi-meet to work.
Please, when you have problems or questions use the community forum before opening new issues.

**Comment by ZelphirKaltstahl** [comment]
Thank you for the quick reply!

Which community forum should I ask my question in? Can you link the forum? I have not seen or found it yet. It is not mentioned in the readme of this repository, nor is it mentioned in the readme of <https://github.com/jitsi/jitsi-meet> and I did not come across it during searching for setup guides. It might be a good idea to mention that in the readme, if asking about issues directly on Github is not desired.

In general I find it much easier to ask technical questions directly on the concerning repository, instead of going to an external forum, to then ask there about the repository here. Do I need to create yet another account somewhere to ask a question? Creating accounts can be an additional hurdle for people. One might want to ask one question and be done with it, but then would have to create an extra account, just to ask one question. It would be an inconvenience at least.

**Comment by damencho** [comment]
https://community.jitsi.org/

**Comment by ZelphirKaltstahl** [comment]
Ah that's a shame … When I visit that website, it is a completely white page, nothing to see. First I am perplexed. "Is the link wrong? Did the page not load?" Then I realized, that I must be blocking something. Usually I would close the browser tab right there. Then I saw, that it is a discourse forum ._. I allowed discourse for once, which I usually never do, as I dislike the user experience of it so much. But still a blank page, still nothing to be seen.

Apparently everything depends on loading external scripts from kxcdn, the new fashion of CDN. I do not trust kxcdn. It is really a pity, that the community of a supposedly free software tool relies on a website which simply does not work at all, loading third party scripts from this month's fad of CDN.

This "blank page, show nothing" thing spreads more and more on the web and is so anti web in its character. I miss the times, when you could visit a forum and browse it and post things to it without even using JS. This kind of forum is not even properly searchable by search engines. No wonder I did not come across it during my previous search queries about jitsi-meet. Now it all makes sense, unfortunately.

Is there perhaps a mailing list? One not using Google groups … I guess not, because then I should have seen some links to that in search results as well.

See, that is a significant downside of a forum of such kind: No one finds it via search queries. No solution posted there will ever surface when anyone looks for a problem in a search engine. It is encapsulating jitsi-meet knowledge away from people searching for it. Ugh. It is also excluding people, who do not want to associate their accounts with everything. It is truly not in the spirit of free software.
