### ISSUE TITLE
JVB tcp disabled even JVB_TCP_HARVESTER_DISABLED is set to false

### ISSUE THREAD

**Issue by Akkiesoft** [jitsi/docker-jitsi-meet#885]
```{{ not .Env.JVB_TCP_HARVESTER_DISABLED }}```  in jvb.conf should be return the flipped value of .Env.JVB_TCP_HARVESTER_DISABLED. But result is false even value is false.

```
# {{ not .Env.JVB_TCP_HARVESTER_DISABLED }}
# {{     .Env.JVB_TCP_HARVESTER_DISABLED }}

result:
# false
# false
```

```{{ not .Env.JVB_TCP_HARVESTER_DISABLED }}``` seems to work only if the value is true.

```
# {{ not .Env.JVB_TCP_HARVESTER_DISABLED }}
# {{     .Env.JVB_TCP_HARVESTER_DISABLED }}

result:
# false
# true
```

**Comment by saghul** [comment]
We may need to do `{{ not (.Env.JVB_TCP_HARVESTER_DISABLED | default "true" | toBool) }}` Any chance you can test that?

**Comment by Akkiesoft** [comment]
@saghul I tested your code and works fine both true and false. Thank you!
