### ISSUE TITLE
changing interface_config.js does not do anything

### ISSUE THREAD

**Issue by Palshee** [jitsi/docker-jitsi-meet#886]
I've changed my `interface_config.js` to enable/disable some features like watermark, guests, the link when the logo is clicked, colors etc but these settings do not go into effect. I've even try `docker-compose up -d --force-recreate` but none of the settings seem to be doing anything.

I saw a few other people having the same issue and the fix is to delete the config file, however, if I delete the config file, won't it just generate another default file?

**Comment by saghul** [comment]
The file is regenerated on every container boot. You can specify custom overrides on your own file: https://github.com/jitsi/docker-jitsi-meet/blob/master/web/rootfs/etc/cont-init.d/10-config#L87-L89

**Comment by talski** [comment]
> The file is regenerated on every container boot. You can specify custom overrides on your own file: https://github.com/jitsi/docker-jitsi-meet/blob/master/web/rootfs/etc/cont-init.d/10-config#L87-L89

This file `/config/custom-interface_config.js`, where should I put it? I have `~/docker-jitsi-meet-stable-5870` where I downloaded docker installer and have a .env file inside and run docker-compose commands, and `~/.jitsi-meet-cfg`, tried both and didn't work.
```
~/docker-jitsi-meet-stable-5870/web/rootfs/config/custom-interface_config.js
~/.jitsi-meet-cfg/web/rootfs/config/custom-interface_config.js
```
