### ISSUE TITLE
Etherpad API 2 domains

### ISSUE THREAD

**Issue by ortomind** [jitsi/docker-jitsi-meet#888]
Etherpad used to work ok in docker and API with a different domain than Jitsi. Now I get this error:
Error
Cookie could not be found. Please allow cookies in your browser! Your session and settings will not be saved between visits. This may be due to Etherpad being included in an iFrame in some Browsers. Please ensure Etherpad is on the same subdomain/domain as the parent iFrame

**Comment by saghul** [comment]
You'd need to ask the Etherpad authors.

**Comment by ortomind** [comment]
image: etherpad/etherpad:1.8.5 instead image: etherpad/etherpad:1.8.6 solved for the moment the problem. Thanks
