### ISSUE TITLE
Jibri not working 

### ISSUE THREAD

**Issue by matheusfillipe** [jitsi/docker-jitsi-meet#889]
I tried livestreaming to my custom rtmp server, it didn't work, connection failed from the web gui (That should work right?). Then I tried to stream with a youtube stream key and also had the same problem.  I am trying stable-5142-4 since in older versions before 5142 I can't even conference. (When another user joins the conference breaks). 

``` 
2020-12-23T23:32:13.626Z [modules/RTC/BridgeChannel.js] <_handleChannel/e.onclose>:  Channel closed: 1006 Logger.js:154:22
2020-12-23T23:32:26.385Z [JitsiMeetJS.js] <getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  
<iq id="4338bc7d-9651-4ea7-b2a3-b4ff780d17b3:sendIQ" to="b32964ad-8bee-4c39-98c2-…est.meet.jitsi/9gUn9_gf" type="error" from="room1@muc.meet.jitsi/focus" xmlns="jabber:client">
Logger.js:154:22
    o Logger.js:154
    getGlobalOnErrorHandler JitsiMeetJS.js:613
    onunhandledrejection middleware.js:118
Uncaught (in promise) 
<iq id="4338bc7d-9651-4ea7-b2a3-b4ff780d17b3:sendIQ" to="b32964ad-8bee-4c39-98c2-…est.meet.jitsi/9gUn9_gf" type="error" from="room1@muc.meet.jitsi/focus" xmlns="jabber:client">
```

Here is my .env: 
[env.txt](https://github.com/jitsi/docker-jitsi-meet/files/5737478/env.txt)

I didn't change other settings. Is there something wrong or did I miss something? Also i am always removing all the configs like:
 `rm -r ~/.jitsi-meet-cfg/{web/letsencrypt,transcripts,prosody/config,prosody/prosody-plugins-custom,jicofo,jvb,jigasi,jibri}` 
and also removing the containers and building them again with:
`sudo docker-compose -f docker-compose.yml -f jibri.yml up -d `

**Comment by guymass** [comment]
I have a similar problem and would very much like to see a fix for this soon as I cannot stream to YT at all. In my case I am using another script named aVideo which have developed a plugin for jitsi meet and while the plugin works well in managing the rooms and users, I cannot get any recordings or live streams on my site when connecting to my own jitsi+jibri servers, but when I use aVideo servers the do work, so I am not sure what the issue is as they don't disclose their server configs.

**Comment by saghul** [comment]
> I tried livestreaming to my custom rtmp server, it didn't work, connection failed from the web gui (That should work right?). Then I tried to stream with a youtube stream key and also had the same problem.  I am trying stable-5142-4 since in older versions before 5142 I can't even conference. (When another user joins the conference breaks). 
> 
> 
> 
> ``` 
> 
> 2020-12-23T23:32:13.626Z [modules/RTC/BridgeChannel.js] <_handleChannel/e.onclose>:  Channel closed: 1006 Logger.js:154:22
> 
> 2020-12-23T23:32:26.385Z [JitsiMeetJS.js] <getGlobalOnErrorHandler>:  UnhandledError: null Script: null Line: null Column: null StackTrace:  
> 
> <iq id="4338bc7d-9651-4ea7-b2a3-b4ff780d17b3:sendIQ" to="b32964ad-8bee-4c39-98c2-…est.meet.jitsi/9gUn9_gf" type="error" from="room1@muc.meet.jitsi/focus" xmlns="jabber:client">
> 
> Logger.js:154:22
> 
>     o Logger.js:154
> 
>     getGlobalOnErrorHandler JitsiMeetJS.js:613
> 
>     onunhandledrejection middleware.js:118
> 
> Uncaught (in promise) 
> 
> <iq id="4338bc7d-9651-4ea7-b2a3-b4ff780d17b3:sendIQ" to="b32964ad-8bee-4c39-98c2-…est.meet.jitsi/9gUn9_gf" type="error" from="room1@muc.meet.jitsi/focus" xmlns="jabber:client">
> 
> ```
> 
> 
> 
> Here is my .env: 
> 
> [env.txt](https://github.com/jitsi/docker-jitsi-meet/files/5737478/env.txt)
> 
> 
> 
> I didn't change other settings. Is there something wrong or did I miss something? Also i am always removing all the configs like:
> 
>  `rm -r ~/.jitsi-meet-cfg/{web/letsencrypt,transcripts,prosody/config,prosody/prosody-plugins-custom,jicofo,jvb,jigasi,jibri}` 
> 
> and also removing the containers and building them again with:
> 
> `sudo docker-compose -f docker-compose.yml -f jibri.yml up -d `
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

Streaming to generic RTMP endpoints hasn't hit stable yet.

**Comment by matheusfillipe** [comment]
@saghul  okay but shouldn't streaming to youtube work at least?

**Comment by matheusfillipe** [comment]
It works now on latest commits: https://github.com/jitsi/docker-jitsi-meet/issues/966
