### ISSUE TITLE
WebSockets configuration question

### ISSUE THREAD

**Issue by dawidmalina** [jitsi/docker-jitsi-meet#891]
Quick question (hope it will not too stupid). If I configure properly XMPP WebSockets does it mean that jvb will be exposed directly over that websocket and I don't need to expose jvb on public ip over udp protocol? Or i am just mixing topics?

**Comment by paweldomas** [comment]
XMPP websocket are for the signaling connection and it's a separate thing from the jvb, so you will still need to expose udp port on public ip.

**Comment by dawidmalina** [comment]
Thanks @paweldomas for explanation. So UDP port will always need to be exposed, right?

**Comment by paweldomas** [comment]
yes

**Comment by schadom** [comment]
Why?  The usage of UDP/TCP high-ports makes Jitsi basically unusable in any environment with corporate firewalls...

**Comment by paweldomas** [comment]
> Why? The usage of UDP/TCP high-ports makes Jitsi basically unusable in any environment with corporate firewalls...

For corporate firewall you can try TCP TURN server on port 443

**Comment by collinks2** [comment]
Gooday everyone. I am a newbie in jitsi. Infact I just installed jitsi on Ubuntu. I want to use jitsi to route Webrtc calls to my cucm IVR. I don't really need the video conference feature. I need to configure WebSocket protocol in jitis. how will i  configure it?
