### ISSUE TITLE
documentation: "first steps"

### ISSUE THREAD

**Issue by fxa** [jitsi/docker-jitsi-meet#894]
The first steps are much too long. When I saw them first, I was really scared.
The first steps should only be:
* git clone blablabla
* cd blablabla
* docker-compose up --detach
all the other things should be declared below.
First I thought, I all have to configure in the .env file. But afterwords I saw, I can pass by the docker-compose.yml, wich is much easier, but not documented
ps I know, especially in open source projects documentation has "not the first priority" (I know from my own open source projects). But especial "first steps" should have as less as possible steps to get a running system. Ok, everybody should be aware, that there has to be some aftermath (e.g. for my "architecture" to fix nginx settings to remove insecure tls versions et al)

**Comment by helloncanella** [comment]
check out https://github.com/helloncanella/jitsi-with-external-nginx-config
