### ISSUE TITLE
web/config.js overwritten on container restart

### ISSUE THREAD

**Issue by nerdreich** [jitsi/docker-jitsi-meet#895]
I just made a fresh install using the instructions at `https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker`, HEAD on git clone was b0e653ae. Jitsi runs fine on my setup, I and others can connect.

When I edit `~/.jitsi-meet-cfg/web/config.js`, changes seem to immediately take effect (e.g. enabling prejoinPageEnabled:). However, when I manually restart all containers (docker restart ..., or reboot the host), `~/.jitsi-meet-cfg/web/config.js` seems to revert to its default content, loosing all custom changes. How can I prevent this?

This does not happen to e.g. `~/.jitsi-meet-cfg/jvb/logging.properties`, where I changed the log level. That file is not reverted on container restart/reboot.

**Comment by ortomind** [comment]
I have the same question

**Comment by prayagsingh** [comment]
It's an expected behavior.

**Comment by nerdreich** [comment]
It is an expected behavior that the web-container looses its configuration on restart and requires manual changes every time it restarts? That does not feel right to me. (I'm not deleting and recreating the container, I'm just restarting it.).

**Comment by saghul** [comment]
Yes this is expected and intentional. We started the opposite way and too many people encountered problems as this is not the "container native" way to do things. We now have env vars for all the settings and a custom JS file can be specified which will be appended at the end.

**Comment by anirbandas18** [comment]
@saghul How do I specify this custom JS file to be appended at the end? What is the environment variable name for Docker setup?

**Comment by saghul** [comment]
See here: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker/#jitsi-meet-configuration

**Comment by anirbandas18** [comment]
> https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker/#jitsi-meet-configuration

Thank you! On another note, is there something similar for jvb.conf as well?

**Comment by saghul** [comment]
No, we don't have such a mechanism for jvb.conf
