### ISSUE TITLE
Docker Engine's error 

### ISSUE THREAD

**Issue by s4miii** [jitsi/docker-jitsi-meet#896]
Thnx for your great job
I want to install `docker-jitsi-meet` on `CentOS release 6.10 (Final)` 

so I installed `docker-compose` like this :
`sudo curl -L https://github.com/docker/compose/releases/download/1.19.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose`

then after these steps

1. `git clone https://github.com/jitsi/docker-jitsi-meet && cd docker-jitsi-meet`
2. `cp env.example .env`
3. `./gen-passwords.sh`
4. `mkdir -p ~/.jitsi-meet-cfg/{web/letsencrypt,transcripts,prosody/config,prosody/prosody-plugins-custom,jicofo,jvb,jigasi,jibri}`
5. `docker-compose up -d`
I've got this error
`ERROR: The Docker Engine version is less than the minimum required by Compose. Your current project requires a Docker Engine of version 1.13.0 or greater.`

the version of docker-compose is : 
`docker-compose version 1.19.0, build 9e633ef`

any suggestion ?

**Comment by prayagsingh** [comment]
It's not a Jitsi error. Your `docker engine` version is less than `1.13`. Check the output of `docker version` command.
Below is the result of the command that I ran on my machine.
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.0
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       eeddea2
  Built:            Tue Dec  8 18:58:04 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by s4miii** [comment]
thnx for your reply the output is like this :

`$ docker version`
```
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

how to install engine ? thnx

**Comment by s4miii** [comment]
> It's not a Jitsi error. Your `docker engine` version is less than `1.13`. Check the output of `docker version` command.
> Below is the result of the command that I ran on my machine.
> 
> ```
> Client: Docker Engine - Community
>  Version:           19.03.12
>  API version:       1.40
>  Go version:        go1.13.10
>  Git commit:        48a66213fe
>  Built:             Mon Jun 22 15:45:36 2020
>  OS/Arch:           linux/amd64
>  Experimental:      true
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          20.10.0
>   API version:      1.41 (minimum version 1.12)
>   Go version:       go1.13.15
>   Git commit:       eeddea2
>   Built:            Tue Dec  8 18:58:04 2020
>   OS/Arch:          linux/amd64
>   Experimental:     true
>  containerd:
>   Version:          v1.4.3
>   GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
>  runc:
>   Version:          1.0.0-rc92
>   GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0
> ```

thnx for your reply the output is like this :

`$ docker version`
```
Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64
```

how to install engine ? thnx

**Comment by prayagsingh** [comment]
install latest docker-ce. 
```
sudo apt update && sudo apt install -y apt-transport-https ca-certificates curl software-properties-common && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable" && sudo apt update && apt-cache policy docker-ce && sudo apt install -y docker-ce && sudo usermod -aG docker ${USER} && su - ${USER} && id -nG && systemctl status docker
```
