### ISSUE TITLE
Option to delete room history

### ISSUE THREAD

**Issue by kombasltd** [jitsi/docker-jitsi-meet#898]
Please add an option in the .env file to not show or to delete the room history for privacy reasons.

Thanks!

**Comment by saghul** [comment]
This (deleting history entries) is already implemented in the frontend and will be part of the next stable (-1) release.

**Comment by maglub** [comment]
I was also looking for this, almost a year later.

I don't think this made it to any release of the docker container, as there does not seem to be any templating done to set the `config.doNotStoreRoom` to anything but true (the default value). I also don't think there is an easy fix to the templating from the `.env` variable until the `interface_config.js` is fully migrated to `config.js`. To achieve what we want, we need config settings in both `config.js` and `interface_config.js`.

```
root@2141ae19efb1:/defaults# grep -ri doNotStoreRoom .
./config.js:    // doNotStoreRoom: true,
root@2141ae19efb1:/defaults# ls -la
total 112
drwxr-xr-x 1 root root  4096 Dec 11 07:11 .
drwxr-xr-x 1 root root  4096 Dec 13 19:07 ..
-rw-r--r-- 1 root root 51023 Dec  9 07:50 config.js
-rw-r--r-- 1 root root   550 Dec  7 12:55 default
-rw-r--r-- 1 root root   423 Dec  7 12:55 ffdhe2048.txt
-rw-r--r-- 1 root root  8591 Nov 26 16:55 interface_config.js
-rw-r--r-- 1 root root  2611 Dec  7 12:55 meet.conf
-rw-r--r-- 1 root root  1353 Dec  7 12:55 nginx.conf
-rw-r--r-- 1 root root 13536 Dec  7 12:55 settings-config.js
-rw-r--r-- 1 root root  1262 Dec  7 12:55 ssl.conf
-rw-r--r-- 1 root root  2017 Aug 10 12:02 system-config.js
```

I have been looking in the latest builds, and have been looking in:

* https://github.com/jitsi/docker-jitsi-meet/blob/0600eceadc713e02027aea5df4a4e095e1d1cb26/web/rootfs/etc/cont-init.d/10-config#L78

As well as the `/default/config.js` (which comes from the Docker file's `mv /tmp/pkg/usr/share/jitsi-meet-web-config/config.js /defaults` here: https://github.com/jitsi/docker-jitsi-meet/blob/0600eceadc713e02027aea5df4a4e095e1d1cb26/web/Dockerfile#L12)

I can't see any trace of an environment variable that would control this. Also, the documentation does not mention this either (although there are some other `.env` variables that are not yet documented either). I think that the move from `interface_config.js` into `config.js` is not really complete, and we don't template the `interface_config.js` either, so to get rid of the history, you need to do a manual workaround (see below):

`10-config` (https://github.com/jitsi/docker-jitsi-meet/blob/0600eceadc713e02027aea5df4a4e095e1d1cb26/web/rootfs/etc/cont-init.d/10-config#L78):

```
...
cp /defaults/config.js /config/config.js
tpl /defaults/system-config.js >> /config/config.js
tpl /defaults/settings-config.js >> /config/config.js
if [[ -f /config/custom-config.js ]]; then
    cat /config/custom-config.js >> /config/config.js
fi

cp /defaults/interface_config.js /config/interface_config.js
if [[ -f /config/custom-interface_config.js ]]; then
    cat /config/custom-interface_config.js >> /config/interface_config.js
fi
...
```

# Workaround

One way to workaround this to create two local (on your docker host) custom config files:

* ~/.jitsi-meet-cfg/web/custom-config.js
* ~/.jitsi-meet-cfg/web/custom-interface_config.js

This is also related to the attribute `interfaceConfig.RECENT_LIST_ENABLED`, that we can set in `~/.jitsi-meet-cfg/web/custom-interface_config.js` (see https://community.jitsi.org/t/do-not-want-to-see-room-history-on-welcome-page/50059/3, which was introduced with this pull request: https://github.com/jitsi/jitsi-meet/pull/5452). Without setting this, the web gui will anyways show you the history. 

`~/.jitsi-meet-cfg/web/custom-config.js`:

```
ops@lin-build-l01:$ cat ~/.jitsi-meet-cfg/web/custom-config.js
// This disables the gathering of room history, but does not disable the display of it in the web gui
config.doNotStoreRoom = true;
```

`~/.jitsi-meet-cfg/web/custom-interface_config.js`:

```
ops@lin-build-l01:$ cat ~/.jitsi-meet-cfg/web/custom-interface_config.js 
// Step 2 in disabling the recent list, removing the display of the recent list in the web gui
interfaceConfig.RECENT_LIST_ENABLED = false;
```

Then restart your containers:

```
docker-compose down
docker-compose up
```

Have a nice day!
//magnus
