### ISSUE TITLE
JWT Suport

### ISSUE THREAD

**Issue by amirasaran** [jitsi/docker-jitsi-meet#9]
Hi 
I want to active private room in jitsi meet

I found this link but i cannot use that
[https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md](https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md)

**Comment by saghul** [comment]
Yep, the Prosody container does not have the necessary plugins at this time. I can't give you an ETA for when this will be added to the Docker files, sorry.

**Comment by saghul** [comment]
> can you help me to modify this Dockerfile ?
> Which file needed to change ?

Doing that implies the same amount of effort as doing it myself, which I currently have no time for, sorry.

> I'm try to change Prosody config is it enough?

No, you also need the plugins.



> if I change https://github.com/jitsi/docker-jitsi-meet/blob/master/prosody/Dockerfile#L6 to apt-dpkg-wrap apt-get install -t stretch-backports -y prosody prosody-trunk&& \ is correct way ?

I don't think that is necessary anymore.

**Comment by amirasaran** [comment]
I fix this issue by the flowing changes:

change prosody Dockerfile to :


```
FROM jitsi/base

RUN \
	echo "deb http://ftp.debian.org/debian stretch-backports main" > /etc/apt/sources.list.d/backports.list && \
	apt-dpkg-wrap apt-get update && \
	apt-dpkg-wrap apt-get install -t stretch-backports -y prosody luarocks gcc libssl1.1 libssl1.0-dev git && \
	apt-cleanup && \
	rm -rf /etc/prosody

COPY rootfs/ /

RUN    luarocks list --outdated && \
       luarocks install luaossl  CRYPTO_LIBDIR=/usr/lib/x86_64-linux-gnu  CRYPTO_INCDIR=/usr/include OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu OPENSSL_INCDIR=/usr/include && \
       luarocks install luajwt CRYPTO_LIBDIR=/usr/lib/x86_64-linux-gnu  CRYPTO_INCDIR=/usr/include OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu OPENSSL_INCDIR=/usr/include && \
       luarocks install luajwtjitsi CRYPTO_LIBDIR=/usr/lib/x86_64-linux-gnu  CRYPTO_INCDIR=/usr/include OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu OPENSSL_INCDIR=/usr/include && \
       luarocks install jwt-jitsi CRYPTO_LIBDIR=/usr/lib/x86_64-linux-gnu  CRYPTO_INCDIR=/usr/include OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu OPENSSL_INCDIR=/usr/include

EXPOSE 5222 5269 5347 5280 5281

VOLUME /config

```


And Change prosody config file `jitsi-meet.cfg.lua` to :

```
admins = { "{{ .Env.JICOFO_AUTH_USER }}@{{ .Env.XMPP_AUTH_DOMAIN }}" }
plugin_paths = { "/prosody-plugins/" }
VirtualHost "{{ .Env.XMPP_DOMAIN }}"
        ssl = {
                key = "/config/certs/{{ .Env.XMPP_DOMAIN }}.key";
                certificate = "/config/certs/{{ .Env.XMPP_DOMAIN }}.crt";
        }
        modules_enabled = {
            "bosh";
            "pubsub";
            "ping";
        }
        authentication = "token";
        app_id = "my-app-id";
        app_secret = "my-app-secret";
        allow_empty_token = false;
--        consider_bosh_secure = true;
        c2s_require_encryption = false;

VirtualHost "{{ .Env.XMPP_AUTH_DOMAIN }}"
    ssl = {
        key = "/config/certs/{{ .Env.XMPP_AUTH_DOMAIN }}.key";
        certificate = "/config/certs/{{ .Env.XMPP_AUTH_DOMAIN }}.crt";
    }
    authentication = "internal_plain"

Component "{{ .Env.XMPP_MUC_DOMAIN }}" "muc"
    storage = "none"
    modules_enabled = { "token_verification" }

Component "jitsi-videobridge.{{ .Env.XMPP_DOMAIN }}"
    component_secret = "{{ .Env.JVB_COMPONENT_SECRET }}"

Component "focus.{{ .Env.XMPP_DOMAIN }}"
    component_secret = "{{ .Env.JICOFO_COMPONENT_SECRET }}"

```

copy this folder `https://github.com/jitsi/jitsi-meet/tree/master/resources/prosody-plugins` to `prosody/rootfs/prosody-plugins`


Thanks to @saghul

**Comment by sapkra** [comment]
Hey guys,

I added a PR - maybe someone can have a look. https://github.com/jitsi/docker-jitsi-meet/pull/29

**Comment by YUEJINYUAN** [comment]
I have a high level of attention to JWT support. I saw the merge of the relevant branches, but now the changes don't seem to be in the main branch, so I want to know if I will join the JWT to the master, or tell me the approximate merge time, I am looking forward to the update.
@saghul @sapkra  Sincere blessing

**Comment by saghul** [comment]
@YUEJINYUAN you can test it right away on the dev branch. I hope to have some time this week to get it reasdy for release, but I'm not sure.

**Comment by saghul** [comment]
Also, since @sapkra 's amazing work in #29 already landed, I'm going to go ahead and close this.
