### ISSUE TITLE
Deeplinking for mobile applications

### ISSUE THREAD

**Issue by tusharsonawanes** [jitsi/docker-jitsi-meet#901]
Hello, I have an issue configuring deeplinking for android and iOS phones. I'll explain my entire scenario here.

Backend - docker-jitsi-meet-5142

Reference jitsi repository for android and iOS apps - https://github.com/gunschu/jitsi_meet

Issues.

**Android** ( 1 Issue )

**1.** When the user does **not** have the custom application ( made by using the above repository )  installed in the phone, on click of the link, it ( as expected ) opens the web where three options are prompted, '

- Join this meeting using the app
- Download the app
- Launch in web

The first two options, redirect to custom android application which is present android play store and the third options opens the web browser. This works perfectly well. The **issue** is, when the user installs the application, and then clicks the link, I can see the application listed in the **open with** section, but if I click on any mobile browser ( chrome or mozilla ), I am again prompted the above three options. When I click on the first option **- Join this meeting using the app**, **it again redirects to play store** whereas the **expected** behavior is, it should open the app installed in the phone. Is it a configuration issue in the app or **interface_config.js** file ?

**iOS** ( 2 issues )

**1.** From what I have read in the community page, I need to place the apple-app-association file in .well-known directory. Where exactly am I supposed to place this file  in my docker based backend ?

**2.** How to configure deeplinking for iOS ? The method that I am following is, mentioning URL Types in XCode. Is this the right way to configure deeplinking completely for iOS ?

@saghul as discussed, I have mentioned my issue here. 

Please let me know if you need any more information.

**Comment by saghul** [comment]
>  Is it a configuration issue in the app or **interface_config.js** file ?

Both. Did you configure you app for the domains you care about? You need an intent filter, check how Jitsi Meet does it for meet.jit.si. Then for the links to work you need to customize this part of interface_config.js: https://github.com/jitsi/jitsi-meet/blob/9268255ca857260a298e3b6ea0c639dc3f62729e/interface_config.js#L262 (and the 2 options above it)

**Comment by tusharsonawanes** [comment]
@saghul 

Yes, I have my intent filter in android app. Correct me if I am wrong, because of that, I see the app listed when I click on the link. 

Now, in firebase, I have created a project and in the Dynamic Links Section, I have created a link which successfully redirects me to my custom domain. 

Is it that if I put the same url, say https://example.page.link/meet in my mobile browser, my app will open ? Because that is not happening now. 

I have also added my android app package name and details ( which is available on play store ) in the details section, still no luck.

**Comment by tusharsonawanes** [comment]
Yes, I have added intent filter in the android app. Correct me if I am wrong in the following points

1. Because of adding the intent filter, I can see the application in the **open with** list. 

2. I have also configured firebase dynamic linking. I think we need it when the user clicks **Join this meeting using the app**, the user will be redirected to play store or app store. If the app is installed, then the app will be used. 

3. My dynamic link when opened from the mobile phone, redirects to the app successfully. 

The issue is the button **Join this meeting using the app**, what do I do for it ?

**Comment by tusharsonawanes** [comment]
how and where do I add the apple-app-site-association file to my docker-jitsi-meet based installation ?

**Comment by saghul** [comment]
That button uses an intent link which is generated for your specific app package ID. Did you configure that?

**Comment by tusharsonawanes** [comment]
@saghul Hi. The status as of now is

**Download the app** - Button is working perfectly. It redirects to app/ play store. This is possible because of the

**MOBILE_DOWNLOAD_LINK_IOS**
**MOBILE_DOWNLOAD_LINK_ANDROID** 

setting in interface_config.js file.

Now, my for my android application, we have created an intent filter which opens the app on the click of the link. For iOS, I dont have any idea how to create an intent filter. 

I have figured out how to add **apple-app-site-association** in the .well-known directory. 

How to generate an intent link for iOS and android for "Join this meeting using the app" button ?

**Comment by saghul** [comment]
> For iOS, I dont have any idea how to create an intent filter.

You need to add an "associated domain". You can do that in the "Signing & Capabilities" section in Xcode.

> How to generate an intent link for iOS and android for "Join this meeting using the app" button ?

The link is automatically generated. It uses the configured android package ID and URL scheme configured in interface_config.js.

**Comment by tusharsonawanes** [comment]
Ill check it, give me some time..

**Comment by tusharsonawanes** [comment]
Okaye, in my Signing and capabilities, I have added Associated Domains, in which I have mentioned

```applinks:subdomain.domain.com``` without https://

is it right ?

**Comment by saghul** [comment]
Yes.

**Comment by Waqas619** [comment]
Solution that I would like to share is if we are using import { JaaSMeeting } from "@jitsi/react-sdk";
we can disable deep linking and hide invite page by just passing "  disableDeepLinking: true," in configOverride. This will work on both web and mobile browsers.

  <JaaSMeeting
            roomName={roomName}
            domain={"your-domain-name"}
            appId="vpaas-magic-cookie-abasdadsadasdadadasdasd"
            getIFrameRef={handleJaaSIFrameRef}
            onApiReady={handleApiReady} // Trigger when the Jitsi API is ready
            configOverwrite={{
              disableDeepLinking: true,
              disableShortcuts: true, // Disable all keyboard shortcuts
              prejoinConfig: {
                enabled: false,
              }, // Disable the prejoin page
              disableTileViewContextMenu: true,
            }}
            userInfo={{
              displayName: userName,
              email: userEmail,
            }}
            jwt={jwtToken}
          />
