### ISSUE TITLE
ENABLE_XMPP_WEBSOCKET=0 with nginx reverse proxy

### ISSUE THREAD

**Issue by moe5k** [jitsi/docker-jitsi-meet#902]
As many other i ran in a problem "You have been disconnected ..." with one of the lastest versions (stable-5142-4 in my case). We using nginx reverse proxy in front.

After i read here in the issues that the option
ENABLE_XMPP_WEBSOCKET=0
prevents or works arround this problem i could solve it.

BUT:
1. What exactly does this XMPP_Websocket what i disabled with this option?
2. Why is there not a default etry for this option in the env.example file?

When it is nessesary to switch this feature off for get jitsi to work with a reverse proxy there should be at least
a mandatory setting for this option!

**Comment by saghul** [comment]
Using XMPP over WebSocket instead of BOSH is more reliable. We have been running it on mee.jit.si for months and switched the default here too, now that we are confident it's a net improvement.

If you are using a reverse proxy setup all you need to do is proxy the "xmpp-websocket" route (WebSocket). Same as with WebSocket based datachannels (colibri-ws).

**Comment by laf0rge** [comment]
I am still experiencing this problem with stable-5142-4 behind a nginx reverse proxy. I evene deleted all the configs from ~/.jitsi-meet-cfg and started from scratch. The only work-around that makes jitsi meet functional again is to use ENABLE_XMPP_WEBSOCKET=0

**Comment by moe5k** [comment]
> If you are using a reverse proxy setup all you need to do is proxy the "xmpp-websocket" route (WebSocket). Same as with WebSocket based datachannels (colibri-ws).

What do you exactly mean?
All what i do atm is to proxy the https Port to the http port which the docker container provides.
I do this config via plesk with a plain proxy rule.

**Comment by saghul** [comment]
The xmpp-websocket and colibri-ws routes need to be proxied with WebSocket support. A plan HTTP proxying will no longer be enough. I don't have experience with Plesk so I don't know how to do it in such environment.

**Comment by F-Node-Karlsruhe** [comment]
I tried proxy ws:// in general in apache2 but it had no effect. Where does the xmpp-websocket route has to be proxied to?

**Comment by saghul** [comment]
It has to be proxied to the same place. I don't have much experience with Apache, but I do know you'll need the wstunnel module. Did you enable that?

**Comment by F-Node-Karlsruhe** [comment]
proxy_wstunnel_module is active and i routed ws:// to the same port as the `http one ProxyPassMatch (.*)(\/websocket)$ `ws://127.0.0.1:8085/$1$2
Still setting ENABLE_XMPP_WEBSOCKET=0 is the only way to make it work

**Comment by saghul** [comment]
Others have shared how to configure Apache for this. Note that you need to proxy the incoming WSS connection, not only WS.

**Comment by F-Node-Karlsruhe** [comment]
Sadly i can only find http examples. Can you provide a link to a working websocket jitsi reverse proxy config?

**Comment by saghul** [comment]
Check this: https://github.com/jitsi/docker-jitsi-meet/issues/854#issuecomment-740681178

**Comment by F-Node-Karlsruhe** [comment]
i still get `Firefox kann keine Verbindung zu dem Server unter wss://localhost:8443/xmpp-websocket?room=test`

i wonder why he is trying to connect under the jitsi https port on localhost o.O

**Comment by saghul** [comment]
What is your PUBLIC_URL set to?

**Comment by F-Node-Karlsruhe** [comment]
It was not set. now it works :)

**Comment by normen** [comment]
Are you sure it works correctly now? Or do you also get errors about the colibri-ws websocket in the web client? It works but the video quality stays low and theres constant errors about the colibri-ws websocket.

**Comment by sapkra** [comment]
@normen Can you post the errors you get?

**Comment by normen** [comment]
> @normen Can you post the errors you get?

See https://github.com/jitsi/docker-jitsi-meet/issues/943
