### ISSUE TITLE
jwt and guest access

### ISSUE THREAD

**Issue by badsmoke** [jitsi/docker-jitsi-meet#907]
hello we use our jitsi in combination with mattermost.

only the users of mattermost (jwt) are able to start a channel but if the channel is open of course still external should have access.

with version stable-5142 this worked fine. With the latest version stable-5142-4, but unfortunately this no longer works.

I have already tried all combinations of 

JWT_ALLOW_EMPTY=1/0
ENABLE_GUESTS=1/0

tried.

what I would like to have:

only user with jwt can create channel. guests (without jwt) can join it

**Comment by badsmoke** [comment]
even with the latest version it still does not work for me

**Comment by badsmoke** [comment]
has no one an idea?

**Comment by Twilek-de** [comment]
I am having a similar problem. Jitsi worked fine with Mattermost. Now I get an Auth Error with "Sorry you are not allowed to be here". I have completely reinstalled Jitsi with the latest stable. Still not working.

**Comment by saghul** [comment]
Try making this change and setting the value to false: https://github.com/jitsi/docker-jitsi-meet/commit/47804d0b9e1657debf0200472e3eb22563a26100

**Comment by Twilek-de** [comment]
> Try making this change and setting the value to false: [47804d0](https://github.com/jitsi/docker-jitsi-meet/commit/47804d0b9e1657debf0200472e3eb22563a26100)

That was the problem! Thanks a lot!!

**Comment by gh4tg** [comment]
Hi,

had the same error when upgraded from stable-7439-2 to the latest stable-7882, I figured out, that the error was already "introduced" in 7577, when jwt-auth stopped working with the above error:

`authError.html -> 'Sorry you are not allowed to be here.'`

The named parameter is not jet working in stable-7577-2, but it does (at least) in stable-7882.

Please include the parameter "JWT_ENABLE_DOMAIN_VERIFICATION=0" in the 'env.example', I needed a lot of hours to figure it out!

Thanks a lot!
