### ISSUE TITLE
Jitsi 80,443 port these ports do not work externally

### ISSUE THREAD

**Issue by oguzhansrky** [jitsi/docker-jitsi-meet#909]
Hi,

http and https ports are different from the default in "env.example" given as an example. 

I cannot give default http and https ports (80,443) for jitsi. When I set it to 32829 and 32830 "you have been disconnected." I get an error.

Why do I have to give port 80 and 443?

**Comment by saghul** [comment]
If you want your setup to be accessible to the world you should probably use standard ports, that is, 80 and 443.
