### ISSUE TITLE
Default etherpad welcome text: double quotes and line breaks not working

### ISSUE THREAD

**Issue by tele-tom** [jitsi/docker-jitsi-meet#910]
stable-5142-4: release

After opening shared document the headline is like this
`""Welcome to video chat\n\n""`

So the new lines not respected and the double quotes are printed twice.
If I remove the double quotes from .env there are still quotes in the pad. There are no quotes needed at all in the welcome text.
Would be great to fix this.

**Comment by sapkra** [comment]
Do you have the latest docker-compose installed?

**Comment by saghul** [comment]
@sapkra Can we fix this so it works also on no-quite-the-latest compose?

**Comment by sapkra** [comment]
Maybe we need this change then: https://github.com/jitsi/docker-jitsi-meet/pull/862

**Comment by saghul** [comment]
Looks like it indeed. Alas the branch got deleted so I can't merge the PR, care to open a new one?

**Comment by tele-tom** [comment]
> Do you have the latest docker-compose installed?

it's 1.24.1 on a debian `stretch` machine.

**Comment by tele-tom** [comment]
Now updated to docker-compose 1.28.2:

Line break works now and double quotes are no matter anymore but it looks like that:
```
"Welcome to video chat

"
```

**Comment by saghul** [comment]
The fix landed.
