### ISSUE TITLE
TCP connection reset by peer

### ISSUE THREAD

**Issue by grahhnt** [jitsi/docker-jitsi-meet#913]
I am unable to connect to my docker instance through CURL or via browser on another computer on the network

**Comment by uvwild** [comment]
How about some info regarding environment. Otherwise, i am sorry it didnt work.
too bad you did not share any information which could give any insight to why.
Maybe you did not plugin the cable?

**Comment by grahhnt** [comment]
@uvwild i forgot to reply to this, it was due to my docker version not at the correct version for CentOS 7
I don't remember the article sadly but you should be able to find it
