### ISSUE TITLE
acme.sh permission denied

### ISSUE THREAD

**Issue by Normand-Nadon** [jitsi/docker-jitsi-meet#914]
This is the first time that I face this issue... It is not a problem on my older jitsi-meet build from this fall in the same environment

Docker logs from web container finishes with this:

```
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-set-timezone: executing... 
[cont-init.d] 01-set-timezone: exited 0.
[cont-init.d] 10-config: executing... 
/var/run/s6/etc/cont-init.d/10-config: line 27: /config/acme.sh/acme.sh: Permission denied
/var/run/s6/etc/cont-init.d/10-config: line 44: /config/acme.sh/acme.sh: Permission denied
Failed to install certificate.
```
I am looking into the issue but I am no expert on that!

**Comment by saghul** [comment]
Have you tried wiping your config volume?

**Comment by Normand-Nadon** [comment]
I realized this weekend that the current build differs from the ones from this fall as they don't use the letsencrypt folder anymore...
I rebased my project completely and erased all folders and did many more things... One of those things fixed the issue.
(I am forking from the master repo to pre-load some stuff on our install so my build must have had something incompatible with the current master)

**Comment by rrupi** [comment]
I ran into the same problem, after reading this i did try with a fresh git clone and a wiped config volume. Unfortunatly the problem persists.

**Comment by rrupi** [comment]
I pulled the images from docker hub -> same problem. So it's not a bug in buildprocess but has something to do with the configuration?
