### ISSUE TITLE
Provide images with latest stable release 5390

### ISSUE THREAD

**Issue by dawidmalina** [jitsi/docker-jitsi-meet#915]
Can you please provide information when new images will be provided.

**Comment by dasfreak** [comment]
:+1:  because this allegedly fixes https://github.com/RocketChat/Rocket.Chat.Electron/issues/1841

**Comment by merlin-tc** [comment]
> 👍 because this allegedly fixes [RocketChat/Rocket.Chat.Electron#1841](https://github.com/RocketChat/Rocket.Chat.Electron/issues/1841)

Yes, we are hit by the same bug and use docker so a new version would be greatly appreciated!

**Comment by saghul** [comment]
Hopefully by the end of the week.

**Comment by saghul** [comment]
Done.
