### ISSUE TITLE
Question: Local Jitsi

### ISSUE THREAD

**Issue by abhatikar** [jitsi/docker-jitsi-meet#916]
Hello, 
I followed the https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker to setup my local jitsi server. 
I just want to set up a local jitsi video conferencing over LAN. I got issues with the latest build with error "You have been disconnected. You may want to check your network connection". 
I then pulled the **stable-5076** version and with same steps I was able to run the portal. But I am not getting access to microphone and camera on my browser. 
Please help.

**Comment by saghul** [comment]
Please provide more details like console logs.

**Comment by abhatikar** [comment]
@saghul 

I downloaded the latest stable [release](https://github.com/jitsi/docker-jitsi-meet/releases/tag/stable-5765-1) and followed the [guide](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker) .
I am using mac to run the application. After docker compose is completed. I see 2 issues

1.  https://localhost:8443 gives an error on chrome saying not secure

<img width="1280" alt="Screenshot 2021-04-22 at 09 45 31" src="https://user-images.githubusercontent.com/7994511/115684863-9c013200-a34f-11eb-8e84-88d8577efd71.png">


2.  http://localhost:8000 opens up the jitsi welcome page and asks to create a room. When I create a room, it gives this error
<img width="1789" alt="Screenshot 2021-04-22 at 09 47 45" src="https://user-images.githubusercontent.com/7994511/115685093-d36fde80-a34f-11eb-8b0d-7b50f2acda65.png">

I just want to create a jitsi environment on lan where 2 mobile phones with jitsi app can talk to each other without connecting to internet. Kindly help.

thanks in advance,

**Comment by saghul** [comment]
The first error is because you didn't use Let's Encrypt or your own cert, so we generate a self-signed one, which is of course not trusted by Chrome.

WebRTC cannot be used with HTTP, you need HTTPS, hence the second error.

**Comment by abhatikar** [comment]
Thanks @saghul I got away with the second error with ENABLE_XMPP_WEBSOCKET=0 in the .env file.

I need your help for the first error. To give you a context, I want to use jitsi on local lan. No internet. How to go about that ?

I generated self signed certificate and put in the $HOME/.jitsi-meet-cfg/web/keys/ but still not luck. please guide.

**Comment by abhatikar** [comment]
You will have to setup ssl and then it should work.

**Comment by gcravo** [comment]
Can you explain how did you do that @abhatikar ? 

> You will have to setup ssl and then it should work.
