### ISSUE TITLE
How to edit interface_config?

### ISSUE THREAD

**Issue by ramsesdeux** [jitsi/docker-jitsi-meet#917]
Hi All,

After going through all thread on this issues page, none of the solution I saw here actually works when it comes to edit interface_config.js

Or maybe they work, but instructions aren't clear/complete enough for a beginner user to actually successfully achieve it.

I'm looking to set  **GENERATE_ROOMNAMES_ON_WELCOME_PAGE** and **GENERATE_ROOMNAMES_ON_WELCOME_PAGE**   both  to **false** 

I'd like to follow instruction from this post:
https://community.jitsi.org/t/remove-disable-welcome-page/30780/8

Within a docker environment nothing seems to work.

Of course I followed the posts below, sadly nothing seems to work.
https://github.com/jitsi/docker-jitsi-meet/issues/886
https://github.com/jitsi/docker-jitsi-meet/issues/768#issuecomment-705536542
https://community.jitsi.org/t/remove-disable-welcome-page/30780

Would be wonderful if anyone had a real working solution?

Thank you a ton in advance :)

**Comment by Normand-Nadon** [comment]
This question is not a bug, it should be discussed in the community forums ;)
https://community.jitsi.org/

By default, the file interface_config.js and config.js are located in 
~/.jitsi-meet-cfg/web/

**Comment by ramsesdeux** [comment]
Thank you for the feedback @Normand-Nadon, and sorry for placing the request here 😅

I wasn't able to find the answer on the community forums, and this info isn't clearly mentioned anywhere.
Thanks a lot, I'll try that straight away.
