### ISSUE TITLE
nginx is not using Lets Encrypt certificates

### ISSUE THREAD

**Issue by SMUsamaShah** [jitsi/docker-jitsi-meet#92]
Using `ENABLE_LETSENCRYPT` and allows lets encrypt install script to run and it generates certificates successfully. But nginx still keeps using the default certificates instead of lets encrypt.

This is how the nginx config file inside jitsi/web container looks like

```conf
root@fa610f8c947b:/# echo $ENABLE_LETSENCRYPT
1
root@fa610f8c947b:/# cat /config/nginx/ssl.conf
# session settings
ssl_session_timeout 1d;
ssl_session_cache shared:SSL:50m;
ssl_session_tickets off;

# Diffie-Hellman parameter for DHE cipher suites
ssl_dhparam /config/nginx/dhparams.pem;

# ssl certs

ssl_certificate /config/keys/cert.crt;
ssl_certificate_key /config/keys/cert.key;


# protocols
ssl_protocols TLSv1.2;
ssl_prefer_server_ciphers on;
ssl_ecdh_curve secp384r1;
ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDH+CHACHA20:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK;

# headers
add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload";
add_header X-Content-Type-Options nosniff;
add_header X-XSS-Protection "1; mode=block";
```

**Comment by saghul** [comment]
Did you change the settings in your `.env` file without re-creating the containers?

**Comment by SMUsamaShah** [comment]
No. I changed the .env file and set ENABLE_LETSENCRYPT , LETSENCRYPT_DOMAIN and LETSENCRYPT_EMAIL variables. 

I removed the container everytime and then started all containers with `docker-compose up -d` or only meet container with `docker-compose up -d web`.

I ended up modifying nginx.conf manually to point to letsencrypt key and cert files and restarted nginx. Only that worked.

**Comment by saghul** [comment]
You need to remove the CONFIG directory every time you mnodify the .env file. https://github.com/jitsi/docker-jitsi-meet#configuration

**Comment by ansgerl** [comment]
Unfortunately removing the CONFIG directory did not help to solve the problem.
