### ISSUE TITLE
Missing Https redirection in the current build

### ISSUE THREAD

**Issue by Normand-Nadon** [jitsi/docker-jitsi-meet#920]
Since I have rebuilted my instance from the latest stack on 2021-01-23, it is not automatically forwarding http requests to https as it did before

It seems like there is a missing 301-type redirection in the config. I will try to manually change it but I think it should be included in the stack.

**Comment by Normand-Nadon** [comment]
adding: _return 301 https://$host$request_uri;_ in the default nginx config file fixed it...

I can see a line in the build that should forward this config based on .env but it seems like it failed.

`	{{ if .Env.ENABLE_HTTP_REDIRECT | default "0" | toBool }}
	return 301 https://$host$request_uri;
	{{ else }}
	include /config/nginx/meet.conf;
	{{ end }}`

Hope I can help some way...

**Comment by saghul** [comment]
Did you set the ENABLE_HTTP_REDIRECT env variable in your .env file?
