### ISSUE TITLE
Edit the startWithAudioMuted variable

### ISSUE THREAD

**Issue by f0086** [jitsi/docker-jitsi-meet#921]
I want to edit the ```startWithAudioMuted``` and other settings where there are no environment variables in ```.env``` to set. New environment variables are needed here or an "additional" custom settings variable to set custom stuff. I could not find any hints for that in the template file (https://github.com/jitsi/docker-jitsi-meet/blob/master/web/rootfs/defaults/settings-config.js)

According to this (official?) guide ...
> IMPORTANT: At the moment, the configuration is not regenerated on every container boot, so if you make any changes to your .env file, make sure you remove the configuration directory before starting your containers again.

... the configuration should not overwritten after a restart, but **this is the case**. So, manually edit the ```config.js``` and ignore the ```.env``` file is not an option. Or do I miss something?

**Comment by saghul** [comment]
Oops, we have to update the guide. The config is indeed regenerated on every container boot.

**Comment by saghul** [comment]
Updated the handbook.

> I want to edit the `startWithAudioMuted` and other settings where there are no environment variables in `.env` to set. New environment variables are needed here or an "additional" custom settings variable to set custom stuff. I could not find any hints for that in the template file (https://github.com/jitsi/docker-jitsi-meet/blob/master/web/rootfs/defaults/settings-config.js)

You'd need to add a new env variable. You can look in that file and do it analogously to the other ones.

**Comment by saghul** [comment]
> OR a mechanism to add "custom" settings not exposed by a env variable.

That already exists: https://github.com/jitsi/docker-jitsi-meet/blob/88d1034e32a59aec15602bd6520d1eb3ec17ec66/web/rootfs/etc/cont-init.d/10-config#L82-L83
