### ISSUE TITLE
Customize interface_config

### ISSUE THREAD

**Issue by shanehughes1990** [jitsi/docker-jitsi-meet#922]
Was wondering if currently there is a way to customize the settings in interface_config.js like you do in web/root/defaults/settings-config.js?, Or no of a way to implement an interface-settings.js? We can start filling out to start using environment variables for that file as well? My goal is to _NOT_ have to mount either file, A PR was already merged for the config.js settings that I needed now I got to figure out how to do it with interface_config.js as well?

**Comment by saghul** [comment]
You can now specify a custom interface config file which will be concatenated: https://github.com/jitsi/docker-jitsi-meet/blob/master/web/rootfs/etc/cont-init.d/10-config#L87-L89
