### ISSUE TITLE
LDAP authentication stopped working with 5390-1

### ISSUE THREAD

**Issue by Twilek-de** [jitsi/docker-jitsi-meet#924]
With the latest release 5390-1 Ldap auth stopped working for me. I changed nothing with my LDAP config in .env and it now says in the logs

```
prosody_1  | saslauthd[259] :released accept lock
prosody_1  | saslauthd[241] :acquired accept lock
prosody_1  | saslauthd[259] :attempting a read lock on slot: 365
prosody_1  | saslauthd[259] :[login=Twilek] [service=xmpp] [realm=meet.jitsi]: not found, update pending
prosody_1  | saslauthd[259] :attempting to release lock on slot: 365
prosody_1  | saslauthd[259] :auth failure: [user=Twilek] [service=xmpp] [realm=meet.jitsi] [mech=ldap] [reason=Unknown]
prosody_1  | saslauthd[259] :response: NO
```

**Comment by pwFoo** [comment]
Tried to move from internal auth to ldap today...
Fails with 5390-1 and stable-5142
```
60159737 conn=1258 fd=12 ACCEPT from IP=10.0.8.4:60438 (IP=0.0.0.0:389)
60159737 conn=1258 op=0 BIND dn="uid=jitsi,ou=bind,dc=example,dc=com" method=128
60159737 conn=1258 op=0 BIND dn="uid=jitsi,ou=bind,dc=example,dc=com" mech=SIMPLE ssf=0
60159737 conn=1258 op=0 RESULT tag=97 err=0 text=
60159737 conn=1258 op=1 SRCH base="ou=users,dc=example,dc=com" scope=2 comref=0 filter="(&(objectClass=inetOrgPerson)(uid=%u)(memberOf=cn=jitsi,ou=groups,dc=example,dc=com))"
60159737 conn=1258 op=1 SRCH attr=dn
60159737 conn=1258 op=1 SEARCH RESULT tag=101 err=32 nentries=0 text=
```
`%u` is replaced by the correct login user, but login fails.

Tested different filters... Here three examples tested with and without LDAP_BASE.

- `(uid=%u)`
- `(cn=%u)`
- `(cn=%u,ou=users,dc=example,dc=com)`
- `(&(objectClass=inetOrgPerson)(uid=%u)(memberof=CN=jitsi,OU=groups,dc=example,dc=com))`

Also simple filters fail. Anyone get ldap working with stable-5390-1 (or older versions back to stable-5142)?
```
AUTH_TYPE=ldap

LDAP_AUTH_METHOD=bind
LDAP_URL=ldap://ldap/
LDAP_VERSION=3
LDAP_USE_TLS=0
LDAP_BASE='ou=users,dc=example,dc=com'
LDAP_BINDDN='uid=jitsi,ou=bind,dc=example,dc=com'
LDAP_BINDPW='<password>'
```

**Comment by Twilek-de** [comment]
Actually my config worked fine with the previous version so I am wondering if something changed or is broken with the current version.

**Comment by pwFoo** [comment]
Could you share your configuration to compare with my one? 
Can't get it work with older versions too... filter works fine with phpldapadmin web gui and fails with jitsi.

**Comment by Twilek-de** [comment]
```
# LDAP authentication (for more information see the Cyrus SASL saslauthd.conf man page)
#

# LDAP url for connection
LDAP_URL=ldap://172.17.0.1/

# LDAP base DN. Can be empty
LDAP_BASE=DC=xxx,DC=de

# LDAP user DN. Do not specify this parameter for the anonymous bind
LDAP_BINDDN=CN=admin,DC=xxx,DC=de

# LDAP user password. Do not specify this parameter for the anonymous bind
LDAP_BINDPW=xxx

# LDAP filter. Tokens example:
# %1-9 - if the input key is user@mail.domain.com, then %1 is com, %2 is domain and %3 is mail
# %s - %s is replaced by the complete service string
# %r - %r is replaced by the complete realm string
#LDAP_FILTER=(sAMAccountName=%u)
LDAP_FILTER=(uid=%u)

# LDAP authentication method
LDAP_AUTH_METHOD=bind

# LDAP version
LDAP_VERSION=3

# LDAP TLS using
LDAP_USE_TLS=1

# List of SSL/TLS ciphers to allow
#LDAP_TLS_CIPHERS=SECURE256:SECURE128:!AES-128-CBC:!ARCFOUR-128:!CAMELLIA-128-CBC:!3DES-CBC:!CAMELLIA-128-CBC

# Require and verify server certificate
LDAP_TLS_CHECK_PEER=0

# Path to CA cert file. Used when server certificate verify is enabled
#LDAP_TLS_CACERT_FILE=/etc/ssl/certs/ca-certificates.crt

# Path to CA certs directory. Used when server certificate verify is enabled
#LDAP_TLS_CACERT_DIR=/etc/ssl/certs

# Wether to use starttls, implies LDAPv3 and requires ldap:// instead of ldaps://
LDAP_START_TLS=1

```

**Comment by Twilek-de** [comment]
Oh Open-LDAP reports an error whenever I try logging in:

`slapd[3982376]: conn=1012 op=0 do_extended: unsupported operation "1.3.6.1.4.1.1466.20037"`

**Comment by Twilek-de** [comment]
Ok that was TLS not working (for whatever reason). Turned TLS off. Now Slapd does not report any errors anymore but authentication still is not working...

**Comment by Twilek-de** [comment]
This kind of embarrassing. It seems I simply used the wrong password (or OpenLDAP messed up its data, but I suspect it is rather my own fault). I reset my password in in OpenLDAP and abracadabra it´s working again....

**Comment by pwFoo** [comment]
I have still the same problem with an additional user and changed password. Still can't auth a user... binddn works.
Any idea way user auth fails with a search filter works fine with phpldapadmin fronted for openldap  backend?

**Comment by eudoxos** [comment]
Hitting the same issue. When I enter the container (`docker exec -ti docker-jitsi-meet-stable-8044_prosody_1 /bin/bash`), I can check `/etc/saslauthd.conf` and run `testsaslauth -u user -p pwd -r jitsi.meet -s xmpp`, which returns success. But when I run from the web interface, I see the "not found, update pending". Any solution to this?
