### ISSUE TITLE
run gen-passwords.sh without bash (Asustor NAS)

### ISSUE THREAD

**Issue by Harrenkyym** [jitsi/docker-jitsi-meet#925]
Hi all.

The thing is I can't run gen-passwords.sh because my distro is not very usual, is ADM from ASUS adn I don't know how to do it.

`docker-jitsi-meet $ ./gen-passwords.sh
-sh: ./gen-passwords.sh: not found
`

I've tried to remove the first line of the .sh, I've tried to change it to #!/bin/sh, but nothing... As you can guess, I don't have bash (and I can't install it). It's a very limited distro... what can I do?

**Comment by ghostbusker** [comment]
I was trying to build from the Docker setup instructions and had a similar issue on Windows (Server). After looking at 'gen-passwords.sh' it's apparent that all the file does is generate a random string of 32 hexidecimal digits for each of the six empty XMPP paswords near the top of the .env file. For me, the fastest thing to do was to move the two files '.env' and 'gen-passwords.sh' to a linux system to run the command. I used a thumb drive and raspberry pi. You could just generate some random 32 digit hex strings and paste them into '.env' using a text editor instead. There are online generators that will produce examples that look like this "ad06168ea98bafe90e3a4d2434a35743".

**Comment by saghul** [comment]
You don't need to run the script per se, you can just come up with some passwords of your own and put them on the env file.
