### ISSUE TITLE
Multi domain suppor behind reverse proxyt?

### ISSUE THREAD

**Issue by pwFoo** [jitsi/docker-jitsi-meet#927]
Hi,

with an older version it was possible to modify the host header to backends. Just rewrite the host header from second domain to the first one was enough to get it working. With the latest version it fails. I don't know if it related to changes in jitsi docker. But maybe it's just a problem with the domain name the websocket uses?

I the the PRIMARY _DOMAIN instead of the used SECONDARY_DOMAIN in chrome developer tools.
```
WebSocket connection to 'wss://<PRIMARY_DOMAIN>/xmpp-websocket?room=test123' failed: Error during WebSocket handshake: Unexpected response code: 403
_connect @ lib-jitsi-meet.min.js?v=4628:1
connect @ lib-jitsi-meet.min.js?v=4628:1
_interceptConnectArgs @ lib-jitsi-meet.min.js?v=4628:25
connect @ lib-jitsi-meet.min.js?v=4628:1
_connect @ lib-jitsi-meet.min.js?v=4628:1
connect @ lib-jitsi-meet.min.js?v=4628:1
c.connect @ lib-jitsi-meet.min.js?v=4628:10
e @ app.bundle.min.js?v=4628:83
(anonymous) @ app.bundle.min.js?v=4628:83
d @ app.bundle.min.js?v=4628:83
h @ app.bundle.min.js?v=4628:83
W @ app.bundle.min.js?v=4628:113
createInitialLocalTracksAndConnect @ app.bundle.min.js?v=4628:113
init @ app.bundle.min.js?v=4628:113
Logger.js:154 2021-01-31T12:44:59.409Z [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: Strophe: Websocket error [object Event] Script: null Line: null Column: null StackTrace:  Error: Strophe: Websocket error [object Event]
```

Would it help to use the given domain name instead of the first / primary one for websocket connection?

With older versions it was easy to get the second domain working! Just rewrite the host header at the reverse proxy before pass it to the backend. Example with caddy swarm proxy configured by labels:
```
caddy: "<PRIMARY _DOMAIN> <SECONDARY_DOMAIN>"
caddy.reverse_proxy: "{{upstreams 80}}"
caddy.reverse_proxy.header_up: "Host <PRIMARY _DOMAIN>"
caddy.log.output: "stdout"
```
So backend gets <PRIMARY _DOMAIN> also if <SECONDARY_DOMAIN> was used from the user. Worked fine for me some time, but fails since I updated to latest jitsi docker version.

**Comment by pwFoo** [comment]
Also tested cors settings, but 403 seems to be not related to cors. Any ideas how to get second domain working with reverse proxy?

**Comment by p-schneider** [comment]
Have you seen the new config variable `XMPP_CROSS_DOMAIN`? That setting was introduced 3 months ago in 5679578d808e33e0eb2ffbcff67e8b643992b177 and could relate to your problem. (I haven't tried it myself yet.)

I have been using a simlar setup (with apache as reverse proxy) until it stopped working.
(Currently I'm forwarding the secondary domain to the primary domain in apache as a temporary workaround, I plan to revert back to the old behaviour once I get it to work.)

**Comment by pwFoo** [comment]
But seems not supported by ENV Vars / docker-compose.yml?

**Comment by ccoenen** [comment]
Yeah, with the last update, our multi-domain setup broke, too. If someone has a viable solution to this, I'm all ears.

**Comment by MartijnHols** [comment]
You can allow all domains by adding `XMPP_CROSS_DOMAIN=true` to your `.env`. Ideally you'd list all the supported domains except for the public url in that env var (e.g. `XMPP_CROSS_DOMAIN=http://example.com`), but that doesn't seem to be working correctly as it gives errors in Chrome; `Access to XMLHttpRequest at 'https://jitsi.example.app/http-bind?room=example' from origin 'https://example.dev' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The 'Access-Control-Allow-Origin' header contains multiple values 'https://jitsi.example.app, https://meet.jitsi, https://example.dev', but only one is allowed.`

**Comment by MartijnHols** [comment]
Workaround for the standard web client:

Add `XMPP_CROSS_DOMAIN=true` to `.env`.

Add `- ./web/rootfs/defaults/system-config.js:/defaults/system-config.js:ro` to the volumes of the web container.

Edit `web/rootfs/defaults/system-config.js`; change `config.websocket = 'wss://{{ $PUBLIC_URL_DOMAIN }}/xmpp-websocket';` into `config.websocket = 'wss://' + window.location.origin.replace(/^https?:\/\//, '') + '/xmpp-websocket';`.

**Comment by gthbusrr** [comment]
I have the same problem.... I tried @MartijnHols 's solution and it worked flawlessly on web clients but not on mobile apps. I've added a "fallback" so that it'll set uri to $PUBLIC_URL_DOMAIN when window.location is not availble. However, it returns to square one where the Secondary URL doesn't work.

**Comment by saghul** [comment]
This is not a use case we have plans to support, sorry.
