### ISSUE TITLE
Lobby button missing in docker environment

### ISSUE THREAD

**Issue by steglicd** [jitsi/docker-jitsi-meet#930]
I'm using the Jitsi docker images (see: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker)
Everything works fine. Two days ago the ```jitsi/web``` container was updated. Now the Lobby button is missing.

I already tried to uncomment this:
```hideLobbyButton: false,```
in ~/.jitsi-meet-cfg/web/config.js, but this did not worked.

Following this discussion here:
https://community.jitsi.org/t/fix-lobby-not-working-after-upgrade-to-latest-version-2-0-5390/90541
It seems like the ```"muc_lobby_rooms"; ``` must be moved under a different section of the prosody config. But since this config files are not persistent volumes of the ```jitsi/prosody``` container this can't be done without mountig that files as volume (which I want to avoid since I want to have the most recent version of that config)-

reverting ```jitsi/web``` to ```jitsi/web:stable-5142-4``` fixes the issue.

**Comment by sysadmama** [comment]
Can confirm.

Had to manually correct `.jitsi-meet-cfg/prosody/config/conf.d/jitsi-meet.cfg.lua` so `VirtualHost "meet.jitsi"` contains `main_muc` and `lobby_muc`; the initial config has these within `VirtualHost "guest.meet.jitsi"` which seems to be wrong meanwhile. Also had ensured the corrected config is not overwritten again.

```
VirtualHost "meet.jitsi"

    authentication = "internal_hashed"
    ssl = {
        key = "/config/certs/meet.jitsi.key";
        certificate = "/config/certs/meet.jitsi.crt";
    }
    modules_enabled = {
        "bosh";
        "websocket";
        "smacks"; -- XEP-0198: Stream Management
        "pubsub";
        "ping";
        "speakerstats";
        "conference_duration";
        "muc_lobby_rooms";
    }

    main_muc = "muc.meet.jitsi"
    lobby_muc = "lobby.meet.jitsi"

    speakerstats_component = "speakerstats.meet.jitsi"
    conference_duration_component = "conferenceduration.meet.jitsi"

    c2s_require_encryption = false
```

**Comment by saghul** [comment]
Sigh, I thought I had applied the fix, but I did it in the wrong branch 🤦 . Anyway, `stable-5390-2` is being uploaded now with the fix. Cheers!

**Comment by sysadmama** [comment]
@saghul Doesn't matter, shit happens :)
Thank you for all your hard work!
