### ISSUE TITLE
Websocket request to /xmpp-websocket sent to wrong port?

### ISSUE THREAD

**Issue by jonashaag** [jitsi/docker-jitsi-meet#931]
Using the latest release and vanilla Docker setup instructions, I can't connect to any meeting. The `wss://.../xmpp-websocket` request is being sent to `PUBLIC_URL` (without the custom port). When I add `:8443` to `PUBLIC_URL` it works.

My config:

```diff
--- .env.bak	2021-02-01 11:58:08.375663409 +0100
+++ .env	2021-02-01 12:47:08.091436914 +0100
@@ -45,12 +45,12 @@
 TZ=UTC

 # Public URL for the web service (required)
-#PUBLIC_URL=https://meet.example.com
+PUBLIC_URL=https://<mymachine.local>:8443

 # IP address of the Docker host
 # See the "Running behind NAT or on a LAN environment" section in the Handbook:
 # https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#running-behind-nat-or-on-a-lan-environment
-#DOCKER_HOST_ADDRESS=192.168.1.1
+DOCKER_HOST_ADDRESS=192.168.X.Y # (the local IP address of mymachine.local)

 # Control whether the lobby feature should be enabled or not
 #ENABLE_LOBBY=1
```

**Comment by saghul** [comment]
That's correct. PUBLIC_URL should have the URL in the same form as others would type it in a browser. If you are using a custom port it won't work in a browser either, hence the need to specify it there.

**Comment by jonashaag** [comment]
But why isn’t it part of the documentation then? The default example uses port 8443 but does not include the port in the placeholder. I think it’s misleading.

**Comment by saghul** [comment]
Because humans make mistakes, and this piece of software is written by humans. If you feel this could be improved please feel free to open a PR, that would be most welcome.
