### ISSUE TITLE
Best practice update?

### ISSUE THREAD

**Issue by solick** [jitsi/docker-jitsi-meet#936]
Hi, just wanna know if there is a best practice for updating?

From what I see we need to save docker-compose.yml and .env (if changed), than stash, than stop and remove from docker, than pull the stable release tag, copy yml and .env file back and build again. Is this correct?

**Comment by saghul** [comment]
Yep, that's pretty much the gist of it!

**Comment by normen** [comment]
I even completely delete `.env` and copy in the `env.example`, then just `sed`-replace the options in question each time I do a new build. This is because sometimes new options get added to `.env` and I had the build fail a few times because of missing new options.

**Comment by saghul** [comment]
> This is because sometimes new options get added to `.env` and I had the build fail a few times because of missing new options.

This shouldn't happen any more, we've stopped adding stuff to .env and make the code use default when env vars are not provided. I intend to drop almost all options from .env altogether.

**Comment by normen** [comment]
> This shouldn't happen any more, we've stopped adding stuff to .env and make the code use default when env vars are not provided. I intend to drop almost all options from .env altogether.

This sounds good, adding each and every parameter from every component to ENV vars seemed to get out of hand :)

**Comment by JacBra** [comment]
Sure thing. These are all included in the docker-compose.yml files such that one knows which ENV vars exists, right?
Is there somewhere documentation of all available ENV vars?
