### ISSUE TITLE
Missing all.css

### ISSUE THREAD

**Issue by Maurotb** [jitsi/docker-jitsi-meet#94]
Hi, after deploy jitsi latest with docker , i got missing all.css
i need to copy this file from another installation
thanks

**Comment by saghul** [comment]
No, you don't need to copy the file from anywhere. What steps are you following exactly?

**Comment by Maurotb** [comment]
I use compose, this is my docker- compose...

version: '2'

services:
    # Frontend
    web:
        image: jitsi/web
        restart: always
        ports:
            - '${HTTP_PORT}:80'
            - '${HTTPS_PORT}:443'
        volumes:
            - ${CONFIG}/web:/config
            - ${CONFIG}/web/css:/usr/share/jitsi-meet/css
        environment:
            - ENABLE_AUTH
            - ENABLE_GUESTS
            - JICOFO_AUTH_USER
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_BOSH_URL_BASE=http://xmpp.meet.jitsi:5280
            - XMPP_GUEST_DOMAIN
            - XMPP_MUC_DOMAIN
            - TZ
        networks:
            meet.jitsi:

**Comment by saghul** [comment]
That is not a list of steps. Please type exactly what steps you followed to setup your containers so I can spot any mistakes, as I cannot reproduce the issue with the recommended setup.

**Comment by saghul** [comment]
> - ${CONFIG}/web/css:/usr/share/jitsi-meet/css

Why are you doing this? You are overriding the files in the jitsi/web image. It's missing in your volume.
