### ISSUE TITLE
xmpp-websocket proxy issues again in 5390-3

### ISSUE THREAD

**Issue by normen** [jitsi/docker-jitsi-meet#941]
It seems that the xmpp-websocket connection is broken again in 5390-3 when running behind an external http(s) proxy.

Given the issue #850 I updated my external nginx proxy with this setting:

```
location = /xmpp-websocket {
	proxy_pass http://0.0.0.0:38000/xmpp-websocket;
	proxy_http_version 1.1;
	proxy_set_header Connection "upgrade";
	proxy_set_header Upgrade $http_upgrade;
	tcp_nodelay on;
}
```

And it worked up to 5390-2. Now I am getting "A network error occurred try again" and 404 errors in the Jitsi WebApp JS console.

Safari JS Console:
```
[Error] WebSocket connection to 'wss://meet.bitwaves.de:8443/xmpp-websocket?room=friesenschlampen' failed: Unexpected response code: 404
```

**Comment by normen** [comment]
It seems that this is was due to the newly added port in the `.env` file, my install script replaced only the URL part, resulting in the wrong port being set there.

**Comment by normen** [comment]
Reopenig this - it seems that when I set the _correct_ external port in the .env file the xmpp endpoint can't be reached.. When I don't set it the connection works but the `colibri-ws` endpoint can't be reached then.

**Comment by sebastianrothe** [comment]
@normen I like the name of your channel :P

**Comment by normen** [comment]
> @normen I like the name of your channel :P

What channel?

**Comment by sebastianrothe** [comment]
> > @normen I like the name of your channel :P
> 
> What channel?

`'wss://meet.bitwaves.de:8443/xmpp-websocket?room=friesenschlampen'`

**Comment by normen** [comment]
> > > @normen I like the name of your channel :P
> > 
> > 
> > What channel?
> 
> `'wss://meet.bitwaves.de:8443/xmpp-websocket?room=friesenschlampen'`

Ah, thats the name of my band. Its gotten so easy to play the bad boy again these days - we even got a facebook ban 🤪😂
