### ISSUE TITLE
Always Connect Fail !!!!!

### ISSUE THREAD

**Issue by Jacky-LinPeng** [jitsi/docker-jitsi-meet#942]
Install by Docker
 Access to: https://192.168.0.104:8443  
<img width="848" alt="image" src="https://user-images.githubusercontent.com/15797691/107116051-d6f4dd00-68ab-11eb-9e9a-4d6d1d48c56d.png">

but  https://localhost:8443 is OK
<img width="744" alt="image" src="https://user-images.githubusercontent.com/15797691/107116079-ff7cd700-68ab-11eb-96bf-1dd581904250.png">

Can anyone help me solve it？

 What is the port of WSS? I tried to connect with WebRTC client of IOS locally, but I couldn't connect.
I've been unable to find the documentation,

Hope to wait for your help

licode 用docker 搭建服务之后也是类似的问题，localhost可以正常 但是使用192.168.0.104访问 摄像头就出不来 用webRTC测试连接192.168.0.104 根本连不上，  
jitsi也是很醉，有大神出来指导一下吗？
哎... 从入门到放弃.....

**Comment by saghul** [comment]
Please paste the JS console logs. What did you set PUBLIC_URL to?

**Comment by Jacky-LinPeng** [comment]
> Please paste the JS console logs. What did you set PUBLIC_URL to?

env.example config 

<img width="790" alt="image" src="https://user-images.githubusercontent.com/15797691/107147134-5c998b00-6987-11eb-9818-cadc0b39630d.png">


error log:

<img width="1164" alt="image" src="https://user-images.githubusercontent.com/15797691/107147098-3542be00-6987-11eb-9f5d-dcbd333bc57c.png">

**Comment by Jacky-LinPeng** [comment]
[Error] WebSocket connection to 'wss://localhost:8443/xmpp-websocket?room=1000' failed: Unexpected response code: 403
[Error] 2021-02-07T13:01:24.778Z – "[JitsiMeetJS.js]" – "UnhandledError: Strophe: Websocket error [object Event]" – "Script: null" – "Line: null" – "Column: null" – "StackTrace: " – "https://192.168.0.106:8443/libs/lib-jitsi-meet.min.js?v=4628:17:16663↵error@https://192.168.0.106:8443/libs/lib-jitsi-meet.min.js?v=4628:1:2…"
	error
	o (lib-jitsi-meet.min.js:10:28653)
	o
	getGlobalOnErrorHandler (lib-jitsi-meet.min.js:17:152552)
	（匿名函数） (app.bundle.min.js:240:847559)
	callErrorHandler (lib-jitsi-meet.min.js:1:100218)
	（匿名函数） (lib-jitsi-meet.min.js:17:16654)
	error (lib-jitsi-meet.min.js:1:23435)
	_onError (lib-jitsi-meet.min.js:1:62911)
	_onError
[Error] 2021-02-07T13:01:24.778Z – "[modules/xmpp/strophe.util.js]" – "Strophe: Websocket error [object Event]"
	error
	o (lib-jitsi-meet.min.js:10:28653)
	o
	（匿名函数） (lib-jitsi-meet.min.js:17:16676)
	error (lib-jitsi-meet.min.js:1:23435)
	_onError (lib-jitsi-meet.min.js:1:62911)
	_onError
[Error] 2021-02-07T13:01:24.779Z – "[connection.js]" – "CONNECTION FAILED:" – "connection.otherError"
	error
	o (app.bundle.min.js:101:14618)
	o
	d (app.bundle.min.js:83:90281)
	（匿名函数） (lib-jitsi-meet.min.js:1:115272)
	connectionHandler (lib-jitsi-meet.min.js:1:139689)
	connectionHandler
	_stropheConnectionCb (lib-jitsi-meet.min.js:1:178670)
	_stropheConnectionCb
	_changeConnectStatus (lib-jitsi-meet.min.js:1:33192)
	_doDisconnect (lib-jitsi-meet.min.js:1:33774)
	_interceptDoDisconnect (lib-jitsi-meet.min.js:25:8028)
	_interceptDoDisconnect
	_disconnect (lib-jitsi-meet.min.js:1:61799)
	_onError (lib-jitsi-meet.min.js:1:63074)
	_onError
[Error] 2021-02-07T13:01:24.786Z – "[features/base/connection]" – "connection.otherError"
	error
	o (app.bundle.min.js:101:14618)
	o
	（匿名函数） (app.bundle.min.js:44:525991)
	promiseReactionJob
