### ISSUE TITLE
PUBLIC_URL doesn't accept external port 443

### ISSUE THREAD

**Issue by normen** [jitsi/docker-jitsi-meet#943]
So it looks like colibri-ws can't be reached when using an external nginx proxy.

```
[Error] WebSocket connection to 'wss://meet.blah.de/colibri-ws/172.28.0.4/5ee3129342726f27/76aae33e?pwd=4fasf5f7ksfas2dv4ksasfsf9' failed: Unexpected response code: 405
``` 

Given the issue #850 I updated my external nginx proxy with this setting:

```
location = /xmpp-websocket {
	proxy_pass http://0.0.0.0:38000/xmpp-websocket;
	proxy_http_version 1.1;
	proxy_set_header Connection "upgrade";
	proxy_set_header Upgrade $http_upgrade;
	tcp_nodelay on;
}
```

I tried to do something similar for colibri but it doesn't seem to work:
```
location ~ ^/colibri-ws/([a-zA-Z0-9-\.]+)/(.*) {
	proxy_pass http://0.0.0.0:38000/colibri-ws/$1/$2$is_args$args;
	proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection "upgrade";
	tcp_nodelay on;
}
```

A thing I noticed is that I tried adding a port to the `PUBLIC_URL` as suggested in the new env file but adding the correct `:443` port results in the xmpp-websocket failing in the web app.

Without a port in the `PUBLIC_URL` the xmpp-websocket works and the meetings work as well but I get constant errors like this as well as bad video quality.

**Comment by saghul** [comment]
> A thing I noticed is that I tried adding a port to the `PUBLIC_URL` as suggested in the new env file but adding the correct `:443` port results in the xmpp-websocket failing in the web app.

That shouldn't matter. Can you provide some logs?



> Without a port in the `PUBLIC_URL` the xmpp-websocket works and the meetings work as well but I get constant errors like this as well as bad video quality.

That looks like the colibri WebSocket has failed. Did you proxy that properly?

**Comment by normen** [comment]
> > A thing I noticed is that I tried adding a port to the `PUBLIC_URL` as suggested in the new env file but adding the correct `:443` port results in the xmpp-websocket failing in the web app.
> 
> That shouldn't matter. Can you provide some logs?
> 

Shouldn't? Did you try? I get the following error in the web app when I use the actual `https://my.comain.com:443` with port in `.env`. As said, the _xmpp_ websocket connection doesn't work in that case. It _does_ work when I leave the port out like `https://my.comain.com`.

My suspicion is that some part of the code tries to be smart and adds the port based on the `https` prefix, thus resulting in multiple ports. I couldn't see any suspicious warnings in the backend log files though..

```
[Info] 2021-02-07T12:12:48.617Z – "[modules/RTC/RTCUtils.js]" – "Got media constraints: " (lib-jitsi-meet.min.js, line 10)
"{\"video\":{\"height\":{\"ideal\":720},\"width\":{\"ideal\":1280},\"deviceId\":\"46276755648EA6898295F4BF8D22AE88D144744C\"},\"audio\":{\"autoGainControl\":true,\"echoCancellation\":true,\"noiseSuppression\":true}}"
[Error] WebSocket connection to 'wss://meet.bitwaves.de/xmpp-websocket?room=friesenschlampen' failed: Unexpected response code: 403
[Error] 2021-02-07T12:12:48.932Z – "[JitsiMeetJS.js]" – "UnhandledError: Strophe: Websocket error [object Event]" – "Script: null" – "Line: null" – "Column: null" – "StackTrace: " (1)
(anonyme Funktion) — strophe.util.js:109error — strophe.umd.js:1392_onError — strophe.umd.js:5730_onError
	error
	o (lib-jitsi-meet.min.js:10:28653)
	o
	getGlobalOnErrorHandler (lib-jitsi-meet.min.js:17:152552)
	(anonyme Funktion) (app.bundle.min.js:240:847559)
	callErrorHandler (lib-jitsi-meet.min.js:1:100218)
	(anonyme Funktion) (lib-jitsi-meet.min.js:17:16654)
	error (lib-jitsi-meet.min.js:1:23435)
	_onError (lib-jitsi-meet.min.js:1:62911)
	_onError
[Error] 2021-02-07T12:12:48.932Z – "[modules/xmpp/strophe.util.js]" – "Strophe: Websocket error [object Event]"
	error
	o (lib-jitsi-meet.min.js:10:28653)
	o
	(anonyme Funktion) (lib-jitsi-meet.min.js:17:16676)
	error (lib-jitsi-meet.min.js:1:23435)
	_onError (lib-jitsi-meet.min.js:1:62911)
	_onError
```

> > Without a port in the `PUBLIC_URL` the xmpp-websocket works and the meetings work as well but I get constant errors like this as well as bad video quality.
> 
> That looks like the colibri WebSocket has failed. Did you proxy that properly?

Yes, thats why I added the code for that in the issue text. Its taken from the web containers nginx and adapted to proxy to that same web container - which in turn should proxy to the actual jvb container(s), right?.

**Comment by saghul** [comment]
Can you check what URL the connection is using in the Network tab in the browser's developer tools?

**Comment by normen** [comment]
I guess it's the one in the log?

**Comment by normen** [comment]
Really looking at the code again, I don't know if the new colibri redirect can work at all?

(from https://github.com/jitsi/docker-jitsi-meet/blob/master/web/rootfs/defaults/meet.conf)
```
location ~ ^/colibri-ws/([a-zA-Z0-9-\.]+)/(.*) {
    proxy_pass http://$1:9090/colibri-ws/$1/$2$is_args$args;
```

doesn't seem to fit the URL thats requested:

```
[Error] WebSocket connection to 'wss://meet.blah.de/colibri-ws/172.28.0.4/5ee3129342726f27/76aae33e?pwd=4fasf5f7ksfas2dv4ksasfsf9' failed: Unexpected response code: 405
```

wouldn't it be 
```
location ~ ^/colibri-ws/([a-zA-Z0-9-\.]+)/(.*)/(.*) {
    proxy_pass http://$1:9090/colibri-ws/$1/$2/$3$is_args$args;
```
?

**Comment by sapkra** [comment]
`(.*)`  Matches 0 or more of any characters except line breaks. So `$2` will already include what you have defined as `/$3` in a separate matching group.

In my setup the colibri-ws proxy works totally fine.

**Comment by normen** [comment]
> `(.*)` Matches 0 or more of any characters except line breaks. So `$2` will already include what you have defined as `/$3` in a separate matching group.
> 
> In my setup the colibri-ws proxy works totally fine.

You did realize this is literally the nginx config from this docker web container?

**Comment by sapkra** [comment]
I'm using kubernetes/openshift and have changed nothing - it just works but I'm still at 5142. I don't think anything about this is different in the new release.

Can you look in your nginx logs - maybe there are some hints? Or you could also try replacing `0.0.0.0` with the IP address or hostname of the web container.

**Comment by normen** [comment]
> I'm using kubernetes/openshift and have changed nothing - it just works but I'm still at 5142. I don't think anything about this is different in the new release.
> 
> Can you look in your nginx logs - maybe there are some hints? Or you could also try replacing `0.0.0.0` with the IP address or hostname of the web container.

5142-1 changed the colibri-websocket proxy:
https://github.com/jitsi/docker-jitsi-meet/commit/b2779263328fb1183b450af77d1e267c8b0c055a

Changing the ip.. idk, why would the xmpp-websocket work with 0.0.0.0 and the colibri one wouldn't? I did in fact copy the docker containers nginx config completely to test, i.e. routing directly from the docker host to the JVB container IP on port 9090, didn't work either:

```
location ~ ^/colibri-ws/([a-zA-Z0-9-\.]+)/(.*) {
    proxy_pass http://$1:9090/colibri-ws/$1/$2$is_args$args;
```

As said, I'd expect the web container to do the final proxying to the jvb container.

**Comment by normen** [comment]
Okay, I found a fix for the colibri-ws issue, I had to do the external nginx redirect like this:
```
location ^~ /colibri-ws {
	proxy_pass http://0.0.0.0:38000/colibri-ws;
	proxy_http_version 1.1;
	proxy_set_header Connection "upgrade";
	proxy_set_header Upgrade $http_upgrade;
	tcp_nodelay on;
}
```

Idk if my nginx is too old and doesn't pick up the regex properly or what but this setup doesn't give me constant errors and I can see the stats during meetings.

That just leaves the titular issue which I admittedly only mentioned because I knew it would gain attention 😅 But its real nonetheless.

**Comment by ahosseinich** [comment]
hi 
i have same problem
and would you share your nginx config?

**Comment by polybos** [comment]
> hi
> i have same problem
> and would you share your nginx config?

I have similar setup - working fine for me (but just small load on jitsi until now):

my nginx reverse-proxy part for the complete jitsi service:
```
    location / {
      proxy_pass http://127.0.0.1:8000/;
      proxy_read_timeout 600s;
    }

    location /http-bind {
      proxy_pass http://127.0.0.1:8000/http-bind;
      proxy_set_header X-Forwarded-For $remote_addr;
      proxy_set_header Host $http_host;
    }

    location /xmpp-websocket {
      proxy_pass http://127.0.0.1:8000/xmpp-websocket;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_set_header Host $host;
      tcp_nodelay on;
    }
    
    location /colibri-ws/ {
      proxy_pass http://127.0.0.1:8000/colibri-ws/;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";
      proxy_set_header Host $host;
      tcp_nodelay on;
    }
```

But I needed some more changes to get the colibri WebSocket (triggered inside docker-compose via ENABLE_XMPP_WEBSOCKET ?) working:
1) inside the docker-compose.yml
Adding `- JICOFO_COMPONENT_SECRET` inside the jicofo part

2) inside .env
Adding `JICOFO_COMPONENT_SECRET` with a new generated secret key (e.g. `openssl rand -hex 16` as it does gen-passwords.sh)

All my jitsi images inside the docker-compose pinned to `stable-5765-1` (e.g. `image: jitsi/web:stable-5765-1`), running on debian-10 without "WebSocket connection to 'wss:...'" errors.

**Comment by skogler** [comment]
@polybos Thanks a lot, your config works perfectly, I was stuck for way too long on this! Probably should be added to the documentation in the section "Running behind a reverse proxy"
