### ISSUE TITLE
Easiest method For Subdirectory Installations -  Apache Reverse Proxy

### ISSUE THREAD

**Issue by outis151** [jitsi/docker-jitsi-meet#944]
This is the easiest method to install jitsi in a subdirectory using an apache reverse proxy with **zero configuration on the jitsi side**. Sharing it here to help other users.

1. Replace domain.com with your domain
2. Enable apache modules `proxy_html` and `substitute`

```
RequestHeader set X-Forwarded-Proto "https"
ProxyPass /meet/ http://127.0.0.1:8000/
ProxyPassReverse /meet/ http://127.0.0.1:8000/

RewriteCond %{HTTP:Connection} Upgrade [NC]
RewriteCond %{HTTP:Upgrade} websocket [NC]
RewriteRule ^/meet/?(.*) "ws://127.0.0.1:8000/$1" [P,L]

<Location /meet/>
    ProxyPassReverse /
    ProxyHTMLEnable On
    ProxyHTMLURLMap  /  /meet/
    RequestHeader    unset  Accept-Encoding
    AddOutputFilterByType SUBSTITUTE text/html
    Substitute "s|wss://domain.com/|wss://domain.com/meet/|n"
</Location>
```

Works without "ENABLE_XMPP_WEBSOCKET=0"
(for now, the devs seem to drastically change stuff with every update so you never know)

**Unfortunately, this is not supported by some client apps such as the Android app** (Opened issues: [#8575](https://github.com/jitsi/jitsi-meet/issues/8575) , [#514](https://github.com/jitsi/jitsi-meet-electron/issues/514) )

**Comment by saghul** [comment]
Yeah, our support for subdirectories is not great, I wouldn't recommend deploying that way.
