### ISSUE TITLE
Traefik routing 

### ISSUE THREAD

**Issue by Nicobai** [jitsi/docker-jitsi-meet#946]
Hello, can you please document the routing for XMPP ? Indeed, since the 5142-2 release, a breaking change was introduced without warning, XMPP websocket doesn't work anymore with Treafik.

**Comment by saghul** [comment]
We did mention the change here: https://github.com/jitsi/docker-jitsi-meet/blob/master/CHANGELOG.md#stable-5142-3

Note that the Traefik samples are community maintained, we don't update them ourselves and rely on the community so do that.

What is not working exactly?

**Comment by bluikko** [comment]
Might this be why updating a traefik Jitsi setup from 5142 to 5390-3 all participants show as muted where the older version worked with the same config?

**Comment by saghul** [comment]
Traefik and other setups are community maintained. Please see https://github.com/jitsi/docker-jitsi-meet/issues/991 if you'd like to help.
