### ISSUE TITLE
Documentation: letsencrypt doc is somehow confusing

### ISSUE THREAD

**Issue by tele-tom** [jitsi/docker-jitsi-meet#950]
Using jitsi/docker-jitsi-meet
stable-5390-3: release

Under
https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#lets-encrypt-configuration

it says:
"In addition, you will need to set HTTP_PORT to 80 and HTTPS_PORT to 443. You might also consider to redirect HTTP traffic to HTTPS by setting ENABLE_HTTP_REDIRECT=1"

I'm using the docker deployment and I didn't set HTTP_PORT to 80 (left 8000) and HTTPS_PORT to 443 (left 8443) and it works nvertheless (what I expected) since the outside ports on the firewall are 80 and 443. I think it would be good to mentioned that it's not about the -env Settings if some network component outside the docker host is involved.

The other thing is:
If I set ENABLE_HTTP_REDIRECT=1 as suggested, letsencrypt fails with error that the site didn't answer the acme challenge on port 80. I guess something is wrong configured in the web container regarding the ACME protocol in case ENABLE_HTTP_REDIRECT=1

Generally spoken either setup should work, with or without redirect to https as long as both ports are served correctly regarding acme.

**Comment by saghul** [comment]
Feel free to make a PR to the handbook!
