### ISSUE TITLE
Just asking: Is it bad to have recurring "org.xmpp.component.ComponentException"?

### ISSUE THREAD

**Issue by AnanasPfirsichSaft** [jitsi/docker-jitsi-meet#953]
I have been using stable-4548 for a while without issues. Recently I found the journal filled up with the following record every few seconds.

jvb_1      | Feb 13, 2021 1:38:26 PM org.jitsi.utils.logging.LoggerImpl log
jvb_1      | SEVERE: java.net.ConnectException: Connection refused (Connection refused), host:localhost, port:5275
jvb_1      | org.xmpp.component.ComponentException: java.net.ConnectException: Connection refused (Connection refused)
jvb_1      |    at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:296)
jvb_1      |    at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:242)
jvb_1      |    at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:222)
jvb_1      |    at org.jitsi.meet.ComponentMain.lambda$getConnectCallable$0(ComponentMain.java:285)
jvb_1      |    at org.jitsi.retry.RetryStrategy$TaskRunner.run(RetryStrategy.java:193)
jvb_1      |    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
jvb_1      |    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
jvb_1      |    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
jvb_1      |    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
jvb_1      |    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
jvb_1      |    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
jvb_1      |    at java.lang.Thread.run(Thread.java:748)
jvb_1      | Caused by: java.net.ConnectException: Connection refused (Connection refused)
jvb_1      |    at java.net.PlainSocketImpl.socketConnect(Native Method)
jvb_1      |    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
jvb_1      |    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
jvb_1      |    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
jvb_1      |    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
jvb_1      |    at java.net.Socket.connect(Socket.java:607)
jvb_1      |    at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:174)
jvb_1      |    ... 11 more

I cannot see it to have side effects. Jitsi Meet still works. Strange is that the port is supposed to be 5347 for jvb to connect to prosody. As far as I know 5275 was/is used by ejabber. Maybe I could have prosody listening on that port, too? ("expose" port in yml, set "component_ports" in prosody and rebuild containers)

Do you thhink I can ignore it and accept the wasted (journal) disk space?

I am reluctant to touch the running system unless I have to :)

**Comment by saghul** [comment]
The latest version no longer uses component connections (it uses a client connection), so you should never run into this issue.
