### ISSUE TITLE
HTTPS_PORT port redirected even if DISABLE_HTTPS=1

### ISSUE THREAD

**Issue by goulov** [jitsi/docker-jitsi-meet#957]
When setting `DISABLE_HTTPS=1`, the docker container `web` still redirects the port assigned in `HTTPS_PORT=1235` to the container. E.g.

```
IMAGE                  COMMAND   CREATED       STATUS      PORTS                                              NAMES
jitsi/web:latest       "/init"   2 weeks ago   Up 3 days   0.0.0.0:1234->80/tcp, 0.0.0.0:1235->443/tcp      docker-jitsi-meet_web_1
```

This means that docker will create the redirection rules in its iptables chains, which means traffic to this port will be handled (like an open port).

By setting `DISABLE_HTTPS=1` the `docker-jitsi-meet_web_1` should only redirect the port for http.

As a workaround, one could block this port in the DOCKER-USER iptables chain, but this means that one would need to mess with iptables besides only using docker-compose.

**Comment by saghul** [comment]
I don't think we can conditionally export a port.
