### ISSUE TITLE
About Token Auth and Env Variables

### ISSUE THREAD

**Issue by serban-mihai** [jitsi/docker-jitsi-meet#96]
I tried again to make JWT Auth working many times without results.

Using the following .env file:
![Screenshot_2019-05-08_14-51-09](https://user-images.githubusercontent.com/34487580/57373307-bc567700-71a0-11e9-80dd-23a4f851208e.png)

We noticed that once the containers are started, the config file (jitsi-meet.cfg.lua) in prosody's container isn't build as it should be:
![Screenshot_2019-05-08_14-40-26](https://user-images.githubusercontent.com/34487580/57372750-3f76cd80-719f-11e9-827d-8f5a02ebcaf7.png)
Standing to the **prosody/rootfs/defaults/conf.d/jitsi-meet.cfg.lua** the **VirtualHost "meet.jitsi"** should have had:
**authentification = "token"** instead of **"internal_plain"**
**app_id** and **app_secret** are missing as well as **allow_empty_token**
**"token_verification"** is missing as well from the **modules_enabled**

This seems to happen due to the lua script that builds the config files, even though the ENABLE_AUTH and JWT_ENABLE_TOKEN_AUTH are both set to eithter 1 or true it seems that the script doesn't get into the token if while building the VirtualHost and the XMPP_MUC_DOMAIN Component

![Screenshot_2019-05-08_14-53-01](https://user-images.githubusercontent.com/34487580/57373521-3dae0980-71a1-11e9-8cf0-67e4447cacd9.png)

(In Yellow is the condition that should be executed, in Red is the condition that is actually executed despite the fact that env variables are recognized correctly from inside the container)

![Screenshot_2019-05-08_14-58-43](https://user-images.githubusercontent.com/34487580/57373792-efe5d100-71a1-11e9-84fe-b4dbe7113c04.png)

(Please don't mind the "true" value instead of "1", it was just a temp test but the result is the same)

Has anyone else faced this problem before?
I think that could be some Lua syntax mistake somewhere because even on GitHub or in my text editor the lua syntax highlighter reports me an unexpected { in the first if condition of the file, but since I never programmed in Lua I can't say that for sure.

What I'm still asking myself is why it works for you and not for me, is there anything else that I'm missing?

_Originally posted by @serban-mihai in https://github.com/jitsi/docker-jitsi-meet/issues/83#issuecomment-490459991_

**Comment by fidelsam1992** [comment]
> First of all, are you sure you are using the dev branch? If so, did you build the containers youself? The ones on DockerHub match master, so JWT is not in yet. You can build all of them by running `make`.
> 
> Then, you need to edit `.env` before ever creating any containers.
> 
> Did you do both of the things above?

I did run "make" on the dev branch

But still the .env settings are not reflecting inside prosody config.

What am I doing wrong here ?

**Comment by Qizot** [comment]
Is this feature already on master branch meaning available via official docker image?

**Comment by saghul** [comment]
Yes, it has been for a while already.
