### ISSUE TITLE
ACME didn't auto-renew SSL certificate after 60 days

### ISSUE THREAD

**Issue by kachar** [jitsi/docker-jitsi-meet#963]
Nothing in `web` container logs about SSL certificates prior intervention
No crontab is installed in `web` container
Running version `jitsi/web:stable-5142-3`

I hope the following investigation and exploration might be useful to someone in the same situation.

---

Once we've found the invalid ssl problem checked the existence of acme cron, but there were no records in `contab -l` for root.

I did try reinstall the cron **manually** and now I've got it listed on `crontab -l`

```
root@7ddb61c100e5:/# sh /opt/acme.sh --home /config/acme.sh --accountemail $LETSENCRYPT_EMAIL --install-cronjob
[Mon Feb 22 07:45:54 UTC 2021] Installing cron job

root@7ddb61c100e5:/# crontab -l
54 0 * * * "/config/acme.sh"/acme.sh --cron --home "/config/acme.sh" > /dev/null
```

Tried to **manually** run the cron process, so it doesn't wait for 54 more days. This process normally should renew the certificate but it skipped the **invalid** certificate

```
root@7ddb61c100e5:/# "/config/acme.sh"/acme.sh --cron --home "/config/acme.sh"
[Mon Feb 22 07:46:25 UTC 2021] ===Starting cron===
[Mon Feb 22 07:46:25 UTC 2021] Renew: 'meet.example.com'
[Mon Feb 22 07:46:25 UTC 2021] Skip invalid cert for: meet.example.com
[Mon Feb 22 07:46:25 UTC 2021] Skipped meet.example.com
[Mon Feb 22 07:46:25 UTC 2021] ===End cron===
```

Running acme renewal **manually** fails as well:

```shell
$ docker-compose exec web bash

sh /opt/acme.sh --home /config/acme.sh --accountemail $LETSENCRYPT_EMAIL --renew-all
```

```
[Mon Feb 22 07:46:42 UTC 2021] Renew: 'meet.example.com'
[Mon Feb 22 07:46:43 UTC 2021] Using CA: https://acme-v02.api.letsencrypt.org/directory
[Mon Feb 22 07:46:43 UTC 2021] Run pre hook:'if [[ -f /var/run/s6/services/nginx ]]; then s6-svc -d /var/run/s6/services/nginx; fi'
/opt/acme.sh: 1: eval: [[: not found
[Mon Feb 22 07:46:43 UTC 2021] Standalone mode.
[Mon Feb 22 07:46:43 UTC 2021] Single domain='meet.example.com'
[Mon Feb 22 07:46:43 UTC 2021] Getting domain auth token for each domain
[Mon Feb 22 07:46:45 UTC 2021] Getting webroot for domain='meet.example.com'
[Mon Feb 22 07:46:45 UTC 2021] Verifying: meet.example.com

[Mon Feb 22 07:46:45 UTC 2021] Standalone mode server
2021/02/22 07:46:45 socat[2217] E bind(5, {AF=2 0.0.0.0:80}, 16): Address already in use

[Mon Feb 22 07:46:49 UTC 2021] meet.example.com:Verify error:Invalid response from https://meet.example.com/.well-known/acme-challenge/sZk8X2BFolMDD4NzB0DxSEm3N4nXQk8qsAxX3MdxcIM [36.153.163.224]: 
/opt/acme.sh: 2344: kill: No such process

[Mon Feb 22 07:46:49 UTC 2021] Please add '--debug' or '--log' to check more details.
[Mon Feb 22 07:46:49 UTC 2021] See: https://github.com/acmesh-official/acme.sh/wiki/How-to-debug-acme.sh
[Mon Feb 22 07:46:49 UTC 2021] Run post hook:'if [[ -f /var/run/s6/services/nginx ]]; then s6-svc -u /var/run/s6/services/nginx; fi'
/opt/acme.sh: 1: eval: [[: not found
[Mon Feb 22 07:46:50 UTC 2021] Error renew meet.example.com.
```

(My domain has been replaced with `example.com` for the sake of the example)

---

I had to manually stop `nginx` via `s6-svc -d /var/run/s6/services/nginx` and renew using the command above with the following error in the logs regarding the `pre-hook`

```
[Mon Feb 22 08:03:32 UTC 2021] Run pre hook:'if [[ -f /var/run/s6/services/nginx ]]; then s6-svc -d /var/run/s6/services/nginx; fi'
/opt/acme.sh: 1: eval: [[: not found
```

---

**Manual renewal and installation of the certificate (all steps):**

```shell
sh /opt/acme.sh \
--home /config/acme.sh \
--accountemail $LETSENCRYPT_EMAIL \
--standalone \
--pre-hook "s6-svc -d /var/run/s6/services/nginx" \
--post-hook "s6-svc -u /var/run/s6/services/nginx" \
--renew-all

sh /opt/acme.sh \
  --home /config/acme.sh \
  --accountemail $LETSENCRYPT_EMAIL \
  --install-cert -d $LETSENCRYPT_DOMAIN \
  --key-file /config/acme-certs/$LETSENCRYPT_DOMAIN/key.pem  \
  --fullchain-file /config/acme-certs/$LETSENCRYPT_DOMAIN/fullchain.pem
```
---

Once I've renewed the certificate I did a `docker-compose down && docker-compose up -d` to ensure the new certificate is loaded normally and checked for the existence of the crontab in the `web` container, but I **wasn't able to find any**, even though I did install it manually.  So this might be one of the core issues.

```
root@4b76c8ab35f4:/# crontab -l
no crontab for root
```

**Comment by saghul** [comment]
Thanks for the report! I'll take a look.

**Comment by saghul** [comment]
> There doesn't seem to be any negative effect from repeatedly running `sh ./acme.sh --install --home /config/acme.sh --accountemail $LETSENCRYPT_EMAIL` and it does not duplicate the cronjob. One possible fix would be to remove the check for an existing acme.sh installation and let it always run on startup. This would have the effect of also automatically upgrading the installed version of acme.sh whenever the pinned version in the Dockerfile is updated. If that sounds reasonable then I can make the PR for the change.

That sounds reasonable, can you make a PR please? Thanks for looking into it!

**Comment by kevinconway** [comment]
PR up: https://github.com/jitsi/docker-jitsi-meet/pull/978
