### ISSUE TITLE
[Question] Auth support with GSuite

### ISSUE THREAD

**Issue by gsi-nestor** [jitsi/docker-jitsi-meet#976]
Hi,

We are moving to Jitsi from some propietary solution, and we are trying to integrate the authentication with GSuite so our users could benefit from single login. Please, could you point us in the right direction? We are a software shop so we can help with implementation/modifications if needed.

Thanks in advance,

Nestor

**Comment by sapkra** [comment]
To realize this you currently need an own authentication server which handles the login and exchanges your Google Auth Token with an JWT token for jitsi and redirects you to the room with the JWT token attached to the URL GET parameters.
