### ISSUE TITLE
Can’t establish a connection to the server at wss://<public_ip>:8000/xmpp-websocket?room=test2.

### ISSUE THREAD

**Issue by petrbel** [jitsi/docker-jitsi-meet#977]
Hi, I'm trying to run a simple instance of jitsi on my VPS. So far, no https is required (will handle later by nginx a let's encrypt manually as I have multiple services/domains/... running on my VPS).

These issues may be related to my problem. I hope I provide more detail for a quick fix :)
- #975
- #850

First of all, I make sure that the required ports are open. I manually stop nginx and then tried to run multiple containers bound to ports 80, 443, 4443, 10000. All of them are accessible and well running. I stop all the containers so that the ports are released.

Secondly, I double check the firewall via `sudo iptables -L -v -n` verifying that `Chain INPUT (policy ACCEPT...` and nothing suspicious proceeds.

Additionaly I make sure that neither `~/.jitsi-meet-cfg` nor `~/docker-jitsi-meet` exists.

Then, I follow the [tutorial](https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker). So I clone the repo and cd into it. For more reproducibility, I checkout the last stable tag `stable-5390-3` (however master behaves the same). I copy the `env.example` to `.env` and generate passwords for it. 

Then I edit `.env` as following (note that `<public_ip>` is in form of `10.20.30.40` and depresent the public IP address of the VPS):
```
PUBLIC_URL=http://<public_ip>:8000   # 8000 is the default unchaned port setting
DOCKER_HOST_ADDRESS=<public_ip>
```

As of `DOCKER_HOST_ADDRESS` I also tried leaving it commented, using http:// prefix, specifying the protocol, ...

Finally, I start everything by `docker-compose up` intentionally not in the detached mode so that I can easily see that all containers are up and running (which I wait for).

As of the fun part, I open firefox (google chrome behaves the same) and open `http://<public_ip>:8000`. I see jitsi welcome page correctly. I open the developer tools and create a room `test2`. Once redirected to the room, I get `You have been disconected. You may want to check your network connection`. The developer console displays some errors such as 
```Firefox can’t establish a connection to the server at wss://http//<public_ip>:8000/xmpp-websocket?room=test2.```

I was worried about the weird URL having both `wss://` and `http://`. Editing `PUBLIC_URL` removes that but the problem remains.

There are some other errors such as
```
[modules/xmpp/strophe.util.js] <t.a/r.Strophe.log>:  Strophe: Websocket error [object Event]
[connection.js] CONNECTION FAILED: connection.otherError
[features/base/connection] <h/</</<>:  connection.otherError
[features/base/tracks] <u/</<>:  Failed to create local tracks Array [ "audio" ] TypeError: navigator.mediaDevices is undefined
```

Unfortunatelly I am no FE developer and actually can't parse the error well. I will happily provide more information if you would kindly point me to the right direction. Sorry for probably a noob question but I really can't get it running for 3 evening straight.

Thanks!

Also tagging @nechciGitHub, a probably interested friend of mine :)

**Comment by damencho** [comment]
wss is a secure websocket connection.


http will not work with webrtc, https is a requirement for webrtc to work in the browsers. That's why you see `navigator.mediaDevices is undefined`

**Comment by petrbel** [comment]
@damencho oh, I haven't thought of that at all! Thank you very much.

I managed to set up the nginx server so that it correctly passes all connections to the container. For my fellows guys struggling with this I attach a [link to the deprecated wiki](https://github.com/jitsi/jitsi-meet/wiki/nginx-SSL-example) that helped me set everything up.

**Comment by uvwild** [comment]
Unfortunately that link is just pointing to more  diluted information.
Referencing ~100 lines of config which somehow helped to solve the issue does not help others to understand what needs to be done!
Its probably just 1 or 2 lines which is needed.

This is the ongoing issue with jitsi....
Almost nobody actually understand what they fixed to make things work.
A long list of try and error and suddenly it works. Once it works nobody bothers.

I am banging my head on this for months now. with a particular complex setup.

**Comment by petrbel** [comment]
> Unfortunately that link is just pointing to more diluted information. 
>Referencing ~100 lines of config which somehow helped to solve the issue does not help others to understand what needs to be done!

@uvwild lol you're completely right. I'll try to elaborate more with a hope of potential help to others :)

> This is the ongoing issue with jitsi....
> Almost nobody actually understand what they fixed to make things work.
> A long list of try and error and suddenly it works. Once it works nobody bothers.

My thougts exactly. Anyway, I think it would be very nice to have a simple step-by-step tutorial of setting up jitsi on a public-ip vps within a docker (and nginx). I believe that people who would like a really self-hosted private calls are the ones who just have a bunch of vps laying around and could simple run a simple command to do that. Instead, there is a bunch of tutorials of running jitsi behind NAT etc which is cool but in my opinion niche :) I'd be more than happy to write such tutorial once somebody verifies my config. 

Note that I just tried to get things going as fast as possible in order to check whether my tiny vps can even handle jitsi. I'm definitely no expert and I would discourage anyone from replicating my configuration. Especially my fellow @nechciGithub!!!

### `.env`
I set the following. I believe these are the crucial things.
```
HTTP_PORT=5010
HTTPS_PORT=5011
PUBLIC_URL=https://meet.example.org  # NOTE: use your actual domain :)
DOCKER_HOST_ADDRESS=meet.example.org
DISABLE_HTTPS=1  # NOTE: I want to use only HTTP between the container and nginx, potentially a huge security risk
ENABLE_HSTS=1
```

### Let's encrypt
I generate the LE SSL certificate for my (sub)domain `meet.example.org`

### Nginx
I add new `server` section to `/etc/nginx/nginx.conf` (where I already have multiple other subdomains configured...). I hoped that a simple entry would suffice, however, I had to manually configured also `wss` forwarding etc. Basically a copy-paste from the mentioned [deprecated wiki page](https://github.com/jitsi/jitsi-meet/wiki/nginx-SSL-example).
```
    # meet.example.org
    server {
        listen 80;
        server_name meet.example.org;
        rewrite ^ https://$http_host$request_uri? permanent;
    }
    
    server {
        listen 443 ssl http2;
        server_name meet.example.org;

        # global SSL options with Perfect Forward Secrecy (PFS) high strength ciphers
        # first. PFS ciphers are those which start with ECDHE which means (EC)DHE
        # which stands for (Elliptic Curve) Diffie-Hellman Ephemeral.
        ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_session_timeout 1d;
        ssl_session_cache shared:MozSSL:10m;  # about 40000 sessions
        resolver 8.8.8.8;
        ssl_stapling on;
        ssl_stapling_verify on;

        # this are optional but recommended Security Headers
        # thats the HSTS Header - it will enforce that all connections regarding this host and the subdomains will only used with encryption
        add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;
        # this tells the browser that when click on links in the chat / pad, the referrer is only set when the link points to hosts site and encrypted
        add_header Referrer-Policy strict-origin;
        # this tells the browser that jitsi can't be embedded in a Frame
        add_header X-Frame-Options "DENY";
        add_header X-Content-Type-Options nosniff;
        add_header X-XSS-Protection "1; mode=block";
        add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; img-src 'self'; style-src 'self' 'unsafe-inline'; font-src 'self'; object-src 'none'; base-uri 'none'; frame-ancestors 'none'; form-action 'none'; block-all-mixed-content";
        # List of Browser-Features which are allowed / denied for this Site
        add_header Feature-Policy "geolocation 'none'; camera 'self'; microphone 'self'; speaker 'self'; autoplay 'none'; battery 'none'; accelerometer 'none'; autoplay 'none'; payment 'none';";

	# Web meet
        location / {
            proxy_pass http://localhost:5010;
            proxy_read_timeout 600s;
        }

        # BOSH
        location /http-bind {
            proxy_pass http://localhost:5010/http-bind;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Host $http_host;
        }

        # xmpp websockets
        location /xmpp-websocket {
            proxy_pass http://localhost:5010;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            tcp_nodelay on;
        }

        ssl_certificate /etc/letsencrypt/live/meet.example.org/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/meet.example.org/privkey.pem; # managed by Certbot
    }
```
