### ISSUE TITLE
New Issue  causing video stream to fail in Chrome only - TypeError: Cannot read property 'postis'of null

### ISSUE THREAD

**Issue by uvwild** [jitsi/docker-jitsi-meet#984]
I find this one now since 2 days. 
This is a new error I have not seen in the last months.
_from commit c4fc3d37c629096a08540989d930cfef5cdecb56_
Leading up to the error:
 `ServiceWorkerRegistration`
` Device list updated:`
` P2P STUN servers:  stun:meet-jit-si-turnrelay.jitsi.net:443`
` Strophe connecting:`
```
2021-03-11T22:59:08.752Z [modules/RTC/RTCUtils.js] <X.newObtainAudioAndVideoPermissions>:  Using the new gUM flow
22:59:08.753 Logger.js:154 2021-03-11T22:59:08.753Z [modules/RTC/RTCUtils.js] <X.<anonymous>>:  Got media constraints:  {"video":{"height":{"ideal":720,"max":720,"min":180},"width":{"ideal":1280,"max":1280,"min":320},"facingMode":"user"},"audio":{"optional":[{},{"echoCancellation":true},{"googEchoCancellation":true},{"googAutoGainControl":true},{"googNoiseSuppression":true},{"googHighpassFilter":true},{"googNoiseSuppression2":true},{"googEchoCancellation2":true},{"googAutoGainControl2":true}]}}
```
```
Logger.js:154 2021-03-11T22:59:10.221Z [JitsiMeetJS.js] <Object.getGlobalOnErrorHandler>:  UnhandledError: Uncaught TypeError: Cannot read property 'postis' of null Script: https://jitsid.otcdemo.gardener.t-systems.net/libs/app.bundle.min.js?v=4628 Line: 155 Column: 33665 StackTrace:  TypeError: Cannot read property 'postis' of null
    at u (https://xxx.xxx.xxx/libs/app.bundle.min.js?v=4628:155:33665)
```
There are no error in the docker logs of the servers.

Any ideas? I am a bit stuck here with such an error message.

here is the stack trace:|

```
@ | Logger.js:154
-- | --
  | getGlobalOnErrorHandler | @ | JitsiMeetJS.js:613
  | window.onerror | @ | middleware.js:110
  | error (async) |   |  
  | (anonymous) | @ | middleware.js:106
  | (anonymous) | @ | middleware.js:31
  | (anonymous) | @ | middleware.js:28
  | (anonymous) | @ | middleware.js:12
  | (anonymous) | @ | middleware.js:39
  | (anonymous) | @ | middleware.js:31
  | (anonymous) | @ | middleware.web.js:22
  | (anonymous) | @ | middleware.any.js:100
  | (anonymous) | @ | middleware.js:106
  | (anonymous) | @ | middleware.js:19
  | (anonymous) | @ | middleware.js:29
  | (anonymous) | @ | middleware.js:91
  | (anonymous) | @ | middleware.js:101
  | (anonymous) | @ | middleware.js:24
  | (anonymous) | @ | middleware.js:20
  | (anonymous) | @ | middleware.js:15
  | (anonymous) | @ | middleware.js:23
  | (anonymous) | @ | middleware.js:20
  | (anonymous) | @ | middleware.js:25
  | (anonymous) | @ | middleware.js:74
  | (anonymous) | @ | middleware.js:40
  | (anonymous) | @ | middleware.js:158
  | dispatch | @ | redux.js:636
  | (anonymous) | @ | actions.js:50
  | (anonymous) | @ | index.js:11
  | (anonymous) | @ | middleware.js:29
  | (anonymous) | @ | middleware.js:32
  | Promise.then (async) |   |  
  | componentDidMount | @ | AbstractApp.js:44
  | js | @ | react-dom.production.min.js:238
  | t.unstable_runWithPriority | @ | scheduler.production.min.js:20
  | pa | @ | react-dom.production.min.js:113
  | Es | @ | react-dom.production.min.js:230
  | ds | @ | react-dom.production.min.js:204
  | Vs | @ | react-dom.production.min.js:263
  | Ws | @ | react-dom.production.min.js:263
  | (anonymous) | @ | react-dom.production.min.js:272
  | ys | @ | react-dom.production.min.js:208
  | el | @ | react-dom.production.min.js:272
  | render | @ | react-dom.production.min.js:273
  | Rs.renderEntryPoint | @ | index.web.js:71
```

**Comment by damencho** [comment]
I have seen this when using bitwarden extension in chrome.

**Comment by paweldomas** [comment]
This is happening on Chrome 89 and the crash is caused by this call:

https://github.com/jitsi/lib-jitsi-meet/blob/master/modules/browser/BrowserCapabilities.js#L297

Crashes here:

https://github.com/jitsi/js-utils/blob/47c940752014489e28937cae3fd9d54f73fd4083/transport/postis.js#L51

**Comment by paweldomas** [comment]
Btw. the postist crash I think is harmless and probably unrelated to any video issues mentioned here.

**Comment by uvwild** [comment]
Thanks for pointing that out. It was a very misleading track.
My docker setup works now with more clients. 

In the virtualbox I had to update to 6.1.18 to resolve the firefox video not working.
There was a known issue with the VMSVGA driver. It just stopped working at some point. the update resolved it.

In chrome i had to disable all  extensions regarding webrtc.

1. https://chrome.google.com/webstore/detail/webrtc-network-limiter/npeicpdbkakmehahjeeohfdhnlpdklia 
2. https://mybrowseraddon.com/webrtc-control.html

They created the illusion of being able to control the webrtc behavior by being able to control the choice of the right endpoints. 

However, they had to be **both off AND the session restarted from scratch** to make it happen. 
They came into play a while ago when no video was working at all. 

`Finally, I have a working setup which I can evolve without chasing errors.`

**Comment by saghul** [comment]
I made https://github.com/jitsi/js-utils/pull/46 to get rid of the postis error which is indeed misleading.

**Comment by uvwild** [comment]
Thanks for the fix!
For me working on the k8s integration, the loadbalancer config and the handling of the websockets are a major challenge.
Being able to verify those connections outside the complex webrtc connection handling would be very helpful for many I would think.... identifying the broken element of the complex interaction is the hard part and the nodejs wscat tool is only partually helpful.
