### ISSUE TITLE
Jitsi on docker get stuck :(

### ISSUE THREAD

**Issue by MichalSzopinski00** [jitsi/docker-jitsi-meet#985]
My problem is that jitsi doesn't work on my set up I can't turn my mic,camera on even invite someone, Its just get stuck.
I set up my envoirment on azure. I had created VM(ubuntu 18.04 LTS) with docker and set up jitsi with following quick setup guide:
https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker

(jvb logs as  second screenshot)

I will be gratefull for any helpful comment.

![Screenshot_2](https://user-images.githubusercontent.com/49531926/111313687-edd3df80-8660-11eb-9c28-7e545ccfb241.png)
![Screenshot_3](https://user-images.githubusercontent.com/49531926/111314468-bc0f4880-8661-11eb-94d6-e957adef597f.png)

**Comment by saghul** [comment]
What do you see in the browser JS console?

**Comment by MichalSzopinski00** [comment]
![Uploading Screenshot_1.png…]()

**Comment by MichalSzopinski00** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/49531926/111315380-9c2c5480-8662-11eb-9b5e-4c2ab7050974.png)

**Comment by MichalSzopinski00** [comment]
feel free to check it 
https://homeplusslawomirwilowski.tk/

**Comment by saghul** [comment]
The configuration is incorrect. All domain options say 127.0.0.1, which means my browser will try to connect there, obviously failing. If you are using Docker there is no need to change from the default "meet.jitsi". Just set PUBLIC_URL to the right value.

**Comment by MichalSzopinski00** [comment]
this is my .env config 
![Screenshot_4](https://user-images.githubusercontent.com/49531926/111317855-d139a680-8664-11eb-846e-562a82789352.png)

**Comment by saghul** [comment]
Did you change XMPP_DOMAIN ?

**Comment by MichalSzopinski00** [comment]
I think I leave as it is
![Screenshot_5](https://user-images.githubusercontent.com/49531926/111318217-22499a80-8665-11eb-936f-382532850517.png)

**Comment by saghul** [comment]
This doesn't look like the config.js the Docker setup generates: https://github.com/jitsi/jitsi-meet/pull/8810

**Comment by MichalSzopinski00** [comment]
I had sent you the part of my .env file.
So where should I change value from localhost to my VM ?

**Comment by saghul** [comment]
If you are using Docker the file is generated automatically. What exact steps did you use to deploy it?

**Comment by MichalSzopinski00** [comment]
just after pure installation without editing anything i just run it by 
docker-compose up -d

**Comment by MichalSzopinski00** [comment]
When I saw error I made changes and reboot system.starting, downing containers do nothing the errors remain :(

**Comment by MichalSzopinski00** [comment]
I followed https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker
and made first 5 steps and run it

**Comment by saghul** [comment]
It's not possible to do that and end up with the config file your deployment has. Are you sure you never attempted the non-Docker quick install?

**Comment by MichalSzopinski00** [comment]
yes I'm sure. To be honest I will set up my VM from scratches and try again from quick step guide. I will notify you if I will face with the same problem. and  describe step by step what I have done.
thanks for help. :)
I appreciate it.
have a great day

**Comment by saghul** [comment]
No worries, hope it works for you!
