### ISSUE TITLE
Deploying Jitsi Web Docker Container On CentOS7 Failed

### ISSUE THREAD

**Issue by cashcat** [jitsi/docker-jitsi-meet#987]
follow this step,  https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker
Deploying Jitsi Web Docker Container On CentOS7 Failed，it continuse reconnect...

![image](https://user-images.githubusercontent.com/7604008/111663812-21bf2880-884c-11eb-9d1f-9bb835c4d32b.png)

**Comment by saghul** [comment]
Please paste the JS console logs.

**Comment by magicdrums** [comment]
Same issue here...

**Comment by magicdrums** [comment]
Here my log web

> web_1      | 10.69.120.10 - - [29/Mar/2021:17:22:36 -0300] "GET /12edqwd HTTP/1.1" 200 50222 "https://meet.mydomain.com/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
> web_1      | 10.69.120.10 - - [29/Mar/2021:17:22:36 -0300] "GET /libs/do_external_connect.min.js?v=1 HTTP/1.1" 200 2415 "https://meet.mydomain.com/12edqwd" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
> web_1      | 10.69.120.10 - - [29/Mar/2021:17:22:36 -0300] "GET /libs/lib-jitsi-meet.min.js?v=4628 HTTP/1.1" 200 702537 "https://meet.mydomain.com/12edqwd" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
> web_1      | 10.69.120.10 - - [29/Mar/2021:17:22:36 -0300] "GET /libs/app.bundle.min.js?v=4628 HTTP/1.1" 200 3901182 "https://meet.mydomain.com/12edqwd" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
> web_1      | 2021/03/29 17:22:38 [error] 262#262: *18 open() "/usr/share/jitsi-meet/images/avatar.png" failed (2: No such file or directory), client: 10.69.120.10, server: _, request: "GET /images/avatar.png HTTP/1.1", host: "meet.mydomain.com", referrer: "https://meet.mydomain.com/12edqwd"
> web_1      | 10.69.120.10 - - [29/Mar/2021:17:22:38 -0300] "GET /images/avatar.png HTTP/1.1" 404 1026 "https://meet.mydomain.com/12edqwd" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
> jvb_1      | Mar 29, 2021 5:22:38 PM org.jitsi.utils.logging2.LoggerImpl log
> jvb_1      | INFO: Performed a successful health check in PT0S. Sticky failure: false
> web_1      | 2021/03/29 17:22:38 [error] 262#262: *19 open() "/usr/share/jitsi-meet/images/favicon.ico" failed (2: No such file or directory), client: 10.69.120.10, server: _, request: "GET /images/favicon.ico?v=1 HTTP/1.1", host: "meet.mydomain.com", referrer: "https://meet.mydomain.com/12edqwd"
> web_1      | 10.69.120.10 - - [29/Mar/2021:17:22:38 -0300] "GET /images/favicon.ico?v=1 HTTP/1.1" 404 1026 "https://meet.mydomain.com/12edqwd" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
> web_1      | 10.69.120.10 - - [29/Mar/2021:17:22:38 -0300] "GET /xmpp-websocket?room=12edqwd HTTP/1.1" 403 413 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
> web_1      | 2021/03/29 17:22:39 [error] 262#262: *22 open() "/usr/share/jitsi-meet/images/favicon.ico" failed (2: No such file or directory), client: 10.69.120.10, server: _, request: "GET /images/favicon.ico?v=1 HTTP/1.1", host: "meet.mydomain.com", referrer: "https://meet.mydomain.com/12edqwd"
> web_1      | 10.69.120.10 - - [29/Mar/2021:17:22:39 -0300] "GET /images/favicon.ico?v=1 HTTP/1.1" 404 1026 "https://meet.mydomain.com/12edqwd" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
> web_1      | 10.69.120.10 - - [29/Mar/2021:17:22:40 -0300] "GET /pwa-worker.js HTTP/1.1" 200 3370 "https://meet.mydomain.com/pwa-worker.js" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
> jvb_1      | Mar 29, 2021 5:22:48 PM org.jitsi.utils.logging2.LoggerImpl log
> jvb_1      | INFO: Performed a successful health check in PT0S. Sticky failure: false
> jvb_1      | Mar 29, 2021 5:22:58 PM org.jitsi.utils.logging2.LoggerImpl log
> jvb_1      | INFO: Performed a successful health check in PT0S. Sticky failure: false
> web_1      | 10.69.120.10 - - [29/Mar/2021:17:23:05 -0300] "GET /12edqwd HTTP/1.1" 200 50222 "https://meet.mydomain.com/12edqwd" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
> web_1      | 10.69.120.10 - - [29/Mar/2021:17:23:05 -0300] "GET /libs/do_external_connect.min.js?v=1 HTTP/1.1" 200 2415 "https://meet.mydomain.com/12edqwd" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
> web_1      | 10.69.120.10 - - [29/Mar/2021:17:23:05 -0300] "GET /libs/lib-jitsi-meet.min.js?v=4628 HTTP/1.1" 200 702545 "https://meet.mydomain.com/12edqwd" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
> web_1      | 10.69.120.10 - - [29/Mar/2021:17:23:06 -0300] "GET /libs/app.bundle.min.js?v=4628 HTTP/1.1" 200 3901189 "https://meet.mydomain.com/12edqwd" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
> web_1      | 2021/03/29 17:23:07 [error] 262#262: *28 open() "/usr/share/jitsi-meet/images/avatar.png" failed (2: No such file or directory), client: 10.69.120.10, server: _, request: "GET /images/avatar.png HTTP/1.1", host: "meet.mydomain.com", referrer: "https://meet.mydomain.com/12edqwd"
> web_1      | 10.69.120.10 - - [29/Mar/2021:17:23:07 -0300] "GET /images/avatar.png HTTP/1.1" 404 1026 "https://meet.mydomain.com/12edqwd" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
> web_1      | 2021/03/29 17:23:07 [error] 262#262: *29 open() "/usr/share/jitsi-meet/images/favicon.ico" failed (2: No such file or directory), client: 10.69.120.10, server: _, request: "GET /images/favicon.ico?v=1 HTTP/1.1", host: "meet.mydomain.com", referrer: "https://meet.mydomain.com/12edqwd"
> web_1      | 10.69.120.10 - - [29/Mar/2021:17:23:07 -0300] "GET /images/favicon.ico?v=1 HTTP/1.1" 404 1026 "https://meet.mydomain.com/12edqwd" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
> web_1      | 10.69.120.10 - - [29/Mar/2021:17:23:07 -0300] "GET /xmpp-websocket?room=12edqwd HTTP/1.1" 403 413 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
> jvb_1      | Mar 29, 2021 5:23:08 PM org.jitsi.utils.logging2.LoggerImpl log
> jvb_1      | INFO: Performed a successful health check in PT0S. Sticky failure: false
> web_1      | 2021/03/29 17:23:08 [error] 262#262: *32 open() "/usr/share/jitsi-meet/images/favicon.ico" failed (2: No such file or directory), client: 10.69.120.10, server: _, request: "GET /images/favicon.ico?v=1 HTTP/1.1", host: "meet.mydomain.com", referrer: "https://meet.mydomain.com/12edqwd"
> web_1      | 10.69.120.10 - - [29/Mar/2021:17:23:08 -0300] "GET /images/favicon.ico?v=1 HTTP/1.1" 404 1026 "https://meet.mydomain.com/12edqwd" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
> web_1      | 10.69.120.10 - - [29/Mar/2021:17:23:09 -0300] "GET /pwa-worker.js HTTP/1.1" 200 3370 "https://meet.mydomain.com/pwa-worker.js" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
> jvb_1      | Mar 29, 2021 5:23:17 PM org.jitsi.utils.logging2.LoggerImpl log
> jvb_1      | INFO: Running expire()
> jvb_1      | Mar 29, 2021 5:23:18 PM org.jitsi.utils.logging2.LoggerImpl log
> jvb_1      | INFO: Performed a successful health check in PT0S. Sticky failure: false

**Comment by saghul** [comment]
Check the browser console logs please.

**Comment by magicdrums** [comment]
> Check the browser console logs please.

This is console Log from Browser
![Selection_999(128)](https://user-images.githubusercontent.com/402996/113069056-ed296600-9195-11eb-91cd-4a263d839a78.png)

**Comment by saghul** [comment]
Is your setup running behind a reverse proxy?

**Comment by LithiumSR** [comment]
Same problem here. The problem is there even when jitsi is not behind a reverse proxy

**Comment by LithiumSR** [comment]
In order to fix the issue in my nginx reverse proxy I rewrote the proxy conf as follow:
`server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name meet.*;

    include /config/nginx/ssl.conf;

    client_max_body_size 0;

    # enable for ldap auth, fill in ldap details in ldap.conf
    #include /config/nginx/ldap.conf;

    # enable for Authelia
    #include /config/nginx/authelia-server.conf;

    location / {
    # enable the next two lines for http auth
    #auth_basic "Restricted";
    #auth_basic_user_file /config/nginx/.htpasswd;

    # enable the next two lines for ldap auth, also customize and enable ldap.conf in the default conf
    #auth_request /auth;
    #error_page 401 =200 /ldaplogin;

    # enable for Authelia
    #include /config/nginx/authelia-location.conf;
        include /config/nginx/proxy.conf;
        resolver 127.0.0.11 valid=30s;
        set $upstream_app  jitsi-meet_web;
        set $upstream_port 80;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port;
        proxy_set_header X-Scheme $scheme;
    }

    location /xmpp-websocket {
        resolver 127.0.0.11 valid=30s;
        set $upstream_app  jitsi-meet_web;
        set $upstream_port 80;
        set $upstream_proto http;
        proxy_pass $upstream_proto://$upstream_app:$upstream_port/xmpp-websocket;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        tcp_nodelay on;
   }
}`

Hope it helps someone that is my same situation

**Comment by magicdrums** [comment]
> Is your setup running behind a reverse proxy?

Yes but previous version work's fine... this configuration reverse proxy not changed

**Comment by LithiumSR** [comment]
Did you changed the public URL in .env? If yes, did you also nuked the configuration after making that change?

**Comment by magicdrums** [comment]
SOLVED with solution issue #992

**Comment by LithiumSR** [comment]
@magicdrums By disabling the xmpp websocket you just reverted the behaviour of jitsi to be like the old release. It is more like a temporary workaround than a fix

**Comment by magicdrums** [comment]
> @magicdrums Al deshabilitar el xmpp websocket, acaba de revertir el comportamiento de jitsi para que sea como la versión anterior. Es más una solución temporal que una solución

Totally agree, in fact now it works slow, but it works which is what I wanted since I use it in production and my clients were already desperate

**Comment by saghul** [comment]
Updated docs on reverse proxies and disablign websocket as a last resort measure: https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-docker#running-behind-a-reverse-proxy
