### ISSUE TITLE
Layer Suspension

### ISSUE THREAD

**Issue by noahmanthey** [jitsi/docker-jitsi-meet#988]
Hi,

i would like to enable Layer Suspension. I tryed to edit docker-compose.yml and the web/rootfs/defaults/settings-config.js but it didnt work. 

I added ENABLE_LAYER_SUSPENSION as  a envoirmental variable and  as is run docker-compose the web container was recreated.
But Layer suspension was not enabled.

What can i do?

**Comment by noahmanthey** [comment]
[env.txt](https://github.com/jitsi/docker-jitsi-meet/files/6172124/env.txt)
[docker-compose.txt](https://github.com/jitsi/docker-jitsi-meet/files/6172126/docker-compose.txt)
[settings-config.txt](https://github.com/jitsi/docker-jitsi-meet/files/6172127/settings-config.txt)

**Comment by prayagsingh** [comment]
try **`{{ $ENABLE_LAYER_SUSPENSION := .Env.ENABLE_LAYER_SUSPENSION | default "true" | toBool  -}}`** in `settings-config.js`

**Comment by noahmanthey** [comment]
i tried that but it still doesnt work 😥 the problem is that the file settings-config.js in the cointainer doesnt even contain my changes

**Comment by noahmanthey** [comment]
[settings-config.txt](https://github.com/jitsi/docker-jitsi-meet/files/6176338/settings-config.txt)

**Comment by saghul** [comment]
Have you rebuilt the image?

**Comment by noahmanthey** [comment]
i stopped all container

`docker system prune -a`

and run again:

`docker-compose up -d'

its still not working and its not showing up in  settings-config.txt within the cointainer.

**Comment by prayagsingh** [comment]
@noahmanthey What @saghul said that is you have build your own docker images. Right now you might be using `jitsi/web:tag` image in `docker-compose.yaml` under `web` service. If you are making any changes to any of the file then you have to build your own docker images like `noahmanthey/web:latest`. Please follow below steps:

1. Clone `docker-jitsi-meet`.
2. Go to `docker-jitsi-meet/web` directory
3. Add your changes to `/rootfs/defaults/setting-config.js` file. 
4. Now execute command `docker image build -t noahmanthey/web:latest . ` from `web` directory. Here I'm assuming that `noahmanthey` is the user name that you are using for `dockerhub`.  dockerhub is required in case you want to push/pull your image when running it on the cloud.
5. Now replace `jitsi/web:tag` image by `noahmanthey/web:latest` in `docker-compose.yaml` file. 

**OR**

You can follow this [thread](https://community.jitsi.org/t/mute-video-for-remote-user/58695/28?u=metadata) from the community if you want to build from unstable.

**Comment by noahmanthey** [comment]
ok it the new settings-config.js shows up. I will test it in a couple of days but i think im good for now. 

Thank you so much.
