### ISSUE TITLE
Kubernetes example is broken on updated version of Jitsi

### ISSUE THREAD

**Issue by marner2** [jitsi/docker-jitsi-meet#989]
A few things seem to be missing with the Kubernetes example, especially since the recent jitsi upgrade that turns on websockets by default (and doesn't seem to be able to turn them off).

As it stands, if I try to run the kubernetes scripts, I end up running into the problem where the websockets are trying to connect to "wss://localhost:8443." This is fixed by adding `PUBLIC_URL` to the web environment. However, even with that fix, something is still wrong with the forwarding because I'm getting errors connecting to those sockets (this seems to be the problem with #952 )

Can we either get the kubernetes example to use a compatible version of the docker containers or get it updated to actually have the right environment variables for the latest defaults from the jitsi docker containers? Thanks.

**Comment by saghul** [comment]
As mentioned in https://github.com/jitsi/docker-jitsi-meet/blob/master/examples/README.md the k8s setup is community maintained. PRs are welcome.

**Comment by rsoika** [comment]
I still did not manage to get it running on kubernetes. 
Can you provide an example of you tweeked deployments.yaml file?

**Comment by saghul** [comment]
PSA: https://github.com/jitsi/docker-jitsi-meet/issues/991

**Comment by rsoika** [comment]
My question was for @marner2 
I am still trying to get it working in my kubernetes cluster and if I succeed I would of course provide my results. But we also need a place to discuss....

**Comment by saghul** [comment]
Sorry, my message was not directed at you but rather at those who have an interest in the k8s setup in general, who might be following this thread.

**Comment by rsoika** [comment]
@saghul  I have no created a pull request containing a new concept of how to setup jitsi in kuberenetes with [Kustomize](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/).

https://github.com/jitsi/docker-jitsi-meet/pull/993

**Comment by marner2** [comment]
@rsoika where were you getting errors? The purpose of these instructions to allow for simplified community transformation of the `docker-compose.yml` file into something that works with kubernetes (since the jitsi organization is only managing the `docker-compose.yml` file)

Have you checked out [KOMPOSE.md](https://github.com/jitsi/docker-jitsi-meet/blob/83e06562e56f66d4986143422a0f6da378ea25e6/examples/kubernetes/KOMPOSE.md) in #990? It's more complete.

Here is a gist of [docker-compose.k8s.yml](https://gist.github.com/marner2/be4b8b4ac47ae4176e21d99d202a9c00#file-docker-compose-k8s-yml) that I transformed from the version of `[docker-compose.yml](https://github.com/jitsi/docker-jitsi-meet/blob/f4ec02329e1364f959640875b7f20a6a115681a5/docker-compose.yml)` that I had at the time. See if that clears anything up. It will be accurate until the jitsi team updates `[docker-compose.yml](https://github.com/jitsi/docker-jitsi-meet/blob/master/docker-compose.yml)` again.

**Comment by rsoika** [comment]
My problem is still to get websockets to work. I only succeeded if I disable the feature.
The goal with my pull request was, that I wanted to provide a clean kubernetes setup which can be customized based on the Kubernetes tool [Kustomize](https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/). This is something different to the [kompose tool](https://kompose.io/)

I think there is a problem with websockets and Ingress configuration via NGINX.  I have the problem with the endless redirect if websockets are activated. And I still did not figure out how to solve it. 

The [README.md](https://github.com/jitsi/docker-jitsi-meet/tree/fb23fb56b6cd8a74180ea2967563052981131e46/examples/kubernetes/kompose) file is telling something about exposing port 9090. In Kubernetes it would mean to create an additional service object. But how should this look like?

**Comment by marner2** [comment]
@rsoika all right, thanks for that. I think I had run across that trailing slash issue a long time ago and forgot how important it was. I'll update my Pull Request to mention that as well.

Are you running your prosody, web, jibri and jicofo on separate deployments, or all on the same pod with different containers? I think that makes a difference with the expose.

**Comment by rsoika** [comment]
Yes, I run all my containers in the same pod. This is an important hint I think, because as you mentioned, deployment across several pods needs more configuration on the services. 

I have created a new Pull Request with all my setup based on Kustomize and also a readme file explaining the deployment details.

https://github.com/jitsi/docker-jitsi-meet/pull/997

**Comment by saghul** [comment]
I'm leaning towards removing the k8s example and moving it to https://github.com/jitsi-contrib

Are there volunteers (@marner2 already volunteered and got added) that want to work on this over at jitsi-contrib?

**Comment by rsoika** [comment]
See the new repo for kubernetes: https://github.com/jitsi-contrib/jitsi-kubernetes
