### ISSUE TITLE
PSA: New GH org for community maintained 3rd party Jitsi projects

### ISSUE THREAD

**Issue by saghul** [jitsi/docker-jitsi-meet#991]
Hey all!

We just announced a thing: https://community.jitsi.org/t/introducing-the-jitsi-contrib-github-organization/96409

I think there are a number of people here that would he happy to contribute to a k8s setup, helm chart, etc. This new org could be a home for that.

If there is enough interest we could move the projects currently in examples/ to standalone projects in this new org, fully managed by the members of the community who choose to steer them.

Any feedback is welcome!

Thanks @sapkra for working with us in shaping this.

**Comment by saghul** [comment]
Perhaps a mention to this on the README here would be nice. Up for a PR?

**Comment by rsoika** [comment]
See: https://github.com/jitsi/docker-jitsi-meet/pull/998

**Comment by rsoika** [comment]
Note that I just renamed the repo form 'kubernetes' to 'jitsi-kubernetes' to avoid name conflicts

https://github.com/jitsi-contrib/jitsi-kubernetes

**Comment by saghul** [comment]
Closing since this issue has run its course. Further activity continues over at jitsi-contrib!
