### ISSUE TITLE
Add option to enable UNIX file sockets rather than TCP/IP

### ISSUE THREAD

**Issue by AquaL1te** [jitsi/docker-jitsi-meet#995]
As also mentioned in #962 (and again below), it would great if Jitsi can be configured to use UNIX file sockets to facilitate network connections. These can then be used by Nginx to proxy requests to. This is faster and more secure (because the TCP/IP stack is not reused). This is also more stable in my experience. Using Nginx to proxy to localhost:port is unstable, sometimes I have to restart Nginx after the Jitsi containers are started. I don't have this issue with Discourse, which uses these UNIX file sockets already. You may use that as a reference.

---

Best is to not use localhost:port for the proxy_pass. At least that's my experience. When I reboot and the Jitsi containers come up automatically, I have to restart Nginx to make it work. Probably because the socket wasn't created yet.

Discourse uses UNIX file socket to proxy towards, which works very stable! It's also a performance benefit, because you don't have to use the TCP/IP stack, this is also more secure.

Check their setup [here](https://meta.discourse.org/t/adding-an-offline-page-when-rebuilding/45238). It would be cool if there was an **environment variable to enable UNIX file sockets** for the external reachable things so that Nginx can simply do something like this, but then with Jitsi:

```
  location / {
    proxy_pass http://unix:/var/discourse/shared/standalone/nginx.http.sock:;
    proxy_set_header Host $http_host;
    proxy_http_version 1.1;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
```

**Comment by saghul** [comment]
I have never seen any problem proxying to localhost. We actually don't even do that, we proxy to a different container.

Can you share any reported issues on proxying to a local IP / port?

**Comment by AquaL1te** [comment]
> I have never seen any problem proxying to localhost. We actually don't even do that, we proxy to a different container.

The reason I don't proxy through containers, like e.g. with [Nginx Proxy Manager](https://nginxproxymanager.com/) is because I only have one /64 IPv6 subnet on my VPS. Since Docker requires its own /64 subnet and I don't have a /48 IPv6 subnet I use Nginx on the Docker host to proxy to this port.

> Can you share any reported issues on proxying to a local IP / port?

I'll troubleshoot a bit more. If I don't find any fix, I'll report the issue here in more detail.

**Comment by saghul** [comment]
Closing for now since there is nothing actionable.
