### ISSUE TITLE
Theming Jitsi (Docker installation)

### ISSUE THREAD

**Issue by AquaL1te** [jitsi/docker-jitsi-meet#996]
Hi,

When looking at threads like [this](https://community.jitsi.org/t/jitsi-meet-web-ui-customization/64960) it's clear that Jitsi can be themed, but only by modifying the source?

What would be a good method to do this when using Docker containers, which are stateless? My guess would be to create an extra overlay by importing the Jitsi web container in a Dockerfile and then make the adjustments. Then use that container in the docker-compose?

Or are there better suggestions? Thanks!

**Comment by saghul** [comment]
There is no theming available unless you go and modish the CSS source yourself.

There are some UI customizations you can apply my modifying interface_config.js, similar to the functionality that can be controlled from config.js.

**Comment by AquaL1te** [comment]
Thanks for your quick reply. I also saw the interface_config.js, but isn't this file generated? So in that sense it may change. It also points to images that are inside the Jitsi web container (/usr/share/jitsi-meet/images). So I cannot use this file to point to a file on the Docker host.

That's why I suggested that perhaps an overlay is needed. What I mean with that is that I import the official Jitsi web container as a base image, and then include my own stuff into the image so that I may point to other images in that file, which hopefully is static to a certain degree.

And then I only have to change the docker-compose so that it will use my custom Jitsi web image rather then the official. Is that more or less the way to go about this? It would work, but considering your first reply, I guess this is the way. Then my only question remains is about the interface_config.js file, will that change during it's lifetime? Thank you for your time.

**Comment by saghul** [comment]
You can have a custom file (-custom.js at the end of the name) mounted in your container and the content will be appended at the end of the default file.

The templating happens on every container boot.

**Comment by AquaL1te** [comment]
That's helpful to know, where did you find this information? Do you have a link? Then I might read more about it. I think my idea of an extra Docker container layer t to include custom images would still be needed. Because the interface_config.js has relative paths inside the container, so the images must be included there.
